/** Whitelist truy vấn đọc cho UI/AI (read-only, đã qua RLS). $1 = farm_id luôn. */
export const QUERIES: Record<string, { sql: string; params?: string[] }> = {
  tasks_today: { sql: "select t.*, s.full_name as assignee_name from tasks t left join staff s on s.id=t.assignee_id where t.farm_id=$1 and t.status in ('MO','DANG_LAM','TREO') and t.due_at <= now() + interval '2 days' order by case t.priority when 'KHAN' then 0 when 'CAO' then 1 when 'BINH_THUONG' then 2 else 3 end, t.due_at limit 300" },
  tasks_all: { sql: "select * from tasks where farm_id=$1 order by status, due_at desc limit 500" },
  shift_notes: { sql: "select n.*, s.full_name as by_name from shift_notes n left join staff s on s.id=n.created_by where n.farm_id=$1 and n.ts >= now()-interval '3 days' order by n.ts desc" },
  purchase_orders: { sql: "select po.*, p.name as supplier_name from purchase_orders po left join partners p on p.id=po.supplier_id where po.farm_id=$1 order by po.ts desc limit 100" },
  expense_requests: { sql: "select e.*, s.full_name as by_name from expense_requests e left join staff s on s.id=e.requested_by where e.farm_id=$1 order by e.ts desc limit 100" },
  price_list: { sql: "select * from price_list where (farm_id=$1 or farm_id is null) and (valid_to is null or valid_to>=current_date) order by kind, subject" },
  days_of_stock: { sql: "select * from v_days_of_stock where farm_id=$1 order by days nulls last" },
  animal_tags: { sql: "select * from animal_tags where farm_id=$1 and animal_id=$2 order by from_ts desc", params: ["code"] },
  hq_kpis: { sql: `select f.id as farm_id, f.name, f.region_id,
      (select conception_pct from v_kpi_conception k where k.farm_id=f.id) as conception_pct,
      (select weaned_per_dam from v_kpi_weaned_per_dam k where k.farm_id=f.id) as weaned_per_dam,
      (select days_silage from v_days_silage d where d.farm_id=f.id) as days_silage,
      (select avg(err_pct) from v_kpi_feed_accuracy a where a.farm_id=f.id and a.day>=current_date-7) as feed_err_pct,
      (select avg(lay_pct) from v_kpi_lay_rate l where l.farm_id=f.id and l.day>=current_date-7) as lay_pct,
      (select count(*) from tasks t where t.farm_id=f.id and t.status='MO' and t.due_at<now()) as overdue_tasks,
      (select count(*) from alerts a where a.farm_id=f.id and a.acked_at is null and a.level='DO') as red_alerts,
      (select coalesce(sum(amount),0) from sales s where s.farm_id=f.id and s.status='ACTIVE' and s.ts>=date_trunc('month',now())) as revenue_mtd,
      (select coalesce(sum(amount) filter (where not paid),0) from sales s where s.farm_id=f.id and s.status='ACTIVE') as receivable,
      (select count(*) from paper_scans p where p.farm_id=f.id and not p.digitized) as paper_pending
      from farms f order by f.id` },
  audit_anchors: { sql: "select * from audit_anchors where farm_id=$1 order by day desc, table_name limit 200" },
  governance: { sql: `select
      (select count(*) from recon_results r where r.farm_id=$1 and r.status in ('DO','VANG') and r.acked_by is null and r.ts < now()-interval '48 hours') as rc_hanging_48h,
      (select count(*) from paper_scans p where p.farm_id=$1 and not p.digitized and p.ts < now()-interval '24 hours') as paper_late,
      (select round(100.0*count(*) filter (where is_backfill)/nullif(count(*),0),1) from animal_events where farm_id=$1 and ts>=now()-interval '30 days') as backfill_pct_animal,
      (select round(100.0*count(*) filter (where is_backfill)/nullif(count(*),0),1) from feed_logs where farm_id=$1 and ts>=now()-interval '30 days') as backfill_pct_feed,
      (select count(*) from sales s join price_list pl on pl.subject=s.sku and pl.kind='SAN' where s.farm_id=$1 and s.status='ACTIVE' and s.price < pl.price and s.ts>=now()-interval '30 days') as sales_below_floor,
      (select count(*) from expense_requests e where e.farm_id=$1 and e.status='DUYET' and e.amount>2e7 and (e.approver2 is null)) as expense_missing_sig,
      (select count(*) from inventory_moves m where m.farm_id=$1 and m.status='ACTIVE' and m.reason='NHAP_MUA' and m.ts>=now()-interval '30 days' and not exists (select 1 from purchase_orders po where po.farm_id=$1 and po.po_status in ('DUYET','DA_NHAN') and po.lines::text like '%'||m.sku||'%')) as receipts_without_po,
      (select count(distinct s.partner_id) from sales s where s.farm_id=$1 and s.status='ACTIVE' and s.ts>=now()-interval '7 days' and s.partner_id in (select partner_id from sales x where x.farm_id=$1 and x.status='ACTIVE' and not x.paid group by partner_id having min(ts) < now()-interval '30 days')) as delivered_to_overdue,
      (select count(*) from staff st where st.farm_id=$1 and st.active and st.role='worker' and not exists (select 1 from animal_events e where e.created_by=st.id and e.ts>=now()-interval '7 days' union all select 1 from feed_logs f where f.created_by=st.id and f.ts>=now()-interval '7 days' union all select 1 from crop_logs c where c.created_by=st.id and c.ts>=now()-interval '7 days' union all select 1 from batch_logs b where b.created_by=st.id and b.ts>=now()-interval '7 days' union all select 1 from inventory_moves m where m.created_by=st.id and m.ts>=now()-interval '7 days' union all select 1 from checklist_runs k where k.created_by=st.id and k.ts>=now()-interval '7 days')) as workers_silent_7d,
      (select json_agg(row_to_json(x)) from (select date_part('hour', ts) as h, count(*) as n from (select ts from animal_events where farm_id=$1 and ts>=now()-interval '7 days' union all select ts from feed_logs where farm_id=$1 and ts>=now()-interval '7 days' union all select ts from inventory_moves where farm_id=$1 and ts>=now()-interval '7 days' union all select ts from crop_logs where farm_id=$1 and ts>=now()-interval '7 days' union all select ts from batch_logs where farm_id=$1 and ts>=now()-interval '7 days') u group by 1 order by 1) x) as hour_hist,
      (select json_agg(row_to_json(x)) from (select coalesce(s.full_name, e.created_by) as name, count(*) as n from (select created_by from animal_events where farm_id=$1 and ts>=now()-interval '7 days' union all select created_by from feed_logs where farm_id=$1 and ts>=now()-interval '7 days' union all select created_by from inventory_moves where farm_id=$1 and ts>=now()-interval '7 days' union all select created_by from crop_logs where farm_id=$1 and ts>=now()-interval '7 days' union all select created_by from batch_logs where farm_id=$1 and ts>=now()-interval '7 days' union all select created_by from checklist_runs where farm_id=$1 and ts>=now()-interval '7 days') e left join staff s on s.id=e.created_by group by 1 order by 2 desc) x) as by_staff,
      (select count(*) from farms) as farms_total,
      (select count(*) from settings where farm_id<>'GLOBAL') as farm_setting_overrides` },
  location_summary: { sql: "select * from v_location_summary where farm_id=$1 order by kind, name" },
  receivable_aging: { sql: "select * from v_receivable_aging where farm_id=$1 order by d30p desc nulls last" },
  cycles: { sql: "select c.*, g.name as group_name, p.name as plot_name from cycles c left join animal_groups g on g.id=c.group_id left join plots p on p.id=c.plot_id where c.farm_id=$1 order by c.status, c.start_date desc" },
  animal_parity: { sql: "select * from v_animal_parity where animal_id=$2", params: ["code"] },
  herd_daily: { sql: "select day, sum(head) as head, sum(value) as value from herd_daily where farm_id=$1 and day>=current_date-365 group by day order by day" },
  alerts_grouped: { sql: "select rule_code, level, count(*) as n, max(ts) as last_ts, min(ts) as first_ts, (array_agg(subject order by ts desc))[1] as last_subject, count(*) filter (where acked_at is null) as open from alerts where farm_id=$1 and ts>=now()-interval '30 days' group by rule_code, level order by open desc, last_ts desc" },
  period_locks: { sql: "select * from period_locks where farm_id=$1 order by period_end desc" },
  feed_plan_vs_actual: { sql: "select * from v_feed_plan_vs_actual where farm_id=$1 and day between current_date-7 and current_date+1 order by day desc, group_name" },
  season_plans: { sql: "select sp.*, p.name as plot_name, (select coalesce(sum(qty_kg),0) from crop_logs c where c.plot_id=sp.plot_id and c.status='ACTIVE' and c.activity in ('THU','CAT') and c.ts::date between coalesce(sp.sow_date, current_date-365) and coalesce(sp.harvest_date+30, current_date)) as actual_kg from season_plans sp join plots p on p.id=sp.plot_id where sp.farm_id=$1 order by sp.sow_date desc" },
  orders: { sql: "select o.*, p.name as partner_name from orders o left join partners p on p.id=o.partner_id where o.farm_id=$1 order by o.created_at desc limit 200" },
  contracts: { sql: "select c.*, p.name as partner_name, (select coalesce(sum(qty),0) from sales s where s.farm_id=c.farm_id and s.partner_id=c.partner_id and s.sku=c.sku and s.status='ACTIVE' and s.ts::date between coalesce(c.start_date,'2000-01-01') and coalesce(c.end_date,'2100-01-01')) as delivered from contracts c left join partners p on p.id=c.partner_id where c.farm_id=$1 order by c.status, c.end_date" },
  contract_coverage: { sql: "select coalesce(sum(c.qty_committed),0) as committed, (select coalesce(sum(qty),0) from sales s where s.farm_id=$1 and s.status='ACTIVE' and s.ts>=date_trunc('quarter',now())) as sold_q from contracts c where c.farm_id=$1 and c.status='HIEU_LUC'" },
  vet_board: { sql: "select * from v_vet_board where farm_id=$1 order by withdrawal_until desc nulls last" },
  vaccine_schedules: { sql: "select * from vaccine_schedules order by species, age_days_min" },
  treatment_protocols: { sql: "select * from treatment_protocols where active order by id" },
  drug_stock: { sql: "select b.*, l.expiry_date from v_stock_balance b left join lots l on l.id=b.lot_id join products p on p.sku=b.sku where b.farm_id=$1 and p.kind in ('THUOC','VACCINE','GIONG') order by p.kind, b.sku" },
  staff_activity: { sql: "select * from v_staff_activity where farm_id=$1 or farm_id is null order by role, id" },
  device_board: { sql: "select * from v_device_board where farm_id=$1 order by kind, id" },
  custody: { sql: "select cc.*, p.name as partner_name from custody_contracts cc left join partners p on p.id=cc.partner_id where cc.farm_id=$1 order by cc.created_at desc" },
  funds: { sql: "select f.*, case f.base when 'DOANH_THU' then (select coalesce(sum(amount),0) from sales s where s.farm_id=f.farm_id and s.status='ACTIVE' and s.ts>=date_trunc('year',now()))*f.pct/100 else null end as accrued_ytd from funds f where f.farm_id=$1" },
  job_runs: { sql: "select * from job_runs where farm_id=$1 or farm_id is null order by started_at desc limit 50" },
  stock_at: { sql: "select sd.*, p.name as product_name, w.code as warehouse_code from stock_daily sd join products p on p.sku=sd.sku join warehouses w on w.id=sd.warehouse_id where sd.farm_id=$1 and sd.day=$2::date order by w.code, sd.sku", params: ["day"] },
  po_all: { sql: "select po.*, p.name as supplier_name from purchase_orders po left join partners p on p.id=po.supplier_id where po.farm_id=$1 order by po.ts desc limit 100" },
  pl_cc: { sql: "select * from v_pl_cc_month where farm_id=$1 and month>=date_trunc('month',now())-interval '11 months' order by month desc, cc" },
  cc_fixed_costs: { sql: "select * from cc_fixed_costs where farm_id=$1 order by month desc, cost_center" },
  bank_lines: { sql: "select * from bank_statement_lines where farm_id=$1 order by txn_date desc limit 300" },
  staff_kpi: { sql: "select * from v_staff_kpi_month where farm_id=$1 and month=coalesce($2::date, date_trunc('month',now())::date) order by score desc", params: ["month"] },
  staff_kpi_history: { sql: "select month, round(avg(score)) as score from v_staff_kpi_month where farm_id=$1 group by month order by month" },
  location_grid: { sql: "select l.id, l.name, l.kind, l.grid_x, l.grid_y, l.color, s.head_individual, s.head_group, s.attention, s.open_tasks from locations l left join v_location_summary s on s.location_id=l.id where l.farm_id=$1 order by l.grid_y, l.grid_x" },
  customer_messages: { sql: "select m.*, c.partner_id, p.name as partner_name from customer_messages m left join custody_contracts c on c.id=m.contract_id left join partners p on p.id=c.partner_id where m.farm_id=$1 order by m.ts desc limit 200" },
  alert_rules: { sql: "select * from alert_rules where farm_id in ('GLOBAL',$1) order by active desc, code, version desc" },
  regions: { sql: "select * from regions order by id" },
  farm_settings: { sql: "select farm_id, key, value, version, updated_by, updated_at from settings where farm_id in ('GLOBAL',$1) order by key, (farm_id=$1) desc, version desc" },
  staff_all: { sql: "select id, full_name, role, dept, position, phone, farm_id, farm_ids, active from staff order by farm_id nulls first, role, id" },
  farms: { sql: "select f.*, r.name as region_name from farms f left join regions r on r.id=f.region_id order by f.id" },
  icfs_score: { sql: "select * from icfs_score($1)" }, icfs_summary: { sql: "select * from v_icfs_summary order by farm_id" },
  compliance: { sql: "select * from v_compliance where farm_id=$1" }, standards: { sql: "select * from standards where active order by position" }, standard_requirements: { sql: "select * from standard_requirements order by standard_code, id" },
  certifications: { sql: "select * from certifications where farm_id=$1 or farm_id is null order by valid_to desc nulls last" }, compliance_checks: { sql: "select * from compliance_checks where farm_id=$1 order by checked_at desc limit 500" },
  me: { sql: "select id, full_name, role, dept, position, position_code, farm_id, farm_ids from staff where id=app_staff()" },
  process_runs: { sql: "select * from v_process_runs where farm_id=$1 order by status='DANG_CHAY' desc, started_at desc limit 200" },
  process_run_steps: { sql: "select s.*, r.process_code from process_run_steps s join process_runs r on r.id=s.run_id where r.farm_id=$1 and r.status='DANG_CHAY' order by s.run_id, s.step_no" },
  process_coverage: { sql: "select * from v_process_coverage" },
  roles_catalog: { sql: "select * from roles_catalog order by position" }, positions_catalog: { sql: "select * from positions_catalog order by position" },
  species: { sql: "select * from species where active order by position" }, animal_classes: { sql: "select * from animal_classes order by species_code, position" }, crops: { sql: "select * from crops where active order by group_name, position" }, product_kinds: { sql: "select * from product_kinds order by position" },
  obj_people: { sql: "select * from v_obj_people order by farm_id, role" }, obj_animals: { sql: "select * from v_obj_animals where farm_id=$1 order by species, class_code" }, obj_crops: { sql: "select * from v_obj_crops where farm_id=$1 order by area_ha desc" }, obj_products: { sql: "select * from v_obj_products" },
  departments: { sql: "select * from departments where active order by position" },
  processes: { sql: "select p.*, d.name as dept_name, (select count(*) from process_steps x where x.process_code=p.code) as steps_n from processes p left join departments d on d.code=p.dept_code where p.active order by d.position, p.position, p.code" },
  process_steps: { sql: "select * from process_steps order by process_code, step_no" },
  dept_io: { sql: "select * from v_dept_io" },
  event_topics: { sql: "select * from event_topics order by wired desc, topic" },
  records_catalog: { sql: "select * from records_catalog order by position" },
  crop_dossier: { sql: "select * from v_crop_dossier where farm_id=$1 order by status, sow_date desc" },
  crop_inputs_recent: { sql: "select * from crop_inputs where farm_id=$1 and status='ACTIVE' order by ts desc limit 300" },
  harvests_recent: { sql: "select * from harvests where farm_id=$1 and status='ACTIVE' order by ts desc limit 300" },
  hosp_today: { sql: "select * from v_hosp_today where farm_id=$1" },
  hosp_rooms: { sql: "select r.*, t.name as type_name, t.base_price, t.capacity from hosp_rooms r left join hosp_room_types t on t.id=r.room_type_id where r.farm_id=$1 and r.active order by r.code" },
  hosp_room_types: { sql: "select * from hosp_room_types where farm_id=$1 and active order by code" },
  hosp_bookings: { sql: "select b.*, r.code as room_code from hosp_bookings b left join hosp_rooms r on r.id=b.room_id where b.farm_id=$1 and b.check_out >= current_date - 30 order by b.check_in desc limit 500" },
  hosp_events: { sql: "select e.*, m.name as menu_name from hosp_events e left join hosp_menus m on m.id=e.menu_id where e.farm_id=$1 and e.event_date >= current_date - 60 order by e.event_date" },
  hosp_services: { sql: "select * from hosp_services where farm_id=$1 and active order by kind, name" },
  hosp_menus: { sql: "select * from hosp_menus where farm_id=$1 and active order by name" },
  hosp_tours: { sql: "select t.*, s.name as service_name from hosp_tours t left join hosp_services s on s.id=t.service_id where t.farm_id=$1 and t.tour_date >= current_date - 7 order by t.tour_date, t.start_time" },
  hosp_folio: { sql: "select * from hosp_folio where farm_id=$1 and status='ACTIVE' order by ts desc limit 500" },
  hosp_occupancy: { sql: "select * from v_hosp_occupancy where farm_id=$1 and day >= current_date - 60 order by day" },
  crm_leads: { sql: "select l.*, s.full_name as owner_name from crm_leads l left join staff s on s.id=l.owner_id where (l.farm_id=$1 or l.farm_id is null) order by l.updated_at desc limit 500" },
  crm_pipeline: { sql: "select * from v_crm_pipeline where farm_id=$1 or farm_id is null" },
  crm_activities: { sql: "select * from crm_activities where (farm_id=$1 or farm_id is null) and status='ACTIVE' order by ts desc limit 300" },
  promotions: { sql: "select * from promotions where (farm_id=$1 or farm_id is null) order by active desc, ends_on desc" },
  sales_channels: { sql: "select * from sales_channels where active order by code" },
  pos_shifts: { sql: "select * from pos_shifts where farm_id=$1 order by opened_at desc limit 50" },
  pos_receipts: { sql: "select * from pos_receipts where farm_id=$1 and status='ACTIVE' order by ts desc limit 300" },
  sales_by_channel: { sql: "select coalesce(channel_code, 'KENH-'||channel::text) as channel_code, date_trunc('month', ts)::date as month, sum(amount) as amount, count(*) as n from sales where farm_id=$1 and status='ACTIVE' and ts >= now() - interval '12 months' group by 1,2 order by 2,1" },
  farm_profile: { sql: "select * from v_farm_profile where id=$1" },
  audit_recent: { sql: "select * from audit_log where (farm_id=$1 or farm_id is null) order by ts desc limit 200" },
  import_batches: { sql: "select * from import_batches where farm_id=$1 order by ts desc limit 100" },
  farm_summary: { sql: `select f.id, f.name, f.province,
      (select head_count from v_herd_value h where h.farm_id=f.id) as head_count,
      (select value from v_herd_value h where h.farm_id=f.id) as herd_value,
      (select days_silage from v_days_silage d where d.farm_id=f.id) as days_silage,
      (select count(*) from alerts a where a.farm_id=f.id and a.acked_at is null and a.level='DO') as red_alerts,
      (select count(*) from alerts a where a.farm_id=f.id and a.acked_at is null and a.level='VANG') as yellow_alerts,
      (select count(*) from recon_results r where r.farm_id=f.id and r.status<>'OK' and r.acked_by is null) as recon_open,
      (select coalesce(sum(amount),0) from sales s where s.farm_id=f.id and s.status='ACTIVE' and s.ts>=date_trunc('month',now())) as revenue_mtd
      from farms f order by f.id` },
  animals: { sql: "select a.*, g.name as group_name, l.name as location_name from animals a left join animal_groups g on g.id=a.group_id left join locations l on l.id=a.location_id where a.farm_id=$1 order by a.id" },
  animal: { sql: "select a.*, g.name as group_name, il.kind as intake_kind, il.date as intake_date, il.quarantine_until from animals a left join animal_groups g on g.id=a.group_id left join intake_lots il on il.id=a.intake_lot_id where a.farm_id=$1 and (a.id=$2 or a.rfid=$2 or a.visual_tag=$2 or a.qr_token=$2)", params: ["code"] },
  animal_events: { sql: "select e.*, s.full_name as by_name from animal_events e left join staff s on s.id=e.created_by where e.farm_id=$1 and (e.animal_id=$2 or e.group_id=$2) order by e.ts desc limit 200", params: ["code"] },
  animal_groups: { sql: "select g.*, l.name as location_name from animal_groups g left join locations l on l.id=g.location_id where g.farm_id=$1 order by g.id" },
  intake_lots: { sql: "select il.*, (select count(*) from animals a where a.intake_lot_id=il.id) as n from intake_lots il where il.farm_id=$1 order by date desc" },
  herd: { sql: "select * from v_herd where farm_id=$1 order by species, status" },
  herd_value: { sql: "select * from v_herd_value where farm_id=$1" },
  stock: { sql: "select * from v_stock_balance where farm_id=$1 and qty<>0 order by warehouse_code, sku, lot_id" },
  stock_ledger: { sql: "select * from v_stock_ledger where farm_id=$1 and sku=$2 order by ts desc limit 300", params: ["sku"] },
  days_silage: { sql: "select * from v_days_silage where farm_id=$1" },
  fefo_red: { sql: "select * from v_fefo_red where farm_id=$1" },
  material_balance: { sql: "select * from v_material_balance_week where farm_id=$1" },
  kpi_conception: { sql: "select * from v_kpi_conception where farm_id=$1" },
  kpi_weaned: { sql: "select * from v_kpi_weaned_per_dam where farm_id=$1" },
  kpi_feed_accuracy: { sql: "select * from v_kpi_feed_accuracy where farm_id=$1 order by day desc limit 30" },
  kpi_lay_rate: { sql: "select * from v_kpi_lay_rate where farm_id=$1 order by day desc limit 30" },
  kpi_defs: { sql: "select * from kpi_defs where active order by code" },
  alerts_open: { sql: "select * from alerts where farm_id=$1 and acked_at is null order by case level when 'DO' then 0 when 'CAM' then 1 when 'VANG' then 2 else 3 end, ts desc limit 100" },
  alerts_all: { sql: "select * from alerts where farm_id=$1 order by ts desc limit 200" },
  recon_latest: { sql: "select r.*, rr.name from recon_results r join rc_rules rr on rr.code=r.rule_code where r.farm_id=$1 and r.period=(select max(period) from recon_results x where x.farm_id=$1) order by r.rule_code" },
  recon_history: { sql: "select r.* from recon_results r where r.farm_id=$1 and r.rule_code=$2 order by period desc limit 60", params: ["rule"] },
  recipes: { sql: "select * from recipes where farm_id=$1 and active order by id" },
  recipe: { sql: "select * from recipes where farm_id=$1 and id=$2 order by version desc limit 1", params: ["id"] },
  plots: { sql: "select * from plots where farm_id=$1 order by id" },
  locations: { sql: "select * from locations where farm_id=$1 order by id" },
  warehouses: { sql: "select * from warehouses where farm_id=$1 order by code" },
  products: { sql: "select * from products where active order by kind, sku" },
  partners: { sql: "select * from partners where (farm_id=$1 or farm_id is null) and active order by kind, id" },
  devices: { sql: "select * from devices where farm_id=$1 order by id" },
  sops: { sql: "select s.*, v.version, v.steps, v.pass_criteria, v.review_due, v.status as vstatus from sops s left join lateral (select * from sop_versions v where v.sop_code=s.code order by version desc limit 1) v on true order by s.code" },
  sop: { sql: "select s.*, v.* from sops s join sop_versions v on v.sop_code=s.code where s.code=$2 order by v.version desc limit 1", params: ["code"] },
  checklist_today: { sql: "select * from checklist_runs where farm_id=$1 and ts::date=current_date order by ts desc" },
  feed_today: { sql: "select f.*, s.full_name as by_name from feed_logs f left join staff s on s.id=f.created_by where f.farm_id=$1 and f.ts::date=current_date order by f.ts desc" },
  events_recent: { sql: "select 'animal' as kind, id, ts, created_by, event_type as what, animal_id as who, source, is_backfill from animal_events where farm_id=$1 union all select 'feed', id, ts, created_by, 'FEED '||qty_kg||'kg', dest_location_id, source, is_backfill from feed_logs where farm_id=$1 union all select 'crop', id, ts, created_by, activity, plot_id, source, is_backfill from crop_logs where farm_id=$1 union all select 'batch', id, ts, created_by, line, batch_code, source, is_backfill from batch_logs where farm_id=$1 union all select 'move', id, ts, created_by, reason||' '||qty, sku, source, is_backfill from inventory_moves where farm_id=$1 order by ts desc limit 100" },
  paper_pending: { sql: "select * from paper_scans where farm_id=$1 and not digitized order by ts" },
  paper_all: { sql: "select * from paper_scans where farm_id=$1 order by ts desc limit 200" },
  adjustments_pending: { sql: "select * from adjustments where farm_id=$1 and adj_status='CHO_DUYET' order by ts" },
  incidents_open: { sql: "select * from incidents where farm_id=$1 and closed_at is null order by ts desc" },
  sales_recent: { sql: "select s.*, p.name as partner_name from sales s left join partners p on p.id=s.partner_id where s.farm_id=$1 order by s.ts desc limit 100" },
  receivables: { sql: "select p.id, p.name, sum(s.amount) filter (where not s.paid) as unpaid, min(s.ts) filter (where not s.paid) as oldest, extract(day from now()-min(s.ts) filter (where not s.paid))::int as days from sales s join partners p on p.id=s.partner_id where s.farm_id=$1 and s.status='ACTIVE' group by p.id, p.name having sum(s.amount) filter (where not s.paid) > 0 order by days desc" },
  trace_lot: { sql: `with recursive back as (select input_lot, output_lot, batch_code, 1 as depth from v_trace_links where farm_id=$1 and output_lot=$2 union select t.input_lot, t.output_lot, t.batch_code, b.depth+1 from v_trace_links t join back b on t.output_lot=b.input_lot where b.depth<6),
     fwd as (select input_lot, output_lot, batch_code, 1 as depth from v_trace_links where farm_id=$1 and input_lot=$2 union select t.input_lot, t.output_lot, t.batch_code, f.depth+1 from v_trace_links t join fwd f on t.input_lot=f.output_lot where f.depth<6)
     select 'BACK' as dir, * from back union all select 'FWD', * from fwd`, params: ["lot"] },
  trace_customers: { sql: "select s.ts, s.qty, s.unit, p.name, p.phone from sales s join partners p on p.id=s.partner_id where s.farm_id=$1 and s.status='ACTIVE' and s.lot_id=$2 order by s.ts", params: ["lot"] },
  lot: { sql: "select l.*, p.name as product_name from lots l join products p on p.sku=l.sku where l.farm_id=$1 and l.id=$2", params: ["lot"] },
  staff: { sql: "select id, full_name, role, dept, position, phone, farm_id, active from staff where farm_id=$1 or farm_id is null order by role, id" },
  settings: { sql: "select distinct on (key) key, value, farm_id from settings where farm_id in ('GLOBAL',$1) order by key, (farm_id=$1) desc, version desc" },
  norms: { sql: "select * from norms where farm_id=$1 or farm_id is null order by kind" },
  gate_today: { sql: "select * from gate_logs where farm_id=$1 and ts::date=current_date order by ts desc" },
  weekly_one_page: { sql: `select
      (select row_to_json(m) from v_material_balance_week m where m.farm_id=$1) as balance,
      (select row_to_json(d) from v_days_silage d where d.farm_id=$1) as silage,
      (select row_to_json(h) from v_herd_value h where h.farm_id=$1) as herd,
      (select json_agg(a) from (select rule_code, level, subject, ts from alerts where farm_id=$1 and level='DO' and ts>=now()-interval '7 days' order by ts desc limit 20) a) as red_week,
      (select json_agg(r) from (select rule_code, diff_pct, status, period from recon_results where farm_id=$1 and status<>'OK' and period>=current_date-7 order by period desc) r) as recon_week,
      (select coalesce(sum(amount),0) from sales where farm_id=$1 and status='ACTIVE' and ts>=now()-interval '7 days') as revenue_week,
      (select coalesce(sum(amount) filter (where not paid),0) from sales where farm_id=$1 and status='ACTIVE') as receivable,
      (select json_agg(i) from (select code, kind, severity, description, ts from incidents where farm_id=$1 and ts>=now()-interval '7 days' order by ts desc) i) as incidents_week` },
};
