/** Whitelist truy vấn đọc cho UI/AI (read-only, đã qua RLS). $1 = farm_id luôn. */
export const QUERIES: Record<string, { sql: string; params?: string[]; cache?: boolean; ttl?: number }> = {
  cache_status: { sql: "select farm_id, refreshed_at, (select dirty_at from cache_dirty d where d.farm_id=$1) as dirty_at from cache_kv where farm_id=$1 and key='warehouse_fill'" },
  // GOM việc lặp. Sinh việc đang tạo mỗi con một dòng ("Cân định kỳ 30 ngày — F01-BO-H015"),
  // nên một ghế ôm 120 dòng giống hệt nhau chỉ khác mã con vật. Công nhân cuộn không hết rồi
  // bỏ qua cả danh sách. Gom theo (luật sinh + phần đầu tiêu đề + người nhận + ngày đến hạn),
  // trả về `group_ids` để bấm ✓ Xong đóng trọn nhóm chỉ bằng MỘT lượt gọi.
  // Mã nghề lấy từ job_accounts (chỗ ngồi) chứ không dò regex trên chức danh tự do nữa.
  tasks_today: { sql: `with q as (
      select t.*, s.full_name as assignee_name,
             coalesce(t.rule_code,'') || '|' || split_part(t.title, ' — ', 1) || '|' || coalesce(t.assignee_id,'') || '|' || t.due_at::date as gk
        from tasks t left join staff s on s.id = t.assignee_id
       where t.farm_id = $1 and t.status in ('MO','DANG_LAM','TREO')
         and t.due_at <= now() + interval '2 days'
         and (t.assignee_id = app_staff()
              or t.role_hint is null
              or t.role_hint = app_role()
              or t.role_hint = 'worker:' || coalesce((select a.position_code from job_accounts a join account_holders h on h.account_code = a.code and h.to_date is null where h.staff_id = app_staff() limit 1), '~')
              or (t.role_hint like 'worker:%' and app_role() <> 'worker')
              or app_role() in ('tech_head','director','owner')))
    select (array_agg(id order by due_at, id))[1] as id,
           array_agg(id order by due_at, id) as group_ids,
           count(*)::int as group_n,
           case when count(*) > 1 then split_part(min(title), ' — ', 1) || ' — ' || count(*) || ' việc'
                else min(title) end as title,
           min(kind) as kind, min(due_at) as due_at, max(priority) as priority, min(status) as status,
           min(role_hint) as role_hint, min(sop_code) as sop_code, min(target_type) as target_type,
           case when count(*) > 1 then null else min(target_id) end as target_id,
           min(handover_note) as handover_note, min(assignee_id) as assignee_id, min(assignee_name) as assignee_name
      from q group by gk
     -- VIỆC ĐÍCH DANH (giao đúng mình) LUÔN NỔI trước, không bao giờ bị việc chung của bộ phận
     -- đẩy khỏi giới hạn 300. Đo được: a1 có 38 việc gán nhưng chỉ 9 lọt vì 291 việc chung
     -- chen trước — cả chỉ thị giao ca của trưởng nhóm cũng bị chôn. Đích danh đi đầu, rồi mới
     -- tới ưu tiên/hạn.
     order by (bool_or(assignee_id = app_staff())) desc,
              case max(priority) when 'KHAN' then 0 when 'CAO' then 1 when 'BINH_THUONG' then 2 else 3 end, min(due_at)
     limit 300` },
  tasks_all: { sql: "select * from tasks where farm_id=$1 order by status, due_at desc limit 500" },
  shift_notes: { sql: "select n.*, s.full_name as by_name from shift_notes n left join staff s on s.id=n.created_by where n.farm_id=$1 and n.ts >= now()-interval '3 days' order by n.ts desc" },
  purchase_orders: { sql: "select po.*, p.name as supplier_name from purchase_orders po left join partners p on p.id=po.supplier_id where po.farm_id=$1 order by po.ts desc limit 100" },
  expense_requests: { sql: "select e.*, s.full_name as by_name from expense_requests e left join staff s on s.id=e.requested_by where e.farm_id=$1 order by e.ts desc limit 100" },
  price_list: { sql: "select * from price_list where (farm_id=$1 or farm_id is null) and (valid_to is null or valid_to>=current_date) order by kind, subject" },
  days_of_stock: { sql: "select * from v_days_of_stock where farm_id=$1 order by days nulls last" },
  animal_tags: { sql: "select * from animal_tags where farm_id=$1 and animal_id=$2 order by from_ts desc", params: ["code"] },
  hq_kpis: { sql: `select f.id as farm_id, f.name, f.region_id,
      (select conception_pct from v_kpi_conception k where k.farm_id=f.id) as conception_pct,
      (select weaned_per_dam from v_kpi_weaned_per_dam k where k.farm_id=f.id) as weaned_per_dam,
      (select days_silage from v_days_silage d where d.farm_id=f.id) as days_silage,
      (select avg(err_pct) from v_kpi_feed_accuracy a where a.farm_id=f.id and a.day>=current_date-7) as feed_err_pct,
      (select avg(lay_pct) from v_kpi_lay_rate l where l.farm_id=f.id and l.day>=current_date-7) as lay_pct,
      (select count(*) from tasks t where t.farm_id=f.id and t.status='MO' and t.due_at<now()) as overdue_tasks,
      (select count(*) from alerts a where a.farm_id=f.id and a.acked_at is null and a.level='DO') as red_alerts,
      (select coalesce(sum(amount),0) from sales s where s.farm_id=f.id and s.status='ACTIVE' and s.ts>=date_trunc('month',now())) as revenue_mtd,
      (select coalesce(sum(amount) filter (where not paid),0) from sales s where s.farm_id=f.id and s.status='ACTIVE') as receivable,
      (select count(*) from paper_scans p where p.farm_id=f.id and not p.digitized) as paper_pending
      from farms f order by f.id` },
  audit_anchors: { sql: "select * from audit_anchors where farm_id=$1 order by day desc, table_name limit 200" },
  governance: { sql: `select
      (select count(*) from recon_results r where r.farm_id=$1 and r.status in ('DO','VANG') and r.acked_by is null and r.ts < now()-interval '48 hours') as rc_hanging_48h,
      (select count(*) from paper_scans p where p.farm_id=$1 and not p.digitized and p.ts < now()-interval '24 hours') as paper_late,
      (select round(100.0*count(*) filter (where is_backfill)/nullif(count(*),0),1) from animal_events where farm_id=$1 and ts>=now()-interval '30 days') as backfill_pct_animal,
      (select round(100.0*count(*) filter (where is_backfill)/nullif(count(*),0),1) from feed_logs where farm_id=$1 and ts>=now()-interval '30 days') as backfill_pct_feed,
      (select count(*) from sales s join price_list pl on pl.subject=s.sku and pl.kind='SAN' where s.farm_id=$1 and s.status='ACTIVE' and s.price < pl.price and s.ts>=now()-interval '30 days') as sales_below_floor,
      (select count(*) from expense_requests e where e.farm_id=$1 and e.status='DUYET' and e.amount>2e7 and (e.approver2 is null)) as expense_missing_sig,
      (select count(*) from inventory_moves m where m.farm_id=$1 and m.status='ACTIVE' and m.reason='NHAP_MUA' and m.ts>=now()-interval '30 days' and not exists (select 1 from purchase_orders po where po.farm_id=$1 and po.po_status in ('DUYET','DA_NHAN') and po.lines::text like '%'||m.sku||'%')) as receipts_without_po,
      (select count(distinct s.partner_id) from sales s where s.farm_id=$1 and s.status='ACTIVE' and s.ts>=now()-interval '7 days' and s.partner_id in (select partner_id from sales x where x.farm_id=$1 and x.status='ACTIVE' and not x.paid group by partner_id having min(ts) < now()-interval '30 days')) as delivered_to_overdue,
      (select count(*) from staff st where st.farm_id=$1 and st.active and st.role='worker' and not exists (select 1 from animal_events e where e.created_by=st.id and e.ts>=now()-interval '7 days' union all select 1 from feed_logs f where f.created_by=st.id and f.ts>=now()-interval '7 days' union all select 1 from crop_logs c where c.created_by=st.id and c.ts>=now()-interval '7 days' union all select 1 from batch_logs b where b.created_by=st.id and b.ts>=now()-interval '7 days' union all select 1 from inventory_moves m where m.created_by=st.id and m.ts>=now()-interval '7 days' union all select 1 from checklist_runs k where k.created_by=st.id and k.ts>=now()-interval '7 days')) as workers_silent_7d,
      (select json_agg(row_to_json(x)) from (select date_part('hour', ts) as h, count(*) as n from (select ts from animal_events where farm_id=$1 and ts>=now()-interval '7 days' union all select ts from feed_logs where farm_id=$1 and ts>=now()-interval '7 days' union all select ts from inventory_moves where farm_id=$1 and ts>=now()-interval '7 days' union all select ts from crop_logs where farm_id=$1 and ts>=now()-interval '7 days' union all select ts from batch_logs where farm_id=$1 and ts>=now()-interval '7 days') u group by 1 order by 1) x) as hour_hist,
      (select json_agg(row_to_json(x)) from (select coalesce(s.full_name, e.created_by) as name, count(*) as n from (select created_by from animal_events where farm_id=$1 and ts>=now()-interval '7 days' union all select created_by from feed_logs where farm_id=$1 and ts>=now()-interval '7 days' union all select created_by from inventory_moves where farm_id=$1 and ts>=now()-interval '7 days' union all select created_by from crop_logs where farm_id=$1 and ts>=now()-interval '7 days' union all select created_by from batch_logs where farm_id=$1 and ts>=now()-interval '7 days' union all select created_by from checklist_runs where farm_id=$1 and ts>=now()-interval '7 days') e left join staff s on s.id=e.created_by group by 1 order by 2 desc) x) as by_staff,
      (select count(*) from farms) as farms_total,
      (select count(*) from settings where farm_id<>'GLOBAL') as farm_setting_overrides` },
  location_summary: { sql: "select * from v_location_summary where farm_id=$1 order by kind, name" },
  receivable_aging: { sql: "select * from v_receivable_aging where farm_id=$1 order by d30p desc nulls last" },
  cycles: { sql: "select c.*, g.name as group_name, p.name as plot_name from cycles c left join animal_groups g on g.id=c.group_id left join plots p on p.id=c.plot_id where c.farm_id=$1 order by c.status, c.start_date desc" },
  animal_parity: { sql: "select * from v_animal_parity where animal_id=$2", params: ["code"] },
  herd_daily: { sql: "select day, sum(head) as head, sum(value) as value from herd_daily where farm_id=$1 and day>=current_date-365 group by day order by day" },
  alerts_grouped: { sql: "select rule_code, level, count(*) as n, max(ts) as last_ts, min(ts) as first_ts, (array_agg(subject order by ts desc))[1] as last_subject, count(*) filter (where acked_at is null) as open from alerts where farm_id=$1 and ts>=now()-interval '30 days' group by rule_code, level order by open desc, last_ts desc" },
  period_locks: { sql: "select * from period_locks where farm_id=$1 order by period_end desc" },
  feed_plan_vs_actual: { sql: "select * from v_feed_plan_vs_actual where farm_id=$1 and day between current_date-7 and current_date+1 order by day desc, group_name" },
  season_plans: { sql: "select sp.*, p.name as plot_name, (select coalesce(sum(qty_kg),0) from crop_logs c where c.plot_id=sp.plot_id and c.status='ACTIVE' and c.activity in ('THU','CAT') and c.ts::date between coalesce(sp.sow_date, current_date-365) and coalesce(sp.harvest_date+30, current_date)) as actual_kg from season_plans sp join plots p on p.id=sp.plot_id where sp.farm_id=$1 order by sp.sow_date desc" },
  orders: { sql: "select o.*, p.name as partner_name from orders o left join partners p on p.id=o.partner_id where o.farm_id=$1 order by o.created_at desc limit 200" },
  contracts: { sql: "select c.*, p.name as partner_name, (select coalesce(sum(qty),0) from sales s where s.farm_id=c.farm_id and s.partner_id=c.partner_id and s.sku=c.sku and s.status='ACTIVE' and s.ts::date between coalesce(c.start_date,'2000-01-01') and coalesce(c.end_date,'2100-01-01')) as delivered from contracts c left join partners p on p.id=c.partner_id where c.farm_id=$1 order by c.status, c.end_date" },
  contract_coverage: { sql: "select coalesce(sum(c.qty_committed),0) as committed, (select coalesce(sum(qty),0) from sales s where s.farm_id=$1 and s.status='ACTIVE' and s.ts>=date_trunc('quarter',now())) as sold_q from contracts c where c.farm_id=$1 and c.status='HIEU_LUC'" },
  vet_board: { sql: "select * from v_vet_board where farm_id=$1 order by withdrawal_until desc nulls last" },
  vaccine_schedules: { sql: "select * from vaccine_schedules order by species, age_days_min" },
  treatment_protocols: { sql: "select * from treatment_protocols where active order by id" },
  drug_stock: { sql: "select b.*, l.expiry_date from v_stock_balance b left join lots l on l.id=b.lot_id join products p on p.sku=b.sku where b.farm_id=$1 and p.kind in ('THUOC','VACCINE','GIONG') order by p.kind, b.sku" },
  staff_activity: { sql: "select * from v_staff_activity where farm_id=$1 or farm_id is null order by role, id" },
  device_board: { sql: "select * from v_device_board where farm_id=$1 order by kind, id" },
  custody: { sql: "select cc.*, p.name as partner_name from custody_contracts cc left join partners p on p.id=cc.partner_id where cc.farm_id=$1 order by cc.created_at desc" },
  funds: { sql: "select f.*, case f.base when 'DOANH_THU' then (select coalesce(sum(amount),0) from sales s where s.farm_id=f.farm_id and s.status='ACTIVE' and s.ts>=date_trunc('year',now()))*f.pct/100 else null end as accrued_ytd from funds f where f.farm_id=$1" },
  job_runs: { sql: "select * from job_runs where farm_id=$1 or farm_id is null order by started_at desc limit 50" },
  stock_at: { sql: "select sd.*, p.name as product_name, w.code as warehouse_code from stock_daily sd join products p on p.sku=sd.sku join warehouses w on w.id=sd.warehouse_id where sd.farm_id=$1 and sd.day=$2::date order by w.code, sd.sku", params: ["day"] },
  po_all: { sql: "select po.*, p.name as supplier_name from purchase_orders po left join partners p on p.id=po.supplier_id where po.farm_id=$1 order by po.ts desc limit 100" },
  pl_cc: { sql: "select * from v_pl_cc_month where farm_id=$1 and month>=date_trunc('month',now())-interval '11 months' order by month desc, cc" },
  cc_fixed_costs: { sql: "select * from cc_fixed_costs where farm_id=$1 order by month desc, cost_center" },
  bank_lines: { sql: "select * from bank_statement_lines where farm_id=$1 order by txn_date desc limit 300" },
  staff_kpi: { sql: "select * from v_staff_kpi_month where farm_id=$1 and month=coalesce($2::date, date_trunc('month',now())::date) order by score desc", params: ["month"] },
  staff_kpi_history: { sql: "select month, round(avg(score)) as score from v_staff_kpi_month where farm_id=$1 group by month order by month" },
  location_grid: { sql: "select l.id, l.name, l.kind, l.grid_x, l.grid_y, l.color, s.head_individual, s.head_group, s.attention, s.open_tasks from locations l left join v_location_summary s on s.location_id=l.id where l.farm_id=$1 order by l.grid_y, l.grid_x" },
  customer_messages: { sql: "select m.*, c.partner_id, p.name as partner_name from customer_messages m left join custody_contracts c on c.id=m.contract_id left join partners p on p.id=c.partner_id where m.farm_id=$1 order by m.ts desc limit 200" },
  alert_rules: { sql: "select * from alert_rules where farm_id in ('GLOBAL',$1) order by active desc, code, version desc" },
  regions: { sql: "select * from regions order by id" },
  farm_settings: { sql: "select farm_id, key, value, version, updated_by, updated_at from settings where farm_id in ('GLOBAL',$1) order by key, (farm_id=$1) desc, version desc" },
  staff_all: { sql: "select id, full_name, role, dept, position, phone, farm_id, farm_ids, active from staff order by farm_id nulls first, role, id" },
  farms: { sql: "select f.*, r.name as region_name from farms f left join regions r on r.id=f.region_id order by f.id" },
  icfs_score: { sql: "select * from icfs_score($1)" }, icfs_summary: { sql: "select * from v_icfs_summary order by farm_id" },
  compliance: { sql: "select * from v_compliance where farm_id=$1" }, standards: { sql: "select * from standards where active order by position" }, standard_requirements: { sql: "select * from standard_requirements order by standard_code, id" },
  certifications: { sql: "select * from certifications where farm_id=$1 or farm_id is null order by valid_to desc nulls last" }, compliance_checks: { sql: "select * from compliance_checks where farm_id=$1 order by checked_at desc limit 500" },
  variable_catalog: { sql: "select * from variable_catalog order by domain, position" },
  expenses_pending: { sql: "select * from expense_requests where farm_id=$1 and status in ('CHO_DUYET','DUYET_1') order by ts" },
  checklists_pending: { sql: "select * from checklist_runs where farm_id=$1 and status='ACTIVE' and approved_by is null order by ts desc limit 200" },
  po_pending: { sql: "select * from purchase_orders where farm_id=$1 and po_status in ('MOI','CHO_DUYET','NHAP') order by ts" },
  leave_pending: { sql: "select * from leave_requests where farm_id=$1 and status='CHO' order by created_at" },
  nc_open: { sql: "select * from compliance_checks where farm_id=$1 and result='KHONG_DAT' and closed_at is null order by checked_at desc" },
  attendance_month: { sql: "select a.*, s.full_name from v_attendance_month a join staff s on s.id=a.staff_id where a.farm_id=$1 and a.month >= date_trunc('month', now()) - interval '2 months' order by month desc, staff_id" },
  attendance_today: { sql: "select a.*, s.full_name from attendance a join staff s on s.id=a.staff_id where a.farm_id=$1 and a.day=current_date order by check_in" },
  grade_scales: { sql: "select * from grade_scales where active order by track, rank" },
  staff_grades_all: { sql: "select g.*, s.full_name, s.dept, s.position, (grade_eligibility($1, g.staff_id, g.track)->>'next') as next_grade, (grade_eligibility($1, g.staff_id, g.track)->>'pct') as next_pct from staff_grades g join staff s on s.id=g.staff_id where g.until is null and (g.farm_id=$1 or s.farm_id is null) and s.active order by g.track, s.dept, s.full_name", ttl: 120 },
  grade_reviews: { sql: "select r.*, s.full_name, s.dept from grade_reviews r join staff s on s.id=r.staff_id where r.farm_id=$1 order by r.status='DE_XUAT' desc, r.created_at desc limit 300" },
  my_path: { sql: "select grade_eligibility($1, app_staff(), $2) as e", params: ["track"] },
  gs_coverage_me: { sql: "select * from gs_coverage_done($1, app_staff()) where current_grade(app_staff(),'GS') is not null" },
  gs_coverage_all: { sql: "select s.id as staff_id, s.full_name, s.dept, current_grade(s.id,'GS') as grade_gs, c.* from staff s cross join lateral gs_coverage_done($1, s.id) c where s.active and current_grade(s.id,'GS') is not null order by s.full_name, c.block", ttl: 60 },
  supervisor_ratings: { sql: "select supervisor_id, round(avg((useful+fair+knows)/3.0),2) as avg, count(*) as n from supervisor_ratings where farm_id=$1 and created_at > now() - interval '6 months' group by 1" },
  succession: { sql: "select * from v_succession where farm_id=$1 order by n_successors, title" },
  contribution: { sql: "select *, round(kpi_pts+sup_pts+teach_pts+init_pts+cover_pts) as total from v_contribution where farm_id=$1 or farm_id is null order by total desc limit 200", ttl: 120 },
  my_contribution: { sql: "select * from v_contribution where staff_id=app_staff()" },
  initiatives: { sql: "select i.*, s.full_name from initiatives i join staff s on s.id=i.staff_id where i.farm_id=$1 order by i.created_at desc limit 200" },
  capa_status: { sql: "select * from v_capa_status where farm_id=$1 order by week_start desc, dept" },
  repeat_faults: { sql: "select * from v_repeat_faults where farm_id=$1 order by weeks desc" },
  faults_week: { sql: "select c.*, s.full_name as target_name, cr.name as criteria_name from supervision_checks c left join staff s on s.id=c.target_staff_id left join supervision_criteria cr on cr.id=c.criteria_id where c.farm_id=$1 and c.result='LOI' and c.week_start >= date_trunc('week', current_date)::date - 7 order by c.ts desc" },
  my_field_days: { sql: "select * from gs_field_days where farm_id=$1 and supervisor_id=app_staff() order by day desc limit 30" },
  gs_list: { sql: "select s.id, s.full_name, current_grade(s.id,'GS') as grade_gs from staff s where s.active and current_grade(s.id,'GS') is not null order by s.full_name" },
  my_pay_estimate: { sql: "select pay_estimate($1, app_staff()) as e" },
  my_payslips: { sql: "select month, work_days, base_salary, salary_by_days, kpi_bonus, allowances, other_add, gross, ins_salary, bhxh, bhyt, bhtn, taxable, pit, advances, net, employer_ins from payslips where farm_id=$1 and staff_id=app_staff() order by month desc limit 12" },
  pit_brackets: { sql: "select * from v_pit_brackets order by bac" },
  my_dependent_claims: { sql: "select * from dependent_claims where farm_id=$1 and staff_id=app_staff() order by created_at desc limit 5" },
  dependent_claims_pending: { sql: "select d.*, s.full_name from dependent_claims d join staff s on s.id=d.staff_id where d.farm_id=$1 and d.status='CHO' order by d.created_at" },
  pay_settings: { sql: "select distinct on (key) key, value, farm_id, version from settings where farm_id in ('GLOBAL',$1) and (key like 'payroll.%' or key like 'bonus.%' or key like 'gs.%' or key like 'pay.%' or key like 'contrib.%' or key like 'grade.%' or key like 'supervision.%' or key like 'training.%') order by key, (farm_id=$1) desc, version desc" },
  mkt_campaigns: { sql: "select * from v_campaign_perf where farm_id=$1 order by starts_on desc" },
  mkt_contents: { sql: "select k.*, c.name as campaign_name, a.full_name as author_name, ap.full_name as approver_name from mkt_contents k left join mkt_campaigns c on c.id=k.campaign_id left join staff a on a.id=k.author_id left join staff ap on ap.id=k.approved_by where k.farm_id=$1 and k.planned_at >= current_date - 120 order by k.planned_at" },
  mkt_weekly: { sql: "select * from v_mkt_weekly where farm_id=$1 order by week" },
  mkt_assets: { sql: "select * from mkt_assets where farm_id=$1 order by approved desc, kind, title" },
  mkt_mentions: { sql: "select m.*, h.full_name as handler_name from mkt_mentions m left join staff h on h.id=m.handler_id where m.farm_id=$1 order by m.status='MOI' desc, m.ts desc limit 200" },
  record_for_table: { sql: "select * from v_record_for_table" },
  labor_budget: { sql: "select * from v_labor_budget_vs_actual where farm_id=$1 order by month", ttl: 120 },
  order_margin: { sql: "select * from v_order_margin where farm_id=$1 and revenue>0 order by ts desc limit 300", ttl: 60 },
  qc_holds: { sql: "select * from qc_holds where farm_id=$1 order by status='GIU' desc, held_at desc limit 200" },
  supplier_returns: { sql: "select r.*, p.name as supplier_name from supplier_returns r left join partners p on p.id=r.supplier_id where r.farm_id=$1 order by r.status='CHO' desc, r.created_at desc limit 200" },
  bank_recon: { sql: "select * from v_bank_reconciliation where farm_id=$1 order by txn_date desc limit 400" },
  sop_signoff: { sql: "select * from v_sop_signoff where dept is not null order by (need-signed) desc, dept limit 300" },
  my_sop_todo: { sql: "select code, title, dept, version, video_url from v_sop_signoff where (dept = (select dept from staff where id=app_staff()) or dept is null) and not exists (select 1 from sop_acknowledgments a where a.sop_code=v_sop_signoff.code and a.staff_id=app_staff() and a.kind='DOC_HIEU') order by code limit 100" },
  lots_sellable: { sql: "select id, sku, lot_no, status, expiry_date from lots where farm_id=$1 and status in ('KHA_DUNG','GIU_QC','CO_LAP') order by status='GIU_QC' desc, expiry_date limit 200" },
  reading_latest: { sql: "select * from v_reading_latest where farm_id=$1 order by is_anomaly desc, code", ttl: 60 },
  reading_due: { sql: "select * from v_reading_due where farm_id=$1 order by due desc, metric_name", ttl: 60 },
  reading_metrics: { sql: "select m.id, m.code, m.name, m.unit, m.kind, m.facility_id, f.name as facility_name from reading_metrics m left join facilities f on f.id=m.facility_id where m.farm_id=$1 and m.active order by f.name, m.name" },
  reading_anomalies: { sql: "select r.id, r.ts, r.value, r.unit, r.delta, r.anomaly_reason, r.paper_serial, m.name as metric_name, f.name as facility_name from device_readings r join reading_metrics m on m.id=r.metric_id left join facilities f on f.id=m.facility_id where r.farm_id=$1 and r.is_anomaly order by r.ts desc limit 10", ttl: 60 },
  recording_due: { sql: "select * from v_recording_due where farm_id=$1 order by (level='ESCALATE') desc, (level='DUE') desc, hours_late desc", ttl: 60 },
  recording_compliance: { sql: "select * from v_recording_compliance where farm_id=$1 order by misses_30d desc, name", ttl: 120 },
  control_coverage: { sql: "select * from control_coverage($1) order by blind desc, days_since desc", ttl: 120 },
  gs_today: { sql: "select gs_today($1, app_staff()) as t" },
  gs_omissions_all: { sql: "select o.*, s.full_name from gs_omissions o join staff s on s.id=o.supervisor_id where o.farm_id=$1 order by o.day desc limit 300" },
  pay_structure: { sql: "select * from v_pay_structure where farm_id=$1 or farm_id is null order by dept, full_name", ttl: 120 },
  my_pay: { sql: "select * from v_pay_structure where staff_id=app_staff()" },
  salary_scales: { sql: "select * from salary_scales where active order by scope_kind desc, scope_code" },
  headcount: { sql: "select * from v_headcount where farm_id=$1 order by year desc, dept, position_code" },
  contribution_bonus: { sql: "select b.*, s.full_name from bonus_ledger b join staff s on s.id=b.staff_id where b.farm_id=$1 and b.kind in ('THUONG_QUY','THUONG_NAM') order by b.created_at desc limit 200" },
  collusion_pairs: { sql: "select * from v_collusion_pairs where farm_id=$1 order by level='DO' desc, n_signals desc", ttl: 300 },
  collusion_signals: { sql: "select v.*, s.full_name as supervisor_name from v_collusion_signals v left join staff s on s.id=v.supervisor_id where v.farm_id=$1 order by v.week_start desc, v.severity", ttl: 300 },
  my_cross_checks: { sql: "select x.*, c.item, c.note as original_note, cr.name as criteria_name, s.full_name as target_name from cross_checks x join supervision_checks c on c.id=x.original_check_id left join supervision_criteria cr on cr.id=x.criteria_id left join staff s on s.id=x.target_staff_id where x.farm_id=$1 and x.checker_id=app_staff() and x.status='MO' order by x.created_at" },
  cross_checks_all: { sql: "select x.*, o.full_name as original_name, k.full_name as checker_name from cross_checks x left join staff o on o.id=x.original_supervisor left join staff k on k.id=x.checker_id where x.farm_id=$1 order by x.created_at desc limit 200" },
  whistle_reports: { sql: "select id, farm_id, created_at, category, target_dept, content, status, handled_by, handled_at, note from whistle_reports where farm_id=$1 order by status='MOI' desc, created_at desc limit 200" },
  my_inbox: { sql: "select * from (select * from my_inbox($1, app_staff(), app_role()) union all select * from my_inbox_gs($1, app_staff())) x order by case priority when 'KHAN' then 0 when 'CAO' then 1 when 'BINH_THUONG' then 2 else 3 end, due_at nulls last limit 400", ttl: 20 },
  my_inbox_counts: { sql: "select kind, count(*)::int as n, min(due_at) as first_due from (select * from my_inbox($1, app_staff(), app_role()) union all select * from my_inbox_gs($1, app_staff())) x group by 1", ttl: 20 },
  suggest_delegates: { sql: "select * from suggest_delegates($1, coalesce(nullif($2,''), app_staff()), $3::date, $4::date)", params: ["staff", "from", "to"] },
  my_delegations: { sql: "select d.*, f.full_name as from_name, t.full_name as to_name from staff_delegations d join staff f on f.id=d.from_staff join staff t on t.id=d.to_staff where d.farm_id=$1 and (d.from_staff=app_staff() or d.to_staff=app_staff() or app_role() in ('owner','director','tech_head','team_lead','accountant')) order by d.status='ACTIVE' desc, d.from_date desc limit 100" },
  dept_discipline: { sql: "select * from v_dept_discipline where farm_id=$1 order by overdue desc", ttl: 60 },
  my_attendance: { sql: "select * from attendance where farm_id=$1 and staff_id=app_staff() order by day desc limit 40" },
  leave_all: { sql: "select l.*, s.full_name from leave_requests l join staff s on s.id=l.staff_id where l.farm_id=$1 order by created_at desc limit 200" },
  gl_trial_balance: { sql: "select * from v_gl_trial_balance where farm_id=$1 and period >= date_trunc('month', now()) - interval '3 months' order by period desc, acct" },
  gl_ledger: { sql: "select * from v_gl_ledger where farm_id=$1 order by ts desc limit 500" },
  gl_accounts: { sql: "select * from gl_accounts where active order by code" },
  ghg_month: { sql: "select * from v_ghg_month where farm_id=$1 order by month desc, species" },
  monitoring_due: { sql: "select * from v_monitoring_due where farm_id=$1 limit 500" },
  animal_monitoring: { sql: "select * from v_animal_monitoring where farm_id=$1 and animal_id=$2 order by due_date", params: ["animal"] },
  monitoring_params: { sql: "select * from monitoring_params where active order by species_code, position" },
  sales_returns: { sql: "select r.*, pt.name as partner_name from sales_returns r left join partners pt on pt.id=r.partner_id where r.farm_id=$1 order by r.ts desc limit 300" },
  returns_pending: { sql: "select * from sales_returns where farm_id=$1 and status='MOI' order by ts" },
  production_orders: { sql: "select * from production_orders where farm_id=$1 order by created_at desc limit 200" },
  batch_cost: { sql: "select * from v_batch_cost where farm_id=$1 order by ts desc limit 200" },
  picking: { sql: "select * from v_picking where farm_id=$1 and order_id=$2", params: ["order"] },
  stock_available: { sql: "select * from v_stock_available where farm_id=$1 order by warehouse_code, sku, expiry_date" },
  payroll_runs: { sql: "select * from payroll_runs where farm_id=$1 order by month desc" },
  payslips: { sql: "select p.*, s.full_name from payslips p join staff s on s.id=p.staff_id where p.farm_id=$1 and p.month=$2::date order by p.net desc", params: ["month"] },
  fixed_assets: { sql: "select * from v_fixed_assets where farm_id=$1 order by start_date desc" },
  pedigree: { sql: "select * from pedigree($2, 4) where $1::text is not null", params: ["animal"] }, descendants: { sql: "select * from descendants($2, 4) where $1::text is not null", params: ["animal"] },
  inbreeding: { sql: "select inbreeding_risk($2,$3) as risk where $1::text is not null", params: ["animal", "mate"] },
  epi_region_sum: { sql: "select * from v_epi_region_sum order by region_id" }, epi_region: { sql: "select * from v_epi_region order by region_id, farm_id" },
  budget_vs_actual: { sql: "select * from v_budget_vs_actual where farm_id=$1 order by year desc, month, cc, kind" },
  cashflow_forecast: { sql: "select * from v_cashflow_forecast where farm_id=$1 order by week_start" },
  cost_centers: { sql: "select * from cost_centers where farm_id=$1 and coalesce(active,true) order by id" },
  standard_requirements_all: { sql: "select id, standard_code, clause, title, level from standard_requirements order by standard_code, clause" },
  compliance_coverage: { sql: "select * from v_compliance_coverage" },
  controls: { sql: "select c.*, (select count(*) from clause_controls cc where cc.control_id=c.id) as clauses from controls c where active order by id" },
  clause_controls: { sql: "select cc.*, r.standard_code, r.clause, r.title from clause_controls cc join standard_requirements r on r.id=cc.requirement_id" },
  compliance_gaps: { sql: "select g.*, r.standard_code, r.clause, r.title, r.level from compliance_gaps g join standard_requirements r on r.id=g.requirement_id where g.status<>'DONG' order by r.level, r.standard_code" },
  sop_library: { sql: "select s.*, p.name as l2_name, p.organ, p.dept_code from sops s left join processes p on p.code=s.l2_code order by s.l1_chain, s.l2_code, s.l3_no, s.code" },
  me: { sql: "select id, full_name, role, dept, position, position_code, farm_id, farm_ids from staff where id=app_staff()" },
  process_runs: { sql: "select * from v_process_runs where farm_id=$1 order by status='DANG_CHAY' desc, started_at desc limit 200" },
  process_run_steps: { sql: "select s.*, r.process_code from process_run_steps s join process_runs r on r.id=s.run_id where r.farm_id=$1 and r.status='DANG_CHAY' order by s.run_id, s.step_no" },
  process_coverage: { sql: "select * from v_process_coverage" },
  roles_catalog: { sql: "select * from roles_catalog order by position" }, positions_catalog: { sql: "select * from positions_catalog order by position" },
  species: { sql: "select * from species where active order by position" }, animal_classes: { sql: "select * from animal_classes order by species_code, position" }, crops: { sql: "select * from crops where active order by group_name, position" }, product_kinds: { sql: "select * from product_kinds order by position" },
  obj_people: { sql: "select * from v_obj_people order by farm_id, role" }, obj_animals: { sql: "select * from v_obj_animals where farm_id=$1 order by species, class_code" }, obj_crops: { sql: "select * from v_obj_crops where farm_id=$1 order by area_ha desc" }, obj_products: { sql: "select * from v_obj_products" },
  departments: { sql: "select * from departments where active order by position" },
  processes: { sql: "select p.*, d.name as dept_name, (select count(*) from process_steps x where x.process_code=p.code) as steps_n from processes p left join departments d on d.code=p.dept_code where p.active order by d.position, p.position, p.code" },
  process_steps: { sql: "select * from process_steps order by process_code, step_no" },
  dept_io: { sql: "select * from v_dept_io" },
  event_topics: { sql: "select * from event_topics order by wired desc, topic" },
  records_catalog: { sql: "select * from records_catalog order by position" },
  crop_dossier: { sql: "select * from v_crop_dossier where farm_id=$1 order by status, sow_date desc" },
  po_list: { sql: "select p.*, pt.name as supplier_name, s.full_name as created_name from purchase_orders p left join partners pt on pt.id=p.supplier_id left join staff s on s.id=p.created_by where p.farm_id=$1 order by p.ts desc limit 300" },
  po_suggest: { sql: "select 'ROP' as src, sku, product_name, suggest_qty as qty, supplier_name, preferred_supplier_id as supplier_id, lead_time_days as lead from v_replenishment where farm_id=$1 and suggest_qty>0 union all select 'MRP', component_sku, component_name, shortage, null, null, null from mrp_run($1, 14) where shortage>0 and not exists (select 1 from bom_headers b where b.farm_id=$1 and b.sku=component_sku and b.status='BAN_HANH') union all select 'DU_TRU', sku, name, need_qty, null, null, lead from v_stock_dashboard where farm_id=$1 and need_qty>0 and block='DAU_VAO' order by 4 desc" },
  purchases_month: { sql: "select to_char(m.ts,'YYYY-MM') as month, p.stock_group, g.name as group_name, sum(m.qty) as qty, sum(m.qty*coalesce(m.unit_cost,0)) as amount from inventory_moves m join products p on p.sku=m.sku left join stock_groups g on g.code=p.stock_group where m.farm_id=$1 and m.status='ACTIVE' and m.direction=1 and m.reason='NHAP_MUA' and m.ts>now()-interval '13 months' group by 1,2,3 order by 1" },
  stock_groups: { sql: "select g.*, (select count(*) from products p where p.stock_group=g.code and p.active) as n_items, (select count(*) from products p where p.stock_group=g.code and p.active and p.reserve) as n_reserve from stock_groups g order by g.position" },
  reserve_catalog: { sql: "select p.sku, p.name, p.unit, p.kind, p.stock_group, p.reserve, p.shelf_life_days from products p where p.active and p.kind not in ('DICH_VU','CONG_CU') order by p.stock_group, p.name" },
  stock_projection: { sql: "select * from stock_projection($1, $2, coalesce($3::int, 90))", params: ["sku", "days"] },
  herd_forecast_series: { sql: "select x.* from cache_kv k, jsonb_to_recordset(k.payload) as x(horizon int, class_code text, class_name text, head_now numeric, head_forecast numeric, births numeric, exits numeric) where k.farm_id=$1 and k.key='herd_forecast_series' order by class_code, horizon", cache: true },
  feed_forecast_series: { sql: "select x.* from cache_kv k, jsonb_to_recordset(k.payload) as x(horizon int, kg_day numeric, head numeric) where k.farm_id=$1 and k.key='feed_forecast_series' order by horizon", cache: true },
  my_supervision: { sql: "select a.*, coalesce(a.target_dept, s.full_name) as target_label from supervision_assignments a left join staff s on s.id=a.target_staff_id where a.farm_id=$1 and a.active and (a.supervisor_id=app_staff() or app_role() in ('owner','director','auditor','it_engineer')) order by a.id" },
  supervision_targets: { sql: "select s.id, s.full_name, s.dept, s.position_code, s.role from staff s join supervision_assignments a on a.farm_id=s.farm_id and a.active and (a.target_staff_id=s.id or (a.target_staff_id is null and (a.target_dept=s.dept or a.target_dept is null))) where s.farm_id=$1 and s.active and s.role in ('worker','team_lead','tech_head') and (a.supervisor_id=app_staff() or app_role() in ('owner','director','auditor','it_engineer')) group by s.id order by s.dept, s.id" },
  supervision_criteria: { sql: "select * from supervision_criteria where active order by position, id" },
  supervision_week: { sql: "select ss.*, c.name as criteria_name, c.method as cmethod, st.full_name, st.dept, st.position_code from supervision_scores ss join supervision_criteria c on c.id=ss.criteria_id join staff st on st.id=ss.staff_id where ss.farm_id=$1 and ss.week_start=coalesce(nullif($2,'')::date, date_trunc('week', current_date)::date) order by st.dept, st.id, c.position", params: ["week"] },
  supervision_weekly: { sql: "select * from v_supervision_weekly where farm_id=$1 and week_start >= current_date - 100 order by week_start desc, dept, staff_id" },
  supervision_dept_weekly: { sql: "select * from v_supervision_dept_weekly where farm_id=$1 and week_start >= current_date - 100 order by week_start, dept" },
  supervision_checks_recent: { sql: "select sc.*, s.full_name as target_name, sv.full_name as supervisor_name from supervision_checks sc left join staff s on s.id=sc.target_staff_id left join staff sv on sv.id=sc.supervisor_id where sc.farm_id=$1 and sc.status='ACTIVE' order by sc.ts desc limit 200" },
  my_training: { sql: "select t.*, tr.full_name as trainer_name, te.full_name as trainee_name, (select score from training_tests x where x.session_id=t.id order by taken_at desc limit 1) as score from training_sessions t join staff tr on tr.id=t.trainer_id join staff te on te.id=t.trainee_id where t.farm_id=$1 and (t.trainer_id=app_staff() or t.trainee_id=app_staff() or app_role() in ('owner','director','tech_head','it_engineer','accountant','auditor')) and t.week_start >= current_date - 60 order by t.week_start desc, t.trainee_id" },
  training_stats: { sql: "select to_char(week_start,'IYYY-IW') as wk, week_start, count(*) as planned, count(*) filter (where status='XONG') as done, round(avg((select score from training_tests x where x.session_id=t.id limit 1)),1) as avg_score from training_sessions t where farm_id=$1 and week_start >= current_date - 180 group by 1,2 order by 2" },
  competency_matrix: { sql: "select vc.staff_id, vc.full_name, vc.dept, count(*) as n_sop, count(*) filter (where level in ('THUAN_THUC','DAY_DUOC')) as mastered, count(*) filter (where level='THUC_HANH') as practicing, count(*) filter (where level='CHUA_HOC') as not_started, round(100.0*count(*) filter (where level in ('THUAN_THUC','DAY_DUOC'))/count(*),0) as pct from v_training_curriculum vc where vc.farm_id=$1 group by 1,2,3 order by pct desc" },
  bonus_eval: { sql: "select * from bonus_eval($1, coalesce(nullif($2,''), to_char(current_date,'YYYY-MM')))", params: ["period"] },
  bonus_ledger: { sql: "select b.*, s.full_name from bonus_ledger b join staff s on s.id=b.staff_id where b.farm_id=$1 order by b.period desc, b.staff_id" },
  stock_dashboard: { sql: "select * from cache_stock_dashboard where farm_id=$1 order by block, case flag when 'HET' then 0 when 'THIEU_SOM' then 1 when 'CHAM_ROP' then 2 when 'AM_30_NGAY' then 3 else 9 end, days_left nulls last" },
  warehouse_fill: { sql: "select x.* from cache_kv k, jsonb_to_recordset(k.payload) as x(farm_id text, warehouse_id text, code text, name text, block text, area text, unit_kind text, capacity numeric, qty numeric, pct_full numeric, skus int, bins int) where k.farm_id=$1 and k.key='warehouse_fill' order by block, code", cache: true },
  tool_stock: { sql: "select * from v_tool_stock where farm_id=$1 order by warehouse_code, tool_group, name" },
  tool_issued: { sql: "select * from v_tool_issued where farm_id=$1 order by overdue desc, issued_at desc" },
  tool_catalog: { sql: "select sku, name, unit, tool_group, life_months, ref_price, needs_cert from products where kind='CONG_CU' and active order by tool_group, name" },
  tool_history: { sql: "select t.*, p.name as tool_name, s.full_name as staff_name from tool_issues t join products p on p.sku=t.sku left join staff s on s.id=t.staff_id where t.farm_id=$1 order by t.issued_at desc limit 200" },
  bio_batches: { sql: "select b.* from batch_logs b where b.farm_id=$1 and b.status='ACTIVE' and b.line in ('TRUN_NAP','TRUN_THU','BSF','BIOGAS','COMPOST','IMO_EM','ANOLYTE') order by b.ts desc limit 600" },
  bio_beds: { sql: "select l.id, l.name, (select max(ts) from batch_logs b where b.location_id=l.id and b.line='TRUN_NAP') as last_nap, (select max(ts) from batch_logs b where b.location_id=l.id and b.line='TRUN_THU') as last_thu, (select temp_c from batch_logs b where b.location_id=l.id and b.temp_c is not null order by ts desc limit 1) as temp_c, (select count(*) from batch_logs b where b.location_id=l.id and b.ts>now()-interval '30 days') as n30 from locations l where l.farm_id=$1 and (l.kind='O' or l.id like '%-TR-%' or l.id like '%-KHU-D') and l.active order by l.id" },
  herd_actions: { sql: "select h.*, a.location_id, a.group_id from v_herd_actions h join animals a on a.id=h.animal_id where h.farm_id=$1 order by h.due, h.priority" },
  plot_cost: { sql: "select *, input_cost+machine_cost+water_cost+labor_cost as total_cost, case when yield_kg>0 then round((input_cost+machine_cost+water_cost+labor_cost)/yield_kg) end as cost_per_kg, case when area_ha>0 then round((input_cost+machine_cost+water_cost+labor_cost)/area_ha) end as cost_per_ha from v_plot_cost where farm_id=$1 order by sow_date desc" },
  stock_value: { sql: "select * from v_stock_value where farm_id=$1 order by value desc" },
  occupancy_month: { sql: "select * from v_occupancy_month where farm_id=$1 order by month" },
  plan_years: { sql: "select * from plan_years where farm_id=$1 order by year desc, version desc" },
  plan_assumptions: { sql: "select * from plan_assumptions where farm_id=$1 order by key" },
  plan_capacity: { sql: "select * from plan_capacity where farm_id=$1 and active order by kind" },
  plan_herd_batches: { sql: "select * from plan_herd_batches where farm_id=$1 and status<>'HUY' order by start_date" },
  plan_crop_calendar: { sql: "select c.*, p.name as plot_name, coalesce(c.area_ha, p.area_ha) as ha, cr.name as crop_name from plan_crop_calendar c join plots p on p.id=c.plot_id left join crops cr on cr.code=c.crop_code where c.farm_id=$1 and c.status<>'HUY' order by c.sow_date" },
  sop_monthly: { sql: "select * from sop_monthly($1, coalesce(nullif($2,'')::date, date_trunc('month', current_date)::date), 12)", params: ["from"], ttl: 120 },
  plan_monthly_closed: { sql: "select p.* from plan_monthly p join plan_years y on y.id=p.plan_year_id and y.version=p.version where p.farm_id=$1 and p.plan_year_id=$2 order by month, line", params: ["year_id"] },
  plan_vs_actual: { sql: "select * from v_plan_vs_actual where farm_id=$1 order by month, line" },
  plan_scenarios: { sql: "select * from plan_scenarios where farm_id=$1 and status<>'LUU_TRU' order by created_at desc" },
  herd_by_class: { sql: "select * from herd_by_class($1)" },
  plan_feed_demand: { sql: "select * from plan_feed_demand($1, nullif($2::text,''))", params: ["scenario"] },
  plan_supply: { sql: "select * from plan_supply($1, nullif($2::text,''))", params: ["scenario"] },
  plan_lines: { sql: "select * from plan_lines where scenario_id=$2 and farm_id=$1 order by shortage_kg desc", params: ["scenario"] },
  plan_tasks: { sql: "select * from tasks where farm_id=$1 and source='PLAN' and status='MO' order by created_at desc limit 100" },
  sku_crop_map: { sql: "select m.*, p.name as sku_name, c.name as crop_name, c.yield_norm_kg_ha, c.cuts_per_year from sku_crop_map m join products p on p.sku=m.sku left join crops c on c.code=m.crop_code order by m.source, m.sku" },
  feed_norms: { sql: "select n.*, c.code as class_code, c.name as class_name from norms n left join animal_classes c on c.feed_norm_key=n.kind and (n.subject=c.code or n.subject=c.species_code) where n.kind like 'TA_KG%' and (n.farm_id=$1 or n.farm_id is null) order by n.kind, n.subject" },
  ap_summary: { sql: "select * from v_ap_summary where farm_id=$1 order by unpaid desc" },
  ap_aging: { sql: "select * from v_ap_aging where farm_id=$1 order by due_date" },
  loans: { sql: "select * from v_loans where farm_id=$1 order by status, start_date desc" },
  loan_schedule: { sql: "select * from loan_schedule where loan_id=$2 order by seq", params: ["loan"] },
  approval_matrix: { sql: "select * from approval_matrix where active and (farm_id is null or farm_id=$1) order by kind, max_amount nulls last" },
  insurance: { sql: "select * from v_insurance where farm_id=$1 order by end_date" },
  insurance_claims: { sql: "select c.*, p.insurer, p.kind from insurance_claims c join insurance_policies p on p.id=c.policy_id where c.farm_id=$1 order by c.event_date desc" },
  vat_summary: { sql: "select * from v_vat_summary where farm_id=$1 order by period desc limit 24" },
  payment_calendar: { sql: "select * from v_payment_calendar where farm_id=$1 and due_date <= current_date + 91 order by due_date" },
  legal_entities: { sql: "select le.*, (select string_agg(f.id, ',') from farms f where f.legal_entity_id=le.id) as farms from legal_entities le where le.active order by le.id" },
  consolidated: { sql: "select * from v_consolidated where period=$2 and $1::text is not null order by account", params: ["period"] },
  gl_by_entity: { sql: "select * from v_gl_by_entity where period=$2 and (farm_id=$1 or $1 is null) order by legal_entity_id, account", params: ["period"] },
  customer_prices: { sql: "select cp.*, p.name as product_name, pt.name as partner_name from customer_prices cp join products p on p.sku=cp.sku left join partners pt on pt.id=cp.partner_id where cp.farm_id=$1 and cp.active order by cp.sku, cp.priority" },
  discount_tiers: { sql: "select dt.*, p.name as product_name from discount_tiers dt left join products p on p.sku=dt.sku where dt.farm_id=$1 and dt.active order by dt.sku nulls first, dt.min_qty" },
  quotes: { sql: "select q.*, pt.name as partner_name, s.full_name as rep_name from quotes q left join partners pt on pt.id=q.partner_id left join staff s on s.id=q.sales_rep_id where q.farm_id=$1 order by q.created_at desc limit 200" },
  sales_performance: { sql: "select * from v_sales_performance where farm_id=$1 order by period desc, staff_id" },
  loyalty_top: { sql: "select id, name, customer_group, loyalty_points, loyalty_tier, payment_terms, credit_limit, sales_rep_id from partners where kind='KH' and (farm_id=$1 or farm_id is null) order by loyalty_points desc nulls last limit 200" },
  loyalty_ledger: { sql: "select l.*, p.name as partner_name from loyalty_ledger l join partners p on p.id=l.partner_id where l.farm_id=$1 order by l.ts desc limit 200" },
  ar_summary: { sql: "select * from v_ar_summary where farm_id=$1 order by unpaid desc" },
  ar_aging_rows: { sql: "select * from v_ar_aging where farm_id=$1 and partner_id=$2 order by due_date", params: ["partner"] },
  dunning_log: { sql: "select d.*, p.name as partner_name from dunning_log d join partners p on p.id=d.partner_id where d.farm_id=$1 order by d.sent_at desc limit 100" },
  contract_schedule: { sql: "select * from v_contract_schedule where farm_id=$1 order by planned_date" },
  bins: { sql: "select b.*, w.code as warehouse_code, w.name as warehouse_name, (select coalesce(sum(qty),0) from v_bin_stock s where s.bin_id=b.id) as qty, (select count(distinct sku) from v_bin_stock s where s.bin_id=b.id) as skus from bins b join warehouses w on w.id=b.warehouse_id where b.farm_id=$1 and b.active order by w.code, b.pick_seq, b.code" },
  bin_stock: { sql: "select * from v_bin_stock where farm_id=$1 order by warehouse_code, pick_seq, bin_code, expiry_date" },
  putaway: { sql: "select * from suggest_putaway($1, $2, $3, coalesce($4::numeric, 1))", params: ["wh", "sku", "qty"] },
  picking_bins: { sql: "select * from v_picking_bins where farm_id=$1 order by order_id, pick_seq" },
  replenishment: { sql: "select * from v_replenishment where farm_id=$1 order by suggest_qty desc, sku" },
  abc_suggest: { sql: "select a.*, p.name as product_name from v_abc_suggest a join products p on p.sku=a.sku where a.farm_id=$1 order by a.val desc" },
  cold_chain: { sql: "select * from v_cold_chain where farm_id=$1 order by code" },
  cold_temps: { sql: "select s.ts, s.value, s.device_id from sensor_reads s join warehouses w on w.temp_device_id=s.device_id and w.farm_id=s.farm_id where s.farm_id=$1 and s.metric in ('temp','temp_c','temperature') and s.ts>now()-interval '48 hours' order by s.ts" },
  vehicles: { sql: "select v.*, s.full_name as driver_name from vehicles v left join staff s on s.id=v.driver_id where v.farm_id=$1 and v.active order by v.plate" },
  trips: { sql: "select * from v_trips where farm_id=$1 order by coalesce(planned_at, created_at) desc limit 200" },
  trip_stops: { sql: "select ts.*, p.name as partner_name from trip_stops ts left join partners p on p.id=ts.partner_id where ts.trip_id=$2 order by ts.seq", params: ["trip"] },
  supplier_scorecard: { sql: "select * from v_supplier_scorecard where farm_id=$1 or farm_id is null order by score desc nulls last" },
  stock_card: { sql: "select * from v_stock_card where farm_id=$1 and sku=$2 order by ts desc limit 500", params: ["sku"] },
  cycle_count_tasks: { sql: "select * from tasks where farm_id=$1 and kind='KIEM_KE_CHU_KY' and status='MO' order by due_at" },
  bom_headers: { sql: "select h.*, p.name as sku_name, (select count(*) from bom_lines l where l.bom_id=h.id) as n_lines from bom_headers h join products p on p.sku=h.sku where h.farm_id=$1 order by h.sku, h.version desc" },
  bom_lines: { sql: "select l.*, p.name as component_name, exists(select 1 from bom_headers b where b.sku=l.component_sku and b.status='BAN_HANH') as has_bom from bom_lines l join products p on p.sku=l.component_sku where l.bom_id=$2 order by l.seq", params: ["bom"] },
  mrp_explode: { sql: "select * from mrp_explode($1, $2, $3::numeric)", params: ["sku", "qty"] },
  mrp_run: { sql: "select m.*, exists(select 1 from bom_headers b where b.farm_id=$1 and b.sku=m.component_sku and b.status='BAN_HANH') as has_bom from mrp_run($1, coalesce($2::int, 14)) m", params: ["days"] },
  production_plans: { sql: "select pp.*, p.name as sku_name from production_plans pp join products p on p.sku=pp.sku where pp.farm_id=$1 and pp.status<>'HUY' order by pp.week_start desc, pp.sku" },
  packaging_specs: { sql: "select ps.*, p.name as sku_name from packaging_specs ps join products p on p.sku=ps.sku where ps.status='ACTIVE' order by ps.sku, array_position(array['SO_CAP','THU_CAP','VAN_CHUYEN'], ps.level)" },
  label_specs: { sql: "select ls.*, p.name as sku_name from label_specs ls join products p on p.sku=ls.sku where ls.status<>'NGUNG' order by ls.sku, ls.market, ls.version desc" },
  allergens: { sql: "select * from allergens order by code" },
  lot_labels: { sql: "select * from v_lot_label where farm_id=$1 order by mfg_date desc nulls last limit 200" },
  pack_batches: { sql: "select * from v_pack_batches where farm_id=$1 order by ts desc limit 300" },
  weather_recent: { sql: "select * from weather_daily where farm_id=$1 order by day desc limit 120" },
  water_balance: { sql: "select * from v_water_balance where farm_id=$1 order by sow_date desc" },
  irrigation_recent: { sql: "select i.*, p.name as plot_name from irrigation_logs i left join plots p on p.id=i.plot_id where i.farm_id=$1 and i.status='ACTIVE' order by ts desc limit 300" },
  pest_recent: { sql: "select ps.*, p.name as plot_name from pest_scouting ps left join plots p on p.id=ps.plot_id where ps.farm_id=$1 and ps.status='ACTIVE' order by ts desc limit 300" },
  soil_tests: { sql: "select st.*, p.name as plot_name from soil_tests st left join plots p on p.id=st.plot_id where st.farm_id=$1 and st.status='ACTIVE' order by sampled_at desc" },
  rotation_check: { sql: "select * from v_rotation_check where farm_id=$1 order by plot_id, year, season_no" },
  plot_contracts: { sql: "select pc.*, p.name as plot_name, pt.name as partner_name from plot_contracts pc left join plots p on p.id=pc.plot_id left join partners pt on pt.id=pc.partner_id where pc.farm_id=$1 and pc.status<>'HUY' order by pc.end_date" },
  crop_kc: { sql: "select * from crop_kc order by crop_code, array_position(array['INI','DEV','MID','END'], stage)" },
  crop_inputs_recent: { sql: "select * from crop_inputs where farm_id=$1 and status='ACTIVE' order by ts desc limit 300" },
  harvests_recent: { sql: "select * from harvests where farm_id=$1 and status='ACTIVE' order by ts desc limit 300" },
  hosp_today: { sql: "select * from v_hosp_today where farm_id=$1" },
  hosp_rooms: { sql: "select r.*, t.name as type_name, t.base_price, t.capacity from hosp_rooms r left join hosp_room_types t on t.id=r.room_type_id where r.farm_id=$1 and r.active order by r.code" },
  hosp_room_types: { sql: "select * from hosp_room_types where farm_id=$1 and active order by code" },
  hosp_bookings: { sql: "select b.*, r.code as room_code from hosp_bookings b left join hosp_rooms r on r.id=b.room_id where b.farm_id=$1 and b.check_out >= current_date - 30 order by b.check_in desc limit 500" },
  hosp_events: { sql: "select e.*, m.name as menu_name from hosp_events e left join hosp_menus m on m.id=e.menu_id where e.farm_id=$1 and e.event_date >= current_date - 60 order by e.event_date" },
  hosp_services: { sql: "select * from hosp_services where farm_id=$1 and active order by kind, name" },
  hosp_menus: { sql: "select * from hosp_menus where farm_id=$1 and active order by name" },
  hosp_tours: { sql: "select t.*, s.name as service_name from hosp_tours t left join hosp_services s on s.id=t.service_id where t.farm_id=$1 and t.tour_date >= current_date - 7 order by t.tour_date, t.start_time" },
  hosp_folio: { sql: "select * from hosp_folio where farm_id=$1 and status='ACTIVE' order by ts desc limit 500" },
  hosp_occupancy: { sql: "select * from v_hosp_occupancy where farm_id=$1 and day >= current_date - 60 order by day" },
  crm_leads: { sql: "select l.*, s.full_name as owner_name from crm_leads l left join staff s on s.id=l.owner_id where (l.farm_id=$1 or l.farm_id is null) order by l.updated_at desc limit 500" },
  crm_pipeline: { sql: "select * from v_crm_pipeline where farm_id=$1 or farm_id is null" },
  crm_activities: { sql: "select * from crm_activities where (farm_id=$1 or farm_id is null) and status='ACTIVE' order by ts desc limit 300" },
  promotions: { sql: "select * from promotions where (farm_id=$1 or farm_id is null) order by active desc, ends_on desc" },
  sales_channels: { sql: "select * from sales_channels where active order by code" },
  pos_shifts: { sql: "select * from pos_shifts where farm_id=$1 order by opened_at desc limit 50" },
  pos_receipts: { sql: "select * from pos_receipts where farm_id=$1 and status='ACTIVE' order by ts desc limit 300" },
  sales_by_channel: { sql: "select coalesce(channel_code, 'KENH-'||channel::text) as channel_code, date_trunc('month', ts)::date as month, sum(amount) as amount, count(*) as n from sales where farm_id=$1 and status='ACTIVE' and ts >= now() - interval '12 months' group by 1,2 order by 2,1" },
  farm_profile: { sql: "select * from v_farm_profile where id=$1" },
  audit_recent: { sql: "select * from audit_log where (farm_id=$1 or farm_id is null) order by ts desc limit 200" },
  import_batches: { sql: "select * from import_batches where farm_id=$1 order by ts desc limit 100" },
  farm_summary: { sql: `select f.id, f.name, f.province,
      (select head_count from v_herd_value h where h.farm_id=f.id) as head_count,
      (select value from v_herd_value h where h.farm_id=f.id) as herd_value,
      (select days_silage from v_days_silage d where d.farm_id=f.id) as days_silage,
      (select count(*) from alerts a where a.farm_id=f.id and a.acked_at is null and a.level='DO') as red_alerts,
      (select count(*) from alerts a where a.farm_id=f.id and a.acked_at is null and a.level='VANG') as yellow_alerts,
      (select count(*) from recon_results r where r.farm_id=f.id and r.status<>'OK' and r.acked_by is null) as recon_open,
      (select coalesce(sum(amount),0) from sales s where s.farm_id=f.id and s.status='ACTIVE' and s.ts>=date_trunc('month',now())) as revenue_mtd
      from farms f order by f.id` },
  animals: { sql: "select a.*, g.name as group_name, l.name as location_name from animals a left join animal_groups g on g.id=a.group_id left join locations l on l.id=a.location_id where a.farm_id=$1 order by a.id" },
  animal: { sql: "select a.*, g.name as group_name, il.kind as intake_kind, il.date as intake_date, il.quarantine_until from animals a left join animal_groups g on g.id=a.group_id left join intake_lots il on il.id=a.intake_lot_id where a.farm_id=$1 and (a.id=$2 or a.rfid=$2 or a.visual_tag=$2 or a.qr_token=$2)", params: ["code"] },
  animal_events: { sql: "select e.*, s.full_name as by_name from animal_events e left join staff s on s.id=e.created_by where e.farm_id=$1 and (e.animal_id=$2 or e.group_id=$2) order by e.ts desc limit 200", params: ["code"] },
  animal_groups: { sql: "select g.*, l.name as location_name from animal_groups g left join locations l on l.id=g.location_id where g.farm_id=$1 order by g.id" },
  intake_lots: { sql: "select il.*, (select count(*) from animals a where a.intake_lot_id=il.id) as n from intake_lots il where il.farm_id=$1 order by date desc" },
  herd: { sql: "select * from v_herd where farm_id=$1 order by species, status" },
  herd_value: { sql: "select * from v_herd_value where farm_id=$1" },
  stock: { sql: "select * from v_stock_balance where farm_id=$1 and qty<>0 order by warehouse_code, sku, lot_id" },
  stock_ledger: { sql: "select * from v_stock_ledger where farm_id=$1 and sku=$2 order by ts desc limit 300", params: ["sku"] },
  days_silage: { sql: "select * from v_days_silage where farm_id=$1" },
  fefo_red: { sql: "select * from v_fefo_red where farm_id=$1" },
  material_balance: { sql: "select * from v_material_balance_week where farm_id=$1" },
  kpi_conception: { sql: "select * from v_kpi_conception where farm_id=$1" },
  kpi_weaned: { sql: "select * from v_kpi_weaned_per_dam where farm_id=$1" },
  kpi_feed_accuracy: { sql: "select * from v_kpi_feed_accuracy where farm_id=$1 order by day desc limit 30" },
  kpi_lay_rate: { sql: "select * from v_kpi_lay_rate where farm_id=$1 order by day desc limit 30" },
  kpi_defs: { sql: "select * from kpi_defs where active order by code" },
  alerts_open: { sql: "select * from alerts where farm_id=$1 and acked_at is null order by case level when 'DO' then 0 when 'CAM' then 1 when 'VANG' then 2 else 3 end, ts desc limit 100" },
  alerts_all: { sql: "select * from alerts where farm_id=$1 order by ts desc limit 200" },
  recon_latest: { sql: "select r.*, rr.name from recon_results r join rc_rules rr on rr.code=r.rule_code where r.farm_id=$1 and r.period=(select max(period) from recon_results x where x.farm_id=$1) order by r.rule_code" },
  recon_history: { sql: "select r.* from recon_results r where r.farm_id=$1 and r.rule_code=$2 order by period desc limit 60", params: ["rule"] },
  recipes: { sql: "select * from recipes where farm_id=$1 and active order by id" },
  recipe: { sql: "select * from recipes where farm_id=$1 and id=$2 order by version desc limit 1", params: ["id"] },
  plots: { sql: "select * from plots where farm_id=$1 order by id" },
  locations: { sql: "select * from locations where farm_id=$1 order by id" },
  warehouses: { sql: "select * from warehouses where farm_id=$1 order by code" },
  products: { sql: "select * from products where active order by kind, sku" },
  partners: { sql: "select * from partners where (farm_id=$1 or farm_id is null) and active order by kind, id" },
  devices: { sql: "select * from devices where farm_id=$1 order by id" },
  sops: { sql: "select s.*, v.version, v.steps, v.pass_criteria, v.review_due, v.status as vstatus from sops s left join lateral (select * from sop_versions v where v.sop_code=s.code order by version desc limit 1) v on true order by s.code" },
  sop: { sql: "select s.*, v.* from sops s join sop_versions v on v.sop_code=s.code where s.code=$2 order by v.version desc limit 1", params: ["code"] },
  checklist_today: { sql: "select * from checklist_runs where farm_id=$1 and ts::date=current_date order by ts desc" },
  feed_today: { sql: "select f.*, s.full_name as by_name from feed_logs f left join staff s on s.id=f.created_by where f.farm_id=$1 and f.ts::date=current_date order by f.ts desc" },
  events_recent: { sql: "select 'animal' as kind, id, ts, created_by, event_type as what, animal_id as who, source, is_backfill from animal_events where farm_id=$1 union all select 'feed', id, ts, created_by, 'FEED '||qty_kg||'kg', dest_location_id, source, is_backfill from feed_logs where farm_id=$1 union all select 'crop', id, ts, created_by, activity, plot_id, source, is_backfill from crop_logs where farm_id=$1 union all select 'batch', id, ts, created_by, line, batch_code, source, is_backfill from batch_logs where farm_id=$1 union all select 'move', id, ts, created_by, reason||' '||qty, sku, source, is_backfill from inventory_moves where farm_id=$1 order by ts desc limit 100" },
  // "Gần đây" của CÔNG NHÂN = những gì CHÍNH HỌ vừa ghi. Dùng events_recent (toàn trại) cho tab này
  // thì công nhân ghi xong không tìm thấy bản ghi của mình giữa 100 dòng của cả trại — đo được: 60/60
  // dòng là bản nhập liệu cũ của người khác, 0 dòng vừa ghi. Kèm chặn ts tương lai để bản ghi hôm nay
  // không bị dữ liệu đặt lịch/nhập sai ngày đè xuống dưới.
  events_mine: { sql: "select * from (select 'animal' as kind, id, ts, created_by, event_type as what, animal_id as who, source, is_backfill from animal_events where farm_id=$1 and created_by=app_staff() union all select 'feed', id, ts, created_by, 'FEED '||qty_kg||'kg', dest_location_id, source, is_backfill from feed_logs where farm_id=$1 and created_by=app_staff() union all select 'crop', id, ts, created_by, activity, plot_id, source, is_backfill from crop_logs where farm_id=$1 and created_by=app_staff() union all select 'batch', id, ts, created_by, line, batch_code, source, is_backfill from batch_logs where farm_id=$1 and created_by=app_staff() union all select 'move', id, ts, created_by, reason||' '||qty, sku, source, is_backfill from inventory_moves where farm_id=$1 and created_by=app_staff()) t where ts <= now() order by ts desc limit 100" },
  // Bộ form theo NGHỀ — thay cho việc dò chữ trong chức danh tự do ở src/lib/forms.ts.
  // Không lọc theo farm: danh mục nghề dùng chung toàn công ty.
  position_forms: { sql: "select position_code, name, dept_code, role_code, forms from v_position_forms where $1 = $1" },
  paper_pending: { sql: "select * from paper_scans where farm_id=$1 and not digitized order by ts" },
  paper_all: { sql: "select * from paper_scans where farm_id=$1 order by ts desc limit 200" },
  adjustments_pending: { sql: "select * from adjustments where farm_id=$1 and adj_status='CHO_DUYET' order by ts" },
  incidents_open: { sql: "select * from incidents where farm_id=$1 and closed_at is null order by ts desc" },
  sales_recent: { sql: "select s.*, p.name as partner_name from sales s left join partners p on p.id=s.partner_id where s.farm_id=$1 order by s.ts desc limit 100" },
  receivables: { sql: "select p.id, p.name, sum(s.amount) filter (where not s.paid) as unpaid, min(s.ts) filter (where not s.paid) as oldest, extract(day from now()-min(s.ts) filter (where not s.paid))::int as days from sales s join partners p on p.id=s.partner_id where s.farm_id=$1 and s.status='ACTIVE' group by p.id, p.name having sum(s.amount) filter (where not s.paid) > 0 order by days desc" },
  trace_lot: { sql: `with recursive back as (select input_lot, output_lot, batch_code, 1 as depth from v_trace_links where farm_id=$1 and output_lot=$2 union select t.input_lot, t.output_lot, t.batch_code, b.depth+1 from v_trace_links t join back b on t.output_lot=b.input_lot where b.depth<6),
     fwd as (select input_lot, output_lot, batch_code, 1 as depth from v_trace_links where farm_id=$1 and input_lot=$2 union select t.input_lot, t.output_lot, t.batch_code, f.depth+1 from v_trace_links t join fwd f on t.input_lot=f.output_lot where f.depth<6)
     select 'BACK' as dir, * from back union all select 'FWD', * from fwd`, params: ["lot"] },
  trace_customers: { sql: "select s.ts, s.qty, s.unit, p.name, p.phone from sales s join partners p on p.id=s.partner_id where s.farm_id=$1 and s.status='ACTIVE' and s.lot_id=$2 order by s.ts", params: ["lot"] },
  lot: { sql: "select l.*, p.name as product_name from lots l join products p on p.sku=l.sku where l.farm_id=$1 and l.id=$2", params: ["lot"] },
  staff: { sql: "select id, full_name, role, dept, position, phone, farm_id, active from staff where farm_id=$1 or farm_id is null order by role, id" },
  settings: { sql: "select distinct on (key) key, value, farm_id from settings where farm_id in ('GLOBAL',$1) order by key, (farm_id=$1) desc, version desc" },
  norms: { sql: "select * from norms where farm_id=$1 or farm_id is null order by kind" },
  gate_today: { sql: "select * from gate_logs where farm_id=$1 and ts::date=current_date order by ts desc" },
  weekly_one_page: { sql: `select
      (select row_to_json(m) from v_material_balance_week m where m.farm_id=$1) as balance,
      (select row_to_json(d) from v_days_silage d where d.farm_id=$1) as silage,
      (select row_to_json(h) from v_herd_value h where h.farm_id=$1) as herd,
      (select json_agg(a) from (select rule_code, level, subject, ts from alerts where farm_id=$1 and level='DO' and ts>=now()-interval '7 days' order by ts desc limit 20) a) as red_week,
      (select json_agg(r) from (select rule_code, diff_pct, status, period from recon_results where farm_id=$1 and status<>'OK' and period>=current_date-7 order by period desc) r) as recon_week,
      (select coalesce(sum(amount),0) from sales where farm_id=$1 and status='ACTIVE' and ts>=now()-interval '7 days') as revenue_week,
      (select coalesce(sum(amount) filter (where not paid),0) from sales where farm_id=$1 and status='ACTIVE') as receivable,
      (select json_agg(i) from (select code, kind, severity, description, ts from incidents where farm_id=$1 and ts>=now()-interval '7 days' order by ts desc) i) as incidents_week` },
};
