"use client";
import { useState } from "react";
import { useData, act, fmt } from "@/lib/client";
import type { Sess } from "@/components/Shell";
import Tabs from "@/components/Tabs";
import { usePrompt } from "@/components/ui/PromptDialog";
import { DataBoundary } from "@/components/ui/DataBoundary";
type R = Record<string, unknown>;
const GRADE_COL: Record<string, string> = { B1: "bg-slate-200 text-slate-800", B2: "bg-sky-100 text-sky-900", B3: "bg-emerald-100 text-emerald-900", B4: "bg-amber-100 text-amber-900", GS1: "bg-violet-100 text-violet-900", GS2: "bg-violet-200 text-violet-900", GS3: "bg-fuchsia-200 text-fuchsia-900", PGD: "bg-rose-200 text-rose-900" };
export const Badge = ({ g }: { g?: unknown }) => g ? <span className={`px-1.5 py-0.5 rounded text-xs font-bold ${GRADE_COL[String(g)] ?? "bg-slate-100"}`}>{String(g)}</span> : <span className="text-slate-400">—</span>;
const CRIT_LABEL: Record<string, string> = { min_months: "Thâm niên (tháng)", comp_level: "Mức SOP vị trí", comp_pct: "% SOP đạt mức", sup_avg_min: "Điểm giám sát TB ≥", sup_months: "…trong số tháng liền", ontime_min: "Ghi đúng giờ ≥ %", kpi_hit_min: "Tháng đạt thưởng KPI ≥", kpi_of: "…trên số tháng xét", severe_free_months: "Không lỗi nặng (tháng)", teach_sessions_min: "Buổi dạy ≥ /12 th", trainee_pass_pct_min: "Học viên đậu ≥ %", initiatives_min: "Sáng kiến duyệt ≥", acting_stints_min: "Kỳ làm quyền ≥", acting_days: "…mỗi kỳ ≥ ngày", entry_grade: "Bậc CM tối thiểu", gs_months: "Tháng làm GS ≥", weekly_fill_min: "Đủ lượt tuần ≥ %", agree_min: "Khớp kiểm chéo ≥ %", blocks_min: "Khối đạt ≥ /8", rating_min: "Chấm ngược ≥ /5", field_days_min: "Đi ca thật ≥ ngày/6 th", dept_improve_min: "Phòng kiểm tăng ≥ điểm", led_plan_or_audit: "Chủ trì KH năm/audit" };

function PathBox({ title, el, track }: { title: string; el: R | undefined; track: string }) { if (!el) return null; const miss = ((el.missing as string[]) ?? []).map(String); const pct = Number(el.pct ?? 0); return <div className="rounded-xl border p-3">
    <div className="flex items-center gap-2 flex-wrap"><b>{title}</b> <Badge g={el.current} /> {el.next ? <>→ <Badge g={el.next} /> <span className="text-sm text-slate-600">{String(el.next_name ?? "")}</span></> : <span className="text-sm text-emerald-700">bậc cao nhất của ngạch {track}</span>}</div>
    {el.next ? <><div className="mt-2 h-3 rounded-full bg-slate-100 overflow-hidden"><div className={`h-3 ${pct >= 100 ? "bg-emerald-600" : "bg-sky-500"}`} style={{ width: `${Math.min(100, pct)}%` }} /></div><div className="text-xs text-slate-600 mt-1">{String(el.ok)}/{String(el.total)} điều kiện · {pct}%{pct >= 100 ? " — ĐỦ ĐIỀU KIỆN, chờ xét quý (3 chữ ký)" : ""}</div>
      {miss.length > 0 && <div className="mt-1 text-sm"><div className="text-xs font-bold text-slate-500 uppercase">Còn thiếu</div><ul className="list-disc ml-5">{miss.map((m, i) => <li key={i}>{m}</li>)}</ul></div>}
      {el.perks ? <div className="text-xs text-slate-600 mt-1">Lên bậc được: {String(el.perks)}</div> : null}</> : null}
  </div>; }
/** Đường lên của tôi — thẻ cá nhân (dùng ở /tai-khoan) */
export function MyPath({ sess }: { sess: Sess }) {
  const cm = useData<R>("my_path", { track: "CM" }); const gs = useData<R>("my_path", { track: "GS" }); const cov = useData<R>("gs_coverage_me"); const contrib = useData<R>("my_contribution"); const pay = useData<R>("my_pay"); const p = (pay.rows ?? [])[0]; const est = useData<R>("my_pay_estimate"); const e2 = (est.rows ?? [])[0]?.e as R | undefined;
  const e = (cm.rows ?? [])[0]?.e as R | undefined; const g = (gs.rows ?? [])[0]?.e as R | undefined; const c = (contrib.rows ?? [])[0];
  return <div className="card space-y-3">
    <div className="font-black">🪜 Đường lên của tôi <span className="text-xs font-normal text-slate-500">— bậc là của cá nhân, xét mỗi quý bằng dữ liệu thật; ghế theo định biên</span></div>
    <div className="grid md:grid-cols-2 gap-3"><PathBox title="Ngạch chuyên môn" el={e} track="CM" />{g && <PathBox title="Ngạch Giám sát – Kế thừa" el={g} track="GS" />}</div>
    {(cov.rows ?? []).length > 0 && <div><div className="text-xs font-bold text-slate-500 uppercase mb-1">Bảng phủ 8 khối (ngạch GS)</div><div className="grid grid-cols-4 md:grid-cols-8 gap-1">{(cov.rows ?? []).map((b) => <div key={String(b.block)} className={`rounded-lg p-2 text-center text-xs border ${b.done ? "bg-emerald-100 border-emerald-300" : b.current ? "bg-sky-50 border-sky-300" : "bg-white"}`} title={`${b.months} tháng · SOP đậu ${b.sop_passed} · đi ca ${b.field_days} · làm quyền ${b.acting}`}><div className="font-bold">{String(b.block)}</div><div>{String(b.months)} th</div><div>{b.done ? "✓ đạt" : b.current ? "đang kiểm" : "chưa"}</div></div>)}</div></div>}
    {c && <div className="text-sm">⭐ Điểm cống hiến: <b>{Math.round(Number(c.kpi_pts) + Number(c.sup_pts) + Number(c.teach_pts) + Number(c.init_pts) + Number(c.cover_pts))}</b> <span className="text-xs text-slate-500">(KPI {String(c.kpi_pts)} · giám sát {Number(c.sup_pts).toFixed(0)} · dạy {String(c.teach_pts)} · sáng kiến {String(c.init_pts)} · thay người {String(c.cover_pts)})</span> · <a className="underline" href="/nhan-su?tab=bac">Bảng bậc & tiêu chí</a></div>}
    {p && e2 && <MyPayBox p={p} e={e2} />}
    <div className="text-xs text-slate-500">Vai của {sess.staffName}: {sess.role}. Muốn góp sáng kiến? <InitiativeForm /></div>
  </div>;
}
function MyPayBox({ p, e }: { p: R; e: R }) {
  const claims = useData<R>("my_dependent_claims"); const slips = useData<R>("my_payslips"); const br = useData<R>("pit_brackets"); const [dep, setDep] = useState(String(e.dependents ?? 0)); const [m, setM] = useState(""); const [open, setOpen] = useState(false);
  const last = e.last_payslip as R | null; const n = (v: unknown) => fmt.n(v);
  return <div className="text-sm rounded-xl border p-3 bg-slate-50 space-y-2">
    <div className="flex items-center gap-2 flex-wrap"><b>💰 Lương – bảo hiểm – thuế của tôi</b><span className="text-xs text-slate-500">(ước tính tháng đủ công, KPI 100%; số thật xem phiếu lương bên dưới)</span><button className="ml-auto text-xs underline" onClick={() => setOpen(!open)}>{open ? "thu gọn" : "chi tiết"}</button></div>
    <div className="grid grid-cols-2 md:grid-cols-4 gap-2 text-xs">
      <div className="rounded-lg bg-white p-2"><div className="text-slate-500">Lớp 1 · thang × hệ số</div><div className="font-bold text-base">{n(e.base_l1)}</div><div>{n(p.scale_amount)} × {String(p.coef)} ({String(p.grade_gs ?? p.grade_cm)})</div></div>
      <div className="rounded-lg bg-white p-2"><div className="text-slate-500">KPI tối đa + phụ cấp</div><div className="font-bold text-base">{n(Number(e.kpi_max) + Number(e.allowances))}</div><div>KPI {n(e.kpi_max)} · PC {n(e.allowances)}</div></div>
      <div className="rounded-lg bg-white p-2"><div className="text-slate-500">Bảo hiểm tôi đóng ({String(e.bhxh_pct)}+{String(e.bhyt_pct)}+{String(e.bhtn_pct)}%)</div><div className="font-bold text-base text-amber-800">−{n(Number(e.bhxh) + Number(e.bhyt) + Number(e.bhtn))}</div><div>trên lương BH {n(e.ins_salary)}{e.contract_kind ? ` · HĐ ${String(e.contract_kind)}` : ""}</div></div>
      <div className="rounded-lg bg-white p-2"><div className="text-slate-500">Thuế TNCN</div><div className="font-bold text-base text-amber-800">−{n(e.pit)}</div><div>TN tính thuế {n(e.taxable)}</div></div>
      <div className="rounded-lg bg-emerald-50 p-2 col-span-2"><div className="text-slate-500">Thực nhận ước tính</div><div className="font-black text-lg text-emerald-800">{n(e.net)}</div><div>Công ty đóng thêm BH cho tôi: {n(e.employer_ins)}/tháng</div></div>
      <div className="rounded-lg bg-white p-2 col-span-2"><div className="text-slate-500">Giảm trừ gia cảnh</div><div>Bản thân {n(e.giam_tru_ban_than)} · Phụ thuộc {String(e.dependents)} người × {n(Number(e.giam_tru_phu_thuoc) / Math.max(1, Number(e.dependents)))} = {n(e.giam_tru_phu_thuoc)}</div>
        <div className="flex items-center gap-1 mt-1">Khai người phụ thuộc: <input className="input !py-0 !w-14 text-right" value={dep} onChange={(ev) => setDep(ev.target.value)} /><button className="btn-secondary !py-0.5 !px-2 !text-xs" onClick={async () => { const j = await act("dependent_claim", { dependents: Number(dep), note: "khai từ Tài khoản" }); setM(j.error ? String(j.error) : "Đã gửi HCNS duyệt (kèm hồ sơ giấy)"); claims.reload(); }}>Gửi HCNS</button><span className="text-[11px]">{m}{(claims.rows ?? [])[0] ? ` · lần gần nhất: ${String((claims.rows ?? [])[0].dependents)} người — ${String((claims.rows ?? [])[0].status)}` : ""}</span></div></div>
    </div>
    {open && <div className="space-y-2">
      <div className="text-xs text-slate-600">Cách tính: Lớp 1 = thang lương vị trí × hệ số bậc × ngày công/26 · Lớp 2 = KPI ({n(e.kpi_max)} khi 100%) + thưởng điều kiện tháng · Lớp 3 = phụ cấp · Lớp 4 = thưởng cống hiến quý. BH tính trên lương đóng BH (trần {n(e.ins_cap)}); TNCN = (tổng − BH − giảm trừ) × biểu lũy tiến. Mọi tham số là cấu hình (HCNS › Cơ chế lương–thưởng).</div>
      <div className="grid md:grid-cols-2 gap-2">
        <div className="rounded-lg bg-white p-2 overflow-auto"><div className="text-xs font-bold text-slate-500 uppercase">Biểu thuế TNCN lũy tiến (tháng)</div><table className="tbl text-xs"><tbody>{(br.rows ?? []).map((b) => <tr key={String(b.bac)}><td className="pl-2">Bậc {String(b.bac)}</td><td>{n(b.tu)} → {b.den ? n(b.den) : "∞"}</td><td className="text-right">{String(b.thue_pct)}%</td></tr>)}</tbody></table></div>
        <div className="rounded-lg bg-white p-2 overflow-auto"><div className="text-xs font-bold text-slate-500 uppercase">Phiếu lương của tôi (12 tháng)</div><DataBoundary loading={slips.loading} error={slips.error} empty={!slips.rows?.length} onRetry={slips.reload} emptyText={`Chưa có phiếu lương${last ? "" : "."}`}><table className="tbl text-xs"><thead><tr><th className="pl-2">Tháng</th><th className="text-right">Công</th><th className="text-right">Tổng</th><th className="text-right">BH</th><th className="text-right">Thuế</th><th className="text-right">Thực nhận</th></tr></thead><tbody>{(slips.rows ?? []).map((r) => <tr key={String(r.month)}><td className="pl-2">{fmt.d(r.month).slice(3)}</td><td className="text-right">{String(r.work_days)}</td><td className="text-right">{n(r.gross)}</td><td className="text-right">{n(Number(r.bhxh) + Number(r.bhyt) + Number(r.bhtn))}</td><td className="text-right">{n(r.pit)}</td><td className="text-right font-bold">{n(r.net)}</td></tr>)}</tbody></table></DataBoundary></div>
      </div>
    </div>}
  </div>;
}
function InitiativeForm() {
  const [t, setT] = useState(""); const [b, setB] = useState(""); const [m, setM] = useState("");
  return <span className="inline-flex gap-1 items-center flex-wrap"><input className="input !py-1 !text-xs" placeholder="Tên sáng kiến" aria-label="Tên sáng kiến" value={t} onChange={(e) => setT(e.target.value)} /><input className="input !py-1 !text-xs" placeholder="Lợi ích ước tính" aria-label="Lợi ích ước tính" value={b} onChange={(e) => setB(e.target.value)} /><button className="btn-secondary !py-1 !text-xs" onClick={async () => { if (!t) return; const j = await act("initiative", { title: t, benefit: b }); setM(j.error ? String(j.error) : "Đã gửi — trưởng phòng/GĐ duyệt"); setT(""); setB(""); }}>Gửi</button>{m && <span>{m}</span>}</span>;
}

/** BẬC · GHẾ · KẾ THỪA · TỔ GIÁM SÁT (tab trong /nhan-su) */
export default function CareerPanel({ sess }: { sess: Sess }) {
  const [tab, setTab] = useState<"tong" | "xet" | "ghe" | "gs" | "conghien" | "tieuchi" | "luong">("tong");
  const scales = useData<R>("grade_scales"); const grades = useData<R>("staff_grades_all"); const reviews = useData<R>("grade_reviews"); const succ = useData<R>("succession"); const contrib = useData<R>("contribution"); const gsc = useData<R>("gs_coverage_all"); const gsr = useData<R>("supervisor_ratings"); const inis = useData<R>("initiatives"); const staff = useData<R>("staff_all");
  const [msg, setMsg] = useState(""); const canHR = ["owner", "director", "accountant", "it_engineer"].includes(sess.role) || sess.dept === "HCNS";
  const { prompt, promptElement } = usePrompt();
  const reload = () => { reviews.reload(); grades.reload(); succ.reload(); gsc.reload(); inis.reload(); };
  const q = (() => { const d = new Date(); return `${d.getFullYear()}-Q${Math.floor(d.getMonth() / 3) + 1}`; })();
  const S = scales.rows ?? []; const G = grades.rows ?? [];
  const dist = (track: string) => S.filter((s) => s.track === track).map((s) => [String(s.code), G.filter((g) => g.track === track && g.grade_code === s.code).length] as const);
  const sign = async (id: unknown, slot: string) => { const j = await act("sign_grade", { id, slot }); setMsg(j.error ? `${j.error}: ${j.detail ?? ""}` : j.applied ? "Đủ 3 chữ ký — đã áp dụng (thử bậc 3 tháng)" : `Đã ký (${j.signs}/3)`); reload(); };
  return <div className="space-y-3">{promptElement}
    <Tabs items={[["tong", "Tổng quan bậc"], ["xet", `Xét quý ${q} (${(reviews.rows ?? []).filter((r) => r.status !== "AP_DUNG" && r.status !== "TU_CHOI").length} chờ ký)`], ["ghe", `Ghế then chốt & kế thừa (${(succ.rows ?? []).filter((r) => Number(r.n_successors) === 0).length} thiếu)`], ["gs", "Tổ giám sát · 8 khối · luân chuyển"], ["conghien", "Điểm cống hiến & sáng kiến"], ["luong", "💰 Cơ chế lương–thưởng · định biên"], ["tieuchi", "Bảng bậc & tiêu chí"]]} value={tab} onChange={(k) => setTab(k as typeof tab)} />
    {msg && <div className="text-sm text-emerald-800">{msg}</div>}
    {tab === "tong" && <div className="space-y-3">
      <div className="grid md:grid-cols-2 gap-3">
        <div className="card"><b>Ngạch chuyên môn (CM)</b><div className="flex gap-2 mt-2 flex-wrap">{dist("CM").map(([c, n]) => <div key={c} className="rounded-xl border px-3 py-2 text-center"><Badge g={c} /><div className="text-2xl font-black">{n}</div></div>)}</div><div className="text-xs text-slate-500 mt-1">Bậc = của cá nhân, không giới hạn số lượng, gắn hệ số lương. Ghế = theo định biên.</div></div>
        <div className="card"><b>Ngạch Giám sát – Kế thừa (GS, thuộc công ty mẹ)</b><div className="flex gap-2 mt-2 flex-wrap">{dist("GS").map(([c, n]) => <div key={c} className="rounded-xl border px-3 py-2 text-center"><Badge g={c} /><div className="text-2xl font-black">{n}</div></div>)}</div><div className="text-xs text-slate-500 mt-1">Vào từ B3 mọi phòng · luân chuyển 8 khối · đi ca thật · làm quyền trưởng phòng · GS3 = 6/8 khối → PGĐ → GĐ trại/GĐ trại mới.</div></div>
      </div>
      <div className="card p-0 overflow-auto"><div className="px-3 py-2 bg-slate-100 rounded-t-xl font-bold">Bậc từng người ({G.length})</div><table className="tbl text-sm"><thead><tr><th className="pl-3">Nhân sự</th><th>Phòng</th><th>Vị trí</th><th>Bậc CM</th><th>Bậc GS</th><th>Từ</th><th>TT</th><th>Hệ số</th><th>Bậc kế tiếp · % đủ</th></tr></thead><tbody>
        {G.filter((g) => g.track === "CM").map((g) => { const gg = G.find((x) => x.staff_id === g.staff_id && x.track === "GS"); return <tr key={String(g.id)}><td className="pl-3"><a className="underline" href={`/xem/staff/${g.staff_id}`}>{String(g.full_name)}</a></td><td>{String(g.dept ?? "")}</td><td className="text-xs">{String(g.position ?? "")}</td><td><Badge g={g.grade_code} /></td><td><Badge g={gg?.grade_code} /></td><td>{fmt.d(g.since)}</td><td className="text-xs">{g.status === "THU_BAC" ? <span className="b-yel">thử bậc</span> : g.status === "HA_BAC" ? <span className="b-red">hạ bậc</span> : ""}</td><td>{String(g.salary_coef ?? "")}</td><td className="text-xs">{g.next_grade ? <>→ <Badge g={g.next_grade} /> {String(g.next_pct)}%</> : "—"}</td></tr>; })}</tbody></table></div>
    </div>}
    {tab === "xet" && <div className="space-y-3">
      <div className="card flex items-center gap-2 flex-wrap"><b>Xét bậc quý {q}</b><span className="text-xs text-slate-500">Hệ thống so bằng chứng với tiêu chí → đề xuất LÊN (đủ 100%) / CẢNH BÁO (dưới chuẩn) / HẠ (2 quý liền). Hội đồng 3 chữ ký: quản lý trực tiếp · giám sát · HCNS. Không ai ký cho chính mình. Lên bậc = thử bậc 3 tháng rồi chính thức.</span>
        {canHR && <button className="btn-primary !py-1.5 ml-auto" onClick={async () => { const j = await act("run_grade_review", { quarter: q }); setMsg(j.error ? String(j.error) : `Đã tạo ${j.n} đề xuất`); reload(); }}>▶ Chạy xét quý</button>}</div>
      <DataBoundary loading={reviews.loading} error={reviews.error} empty={!reviews.rows?.length} onRetry={reviews.reload} emptyText={'Chưa có đề xuất — bấm "Chạy xét quý".'}><div className="card p-0 overflow-auto"><table className="tbl text-sm"><thead><tr><th className="pl-3">Nhân sự</th><th>Ngạch</th><th>Loại</th><th>Từ → đến</th><th>Bằng chứng / thiếu</th><th>Chữ ký</th><th>TT</th><th></th></tr></thead><tbody>
        {(reviews.rows ?? []).map((r) => { const s = (r.signs ?? {}) as Record<string, R>; const miss = (r.missing ?? []) as string[]; return <tr key={String(r.id)}><td className="pl-3">{String(r.full_name)}<div className="text-xs text-slate-500">{String(r.dept ?? "")}</div></td><td>{String(r.track)}</td><td>{r.kind === "LEN" ? <span className="b-grn">LÊN</span> : r.kind === "HA" ? <span className="b-red">HẠ</span> : <span className="b-yel">CẢNH BÁO</span>}</td><td><Badge g={r.from_grade} /> → <Badge g={r.to_grade} /></td><td className="text-xs max-w-md">{miss.length ? miss.join(" · ") : `Đủ ${String(r.score_pct)}% điều kiện`}</td><td className="text-xs">{["manager", "gs", "hcns"].map((k) => <div key={k}>{s[k] ? "✓" : "☐"} {k === "manager" ? "Quản lý" : k === "gs" ? "Giám sát" : "HCNS"}{s[k] ? ` (${String(s[k].by)})` : ""}</div>)}</td><td className="text-xs">{String(r.status)}</td><td className="text-xs whitespace-nowrap">{r.status !== "AP_DUNG" && r.status !== "TU_CHOI" && r.staff_id !== sess.staffId && r.kind !== "CANH_BAO" && <>{["manager", "gs", "hcns"].filter((k) => !s[k]).map((k) => <button key={k} className="btn-secondary !py-0.5 !px-2 !text-xs mr-1" onClick={() => sign(r.id, k)}>Ký {k === "manager" ? "QL" : k === "gs" ? "GS" : "HCNS"}</button>)}<button className="text-xs underline text-red-700 ml-1" onClick={async () => { const n = await prompt({ title: "Từ chối xét bậc", label: "Lý do từ chối", type: "text" }); if (n === null) return; await act("reject_grade", { id: r.id, note: n }); reload(); }}>từ chối</button></>}{r.status === "DE_XUAT" && r.staff_id === sess.staffId && r.kind === "HA" && <button className="text-xs underline" onClick={async () => { const n = await prompt({ title: "Kháng nghị bậc", label: "Nội dung kháng nghị", type: "text" }); if (!n) return; await act("appeal_grade", { id: r.id, note: n }); reload(); }}>kháng nghị</button>}</td></tr>; })}
        </tbody></table></div></DataBoundary>
    </div>}
    {tab === "ghe" && <div className="space-y-3">
      <div className="card text-sm"><b>Bản đồ kế thừa</b> — mỗi ghế then chốt phải có ≥1 người kế thừa được nêu tên và mức sẵn sàng (NGAY / 1 năm / 2 năm). Ghế không có người → đỏ. Người kế thừa GĐ trại phải là ngạch GS (PGĐ). {canHR && <AddKeyPos staff={staff.rows ?? []} onDone={reload} />}</div>
      <div className="grid md:grid-cols-2 gap-3">{(succ.rows ?? []).map((k) => <div key={String(k.id)} className={`card ${Number(k.n_successors) === 0 ? "ring-2 ring-red-400" : Number(k.ready_now) > 0 ? "ring-1 ring-emerald-300" : ""}`}>
        <div className="flex items-center gap-2 flex-wrap"><b>{String(k.title)}</b><span className="text-xs text-slate-500">{String(k.dept ?? "")} · yêu cầu <Badge g={k.min_grade} /> ngạch {String(k.track)}</span>{Number(k.n_successors) === 0 && <span className="b-red ml-auto">chưa có kế thừa</span>}</div>
        <div className="text-sm mt-1">Đang giữ: <b>{String(k.holder_name ?? "trống")}</b></div>
        <div className="text-sm">Kế thừa: {k.successors ? String(k.successors) : <i className="text-red-700">chưa có</i>}</div>
        {canHR && <AddSuccessor kp={k} staff={staff.rows ?? []} onDone={reload} />}
      </div>)}</div>
    </div>}
    {tab === "gs" && <div className="space-y-3">
      <div className="card flex items-center gap-2 flex-wrap text-sm"><b>Tổ giám sát — bảng phủ 8 khối</b><span className="text-xs text-slate-500">Khối đạt = kiểm ≥ 3 tháng · đậu SOP cốt lõi · đi ca thật ≥ 4 ngày. Luân chuyển tự động theo quý, lệch pha (≤ 1/3 tổ đổi khối một lần), 1 tuần chồng ca.</span>
        {canHR && <button className="btn-secondary !py-1.5 ml-auto" onClick={async () => { const j = await act("plan_gs_rotation", {}); setMsg(j.error ? String(j.error) : `Đã luân chuyển ${j.n} giám sát viên`); reload(); }}>🔁 Luân chuyển đợt mới</button>}</div>
      <div className="card p-0 overflow-auto"><table className="tbl text-sm"><thead><tr><th className="pl-3">Giám sát viên</th><th>Bậc GS</th>{["CN", "TT", "SH", "D5", "KHO", "KD", "TCNS", "TB"].map((b) => <th key={b} className="text-center">{b}</th>)}<th className="text-right">Đạt/8</th><th className="text-right">Chấm ngược</th></tr></thead><tbody>
        {[...new Set((gsc.rows ?? []).map((r) => String(r.staff_id)))].map((sid) => { const rows = (gsc.rows ?? []).filter((r) => r.staff_id === sid); const r0 = rows[0]; const rt = (gsr.rows ?? []).find((x) => x.supervisor_id === sid); return <tr key={sid}><td className="pl-3">{String(r0.full_name)}<div className="text-xs text-slate-500">{String(r0.dept ?? "")}</div></td><td><Badge g={r0.grade_gs} /></td>{["CN", "TT", "SH", "D5", "KHO", "KD", "TCNS", "TB"].map((b) => { const c = rows.find((x) => x.block === b); return <td key={b} className={`text-center text-xs ${c?.done ? "bg-emerald-50 font-bold" : c?.current ? "bg-sky-50" : ""}`} title={c ? `${c.months} th · SOP ${c.sop_passed} · ca ${c.field_days} · quyền ${c.acting}` : ""}>{c ? `${c.months}${c.done ? " ✓" : c.current ? " ▶" : ""}` : "—"}</td>; })}<td className="text-right font-bold">{rows.filter((x) => x.done).length}</td><td className="text-right">{rt ? `${Number(rt.avg).toFixed(1)}/5 (${String(rt.n)})` : "—"}</td></tr>; })}</tbody></table></div>
    </div>}
    {tab === "conghien" && <div className="grid md:grid-cols-2 gap-3">
      <div className="card p-0 overflow-auto"><div className="px-3 py-2 bg-slate-100 rounded-t-xl font-bold">Điểm cống hiến (công khai, cộng dồn)</div><table className="tbl text-sm"><thead><tr><th className="pl-3">#</th><th>Nhân sự</th><th>Bậc</th><th className="text-right">KPI</th><th className="text-right">GS</th><th className="text-right">Dạy</th><th className="text-right">Sáng kiến</th><th className="text-right">Thay người</th><th className="text-right">Tổng</th></tr></thead><tbody>
        {(contrib.rows ?? []).map((r, i) => <tr key={String(r.staff_id)}><td className="pl-3">{i + 1}</td><td>{String(r.full_name)}<div className="text-xs text-slate-500">{String(r.dept ?? "")}</div></td><td><Badge g={r.grade_cm} /> <Badge g={r.grade_gs} /></td><td className="text-right">{String(r.kpi_pts)}</td><td className="text-right">{Number(r.sup_pts).toFixed(0)}</td><td className="text-right">{String(r.teach_pts)}</td><td className="text-right">{String(r.init_pts)}</td><td className="text-right">{String(r.cover_pts)}</td><td className="text-right font-bold">{String(r.total)}</td></tr>)}</tbody></table></div>
      <div className="card p-0 overflow-auto"><div className="px-3 py-2 bg-slate-100 rounded-t-xl font-bold">Sáng kiến ({(inis.rows ?? []).length})</div><table className="tbl text-sm"><thead><tr><th className="pl-3">Người</th><th>Sáng kiến</th><th>Lợi ích</th><th>TT</th><th></th></tr></thead><tbody>
        {(inis.rows ?? []).map((r) => <tr key={String(r.id)}><td className="pl-3">{String(r.full_name)}</td><td>{String(r.title)}</td><td className="text-xs">{String(r.benefit ?? "")}</td><td className="text-xs">{String(r.status)}</td><td>{r.status === "DE_XUAT" && r.staff_id !== sess.staffId && ["owner", "director", "tech_head", "team_lead"].includes(sess.role) && <button className="btn-secondary !py-0.5 !px-2 !text-xs" onClick={async () => { await act("approve_initiative", { id: r.id }); reload(); }}>Duyệt</button>}</td></tr>)}</tbody></table></div>
    </div>}
    {tab === "luong" && <PayPanel sess={sess} canHR={canHR} />}
    {tab === "tieuchi" && <div className="space-y-3">{["CM", "GS"].map((t) => <div key={t} className="card p-0 overflow-auto"><div className="px-3 py-2 bg-slate-100 rounded-t-xl font-bold">{t === "CM" ? "Ngạch chuyên môn — 4 bậc" : "Ngạch Giám sát – Kế thừa — 4 bậc (công ty mẹ)"} <span className="text-xs font-normal text-slate-500">— tiêu chí là dữ liệu có phiên bản (sửa ở Quản trị DL › grade_scales); hệ số lương × lương vị trí = lương lớp 1</span></div><table className="tbl text-sm"><thead><tr><th className="pl-3">Bậc</th><th>Tên</th><th className="text-right">Hệ số</th><th>Điều kiện (tự tính)</th><th>Được gì</th></tr></thead><tbody>
      {S.filter((s) => s.track === t).map((s) => <tr key={String(s.code)}><td className="pl-3"><Badge g={s.code} /></td><td className="font-semibold">{String(s.name)}</td><td className="text-right">{String(s.salary_coef)}</td><td className="text-xs">{Object.entries((s.criteria ?? {}) as R).map(([k, v]) => <span key={k} className="inline-block mr-2 mb-0.5 rounded bg-slate-100 px-1.5">{CRIT_LABEL[k] ?? k}: <b>{String(v)}</b></span>)}</td><td className="text-xs">{String(s.perks ?? "")}</td></tr>)}</tbody></table></div>)}
      <div className="card text-sm"><b>Quan hệ Trưởng phòng ↔ Giám sát (3 tuyến, 1 sếp)</b><ul className="list-disc ml-5 mt-1 text-slate-700"><li>Tuyến 1 — trưởng phòng/tổ trưởng: giao việc, chấm công, tự kiểm, dạy 2–3h/tuần, đề xuất thưởng/bậc. Mỗi người chỉ có MỘT sếp.</li><li>Tuyến 2 — giám sát (công ty mẹ, biệt phái): kiểm độc lập theo tiêu chí, chấm điểm, ghi lỗi → CAPA, kiểm chéo, chấm thi. Không giao việc, không ra lệnh công nhân (trừ nguy hiểm tức thời).</li><li>Tuyến 3 — tuân thủ/audit: kiểm cả 2 tuyến theo chuẩn chứng nhận.</li><li>Nhịp tuần: T2–T5 kiểm (+1 ngày đi ca thật) → T6 lỗi đổ vào việc CAPA của trưởng phòng → T2 nộp biện pháp + nội dung dạy → GS chấm lại lỗi cũ. Lỗi lặp 3 tuần → trừ trưởng phòng.</li><li>Trưởng phòng chấm ngược GS (hữu ích/công tâm/hiểu nghề) — là điều kiện lên bậc GS. Trưởng phòng nghỉ → GS là người thay mặc định (bài thi "làm quyền").</li></ul></div>
    </div>}
  </div>;
}
function AddKeyPos({ staff, onDone }: { staff: R[]; onDone: () => void }) {
  const [f, setF] = useState<R | null>(null);
  if (!f) return <button className="btn-secondary !py-1 !text-xs ml-2" onClick={() => setF({ code: "", title: "", dept: "", holder_id: "", min_grade: "B3", track: "CM" })}>＋ Ghế then chốt</button>;
  return <div className="flex flex-wrap gap-1 mt-2"><input className="input !py-1" placeholder="Mã" aria-label="Mã" value={String(f.code)} onChange={(e) => setF({ ...f, code: e.target.value })} /><input className="input !py-1" placeholder="Tên ghế" aria-label="Tên ghế" value={String(f.title)} onChange={(e) => setF({ ...f, title: e.target.value })} /><input className="input !py-1" placeholder="Phòng" aria-label="Phòng" value={String(f.dept)} onChange={(e) => setF({ ...f, dept: e.target.value })} /><select className="input !py-1" value={String(f.holder_id)} onChange={(e) => setF({ ...f, holder_id: e.target.value })}><option value="">— người giữ —</option>{staff.map((s) => <option key={String(s.id)} value={String(s.id)}>{String(s.full_name)}</option>)}</select><select className="input !py-1" value={String(f.min_grade)} onChange={(e) => setF({ ...f, min_grade: e.target.value })}>{["B3", "B4", "GS2", "GS3", "PGD"].map((g) => <option key={g}>{g}</option>)}</select><button className="btn-primary !py-1 !text-xs" onClick={async () => { await act("key_position", { ...f, track: String(f.min_grade).startsWith("B") ? "CM" : "GS" }); setF(null); onDone(); }}>Lưu</button><button className="btn-secondary !py-1 !text-xs" onClick={() => setF(null)}>Hủy</button></div>;
}
function AddSuccessor({ kp, staff, onDone }: { kp: R; staff: R[]; onDone: () => void }) {
  const [sid, setSid] = useState(""); const [r, setR] = useState("2_NAM"); const [p, setP] = useState("");
  return <div className="flex flex-wrap gap-1 mt-2"><select className="input !py-1 !text-xs" value={sid} onChange={(e) => setSid(e.target.value)}><option value="">＋ người kế thừa</option>{staff.filter((s) => s.id !== kp.holder_id).map((s) => <option key={String(s.id)} value={String(s.id)}>{String(s.full_name)}</option>)}</select><select className="input !py-1 !text-xs" value={r} onChange={(e) => setR(e.target.value)}><option value="NGAY">Sẵn sàng ngay</option><option value="1_NAM">1 năm</option><option value="2_NAM">2 năm</option></select><input className="input !py-1 !text-xs" placeholder="Kế hoạch phát triển" aria-label="Kế hoạch phát triển" value={p} onChange={(e) => setP(e.target.value)} /><button className="btn-secondary !py-1 !text-xs" disabled={!sid} onClick={async () => { await act("succession", { key_position_id: kp.id, successor_id: sid, readiness: r, dev_plan: p }); setSid(""); setP(""); onDone(); }}>Lưu</button></div>;
}

const SETTING_LABEL: Record<string, string> = { "payroll.bhxh_employee_pct": "BHXH người LĐ %", "payroll.bhyt_employee_pct": "BHYT người LĐ %", "payroll.bhtn_employee_pct": "BHTN người LĐ %", "payroll.bhxh_employer_pct": "BHXH công ty %", "payroll.bhyt_employer_pct": "BHYT công ty %", "payroll.bhtn_employer_pct": "BHTN công ty %", "payroll.giam_tru_ban_than": "Giảm trừ bản thân/tháng", "payroll.giam_tru_phu_thuoc": "Giảm trừ mỗi người phụ thuộc", "payroll.kpi_bonus_base_pct": "KPI tối đa = % lương L1", "payroll.standard_days": "Ngày công chuẩn", "payroll.insurance_cap": "Trần lương đóng BH", "payroll.insure_probation": "Thử việc có đóng BH (0/1)", "bonus.deduct_per_point": "Tiền trừ mỗi điểm lỗi", "bonus.max_deduct_pct": "Trừ tối đa % thưởng", "supervision.checks_per_week": "Lượt kiểm/tuần mặc định", "training.hours_per_week": "Giờ học/tuần", "training.pass_score": "Điểm đậu bài thi" };
/** CƠ CHẾ LƯƠNG – THƯỞNG 4 lớp + định biên */
function PayPanel({ sess, canHR }: { sess: Sess; canHR: boolean }) {
  const ps = useData<R>("pay_structure"); const sc = useData<R>("salary_scales"); const hc = useData<R>("headcount"); const cb = useData<R>("contribution_bonus"); const st = useData<R>("pay_settings"); const dc = useData<R>("dependent_claims_pending"); const [msg, setMsg] = useState("");
  const yr = new Date().getFullYear(); const canMoney = ["owner", "director", "accountant"].includes(sess.role);
  const prevQ = (() => { const d = new Date(); const q = Math.floor(d.getMonth() / 3); return q === 0 ? `${d.getFullYear() - 1}-Q4` : `${d.getFullYear()}-Q${q}`; })();
  return <div className="space-y-3">
    <div className="card text-sm"><b>Thu nhập = 4 lớp, minh bạch, ai cũng tự tính được</b>
      <ol className="list-decimal ml-5 mt-1 text-slate-700"><li><b>Lớp 1 — Lương vị trí × hệ số bậc × ngày công</b>: thang lương theo vị trí (A1–A14) hoặc vai; hệ số bậc B1 1.00 → B4 1.60, GS1 1.35 → PGĐ 2.20. Lên bậc = tăng lương ngay, không xin-cho.</li><li><b>Lớp 2 — KPI & thưởng điều kiện tháng</b>: KPI ghi chép (× % lương) + thưởng tháng theo điều kiện học/dạy/thi/giám sát; lỗi giám sát trừ; <b>GS quá ngưỡng lỗi bỏ sót → mất thưởng</b>; trưởng phòng bị trừ theo lỗi lặp/CAPA quá hạn của phòng.</li><li><b>Lớp 3 — Phụ cấp</b>: ghế then chốt (theo ghế), biệt phái GS, độc hại/ca đêm (hồ sơ).</li><li><b>Lớp 4 — Thưởng cống hiến quý/năm</b>: điểm cống hiến × đơn giá (trần), chốt cuối quý, trả vào lương tháng đầu quý sau.</li></ol>
      <div className="text-xs text-slate-500 mt-1">Thang lương & hệ số là dữ liệu có phiên bản (Quản trị DL › salary_scales, grade_scales) — in được phụ lục HĐLĐ, đăng ký Sở LĐ. Bảng lương thật (Kế toán › Lương) đã dùng công thức này, ghi rõ nguồn từng người.</div>
      {canMoney && <button className="btn-secondary !py-1 !text-xs mt-1" onClick={async () => { const j = await act("close_contribution_bonus", { quarter: prevQ }); setMsg(j.error ? String(j.error) : `Đã chốt thưởng cống hiến ${prevQ}: ${j.n} người`); cb.reload(); }}>Chốt thưởng cống hiến {prevQ}</button>}{msg && <span className="ml-2 text-emerald-800 text-xs">{msg}</span>}</div>
    <div className="card p-0 overflow-auto"><div className="px-3 py-2 bg-slate-100 rounded-t-xl font-bold">Cơ cấu thu nhập từng người ({(ps.rows ?? []).length})</div><table className="tbl text-sm"><thead><tr><th className="pl-3">Nhân sự</th><th>Phòng</th><th>Bậc</th><th className="text-right">Thang</th><th className="text-right">Hệ số</th><th className="text-right">Lớp 1</th><th className="text-right">Phụ cấp</th><th className="text-right">Thưởng tháng tối đa</th><th>Nguồn</th><th>Phụ lục HĐLĐ</th></tr></thead><tbody>
      {(ps.rows ?? []).map((r) => <tr key={String(r.staff_id)}><td className="pl-3">{String(r.full_name)}<div className="text-xs text-slate-500">{String(r.position ?? r.role)}</div></td><td>{String(r.dept ?? "")}</td><td><Badge g={r.grade_gs ?? r.grade_cm} /></td><td className="text-right">{fmt.n(r.scale_amount)}</td><td className="text-right">{String(r.coef)}</td><td className="text-right font-bold">{fmt.n(r.base_l1)}</td><td className="text-right">{fmt.n(r.allowances_l3)}</td><td className="text-right">{fmt.n(r.bonus_l2_max)}</td><td className="text-xs">{String(r.source)}</td><td><a className="underline text-xs" href={`/in/phu-luc-luong/${r.staff_id}`} target="_blank" rel="noreferrer">🖨 In</a></td></tr>)}</tbody></table></div>
    <div className="grid md:grid-cols-2 gap-3">
      <div className="card p-0 overflow-auto"><div className="px-3 py-2 bg-slate-100 rounded-t-xl font-bold">Thang lương (lớp 1 cơ sở)</div><table className="tbl text-sm"><tbody>{(sc.rows ?? []).map((r) => <tr key={String(r.id)}><td className="pl-3 text-xs">{String(r.scope_kind)}</td><td>{String(r.scope_code)}</td><td className="text-xs">{String(r.note ?? "")}</td><td className="text-right">{fmt.n(r.base_amount)}</td><td className="text-xs">từ {fmt.d(r.effective_from)} · v{String(r.version)}</td></tr>)}</tbody></table></div>
      <div className="card p-0 overflow-auto"><div className="px-3 py-2 bg-slate-100 rounded-t-xl font-bold flex items-center gap-2">Định biên {yr} vs thực tế{canHR && <button className="ml-auto btn-secondary !py-0.5 !text-xs" onClick={async () => { const j = await act("suggest_headcount", { year: yr }); setMsg(j.error ? String(j.error) : `Đã gợi ý ${j.n} dòng định biên từ thực tế`); hc.reload(); }}>Gợi ý từ thực tế</button>}</div><DataBoundary loading={hc.loading} error={hc.error} empty={!hc.rows?.length} onRetry={hc.reload} emptyText={'Chưa có định biên — bấm "Gợi ý từ thực tế" rồi sửa theo kế hoạch năm.'}><table className="tbl text-sm"><thead><tr><th className="pl-3">Phòng</th><th>Vị trí</th><th className="text-right">Định biên</th><th className="text-right">Thực tế</th><th className="text-right">Quỹ lương L1/tháng</th></tr></thead><tbody>{(hc.rows ?? []).map((r) => <tr key={String(r.id ?? `${r.dept}${r.position_code}`)} className={Number(r.actual) > Number(r.planned) ? "bg-red-50" : ""}><td className="pl-3">{String(r.dept)}</td><td className="text-xs">{String(r.position_code ?? "")} {String(r.title ?? "")}</td><td className="text-right">{canHR ? <input className="input !py-0 !w-14 text-right" defaultValue={String(r.planned)} onBlur={async (e) => { if (Number(e.target.value) !== Number(r.planned)) { await act("headcount_set", { id: r.id, planned: Number(e.target.value), budget_month: r.budget_month }); hc.reload(); } }} /> : String(r.planned)}</td><td className="text-right font-bold">{String(r.actual)}</td><td className="text-right">{fmt.n(r.actual_base_month)}</td></tr>)}</tbody></table></DataBoundary></div>
    </div>
    <div className="grid md:grid-cols-2 gap-3">
      <div className="card p-0 overflow-auto"><div className="px-3 py-2 bg-slate-100 rounded-t-xl font-bold">⚙ Tham số lương · BH · thuế · thưởng · giám sát (cấu hình, có phiên bản)</div><table className="tbl text-sm"><tbody>{(st.rows ?? []).map((r) => <tr key={String(r.key)}><td className="pl-3 text-xs">{String(r.key)}<div className="text-[10px] text-slate-400">{SETTING_LABEL[String(r.key)] ?? ""} · {String(r.farm_id)} v{String(r.version)}</div></td><td className="text-right">{canMoney || canHR ? <input className="input !py-0 !w-32 text-right" defaultValue={String(typeof r.value === "string" ? r.value : JSON.stringify(r.value)).replace(/^"|"$/g, "")} onBlur={async (e) => { const v = e.target.value; const cur = String(typeof r.value === "string" ? r.value : JSON.stringify(r.value)).replace(/^"|"$/g, ""); if (v === cur) return; const j = await act("set_setting", { key: r.key, value: isNaN(Number(v)) ? v : Number(v) }); setMsg(j.error ? String(j.error) : `Đã lưu ${r.key} = ${v} (v${j.version})`); st.reload(); }} /> : String(typeof r.value === "string" ? r.value : JSON.stringify(r.value))}</td></tr>)}
        {[["payroll.insurance_cap", "Trần lương đóng BH (20× lương cơ sở)"], ["payroll.insure_probation", "Thử việc/thời vụ có đóng BH? (0/1)"], ["gs.omissions_max_month", "Ngưỡng lỗi GS/tháng trước khi mất thưởng"], ["gs.daily_checks_min", "Lượt kiểm tối thiểu/phòng/ngày"], ["pay.gs_secondment_allowance", "Phụ cấp biệt phái GS"], ["bonus.contribution_unit", "Đơn giá 1 điểm cống hiến"], ["bonus.contribution_cap", "Trần thưởng cống hiến/quý"], ["bonus.base_gs", "Thưởng tháng cơ sở GS"], ["bonus.head_repeat_points", "Điểm trừ trưởng phòng/lỗi lặp"], ["bonus.head_capa_points", "Điểm trừ trưởng phòng/CAPA quá hạn"]].filter(([k]) => !(st.rows ?? []).some((r) => r.key === k)).map(([k, l]) => <tr key={k}><td className="pl-3 text-xs">{k}<div className="text-[10px] text-slate-400">{l} · mặc định</div></td><td className="text-right">{(canMoney || canHR) && <input className="input !py-0 !w-32 text-right" placeholder="nhập để ghi đè" aria-label="nhập để ghi đè" onBlur={async (e) => { if (!e.target.value) return; const j = await act("set_setting", { key: k, value: Number(e.target.value) }); setMsg(j.error ? String(j.error) : `Đã lưu ${k}`); st.reload(); }} />}</td></tr>)}</tbody></table></div>
      <div className="card p-0 overflow-auto"><div className="px-3 py-2 bg-slate-100 rounded-t-xl font-bold">Khai người phụ thuộc chờ HCNS duyệt ({(dc.rows ?? []).length})</div><DataBoundary loading={dc.loading} error={dc.error} empty={!dc.rows?.length} onRetry={dc.reload} emptyText="Không có."><table className="tbl text-sm"><tbody>{(dc.rows ?? []).map((r) => <tr key={String(r.id)}><td className="pl-3">{String(r.full_name)}</td><td className="text-right">{String(r.dependents)} người</td><td className="text-xs">{String(r.note ?? "")}</td><td className="whitespace-nowrap">{canHR && <><button className="btn-primary !py-0.5 !px-2 !text-xs mr-1" onClick={async () => { await act("dependent_decide", { id: r.id, approve: true }); dc.reload(); }}>Duyệt</button><button className="text-xs underline" onClick={async () => { await act("dependent_decide", { id: r.id, approve: false }); dc.reload(); }}>từ chối</button></>}</td></tr>)}</tbody></table></DataBoundary></div>
    </div>
    <div className="card p-0 overflow-auto"><div className="px-3 py-2 bg-slate-100 rounded-t-xl font-bold">Thưởng cống hiến đã chốt (lớp 4)</div><table className="tbl text-sm"><tbody>{(cb.rows ?? []).slice(0, 30).map((r) => <tr key={String(r.id)}><td className="pl-3">{String(r.full_name)}</td><td className="text-xs">{String(r.ref_id)} → trả tháng {String(r.period)}</td><td className="text-right">{String(r.points)} đ</td><td className="text-right font-bold">{fmt.n(r.amount)}</td></tr>)}</tbody></table></div>
  </div>;
}
