"use client";
import Tabs from "@/components/Tabs";
import { useState } from "react";
import { useData, fmt, act } from "@/lib/client";
import { QcHoldPanel } from "@/components/panels/CloseoutBits";
import type { Sess } from "@/components/Shell";
import AnyChart from "@/components/AnyChart";
type R = Record<string, unknown>;
const adm = (t: string, row: R) => fetch(`/api/admin/${t}`, { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ row }) }).then((r) => r.json());
/** CHẾ BIẾN SÂU: kế hoạch SX tuần → MRP bung BOM đa cấp so tồn → thiếu hụt mua; bao bì 3 cấp; nhãn (thành phần/dị ứng/dinh dưỡng/HSD/claims); tem QR mẻ in hàng loạt; mẻ sơ chế/sấy/đóng gói + CCP */
export default function CheBien({ sess }: { sess: Sess }) {
  const [tab, setTab] = useState<"khsx" | "mrp" | "bom" | "baobi" | "nhan" | "tem" | "me" | "qc">("khsx");
  const plans = useData("production_plans"); const pos = useData("production_orders"); const [days, setDays] = useState("14"); const mrp = useData("mrp_run", { days }, [days]);
  const boms = useData("bom_headers"); const [bom, setBom] = useState<string | null>(null); const lines = useData(bom ? "bom_lines" : null, { bom: bom ?? undefined }, [bom]);
  const [exSku, setExSku] = useState(""); const [exQty, setExQty] = useState("100"); const ex = useData(exSku ? "mrp_explode" : null, { sku: exSku, qty: exQty }, [exSku, exQty]);
  const pk = useData("packaging_specs"); const lb = useData("label_specs"); const al = useData("allergens"); const lots = useData("lot_labels"); const pb = useData("pack_batches"); const products = useData("products");
  const [pf, setPf] = useState<R>({ week_start: new Date(Date.now() + ((8 - new Date().getDay()) % 7) * 864e5).toISOString().slice(0, 10), source: "DU_BAO", unit: "kg" }); const [msg, setMsg] = useState("");
  const canW = ["owner", "director", "tech_head", "team_lead", "it_engineer"].includes(sess.role);
  const P = products.rows ?? []; const TP = P.filter((p) => ["THANH_PHAM", "BAN_TP"].includes(String(p.kind)));
  const addPlan = async () => { const j = await adm("production_plans", { ...pf, qty_plan: Number(pf.qty_plan) }); setMsg(j.ok ? "Đã thêm kế hoạch" : `${j.error}: ${j.detail ?? ""}`); plans.reload(); mrp.reload(); };
  const setStatus = async (t: string, id: string, status: string) => { const j = await adm(t, { id, status }); setMsg(j.ok ? `Đã cập nhật ${status}` : `${j.error}: ${j.detail ?? ""}`); plans.reload(); boms.reload(); lb.reload(); mrp.reload(); };
  const short = (mrp.rows ?? []).filter((r) => Number(r.shortage) > 0);
  return (
    <div className="space-y-3">
      <div className="grid grid-cols-2 sm:grid-cols-4 gap-2"><div className="kpi"><div className="l">Kế hoạch SX mở</div><div className="v">{(plans.rows ?? []).filter((r) => r.status !== "XONG").length}</div></div><div className="kpi"><div className="l">Lệnh SX từ đơn</div><div className="v">{(pos.rows ?? []).filter((r) => r.status !== "XONG").length}</div></div><div className="kpi"><div className="l">Thiếu hụt MRP ({days} ngày)</div><div className={`v ${short.length ? "text-red-700" : ""}`}>{short.length}</div></div><div className="kpi"><div className="l">BOM ban hành / Nhãn duyệt</div><div className="v">{(boms.rows ?? []).filter((r) => r.status === "BAN_HANH").length} / {(lb.rows ?? []).filter((r) => r.status === "DUYET").length}</div></div></div>
      <Tabs items={[["khsx", "D5 & Chế biến · Kế hoạch SX tuần"], ["mrp", `D5 & Chế biến · MRP thiếu hụt (${short.length})`], ["bom", "D5 & Chế biến · BOM/định mức"], ["qc", "🔬 Giữ lô QC"], ["me", "Chế biến thực phẩm · Mẻ sơ chế/sấy/đóng gói + CCP"], ["baobi", "Chế biến thực phẩm · Bao bì 3 cấp"], ["nhan", "Chế biến thực phẩm · Nhãn (NĐ43/EU1169)"], ["tem", "Chế biến thực phẩm · Tem QR mẻ"]]} value={tab} onChange={(k) => setTab(k as typeof tab)} />
      {tab === "qc" && <QcHoldPanel sess={sess} />}
      {msg && <div className="rounded-xl bg-emerald-50 border border-emerald-300 px-3 py-2 text-sm">{msg}</div>}
      {tab === "khsx" && <div className="space-y-3">
        {canW && <div className="card"><b>Thêm kế hoạch SX tuần</b> <span className="text-xs text-stone-500">— nguồn: đơn hàng / dự báo / tồn min / hợp đồng; chuyển sang ĐANG SX → phát production.planned cho D5/Chế biến/Kho</span><div className="grid sm:grid-cols-3 lg:grid-cols-6 gap-2 mt-2"><input className="input" type="date" value={String(pf.week_start)} onChange={(e) => setPf({ ...pf, week_start: e.target.value })} /><select className="input" value={String(pf.sku ?? "")} onChange={(e) => setPf({ ...pf, sku: e.target.value })}><option value="">Thành phẩm</option>{TP.map((p) => <option key={String(p.sku)} value={String(p.sku)}>{String(p.name)}</option>)}</select><input className="input" type="number" placeholder="Số lượng" value={String(pf.qty_plan ?? "")} onChange={(e) => setPf({ ...pf, qty_plan: e.target.value })} /><select className="input" value={String(pf.source)} onChange={(e) => setPf({ ...pf, source: e.target.value })}>{[["DON_HANG", "Đơn hàng"], ["DU_BAO", "Dự báo"], ["TON_KHO_MIN", "Tồn kho min"], ["HOP_DONG", "Hợp đồng bao tiêu"]].map(([k, l]) => <option key={k} value={k}>{l}</option>)}</select><input className="input" placeholder="Dây chuyền (D5_TMR/DONG_GOI/SAY…)" value={String(pf.line ?? "")} onChange={(e) => setPf({ ...pf, line: e.target.value })} /><button className="btn-primary !py-2" disabled={!pf.sku || !pf.qty_plan} onClick={addPlan}>Thêm</button></div></div>}
        <div className="card p-0 overflow-auto"><table className="tbl text-sm"><thead><tr><th className="pl-3">Tuần</th><th>Thành phẩm</th><th className="text-right">KH</th><th className="text-right">Đã SX</th><th>Nguồn</th><th>Chuyền</th><th>TT</th><th></th></tr></thead><tbody>{(plans.rows ?? []).map((r) => <tr key={String(r.id)}><td className="pl-3">{fmt.d(String(r.week_start))}</td><td>{String(r.sku_name)} <span className="font-mono text-xs text-stone-500">{String(r.sku)}</span></td><td className="text-right">{fmt.n(Number(r.qty_plan))} {String(r.unit)}</td><td className="text-right">{fmt.n(Number(r.qty_done ?? 0))}</td><td>{String(r.source)}</td><td>{String(r.line ?? "")}</td><td><span className={`rounded-full px-2 text-xs ${r.status === "DANG_SX" ? "bg-amber-100" : r.status === "XONG" ? "bg-emerald-100" : "bg-stone-100"}`}>{String(r.status)}</span></td><td className="text-xs whitespace-nowrap">{canW && r.status === "KE_HOACH" && <button className="underline mr-2" onClick={() => setStatus("production_plans", String(r.id), "DANG_SX")}>▶ ban hành SX</button>}{canW && r.status === "DANG_SX" && <button className="underline mr-2" onClick={() => setStatus("production_plans", String(r.id), "XONG")}>✓ xong</button>}<button className="underline" onClick={() => { setExSku(String(r.sku)); setExQty(String(r.qty_plan)); setTab("bom"); }}>bung BOM</button></td></tr>)}</tbody></table></div>
        <div className="card p-0 overflow-auto"><div className="px-3 py-2 bg-stone-100 rounded-t-2xl font-bold">Lệnh sản xuất tự sinh từ đơn hàng (production_orders)</div><table className="tbl text-sm"><thead><tr><th className="pl-3">Mã</th><th>Đơn</th><th>SKU</th><th className="text-right">SL</th><th>Hạn</th><th>Chuyền</th><th>TT</th></tr></thead><tbody>{(pos.rows ?? []).slice(0, 50).map((r) => <tr key={String(r.id)}><td className="pl-3 font-mono">{String(r.id)}</td><td>{String(r.order_id ?? "")}</td><td>{String(r.sku)}</td><td className="text-right">{fmt.n(Number(r.qty))}</td><td>{String(r.due_date ?? "")}</td><td>{String(r.line ?? "")}</td><td>{String(r.status)}</td></tr>)}</tbody></table></div></div>}
      {tab === "mrp" && <div className="card p-0 overflow-auto"><div className="px-3 py-2 bg-stone-100 rounded-t-2xl font-bold flex items-center gap-2 flex-wrap">MRP — nhu cầu nguyên liệu/bao bì trong <input className="input !w-20 !py-1" value={days} onChange={(e) => setDays(e.target.value)} /> ngày = KHSX + đơn CHỐT + lệnh SX, bung BOM đa cấp, so tồn khả dụng (đã trừ giữ chỗ) <span className="text-xs font-normal text-stone-500">· thiếu → tạo PO ở Kho/Mua hàng · dòng có BOM = sản xuất nội bộ, không mua</span></div>
        <table className="tbl text-sm"><thead><tr><th className="pl-3">Thành phần</th><th>Loại</th><th className="text-right">Cần</th><th className="text-right">Tồn khả dụng</th><th className="text-right">Thiếu</th><th>Nguồn nhu cầu</th><th></th></tr></thead><tbody>{(mrp.rows ?? []).map((r) => <tr key={String(r.component_sku)} className={Number(r.shortage) > 0 ? (r.has_bom ? "bg-amber-50" : "bg-red-50") : ""}><td className="pl-3">{String(r.component_name)} <span className="font-mono text-xs text-stone-500">{String(r.component_sku)}</span></td><td className="text-xs">{r.is_packaging ? "bao bì" : r.has_bom ? "BTP (SX nội bộ)" : "nguyên liệu"}</td><td className="text-right">{fmt.n(Number(r.req_qty))} {String(r.unit)}</td><td className="text-right">{fmt.n(Number(r.available))}</td><td className={`text-right font-bold ${Number(r.shortage) > 0 ? "text-red-700" : "text-emerald-700"}`}>{fmt.n(Number(r.shortage))}</td><td className="text-xs">{String(r.sources)}</td><td className="text-xs">{Number(r.shortage) > 0 && !r.has_bom && <a className="underline" href={`/kho?tab=po&sku=${r.component_sku}&qty=${r.shortage}`}>tạo PO</a>}{Number(r.shortage) > 0 && r.has_bom ? <button className="underline" onClick={() => { setPf({ ...pf, sku: String(r.component_sku), qty_plan: String(r.shortage), source: "TON_KHO_MIN" }); setTab("khsx"); }}>→ KHSX</button> : null}</td></tr>)}</tbody></table>{!(mrp.rows ?? []).length && <div className="p-3 text-sm text-stone-500">Không có nhu cầu trong kỳ (chưa có KHSX/đơn chốt) hoặc SKU chưa có BOM ban hành.</div>}</div>}
      {tab === "bom" && <div className="grid lg:grid-cols-2 gap-3">
        <div className="card p-0 overflow-auto"><div className="px-3 py-2 bg-stone-100 rounded-t-2xl font-bold flex items-center gap-2">BOM (định mức) — đa cấp, có bao bì, hao hụt, hiệu suất <a className="ml-auto underline text-sm font-normal" href="/quan-tri?t=bom_headers">＋ BOM</a><a className="underline text-sm font-normal" href="/quan-tri?t=bom_lines">＋ dòng</a></div><table className="tbl text-sm"><thead><tr><th className="pl-3">Thành phẩm</th><th>v</th><th className="text-right">Mẻ</th><th className="text-right">HS %</th><th>Chuyền</th><th className="text-right">Dòng</th><th>TT</th><th></th></tr></thead><tbody>{(boms.rows ?? []).map((r) => <tr key={String(r.id)} className={bom === r.id ? "bg-emerald-50" : ""}><td className="pl-3"><button className="underline text-left" onClick={() => setBom(String(r.id))}>{String(r.sku_name)}</button> <span className="font-mono text-xs text-stone-500">{String(r.sku)}</span></td><td>{String(r.version)}</td><td className="text-right">{String(r.batch_size)} {String(r.unit)}</td><td className="text-right">{String(r.yield_pct)}</td><td>{String(r.line ?? "")}</td><td className="text-right">{String(r.n_lines)}</td><td>{String(r.status)}</td><td className="text-xs">{canW && r.status === "NHAP" && <button className="underline" onClick={() => setStatus("bom_headers", String(r.id), "BAN_HANH")}>ban hành</button>}</td></tr>)}</tbody></table>
          {bom && <div className="p-3 border-t"><b>Dòng BOM {bom}</b><table className="tbl text-sm mt-1"><thead><tr><th>#</th><th>Thành phần</th><th className="text-right">SL</th><th className="text-right">Hao %</th><th>Công đoạn</th><th>Loại</th></tr></thead><tbody>{(lines.rows ?? []).map((l) => <tr key={String(l.id)}><td>{String(l.seq)}</td><td>{String(l.component_name)} <span className="font-mono text-xs text-stone-500">{String(l.component_sku)}</span></td><td className="text-right">{String(l.qty)} {String(l.unit)}</td><td className="text-right">{String(l.scrap_pct ?? 0)}</td><td>{String(l.stage ?? "")}</td><td className="text-xs">{l.is_packaging ? "bao bì" : l.has_bom ? "BTP → có BOM con" : "nguyên liệu"}</td></tr>)}</tbody></table></div>}</div>
        <div className="card"><b>Bung BOM (explode) đa cấp</b><div className="flex gap-2 mt-2 flex-wrap"><select className="input !w-64" value={exSku} onChange={(e) => setExSku(e.target.value)}><option value="">Chọn thành phẩm</option>{[...new Set((boms.rows ?? []).map((b) => String(b.sku)))].map((s) => <option key={s} value={s}>{s}</option>)}</select><input className="input !w-28" type="number" value={exQty} onChange={(e) => setExQty(e.target.value)} /><span className="self-center text-sm text-stone-500">đơn vị thành phẩm</span></div>
          <table className="tbl text-sm mt-2"><thead><tr><th>Cấp</th><th>Thành phần</th><th className="text-right">Cần</th><th>Đường dẫn</th></tr></thead><tbody>{(ex.rows ?? []).map((r, i) => <tr key={i} className={r.is_packaging ? "text-stone-500" : ""}><td>{String(r.level)}</td><td style={{ paddingLeft: Number(r.level) * 12 }}>{String(r.component_name)} <span className="font-mono text-xs">{String(r.component_sku)}</span></td><td className="text-right">{fmt.n(Number(r.req_qty))} {String(r.unit)}</td><td className="text-xs">{String(r.path)}</td></tr>)}</tbody></table>{exSku && !(ex.rows ?? []).length && <div className="text-sm text-stone-500 mt-2">SKU chưa có BOM ban hành.</div>}</div></div>}
      {tab === "baobi" && <div className="card p-0 overflow-auto"><div className="px-3 py-2 bg-stone-100 rounded-t-2xl font-bold flex items-center gap-2">Thông số bao bì theo SKU — sơ cấp (tiếp xúc) · thứ cấp (thùng) · vận chuyển (pallet) <a className="ml-auto underline text-sm font-normal" href="/quan-tri?t=packaging_specs">＋ thêm/sửa</a></div><table className="tbl text-sm"><thead><tr><th className="pl-3">SKU</th><th>Cấp</th><th>Vật liệu</th><th>Kích thước mm</th><th className="text-right">Tịnh g</th><th className="text-right">Bì g</th><th className="text-right">ĐV/gói</th><th className="text-right">Gói/thùng</th><th className="text-right">Thùng/pallet</th><th>GTIN</th><th>Tái chế</th><th>HSD ngày</th><th>Bảo quản</th></tr></thead><tbody>{(pk.rows ?? []).map((r) => <tr key={String(r.id)}><td className="pl-3">{String(r.sku_name)} <span className="font-mono text-xs text-stone-500">{String(r.sku)}</span></td><td>{String(r.level)}</td><td>{String(r.material ?? "")}</td><td>{String(r.dims_mm ?? "")}</td><td className="text-right">{String(r.net_weight_g ?? "")}</td><td className="text-right">{String(r.gross_weight_g ?? "")}</td><td className="text-right">{String(r.units_per_pack ?? "")}</td><td className="text-right">{String(r.packs_per_case ?? "")}</td><td className="text-right">{String(r.cases_per_pallet ?? "")}</td><td className="font-mono text-xs">{String(r.gtin ?? "")}</td><td>{r.recyclable ? `♻ ${String(r.recycle_code ?? "")}` : ""}</td><td>{String(r.shelf_life_days ?? "")}</td><td>{String(r.storage_temp ?? "")}</td></tr>)}</tbody></table></div>}
      {tab === "nhan" && <div className="space-y-3"><div className="card p-0 overflow-auto"><div className="px-3 py-2 bg-stone-100 rounded-t-2xl font-bold flex items-center gap-2">Nhãn sản phẩm theo SKU/thị trường — nội dung bắt buộc NĐ 43/2017 (tên, thành phần, định lượng, NSX/HSD, bảo quản, xuất xứ, tổ chức chịu trách nhiệm) + dị ứng (EU 1169/2011) + dinh dưỡng (TT 29/2023) + claims/dấu chuẩn <a className="ml-auto underline text-sm font-normal" href="/quan-tri?t=label_specs">＋ nhãn</a></div><table className="tbl text-sm"><thead><tr><th className="pl-3">SKU</th><th>TT</th><th>v</th><th>Tên trên nhãn</th><th>Thành phần</th><th>Dị ứng</th><th>Định lượng</th><th>HSD</th><th>Dấu chuẩn</th><th>Claims</th><th>TT</th><th></th></tr></thead><tbody>{(lb.rows ?? []).map((r) => <tr key={String(r.id)}><td className="pl-3">{String(r.sku_name)} <span className="font-mono text-xs text-stone-500">{String(r.sku)}</span></td><td>{String(r.market)}</td><td>{String(r.version)}</td><td className="font-semibold">{String(r.product_name ?? "")}</td><td className="max-w-[260px] truncate" title={String(r.ingredients ?? "")}>{String(r.ingredients ?? "")}</td><td className="text-red-700 font-semibold">{((r.allergens as string[]) ?? []).join(", ")}</td><td>{String(r.net_content ?? "")}</td><td>{String(r.shelf_life_days ?? "")} ngày</td><td className="text-xs">{((r.std_marks as string[]) ?? []).join(" · ")}{r.halal ? " · HALAL" : ""}{r.organic ? " · HỮU CƠ" : ""}</td><td className="text-xs">{((r.claims as string[]) ?? []).join(" · ")}</td><td><span className={`rounded-full px-2 text-xs ${r.status === "DUYET" ? "bg-emerald-100" : "bg-stone-100"}`}>{String(r.status)}</span></td><td className="text-xs whitespace-nowrap">{canW && r.status === "NHAP" && <button className="underline mr-2" onClick={() => setStatus("label_specs", String(r.id), "DUYET")}>duyệt</button>}<a className="underline" href={`/quan-tri?t=label_specs&pk=${r.id}`}>sửa</a></td></tr>)}</tbody></table></div>
        <div className="card text-sm"><b>Danh mục chất gây dị ứng ({(al.rows ?? []).length})</b> — {(al.rows ?? []).map((a) => `${a.code}: ${a.name_vi}`).join(" · ")}<div className="text-xs text-stone-500 mt-1">Nguồn: EU 1169/2011 Phụ lục II · Codex STAN 1-1985 §4.2.1.4. Claims phải có bằng chứng (hồ sơ điều trị 0 kháng sinh, chứng nhận). Nhãn xuất khẩu tạo bản theo thị trường (market=EU/JP/KR/HALAL) và ngôn ngữ.</div></div></div>}
      {tab === "tem" && <div className="card p-0 overflow-auto"><div className="px-3 py-2 bg-stone-100 rounded-t-2xl font-bold flex items-center gap-2">Tem QR theo lô/mẻ — QR sinh nội bộ (không gọi dịch vụ ngoài) → /trace/{"{lô}"} công khai; nhãn lấy từ label_specs đã duyệt <a className="ml-auto underline text-sm font-normal" href="/in/nhan-lo/all" target="_blank">in nhãn lô nhỏ (24)</a></div><table className="tbl text-sm"><thead><tr><th className="pl-3">Lô</th><th>SKU</th><th>Tên nhãn</th><th>NSX</th><th>HSD</th><th>Dị ứng</th><th>Nhãn</th><th></th></tr></thead><tbody>{(lots.rows ?? []).map((r) => <tr key={String(r.lot_id)}><td className="pl-3 font-mono text-xs">{String(r.lot_id)}</td><td>{String(r.sku_name)}</td><td>{String(r.product_name ?? "")}</td><td>{String(r.mfg_date ?? "").slice(0, 10)}</td><td>{String(r.expiry_date ?? "").slice(0, 10)}</td><td className="text-red-700">{((r.allergens as string[]) ?? []).join(", ")}</td><td>{r.product_name ? <span className="text-emerald-700">✓ có nhãn duyệt</span> : <span className="text-amber-700">chưa có nhãn → in tem cơ bản</span>}</td><td className="text-xs whitespace-nowrap"><a className="underline mr-2" href={`/in/tem/${encodeURIComponent(String(r.lot_id))}?n=8`} target="_blank">in 8 tem đủ nhãn</a><a className="underline mr-2" href={`/in/tem/${encodeURIComponent(String(r.lot_id))}?n=48`} target="_blank">48</a><a className="underline" href={`/trace/${encodeURIComponent(String(r.lot_id))}`} target="_blank">xem trace</a></td></tr>)}</tbody></table></div>}
      {tab === "me" && <div className="space-y-3"><div className="grid md:grid-cols-2 gap-3"><div className="card"><AnyChart title="Sản lượng mẻ chế biến theo dây chuyền" table="batch_logs" col="id" agg="count" dim="line" bucket="week" height={220} /></div><div className="card"><AnyChart title="Nhiệt độ mẻ (°C) theo chuyền — CCP" table="batch_logs" col="temp_c" dim="line" bucket="day" height={220} /></div></div>
        <div className="card p-0 overflow-auto"><div className="px-3 py-2 bg-stone-100 rounded-t-2xl font-bold">Mẻ sơ chế / sấy / đóng gói (batch_logs) → đầu ra gắn lô → tem QR; ghi mẻ ở Ca của tôi (form Mẻ D5/khu D) hoặc /ca</div><table className="tbl text-sm"><thead><tr><th className="pl-3">Lúc</th><th>Mã mẻ</th><th>Chuyền</th><th>SKU ra</th><th className="text-right">SL</th><th>Lô</th><th>QC</th><th>CCP</th><th>Người</th></tr></thead><tbody>{(pb.rows ?? []).map((r, i) => <tr key={i}><td className="pl-3">{fmt.dt(String(r.ts))}</td><td className="font-mono text-xs">{String(r.batch_code)}</td><td>{String(r.line)}</td><td>{String(r.sku)}</td><td className="text-right">{fmt.n(Number(r.qty))}</td><td className="font-mono text-xs">{String(r.lot_id ?? "")}</td><td className="text-xs">{JSON.stringify(r.qc ?? {}).slice(0, 60)}</td><td className="text-xs">{Array.isArray(r.ccp_readings) && (r.ccp_readings as unknown[]).length ? `${(r.ccp_readings as unknown[]).length} điểm` : ""}</td><td className="text-xs">{String(r.created_by ?? "")}</td></tr>)}</tbody></table>{!(pb.rows ?? []).length && <div className="p-3 text-sm text-stone-500">Chưa có mẻ chế biến có đầu ra.</div>}</div></div>}
    </div>
  );
}
