"use client";
import { useState } from "react";
import { useData, act, fmt } from "@/lib/client";
import type { Sess } from "@/components/Shell";

const MODULES = [["bo", "Bò sinh sản + vỗ béo"], ["ga", "Gà 2 khối"], ["ras", "RAS/ao/bè"], ["de", "Dê"], ["trun", "Trùn/BSF/biogas/compost"], ["d5", "Xưởng D5"], ["cb", "Chế biến"], ["kd", "Bán hàng"], ["resort", "Resort/MICE"], ["rnd", "R&D"], ["xnk", "Xuất nhập khẩu"], ["custody", "Chăm sóc hộ/nhận nuôi"], ["vien", "Kinh tế viền"]];

/** Quản trị công ty: khai báo trại, module theo trại, nhân sự, cài đặt & định mức theo trại, vùng */
export function CompanyPanel({ sess }: { sess: Sess }) {
  const farms = useData("farms"); const regions = useData("regions"); const staff = useData("staff_all"); const settings = useData("farm_settings"); const norms = useData("norms");
  const [tab, setTab] = useState<"trai" | "moi" | "ns" | "caidat">("trai"); const [f, setF] = useState<Record<string, unknown>>({ kind: "CAMPUS", modules: { bo: true, ga: true, trun: true, d5: true, kd: true } });
  const [ns, setNs] = useState<Record<string, string>>({ role: "worker" }); const [msg, setMsg] = useState("");
  const isOwner = ["owner", "it_engineer"].includes(sess.role);
  const mods = (f.modules as Record<string, boolean>) ?? {};
  return (
    <div className="space-y-3">
      <div className="flex gap-2 overflow-x-auto">{[["trai", `Trại (${farms.rows?.length ?? 0})`], ["moi", "+ Khai báo trại mới"], ["ns", "Nhân sự & phân trại"], ["caidat", "Cài đặt · định mức theo trại"]].map(([k, l]) => <button key={k} className={`px-4 py-2 rounded-xl font-semibold whitespace-nowrap ${tab === k ? "bg-green-700 text-white" : "bg-white border"}`} onClick={() => setTab(k as typeof tab)}>{l}</button>)}</div>
      {tab === "trai" && <div className="grid md:grid-cols-2 gap-3">{(farms.rows ?? []).map((fm) => { const m = (fm.modules as Record<string, boolean>) ?? {}; return <div key={String(fm.id)} className="card"><div className="flex items-center gap-2"><span className="text-2xl font-black">{String(fm.id)}</span><span className="font-semibold">{String(fm.name)}</span><span className={`ml-auto ${fm.status === "ACTIVE" ? "b-grn" : "b-gray"}`}>{String(fm.status)}</span></div>
        <div className="text-sm text-stone-600 mt-1">{String(fm.region_name ?? fm.region_id ?? "—")} · {String(fm.province ?? "")} · {String(fm.kind)} · S {String(fm.s_ha ?? "?")} ha · K {String(fm.k_factor ?? "?")} · {String(fm.legal_entity ?? "")}</div>
        <div className="flex flex-wrap gap-1 mt-2">{MODULES.map(([k, l]) => <button key={k} disabled={!isOwner && sess.role !== "director"} className={`text-xs rounded-full px-2 py-0.5 border ${m[k] ? "bg-green-100 border-green-400 text-green-900" : "bg-stone-100 text-stone-500"}`} title={l} onClick={async () => { await act("update_farm", { id: fm.id, modules: { ...m, [k]: !m[k] } }); farms.reload(); }}>{m[k] ? "✓ " : ""}{l}</button>)}</div>
        <div className="flex gap-2 mt-2 text-sm flex-wrap"><a className="underline font-semibold" href={`/hq/trai/${fm.id}`}>📋 Hồ sơ trại (diện tích · hạ tầng · nhân sự)</a><button className="underline" onClick={async () => { await fetch("/api/auth/switch-farm", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ farm_id: fm.id }) }); location.href = "/gd"; }}>Vào trại →</button><a className="underline" href={`/api/exports/all?farm=${fm.id}`}>Xuất toàn bộ dữ liệu trại</a>{isOwner && fm.status === "ACTIVE" && <button className="underline text-red-700" onClick={async () => { if (confirm(`Lưu trữ (đóng) trại ${fm.id}? Dữ liệu giữ nguyên, chỉ ẩn khỏi vận hành.`)) { await act("update_farm", { id: fm.id, status: "ARCHIVED" }); farms.reload(); } }}>Lưu trữ</button>}</div></div>; })}</div>}
      {tab === "moi" && <div className="card space-y-2">
        <h3 className="font-bold">Khai báo trại mới — tự sinh 9 kho, 12 trung tâm chi phí, khu mặc định, quỹ, năm tài chính; kế thừa SKU/SOP/KPI/alert/RC toàn công ty; dữ liệu tách hoàn toàn theo `farm_id` (RLS)</h3>
        {!isOwner && <div className="text-red-700 text-sm">Chỉ chủ đầu tư / KS công nghệ được khai báo trại.</div>}
        <div className="grid sm:grid-cols-3 gap-2">
          <input className="input" placeholder="Mã trại (F02)" value={String(f.id ?? "")} onChange={(e) => setF({ ...f, id: e.target.value.toUpperCase() })} />
          <input className="input sm:col-span-2" placeholder="Tên trại" value={String(f.name ?? "")} onChange={(e) => setF({ ...f, name: e.target.value })} />
          <select className="input" value={String(f.region_id ?? "")} onChange={(e) => setF({ ...f, region_id: e.target.value })}><option value="">Vùng (tham số tỉnh)</option>{(regions.rows ?? []).map((r) => <option key={String(r.id)} value={String(r.id)}>{String(r.name)}</option>)}</select>
          <input className="input" placeholder="Tỉnh" value={String(f.province ?? "")} onChange={(e) => setF({ ...f, province: e.target.value })} />
          <input className="input" placeholder="Pháp nhân con (Cty TNHH ITRAN F02)" value={String(f.legal_entity ?? "")} onChange={(e) => setF({ ...f, legal_entity: e.target.value })} />
          <select className="input" value={String(f.kind)} onChange={(e) => setF({ ...f, kind: e.target.value })}><option value="CAMPUS">Campus (10–60 ha)</option><option value="HUB">Hub (chế biến–sinh học trung tâm)</option><option value="VE_TINH">Vệ tinh (&lt;3 ha, không bò)</option><option value="SANDBOX">Sandbox đào tạo</option></select>
          <input className="input" type="number" placeholder="S hữu dụng (ha)" value={String(f.s_ha ?? "")} onChange={(e) => setF({ ...f, s_ha: Number(e.target.value) })} />
          <input className="input" type="number" placeholder="K (bò/ha sinh khối: 15–28)" value={String(f.k_factor ?? "")} onChange={(e) => setF({ ...f, k_factor: Number(e.target.value) })} />
        </div>
        {f.s_ha ? <div className="text-sm bg-green-50 rounded-xl p-2">Thế số nhanh (Lớp B): đất sinh khối ≈ {fmt.n(Number(f.s_ha) * 0.55, 1)} ha → đàn ≈ <b>{fmt.n(Number(f.s_ha) * 0.55 * Number(f.k_factor || 23))} con</b> · lõi ≈ {fmt.n(Math.max(0.08 * Number(f.s_ha), Number(f.s_ha) < 10 ? 0.45 : 1.2), 2)} ha · mặt nước ≈ {fmt.n(Number(f.s_ha) * 0.1, 1)} ha · dải: {Number(f.s_ha) < 3 ? "vệ tinh (không bò)" : Number(f.s_ha) < 10 ? "3–10 ha (bò vỗ béo)" : Number(f.s_ha) < 30 ? "10–30 ha (campus chuẩn)" : Number(f.s_ha) < 60 ? "30–60 ha (đủ resort)" : ">60 ha → nhân nhiều campus/HUB"}</div> : null}
        <div className="text-sm"><b>Module bật:</b> {MODULES.map(([k, l]) => <label key={k} className="ml-2 inline-block"><input type="checkbox" checked={!!mods[k]} onChange={() => setF({ ...f, modules: { ...mods, [k]: !mods[k] } })} /> {l}</label>)}</div>
        <button className="btn-primary" disabled={!isOwner} onClick={async () => { const j = await act("create_farm", f); setMsg(j.id ? `Đã tạo trại ${j.id} — chuyển ngữ cảnh ở header để vào` : j.error); farms.reload(); }}>Tạo trại</button>{msg && <div className="text-sm">{msg}</div>}
      </div>}
      {tab === "ns" && <div className="space-y-3">
        {isOwner && <div className="card"><h3 className="font-bold">Thêm nhân sự</h3><div className="flex flex-wrap gap-2 mt-2"><input className="input !w-48" placeholder="Họ tên" value={ns.full_name ?? ""} onChange={(e) => setNs({ ...ns, full_name: e.target.value })} /><input className="input !w-32" placeholder="Login" value={ns.login ?? ""} onChange={(e) => setNs({ ...ns, login: e.target.value })} /><input className="input !w-24" placeholder="PIN" value={ns.pin ?? ""} onChange={(e) => setNs({ ...ns, pin: e.target.value })} /><select className="input !w-36" value={ns.role} onChange={(e) => setNs({ ...ns, role: e.target.value })}>{["worker","team_lead","tech_head","director","accountant","it_engineer","auditor","owner"].map((r) => <option key={r}>{r}</option>)}</select><input className="input !w-40" placeholder="Vị trí (A1 TMR…)" value={ns.position ?? ""} onChange={(e) => setNs({ ...ns, position: e.target.value })} /><select className="input !w-28" value={ns.farm_id ?? sess.farmId} onChange={(e) => setNs({ ...ns, farm_id: e.target.value })}>{(farms.rows ?? []).map((fm) => <option key={String(fm.id)}>{String(fm.id)}</option>)}</select><input className="input !w-36" placeholder="SĐT" value={ns.phone ?? ""} onChange={(e) => setNs({ ...ns, phone: e.target.value })} /><button className="btn-primary !py-2" onClick={async () => { const j = await act("create_staff", ns); setMsg(j.id ? `Đã tạo ${j.id}` : j.error); staff.reload(); }}>Thêm</button></div>{msg && <div className="text-sm mt-1">{msg}</div>}</div>}
        <div className="card p-0 overflow-auto"><table className="tbl"><thead><tr><th className="pl-3">Mã</th><th>Tên</th><th>Vai</th><th>Vị trí</th><th>Trại chính</th><th>Được xem</th><th></th></tr></thead><tbody>{(staff.rows ?? []).map((s) => <tr key={String(s.id)}><td className="pl-3 font-mono">{String(s.id)}</td><td>{String(s.full_name)}</td><td>{String(s.role)}</td><td className="text-sm">{String(s.position ?? "")}</td><td>{String(s.farm_id ?? "HQ")}</td><td className="text-xs">{(s.farm_ids as string[] ?? []).join(", ")}</td><td>{isOwner && <select className="input !py-1 !text-sm !w-auto" defaultValue="" onChange={async (e) => { if (!e.target.value) return; await act("assign_staff_farm", { staff_id: s.id, add_farm_id: e.target.value }); staff.reload(); }}><option value="">+ thêm trại…</option>{(farms.rows ?? []).map((fm) => <option key={String(fm.id)} value={String(fm.id)}>{String(fm.id)}</option>)}</select>}</td></tr>)}</tbody></table></div></div>}
      {tab === "caidat" && <div className="grid md:grid-cols-2 gap-3">
        <div className="card"><h3 className="font-bold">Cài đặt (GLOBAL kế thừa → trại {sess.farmId} ghi đè, có phiên bản)</h3><SettingEditor rows={settings.rows ?? []} onSaved={() => settings.reload()} canGlobal={isOwner} /></div>
        <div className="card"><h3 className="font-bold">Định mức (NORM) — công thức Lớp B</h3><NormEditor rows={norms.rows ?? []} onSaved={() => norms.reload()} canGlobal={isOwner} /></div>
      </div>}
    </div>);
}
function SettingEditor({ rows, onSaved, canGlobal }: { rows: Record<string, unknown>[]; onSaved: () => void; canGlobal: boolean }) {
  const [k, setK] = useState(""); const [v, setV] = useState(""); const [scope, setScope] = useState("FARM");
  const seen = new Set<string>();
  return (<div><div className="flex flex-wrap gap-2 mt-2"><input className="input !w-56" placeholder="key (vd feed.meal_times)" value={k} onChange={(e) => setK(e.target.value)} /><input className="input !w-56" placeholder='giá trị JSON (vd ["06:00","15:00"] hoặc 45)' value={v} onChange={(e) => setV(e.target.value)} /><select className="input !w-32" value={scope} onChange={(e) => setScope(e.target.value)}><option value="FARM">Trại</option>{canGlobal && <option value="GLOBAL">Toàn cty</option>}</select><button className="btn-secondary !py-2" onClick={async () => { let val: unknown; try { val = JSON.parse(v); } catch { val = v; } await act("set_setting", { key: k, value: val, scope }); onSaved(); }}>Lưu</button></div>
    <table className="tbl mt-2"><tbody>{rows.filter((r) => { const key = `${r.key}`; if (seen.has(key)) return false; seen.add(key); return true; }).map((r) => <tr key={String(r.key)} className="cursor-pointer hover:bg-stone-50" onClick={() => { setK(String(r.key)); setV(JSON.stringify(r.value)); }}><td className="font-mono text-sm">{String(r.key)}</td><td className="text-sm">{JSON.stringify(r.value)}</td><td className="text-xs text-stone-500">{String(r.farm_id)} v{String(r.version)}</td></tr>)}</tbody></table></div>);
}
function NormEditor({ rows, onSaved, canGlobal }: { rows: Record<string, unknown>[]; onSaved: () => void; canGlobal: boolean }) {
  const [f, setF] = useState<Record<string, string>>({ scope: "FARM" });
  return (<div><div className="flex flex-wrap gap-2 mt-2"><input className="input !w-40" placeholder="kind (TA_KG_CON_NGAY)" value={f.kind ?? ""} onChange={(e) => setF({ ...f, kind: e.target.value })} /><input className="input !w-32" placeholder="subject (BO)" value={f.subject ?? ""} onChange={(e) => setF({ ...f, subject: e.target.value })} /><input className="input !w-28" type="number" placeholder="giá trị" value={f.value ?? ""} onChange={(e) => setF({ ...f, value: e.target.value })} /><input className="input !w-28" placeholder="đơn vị" value={f.unit ?? ""} onChange={(e) => setF({ ...f, unit: e.target.value })} /><select className="input !w-32" value={f.scope} onChange={(e) => setF({ ...f, scope: e.target.value })}><option value="FARM">Trại</option>{canGlobal && <option value="GLOBAL">Toàn cty</option>}</select><button className="btn-secondary !py-2" onClick={async () => { if (!f.kind || !f.value) return; await act("set_norm", { ...f, value: Number(f.value) }); onSaved(); }}>Lưu</button></div>
    <table className="tbl mt-2"><tbody>{rows.map((r) => <tr key={String(r.id)} className="cursor-pointer hover:bg-stone-50" onClick={() => setF({ scope: r.farm_id ? "FARM" : "GLOBAL", kind: String(r.kind), subject: String(r.subject ?? ""), value: String(r.value), unit: String(r.unit ?? "") })}><td className="font-mono text-sm">{String(r.kind)}</td><td>{String(r.subject ?? "")}</td><td className="text-right font-bold">{fmt.n(r.value, 2)}</td><td className="text-sm">{String(r.unit ?? "")}</td><td className="text-xs text-stone-500">{r.farm_id ? String(r.farm_id) : "GLOBAL"}</td></tr>)}</tbody></table></div>);
}
