"use client";
import { useState } from "react";
import { useData, act, fmt } from "@/lib/client";
import type { Sess } from "@/components/Shell";
import Tabs from "@/components/Tabs";
import { BarChart, Bar, LineChart, Line, XAxis, YAxis, Tooltip, Legend, CartesianGrid, ResponsiveContainer } from "recharts";
import { usePrompt } from "@/components/ui/PromptDialog";
type R = Record<string, unknown>;
/** ĐÀO TẠO (2–3h/tuần, cấp trên dạy cấp dưới toàn bộ SOP → thuần thục → học SOP cấp trên; kiểm tra người khác chấm) & THƯỞNG THÁNG (điều kiện dạy + học + kiểm tra + giám sát; trừ lỗi) → vào lương */
export default function DaoTaoThuong({ sess }: { sess: Sess }) {
  const [tab, setTab] = useState<"tuan" | "nangluc" | "thuong" | "so">("tuan");
  const my = useData("my_training"); const stats = useData("training_stats"); const cm = useData("competency_matrix"); const [period, setPeriod] = useState(new Date(Date.now() - 30 * 864e5).toISOString().slice(0, 7)); const be = useData("bonus_eval", { period }, [period]); const led = useData("bonus_ledger"); const staff = useData("staff");
  const [msg, setMsg] = useState(""); const canMgr = ["owner", "director", "tech_head", "it_engineer"].includes(sess.role); const canFin = ["owner", "director", "accountant"].includes(sess.role);
  const { prompt, promptElement } = usePrompt();
  const done = async (t: R) => { const hours = await prompt({ title: "Hoàn thành buổi học", label: "Số giờ thực dạy/học?", type: "number", min: 0, defaultValue: String(t.planned_hours ?? 2.5) }); if (!hours) return; const score = await prompt({ title: "Chấm điểm kiểm tra", label: "Điểm kiểm tra (0–100, đạt ≥ 80)?", type: "number", min: 0, defaultValue: "85" }); if (!score) return; let examiner = ""; if (String(t.trainer_id) === sess.staffId) { examiner = (await prompt({ title: "Người chấm", label: "Người chấm (mã NS, PHẢI khác người dạy; để trống = hệ thống/QA)", type: "text", required: false })) ?? ""; } else examiner = sess.staffId === t.trainee_id ? "" : sess.staffId; const j = await act("complete_training", { id: t.id, hours: Number(hours), score: Number(score), examiner_id: examiner || null }); setMsg(j.ok ? `Đã ghi buổi học — ${j.passed ? "ĐẠT" : "chưa đạt"}, năng lực: ${j.level ?? ""}` : String(j.error)); my.reload(); cm.reload(); };
  const B = be.rows ?? []; const elig = B.filter((r) => r.eligible).length;
  return <div className="space-y-3">
    {promptElement}
    <Tabs items={[["tuan", `Đào tạo tuần (${(my.rows ?? []).filter((t) => t.status === "KE_HOACH").length} chưa xong)`], ["nangluc", "Ma trận năng lực"], ["thuong", `Thưởng tháng ${period} (${elig}/${B.length} đủ ĐK)`], ["so", "Sổ thưởng"]]} value={tab} onChange={(k) => setTab(k as typeof tab)} right={canMgr ? <button className="btn-secondary !py-1.5 !px-3 text-sm" onClick={async () => { const j = await act("gen_training_week", {}); setMsg(j.ok ? `Đã sinh lịch: ${j.training} buổi học, ${j.supervision} việc giám sát` : String(j.error)); my.reload(); }}>＋ Sinh lịch tuần này</button> : undefined} />
    {msg && <div className="rounded-xl bg-emerald-50 border border-emerald-300 px-3 py-2 text-sm">{msg}</div>}
    {tab === "tuan" && <div className="space-y-3"><div className="card p-0 overflow-auto"><div className="px-3 py-2 bg-slate-100 rounded-t-xl font-bold">Buổi dạy/học của tôi & cấp dưới (8 tuần) — chủ đề = SOP kế tiếp chưa thuần thục của người học; xong buổi → điểm kiểm tra → năng lực lên bậc; người chấm ≠ người dạy</div><table className="tbl text-sm"><thead><tr><th className="pl-3">Tuần</th><th>Người học</th><th>Người dạy</th><th>Chủ đề (SOP)</th><th className="text-right">Giờ KH</th><th className="text-right">Thực</th><th className="text-right">Điểm</th><th>TT</th><th></th></tr></thead><tbody>{(my.rows ?? []).map((t) => <tr key={String(t.id)} className={t.status === "KE_HOACH" ? "bg-amber-50" : t.status === "BO_LO" ? "bg-red-50" : ""}><td className="pl-3">{fmt.d(String(t.week_start))}</td><td>{String(t.trainee_name)}</td><td className="text-xs">{String(t.trainer_name)}</td><td>{String(t.topic_title ?? "")} <span className="font-mono text-xs text-slate-500">{String(t.topic_code ?? "")}</span></td><td className="text-right">{String(t.planned_hours)}</td><td className="text-right">{String(t.actual_hours ?? "")}</td><td className={`text-right font-bold ${t.score != null && Number(t.score) < 80 ? "text-red-700" : ""}`}>{String(t.score ?? "")}</td><td><span className="rounded-full px-2 text-xs bg-slate-100">{String(t.status)}</span></td><td className="text-xs">{t.status === "KE_HOACH" && (t.trainer_id === sess.staffId || t.trainee_id === sess.staffId || canMgr) && <button className="underline" onClick={() => done(t)}>✓ hoàn thành + chấm</button>}</td></tr>)}</tbody></table>{!(my.rows ?? []).length && <div className="p-3 text-sm text-slate-500">Chưa có lịch — GĐ/KTT bấm "Sinh lịch tuần này" (job đêm thứ Hai tự sinh).</div>}</div>
      <div className="card"><div className="text-sm font-bold">Đào tạo theo tuần: kế hoạch / hoàn thành / điểm TB (26 tuần)</div><div style={{ height: 220 }}><ResponsiveContainer><BarChart data={(stats.rows ?? []).map((r) => ({ wk: fmt.d(String(r.week_start)).slice(0, 5), planned: Number(r.planned), done: Number(r.done), score: Number(r.avg_score ?? 0) }))}><CartesianGrid strokeDasharray="3 3" /><XAxis dataKey="wk" tick={{ fontSize: 10 }} /><YAxis yAxisId="l" tick={{ fontSize: 10 }} /><YAxis yAxisId="r" orientation="right" domain={[0, 100]} tick={{ fontSize: 10 }} /><Tooltip /><Legend wrapperStyle={{ fontSize: 11 }} /><Bar yAxisId="l" dataKey="planned" name="Buổi kế hoạch" fill="#cbd5e1" /><Bar yAxisId="l" dataKey="done" name="Hoàn thành" fill="#059669" /><Line yAxisId="r" type="monotone" dataKey="score" name="Điểm TB" stroke="#f59e0b" strokeWidth={2} /></BarChart></ResponsiveContainer></div></div></div>}
    {tab === "nangluc" && <div className="card p-0 overflow-auto"><div className="px-3 py-2 bg-slate-100 rounded-t-xl font-bold">Ma trận năng lực: mỗi người × SOP vị trí (CHƯA HỌC → HỌC → THỰC HÀNH → THUẦN THỤC → DẠY ĐƯỢC); 100% thuần thục → học SOP cấp trên</div><table className="tbl text-sm"><thead><tr><th className="pl-3">Nhân sự</th><th>BP</th><th className="text-right">SOP vị trí</th><th className="text-right">Thuần thục</th><th className="text-right">Thực hành</th><th className="text-right">Chưa học</th><th>Tiến độ</th></tr></thead><tbody>{(cm.rows ?? []).map((r) => <tr key={String(r.staff_id)}><td className="pl-3">{String(r.full_name)}</td><td className="text-xs">{String(r.dept)}</td><td className="text-right">{String(r.n_sop)}</td><td className="text-right text-emerald-700 font-bold">{String(r.mastered)}</td><td className="text-right">{String(r.practicing)}</td><td className="text-right text-red-700">{String(r.not_started)}</td><td><div className="h-2 w-40 rounded bg-slate-100 overflow-hidden"><div className="h-2 bg-emerald-500" style={{ width: `${r.pct}%` }} /></div><span className="text-xs">{String(r.pct)}%</span></td></tr>)}</tbody></table></div>}
    {tab === "thuong" && <div className="space-y-3"><div className="card flex flex-wrap items-center gap-2 text-sm"><b>Kỳ</b><input className="input !w-32 !py-1" value={period} onChange={(e) => setPeriod(e.target.value)} /><span className="text-xs text-slate-500">Điều kiện: học ≥80% giờ (nếu chưa thuần thục hết SOP) · dạy ≥80% buổi (nếu có cấp dưới) · ≥1 bài kiểm tra ĐẠT · giám sát ≥80% lượt (nếu được phân công) → mức thưởng theo vai (settings bonus.base_*) − điểm lỗi × {fmt.vnd(50000)}</span>{canFin && <><button className="ml-auto btn-secondary !py-1 !px-3" onClick={async () => { const j = await act("close_bonus", { period }); setMsg(j.ok ? `Đã chốt thưởng ${j.n} người vào sổ` : String(j.error)); led.reload(); }}>Chốt sổ thưởng {period}</button><button className="btn-primary !py-1 !px-3" onClick={async () => { const j = await act("apply_bonus", { month: period + "-01" }); setMsg(j.ok ? `Đã đưa vào ${j.n} phiếu lương (kpi_bonus)` : String(j.error)); }}>→ Vào bảng lương</button></>}</div>
      <div className="card p-0 overflow-auto"><table className="tbl text-sm"><thead><tr><th className="pl-3">Nhân sự</th><th>Vai</th><th className="text-right">Học (h)</th><th className="text-right">Dạy (buổi)</th><th className="text-right">KT đạt</th><th className="text-right">Giám sát</th><th className="text-right">Điểm lỗi</th><th className="text-right">Trừ</th><th>Đủ ĐK</th><th className="text-right">Thưởng</th></tr></thead><tbody>{B.map((r) => <tr key={String(r.staff_id)} className={r.eligible ? "" : "bg-red-50"}><td className="pl-3">{String(r.full_name)}{r.mastered_all ? <span className="text-xs text-emerald-700"> · thuần thục 100%</span> : null}</td><td className="text-xs">{String(r.role)} · {String(r.dept)}</td><td className={`text-right ${!r.learn_ok ? "text-red-700 font-bold" : ""}`}>{fmt.n(Number(r.learn_hours))}/{fmt.n(Number(r.learn_required))}</td><td className={`text-right ${!r.teach_ok ? "text-red-700 font-bold" : ""}`}>{String(r.teach_sessions)}/{String(r.teach_required)}</td><td className={`text-right ${!r.test_ok ? "text-red-700 font-bold" : ""}`}>{String(r.tests_passed)}/{String(r.tests)}</td><td className={`text-right ${!r.supervise_ok ? "text-red-700 font-bold" : ""}`}>{String(r.supervise_checks)}/{String(r.supervise_required)}</td><td className="text-right">{fmt.n(Number(r.fault_points))}</td><td className="text-right text-red-700">{fmt.vnd(Number(r.deduction))}</td><td>{r.eligible ? "✓" : "✗"}</td><td className="text-right font-bold">{fmt.vnd(Number(r.bonus))}</td></tr>)}</tbody></table></div></div>}
    {tab === "so" && <div className="card p-0 overflow-auto"><table className="tbl text-sm"><thead><tr><th className="pl-3">Kỳ</th><th>Nhân sự</th><th>Loại</th><th className="text-right">Điểm lỗi</th><th className="text-right">Tiền</th><th>Giải trình</th></tr></thead><tbody>{(led.rows ?? []).map((r) => <tr key={String(r.id)}><td className="pl-3">{String(r.period)}</td><td>{String(r.full_name)}</td><td className="text-xs">{String(r.kind)}</td><td className="text-right">{String(r.points ?? 0)}</td><td className="text-right font-bold">{fmt.vnd(Number(r.amount))}</td><td className="text-xs">{String(r.note ?? "")}</td></tr>)}</tbody></table></div>}
  </div>;
}
