"use client";
import { PlPanel, KpiLuongPanel } from "@/components/panels/Extra";
import SupplyPlan from "@/components/panels/SupplyPlan";
import Tabs from "@/components/Tabs";
import { GlPanel, AttendancePanel } from "@/components/panels/More";
import { ProductionPanel } from "@/components/panels/Fulfillment";
import { PayrollPanel, AssetsPanel } from "@/components/panels/PayrollAssets";
import { BudgetPanel, CashflowPanel } from "@/components/panels/Finance";
import { FinanceMorePanel } from "@/components/panels/FinanceMore";
import { useState } from "react";
import DaoTaoThuong from "@/components/panels/DaoTaoThuong";
import Link from "next/link";
import { useData, act, fmt } from "@/lib/client";
import type { Sess } from "@/components/Shell";
import { KpiTile } from "./Dashboards";

/** KẾ HOẠCH — vụ (KH vs thực) · cho ăn 7 ngày (KH vs thực) */
export function KeHoachPanel({ sess }: { sess: Sess }) {
  const [khTab, setKhTab] = useState<"cc" | "vu">("cc");
  const sp = useData("season_plans"); const fp = useData("feed_plan_vs_actual"); const plots = useData("plots"); const cycles = useData("cycles");
  const [f, setF] = useState<Record<string, string>>({});
  const canW = ["team_lead","tech_head","director","owner"].includes(sess.role);
  const byDay = new Map<string, { plan: number; actual: number }>(); for (const r of fp.rows ?? []) { const k = String(r.day).slice(0, 10); const o = byDay.get(k) ?? { plan: 0, actual: 0 }; o.plan += Number(r.plan_kg); o.actual += Number(r.actual_kg); byDay.set(k, o); }
  return (
    <div className="space-y-3"><Tabs items={[["cc", "📊 Ban kế hoạch · Cung–cầu (đàn → thức ăn → đất → mua)"], ["vu", "Vụ & cho ăn · KH vs thực"]]} value={khTab} onChange={(k) => setKhTab(k as typeof khTab)} />{khTab === "cc" && <SupplyPlan sess={sess} />}{khTab !== "cc" && <div className="space-y-4">
      <div className="card"><div className="flex flex-wrap items-center gap-2"><h3 className="font-bold">Cho ăn: kế hoạch (định mức × số con) vs thực — 7 ngày</h3>{canW && <button className="btn-secondary !py-1 !px-3 !text-sm ml-auto" onClick={async () => { await act("gen_feed_plans", {}); fp.reload(); }}>↻ Sinh KH 7 ngày tới</button>}</div>
        <div className="grid grid-cols-4 sm:grid-cols-8 gap-1 mt-2">{[...byDay.entries()].sort().map(([d, v]) => <div key={d} className={`rounded-xl p-2 text-center ${v.actual === 0 ? "bg-stone-100" : Math.abs(v.actual - v.plan) / (v.plan || 1) > 0.05 ? "bg-amber-50 border border-amber-300" : "bg-green-50"}`}><div className="text-xs text-stone-500">{d.slice(5)}</div><div className="font-bold">{fmt.n(v.actual)}</div><div className="text-xs">KH {fmt.n(v.plan)}</div></div>)}</div>
        <table className="tbl mt-2"><thead><tr><th>Ngày</th><th>Đàn</th><th className="text-right">KH kg</th><th className="text-right">Thực kg</th><th className="text-right">Lệch</th></tr></thead><tbody>{(fp.rows ?? []).slice(0, 40).map((r, i) => { const d = Number(r.actual_kg) - Number(r.plan_kg); return <tr key={i}><td>{fmt.d(r.day)}</td><td>{String(r.group_name)}</td><td className="text-right">{fmt.n(r.plan_kg)}</td><td className="text-right font-bold">{fmt.n(r.actual_kg)}</td><td className={`text-right ${Math.abs(d) / (Number(r.plan_kg) || 1) > 0.05 && Number(r.actual_kg) > 0 ? "text-amber-700" : ""}`}>{Number(r.actual_kg) ? fmt.n(d) : "—"}</td></tr>; })}</tbody></table></div>
      <div className="card"><h3 className="font-bold">Kế hoạch vụ theo lô (năng suất KH vs thực)</h3>
        {canW && <div className="flex flex-wrap gap-2 mt-2"><select className="input !w-48" value={f.plot_id ?? ""} onChange={(e) => setF({ ...f, plot_id: e.target.value })}><option value="">Lô</option>{(plots.rows ?? []).map((p) => <option key={String(p.id)} value={String(p.id)}>{String(p.name)}</option>)}</select><input className="input !w-32" placeholder="Cây" value={f.crop ?? ""} onChange={(e) => setF({ ...f, crop: e.target.value })} /><input className="input !w-40" placeholder="Giống" value={f.variety ?? ""} onChange={(e) => setF({ ...f, variety: e.target.value })} /><input className="input !w-40" type="date" value={f.sow_date ?? ""} onChange={(e) => setF({ ...f, sow_date: e.target.value })} /><input className="input !w-40" type="date" value={f.harvest_date ?? ""} onChange={(e) => setF({ ...f, harvest_date: e.target.value })} /><input className="input !w-36" type="number" placeholder="KH kg" value={f.plan_yield_kg ?? ""} onChange={(e) => setF({ ...f, plan_yield_kg: e.target.value })} /><button className="btn-secondary !py-2" onClick={async () => { if (!f.plot_id || !f.crop) return; await act("add_season_plan", { ...f, plan_yield_kg: Number(f.plan_yield_kg || 0) || null, cycle_id: (plots.rows ?? []).find((p) => p.id === f.plot_id)?.cycle_id ?? null }); setF({}); sp.reload(); }}>+ Kế hoạch vụ</button></div>}
        <table className="tbl mt-2"><thead><tr><th>Lô</th><th>Cây · giống</th><th>Gieo</th><th>Thu KH</th><th className="text-right">KH kg</th><th className="text-right">Thực kg</th><th className="text-right">%</th></tr></thead><tbody>{(sp.rows ?? []).map((r) => <tr key={String(r.id)}><td>{String(r.plot_name)}</td><td>{String(r.crop)} {String(r.variety ?? "")}</td><td>{fmt.d(r.sow_date)}</td><td>{fmt.d(r.harvest_date)}</td><td className="text-right">{fmt.n(r.plan_yield_kg)}</td><td className="text-right font-bold">{fmt.n(r.actual_kg)}</td><td className="text-right">{r.plan_yield_kg ? fmt.n((100 * Number(r.actual_kg)) / Number(r.plan_yield_kg)) + "%" : "—"}</td></tr>)}{!sp.rows?.length && <tr><td colSpan={7} className="text-stone-500 py-3">Chưa có kế hoạch vụ — thêm ở trên (lịch vụ khung 12 tháng theo tỉnh nằm ở regions.params).</td></tr>}</tbody></table></div>
      <div className="card"><h3 className="font-bold">Chu kỳ đang mở</h3><div className="flex flex-wrap gap-2 mt-1">{(cycles.rows ?? []).filter((c) => c.status === "MO").map((c) => <span key={String(c.id)} className="b-gray">{String(c.kind)} · {String(c.group_name ?? c.plot_name)} · từ {fmt.d(c.start_date)}</span>)}</div><Link className="underline text-sm" href="/dan">Quản lý chu kỳ →</Link></div>
    </div>}
    </div>);
}

/** THÚ Y */
export function ThuYPanel({ sess }: { sess: Sess }) {
  const board = useData("vet_board"); const drugs = useData("drug_stock"); const vs = useData("vaccine_schedules"); const tp = useData("treatment_protocols"); const tasks = useData("tasks_today");
  const vac = (tasks.rows ?? []).filter((t) => t.kind === "VACCINE"); const wd = (board.rows ?? []).filter((r) => r.withdrawal_until && new Date(String(r.withdrawal_until)) > new Date());
  return (
    <div className="space-y-4">
      <div className="grid grid-cols-2 sm:grid-cols-4 gap-2"><KpiTile l="Đang theo dõi (bệnh/điều trị 14 ngày)" v={board.rows?.length ?? "—"} warn={(board.rows?.length ?? 0) > 0 ? "yel" : null} /><KpiTile l="Đang ngưng thuốc — không xuất" v={wd.length} warn={wd.length ? "red" : null} /><KpiTile l="Vaccine đến hạn (việc)" v={vac.length} warn={vac.length > 20 ? "yel" : null} /><KpiTile l="Thuốc/vaccine sắp hết hạn" v={(drugs.rows ?? []).filter((d) => d.expiry_date && new Date(String(d.expiry_date)) < new Date(Date.now() + 60 * 86400e3)).length} /></div>
      <div className="grid md:grid-cols-2 gap-3">
        <div className="card p-0 overflow-auto"><div className="px-3 py-2 font-bold bg-stone-100 rounded-t-2xl">Bảng theo dõi con vật (thú y hợp đồng đứng tên phác đồ; KTV nội bộ thao tác)</div><table className="tbl"><thead><tr><th className="pl-3">Con</th><th>TT</th><th>Ngưng đến</th><th>Điều trị gần nhất</th><th>Vaccine gần nhất</th><th className="text-right">Bệnh 90n</th></tr></thead><tbody>{(board.rows ?? []).map((r) => <tr key={String(r.id)}><td className="pl-3"><Link className="underline font-bold" href={`/dan/${r.id}`}>{String(r.visual_tag ?? r.id)}</Link></td><td><span className={r.status === "BENH" ? "b-yel" : "b-gray"}>{String(r.status)}</span></td><td>{r.withdrawal_until && new Date(String(r.withdrawal_until)) > new Date() ? <span className="b-red">{fmt.d(r.withdrawal_until)}</span> : "—"}</td><td>{fmt.dt(r.last_treatment)}</td><td>{fmt.dt(r.last_vaccine)}</td><td className="text-right">{String(r.sick_90d)}</td></tr>)}{!board.rows?.length && <tr><td colSpan={6} className="p-3 text-stone-500">Không có con nào đang theo dõi.</td></tr>}</tbody></table></div>
        <div className="card p-0 overflow-auto"><div className="px-3 py-2 font-bold bg-stone-100 rounded-t-2xl">Kho thuốc – vaccine – giống (K1)</div><table className="tbl"><thead><tr><th className="pl-3">Hàng</th><th>Lô</th><th className="text-right">Tồn</th><th>Hạn</th></tr></thead><tbody>{(drugs.rows ?? []).map((d, i) => <tr key={i} className={d.expiry_date && new Date(String(d.expiry_date)) < new Date(Date.now() + 60 * 86400e3) ? "bg-amber-50" : ""}><td className="pl-3">{String(d.product_name)}</td><td className="font-mono text-xs">{String(d.lot_id ?? "").split("-").slice(3).join("-")}</td><td className="text-right font-bold">{fmt.n(d.qty)} {String(d.unit ?? "")}</td><td>{fmt.d(d.expiry_date)}</td></tr>)}</tbody></table></div>
        <div className="card"><h3 className="font-bold">Lịch vaccine (theo pháp lệnh · tham số vùng)</h3><table className="tbl"><tbody>{(vs.rows ?? []).map((v) => <tr key={String(v.id)}><td>{String(v.species)}</td><td className="font-semibold">{String(v.name)}</td><td className="text-sm">từ {String(v.age_days_min)} ngày tuổi{v.repeat_days ? ` · nhắc lại ${v.repeat_days} ngày` : ""}</td><td>{v.mandatory ? <span className="b-red">bắt buộc</span> : ""}</td></tr>)}</tbody></table></div>
        <div className="card"><h3 className="font-bold">Phác đồ đã ký (chỉ dùng phác đồ ký; ghi DIEU_TRI kèm ngưng thuốc)</h3><table className="tbl"><tbody>{(tp.rows ?? []).map((t) => <tr key={String(t.id)}><td className="font-mono">{String(t.id)}</td><td>{String(t.name)}<div className="text-xs text-stone-500">{String(t.indication ?? "")}</div></td><td className="text-sm">{String(t.drug_sku)} · {String(t.dose_per_kg)}/kg · {String(t.route)} · {String(t.days)} ngày</td><td><span className="b-yel">ngưng {String(t.withdrawal_days)} ngày</span></td></tr>)}</tbody></table><div className="text-xs text-stone-500 mt-1">Vai {sess.role}. Kháng sinh chỉ điều trị cá thể theo chỉ định thú y; không kháng sinh thường xuyên; không hormone tăng trọng.</div></div>
      </div>
    </div>);
}

/** NHÂN SỰ */
export function NhanSuPanel({ sess }: { sess: Sess }) {
  const [nsTab, setNsTab] = useState<"dt" | "ns">("dt");
  const st = useData("staff_activity"); const sops = useData("sops");
  const canW = ["director","owner","it_engineer"].includes(sess.role);
  const due = (d: unknown) => d && new Date(String(d)) < new Date(Date.now() + 30 * 86400e3);
  return (
    <div className="space-y-3"><Tabs items={[["dt", "🎓 Đào tạo & Thưởng (giám sát · học · dạy · kiểm tra → lương)"], ["ns", "Hồ sơ nhân sự · chứng chỉ SOP · sức khỏe"]]} value={nsTab} onChange={(k) => setNsTab(k as typeof nsTab)} right={<a className="btn-secondary !py-1.5 !px-3 text-sm" href="/giam-sat">Giám sát →</a>} />{nsTab === "dt" && <DaoTaoThuong sess={sess} />}{nsTab === "ns" && <div className="space-y-3">
      <ProductionPanel sess={sess} />
      <PayrollPanel sess={sess} />
      <AttendancePanel sess={sess} />
      <KpiLuongPanel sess={sess} />
      <div className="grid grid-cols-2 sm:grid-cols-4 gap-2"><KpiTile l="Nhân sự đang làm" v={st.rows?.length ?? "—"} /><KpiTile l="Khám SK / ATTP sắp hạn (30n)" v={(st.rows ?? []).filter((r) => due(r.health_check_due) || due(r.food_safety_training_due)).length} /><KpiTile l="Công nhân 7 ngày không ghi" v={(st.rows ?? []).filter((r) => r.role === "worker" && Number(r.records_30d) === 0).length} warn={(st.rows ?? []).some((r) => r.role === "worker" && Number(r.records_30d) === 0) ? "yel" : null} /><KpiTile l="SOP ban hành" v={(sops.rows ?? []).filter((s) => s.status === "BAN_HANH").length} sub="chứng chỉ nội bộ theo SOP" /></div>
      <div className="card p-0 overflow-auto"><div className="px-3 py-2 font-bold bg-stone-100 rounded-t-2xl">Nhân sự · chứng chỉ SOP · sức khỏe · hoạt động 30 ngày (KPI ghi chép — lương lớp 2)</div><table className="tbl"><thead><tr><th className="pl-3">Mã</th><th>Tên</th><th>Vai/vị trí</th><th>Chứng chỉ SOP</th><th>Khám SK</th><th>ATTP</th><th className="text-right">Bản ghi</th><th className="text-right">Checklist xanh</th><th className="text-right">Việc xong</th><th></th></tr></thead><tbody>
        {(st.rows ?? []).map((r) => <tr key={String(r.id)}><td className="pl-3 font-mono">{String(r.id)}</td><td>{String(r.full_name)}</td><td className="text-sm">{String(r.role)} · {String(r.position ?? "")}</td><td className="text-xs">{Array.isArray(r.sop_certs) && (r.sop_certs as string[]).length ? (r.sop_certs as string[]).join(", ") : <span className="text-amber-700">chưa</span>}</td><td className={due(r.health_check_due) ? "text-amber-700" : ""}>{fmt.d(r.health_check_due)}</td><td className={due(r.food_safety_training_due) ? "text-amber-700" : ""}>{fmt.d(r.food_safety_training_due)}</td><td className="text-right">{String(r.records_30d)}</td><td className="text-right">{String(r.checklists_green_30d)}/{String(r.checklists_30d)}</td><td className="text-right">{String(r.tasks_done_30d)}</td><td>{canW && <button className="underline text-xs" onClick={async () => { const c = prompt("Chứng chỉ SOP (mã cách nhau bởi dấu phẩy):", Array.isArray(r.sop_certs) ? (r.sop_certs as string[]).join(",") : ""); if (c == null) return; const h = prompt("Hạn khám SK (YYYY-MM-DD):", String(r.health_check_due ?? "").slice(0, 10)); const a = prompt("Hạn tập huấn ATTP (YYYY-MM-DD):", String(r.food_safety_training_due ?? "").slice(0, 10)); await act("update_staff", { staff_id: r.id, sop_certs: c.split(",").map((x) => x.trim()).filter(Boolean), health_check_due: h || null, food_safety_training_due: a || null }); st.reload(); }}>sửa</button>}</td></tr>)}
      </tbody></table></div>
      <div className="text-xs text-stone-500">Luật: không SOP ký = không giao việc; ma trận dự phòng ≥80% kỹ năng cho vị trí then chốt; lương 4 lớp (KPI tháng chấm từ bản ghi).</div>
    </div>}</div>);
}

/** THIẾT BỊ – MÁY MÓC – CÔNG NGHỆ */
export function ThietBiPanel({ sess }: { sess: Sess }) {
  const dev = useData("device_board"); const jobs = useData("job_runs"); const inc = useData("incidents_open");
  const machines = (dev.rows ?? []).filter((d) => d.fuel_l_per_h || d.maint_cycle_h); const sensors = (dev.rows ?? []).filter((d) => String(d.kind).startsWith("SENSOR") || ["CAMERA","CAN_CAU","CAN_XE_TRON"].includes(String(d.kind)));
  const off = sensors.filter((d) => d.last_seen && new Date(String(d.last_seen)) < new Date(Date.now() - 3600e3));
  return (
    <div className="space-y-3">
      <div className="grid grid-cols-2 sm:grid-cols-4 gap-2"><KpiTile l="Máy đến hạn bảo dưỡng" v={machines.filter((d) => d.maint_cycle_h && Number(d.machine_hours) >= Number(d.maint_cycle_h) * 0.9).length} warn={machines.some((d) => d.maint_cycle_h && Number(d.machine_hours) >= Number(d.maint_cycle_h)) ? "yel" : null} /><KpiTile l="Cảm biến mất tín hiệu >1h" v={off.length} warn={off.length ? "red" : null} /><KpiTile l="Sự cố thiết bị mở" v={(inc.rows ?? []).filter((i) => i.kind === "THIET_BI").length} /><KpiTile l="Job đêm gần nhất" v={jobs.rows?.[0] ? fmt.dt(jobs.rows[0].started_at) : "—"} sub={jobs.rows?.[0] ? String(jobs.rows[0].job) : ""} /></div>
      <div className="grid md:grid-cols-2 gap-3">
        <div className="card p-0 overflow-auto"><div className="px-3 py-2 font-bold bg-stone-100 rounded-t-2xl">Máy móc — giờ máy · bảo dưỡng · định mức dầu</div><table className="tbl"><thead><tr><th className="pl-3">Máy</th><th className="text-right">Giờ máy</th><th className="text-right">Chu kỳ BD</th><th className="text-right">l/giờ</th><th>Việc mở</th></tr></thead><tbody>{machines.map((d) => <tr key={String(d.id)} className={d.maint_cycle_h && Number(d.machine_hours) >= Number(d.maint_cycle_h) ? "bg-amber-50" : ""}><td className="pl-3 font-semibold">{String(d.name)}<div className="text-xs text-stone-500 font-mono">{String(d.id)}</div></td><td className="text-right">{fmt.n(d.machine_hours, 1)}</td><td className="text-right">{fmt.n(d.maint_cycle_h)}</td><td className="text-right">{fmt.n(d.fuel_l_per_h)}</td><td>{String(d.open_tasks)}</td></tr>)}</tbody></table></div>
        <div className="card p-0 overflow-auto"><div className="px-3 py-2 font-bold bg-stone-100 rounded-t-2xl">Cảm biến / cân / camera — tín hiệu · hiệu chuẩn</div><table className="tbl"><thead><tr><th className="pl-3">Thiết bị</th><th>Loại</th><th>Tín hiệu cuối</th><th>Hiệu chuẩn kế</th></tr></thead><tbody>{sensors.map((d) => <tr key={String(d.id)} className={d.last_seen && new Date(String(d.last_seen)) < new Date(Date.now() - 3600e3) ? "bg-red-50" : ""}><td className="pl-3 font-semibold">{String(d.name)}</td><td className="text-sm">{String(d.kind)}</td><td className="text-sm">{d.last_seen ? fmt.dt(d.last_seen) : <span className="text-stone-400">chưa có dữ liệu</span>}</td><td className="text-sm">{fmt.d(d.calib_next ?? d.calib_due)}</td></tr>)}</tbody></table></div>
        <div className="card"><h3 className="font-bold">Nhật ký job đêm (đối soát · cảnh báo · việc · tổng hợp)</h3><table className="tbl"><tbody>{(jobs.rows ?? []).slice(0, 15).map((j) => <tr key={String(j.id)}><td>{fmt.dt(j.started_at)}</td><td>{String(j.job)}</td><td>{j.ok ? <span className="b-grn">OK</span> : <span className="b-red">lỗi</span>}</td></tr>)}{!jobs.rows?.length && <tr><td className="text-stone-500">Chưa có — chạy `POST /api/jobs/all` (cron 01:00).</td></tr>}</tbody></table></div>
        <div className="card"><h3 className="font-bold">Chuẩn công nghệ ({sess.farmId})</h3><ul className="text-sm list-disc pl-5"><li>Uptime ≥98%, cảnh báo phản hồi &lt;15', backup ngày + xuất CSV tuần</li><li>Mọi thay đổi ngưỡng cảnh báo có vết (bảng alert_rules)</li><li>Trần chi công nghệ 4–6% doanh thu; mua theo bài toán hoàn vốn</li><li>Điện thoại cấp phát: khóa màn hình, thu hồi phiên ≤1h (Tài khoản)</li></ul></div>
      </div>
    </div>);
}

/** KẾ TOÁN */
export function KeToanPanel({ sess }: { sess: Sess }) {
  const exp = useData("expense_requests"); const po = useData("po_all"); const locks = useData("period_locks"); const funds = useData("funds"); const aging = useData("receivable_aging"); const recon = useData("recon_latest");
  const [day, setDay] = useState(new Date(Date.now() - 86400e3).toISOString().slice(0, 10)); const stockAt = useData("stock_at", { day });
  const [lockTo, setLockTo] = useState(""); const canLock = ["director","owner","accountant"].includes(sess.role);
  const from = new Date(new Date().getFullYear(), new Date().getMonth(), 1).toISOString().slice(0, 10), to = new Date().toISOString().slice(0, 10);
  return (
    <div className="space-y-3">
      <CashflowPanel />
      <FinanceMorePanel sess={sess} />
      <BudgetPanel sess={sess} />
      <GlPanel sess={sess} />
      <AssetsPanel sess={sess} />
      <PlPanel sess={sess} />
      <div className="grid grid-cols-2 sm:grid-cols-4 gap-2"><KpiTile l="Chi chờ duyệt / thiếu chữ ký 2" v={(exp.rows ?? []).filter((e) => ["CHO_DUYET","DUYET_1"].includes(String(e.status))).length} /><KpiTile l="PO chờ duyệt" v={(po.rows ?? []).filter((p) => p.po_status === "CHO_DUYET").length} /><KpiTile l="Công nợ >30 ngày" v={fmt.vnd((aging.rows ?? []).reduce((a, r) => a + Number(r.d30p ?? 0), 0))} warn={(aging.rows ?? []).some((r) => Number(r.d30p) > 0) ? "red" : null} /><KpiTile l="RC10 tiền vs hàng (kỳ gần nhất)" v={String((recon.rows ?? []).find((r) => r.rule_code === "RC10")?.status ?? "—")} /></div>
      <div className="grid md:grid-cols-2 gap-3">
        <div className="card"><h3 className="font-bold">Xuất cho kế toán/thuế (tháng này)</h3><div className="grid gap-2 mt-2">{[["sales-tax", "Bảng kê bán hàng"], ["purchases", "Bảng kê mua hàng"], ["stock-ledger", "Thẻ kho"], ["stock-balance", "Tồn kho hiện tại"], ["herd", "Sổ đàn (tài sản sinh học)"], ["recon", "Kết quả đối soát"]].map(([k, l]) => <a key={k} className="btn-secondary !py-2 !text-base justify-start" href={`/api/exports/${k}?from=${from}&to=${to}`}>⬇ {l}</a>)}</div></div>
        <div className="card"><h3 className="font-bold">Khóa kỳ (sau ngày 5 không ghi lùi; sửa qua điều chỉnh có duyệt)</h3><div className="text-sm">Đã khóa đến: <b>{locks.rows?.[0] ? fmt.d(locks.rows[0].period_end) : "chưa khóa"}</b></div>{canLock && <div className="flex gap-2 mt-2"><input type="date" className="input !w-48" value={lockTo} onChange={(e) => setLockTo(e.target.value)} /><button className="btn-primary !py-2" onClick={async () => { if (!lockTo || !confirm(`Khóa mọi bản ghi có ngày ≤ ${lockTo}?`)) return; await act("lock_period", { period_end: lockTo }); locks.reload(); }}>Khóa kỳ</button></div>}
          <h3 className="font-bold mt-4">Tồn kho tại ngày</h3><input type="date" className="input !w-48" value={day} onChange={(e) => setDay(e.target.value)} /><table className="tbl mt-1"><tbody>{(stockAt.rows ?? []).slice(0, 30).map((r, i) => <tr key={i}><td>{String(r.warehouse_code)}</td><td>{String(r.product_name)}</td><td className="text-right font-bold">{fmt.n(r.qty, 1)}</td></tr>)}{!stockAt.rows?.length && <tr><td className="text-stone-500">Chưa có snapshot ngày này (job đêm tạo).</td></tr>}</tbody></table></div>
        <div className="card p-0 overflow-auto"><div className="px-3 py-2 font-bold bg-stone-100 rounded-t-2xl">Đề nghị chi (hạn mức vai · 2 chữ ký &gt;20tr · SMS chủ &gt;50tr)</div><table className="tbl"><thead><tr><th className="pl-3">Mã</th><th>Mục đích</th><th>CC</th><th className="text-right">Số tiền</th><th>TT</th><th>Ký</th></tr></thead><tbody>{(exp.rows ?? []).map((e) => <tr key={String(e.id)}><td className="pl-3 font-mono">{String(e.id)}</td><td>{String(e.purpose)}<div className="text-xs text-stone-500">{String(e.by_name)} · {fmt.dt(e.ts)}</div></td><td>{String(e.cost_center ?? "")}</td><td className="text-right font-bold">{fmt.vnd(e.amount)}</td><td><span className={e.status === "DUYET" ? "b-grn" : e.status === "TU_CHOI" ? "b-red" : "b-yel"}>{String(e.status)}</span></td><td className="text-xs">{String(e.approver1 ?? "")}{e.approver2 ? ` + ${e.approver2}` : ""}</td></tr>)}</tbody></table></div>
        <div className="card"><h3 className="font-bold">Quỹ trích tự động (từ doanh thu năm)</h3><table className="tbl"><tbody>{(funds.rows ?? []).map((f) => <tr key={String(f.kind)}><td>{String(f.kind)}</td><td>{String(f.pct)}% {String(f.base)}</td><td className="text-right">{f.accrued_ytd != null ? fmt.vnd(f.accrued_ytd) : "—"}</td></tr>)}</tbody></table>
          <h3 className="font-bold mt-3">Tuổi nợ</h3><table className="tbl"><thead><tr><th>Khách</th><th className="text-right">0–15</th><th className="text-right">16–30</th><th className="text-right">&gt;30</th></tr></thead><tbody>{(aging.rows ?? []).map((r) => <tr key={String(r.partner_id)}><td>{String(r.name)}</td><td className="text-right">{fmt.vnd(r.d0_15 ?? 0)}</td><td className="text-right">{fmt.vnd(r.d16_30 ?? 0)}</td><td className={`text-right ${Number(r.d30p) > 0 ? "text-red-700 font-bold" : ""}`}>{fmt.vnd(r.d30p ?? 0)}</td></tr>)}</tbody></table></div>
      </div>
      <div className="text-xs text-stone-500">P&L phân hệ (giá thành theo CC/chu kỳ, giá chuyển 70%) — đợt kế tiếp khi có phân bổ chi phí; sổ thuế giữ ở MISA, ITRAN OS đẩy bảng kê.</div>
    </div>);
}
