"use client";
import { useMemo, useState } from "react";
import { useData, fmt } from "@/lib/client";
import type { Sess } from "@/components/Shell";
import AnyChart from "@/components/AnyChart";
import ChartIcon from "@/components/ChartIcon";
type R = Record<string, unknown>;
const arr = (v: unknown): string[] => (Array.isArray(v) ? (v as string[]) : []);
function VarTable({ rows, domain }: { rows: R[]; domain: string }) {
  const V = rows.filter((v) => v.domain === domain); const dirs = [["DAU_VAO", "ĐẦU VÀO"], ["TRANG_THAI", "TRẠNG THÁI / SỰ KIỆN"], ["DAU_RA", "ĐẦU RA"], ["MOI_TRUONG", "MÔI TRƯỜNG"], ["KINH_TE", "KINH TẾ / KPI"]];
  return <div className="card p-0 overflow-auto"><div className="px-3 py-2 bg-stone-100 rounded-t-2xl font-bold">Danh mục BIẾN đầu vào → trạng thái → đầu ra ({V.length}) — ghi ở bảng/cột nào, cách thu, tần suất · <a className="underline text-sm font-normal" href="/quan-tri?t=variable_catalog">thêm/sửa</a></div>
    {dirs.map(([k, l]) => { const rs = V.filter((v) => v.direction === k); return rs.length ? <div key={k}><div className="px-3 py-1 text-xs font-bold text-emerald-800 bg-emerald-50">{l} ({rs.length})</div><table className="tbl text-sm"><tbody>{rs.map((v) => <tr key={String(v.code)}><td className="pl-3 font-mono text-xs w-24">{String(v.code)}</td><td className="text-xs text-slate-500 w-24">{String(v.group_name ?? "")}</td><td><b>{String(v.name)}</b>{v.formula ? <div className="text-xs text-slate-500">công thức: {String(v.formula)}</div> : null}</td><td className="text-xs">{String(v.unit ?? "")}</td><td className="text-xs font-mono">{String(v.source_table ?? "")}{v.source_col ? `.${v.source_col}` : ""}{v.event_type ? ` [${v.event_type}]` : ""}</td><td className="text-xs">{String(v.capture ?? "")} · {String(v.frequency ?? "")} · {String(v.level ?? "")}</td><td>{v.status === "DA_CO" ? <span className="b-grn">có</span> : <span className="b-yel">kế hoạch</span>}</td></tr>)}</tbody></table></div> : null; })}</div>;
}
/** ĐỐI TƯỢNG: 1 Con người (vai trò · vị trí · phòng ban · danh sách) · 2 Vật nuôi (loài · lớp · số lượng) · 3 Cây trồng (nhóm · vòng đời · diện tích) · 4 Sản phẩm/vật tư (nhóm · SKU · tồn) — mọi số liệu treo vào đây */
export default function DoiTuong({ sess }: { sess: Sess }) {
  const roles = useData("roles_catalog"); const pos = useData("positions_catalog"); const people = useData("obj_people"); const staff = useData("staff_all"); const depts = useData("departments");
  const species = useData("species"); const classes = useData("animal_classes"); const animals = useData("obj_animals"); const crops = useData("crops"); const objCrops = useData("obj_crops"); const kinds = useData("product_kinds"); const vars = useData("variable_catalog"); const objProd = useData("obj_products"); const products = useData("products");
  const [tab, setTab] = useState<"nguoi" | "vat" | "cay" | "sp">("nguoi"); const [flt, setFlt] = useState("");
  const A = animals.rows ?? []; const totalHead = A.filter((a) => a.status !== "CHET" && a.status !== "XUAT" && a.status !== "LOAI").reduce((s, a) => s + Number(a.n), 0);
  const bySpecies = useMemo(() => { const m = new Map<string, { name: string; group: string; n: number; kg: number; classes: Map<string, number> }>(); for (const a of A) { if (["CHET", "XUAT", "LOAI", "DA_BAN"].includes(String(a.status))) continue; const k = String(a.species); const o = m.get(k) ?? { name: String(a.species_name ?? k), group: String(a.group_name ?? ""), n: 0, kg: 0, classes: new Map() }; o.n += Number(a.n); o.kg += Number(a.kg); const ck = String(a.class_name ?? a.class_code); o.classes.set(ck, (o.classes.get(ck) ?? 0) + Number(a.n)); m.set(k, o); } return [...m.entries()]; }, [A]);
  const S = (staff.rows ?? []).filter((s) => !flt || JSON.stringify(s).toLowerCase().includes(flt.toLowerCase()));
  return (
    <div className="space-y-3">
      <div className="grid grid-cols-2 sm:grid-cols-4 gap-2">
        {[["nguoi", "👤 Con người", `${(staff.rows ?? []).filter((s) => s.active !== false).length} người · ${roles.rows?.length ?? 0} vai · ${pos.rows?.length ?? 0} vị trí`], ["vat", "🐄 Vật nuôi", `${fmt.n(totalHead)} con/đv · ${bySpecies.length} loài đang nuôi · ${species.rows?.length ?? 0} loài định nghĩa`], ["cay", "🌱 Cây trồng", `${(objCrops.rows ?? []).length} loại đang trồng · ${fmt.n((objCrops.rows ?? []).reduce((s, c) => s + Number(c.area_ha), 0), 1)} ha · ${crops.rows?.length ?? 0} loại định nghĩa`], ["sp", "📦 Sản phẩm · vật tư", `${(products.rows ?? []).length} SKU · ${kinds.rows?.length ?? 0} nhóm`]].map(([k, l, sub]) => <button key={k} className={`text-left rounded-2xl p-3 border ${tab === k ? "bg-green-700 text-white" : "bg-white"}`} onClick={() => setTab(k as typeof tab)}><div className="font-bold">{l}</div><div className={`text-xs ${tab === k ? "text-green-100" : "text-stone-600"}`}>{sub}</div></button>)}
      </div>
      {tab === "nguoi" && <div className="space-y-3">
        <div className="card p-0 overflow-auto"><div className="px-3 py-2 bg-stone-100 rounded-t-2xl font-bold">Định nghĩa VAI TRÒ (quyền) — {roles.rows?.length ?? 0} vai · <a className="underline text-sm font-normal" href="/quan-tri?t=roles_catalog">sửa</a></div><table className="tbl text-sm"><thead><tr><th className="pl-3">Mã</th><th>Vai trò</th><th>Mô tả</th><th>Phạm vi</th><th>Được ghi</th><th>Được duyệt</th><th className="text-right">Số người</th></tr></thead><tbody>{(roles.rows ?? []).map((r) => <tr key={String(r.code)}><td className="pl-3 font-mono">{String(r.code)}</td><td className="font-semibold">{String(r.name)}</td><td className="text-xs">{String(r.description)}</td><td className="text-xs">{String(r.scope)}</td><td className="text-xs">{arr(r.can_write).join(", ")}</td><td className="text-xs">{arr(r.can_approve).join(", ")}</td><td className="text-right font-bold">{(staff.rows ?? []).filter((s) => s.role === r.code && s.active !== false).length}</td></tr>)}</tbody></table></div>
        <div className="card p-0 overflow-auto"><div className="px-3 py-2 bg-stone-100 rounded-t-2xl font-bold">Định nghĩa VỊ TRÍ công việc (A1–A14) — form 3 chạm & KPI theo vị trí · <a className="underline text-sm font-normal" href="/quan-tri?t=positions_catalog">sửa</a></div><table className="tbl text-sm"><thead><tr><th className="pl-3">Mã</th><th>Vị trí</th><th>Phòng</th><th>Ghi bảng</th><th>KPI</th><th>Định biên</th><th className="text-right">Số người</th></tr></thead><tbody>{(pos.rows ?? []).map((p) => <tr key={String(p.code)}><td className="pl-3 font-mono">{String(p.code)}</td><td className="font-semibold">{String(p.name)}</td><td>{String(p.dept_code)}</td><td className="text-xs font-mono">{arr(p.forms).join(", ")}</td><td className="text-xs">{arr(p.kpis).join(", ")}</td><td className="text-xs">{String(p.headcount_norm ?? "")}</td><td className="text-right font-bold">{(staff.rows ?? []).filter((s) => String(s.position ?? "").startsWith(String(p.code)) && s.active !== false).length}</td></tr>)}</tbody></table></div>
        <div className="card p-0 overflow-auto"><div className="px-3 py-2 bg-stone-100 rounded-t-2xl flex items-center gap-2"><b>DANH SÁCH NHÂN SỰ ({S.length})</b><input className="input !w-56 !py-1 text-sm" placeholder="lọc…" aria-label="lọc…" value={flt} onChange={(e) => setFlt(e.target.value)} /><a className="ml-auto underline text-sm" href="/quan-tri?t=staff">thêm · sửa · nhập CSV</a><a className="underline text-sm" href="/api/admin/staff?csv=1&all=1">xuất CSV</a></div><table className="tbl text-sm"><thead><tr><th className="pl-3">Mã</th><th>Họ tên</th><th>Vai trò</th><th>Vị trí</th><th>Phòng ban</th><th>Trại</th><th>SĐT</th><th>TT</th></tr></thead><tbody>{S.map((s) => <tr key={String(s.id)} className={s.active === false ? "opacity-50" : ""}><td className="pl-3 font-mono text-xs">{String(s.id)}</td><td className="font-semibold">{String(s.full_name)}</td><td>{String(roles.rows?.find((r) => r.code === s.role)?.name ?? s.role)}</td><td className="text-xs">{String(s.position ?? "")}</td><td className="text-xs">{String(depts.rows?.find((d) => d.code === s.dept)?.short ?? s.dept ?? "")}</td><td>{String(s.farm_id ?? "HQ")}{arr(s.farm_ids).length > 1 ? ` (+${arr(s.farm_ids).length - 1})` : ""}</td><td className="text-xs">{String(s.phone ?? "")}</td><td>{s.active === false ? <span className="b-gray">nghỉ</span> : <span className="b-grn">đang làm</span>}</td><td><ChartIcon type="staff" id={String(s.id)} label={String(s.full_name)} /></td></tr>)}</tbody></table></div>
        <div className="card p-0 overflow-auto"><div className="px-3 py-2 bg-stone-100 rounded-t-2xl font-bold">Tổng hợp theo trại × vai × phòng</div><table className="tbl text-sm"><thead><tr><th className="pl-3">Trại</th><th>Vai</th><th>Phòng</th><th>Vị trí</th><th className="text-right">Đang làm</th><th className="text-right">Nghỉ</th></tr></thead><tbody>{(people.rows ?? []).map((p, i) => <tr key={i}><td className="pl-3">{String(p.farm_id)}</td><td>{String(p.role_name ?? p.role)}</td><td>{String(p.dept_name ?? p.dept ?? "")}</td><td className="text-xs">{String(p.position_name ?? p.position_code ?? "")}</td><td className="text-right font-bold">{String(p.n_active)}</td><td className="text-right">{String(p.n_inactive)}</td></tr>)}</tbody></table></div>
      </div>}
      {tab === "vat" && <div className="space-y-3">
        <div className="grid md:grid-cols-2 gap-3">
          <div className="card p-0 overflow-auto"><div className="px-3 py-2 bg-stone-100 rounded-t-2xl font-bold">ĐANG NUÔI tại {sess.farmId}: {fmt.n(totalHead)} — theo loài → lớp</div><table className="tbl text-sm"><tbody>{bySpecies.map(([k, o]) => [<tr key={k} className="bg-green-50"><td className="pl-3 font-bold">{o.name} <span className="text-xs font-normal text-stone-500">{k} · {o.group}</span></td><td className="text-right font-black">{fmt.n(o.n)}</td><td className="text-right text-xs">{o.kg ? `${fmt.n(o.kg)} kg` : ""}</td></tr>, ...[...o.classes.entries()].map(([c, n]) => <tr key={k + c}><td className="pl-8 text-sm">{c}</td><td className="text-right">{fmt.n(n)}</td><td></td></tr>)])}</tbody></table><div className="px-3 py-2 text-xs text-stone-500">Bò/dê: đếm theo cá thể (mỗi con 1 mã) · gà/cá/trùn: theo đàn/khối. Chi tiết → <a className="underline" href="/dan">Đàn</a>.</div></div>
          <div className="card"><AnyChart title="Đàn theo tuần (snapshot herd_daily)" table="herd_daily" col="head" agg="sum" dim="species" bucket="week" height={260} /></div>
        </div>
        <VarTable rows={vars.rows ?? []} domain="CHAN_NUOI" />
        <div className="card p-0 overflow-auto"><div className="px-3 py-2 bg-stone-100 rounded-t-2xl font-bold">Định nghĩa LOÀI ({species.rows?.length}) — mức định danh · chu kỳ · sản phẩm đầu ra · <a className="underline text-sm font-normal" href="/quan-tri?t=species">sửa/thêm loài</a></div><table className="tbl text-sm"><thead><tr><th className="pl-3">Mã</th><th>Loài</th><th>Nhóm</th><th>Định danh</th><th>ĐV</th><th>Mang thai/chu kỳ (ngày)</th><th>Trọng lượng TT</th><th>SKU đầu ra</th><th>Module</th><th className="text-right">Đang nuôi</th></tr></thead><tbody>{(species.rows ?? []).map((s) => <tr key={String(s.code)}><td className="pl-3 font-mono">{String(s.code)}</td><td className="font-semibold">{String(s.name)}</td><td className="text-xs">{String(s.group_name)}</td><td><span className={s.identify_level === "CA_THE" ? "b-grn" : "b-yel"}>{String(s.identify_level)}</span></td><td>{String(s.unit)}</td><td className="text-xs">{String(s.gestation_days ?? "")} / {String(s.cycle_days ?? "")}</td><td className="text-xs">{s.adult_weight_kg ? `${s.adult_weight_kg} kg` : ""}</td><td className="text-xs font-mono">{arr(s.products).join(", ")}</td><td className="text-xs">{String(s.module ?? "")}</td><td className="text-right font-bold">{fmt.n(bySpecies.find(([k]) => k === s.code)?.[1].n ?? 0)}</td></tr>)}</tbody></table></div>
        <div className="card p-0 overflow-auto"><div className="px-3 py-2 bg-stone-100 rounded-t-2xl font-bold">Phân LỚP vật nuôi (giai đoạn/mục đích) · <a className="underline text-sm font-normal" href="/quan-tri?t=animal_classes">sửa</a></div><table className="tbl text-sm"><thead><tr><th className="pl-3">Mã</th><th>Loài</th><th>Lớp</th><th>Giới</th><th>Tuổi (ngày)</th><th>Mục đích</th><th>Định mức TA</th></tr></thead><tbody>{(classes.rows ?? []).map((c) => <tr key={String(c.code)}><td className="pl-3 font-mono">{String(c.code)}</td><td>{String(c.species_code)}</td><td className="font-semibold">{String(c.name)}</td><td>{String(c.sex ?? "—")}</td><td className="text-xs">{String(c.age_from_days ?? 0)}–{String(c.age_to_days ?? "∞")}</td><td className="text-xs">{String(c.purpose)}</td><td className="text-xs font-mono">{String(c.feed_norm_key ?? "")}</td></tr>)}</tbody></table></div>
      </div>}
      {tab === "cay" && <div className="space-y-3">
        <div className="grid md:grid-cols-2 gap-3">
          <div className="card p-0 overflow-auto"><div className="px-3 py-2 bg-stone-100 rounded-t-2xl font-bold">ĐANG TRỒNG tại {sess.farmId}</div><table className="tbl text-sm"><thead><tr><th className="pl-3">Cây</th><th>Nhóm</th><th>Vòng đời</th><th className="text-right">Ô</th><th className="text-right">ha</th><th className="text-right">Vụ đang chạy</th><th className="text-right">Thu hoạch năm nay (kg)</th></tr></thead><tbody>{(objCrops.rows ?? []).map((c, i) => <tr key={i}><td className="pl-3 font-semibold">{String(c.crop_name ?? c.crop_code)}</td><td className="text-xs">{String(c.group_name ?? "")}</td><td className="text-xs">{String(c.life_cycle ?? "")}</td><td className="text-right">{String(c.plots_n)}</td><td className="text-right font-bold">{fmt.n(c.area_ha, 2)}</td><td className="text-right">{String(c.seasons_active)}</td><td className="text-right">{fmt.n(c.harvested_ytd_kg)}</td></tr>)}</tbody></table><div className="px-3 py-2 text-xs text-stone-500">Chi tiết mùa vụ/nhật ký → <a className="underline" href="/canh-tac">Canh tác</a>; ô thửa → <a className="underline" href="/quan-tri?t=plots">Quản trị DL</a>.</div></div>
          <div className="card"><AnyChart title="Thu hoạch/cắt theo giống (kg/tuần)" table="crop_logs" col="qty_kg" dim="variety" filters={{ activity: "" }} bucket="week" height={260} /></div>
        </div>
        <VarTable rows={vars.rows ?? []} domain="TRONG_TROT" />
        <div className="card p-0 overflow-auto"><div className="px-3 py-2 bg-stone-100 rounded-t-2xl font-bold">Định nghĩa CÂY TRỒNG ({crops.rows?.length}) — nhóm · vòng đời · chu kỳ · năng suất chuẩn · sản phẩm · <a className="underline text-sm font-normal" href="/quan-tri?t=crops">sửa/thêm</a></div><table className="tbl text-sm"><thead><tr><th className="pl-3">Mã</th><th>Cây</th><th>Nhóm</th><th>Vòng đời</th><th>Chu kỳ (ngày)</th><th>Lứa/năm</th><th className="text-right">NS chuẩn kg/ha</th><th>Giống</th><th>SKU đầu ra</th></tr></thead><tbody>{["SINH_KHOI", "LUONG_THUC", "RAU", "CU", "QUA", "CAY_CONG_NGHIEP", "DUOC_LIEU", "NAM", "CAY_VIEN", "HOA"].map((g) => (crops.rows ?? []).filter((c) => c.group_name === g).map((c) => <tr key={String(c.code)}><td className="pl-3 font-mono">{String(c.code)}</td><td className="font-semibold">{String(c.name)}</td><td className="text-xs">{g}</td><td className="text-xs">{String(c.life_cycle)}</td><td className="text-xs">{String(c.cycle_days ?? "")}</td><td className="text-xs">{String(c.cuts_per_year ?? "")}</td><td className="text-right">{c.yield_norm_kg_ha ? fmt.n(c.yield_norm_kg_ha) : ""}</td><td className="text-xs">{arr(c.varieties).join(", ")}</td><td className="text-xs font-mono">{arr(c.products).join(", ")}</td></tr>))}</tbody></table></div>
      </div>}
      {tab === "sp" && <div className="space-y-3">
        <div className="card p-0 overflow-auto"><div className="px-3 py-2 bg-stone-100 rounded-t-2xl font-bold">NHÓM sản phẩm / vật tư (dòng chảy đầu vào → trung gian → đầu ra) · <a className="underline text-sm font-normal" href="/quan-tri?t=product_kinds">sửa</a></div><table className="tbl text-sm"><thead><tr><th className="pl-3">Mã</th><th>Nhóm</th><th>Dòng</th><th>Kho mặc định</th><th className="text-right">SKU</th><th className="text-right">Có tồn</th></tr></thead><tbody>{(kinds.rows ?? []).map((k) => { const o = (objProd.rows ?? []).find((x) => x.kind === k.code); return <tr key={String(k.code)}><td className="pl-3 font-mono">{String(k.code)}</td><td className="font-semibold">{String(k.name)}</td><td><span className={k.flow === "DAU_RA" ? "b-grn" : k.flow === "TRUNG_GIAN" ? "b-yel" : "b-gray"}>{String(k.flow)}</span></td><td>{String(k.default_warehouse ?? "")}</td><td className="text-right font-bold">{String(o?.skus ?? 0)}</td><td className="text-right">{String(o?.sku_in_stock ?? 0)}</td></tr>; })}</tbody></table></div>
        <div className="card p-0 overflow-auto"><div className="px-3 py-2 bg-stone-100 rounded-t-2xl flex items-center gap-2"><b>Danh mục SKU ({(products.rows ?? []).length})</b><a className="ml-auto underline text-sm" href="/quan-tri?t=products">thêm · sửa · nhập CSV</a><a className="underline text-sm" href="/kho">tồn kho</a></div><table className="tbl text-sm"><thead><tr><th className="pl-3">SKU</th><th>Tên</th><th>Nhóm</th><th>ĐV</th><th>Kho</th><th>Theo lô</th><th>Hạn (ngày)</th><th>GTIN</th></tr></thead><tbody>{(products.rows ?? []).map((p) => <tr key={String(p.sku)}><td className="pl-3 font-mono text-xs">{String(p.sku)}</td><td className="font-semibold">{String(p.name)}</td><td className="text-xs">{String(p.kind)}</td><td>{String(p.unit)}</td><td className="text-xs">{String(p.default_warehouse ?? "")}</td><td>{p.lot_tracked ? "✓" : ""}</td><td className="text-xs">{String(p.shelf_life_days ?? "")}</td><td className="text-xs font-mono">{String(p.gtin ?? "")}</td><td><ChartIcon type="product" id={String(p.sku)} label={String(p.name)} /></td></tr>)}</tbody></table></div>
      </div>}
    </div>);
}
