"use client";
import { useState } from "react";
import { useData, act, fmt } from "@/lib/client";
import type { Sess } from "@/components/Shell";
import AnyChart from "@/components/AnyChart";
import ChartIcon from "@/components/ChartIcon";
import Tabs from "@/components/Tabs";
import { LineChart, Line, BarChart, Bar, XAxis, YAxis, Tooltip, Legend, CartesianGrid, ResponsiveContainer, ReferenceLine, PieChart, Pie, Cell } from "recharts";
const COLORS = ["#059669", "#0ea5e9", "#f59e0b", "#8b5cf6", "#ef4444", "#14b8a6", "#64748b", "#84cc16", "#f97316", "#a855f7", "#0891b2", "#be185d", "#4d7c0f", "#b45309"];
type R = Record<string, unknown>;
const FLAG: Record<string, [string, string]> = { TRONG: ["Trống", "bg-slate-100 text-slate-600"], HET: ["HẾT", "bg-red-600 text-white"], THIEU_SOM: ["Thiếu sớm", "bg-red-100 text-red-800"], CHAM_ROP: ["Chạm ROP", "bg-orange-100 text-orange-800"], AM_30_NGAY: ["Âm 30 ngày", "bg-amber-100 text-amber-800"], OK: ["OK", "bg-emerald-100 text-emerald-800"] };
function ProjChart({ sku, name }: { sku: string; name: string }) {
  const q = useData("stock_projection", { sku, days: "90" }, [sku]); const rows = (q.rows ?? []).map((r) => ({ d: Number(r.d), day: fmt.d(String(r.day)).slice(0, 5), qty: Number(r.qty), incoming: Number(r.incoming), rop: r.rop != null ? Number(r.rop) : null }));
  const neg = rows.find((r) => r.qty < 0);
  return <div className="card !p-3"><div className="flex items-center gap-2 text-sm"><b>{name}</b><span className="text-xs text-slate-500">dự kiến tồn 90 ngày = tồn + đang về (PO/thu hoạch/SX theo ngày) − nhu cầu/ngày (đàn thật + dự báo đẻ/đổi hạng)</span>{neg && <span className="ml-auto text-xs font-semibold text-red-700">âm từ ngày {neg.day} (+{neg.d})</span>}</div>
    <div style={{ height: 200 }}><ResponsiveContainer><LineChart data={rows}><CartesianGrid strokeDasharray="3 3" /><XAxis dataKey="day" tick={{ fontSize: 10 }} interval={14} /><YAxis tick={{ fontSize: 10 }} width={60} tickFormatter={(v) => fmt.n(Number(v))} /><Tooltip formatter={(v) => fmt.n(Number(v))} /><ReferenceLine y={0} stroke="#dc2626" strokeDasharray="4 4" />{rows[0]?.rop != null && <ReferenceLine y={rows[0].rop} stroke="#f59e0b" strokeDasharray="2 2" label={{ value: "ROP", fontSize: 10 }} />}<Line type="monotone" dataKey="qty" name="Tồn dự kiến" stroke="#059669" dot={false} strokeWidth={2} /><Bar dataKey="incoming" name="Đang về" fill="#3b82f6" /></LineChart></ResponsiveContainer></div></div>;
}
function ForecastChart() {
  const hf = useData("herd_forecast_series"); const ff = useData("feed_forecast_series");
  const classes = [...new Set((hf.rows ?? []).map((r) => String(r.class_name ?? r.class_code)))];
  const data = [0, 30, 60, 90].map((h) => { const o: Record<string, unknown> = { horizon: h === 0 ? "Hôm nay" : `+${h} ngày` }; for (const r of (hf.rows ?? []).filter((x) => Number(x.horizon) === h)) o[String(r.class_name ?? r.class_code)] = Number(r.head_forecast); const f = (ff.rows ?? []).find((x) => Number(x.horizon) === h); o.kg_day = f ? Math.round(Number(f.kg_day)) : 0; return o; });
  const COL = ["#059669", "#0ea5e9", "#f59e0b", "#8b5cf6", "#ef4444", "#14b8a6", "#64748b"];
  const births = (hf.rows ?? []).filter((r) => Number(r.horizon) === 90).reduce((a, r) => a + Number(r.births), 0); const exits = (hf.rows ?? []).filter((r) => Number(r.horizon) === 90).reduce((a, r) => a + Number(r.exits), 0);
  return <div className="grid md:grid-cols-2 gap-3"><div className="card !p-3"><div className="text-sm"><b>Dự báo đàn theo hạng</b> <span className="text-xs text-slate-500">— đẻ dự kiến 90 ngày: <b>{births}</b> (từ phối/khám thai + 283 ngày) · xuất vỗ béo đủ ngày: <b>{exits}</b> · bê tự chuyển hạng theo tuổi</span></div><div style={{ height: 220 }}><ResponsiveContainer><BarChart data={data}><CartesianGrid strokeDasharray="3 3" /><XAxis dataKey="horizon" tick={{ fontSize: 11 }} /><YAxis tick={{ fontSize: 10 }} width={50} /><Tooltip /><Legend wrapperStyle={{ fontSize: 11 }} />{classes.map((c, i) => <Bar key={c} dataKey={c} stackId="a" fill={COL[i % COL.length]} />)}</BarChart></ResponsiveContainer></div></div>
    <div className="card !p-3"><div className="text-sm"><b>Nhu cầu thức ăn/ngày (kg)</b> <span className="text-xs text-slate-500">— tự nhảy theo đàn thật + dự báo</span></div><div style={{ height: 220 }}><ResponsiveContainer><LineChart data={data}><CartesianGrid strokeDasharray="3 3" /><XAxis dataKey="horizon" tick={{ fontSize: 11 }} /><YAxis tick={{ fontSize: 10 }} width={60} tickFormatter={(v) => fmt.n(Number(v))} /><Tooltip formatter={(v) => fmt.n(Number(v))} /><Line type="monotone" dataKey="kg_day" name="kg thức ăn/ngày" stroke="#059669" strokeWidth={2} /></LineChart></ResponsiveContainer></div></div></div>;
}
function Block({ b, title, hint, R0, W, groups, sess, onChanged }: { b: string; title: string; hint: string; R0: R[]; W: R[]; groups: R[]; sess: Sess; onChanged: () => void }) {
  const [gsel, setGsel] = useState<string>(""); const [pick, setPick] = useState<string>(""); const cat = useData("reserve_catalog"); const [nf, setNf] = useState<R>({}); const [rf, setRf] = useState<R>({ reason: "NHAP_MUA" }); const [msg2, setMsg2] = useState(""); const [showRcv, setShowRcv] = useState(false);
  const G = groups.filter((g) => g.block === b); const R1 = gsel ? R0.filter((r) => r.stock_group === gsel) : R0; const bad = R1.filter((r) => !["OK", "TRONG"].includes(String(r.flag)));
  const canPick = ["owner", "director", "tech_head", "it_engineer", "accountant", "team_lead"].includes(sess.role);
  const receipt = async () => { const j = await fetch("/api/events/inventory_moves", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ client_ref: crypto.randomUUID(), warehouse_id: rf.warehouse_id, sku: rf.sku, direction: 1, qty: Number(rf.qty), unit: (cat.rows ?? []).find((c) => c.sku === rf.sku)?.unit ?? "kg", lot_no: rf.lot_no || `L${new Date().toISOString().slice(2, 10).replace(/-/g, "")}`, unit_cost: rf.unit_cost ? Number(rf.unit_cost) : undefined, reason: rf.reason, from_to: rf.from_to || undefined }) }).then((r) => r.json()); const ok = j.results?.[0]?.status === "CREATED"; setMsg2(ok ? "Đã nhập kho — số liệu dự trữ cập nhật" : `Lỗi: ${JSON.stringify(j.results?.[0]?.errors ?? j.error)}`); if (ok) { setRf({ reason: rf.reason, warehouse_id: rf.warehouse_id }); onChanged(); } };
    return <div className="space-y-3">
      <div className="grid lg:grid-cols-3 gap-3">
        <div className="card !p-3"><div className="text-sm font-bold">{gsel ? `Cơ cấu tồn trong nhóm ${String(G.find((g) => g.code === gsel)?.name ?? "")}` : "Cơ cấu tồn theo nhóm dự trữ"} {gsel && <button className="text-xs underline font-normal ml-2" onClick={() => setGsel("")}>← tất cả nhóm</button>}</div><div style={{ height: 230 }}><ResponsiveContainer><PieChart><Pie data={gsel ? R1.map((r) => ({ name: String(r.name), value: Number(r.qty) })).filter((d) => d.value > 0) : G.map((g) => ({ name: String(g.name), value: R0.filter((r) => r.stock_group === g.code).reduce((a, r) => a + Number(r.qty), 0) })).filter((d) => d.value > 0)} dataKey="value" nameKey="name" innerRadius={45} outerRadius={85} paddingAngle={2} onClick={(d) => { if (gsel) return; const g = G.find((x) => x.name === (d as { name?: string }).name); if (g) setGsel(String(g.code)); }}>{(gsel ? R1 : G).map((g, k) => <Cell key={k} fill={COLORS[k % COLORS.length]} />)}</Pie><Tooltip formatter={(v) => fmt.n(Number(v))} /><Legend wrapperStyle={{ fontSize: 10 }} /></PieChart></ResponsiveContainer></div></div>
        <div className="card !p-3"><div className="text-sm font-bold">{gsel ? "Từng mặt hàng trong nhóm: ngày còn & cần bổ sung" : "Theo nhóm: ngày còn (min) & số mặt hàng cần bổ sung"} <span className="text-xs font-normal text-slate-500">— bấm cột để lọc</span></div><div style={{ height: 230 }}><ResponsiveContainer><BarChart data={gsel ? R1.map((r) => ({ code: String(r.sku), name: String(r.name).split(" ").slice(0, 3).join(" "), ngay: r.days_left == null ? 0 : Math.min(Number(r.days_left), 365), thieu: Number(r.need_qty) > 0 ? Math.round(Number(r.need_qty)) : 0, tong: 1 })) : G.map((g) => { const rows = R0.filter((r) => r.stock_group === g.code); const d = Math.min(...rows.map((r) => r.days_left == null ? 9e9 : Number(r.days_left))); return { code: String(g.code), name: String(g.icon ?? "") + " " + String(g.name).replace(/ – .*/, "").split(" ").slice(0, 3).join(" "), ngay: d < 9e9 ? Math.min(d, 365) : 0, thieu: rows.filter((r) => !["OK", "TRONG"].includes(String(r.flag))).length, tong: rows.length }; })} onClick={(e) => { if (gsel) return; const c = (e as { activePayload?: { payload?: { code?: string } }[] })?.activePayload?.[0]?.payload?.code; if (c) setGsel(c); }}><CartesianGrid strokeDasharray="3 3" /><XAxis dataKey="name" tick={{ fontSize: 9 }} interval={0} angle={-20} height={50} /><YAxis yAxisId="l" tick={{ fontSize: 10 }} width={35} /><YAxis yAxisId="r" orientation="right" tick={{ fontSize: 10 }} width={30} /><Tooltip /><Legend wrapperStyle={{ fontSize: 10 }} /><Bar yAxisId="l" dataKey="ngay" name="Ngày còn (min, ≤365)" fill="#059669" /><Bar yAxisId="r" dataKey="thieu" name={gsel ? "Cần bổ sung (số lượng)" : "Cần bổ sung (mặt hàng)"} fill="#ef4444" /></BarChart></ResponsiveContainer></div></div>
        <div className="card !p-3 space-y-2"><div className="text-sm font-bold">Nhóm dự trữ & mặt hàng theo dõi</div>
          <select className="input" value={gsel} onChange={(e) => setGsel(e.target.value)}><option value="">— Tất cả nhóm ({R0.length} mặt hàng theo dõi) —</option>{G.map((g) => { const rows = R0.filter((r) => r.stock_group === g.code); const nbad = rows.filter((r) => !["OK", "TRONG"].includes(String(r.flag))).length; return <option key={String(g.code)} value={String(g.code)}>{String(g.icon ?? "")} {String(g.name)} · {rows.length} mh · {rows.filter((r) => Number(r.qty) > 0).length} có tồn{nbad ? ` · ${nbad} cần bổ sung` : ""}</option>; })}</select>
          <div className="flex gap-2 flex-wrap"><button type="button" className="btn-secondary !py-1.5 !px-3 text-sm" onClick={() => setPick(pick ? "" : (gsel || String(G[0]?.code ?? "")))}>☑ Chọn mặt hàng theo dõi ▾</button><button type="button" className="btn-secondary !py-1.5 !px-3 text-sm" onClick={() => setShowRcv(!showRcv)}>📥 Nhập kho nhanh ▾</button></div>
          {gsel && <div className="text-xs text-slate-500">Ví dụ nhóm: {String(G.find((g) => g.code === gsel)?.examples ?? "")}</div>}
          <div className="text-xs text-slate-500">Nhóm là danh mục (<a className="underline" href="/quan-tri?t=stock_groups">stock_groups</a>); mặt hàng theo dõi = tick trong danh sách; mặt hàng mới thêm ngay tại đây.</div></div></div>
      {pick && <div className="card"><div className="flex items-center gap-2 flex-wrap"><b>Chọn mặt hàng theo dõi dự trữ</b><select className="input !w-72 !py-1" value={pick} onChange={(e) => setPick(e.target.value)}>{G.map((g) => <option key={String(g.code)} value={String(g.code)}>{String(g.icon ?? "")} {String(g.name)}</option>)}</select><span className="text-xs text-slate-500">ví dụ: {String(G.find((g) => g.code === pick)?.examples ?? "")}</span><button className="ml-auto text-sm underline" onClick={() => setPick("")}>đóng</button></div>
        <div className="flex flex-wrap gap-1 mt-2">{(cat.rows ?? []).filter((c) => c.stock_group === pick).map((c) => <label key={String(c.sku)} className={`rounded-lg border px-2 py-1 text-sm cursor-pointer ${c.reserve ? "bg-emerald-50 border-emerald-400" : "bg-white"}`}><input type="checkbox" className="mr-1" checked={!!c.reserve} disabled={!canPick} onChange={async (e) => { await act("set_reserve", { sku: c.sku, reserve: e.target.checked }); cat.reload(); onChanged(); }} />{String(c.name)} <span className="text-xs text-slate-400">({String(c.unit)})</span></label>)}</div>
        {canPick && <div className="flex gap-2 mt-2 flex-wrap"><input className="input !w-64" placeholder="Thêm mặt hàng mới (tên)" value={String(nf.name ?? "")} onChange={(e) => setNf({ ...nf, name: e.target.value })} /><input className="input !w-24" placeholder="đv" value={String(nf.unit ?? "")} onChange={(e) => setNf({ ...nf, unit: e.target.value })} /><input className="input !w-28" type="number" placeholder="HSD ngày" value={String(nf.shelf_life_days ?? "")} onChange={(e) => setNf({ ...nf, shelf_life_days: e.target.value })} /><button className="btn-primary !py-2" disabled={!nf.name} onClick={async () => { const j = await act("add_reserve_item", { ...nf, group: pick, shelf_life_days: nf.shelf_life_days ? Number(nf.shelf_life_days) : null }); if (j.ok) { setNf({}); cat.reload(); onChanged(); } else setMsg2(String(j.error)); }}>＋ Thêm & theo dõi</button></div>}</div>}
      {showRcv && <div className="card"><div className="flex items-center gap-2 flex-wrap"><b>Nhập kho nhanh</b><span className="text-xs text-slate-500">— mọi bộ phận tự nhập phần mình (ruộng → K3, khu D → K5, gà → K5, mua → K1/K2, D5 → K4); công nhân dùng form 3 chạm NHẬP/XUẤT kho trong Ca của tôi; sổ ghi ai nhập, lô nào, từ đâu</span></div>
        <div className="grid sm:grid-cols-3 lg:grid-cols-7 gap-2 mt-2"><select className="input" value={String(rf.warehouse_id ?? "")} onChange={(e) => setRf({ ...rf, warehouse_id: e.target.value })}><option value="">Kho</option>{W.map((w) => <option key={String(w.warehouse_id)} value={String(w.warehouse_id)}>{String(w.code)} {String(w.name)}</option>)}</select><select className="input lg:col-span-2" value={String(rf.sku ?? "")} onChange={(e) => setRf({ ...rf, sku: e.target.value })}><option value="">Mặt hàng (đang theo dõi)</option>{G.map((g) => <optgroup key={String(g.code)} label={String(g.name)}>{(cat.rows ?? []).filter((c) => c.stock_group === g.code && c.reserve).map((c) => <option key={String(c.sku)} value={String(c.sku)}>{String(c.name)}</option>)}</optgroup>)}</select><input className="input" type="number" placeholder="Số lượng" value={String(rf.qty ?? "")} onChange={(e) => setRf({ ...rf, qty: e.target.value })} /><input className="input" placeholder="Số lô (tự sinh nếu trống)" value={String(rf.lot_no ?? "")} onChange={(e) => setRf({ ...rf, lot_no: e.target.value })} /><select className="input" value={String(rf.reason)} onChange={(e) => setRf({ ...rf, reason: e.target.value })}>{[["NHAP_MUA", "Mua"], ["NHAP_SX", "Sản xuất/thu hoạch"], ["TRA", "Trả lại"], ["CHUYEN", "Chuyển đến"], ["DIEU_CHINH", "Điều chỉnh"]].map(([k, l]) => <option key={k} value={k}>{l}</option>)}</select><input className="input" placeholder="Từ (NCC/bộ phận/ô)" value={String(rf.from_to ?? "")} onChange={(e) => setRf({ ...rf, from_to: e.target.value })} /><input className="input" type="number" placeholder="Đơn giá" value={String(rf.unit_cost ?? "")} onChange={(e) => setRf({ ...rf, unit_cost: e.target.value })} /><button className="btn-primary !py-2" disabled={!rf.warehouse_id || !rf.sku || !rf.qty} onClick={receipt}>Nhập</button></div>{msg2 && <div className="text-sm mt-1 text-emerald-700">{msg2}</div>}</div>}
      <div className="grid grid-cols-2 sm:grid-cols-4 gap-2"><div className="kpi"><div className="l">Mặt hàng theo dõi{gsel ? " (nhóm)" : ""}</div><div className="v">{R1.length} <span className="text-base font-normal text-slate-500">· {R1.filter((r) => Number(r.qty) > 0).length} có tồn</span></div></div><div className="kpi"><div className="l">Cần bổ sung</div><div className={`v ${bad.length ? "text-red-700" : ""}`}>{bad.length}</div></div><div className="kpi"><div className="l">Đang về (PO/thu hoạch/SX)</div><div className="v">{fmt.n(R1.reduce((a, r) => a + Number(r.incoming_po) + Number(r.incoming_harvest) + Number(r.incoming_production), 0))}</div></div><div className="kpi"><div className="l">Kho · % sức chứa</div><div className="v text-xl">{W.map((w) => `${w.code} ${w.pct_full != null ? w.pct_full + "%" : "—"}`).join(" · ")}</div></div></div>
      <div className="grid md:grid-cols-3 gap-2">{W.map((w) => <div key={String(w.warehouse_id)} className="card !p-3"><div className="flex items-center gap-2"><b>{String(w.code)}</b> <span className="text-sm">{String(w.name)}</span><span className="ml-auto text-xs text-slate-500">{String(w.area ?? "")}</span></div><div className="h-2 rounded bg-slate-100 mt-2 overflow-hidden"><div className={`h-2 ${Number(w.pct_full) > 90 ? "bg-red-500" : Number(w.pct_full) > 70 ? "bg-amber-500" : "bg-emerald-500"}`} style={{ width: `${Math.min(100, Number(w.pct_full ?? 0))}%` }} /></div><div className="text-xs text-slate-600 mt-1">{fmt.n(Number(w.qty))} {String(w.unit_kind).toLowerCase()} / sức chứa {w.capacity ? fmt.n(Number(w.capacity)) : "—"} · {String(w.skus)} SKU · {String(w.bins)} bin</div></div>)}</div>
      {b === "DAU_VAO" && <ForecastChart />}
      <div className="grid md:grid-cols-2 gap-3">{[...R1].filter((r) => Number(r.qty) > 0 || Number(r.use_per_day) > 0).sort((a, c) => (a.days_left == null ? 9e9 : Number(a.days_left)) - (c.days_left == null ? 9e9 : Number(c.days_left))).slice(0, 4).map((r) => <ProjChart key={String(r.sku)} sku={String(r.sku)} name={String(r.name)} />)}</div>
      <div className="card p-0 overflow-auto"><div className="px-3 py-2 bg-slate-100 rounded-t-xl font-bold flex items-center gap-2 flex-wrap">{title} <span className="text-xs font-normal text-slate-500">{hint}</span></div>
        <table className="tbl text-sm"><thead><tr><th className="pl-3">Mặt hàng</th><th>TT</th><th className="text-right">Còn</th><th className="text-right">% max</th><th className="text-right">{b === "DAU_RA" ? "Bán/ngày" : "Dùng/ngày"}</th><th className="text-right">Ngày còn</th><th className="text-right">Đang về</th><th className="text-right">{b === "DAU_RA" ? "Đơn chốt" : "KH nhu cầu/ng"}</th><th className="text-right">DK 30ng</th><th className="text-right">DK 60ng</th><th className="text-right">DK 90ng</th><th className="text-right">{b === "DAU_RA" ? "Cần SX thêm" : "Cần bổ sung"}</th><th></th></tr></thead>
          <tbody>{R1.map((r) => { const f = FLAG[String(r.flag)] ?? FLAG.OK; return <tr key={String(r.sku)} className={r.flag !== "OK" ? "bg-red-50/60" : ""}><td className="pl-3">{String(r.name)}<div className="text-xs text-slate-500">{String(r.group_icon ?? "")} {String(r.group_name ?? r.kind)} · {String(r.sku)}</div></td><td><span className={`rounded-full px-2 py-0.5 text-xs font-semibold ${f[1]}`}>{f[0]}</span></td><td className="text-right font-bold">{fmt.n(Number(r.qty))} <span className="text-xs font-normal">{String(r.unit)}</span></td><td className="text-right">{r.pct_full != null ? `${r.pct_full}%` : ""}</td><td className="text-right">{fmt.n(Number(r.use_per_day))}{r.demand_source === "DAN_THAT" ? <div className="text-[10px] text-emerald-700">theo đàn thật · +30ng {fmt.n(Number(r.use_per_day_30))}</div> : <div className="text-[10px] text-slate-400">TB 14 ngày</div>}</td><td className={`text-right font-semibold ${r.days_left != null && Number(r.days_left) < 14 ? "text-red-700" : ""}`}>{r.days_left != null ? String(r.days_left) : "—"}</td><td className="text-right">{fmt.n(Number(r.incoming_po) + Number(r.incoming_harvest) + Number(r.incoming_production))}{Number(r.incoming_harvest) > 0 && <span className="text-xs text-emerald-700"> (thu {fmt.n(Number(r.incoming_harvest))})</span>}</td><td className="text-right">{b === "DAU_RA" ? fmt.n(Number(r.committed_orders)) : fmt.n(Number(r.use_per_day))}</td><td className={`text-right ${Number(r.proj_30) < 0 ? "text-red-700 font-bold" : ""}`}>{fmt.n(Number(r.proj_30))}</td><td className={`text-right ${Number(r.proj_60) < 0 ? "text-red-700" : ""}`}>{fmt.n(Number(r.proj_60))}</td><td className={`text-right ${Number(r.proj_90) < 0 ? "text-red-700" : ""}`}>{fmt.n(Number(r.proj_90))}</td><td className={`text-right font-bold ${Number(r.need_qty) > 0 ? "text-red-700" : "text-emerald-700"}`}>{fmt.n(Number(r.need_qty))}</td><td className="text-xs whitespace-nowrap"><ChartIcon type="product" id={String(r.sku)} />{Number(r.need_qty) > 0 && (b === "DAU_RA" ? <a className="underline ml-1" href="/che-bien">→ KHSX</a> : <a className="underline ml-1" href={`/kho?tab=rop`}>→ PO</a>)}</td></tr>; })}</tbody></table>
        {!R1.length && <div className="p-3 text-sm text-slate-500">Chưa có mặt hàng theo dõi — bấm "chọn mặt hàng" ở thẻ nhóm.</div>}<div className="p-2 text-xs text-slate-500">DK = tồn + đang về (PO/thu hoạch/SX) − đơn đã chốt − dùng/ngày × N. Dùng/ngày = kế hoạch cung–cầu đã ban hành (nếu có) hoặc trung bình xuất 14 ngày. Cần bổ sung = max của chính sách (stock_policies) hoặc 60 ngày dùng − (tồn + đang về − dùng trong lead time). Sức chứa kho: <a className="underline" href="/quan-tri?t=warehouses">warehouses.capacity</a>.</div></div>
      <div className="grid md:grid-cols-2 gap-3"><div className="card"><AnyChart title={`${b === "DAU_RA" ? "Xuất bán" : "Xuất dùng"} theo mặt hàng (14 tuần)`} table="inventory_moves" col="qty" dim="sku" bucket="week" filters={{ direction: "-1" }} height={240} /></div><div className="card"><AnyChart title="Nhập theo lý do (14 tuần)" table="inventory_moves" col="qty" dim="reason" bucket="week" filters={{ direction: "1" }} height={240} /></div></div></div>; }
/** DASHBOARD DỰ TRỮ tách 3 khối: ĐẦU VÀO (nguyên liệu/thức ăn cho vật nuôi, giống, phân/thuốc, bao bì, nhiên liệu) · ĐẦU RA (thành phẩm) · CÔNG CỤ (từng cuốc/xẻng/búa, nhiều kho theo khu vực, cấp phát/thu hồi/hỏng) */
export default function DuTru({ sess }: { sess: Sess }) {
  const [tab, setTab] = useState<"vao" | "ra" | "cc">("vao");
  const dash = useData("stock_dashboard"); const sgroups = useData("stock_groups"); const cst = useData("cache_status"); const fill = useData("warehouse_fill"); const tools = useData("tool_stock"); const issued = useData("tool_issued"); const cat = useData("tool_catalog"); const hist = useData("tool_history"); const staff = useData("staff_list"); const wh = useData("warehouses");
  const [msg, setMsg] = useState(""); const [isF, setIsF] = useState<R>({}); const [mvF, setMvF] = useState<R>({}); const [grp, setGrp] = useState<string>("");
  const canW = ["owner", "director", "tech_head", "team_lead", "worker", "it_engineer"].includes(sess.role);
  const rows = (b: string) => (dash.rows ?? []).filter((r) => r.block === b);
  const groups = [...new Set((tools.rows ?? []).map((t) => String(t.tool_group ?? "")))].filter(Boolean);
  return <div className="space-y-3">
    <Tabs items={[["vao", `🌾 KHO ĐẦU VÀO — nguyên liệu, thức ăn, giống, phân/thuốc, bao bì, nhiên liệu (${rows("DAU_VAO").length})`], ["ra", `📦 KHO ĐẦU RA — thành phẩm bán (${rows("DAU_RA").length})`], ["cc", `🔧 KHO CÔNG CỤ – DỤNG CỤ theo khu vực (${(tools.rows ?? []).length} dòng · ${(issued.rows ?? []).length} đang cấp phát)`]]} value={tab} onChange={(k) => setTab(k as typeof tab)} />
    {!(dash.rows ?? []).some((r) => Number(r.qty) > 0) && dash.rows && <div className="rounded-xl bg-amber-50 border border-amber-300 px-3 py-2 text-sm">Trại {sess.farmId} chưa có tồn kho — chọn trại F01 (góc trên trái) để xem dữ liệu, hoặc nhập kho bên dưới.</div>}
    <div className="text-xs text-slate-500 flex items-center gap-2">Số liệu dự trữ/dự báo tính từ bản cache theo trại (làm mới ≤15 phút hoặc ngay khi có nhập/xuất/đàn thay đổi){(cst.rows ?? [])[0]?.refreshed_at ? ` · cập nhật ${fmt.dt(String((cst.rows ?? [])[0].refreshed_at))}` : ""}<button className="underline" onClick={async () => { await fetch("/api/actions", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ action: "refresh_cache" }) }); dash.reload(); fill.reload(); cst.reload(); }}>⟳ làm mới ngay</button></div>
    {msg && <div className="rounded-xl bg-emerald-50 border border-emerald-300 px-3 py-2 text-sm">{msg}</div>}
    {tab === "vao" && <Block groups={sgroups.rows ?? []} sess={sess} onChanged={() => { dash.reload(); fill.reload(); }} R0={rows("DAU_VAO")} W={(fill.rows ?? []).filter((w) => w.block === "DAU_VAO")} b="DAU_VAO" title="Kho đầu vào: còn bao nhiêu · dùng bao nhiêu/ngày · đang về · dự kiến tồn · cần bổ sung" hint="K1 thuốc/vaccine · K2 nguyên liệu · K3 hào ủ/silo · K4 thức ăn TP · K7 nhiên liệu · K9 bao bì (giống trong K1)" />}
    {tab === "ra" && <Block groups={sgroups.rows ?? []} sess={sess} onChanged={() => { dash.reload(); fill.reload(); }} R0={rows("DAU_RA")} W={(fill.rows ?? []).filter((w) => w.block === "DAU_RA")} b="DAU_RA" title="Kho đầu ra: thành phẩm còn · bán/ngày · đơn đã chốt · dự kiến tồn · cần sản xuất thêm" hint="K5 thành phẩm SKU · K6 kho lạnh" />}
    {tab === "cc" && <div className="space-y-3">
      <div className="grid grid-cols-2 sm:grid-cols-4 gap-2"><div className="kpi"><div className="l">Kho công cụ (khu vực)</div><div className="v">{(fill.rows ?? []).filter((w) => w.block === "CONG_CU").length}</div></div><div className="kpi"><div className="l">Dụng cụ định nghĩa</div><div className="v">{(cat.rows ?? []).length}</div></div><div className="kpi"><div className="l">Đang cấp phát</div><div className="v">{(issued.rows ?? []).length}</div></div><div className="kpi"><div className="l">Quá hạn trả</div><div className={`v ${(issued.rows ?? []).some((i) => i.overdue) ? "text-red-700" : ""}`}>{(issued.rows ?? []).filter((i) => i.overdue).length}</div></div></div>
      <div className="grid md:grid-cols-4 gap-2">{(fill.rows ?? []).filter((w) => w.block === "CONG_CU").map((w) => <div key={String(w.warehouse_id)} className="card !p-3"><b>{String(w.code)}</b> <span className="text-sm">{String(w.name)}</span><div className="text-xs text-slate-500">{String(w.area ?? "")} · {fmt.n(Number(w.qty))} cái · {String(w.skus)} loại</div></div>)}</div>
      {canW && <div className="grid lg:grid-cols-2 gap-3"><div className="card"><b>Cấp phát công cụ</b><div className="grid sm:grid-cols-3 lg:grid-cols-6 gap-2 mt-2"><select className="input" value={String(isF.warehouse_id ?? "")} onChange={(e) => setIsF({ ...isF, warehouse_id: e.target.value })}><option value="">Kho</option>{(wh.rows ?? []).filter((w) => w.block === "CONG_CU").map((w) => <option key={String(w.id)} value={String(w.id)}>{String(w.code)}</option>)}</select><select className="input lg:col-span-2" value={String(isF.sku ?? "")} onChange={(e) => setIsF({ ...isF, sku: e.target.value })}><option value="">Dụng cụ</option>{(tools.rows ?? []).filter((t) => !isF.warehouse_id || t.warehouse_id === isF.warehouse_id).map((t) => <option key={String(t.warehouse_id) + String(t.sku)} value={String(t.sku)}>{String(t.name)} (còn {String(t.available)})</option>)}</select><input className="input" type="number" placeholder="SL" value={String(isF.qty ?? 1)} onChange={(e) => setIsF({ ...isF, qty: e.target.value })} /><select className="input" value={String(isF.staff_id ?? "")} onChange={(e) => setIsF({ ...isF, staff_id: e.target.value })}><option value="">Người nhận</option>{(staff.rows ?? []).map((s) => <option key={String(s.id)} value={String(s.id)}>{String(s.full_name)}</option>)}</select><input className="input" type="date" value={String(isF.due_back ?? "")} onChange={(e) => setIsF({ ...isF, due_back: e.target.value })} /><input className="input lg:col-span-5" placeholder="Mục đích / vị trí dùng" value={String(isF.purpose ?? "")} onChange={(e) => setIsF({ ...isF, purpose: e.target.value })} /><button className="btn-primary !py-2" disabled={!isF.warehouse_id || !isF.sku} onClick={async () => { const j = await act("tool_issue", { ...isF, qty: Number(isF.qty ?? 1) }); setMsg(j.ok ? "Đã cấp phát" : String(j.error)); issued.reload(); tools.reload(); hist.reload(); }}>Cấp</button></div></div>
        <div className="card"><b>Chuyển kho công cụ giữa khu vực</b><div className="grid sm:grid-cols-5 gap-2 mt-2"><select className="input" value={String(mvF.from_wh ?? "")} onChange={(e) => setMvF({ ...mvF, from_wh: e.target.value })}><option value="">Từ kho</option>{(wh.rows ?? []).filter((w) => w.block === "CONG_CU").map((w) => <option key={String(w.id)} value={String(w.id)}>{String(w.code)}</option>)}</select><select className="input" value={String(mvF.to_wh ?? "")} onChange={(e) => setMvF({ ...mvF, to_wh: e.target.value })}><option value="">Đến kho</option>{(wh.rows ?? []).filter((w) => w.block === "CONG_CU").map((w) => <option key={String(w.id)} value={String(w.id)}>{String(w.code)}</option>)}</select><select className="input" value={String(mvF.sku ?? "")} onChange={(e) => setMvF({ ...mvF, sku: e.target.value })}><option value="">Dụng cụ</option>{(cat.rows ?? []).map((t) => <option key={String(t.sku)} value={String(t.sku)}>{String(t.name)}</option>)}</select><input className="input" type="number" placeholder="SL" value={String(mvF.qty ?? "")} onChange={(e) => setMvF({ ...mvF, qty: e.target.value })} /><button className="btn-secondary !py-2" disabled={!mvF.from_wh || !mvF.to_wh || !mvF.sku || !mvF.qty} onClick={async () => { const j = await act("tool_move", mvF); setMsg(j.ok ? "Đã chuyển" : String(j.error)); tools.reload(); fill.reload(); }}>Chuyển</button></div><div className="text-xs text-slate-500 mt-1">Nhập mua công cụ mới: form Kho › Nhập (chọn kho KCC-*) hoặc PO. Định nghĩa dụng cụ mới: <a className="underline" href="/quan-tri?t=products">products kind=CONG_CU</a> (nhóm, đơn vị, tuổi thọ, giá, cần chứng chỉ).</div></div></div>}
      <div className="card !p-3"><div className="text-sm font-bold">Số lượng công cụ theo kho/khu vực × nhóm</div><div style={{ height: 220 }}><ResponsiveContainer><BarChart data={(fill.rows ?? []).filter((w) => w.block === "CONG_CU").map((w) => { const o: Record<string, unknown> = { kho: `${w.code}` }; for (const t of (tools.rows ?? []).filter((t) => t.warehouse_id === w.warehouse_id)) o[String(t.tool_group)] = Number(o[String(t.tool_group)] ?? 0) + Number(t.on_hand); return o; })}><CartesianGrid strokeDasharray="3 3" /><XAxis dataKey="kho" tick={{ fontSize: 11 }} /><YAxis tick={{ fontSize: 10 }} width={40} /><Tooltip /><Legend wrapperStyle={{ fontSize: 11 }} />{groups.map((g, i) => <Bar key={g} dataKey={g} stackId="a" fill={["#059669", "#0ea5e9", "#f59e0b", "#8b5cf6", "#ef4444", "#14b8a6", "#64748b", "#84cc16", "#f97316", "#a855f7"][i % 10]} />)}</BarChart></ResponsiveContainer></div></div>
      <div className="card p-0 overflow-auto"><div className="px-3 py-2 bg-slate-100 rounded-t-xl font-bold flex items-center gap-2 flex-wrap">Tồn công cụ theo kho/khu vực <select className="input !w-48 !py-1 font-normal text-sm" value={grp} onChange={(e) => setGrp(e.target.value)}><option value="">Mọi nhóm</option>{groups.map((g) => <option key={g}>{g}</option>)}</select><a className="ml-auto underline text-sm font-normal" href="/api/admin/products?csv=1">xuất danh mục</a></div>
        <table className="tbl text-sm"><thead><tr><th className="pl-3">Kho · khu vực</th><th>Dụng cụ</th><th>Nhóm</th><th className="text-right">Có</th><th className="text-right">Đang cấp</th><th className="text-right">Sẵn</th><th className="text-right">Min</th><th className="text-right">Hỏng/mất 12th</th><th className="text-right">Tuổi thọ (th)</th><th></th></tr></thead><tbody>{(tools.rows ?? []).filter((t) => !grp || t.tool_group === grp).map((t) => <tr key={String(t.warehouse_id) + String(t.sku)} className={t.min_qty != null && Number(t.available) < Number(t.min_qty) ? "bg-red-50" : ""}><td className="pl-3"><b>{String(t.warehouse_code)}</b> <span className="text-xs text-slate-500">{String(t.area ?? "")}</span></td><td>{String(t.name)}{t.needs_cert ? <span className="text-xs text-amber-700"> · cần chứng chỉ</span> : null}</td><td className="text-xs">{String(t.tool_group ?? "")}</td><td className="text-right font-bold">{String(t.on_hand)}</td><td className="text-right">{String(t.issued)}</td><td className="text-right">{String(t.available)}</td><td className="text-right">{String(t.min_qty ?? "")}</td><td className="text-right">{String(t.lost_broken_12m ?? 0)}</td><td className="text-right">{String(t.life_months ?? "")}</td><td><ChartIcon type="product" id={String(t.sku)} /></td></tr>)}</tbody></table></div>
      <div className="grid lg:grid-cols-2 gap-3"><div className="card p-0 overflow-auto"><div className="px-3 py-2 bg-slate-100 rounded-t-xl font-bold">Đang cấp phát (chưa thu hồi)</div><table className="tbl text-sm"><thead><tr><th className="pl-3">Dụng cụ</th><th>Người</th><th>Kho</th><th className="text-right">SL</th><th>Từ</th><th>Hạn trả</th><th></th></tr></thead><tbody>{(issued.rows ?? []).map((i) => <tr key={String(i.id)} className={i.overdue ? "bg-red-50" : ""}><td className="pl-3">{String(i.tool_name)}</td><td>{String(i.staff_name ?? i.dept ?? "")}</td><td className="text-xs">{String(i.warehouse_code)}</td><td className="text-right">{String(i.qty)}</td><td className="text-xs">{fmt.d(String(i.issued_at))}</td><td className="text-xs">{i.due_back ? fmt.d(String(i.due_back)) : ""}{i.overdue ? " ⚠" : ""}</td><td className="text-xs whitespace-nowrap">{canW && ["TOT", "HAO_MON", "HONG", "MAT"].map((c) => <button key={c} className={`underline mr-1 ${c === "HONG" || c === "MAT" ? "text-red-700" : ""}`} onClick={async () => { const rq = c === "MAT" ? "0" : c === "HONG" ? prompt(`Số còn dùng được (đã cấp ${i.qty})?`, "0") : String(i.qty); if (rq == null) return; const j = await act("tool_return", { id: i.id, condition: c, returned_qty: Number(rq) }); setMsg(j.ok ? `Đã thu hồi (${c})` : String(j.error)); issued.reload(); tools.reload(); hist.reload(); }}>{c === "TOT" ? "trả tốt" : c === "HAO_MON" ? "hao mòn" : c === "HONG" ? "hỏng" : "mất"}</button>)}</td></tr>)}</tbody></table>{!(issued.rows ?? []).length && <div className="p-3 text-sm text-slate-500">Không có công cụ đang cấp phát.</div>}</div>
        <div className="card"><AnyChart title="Xuất công cụ (hỏng/mất/chuyển) theo lý do" table="inventory_moves" col="qty" dim="reason" bucket="month" filters={{ direction: "-1" }} height={220} /><div className="text-xs text-slate-500 mt-1">Bấm 📈 ở từng dòng để xem biến động riêng dụng cụ đó (nhập/xuất, so kỳ trước). Lịch sử cấp phát: <a className="underline" href="/quan-tri?t=tool_issues">tool_issues</a>.</div></div></div>
      <div className="card p-0 overflow-auto"><div className="px-3 py-2 bg-slate-100 rounded-t-xl font-bold">Danh mục dụng cụ đã định nghĩa ({(cat.rows ?? []).length})</div><div className="p-2 flex flex-wrap gap-1">{(cat.rows ?? []).map((t) => <span key={String(t.sku)} className="rounded-lg border px-2 py-0.5 text-xs" title={`${t.tool_group} · ${t.unit} · ${t.life_months} tháng · ${fmt.vnd(Number(t.ref_price ?? 0))}`}>{String(t.name)}</span>)}</div></div></div>}
  </div>;
}
