"use client";
import { useEffect, useState } from "react";
import { fmt } from "@/lib/client";
import type { Sess } from "@/components/Shell";
import AnyChart from "@/components/AnyChart";
import Attachments from "@/components/Attachments";
type Row = Record<string, unknown>;
const FK: [string, string][] = [["CHUONG", "Chuồng trại"], ["KHO", "Kho"], ["XUONG", "Xưởng"], ["NHA_DIEU_HANH", "Nhà điều hành"], ["AO", "Ao / bể nước"], ["BE_BIOGAS", "Bể biogas"], ["TRAM_DIEN", "Trạm điện / solar"], ["GIENG", "Giếng / nguồn nước"], ["BE_NUOC", "Bể chứa"], ["NHA_KINH", "Nhà kính / màng"], ["SAN_PHOI", "Sân phơi"], ["CAN", "Trạm cân"], ["CONG", "Cổng / kiểm dịch"], ["DUONG", "Đường nội bộ"], ["HANG_RAO", "Hàng rào"], ["NHA_O", "Nhà ở công nhân"], ["KHAC", "Khác"]];
const FIELDS: [string, string, string?][] = [["name", "Tên trại"], ["legal_entity", "Pháp nhân"], ["tax_code", "Mã số thuế"], ["address", "Địa chỉ"], ["province", "Tỉnh"], ["phone", "Điện thoại"], ["manager_id", "Mã GĐ trại (NS-…)"], ["opened_on", "Ngày hoạt động", "date"], ["kind", "Loại (CAMPUS/HUB/VE_TINH)"], ["lat", "Vĩ độ", "number"], ["lng", "Kinh độ", "number"], ["elevation_m", "Cao độ (m)", "number"], ["land_total_ha", "Tổng diện tích (ha)", "number"], ["land_biomass_ha", "Đất sinh khối (ha)", "number"], ["land_core_ha", "Lõi chuồng–xưởng (ha)", "number"], ["water_ha", "Mặt nước (ha)", "number"], ["land_other_ha", "Khác: viền/rừng/đường (ha)", "number"], ["k_factor", "K (con/ha sinh khối)", "number"], ["design_head", "Đàn thiết kế (con)", "number"], ["power_kva", "Điện lưới (kVA)", "number"], ["solar_kwp", "Solar (kWp)", "number"], ["water_source", "Nguồn nước"], ["water_m3_day", "Nước (m³/ngày)", "number"], ["road_access", "Giao thông"], ["bank_account", "TK ngân hàng"], ["design_notes", "Ghi chú thiết kế"]];

/** HỒ SƠ TRẠI: thông số chi tiết · nhà công năng (thêm/sửa/gỡ) · nhân sự trại · kho/khu/ô · đàn · biểu đồ · lịch sử */
export default function FarmProfile({ sess, farmId }: { sess: Sess; farmId: string }) {
  const [f, setF] = useState<Row | null>(null); const [fac, setFac] = useState<Row[]>([]); const [staff, setStaff] = useState<Row[]>([]); const [wh, setWh] = useState<Row[]>([]); const [loc, setLoc] = useState<Row[]>([]); const [plots, setPlots] = useState<Row[]>([]); const [edit, setEdit] = useState(false); const [ef, setEf] = useState<Row>({}); const [nf, setNf] = useState<Row | null>(null); const [msg, setMsg] = useState("");
  const [lic, setLic] = useState<{ kind: string; number: string; issued: string; expires: string }[]>([]);
  const canW = ["owner", "director", "it_engineer"].includes(sess.role);
  const load = async () => {
    const [a, b, c, d, e, g] = await Promise.all([fetch(`/api/data/farm_profile?farm=${farmId}`).then((r) => r.json()), fetch(`/api/admin/facilities?farm=${farmId}&limit=500`).then((r) => r.json()), fetch(`/api/admin/staff?farm=${farmId}&limit=500`).then((r) => r.json()), fetch(`/api/admin/warehouses?farm=${farmId}`).then((r) => r.json()), fetch(`/api/admin/locations?farm=${farmId}&limit=500`).then((r) => r.json()), fetch(`/api/admin/plots?farm=${farmId}&limit=500`).then((r) => r.json())]);
    const row = (a.rows ?? []).find((x: Row) => x.id === farmId) ?? a.rows?.[0] ?? null; setF(row); setEf(row ?? {}); setLic(Array.isArray(row?.licenses) ? (row.licenses as typeof lic) : []); setFac(b.rows ?? []); setStaff((c.rows ?? []).filter((s: Row) => s.farm_id === farmId || (s.farm_ids as string[] | null)?.includes(farmId))); setWh(d.rows ?? []); setLoc(e.rows ?? []); setPlots(g.rows ?? []);
  };
  useEffect(() => { load(); // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [farmId]);
  const save = async () => { const row: Row = { id: farmId }; for (const [k] of FIELDS) row[k] = ef[k] ?? null; row.licenses = lic; const j = await fetch("/api/admin/farms", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ row }) }).then((r) => r.json()); setMsg(j.ok ? "Đã lưu hồ sơ trại (lịch sử đã ghi)" : `${j.error}: ${j.detail ?? ""}`); setEdit(false); load(); };
  const saveFac = async () => { if (!nf) return; const j = await fetch("/api/admin/facilities", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ row: { ...nf, farm_id: farmId } }) }).then((r) => r.json()); setMsg(j.ok ? `Đã lưu ${String(j.row?.name)}` : `${j.error}: ${j.detail ?? ""}`); setNf(null); load(); };
  const removeFac = async (id: string) => { if (!confirm("Gỡ hạng mục này? (giữ lịch sử)")) return; await fetch(`/api/admin/facilities?pk=${id}`, { method: "DELETE" }); load(); };
  if (!f) return <div className="card">Đang tải hồ sơ trại {farmId}…</div>;
  const land = ["land_biomass_ha", "land_core_ha", "water_ha", "land_other_ha"].map((k) => [k, Number(f[k] ?? 0)] as [string, number]); const landTotal = Number(f.land_total_ha ?? f.s_ha ?? 0);
  return (
    <div className="space-y-3">
      <div className="card"><div className="flex items-center gap-3 flex-wrap"><span className="text-3xl font-black">{farmId}</span><div><div className="font-bold text-lg">{String(f.name)}</div><div className="text-sm text-stone-600">{String(f.region_name ?? "")} · {String(f.province ?? "")} · {String(f.legal_entity ?? "")} · {String(f.kind)} · {String(f.scale_band ?? "")}</div></div>
        <span className={`ml-auto ${f.status === "ACTIVE" ? "b-grn" : "b-gray"}`}>{String(f.status)}</span>{canW && <button className="btn-secondary !py-1 !px-3 !text-sm" onClick={() => setEdit(!edit)}>{edit ? "Đóng" : "✎ Sửa thông số"}</button>}<a className="underline text-sm" href={`/quan-tri?t=farms&pk=${farmId}`}>lịch sử</a><a className="underline text-sm" href={`/api/exports/all?farm=${farmId}`}>xuất toàn bộ dữ liệu</a></div>
        <div className="grid grid-cols-2 sm:grid-cols-4 lg:grid-cols-8 gap-2 mt-3">
          {[["Tổng DT", `${fmt.n(landTotal, 1)} ha`], ["Sinh khối", `${fmt.n(f.land_biomass_ha, 1)} ha`], ["Lõi", `${fmt.n(f.land_core_ha, 2)} ha`], ["Mặt nước", `${fmt.n(f.water_ha, 1)} ha`], ["Đàn sống", `${fmt.n(f.animals_alive)} / TK ${fmt.n(f.design_head)}`], ["Nhân sự", fmt.n(f.staff_n)], ["Hạ tầng", `${fmt.n(f.facilities_n)} hạng mục · ${fmt.n(f.facilities_m2)} m²`], ["Ô/thửa", `${fmt.n(f.plots_n)} · ${fmt.n(f.plots_ha, 1)} ha`], ["Kho", fmt.n(f.warehouses_n)], ["Khu/vị trí", fmt.n(f.locations_n)], ["Thiết bị", fmt.n(f.devices_n)], ["Điện", `${fmt.n(f.power_kva)} kVA + ${fmt.n(f.solar_kwp)} kWp`], ["Nước", `${String(f.water_source ?? "—")} ${f.water_m3_day ? fmt.n(f.water_m3_day) + " m³/ng" : ""}`], ["Giao thông", String(f.road_access ?? "—")], ["Tọa độ", f.lat ? `${f.lat}, ${f.lng}` : "—"], ["Hoạt động từ", f.opened_on ? fmt.d(f.opened_on) : "—"]].map(([l, v]) => <div key={l} className="kpi !p-2"><div className="l">{l}</div><div className="text-sm font-bold truncate" title={String(v)}>{String(v)}</div></div>)}
        </div>
        {landTotal > 0 && <div className="mt-2 flex h-4 rounded overflow-hidden text-[10px] text-white">{land.map(([k, v], i) => v > 0 ? <div key={k} style={{ width: `${(v / landTotal) * 100}%`, background: ["#15803d", "#b45309", "#0369a1", "#78716c"][i] }} title={`${k}: ${v} ha`} className="text-center truncate">{k.replace("land_", "").replace("_ha", "")} {fmt.n((v / landTotal) * 100)}%</div> : null)}</div>}
        {Array.isArray(f.licenses) && (f.licenses as typeof lic).length > 0 && <div className="mt-2 text-sm"><b>Giấy phép / chứng nhận:</b> {(f.licenses as typeof lic).map((l, i) => <span key={i} className={`ml-2 ${l.expires && new Date(l.expires) < new Date() ? "b-red" : "b-grn"}`}>{l.kind} {l.number} {l.expires ? `hết ${fmt.d(l.expires)}` : ""}</span>)}</div>}
        {msg && <div className="text-sm mt-2 text-green-800">{msg}</div>}
        {edit && <div className="mt-3 border-t pt-3"><div className="grid sm:grid-cols-2 lg:grid-cols-4 gap-2">{FIELDS.map(([k, l, ty]) => <label key={k} className="text-sm"><span className="text-xs text-stone-500">{l}</span><input className="input" type={ty ?? "text"} step="any" value={ef[k] == null ? "" : ty === "date" ? String(ef[k]).slice(0, 10) : String(ef[k])} onChange={(e) => setEf({ ...ef, [k]: e.target.value === "" ? null : ty === "number" ? Number(e.target.value) : e.target.value })} /></label>)}</div>
          <div className="mt-2 text-sm"><b>Giấy phép / chứng nhận</b> (ĐKKD, môi trường, VietGAP/GlobalG.A.P., hữu cơ, ATTP, kiểm dịch, PCCC, giấy phép nước…) <button className="underline ml-2" onClick={() => setLic([...lic, { kind: "", number: "", issued: "", expires: "" }])}>+ thêm</button>
            {lic.map((l, i) => <div key={i} className="flex flex-wrap gap-1 mt-1"><input className="input !w-44 !py-1" placeholder="Loại" value={l.kind} onChange={(e) => setLic(lic.map((x, j) => j === i ? { ...x, kind: e.target.value } : x))} /><input className="input !w-40 !py-1" placeholder="Số" value={l.number} onChange={(e) => setLic(lic.map((x, j) => j === i ? { ...x, number: e.target.value } : x))} /><input type="date" className="input !w-40 !py-1" value={l.issued} onChange={(e) => setLic(lic.map((x, j) => j === i ? { ...x, issued: e.target.value } : x))} /><input type="date" className="input !w-40 !py-1" value={l.expires} onChange={(e) => setLic(lic.map((x, j) => j === i ? { ...x, expires: e.target.value } : x))} /><button className="text-red-700" onClick={() => setLic(lic.filter((_, j) => j !== i))}>✕</button></div>)}</div>
          <button className="btn-primary !py-2 mt-2" onClick={save}>Lưu hồ sơ</button></div>}
      </div>
      <Attachments refTable="farms" refId={farmId} />
      <div className="card p-0 overflow-auto"><div className="px-3 py-2 bg-stone-100 rounded-t-2xl flex items-center gap-2"><b>Nhà công năng / hạ tầng ({fac.length})</b>{canW && <button className="btn-secondary !py-1 !px-3 !text-sm ml-auto" onClick={() => setNf({ kind: "CHUONG", status: "HOAT_DONG" })}>＋ Thêm hạng mục</button>}<a className="underline text-sm" href="/api/import/csv?template=facilities">file mẫu CSV</a><a className="underline text-sm" href={`/api/admin/facilities?csv=1&farm=${farmId}`}>xuất CSV</a></div>
        {nf && <div className="p-3 border-b grid sm:grid-cols-3 lg:grid-cols-6 gap-2 bg-green-50"><input className="input" placeholder="Mã (CHUONG-BO-2)" value={String(nf.code ?? "")} onChange={(e) => setNf({ ...nf, code: e.target.value.toUpperCase() })} /><input className="input lg:col-span-2" placeholder="Tên hạng mục" value={String(nf.name ?? "")} onChange={(e) => setNf({ ...nf, name: e.target.value })} /><select className="input" value={String(nf.kind)} onChange={(e) => setNf({ ...nf, kind: e.target.value })}>{FK.map(([k, l]) => <option key={k} value={k}>{l}</option>)}</select><input className="input" type="number" placeholder="Diện tích m²" value={String(nf.area_m2 ?? "")} onChange={(e) => setNf({ ...nf, area_m2: Number(e.target.value) })} /><input className="input" type="number" placeholder="Công suất" value={String(nf.capacity ?? "")} onChange={(e) => setNf({ ...nf, capacity: Number(e.target.value) })} /><input className="input" placeholder="ĐV công suất (con/tấn/m³/kVA)" value={String(nf.capacity_unit ?? "")} onChange={(e) => setNf({ ...nf, capacity_unit: e.target.value })} /><input className="input" type="number" placeholder="Năm XD" value={String(nf.built_year ?? "")} onChange={(e) => setNf({ ...nf, built_year: Number(e.target.value) })} /><input className="input" type="number" placeholder="Giá trị (đ)" value={String(nf.cost ?? "")} onChange={(e) => setNf({ ...nf, cost: Number(e.target.value) })} /><select className="input" value={String(nf.status)} onChange={(e) => setNf({ ...nf, status: e.target.value })}>{["HOAT_DONG", "BAO_TRI", "NGUNG", "KE_HOACH"].map((s) => <option key={s}>{s}</option>)}</select><select className="input" value={String(nf.location_id ?? "")} onChange={(e) => setNf({ ...nf, location_id: e.target.value })}><option value="">— khu —</option>{loc.map((l) => <option key={String(l.id)} value={String(l.id)}>{String(l.name)}</option>)}</select><input className="input lg:col-span-2" placeholder="Ghi chú / thông số kỹ thuật" value={String(nf.note ?? "")} onChange={(e) => setNf({ ...nf, note: e.target.value })} /><div className="flex gap-2"><button className="btn-primary !py-2" onClick={saveFac}>Lưu</button><button className="btn-secondary !py-2" onClick={() => setNf(null)}>Hủy</button></div></div>}
        <table className="tbl text-sm"><thead><tr><th className="pl-3">Mã</th><th>Tên</th><th>Loại</th><th className="text-right">m²</th><th className="text-right">Công suất</th><th>Năm</th><th className="text-right">Giá trị</th><th>TT</th><th>Khu</th><th></th></tr></thead><tbody>{fac.map((x) => <tr key={String(x.id)}><td className="pl-3 font-mono text-xs">{String(x.code)}</td><td className="font-semibold">{String(x.name)}{x.note ? <div className="text-xs text-stone-500 font-normal">{String(x.note)}</div> : null}</td><td>{FK.find(([k]) => k === x.kind)?.[1] ?? String(x.kind)}</td><td className="text-right">{fmt.n(x.area_m2)}</td><td className="text-right">{x.capacity ? `${fmt.n(x.capacity)} ${String(x.capacity_unit ?? "")}` : ""}</td><td>{String(x.built_year ?? "")}</td><td className="text-right">{x.cost ? fmt.vnd(x.cost) : ""}</td><td><span className={x.status === "HOAT_DONG" ? "b-grn" : x.status === "KE_HOACH" ? "b-yel" : "b-red"}>{String(x.status)}</span></td><td className="text-xs">{String(loc.find((l) => l.id === x.location_id)?.name ?? "")}</td><td className="text-xs whitespace-nowrap">{canW && <><button className="underline mr-2" onClick={() => setNf({ ...x })}>sửa</button><button className="underline text-red-700" onClick={() => removeFac(String(x.id))}>gỡ</button></>}</td></tr>)}</tbody></table>
        <div className="px-3 py-2 text-sm text-stone-600">Tổng: {fmt.n(fac.reduce((a, x) => a + Number(x.area_m2 ?? 0), 0))} m² xây dựng · giá trị {fmt.vnd(fac.reduce((a, x) => a + Number(x.cost ?? 0), 0))}</div></div>
      <div className="grid md:grid-cols-2 gap-3">
        <div className="card p-0 overflow-auto"><div className="px-3 py-2 bg-stone-100 rounded-t-2xl flex items-center"><b>Nhân sự trại ({staff.length})</b><a className="underline text-sm ml-auto" href="/quan-tri?t=staff">quản lý · thêm · nhập CSV</a></div><table className="tbl text-sm"><thead><tr><th className="pl-3">Mã</th><th>Họ tên</th><th>Vai</th><th>Vị trí</th><th>SĐT</th><th>Vào làm</th></tr></thead><tbody>{staff.map((s) => <tr key={String(s.id)} className={s.active === false ? "opacity-50" : ""}><td className="pl-3 font-mono text-xs">{String(s.id)}</td><td className="font-semibold">{String(s.full_name)}</td><td>{String(s.role)}</td><td>{String(s.position ?? "")}</td><td>{String(s.phone ?? "")}</td><td>{s.hired_on ? fmt.d(s.hired_on) : ""}</td></tr>)}</tbody></table></div>
        <div className="space-y-3">
          <div className="card p-0 overflow-auto"><div className="px-3 py-2 bg-stone-100 rounded-t-2xl"><b>Kho ({wh.length})</b> · <a className="underline text-sm" href="/quan-tri?t=warehouses">quản lý</a></div><table className="tbl text-sm"><tbody>{wh.map((w) => <tr key={String(w.id)}><td className="pl-3 font-mono">{String(w.code)}</td><td>{String(w.name)}</td><td className="text-xs">{String(w.unit_kind)} · kiểm {String(w.count_cycle)}{w.temp_monitored ? " · 🌡" : ""}</td></tr>)}</tbody></table></div>
          <div className="card p-0 overflow-auto"><div className="px-3 py-2 bg-stone-100 rounded-t-2xl"><b>Khu / vị trí ({loc.length}) · Ô thửa ({plots.length}, {fmt.n(plots.reduce((a, p) => a + Number(p.area_ha ?? 0), 0), 1)} ha)</b> · <a className="underline text-sm" href="/quan-tri?t=locations">khu</a> · <a className="underline text-sm" href="/quan-tri?t=plots">ô thửa</a> · <a className="underline text-sm" href="/so-do">sơ đồ</a></div><table className="tbl text-sm"><tbody>{loc.slice(0, 30).map((l) => <tr key={String(l.id)}><td className="pl-3 font-mono">{String(l.code)}</td><td>{String(l.name)}</td><td className="text-xs">{String(l.kind)} · tầng {String(l.elevation_tier ?? "")}{l.capacity ? ` · sức chứa ${fmt.n(l.capacity)}` : ""}</td></tr>)}{plots.slice(0, 30).map((p) => <tr key={String(p.id)}><td className="pl-3 font-mono">{String(p.id).split("-").slice(1).join("-")}</td><td>{String(p.name)}</td><td className="text-xs">{fmt.n(p.area_ha, 2)} ha · {String(p.current_crop ?? p.kind ?? "")}</td></tr>)}</tbody></table></div>
        </div>
      </div>
      <div className="grid md:grid-cols-2 gap-3"><div className="card"><AnyChart title="Đàn theo ngày (snapshot)" table="herd_daily" col="head" agg="sum" dim="species" bucket="week" height={200} /></div><div className="card"><AnyChart title="Nhập kho theo tuần (mọi mặt hàng)" table="inventory_moves" col="qty" dim="sku" filters={{ direction: "1" }} bucket="week" height={200} /></div></div>
    </div>);
}
