"use client";
import Tabs from "@/components/Tabs";
import { useState } from "react";
import { useData, act, fmt } from "@/lib/client";
import { BankReconPanel } from "@/components/panels/CloseoutBits";
import type { Sess } from "@/components/Shell";
type R = Record<string, unknown>;
/** Tài chính nâng cao: phải trả NCC theo hạn + trả tiền, khoản vay + lịch + trả kỳ (GL 341/635), ma trận ủy quyền (dữ liệu), bảo hiểm + bồi thường, thuế GTGT, lịch thanh toán 13 tuần, hợp nhất đa pháp nhân */
export function FinanceMorePanel({ sess }: { sess: Sess }) {
  const [tab, setTab] = useState<"ap" | "vay" | "uyquyen" | "baohiem" | "thue" | "lich" | "hopnhat" | "bank">("lich");
  const ap = useData("ap_summary"); const apRows = useData("ap_aging"); const loans = useData("loans"); const [loanSel, setLoanSel] = useState<string | null>(null); const sched = useData(loanSel ? "loan_schedule" : null, { loan: loanSel ?? undefined }, [loanSel]);
  const am = useData("approval_matrix"); const ins = useData("insurance"); const claims = useData("insurance_claims"); const vat = useData("vat_summary"); const cal = useData("payment_calendar"); const les = useData("legal_entities");
  const [period, setPeriod] = useState(new Date().toISOString().slice(0, 7)); const cons = useData("consolidated", { period }, [period]); const byEnt = useData("gl_by_entity", { period }, [period]);
  const [msg, setMsg] = useState(""); const canPay = ["owner", "director", "accountant"].includes(sess.role);
  const sum = (rows: R[] | null, k: string) => (rows ?? []).reduce((a, r) => a + Number(r[k] ?? 0), 0);
  const weeks = Array.from({ length: 13 }, (_, i) => { const d0 = new Date(); d0.setDate(d0.getDate() + i * 7); const d1 = new Date(d0); d1.setDate(d1.getDate() + 7); const rows = (cal.rows ?? []).filter((r) => { const d = new Date(String(r.due_date)); return d >= (i === 0 ? new Date(0) : d0) && d < d1; }); return { i, from: d0, rows, total: rows.reduce((a, r) => a + Number(r.amount ?? 0), 0) }; });
  return <div className="card">
    <Tabs items={[["lich", "📆 Lịch thanh toán 13 tuần"], ["bank", "🏦 Sao kê & đối chiếu"], ["ap", `💸 Phải trả NCC (${fmt.vnd(sum(ap.rows, "unpaid"))})`], ["vay", `🏦 Vay & lãi (${(loans.rows ?? []).filter((l) => l.status === "DANG_VAY").length})`], ["baohiem", `🛡 Bảo hiểm (${(ins.rows ?? []).length})`], ["thue", "🧾 Thuế GTGT"], ["uyquyen", "✍ Ma trận ủy quyền"], ["hopnhat", "🏢 Hợp nhất pháp nhân"]]} value={tab} onChange={(k) => setTab(k as typeof tab)} />
    {tab === "bank" && <BankReconPanel sess={sess} />}
    {msg && <div className="mt-2 text-sm text-emerald-700">{msg}</div>}
    {tab === "lich" && <div className="mt-3 space-y-2"><div className="grid grid-cols-13 gap-1 overflow-x-auto" style={{ gridTemplateColumns: "repeat(13, minmax(80px, 1fr))" }}>{weeks.map((w) => <div key={w.i} className={`rounded-lg p-1 text-center text-xs ${w.total > 0 ? "bg-amber-50 border border-amber-300" : "bg-stone-50"}`}><div className="text-stone-500">T{w.i + 1} · {w.from.getDate()}/{w.from.getMonth() + 1}</div><div className="font-bold">{w.total ? fmt.vnd(w.total) : "—"}</div><div className="text-[10px]">{w.rows.length ? `${w.rows.length} khoản` : ""}</div></div>)}</div>
      <table className="tbl text-sm"><thead><tr><th className="pl-3">Hạn</th><th>Loại</th><th>Ai</th><th>Tham chiếu</th><th className="text-right">Số tiền</th></tr></thead><tbody>{(cal.rows ?? []).map((r, i) => <tr key={i} className={new Date(String(r.due_date)) < new Date() ? "bg-red-50" : ""}><td className="pl-3">{fmt.d(String(r.due_date))}</td><td>{String(r.kind)}</td><td>{String(r.who ?? "")}</td><td className="font-mono text-xs">{String(r.ref)}</td><td className="text-right font-bold">{fmt.vnd(Number(r.amount))}</td></tr>)}</tbody></table><div className="text-xs text-stone-500">Gồm: PO đã duyệt/nhận chưa trả (hạn = ngày nhận + kỳ hạn NCC), chi đã duyệt chưa chi, kỳ vay, phí bảo hiểm tái tục, GTGT ước (nộp ngày 20 tháng sau). Đối chiếu với Dòng tiền dự báo ở trên.</div></div>}
    {tab === "ap" && <div className="mt-3 space-y-2"><div className="grid grid-cols-2 sm:grid-cols-5 gap-2"><div className="kpi"><div className="l">Phải trả</div><div className="v">{fmt.vnd(sum(ap.rows, "unpaid"))}</div></div><div className="kpi"><div className="l">Chưa hạn</div><div className="v">{fmt.vnd(sum(ap.rows, "not_due"))}</div></div><div className="kpi"><div className="l">1–30</div><div className="v text-amber-700">{fmt.vnd(sum(ap.rows, "d1_30"))}</div></div><div className="kpi"><div className="l">31–60</div><div className="v text-orange-700">{fmt.vnd(sum(ap.rows, "d31_60"))}</div></div><div className="kpi"><div className="l">&gt;60</div><div className="v text-red-700">{fmt.vnd(sum(ap.rows, "d60p"))}</div></div></div>
      <table className="tbl text-sm"><thead><tr><th className="pl-3">Hạn</th><th>NCC</th><th>Loại</th><th>Chứng từ</th><th>HĐ</th><th className="text-right">Tổng</th><th className="text-right">Đã trả</th><th className="text-right">Còn</th><th className="text-right">Quá hạn</th><th></th></tr></thead><tbody>{(apRows.rows ?? []).map((r, i) => <tr key={i} className={Number(r.days_overdue) > 0 ? "bg-red-50" : ""}><td className="pl-3">{fmt.d(String(r.due_date))}</td><td>{String(r.partner_name ?? "")}</td><td>{String(r.kind)}</td><td className="font-mono text-xs">{String(r.ref_id)}</td><td className="text-xs">{String(r.invoice_no ?? "")}</td><td className="text-right">{fmt.vnd(Number(r.amount))}</td><td className="text-right">{fmt.vnd(Number(r.paid))}</td><td className="text-right font-bold">{fmt.vnd(Number(r.unpaid))}</td><td className="text-right">{String(r.days_overdue)}</td><td className="text-xs">{canPay && r.kind === "PO" && <button className="underline" onClick={async () => { const a = prompt("Số tiền trả?", String(r.unpaid)); if (!a) return; const ref = prompt("Số UNC / tham chiếu") ?? ""; const j = await act("pay_supplier", { id: r.ref_id, amount: Number(a), ref }); setMsg(j.ok ? "Đã ghi trả NCC (GL 331/112)" : String(j.error)); apRows.reload(); ap.reload(); cal.reload(); }}>trả</button>}</td></tr>)}</tbody></table>{!(apRows.rows ?? []).length && <div className="text-sm text-stone-500 p-2">Không có khoản phải trả.</div>}</div>}
    {tab === "vay" && <div className="mt-3 space-y-2"><div className="flex items-center gap-2 text-sm"><a className="underline" href="/quan-tri?t=loans">＋ khoản vay</a><span className="text-stone-500">· sau khi thêm bấm “sinh lịch” · trả kỳ → GL 341 gốc / 635 lãi / 112</span></div>
      <table className="tbl text-sm"><thead><tr><th className="pl-3">Khoản vay</th><th>Bên cho vay</th><th className="text-right">Gốc</th><th className="text-right">Lãi %/năm</th><th>PP</th><th>Kỳ hạn</th><th className="text-right">Dư nợ</th><th>Kỳ tới</th><th className="text-right">Số tiền</th><th className="text-right">Trễ</th><th>TT</th><th></th></tr></thead><tbody>{(loans.rows ?? []).map((l) => <tr key={String(l.id)} className={loanSel === l.id ? "bg-emerald-50" : Number(l.overdue_installments) > 0 ? "bg-red-50" : ""}><td className="pl-3"><button className="underline" onClick={() => setLoanSel(String(l.id))}>{String(l.id)}</button><div className="text-xs text-stone-500">{String(l.purpose ?? "")}</div></td><td>{String(l.lender)}</td><td className="text-right">{fmt.vnd(Number(l.principal))}</td><td className="text-right">{String(l.rate_pct)}</td><td>{String(l.method)}</td><td className="text-xs">{String(l.start_date)} · {String(l.term_months)} th (ân hạn {String(l.grace_months ?? 0)})</td><td className="text-right font-bold">{fmt.vnd(Number(l.outstanding))}</td><td>{l.next_due ? fmt.d(String(l.next_due)) : ""}</td><td className="text-right">{l.next_amount ? fmt.vnd(Number(l.next_amount)) : ""}</td><td className="text-right">{String(l.overdue_installments)}</td><td>{String(l.status)}</td><td className="text-xs"><button className="underline" onClick={async () => { const j = await act("gen_loan_schedule", { id: l.id }); setMsg(j.ok ? `Đã sinh ${j.n} kỳ` : String(j.error)); loans.reload(); if (loanSel === l.id) sched.reload(); }}>sinh lịch</button></td></tr>)}</tbody></table>
      {loanSel && <div className="rounded-xl bg-stone-50 p-2 overflow-auto"><b>Lịch trả {loanSel}</b><table className="tbl text-sm"><thead><tr><th>Kỳ</th><th>Hạn</th><th className="text-right">Gốc</th><th className="text-right">Lãi</th><th className="text-right">Tổng</th><th className="text-right">Dư sau</th><th>TT</th><th></th></tr></thead><tbody>{(sched.rows ?? []).map((s) => <tr key={String(s.id)} className={s.status === "DA_TRA" ? "text-stone-400" : new Date(String(s.due_date)) < new Date() ? "bg-red-50" : ""}><td>{String(s.seq)}</td><td>{fmt.d(String(s.due_date))}</td><td className="text-right">{fmt.vnd(Number(s.principal))}</td><td className="text-right">{fmt.vnd(Number(s.interest))}</td><td className="text-right font-bold">{fmt.vnd(Number(s.principal) + Number(s.interest))}</td><td className="text-right">{fmt.vnd(Number(s.balance_after))}</td><td>{String(s.status)}</td><td className="text-xs">{canPay && s.status !== "DA_TRA" && <button className="underline" onClick={async () => { const ref = prompt("Số UNC / tham chiếu") ?? ""; const j = await act("pay_loan", { id: s.id, ref }); setMsg(j.ok ? "Đã ghi trả kỳ vay" : String(j.error)); sched.reload(); loans.reload(); cal.reload(); }}>trả kỳ</button>}</td></tr>)}</tbody></table></div>}</div>}
    {tab === "baohiem" && <div className="mt-3 space-y-2"><div className="text-sm"><a className="underline" href="/quan-tri?t=insurance_policies">＋ hợp đồng BH</a> · <a className="underline" href="/quan-tri?t=insurance_claims">＋ hồ sơ bồi thường</a> <span className="text-stone-500">· vật nuôi (NĐ 58/2018 BH nông nghiệp) · tài sản · xe · con người · hàng hóa; sắp hết hạn ≤30 ngày → AL-INSURANCE</span></div>
      <table className="tbl text-sm"><thead><tr><th className="pl-3">Số HĐ</th><th>Hãng</th><th>Loại</th><th>Đối tượng</th><th>Phạm vi</th><th className="text-right">Số tiền BH</th><th className="text-right">Phí</th><th>Hiệu lực</th><th className="text-right">Bồi thường</th><th>TT</th></tr></thead><tbody>{(ins.rows ?? []).map((p) => <tr key={String(p.id)} className={p.expiry_flag === "HET_HAN" ? "bg-red-50" : p.expiry_flag === "SAP_HET" ? "bg-amber-50" : ""}><td className="pl-3 font-mono text-xs">{String(p.policy_no ?? p.id)}</td><td>{String(p.insurer)}</td><td>{String(p.kind)}</td><td className="text-xs">{String(p.subject_type ?? "")}{p.animals_alive != null ? ` (${p.animals_alive} con sống)` : ""}</td><td className="text-xs max-w-[280px] truncate" title={String(p.coverage ?? "")}>{String(p.coverage ?? "")}</td><td className="text-right">{fmt.vnd(Number(p.sum_insured ?? 0))}</td><td className="text-right">{fmt.vnd(Number(p.premium ?? 0))}</td><td className="text-xs">{String(p.start_date)} → {String(p.end_date)} {p.expiry_flag !== "OK" ? `⚠ ${p.expiry_flag}` : ""}</td><td className="text-right">{String(p.n_claims)} · {fmt.vnd(Number(p.claims_paid ?? 0))}</td><td>{String(p.status)}</td></tr>)}</tbody></table>
      {(claims.rows ?? []).length > 0 && <table className="tbl text-sm"><thead><tr><th className="pl-3">Bồi thường</th><th>HĐ</th><th>Ngày sự kiện</th><th>Mô tả</th><th className="text-right">Yêu cầu</th><th className="text-right">Duyệt</th><th className="text-right">Đã nhận</th><th>TT</th><th></th></tr></thead><tbody>{(claims.rows ?? []).map((c) => <tr key={String(c.id)}><td className="pl-3 font-mono text-xs">{String(c.id)}</td><td>{String(c.insurer)} · {String(c.kind)}</td><td>{String(c.event_date)}</td><td className="text-xs">{String(c.description ?? "")}</td><td className="text-right">{fmt.vnd(Number(c.claimed_amount ?? 0))}</td><td className="text-right">{fmt.vnd(Number(c.approved_amount ?? 0))}</td><td className="text-right">{fmt.vnd(Number(c.paid_amount ?? 0))}</td><td>{String(c.status)}</td><td className="text-xs">{canPay && c.status !== "DA_NHAN" && <button className="underline" onClick={async () => { const a = prompt("Số tiền nhận?", String(c.approved_amount ?? c.claimed_amount ?? 0)); if (!a) return; const j = await act("receive_claim", { id: c.id, amount: Number(a) }); setMsg(j.ok ? "Đã ghi nhận bồi thường (GL 112/711)" : String(j.error)); claims.reload(); ins.reload(); }}>nhận tiền</button>}</td></tr>)}</tbody></table>}</div>}
    {tab === "thue" && <div className="mt-3"><table className="tbl text-sm"><thead><tr><th className="pl-3">Kỳ</th><th className="text-right">Doanh thu</th><th className="text-right">GTGT đầu ra</th><th className="text-right">Mua vào</th><th className="text-right">GTGT đầu vào</th><th className="text-right">Phải nộp</th></tr></thead><tbody>{(vat.rows ?? []).map((r) => <tr key={String(r.period)}><td className="pl-3">{String(r.period)}</td><td className="text-right">{fmt.vnd(Number(r.revenue))}</td><td className="text-right">{fmt.vnd(Number(r.vat_out))}</td><td className="text-right">{fmt.vnd(Number(r.purchases))}</td><td className="text-right">{fmt.vnd(Number(r.vat_in))}</td><td className="text-right font-bold">{fmt.vnd(Number(r.vat_payable))}</td></tr>)}</tbody></table><div className="text-xs text-stone-500 p-2">Thuế suất theo <code>products.vat_pct</code> (nông sản sơ chế bán ra thường không chịu thuế/0%; chế biến 5–10%). Đây là ước tính quản trị; kê khai chính thức qua HĐĐT & phần mềm thuế (MISA/…) từ CSV <a className="underline" href="/api/exports/sales-tax">bảng kê bán</a> / <a className="underline" href="/api/exports/purchases">mua</a>.</div></div>}
    {tab === "uyquyen" && <div className="mt-3"><div className="text-sm mb-2">Ma trận ủy quyền là <b>dữ liệu</b> — code đọc <code>approval_limit(kind, role)</code>; sửa tại <a className="underline" href="/quan-tri?t=approval_matrix">approval_matrix</a> (chỉ chủ/GĐ). Luật cứng vẫn giữ: không ai duyệt bản ghi của mình; kế toán không duyệt chi.</div><table className="tbl text-sm"><thead><tr><th className="pl-3">Nghiệp vụ</th><th>Vai</th><th className="text-right">Hạn mức</th><th className="text-right">2 chữ ký khi &gt;</th><th className="text-right">Báo chủ khi &gt;</th><th className="text-right">Số chữ ký</th><th>Ghi chú</th></tr></thead><tbody>{(am.rows ?? []).map((r) => <tr key={String(r.id)}><td className="pl-3 font-semibold">{String(r.kind)}</td><td>{String(r.role)}</td><td className="text-right">{r.max_amount == null ? "∞" : fmt.vnd(Number(r.max_amount))}</td><td className="text-right">{r.two_sign_over ? fmt.vnd(Number(r.two_sign_over)) : ""}</td><td className="text-right">{r.notify_owner_over ? fmt.vnd(Number(r.notify_owner_over)) : ""}</td><td className="text-right">{String(r.min_signers)}</td><td className="text-xs">{String(r.note ?? "")}</td></tr>)}</tbody></table></div>}
    {tab === "hopnhat" && <div className="mt-3 space-y-2"><div className="flex items-center gap-2 text-sm flex-wrap"><b>Pháp nhân:</b>{(les.rows ?? []).map((l) => <span key={String(l.id)} className="rounded-full border px-2 py-0.5">{String(l.name)} <span className="text-stone-500">({String(l.farms ?? "—")})</span></span>)}<a className="underline" href="/quan-tri?t=legal_entities">＋ pháp nhân</a><span className="ml-auto">Kỳ <input className="input !w-32 !py-1" value={period} onChange={(e) => setPeriod(e.target.value)} /></span></div>
      <div className="grid lg:grid-cols-2 gap-3"><div className="overflow-auto"><b>Hợp nhất (cộng dồn mọi pháp nhân, tách nội bộ 136/336)</b><table className="tbl text-sm"><thead><tr><th className="pl-3">TK</th><th>Tên</th><th className="text-right">Nợ</th><th className="text-right">Có</th><th className="text-right">Ròng</th><th className="text-right">PN</th></tr></thead><tbody>{(cons.rows ?? []).map((r) => <tr key={String(r.account)} className={["136", "336"].includes(String(r.account)) ? "text-stone-400" : ""}><td className="pl-3 font-mono">{String(r.account)}</td><td>{String(r.account_name ?? "")}</td><td className="text-right">{fmt.vnd(Number(r.debit))}</td><td className="text-right">{fmt.vnd(Number(r.credit))}</td><td className="text-right font-bold">{fmt.vnd(Number(r.net))}</td><td className="text-right">{String(r.entities)}</td></tr>)}</tbody></table>{!(cons.rows ?? []).length && <div className="text-sm text-stone-500 p-2">Chưa có bút toán kỳ {period}.</div>}</div>
        <div className="overflow-auto"><b>Theo từng pháp nhân</b><table className="tbl text-sm"><thead><tr><th className="pl-3">Pháp nhân</th><th>TK</th><th className="text-right">Nợ</th><th className="text-right">Có</th></tr></thead><tbody>{(byEnt.rows ?? []).map((r, i) => <tr key={i}><td className="pl-3 text-xs">{String(r.entity_name ?? r.legal_entity_id)}</td><td className="font-mono">{String(r.account)}</td><td className="text-right">{fmt.vnd(Number(r.debit))}</td><td className="text-right">{fmt.vnd(Number(r.credit))}</td></tr>)}</tbody></table></div></div><div className="text-xs text-stone-500">Mỗi trại gắn <code>farms.legal_entity_id</code>; giao dịch liên pháp nhân ghi qua 136/336 để loại trừ khi hợp nhất. Sổ cái riêng từng pháp nhân xuất qua /api/exports (GL) theo trại.</div></div>}
  </div>;
}
