"use client";
import { useState } from "react";
import { useData, fmt } from "@/lib/client";
import type { Sess } from "@/components/Shell";
import { LineChart, Line, BarChart, Bar, XAxis, YAxis, Tooltip, Legend, ResponsiveContainer, ReferenceLine } from "recharts";
type R = Record<string, unknown>;
const adminPost = (t: string, row: R) => fetch(`/api/admin/${t}`, { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ row }) }).then((r) => r.json());
/** NGÂN SÁCH vs THỰC TẾ theo tháng × CC (thực tế lấy từ sổ cái GL) */
export function BudgetPanel({ sess }: { sess: Sess }) {
  const bva = useData("budget_vs_actual"); const ccs = useData("cost_centers"); const [f, setF] = useState<R | null>(null); const [msg, setMsg] = useState(""); const canW = ["owner", "director", "accountant"].includes(sess.role);
  const rows = bva.rows ?? []; const y = new Date().getFullYear();
  const byMonth = Array.from({ length: 12 }, (_, i) => { const m = i + 1; const r = rows.filter((x) => Number(x.year) === y && Number(x.month) === m); const s = (k: string, kind: string) => r.filter((x) => x.kind === kind).reduce((a, x) => a + Number(x[k] ?? 0), 0); return { t: `T${m}`, "NS thu": s("budget", "DOANH_THU"), "Thực thu": s("actual", "DOANH_THU"), "NS chi": s("budget", "CHI_PHI"), "Thực chi": s("actual", "CHI_PHI") }; });
  return (<div className="card space-y-2"><div className="flex items-center gap-2 flex-wrap"><b>Ngân sách – thực tế {y}</b>{canW && <button className="btn-secondary !py-1 !px-3 !text-sm" onClick={() => setF({ year: y, month: new Date().getMonth() + 1, kind: "CHI_PHI" })}>＋ Dòng ngân sách</button>}<a className="underline text-sm ml-auto" href="/quan-tri?t=budgets&tab=nhap">nhập CSV cả năm</a></div>
    {f && <div className="grid sm:grid-cols-3 lg:grid-cols-6 gap-2 text-sm"><input className="input" type="number" value={String(f.year)} onChange={(e) => setF({ ...f, year: Number(e.target.value) })} /><input className="input" type="number" min={1} max={12} placeholder="tháng (trống = cả năm)" aria-label="tháng (trống = cả năm)" value={String(f.month ?? "")} onChange={(e) => setF({ ...f, month: e.target.value ? Number(e.target.value) : null })} /><select className="input" value={String(f.cost_center ?? "")} onChange={(e) => setF({ ...f, cost_center: e.target.value || null })}><option value="">Toàn trại</option>{(ccs.rows ?? []).map((c) => <option key={String(c.id)} value={String(c.id)}>{String(c.name)}</option>)}</select><select className="input" value={String(f.kind)} onChange={(e) => setF({ ...f, kind: e.target.value })}><option value="DOANH_THU">Doanh thu</option><option value="CHI_PHI">Chi phí</option><option value="DAU_TU">Đầu tư</option></select><input className="input" type="number" placeholder="Số tiền" aria-label="Số tiền" value={String(f.amount ?? "")} onChange={(e) => setF({ ...f, amount: Number(e.target.value) })} /><div className="flex gap-2"><button className="btn-primary !py-2" onClick={async () => { const j = await adminPost("budgets", { ...f, created_by: sess.staffId }); setMsg(j.ok ? "Đã lưu" : `${j.error}: ${j.detail ?? ""}`); setF(null); bva.reload(); }}>Lưu</button><button className="btn-secondary !py-2" onClick={() => setF(null)}>Hủy</button></div></div>}{msg && <div className="text-sm text-emerald-700">{msg}</div>}
    <div style={{ height: 240 }}><ResponsiveContainer><BarChart data={byMonth}><XAxis dataKey="t" fontSize={11} /><YAxis fontSize={11} tickFormatter={(v: number) => fmt.n(v / 1e6) + "tr"} /><Tooltip formatter={(v: unknown) => fmt.vnd(Number(v))} /><Legend /><Bar dataKey="NS thu" fill="#a7f3d0" /><Bar dataKey="Thực thu" fill="#059669" /><Bar dataKey="NS chi" fill="#fecaca" /><Bar dataKey="Thực chi" fill="#dc2626" /></BarChart></ResponsiveContainer></div>
    <div className="overflow-auto max-h-72"><table className="tbl text-xs"><thead><tr><th className="pl-2">Năm</th><th>Tháng</th><th>CC</th><th>Loại</th><th className="text-right">Ngân sách</th><th className="text-right">Thực tế</th><th className="text-right">Chênh</th><th className="text-right">%</th></tr></thead><tbody>{rows.filter((r) => Number(r.year) === y).map((r, i) => <tr key={i} className={r.kind === "CHI_PHI" && Number(r.pct) > 100 ? "bg-red-50" : ""}><td className="pl-2">{String(r.year)}</td><td>{String(r.month)}</td><td>{String(r.cc)}</td><td>{String(r.kind)}</td><td className="text-right">{fmt.vnd(r.budget)}</td><td className="text-right font-semibold">{fmt.vnd(r.actual)}</td><td className={`text-right ${Number(r.variance) > 0 && r.kind === "CHI_PHI" ? "text-red-700" : ""}`}>{fmt.vnd(r.variance)}</td><td className="text-right">{r.pct != null ? `${r.pct}%` : ""}</td></tr>)}</tbody></table></div>
    <div className="text-xs text-slate-500">Thực tế = sổ cái GL (511/711 doanh thu; 6xx chi phí theo cc trong bút toán). Chi vượt ngân sách → đỏ.</div></div>);
}
/** DÒNG TIỀN DỰ BÁO 13 tuần */
export function CashflowPanel() {
  const cf = useData("cashflow_forecast"); const rows = (cf.rows ?? []).map((r) => ({ t: fmt.d(r.week_start), "Thu dự kiến": Number(r.receivable_due) + Number(r.sales_expected), "Chi dự kiến": Number(r.po_due) + Number(r.expense_expected) + Number(r.payroll_wk) + Number(r.fixed_wk), "Số dư cuối tuần": Number(r.cash_end) }));
  const min = Math.min(...rows.map((r) => r["Số dư cuối tuần"]), 0);
  return (<div className="card"><b>Dòng tiền dự báo 13 tuần</b>{min < 0 && <span className="b-red ml-2">Có tuần âm — cần thu nợ / lùi chi / vay</span>}<div style={{ height: 240 }} className="mt-2"><ResponsiveContainer><LineChart data={rows}><XAxis dataKey="t" fontSize={11} /><YAxis fontSize={11} tickFormatter={(v: number) => fmt.n(v / 1e6) + "tr"} /><Tooltip formatter={(v: unknown) => fmt.vnd(Number(v))} /><Legend /><ReferenceLine y={0} stroke="#dc2626" /><Line type="monotone" dataKey="Thu dự kiến" stroke="#059669" dot={false} /><Line type="monotone" dataKey="Chi dự kiến" stroke="#dc2626" dot={false} /><Line type="monotone" dataKey="Số dư cuối tuần" stroke="#1d4ed8" strokeWidth={2} /></LineChart></ResponsiveContainer></div>
    <div className="overflow-auto"><table className="tbl text-xs"><thead><tr><th className="pl-2">Tuần</th><th className="text-right">Công nợ đến hạn</th><th className="text-right">Doanh thu TB</th><th className="text-right">PO phải trả</th><th className="text-right">Chi TB</th><th className="text-right">Lương</th><th className="text-right">Cố định</th><th className="text-right">Ròng</th><th className="text-right">Số dư</th></tr></thead><tbody>{(cf.rows ?? []).map((r, i) => <tr key={i} className={Number(r.cash_end) < 0 ? "bg-red-50" : ""}><td className="pl-2">{fmt.d(r.week_start)}</td><td className="text-right">{fmt.vnd(r.receivable_due)}</td><td className="text-right">{fmt.vnd(r.sales_expected)}</td><td className="text-right">{fmt.vnd(r.po_due)}</td><td className="text-right">{fmt.vnd(r.expense_expected)}</td><td className="text-right">{fmt.vnd(r.payroll_wk)}</td><td className="text-right">{fmt.vnd(r.fixed_wk)}</td><td className={`text-right font-semibold ${Number(r.net_wk) < 0 ? "text-red-700" : ""}`}>{fmt.vnd(r.net_wk)}</td><td className="text-right font-bold">{fmt.vnd(r.cash_end)}</td></tr>)}</tbody></table></div>
    <div className="text-xs text-slate-500">Số dư đầu = TK 111+112 trong GL. Báo cáo tuần/tháng tự gửi theo lịch ở Quản trị DL › report_schedules.</div></div>);
}
