"use client";
import { useState } from "react";
import { useData, act, fmt } from "@/lib/client";
import type { Sess } from "@/components/Shell";
type R = Record<string, unknown>;
const adminPost = (t: string, row: R) => fetch(`/api/admin/${t}`, { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ row }) }).then((r) => r.json());
/** Nút xử lý đơn: NHẬP → Giữ hàng FEFO (thiếu → Lệnh SX tự sinh) → CHỐT → Phiếu soạn → Xuất kho (GIAO) → Hoàn tất */
export function OrderActions({ o, onDone }: { o: R; onDone: () => void }) {
  const [msg, setMsg] = useState("");
  const st = String(o.status);
  return (<span className="whitespace-nowrap text-xs">
    {["NHAP", "CHOT"].includes(st) && <button className="btn-secondary !py-1 !px-2 !text-xs mr-1" title="Giữ hàng theo FEFO; thiếu thì tự sinh lệnh sản xuất" onClick={async () => { const j = await act("reserve_order", { id: o.id }); setMsg(j.ok ? (j.short?.length ? `Thiếu: ${j.short.map((x: R) => `${x.sku} ${x.short}`).join(", ")} → ${j.lsx} lệnh SX` : "Đã giữ đủ hàng") : String(j.error)); onDone(); }}>Giữ hàng</button>}
    {st === "NHAP" && <button className="btn-secondary !py-1 !px-2 !text-xs mr-1" onClick={async () => { await act("order_status", { id: o.id, status: "CHOT" }); onDone(); }}>Chốt</button>}
    {["CHOT", "LENH_SX", "DONG_GOI"].includes(st) && <a className="underline mr-1" href={`/in/phieu-soan/${o.id}`} target="_blank">Phiếu soạn</a>}
    {["CHOT", "LENH_SX", "DONG_GOI"].includes(st) && <button className="btn-primary !py-1 !px-2 !text-xs mr-1" title="Xuất kho theo phiếu soạn (từng lô) → GIAO" onClick={async () => { const j = await act("ship_order", { id: o.id }); setMsg(j.ok ? `Đã xuất ${j.n} lô → GIAO` : String(j.error)); onDone(); }}>Xuất kho</button>}
    {st === "GIAO" && <button className="btn-secondary !py-1 !px-2 !text-xs mr-1" onClick={async () => { await act("order_status", { id: o.id, status: "HOAN_TAT" }); onDone(); }}>Hoàn tất</button>}
    {!["HOAN_TAT", "HUY"].includes(st) && <button className="underline text-red-700" onClick={async () => { if (confirm("Hủy đơn?")) { await act("order_status", { id: o.id, status: "HUY" }); onDone(); } }}>hủy</button>}
    {msg && <div className="text-emerald-700">{msg}</div>}
  </span>);
}
/** TRẢ HÀNG / CREDIT NOTE */
export function ReturnsPanel({ sess }: { sess: Sess }) {
  const rets = useData("sales_returns"); const sales = useData("sales_recent"); const [f, setF] = useState<R | null>(null); const [msg, setMsg] = useState("");
  const canA = ["director", "owner", "accountant", "tech_head"].includes(sess.role);
  return (<div className="space-y-2">
    <div className="card"><div className="flex items-center"><b>Trả hàng · credit note</b><button className="ml-auto btn-secondary !py-1 !px-3 !text-sm" onClick={() => setF({ reason: "HU_HONG", disposition: "NHAP_LAI" })}>＋ Phiếu trả hàng</button></div>
      {f && <div className="grid sm:grid-cols-3 lg:grid-cols-6 gap-2 mt-2 text-sm"><select className="input lg:col-span-2" value={String(f.sale_id ?? "")} onChange={(e) => { const s = (sales.rows ?? []).find((x) => x.id === e.target.value); setF({ ...f, sale_id: e.target.value, sku: s?.sku, lot_id: s?.lot_id, partner_id: s?.partner_id, unit_price: s?.price, qty: s?.qty, amount: s?.amount }); }}><option value="">Chọn phiếu bán…</option>{(sales.rows ?? []).map((s) => <option key={String(s.id)} value={String(s.id)}>{fmt.dt(s.ts)} · {String(s.sku)} × {String(s.qty)} · {fmt.vnd(s.amount)} · {String(s.partner_name ?? s.partner_id ?? "")}</option>)}</select><input className="input" type="number" placeholder="SL trả" value={String(f.qty ?? "")} onChange={(e) => setF({ ...f, qty: Number(e.target.value), amount: Number(e.target.value) * Number(f.unit_price ?? 0) })} /><input className="input" type="number" placeholder="Tiền hoàn" value={String(f.amount ?? "")} onChange={(e) => setF({ ...f, amount: Number(e.target.value) })} /><select className="input" value={String(f.reason)} onChange={(e) => setF({ ...f, reason: e.target.value })}>{["HU_HONG", "SAI_HANG", "HET_HAN", "KHACH_DOI_Y", "KHAC"].map((r) => <option key={r}>{r}</option>)}</select><select className="input" value={String(f.disposition)} onChange={(e) => setF({ ...f, disposition: e.target.value })}><option value="NHAP_LAI">Nhập lại kho</option><option value="HUY">Hủy hàng</option><option value="CHE_BIEN_LAI">Chế biến lại</option></select><input className="input lg:col-span-4" placeholder="Ghi chú" value={String(f.note ?? "")} onChange={(e) => setF({ ...f, note: e.target.value })} /><div className="flex gap-2"><button className="btn-primary !py-2" onClick={async () => { const j = await adminPost("sales_returns", { ...f, created_by: sess.staffId }); setMsg(j.ok ? `Đã tạo phiếu ${String(j.row?.id)} — chờ duyệt ở Phê duyệt` : `${j.error}: ${j.detail ?? ""}`); setF(null); rets.reload(); }}>Lưu</button><button className="btn-secondary !py-2" onClick={() => setF(null)}>Hủy</button></div></div>}{msg && <div className="text-sm text-emerald-700 mt-1">{msg}</div>}</div>
    <div className="card p-0 overflow-auto"><table className="tbl text-sm"><thead><tr><th className="pl-3">Mã</th><th>Lúc</th><th>Hàng</th><th className="text-right">SL</th><th className="text-right">Tiền</th><th>Lý do</th><th>Xử lý</th><th>Credit note</th><th>TT</th><th></th></tr></thead><tbody>{(rets.rows ?? []).map((r) => <tr key={String(r.id)}><td className="pl-3 font-mono text-xs">{String(r.id)}</td><td className="text-xs">{fmt.dt(r.ts)}</td><td>{String(r.sku ?? "")}</td><td className="text-right">{String(r.qty ?? "")}</td><td className="text-right">{fmt.vnd(r.amount)}</td><td className="text-xs">{String(r.reason)}</td><td className="text-xs">{String(r.disposition)}{r.restocked ? " ✓kho" : ""}</td><td className="font-mono text-xs">{String(r.credit_note_no ?? "")}</td><td><span className={r.status === "DUYET" ? "b-grn" : r.status === "TU_CHOI" ? "b-red" : "b-yel"}>{String(r.status)}</span></td><td className="text-xs">{canA && r.status === "MOI" && <><button className="underline mr-1" onClick={async () => { const j = await act("approve_return", { id: r.id }); setMsg(j.ok ? "Đã duyệt: nhập kho + đảo doanh thu + credit note" : String(j.error)); rets.reload(); }}>duyệt</button><button className="underline text-red-700" onClick={async () => { await adminPost("sales_returns", { id: r.id, status: "TU_CHOI", approved_by: sess.staffId }); rets.reload(); }}>từ chối</button></>}</td></tr>)}</tbody></table></div>
  </div>);
}
/** LỆNH SẢN XUẤT (tự sinh khi đơn thiếu tồn hoặc tạo tay) + GIÁ THÀNH TỪNG MẺ */
export function ProductionPanel({ sess }: { sess: Sess }) {
  const po = useData("production_orders"); const cost = useData("batch_cost"); const [msg, setMsg] = useState("");
  const canW = ["team_lead", "tech_head", "director", "owner"].includes(sess.role);
  return (<div className="space-y-3">
    <div className="card p-0 overflow-auto"><div className="px-3 py-2 bg-slate-100 rounded-t-xl font-bold">Lệnh sản xuất ({(po.rows ?? []).length}) — tự sinh khi đơn thiếu tồn (Giữ hàng), hoặc tạo tay ở Quản trị DL › production_orders</div><table className="tbl text-sm"><thead><tr><th className="pl-3">Mã</th><th>Đơn</th><th>SKU</th><th className="text-right">SL</th><th>Hạn</th><th>Công thức</th><th>TT</th><th></th></tr></thead><tbody>{(po.rows ?? []).map((p) => <tr key={String(p.id)}><td className="pl-3 font-mono text-xs">{String(p.id)}</td><td className="font-mono text-xs">{String(p.order_id ?? "")}</td><td>{String(p.sku)}</td><td className="text-right font-bold">{fmt.n(p.qty)}</td><td>{fmt.d(p.due_date)}</td><td className="text-xs">{String(p.recipe_id ?? "—")}</td><td><span className={p.status === "XONG" ? "b-grn" : p.status === "DANG_LAM" ? "b-yel" : "b-gray"}>{String(p.status)}</span></td><td className="text-xs">{canW && p.status === "MOI" && <button className="underline mr-1" onClick={async () => { await adminPost("production_orders", { id: p.id, status: "DANG_LAM" }); po.reload(); }}>bắt đầu</button>}{canW && p.status === "DANG_LAM" && <button className="underline" onClick={async () => { await adminPost("production_orders", { id: p.id, status: "XONG" }); setMsg("Xong lệnh — ghi mẻ ở form A1/A7 (batch_logs) và nhập kho K4/K5 để giữ hàng lại cho đơn"); po.reload(); }}>xong</button>}</td></tr>)}</tbody></table>{msg && <div className="p-2 text-sm text-emerald-700">{msg}</div>}</div>
    <div className="card p-0 overflow-auto"><div className="px-3 py-2 bg-slate-100 rounded-t-xl font-bold">Giá thành từng mẻ (Σ nguyên liệu × giá bình quân lô + chi phí cố định CC-D5/CB phân bổ theo kg ra)</div><table className="tbl text-sm"><thead><tr><th className="pl-3">Mẻ</th><th>Lúc</th><th>Dây chuyền</th><th className="text-right">Vào (kg)</th><th className="text-right">Ra (kg)</th><th className="text-right">NVL (đ)</th><th className="text-right">Phân bổ (đ)</th><th className="text-right">đ/kg</th><th className="text-right">Hao hụt</th></tr></thead><tbody>{(cost.rows ?? []).map((c) => <tr key={String(c.batch_code)}><td className="pl-3 font-mono text-xs">{String(c.batch_code)}</td><td className="text-xs">{fmt.dt(c.ts)}</td><td>{String(c.line ?? "")}</td><td className="text-right">{fmt.n(c.in_kg)}</td><td className="text-right">{fmt.n(c.out_kg)}</td><td className="text-right">{fmt.vnd(c.mat_cost)}</td><td className="text-right">{fmt.vnd(c.overhead_alloc)}</td><td className="text-right font-bold">{c.cost_per_kg ? fmt.vnd(c.cost_per_kg) : "—"}</td><td className={`text-right ${Number(c.loss_pct) > 10 ? "text-red-700" : ""}`}>{c.loss_pct != null ? `${c.loss_pct}%` : ""}</td></tr>)}</tbody></table><div className="p-2 text-xs text-slate-500">Mẻ chưa ghi outputs (kg ra) → chưa có đ/kg; ghi ở form A1/A7. Chi phí cố định nhập ở Kế toán › chi phí cố định theo CC.</div></div>
  </div>);
}
