"use client";
import { useState } from "react";
import { useData, act, fmt } from "@/lib/client";
import type { Sess } from "@/components/Shell";
import Tabs from "@/components/Tabs";
import { LineChart, Line, XAxis, YAxis, Tooltip, Legend, CartesianGrid, ResponsiveContainer } from "recharts";
type R = Record<string, unknown>;
const COL = ["#059669", "#0ea5e9", "#f59e0b", "#8b5cf6", "#ef4444", "#14b8a6", "#64748b", "#84cc16"];
/** GIÁM SÁT: bộ tiêu chí theo vị trí (auto từ dữ liệu vận hành + quan sát tại chỗ) → điểm tuần 0–100/người & bộ phận → lỗi trừ điểm thưởng; giám sát viên đủ lượt = đủ điều kiện thưởng */
export default function GiamSat({ sess }: { sess: Sess }) {
  const [tab, setTab] = useState<"tuan" | "cham" | "tieuchi" | "loi" | "xuhuong">("tuan");
  const asg = useData("my_supervision"); const targets = useData("supervision_targets"); const crit = useData("supervision_criteria"); const wk = useData("supervision_week", { week: "" }); const weekly = useData("supervision_weekly"); const dept = useData("supervision_dept_weekly"); const checks = useData("supervision_checks_recent");
  const [sel, setSel] = useState<string>(""); const [msg, setMsg] = useState(""); const [busy, setBusy] = useState(false);
  const T = targets.rows ?? []; const tsel = T.find((t) => t.id === sel); const C = crit.rows ?? [];
  const critFor = (t: R | undefined) => C.filter((c) => (!c.position_code || c.position_code === t?.position_code) && (!c.dept_code || c.dept_code === t?.dept));
  const scoreOf = (sid: string, cid: string) => (wk.rows ?? []).find((r) => r.staff_id === sid && r.criteria_id === cid);
  const mark = async (t: R, c: R, result: string) => { let severity: string | null = null; let note: string | null = null; if (result === "LOI") { severity = prompt("Mức độ: NHE / TRUNG / NANG / NGHIEM_TRONG", "TRUNG"); if (!severity) return; note = prompt("Mô tả lỗi + yêu cầu khắc phục") ?? ""; } setBusy(true); const j = await act("sup_check", { target_staff_id: t.id, target_dept: t.dept, criteria_id: c.id, sop_code: c.sop_code, item: c.name, result, severity, note }); setBusy(false); setMsg(j.ok ? `Đã ghi ${result}${j.points ? ` (−${j.points} điểm)` : ""}` : String(j.error)); wk.reload(); checks.reload(); weekly.reload(); };
  const trend = (() => { const weeks = [...new Set((dept.rows ?? []).map((r) => String(r.week_start)))].sort(); const depts = [...new Set((dept.rows ?? []).map((r) => String(r.dept)))]; return { depts, data: weeks.map((w) => { const o: R = { week: fmt.d(w).slice(0, 5) }; for (const d of depts) o[d] = Number((dept.rows ?? []).find((r) => r.week_start === w && r.dept === d)?.score ?? null); return o; }) }; })();
  return <div className="space-y-3">
    <Tabs items={[["tuan", `Bảng điểm tuần này (${(wk.rows ?? []).length} dòng)`], ["cham", `Chấm quan sát tại chỗ (${T.length} người)`], ["loi", `Lỗi & khắc phục (${(checks.rows ?? []).filter((c) => c.result === "LOI").length})`], ["xuhuong", "📈 Xu hướng theo bộ phận"], ["tieuchi", `Tiêu chí (${C.length})`]]} value={tab} onChange={(k) => setTab(k as typeof tab)} right={<button className="btn-secondary !py-1.5 !px-3 text-sm" disabled={busy} onClick={async () => { const j = await act("run_supervision", {}); setMsg(j.ok ? `Đã chấm tự động ${j.n} tiêu chí` : String(j.error)); wk.reload(); weekly.reload(); }}>⟳ Chấm tự động ngay</button>} />
    {msg && <div className="rounded-xl bg-emerald-50 border border-emerald-300 px-3 py-2 text-sm">{msg}</div>}
    <div className="text-xs text-slate-600">Phân công của tôi: {(asg.rows ?? []).map((a) => <span key={String(a.id)} className="rounded-full border px-2 py-0.5 mr-1">{String(a.target_label ?? "toàn trại")} · {String(a.checks_per_week ?? 5)} lượt/tuần</span>)}{!(asg.rows ?? []).length && "— chưa được phân công giám sát (GĐ/QA phân ở /quan-tri?t=supervision_assignments)"}</div>
    {tab === "tuan" && <div className="card p-0 overflow-auto"><div className="px-3 py-2 bg-slate-100 rounded-t-xl font-bold">Điểm tuần {fmt.d(String((wk.rows ?? [])[0]?.week_start ?? new Date().toISOString()))} — tự động (từ ghi chép/việc/checklist) + quan sát; A ≥90 · B ≥75 · C ≥60 · D &lt;60</div>
      <table className="tbl text-sm"><thead><tr><th className="pl-3">Nhân sự</th><th>BP · vị trí</th><th className="text-right">Điểm</th><th>Xếp</th><th className="text-right">Tiêu chí</th><th>Chưa đạt (giá trị/mục tiêu)</th></tr></thead><tbody>{(weekly.rows ?? []).filter((r) => r.week_start === (wk.rows ?? [])[0]?.week_start || !(wk.rows ?? []).length).slice(0, 80).map((r) => <tr key={String(r.staff_id) + String(r.week_start)} className={r.grade === "D" ? "bg-red-50" : r.grade === "C" ? "bg-amber-50" : ""}><td className="pl-3">{String(r.full_name)}</td><td className="text-xs">{String(r.dept)} · {String(r.position_code ?? r.role)}</td><td className="text-right font-bold">{String(r.score)}</td><td><span className={`rounded-full px-2 text-xs font-bold ${r.grade === "A" ? "bg-emerald-100 text-emerald-800" : r.grade === "B" ? "bg-sky-100" : r.grade === "C" ? "bg-amber-100" : "bg-red-100 text-red-800"}`}>{String(r.grade)}</span></td><td className="text-right">{String(r.n_criteria)}{Number(r.n_manual) ? ` (${r.n_manual} QS)` : ""}</td><td className="text-xs max-w-[520px]">{String(r.shortfalls ?? "")}</td></tr>)}</tbody></table>{!(weekly.rows ?? []).length && <div className="p-3 text-sm text-slate-500">Chưa có điểm — bấm "Chấm tự động ngay".</div>}</div>}
    {tab === "cham" && <div className="grid lg:grid-cols-3 gap-3"><div className="card p-0 overflow-auto"><div className="px-3 py-2 bg-slate-100 rounded-t-xl font-bold">Người trong phạm vi giám sát</div>{T.map((t) => <button key={String(t.id)} className={`w-full text-left px-3 py-2 border-b text-sm ${sel === t.id ? "bg-emerald-50" : ""}`} onClick={() => setSel(String(t.id))}>{String(t.full_name)} <span className="text-xs text-slate-500">{String(t.dept)} · {String(t.position_code ?? t.role)}</span></button>)}{!T.length && <div className="p-3 text-sm text-slate-500">Không có người nào trong phạm vi.</div>}</div>
      <div className="card lg:col-span-2">{!tsel ? <div className="text-sm text-slate-500">Chọn người bên trái → checklist tiêu chí của vị trí đó: hệ thống đã chấm phần AUTO; anh/chị quan sát và chấm phần QUAN SÁT (đạt/lỗi), xác nhận điểm auto thấp.</div> : <div><b>{String(tsel.full_name)}</b> <span className="text-xs text-slate-500">{String(tsel.dept)} · {String(tsel.position_code ?? tsel.role)}</span>
        <table className="tbl text-sm mt-2"><thead><tr><th>Tiêu chí</th><th>Cách đo</th><th className="text-right">Trọng số</th><th className="text-right">Giá trị / mục tiêu</th><th className="text-right">Đạt</th><th>Chấm</th></tr></thead><tbody>{critFor(tsel).map((c) => { const sc = scoreOf(String(tsel.id), String(c.id)); return <tr key={String(c.id)} className={sc && Number(sc.achieved) < 0.8 ? "bg-amber-50" : ""}><td><b>{String(c.name)}</b><div className="text-xs text-slate-500">{String(c.what ?? "")}{c.sop_code ? ` · ${c.sop_code}` : ""}</div></td><td className="text-xs">{c.method === "AUTO" ? "tự động" : "quan sát"}</td><td className="text-right">{String(c.weight)}</td><td className="text-right">{sc ? `${sc.value ?? "—"} / ${sc.target ?? c.target ?? ""} ${c.unit ?? ""}` : "—"}</td><td className="text-right">{sc ? `${Math.round(Number(sc.achieved) * 100)}%` : ""}</td><td className="text-xs whitespace-nowrap"><button className="underline mr-2 text-emerald-700" disabled={busy} onClick={() => mark(tsel, c, "DAT")}>✓ đạt</button><button className="underline mr-2 text-red-700" disabled={busy} onClick={() => mark(tsel, c, "LOI")}>✗ lỗi</button><button className="underline text-slate-500" disabled={busy} onClick={() => mark(tsel, c, "TU_BAO_LOI")}>tự báo</button></td></tr>; })}</tbody></table>
        <div className="text-xs text-slate-500 mt-1">Lỗi → trừ điểm thưởng bộ phận theo mức độ (NHẸ 1 · TRUNG 3 · NẶNG 6 · NGHIÊM TRỌNG 12 điểm × {fmt.vnd(50000)}); "tự báo lỗi" không trừ. Lỗi phát sinh sự kiện supervision.fault → bộ phận nhận thông báo khắc phục.</div></div>}</div></div>}
    {tab === "loi" && <div className="card p-0 overflow-auto"><table className="tbl text-sm"><thead><tr><th className="pl-3">Lúc</th><th>Giám sát</th><th>Đối tượng</th><th>Tiêu chí</th><th>KQ</th><th>Mức</th><th className="text-right">Điểm</th><th>Ghi chú / khắc phục</th></tr></thead><tbody>{(checks.rows ?? []).map((c) => <tr key={String(c.id)} className={c.result === "LOI" ? "bg-red-50" : ""}><td className="pl-3 text-xs">{fmt.dt(String(c.ts))}</td><td className="text-xs">{String(c.supervisor_name ?? c.supervisor_id)}</td><td>{String(c.target_name ?? c.target_dept ?? "")}</td><td>{String(c.item)}</td><td>{String(c.result)}</td><td>{String(c.severity ?? "")}</td><td className="text-right">{String(c.points ?? 0)}</td><td className="text-xs">{String(c.note ?? "")} {c.corrective ? `→ ${c.corrective}` : ""}</td></tr>)}</tbody></table></div>}
    {tab === "xuhuong" && <div className="card"><div className="text-sm font-bold">Điểm giám sát TB theo bộ phận (12 tuần)</div><div style={{ height: 300 }}><ResponsiveContainer><LineChart data={trend.data}><CartesianGrid strokeDasharray="3 3" /><XAxis dataKey="week" tick={{ fontSize: 10 }} /><YAxis domain={[0, 100]} tick={{ fontSize: 10 }} /><Tooltip /><Legend wrapperStyle={{ fontSize: 11 }} />{trend.depts.map((d, i) => <Line key={d} type="monotone" dataKey={d} stroke={COL[i % COL.length]} dot={false} strokeWidth={2} connectNulls />)}</LineChart></ResponsiveContainer></div></div>}
    {tab === "tieuchi" && <div className="card p-0 overflow-auto"><div className="px-3 py-2 bg-slate-100 rounded-t-xl font-bold flex items-center gap-2">Tiêu chí giám sát & thang điểm (dữ liệu — sửa/thêm không cần lập trình) <a className="ml-auto underline text-sm font-normal" href="/quan-tri?t=supervision_criteria">✎ sửa</a></div><table className="tbl text-sm"><thead><tr><th className="pl-3">Vị trí</th><th>Tiêu chí</th><th>Giám sát cái gì</th><th>Cách đo</th><th className="text-right">Mục tiêu</th><th className="text-right">Trọng số</th><th>Mức lỗi</th><th>SOP</th></tr></thead><tbody>{C.map((c) => <tr key={String(c.id)}><td className="pl-3 font-mono text-xs">{String(c.position_code ?? c.dept_code ?? "Mọi vị trí")}</td><td><b>{String(c.name)}</b></td><td className="text-xs">{String(c.what ?? "")}</td><td className="text-xs">{c.method === "AUTO" ? "Tự động (SQL trên dữ liệu vận hành)" : "Quan sát tại chỗ"}</td><td className="text-right">{String(c.direction)} {String(c.target ?? "")} {String(c.unit ?? "")}</td><td className="text-right">{String(c.weight)}</td><td>{String(c.severity ?? "")}</td><td className="font-mono text-xs">{String(c.sop_code ?? "")}</td></tr>)}</tbody></table></div>}
  </div>;
}
