"use client";
import { useState } from "react";
import { useData, act, fmt } from "@/lib/client";
import type { Sess } from "@/components/Shell";
import Tabs from "@/components/Tabs";
import { LineChart, Line, XAxis, YAxis, Tooltip, Legend, CartesianGrid, ResponsiveContainer } from "recharts";
import { usePrompt } from "@/components/ui/PromptDialog";
import { useUrlTab } from "@/lib/useUrlTab";
import { RecordingCompliancePanel } from "@/components/panels/MeterReading";
type R = Record<string, unknown>;
const COL = ["#059669", "#0ea5e9", "#f59e0b", "#8b5cf6", "#ef4444", "#14b8a6", "#64748b", "#84cc16"];
/** GIÁM SÁT: bộ tiêu chí theo vị trí (auto từ dữ liệu vận hành + quan sát tại chỗ) → điểm tuần 0–100/người & bộ phận → lỗi trừ điểm thưởng; giám sát viên đủ lượt = đủ điều kiện thưởng */
export default function GiamSat({ sess }: { sess: Sess }) {
  const [tab, setTab] = useUrlTab(["ngay", "tuan", "cham", "tieuchi", "loi", "xuhuong", "nhip", "chong", "capnhat"] as const, "ngay");
  const asg = useData("my_supervision"); const targets = useData("supervision_targets"); const crit = useData("supervision_criteria"); const wk = useData("supervision_week", { week: "" }); const weekly = useData("supervision_weekly"); const dept = useData("supervision_dept_weekly"); const checks = useData("supervision_checks_recent");
  const [sel, setSel] = useState<string>(""); const [msg, setMsg] = useState(""); const [busy, setBusy] = useState(false); const { prompt, promptElement } = usePrompt();
  const T = targets.rows ?? []; const tsel = T.find((t) => t.id === sel); const C = crit.rows ?? [];
  const isHeadT = (t: R | undefined) => t?.role === "tech_head" || t?.role === "team_lead";
  const critFor = (t: R | undefined) => C.filter((c) => (c.role_scope === "TRUONG_PHONG" ? isHeadT(t) : !c.role_scope) && (!c.position_code || c.position_code === t?.position_code) && (!c.dept_code || c.dept_code === t?.dept) && !c.process_code);
  const scoreOf = (sid: string, cid: string) => (wk.rows ?? []).find((r) => r.staff_id === sid && r.criteria_id === cid);
  const mark = async (t: R, c: R, result: string) => { let severity: string | null = null; let note: string | null = null; if (result === "LOI") { severity = await prompt({ title: "Ghi lỗi", label: "Mức độ: NHE / TRUNG / NANG / NGHIEM_TRONG", type: "text", defaultValue: "TRUNG" }); if (!severity) return; note = (await prompt({ title: "Mô tả lỗi", label: "Mô tả lỗi + yêu cầu khắc phục", type: "text", required: false })) ?? ""; } setBusy(true); const j = await act("sup_check", { target_staff_id: t.id, target_dept: t.dept, criteria_id: c.id, sop_code: c.sop_code, item: c.name, result, severity, note }); setBusy(false); setMsg(j.ok ? `Đã ghi ${result}${j.points ? ` (−${j.points} điểm)` : ""}` : String(j.error)); wk.reload(); checks.reload(); weekly.reload(); };
  const trend = (() => { const weeks = [...new Set((dept.rows ?? []).map((r) => String(r.week_start)))].sort(); const depts = [...new Set((dept.rows ?? []).map((r) => String(r.dept)))]; return { depts, data: weeks.map((w) => { const o: R = { week: fmt.d(w).slice(0, 5) }; for (const d of depts) o[d] = Number((dept.rows ?? []).find((r) => r.week_start === w && r.dept === d)?.score ?? null); return o; }) }; })();
  return <div className="space-y-3">
    {promptElement}
    <Tabs items={[["ngay", "📅 Hôm nay của GS (kiểm hằng ngày theo quy trình)"], ["tuan", `Bảng điểm tuần này (${(wk.rows ?? []).length} dòng)`], ["cham", `Chấm quan sát tại chỗ (${T.length} người)`], ["loi", `Lỗi & khắc phục (${(checks.rows ?? []).filter((c) => c.result === "LOI").length})`], ["nhip", "🔁 Nhịp tuần & CAPA · đi ca · chấm ngược"], ["chong", "🛡 Chống thông đồng · kiểm chéo mù · phản ánh"], ["capnhat", "🚨 Khâu quên cập nhật"], ["xuhuong", "📈 Xu hướng theo bộ phận"], ["tieuchi", `Tiêu chí (${C.length})`]]} value={tab} onChange={(k) => setTab(k as typeof tab)} right={<button className="btn-secondary !py-1.5 !px-3 text-sm" disabled={busy} onClick={async () => { const j = await act("run_supervision", {}); setMsg(j.ok ? `Đã chấm tự động ${j.n} tiêu chí` : String(j.error)); wk.reload(); weekly.reload(); }}>⟳ Chấm tự động ngay</button>} />
    {msg && <div className="rounded-xl bg-emerald-50 border border-emerald-300 px-3 py-2 text-sm">{msg}</div>}
    <div className="text-xs text-slate-600">Phân công của tôi: {(asg.rows ?? []).map((a) => <span key={String(a.id)} className="rounded-full border px-2 py-0.5 mr-1">{String(a.target_label ?? "toàn trại")} · {String(a.checks_per_week ?? 5)} lượt/tuần</span>)}{asg.rows?.length === 0 && "— chưa được phân công giám sát (GĐ/QA phân ở /quan-tri?t=supervision_assignments)"}</div>
    {tab === "capnhat" && <RecordingCompliancePanel sess={sess} />}
    {tab === "tuan" && <div className="card p-0 overflow-auto"><div className="px-3 py-2 bg-slate-100 rounded-t-xl font-bold">Điểm tuần {fmt.d(String((wk.rows ?? [])[0]?.week_start ?? new Date().toISOString()))} — tự động (từ ghi chép/việc/checklist) + quan sát; A ≥90 · B ≥75 · C ≥60 · D &lt;60</div>
      <table className="tbl text-sm"><thead><tr><th className="pl-3">Nhân sự</th><th>BP · vị trí</th><th className="text-right">Điểm</th><th>Xếp</th><th className="text-right">Tiêu chí</th><th>Chưa đạt (giá trị/mục tiêu)</th></tr></thead><tbody>{(weekly.rows ?? []).filter((r) => r.week_start === (wk.rows ?? [])[0]?.week_start || !(wk.rows ?? []).length).slice(0, 80).map((r) => <tr key={String(r.staff_id) + String(r.week_start)} className={r.grade === "D" ? "bg-red-50" : r.grade === "C" ? "bg-amber-50" : ""}><td className="pl-3">{String(r.full_name)}</td><td className="text-xs">{String(r.dept)} · {String(r.position_code ?? r.role)}</td><td className="text-right font-bold">{String(r.score)}</td><td><span className={`rounded-full px-2 text-xs font-bold ${r.grade === "A" ? "bg-emerald-100 text-emerald-800" : r.grade === "B" ? "bg-sky-100" : r.grade === "C" ? "bg-amber-100" : "bg-red-100 text-red-800"}`}>{String(r.grade)}</span></td><td className="text-right">{String(r.n_criteria)}{Number(r.n_manual) ? ` (${r.n_manual} QS)` : ""}</td><td className="text-xs max-w-[520px]">{String(r.shortfalls ?? "")}</td></tr>)}</tbody></table>{weekly.rows?.length === 0 && <div className="p-3 text-sm text-slate-500">Chưa có điểm — bấm "Chấm tự động ngay".</div>}</div>}
    {tab === "cham" && <div className="grid lg:grid-cols-3 gap-3"><div className="card p-0 overflow-auto"><div className="px-3 py-2 bg-slate-100 rounded-t-xl font-bold">Người trong phạm vi giám sát</div>{T.map((t) => <button key={String(t.id)} className={`w-full text-left px-3 py-2 border-b text-sm ${sel === t.id ? "bg-emerald-50" : ""}`} onClick={() => setSel(String(t.id))}>{String(t.full_name)} <span className="text-xs text-slate-500">{String(t.dept)} · {String(t.position_code ?? t.role)}</span></button>)}{!T.length && <div className="p-3 text-sm text-slate-500">Không có người nào trong phạm vi.</div>}</div>
      <div className="card lg:col-span-2">{!tsel ? <div className="text-sm text-slate-500">Chọn người bên trái → checklist tiêu chí của vị trí đó: hệ thống đã chấm phần AUTO; anh/chị quan sát và chấm phần QUAN SÁT (đạt/lỗi), xác nhận điểm auto thấp.</div> : <div><b>{String(tsel.full_name)}</b> <span className="text-xs text-slate-500">{String(tsel.dept)} · {String(tsel.position_code ?? tsel.role)}</span>
        <table className="tbl text-sm mt-2"><thead><tr><th>Tiêu chí</th><th>Cách đo</th><th className="text-right">Trọng số</th><th className="text-right">Giá trị / mục tiêu</th><th className="text-right">Đạt</th><th>Chấm</th></tr></thead><tbody>{critFor(tsel).map((c) => { const sc = scoreOf(String(tsel.id), String(c.id)); return <tr key={String(c.id)} className={sc && Number(sc.achieved) < 0.8 ? "bg-amber-50" : ""}><td><b>{String(c.name)}</b><div className="text-xs text-slate-500">{String(c.what ?? "")}{c.sop_code ? ` · ${c.sop_code}` : ""}</div></td><td className="text-xs">{c.method === "AUTO" ? "tự động" : "quan sát"}</td><td className="text-right">{String(c.weight)}</td><td className="text-right">{sc ? `${sc.value ?? "—"} / ${sc.target ?? c.target ?? ""} ${c.unit ?? ""}` : "—"}</td><td className="text-right">{sc ? `${Math.round(Number(sc.achieved) * 100)}%` : ""}</td><td className="text-xs whitespace-nowrap"><button className="underline mr-2 text-emerald-700" disabled={busy} onClick={() => mark(tsel, c, "DAT")}>✓ đạt</button><button className="underline mr-2 text-red-700" disabled={busy} onClick={() => mark(tsel, c, "LOI")}>✗ lỗi</button><button className="underline text-slate-500" disabled={busy} onClick={() => mark(tsel, c, "TU_BAO_LOI")}>tự báo</button></td></tr>; })}</tbody></table>
        <div className="text-xs text-slate-500 mt-1">Lỗi → trừ điểm thưởng bộ phận theo mức độ (NHẸ 1 · TRUNG 3 · NẶNG 6 · NGHIÊM TRỌNG 12 điểm × {fmt.vnd(50000)}); "tự báo lỗi" không trừ. Lỗi phát sinh sự kiện supervision.fault → bộ phận nhận thông báo khắc phục.</div></div>}</div></div>}
    {tab === "loi" && <div className="card p-0 overflow-auto"><table className="tbl text-sm"><thead><tr><th className="pl-3">Lúc</th><th>Giám sát</th><th>Đối tượng</th><th>Tiêu chí</th><th>KQ</th><th>Mức</th><th className="text-right">Điểm</th><th>Ghi chú / khắc phục</th></tr></thead><tbody>{(checks.rows ?? []).map((c) => <tr key={String(c.id)} className={c.result === "LOI" ? "bg-red-50" : ""}><td className="pl-3 text-xs">{fmt.dt(String(c.ts))}</td><td className="text-xs">{String(c.supervisor_name ?? c.supervisor_id)}</td><td>{String(c.target_name ?? c.target_dept ?? "")}</td><td>{String(c.item)}</td><td>{String(c.result)}</td><td>{String(c.severity ?? "")}</td><td className="text-right">{String(c.points ?? 0)}</td><td className="text-xs">{String(c.note ?? "")} {c.corrective ? `→ ${c.corrective}` : ""}</td></tr>)}</tbody></table></div>}
    {tab === "ngay" && <GsToday sess={sess} crit={C} />}
    {tab === "nhip" && <NhipTuan sess={sess} />}
    {tab === "chong" && <ChongThongDong sess={sess} />}
    {tab === "xuhuong" && <div className="card"><div className="text-sm font-bold">Điểm giám sát TB theo bộ phận (12 tuần)</div><div style={{ height: 300 }}><ResponsiveContainer><LineChart data={trend.data}><CartesianGrid strokeDasharray="3 3" /><XAxis dataKey="week" tick={{ fontSize: 10 }} /><YAxis domain={[0, 100]} tick={{ fontSize: 10 }} /><Tooltip /><Legend wrapperStyle={{ fontSize: 11 }} />{trend.depts.map((d, i) => <Line key={d} type="monotone" dataKey={d} stroke={COL[i % COL.length]} dot={false} strokeWidth={2} connectNulls />)}</LineChart></ResponsiveContainer></div></div>}
    {tab === "tieuchi" && <div className="card p-0 overflow-auto"><div className="px-3 py-2 bg-slate-100 rounded-t-xl font-bold flex items-center gap-2">Tiêu chí giám sát & thang điểm (dữ liệu — sửa/thêm không cần lập trình) <a className="ml-auto underline text-sm font-normal" href="/quan-tri?t=supervision_criteria">✎ sửa</a></div><table className="tbl text-sm"><thead><tr><th className="pl-3">Vị trí</th><th>Tiêu chí</th><th>Giám sát cái gì</th><th>Cách đo</th><th className="text-right">Mục tiêu</th><th className="text-right">Trọng số</th><th>Mức lỗi</th><th>SOP</th></tr></thead><tbody>{C.map((c) => <tr key={String(c.id)}><td className="pl-3 font-mono text-xs">{String(c.position_code ?? c.dept_code ?? "Mọi vị trí")}</td><td><b>{String(c.name)}</b></td><td className="text-xs">{String(c.what ?? "")}</td><td className="text-xs">{c.method === "AUTO" ? "Tự động (SQL trên dữ liệu vận hành)" : "Quan sát tại chỗ"}</td><td className="text-right">{String(c.direction)} {String(c.target ?? "")} {String(c.unit ?? "")}</td><td className="text-right">{String(c.weight)}</td><td>{String(c.severity ?? "")}</td><td className="font-mono text-xs">{String(c.sop_code ?? "")}</td></tr>)}</tbody></table></div>}
  </div>;
}

/** NHỊP TUẦN GS ↔ TRƯỞNG PHÒNG: T6 lỗi → việc CAPA · T2 biện pháp · GS chấm lại · lỗi lặp 3 tuần · GS đi ca thật · trưởng phòng chấm ngược GS */
function NhipTuan({ sess }: { sess: Sess }) {
  const faults = useData<R>("faults_week"); const capa = useData<R>("capa_status"); const rep = useData<R>("repeat_faults"); const fd = useData<R>("my_field_days"); const gsl = useData<R>("gs_list");
  const [msg, setMsg] = useState(""); const isHead = ["tech_head", "team_lead", "director", "owner"].includes(sess.role);
  const isGS = (gsl.rows ?? []).some((g) => g.id === sess.staffId) || sess.role === "auditor";
  const [rate, setRate] = useState<{ supervisor_id: string; useful: number; fair: number; knows: number; note: string }>({ supervisor_id: "", useful: 4, fair: 4, knows: 4, note: "" });
  const { prompt, promptElement } = usePrompt();
  return <div className="space-y-3">{promptElement}
    <div className="card text-sm"><b>Nhịp tuần cố định</b>: T2–T5 GS kiểm (+1 ngày đi ca thật) → <b>T6</b> lỗi chưa có biện pháp tự đổ vào việc <b>CAPA</b> của trưởng phòng (hạn T2 12h) → trưởng phòng ghi biện pháp + người + hạn (nội dung dạy tuần tới lấy từ đây) → GS chấm lại lỗi cũ trước khi mở lỗi mới. Lỗi lặp 3 tuần → trừ điểm trưởng phòng. GS không giao việc/ra lệnh công nhân; bất đồng → GĐ quyết trong 48h.
      {(isGS || sess.role === "director") && <button className="btn-secondary !py-1 !text-xs ml-2" onClick={async () => { const j = await act("gen_capa", {}); setMsg(j.error ? String(j.error) : `Đã tạo ${j.n} việc CAPA`); }}>▶ Tạo việc CAPA tuần này</button>}{msg && <span className="ml-2 text-emerald-800">{msg}</span>}</div>
    <div className="card p-0 overflow-auto"><div className="px-3 py-2 bg-slate-100 rounded-t-xl font-bold">Lỗi 2 tuần gần đây ({(faults.rows ?? []).length}) — trưởng phòng ghi biện pháp, GS xác nhận</div><table className="tbl text-sm"><thead><tr><th className="pl-3">Lúc</th><th>Phòng/Người</th><th>Tiêu chí</th><th>Mức</th><th>Biện pháp · hạn</th><th>Xác nhận</th></tr></thead><tbody>
      {(faults.rows ?? []).map((c) => <tr key={String(c.id)} className={c.verified_at ? "" : c.corrective ? "bg-amber-50" : "bg-red-50"}><td className="pl-3 text-xs">{fmt.dt(String(c.ts))}</td><td>{String(c.target_dept ?? "")} {String(c.target_name ?? "")}</td><td className="text-xs">{String(c.criteria_name ?? c.item)}<div className="text-slate-500">{String(c.note ?? "")}</div></td><td>{String(c.severity ?? "")}</td>
        <td className="text-xs">{c.corrective ? <>{String(c.corrective)} <span className="text-slate-500">hạn {c.corrective_due ? fmt.d(c.corrective_due) : "—"}</span></> : isHead ? <button className="btn-secondary !py-0.5 !px-2 !text-xs" onClick={async () => { const m = await prompt({ title: "Biện pháp khắc phục", label: "Biện pháp khắc phục + người làm", type: "text" }); if (!m) return; const d = await prompt({ title: "Hạn khắc phục", label: "Hạn (YYYY-MM-DD)", type: "text", defaultValue: new Date(Date.now() + 7 * 864e5).toISOString().slice(0, 10) }); await act("capa_set", { id: c.id, corrective: m, due: d }); faults.reload(); }}>＋ biện pháp</button> : <i className="text-red-700">chưa có</i>}</td>
        <td className="text-xs">{c.verified_at ? <span className="b-grn">✓ {fmt.d(c.verified_at)}</span> : c.corrective && isGS ? <button className="btn-primary !py-0.5 !px-2 !text-xs" onClick={async () => { await act("capa_verify", { id: c.id }); faults.reload(); }}>Đã khắc phục</button> : ""}</td></tr>)}</tbody></table></div>
    <div className="grid md:grid-cols-2 gap-3">
      <div className="card p-0 overflow-auto"><div className="px-3 py-2 bg-slate-100 rounded-t-xl font-bold">CAPA theo phòng · 8 tuần</div><table className="tbl text-sm"><thead><tr><th className="pl-3">Tuần</th><th>Phòng</th><th className="text-right">Lỗi</th><th className="text-right">Có biện pháp</th><th className="text-right">Đã xác nhận</th><th className="text-right">Quá hạn</th></tr></thead><tbody>{(capa.rows ?? []).map((r, i) => <tr key={i} className={Number(r.qua_han) > 0 ? "bg-red-50" : ""}><td className="pl-3">{fmt.d(r.week_start)}</td><td>{String(r.dept ?? "")}</td><td className="text-right">{String(r.loi)}</td><td className="text-right">{String(r.co_bien_phap)}</td><td className="text-right">{String(r.da_xac_nhan)}</td><td className="text-right font-bold">{String(r.qua_han)}</td></tr>)}</tbody></table></div>
      <div className="space-y-3">
        <div className="card p-0 overflow-auto"><div className="px-3 py-2 bg-red-50 rounded-t-xl font-bold">Lỗi LẶP ≥ 3 tuần liền → trừ trưởng phòng ({(rep.rows ?? []).length})</div><table className="tbl text-sm"><tbody>{(rep.rows ?? []).map((r, i) => <tr key={i}><td className="pl-3">{String(r.dept)}</td><td>{String(r.name ?? r.criteria_id)}</td><td className="text-right">{String(r.weeks)} tuần</td></tr>)}{(rep.rows ?? []).length === 0 && <tr><td className="p-3 text-slate-500">Không có — tốt.</td></tr>}</tbody></table></div>
        {isGS && <div className="card text-sm"><b>Đi ca thật của tôi</b> <span className="text-xs text-slate-500">(≥ 1 ngày/tuần trong khối đang kiểm — điều kiện lên bậc GS)</span><div className="flex gap-1 mt-1 flex-wrap"><FieldDay onDone={() => fd.reload()} /></div><div className="text-xs mt-1">{(fd.rows ?? []).slice(0, 8).map((r) => <span key={String(r.id)} className="inline-block mr-2">{fmt.d(r.day)} {String(r.block ?? r.dept ?? "")}</span>)}</div></div>}
        {isHead && <div className="card text-sm"><b>Chấm ngược giám sát viên (tháng này)</b> <span className="text-xs text-slate-500">hữu ích · công tâm · hiểu nghề (1–5) — là điều kiện lên bậc GS</span>
          <div className="flex gap-1 mt-1 flex-wrap items-center"><select className="input !py-1" value={rate.supervisor_id} onChange={(e) => setRate({ ...rate, supervisor_id: e.target.value })}><option value="">— giám sát viên —</option>{(gsl.rows ?? []).filter((g) => g.id !== sess.staffId).map((g) => <option key={String(g.id)} value={String(g.id)}>{String(g.full_name)} ({String(g.grade_gs)})</option>)}</select>{(["useful", "fair", "knows"] as const).map((k) => <label key={k} className="text-xs">{k === "useful" ? "Hữu ích" : k === "fair" ? "Công tâm" : "Hiểu nghề"} <select className="input !py-1 !w-16" value={rate[k]} onChange={(e) => setRate({ ...rate, [k]: Number(e.target.value) })}>{[1, 2, 3, 4, 5].map((n) => <option key={n}>{n}</option>)}</select></label>)}<input className="input !py-1" placeholder="Góp ý" aria-label="Góp ý" value={rate.note} onChange={(e) => setRate({ ...rate, note: e.target.value })} /><button className="btn-primary !py-1 !text-xs" disabled={!rate.supervisor_id} onClick={async () => { const j = await act("rate_supervisor", rate); setMsg(j.error ? String(j.error) : "Đã chấm"); }}>Chấm</button></div></div>}
      </div>
    </div>
  </div>;
}
function FieldDay({ onDone }: { onDone: () => void }) {
  const [d, setD] = useState(new Date().toISOString().slice(0, 10)); const [b, setB] = useState("CN"); const [n, setN] = useState("");
  return <><input className="input !py-1" type="date" value={d} onChange={(e) => setD(e.target.value)} /><select className="input !py-1" value={b} onChange={(e) => setB(e.target.value)}>{["CN", "TT", "SH", "D5", "KHO", "KD", "TCNS", "TB"].map((x) => <option key={x}>{x}</option>)}</select><input className="input !py-1" placeholder="Làm gì cùng tổ" aria-label="Làm gì cùng tổ" value={n} onChange={(e) => setN(e.target.value)} /><button className="btn-secondary !py-1 !text-xs" onClick={async () => { await act("gs_field_day", { day: d, block: b, note: n }); setN(""); onDone(); }}>Ghi</button></>;
}

/** CHỐNG THÔNG ĐỒNG: máy bốc mẫu · kiểm chéo mù · 8 tín hiệu tự tính · cờ đỏ → tuyến 3 kiểm đột xuất · phản ánh ẩn danh · hậu quả vào bậc */
function ChongThongDong({ sess }: { sess: Sess }) {
  const pairs = useData<R>("collusion_pairs"); const sig = useData<R>("collusion_signals"); const mine = useData<R>("my_cross_checks"); const all = useData<R>("cross_checks_all"); const wb = useData<R>(["owner", "director"].includes(sess.role) ? "whistle_reports" : null);
  const [msg, setMsg] = useState(""); const top = ["owner", "director", "auditor", "it_engineer"].includes(sess.role); const { prompt, promptElement } = usePrompt();
  const LV: Record<string, string> = { DO: "bg-red-100 text-red-900 ring-red-300", VANG: "bg-amber-100 text-amber-900 ring-amber-300", XANH: "bg-emerald-50 text-emerald-900" };
  return <div className="space-y-3">{promptElement}
    <div className="card text-sm"><b>6 lớp chống thông đồng — không phụ thuộc lòng tin</b>
      <ol className="list-decimal ml-5 mt-1 text-slate-700"><li><b>Máy chọn mẫu</b>: mỗi tuần GS phải chấm N mục do máy bốc ngẫu nhiên (ai/cái gì), bắt buộc ảnh — không tự chọn chỗ dễ.</li><li><b>Đối chiếu dữ liệu tự động</b>: chấm ĐẠT cho người mà dữ liệu vận hành báo lỗi → tín hiệu S1.</li><li><b>Kiểm chéo mù</b>: máy bốc 20% mẫu ĐẠT của mỗi GS giao GS khác/audit chấm lại độc lập; lệch → S5, khớp% vào bậc GS.</li><li><b>8 tín hiệu tự tính</b> (chấm quá nhanh, không lỗi bất thường, xác nhận CAPA quá nhanh, không ảnh, kiểm phòng gốc, chấm ngược đổi chác…) → cờ đỏ cặp GS↔phòng.</li><li><b>Cờ đỏ → tuyến 3 kiểm đột xuất</b> (audit/GĐ, không báo trước) + báo Chủ tịch/TGĐ; cờ đỏ chặn lên bậc GS; lỗi lặp trừ trưởng phòng.</li><li><b>Phản ánh ẩn danh</b> lên Chủ tịch/TGĐ từ Tài khoản (không lưu người gửi). Luân chuyển GS theo quý phá vỡ quan hệ lâu ngày; GS bị chặn chấm phòng gốc ngay lúc ghi.</li></ol>
      {top && <button className="btn-secondary !py-1 !text-xs mt-1" onClick={async () => { const j = await act("gen_cross_checks", {}); setMsg(j.error ? String(j.error) : `Máy bốc: ${j.spots} mẫu ngẫu nhiên · ${j.cross} kiểm chéo · ${j.audits} kiểm đột xuất`); pairs.reload(); mine.reload(); all.reload(); }}>🎲 Chạy bốc mẫu / kiểm chéo / cờ đỏ ngay</button>}{msg && <span className="ml-2 text-emerald-800">{msg}</span>}</div>
    {(mine.rows ?? []).length > 0 && <div className="card"><b>Kiểm chéo mù giao cho tôi ({(mine.rows ?? []).length})</b> <span className="text-xs text-slate-500">— chấm ĐỘC LẬP, không hỏi người chấm gốc, không xem kết quả gốc</span>
      <table className="tbl text-sm mt-1"><tbody>{(mine.rows ?? []).map((x) => <tr key={String(x.id)}><td className="pl-3">{String(x.criteria_name ?? x.item)}</td><td>{String(x.target_name ?? x.target_dept ?? "")}</td><td className="text-xs">tuần {fmt.d(x.week_start)}</td><td className="whitespace-nowrap"><button className="btn-primary !py-0.5 !px-2 !text-xs mr-1" onClick={async () => { const n = await prompt({ title: "Kiểm chéo — ĐẠT", label: "Ghi chú (ảnh: dán link sau dấu | )", type: "text", required: false }); if (n === null) return; const [note, ev] = n.split("|"); const j = await act("cross_check_submit", { id: x.id, result: "DAT", note, evidence_url: ev?.trim() || null }); setMsg(j.error ? String(j.error) : "Đã ghi ĐẠT"); mine.reload(); all.reload(); }}>ĐẠT</button><button className="btn-secondary !py-0.5 !px-2 !text-xs !bg-red-50" onClick={async () => { const n = await prompt({ title: "Kiểm chéo — LỖI", label: "Mô tả lỗi (ảnh: dán link sau dấu | )", type: "text" }); if (!n) return; const [note, ev] = n.split("|"); const j = await act("cross_check_submit", { id: x.id, result: "LOI", note, evidence_url: ev?.trim() || null }); setMsg(j.error ? String(j.error) : j.mismatch ? "Đã ghi LỖI — LỆCH với chấm gốc, đã báo GĐ" : "Đã ghi LỖI"); mine.reload(); all.reload(); }}>LỖI</button></td></tr>)}</tbody></table></div>}
    <div className="grid md:grid-cols-2 gap-3">
      <div className="card p-0 overflow-auto"><div className="px-3 py-2 bg-slate-100 rounded-t-xl font-bold">Cặp GS ↔ phòng theo mức cảnh báo (8 tuần)</div><table className="tbl text-sm"><thead><tr><th className="pl-3">Giám sát viên</th><th>Phòng</th><th>Mức</th><th className="text-right">Tín hiệu</th><th>Loại</th></tr></thead><tbody>
        {(pairs.rows ?? []).map((p, i) => <tr key={i}><td className="pl-3">{String(p.supervisor_name ?? p.supervisor_id)}</td><td>{String(p.dept ?? "")}</td><td><span className={`px-2 py-0.5 rounded text-xs font-bold ring-1 ${LV[String(p.level)] ?? ""}`}>{p.level === "DO" ? "CỜ ĐỎ" : p.level === "VANG" ? "vàng" : "xanh"}</span></td><td className="text-right">{String(p.n_signals)}</td><td className="text-xs">{((p.signals as string[]) ?? []).map((x) => x.split("_")[0]).join(", ")}</td></tr>)}
        {(pairs.rows ?? []).length === 0 && <tr><td colSpan={5} className="p-3 text-slate-500 text-sm">Không có tín hiệu — sạch.</td></tr>}</tbody></table></div>
      <div className="card p-0 overflow-auto"><div className="px-3 py-2 bg-slate-100 rounded-t-xl font-bold">Tín hiệu chi tiết</div><table className="tbl text-sm"><thead><tr><th className="pl-3">Tuần</th><th>GS</th><th>Phòng</th><th>Tín hiệu</th><th className="text-right">Giá trị</th><th>Mức</th></tr></thead><tbody>
        {(sig.rows ?? []).slice(0, 60).map((r, i) => <tr key={i} className={r.severity === "CAO" ? "bg-red-50" : ""}><td className="pl-3 text-xs">{fmt.d(r.week_start)}</td><td className="text-xs">{String(r.supervisor_name ?? r.supervisor_id)}</td><td className="text-xs">{String(r.dept ?? "")}</td><td className="text-xs">{String(r.label)}</td><td className="text-right">{String(r.value)}</td><td className="text-xs">{String(r.severity)}</td></tr>)}</tbody></table></div>
    </div>
    <div className="card p-0 overflow-auto"><div className="px-3 py-2 bg-slate-100 rounded-t-xl font-bold">Kiểm chéo mù gần đây ({(all.rows ?? []).length}) — lệch = người chấm gốc bị hạ khớp%</div><table className="tbl text-sm"><thead><tr><th className="pl-3">Tuần</th><th>Chấm gốc</th><th>Người kiểm chéo</th><th>Đối tượng</th><th>KQ</th><th>Lệch?</th></tr></thead><tbody>{(all.rows ?? []).slice(0, 40).map((x) => <tr key={String(x.id)} className={x.mismatch ? "bg-red-50" : ""}><td className="pl-3 text-xs">{fmt.d(x.week_start)}</td><td>{String(x.original_name ?? "")}</td><td>{String(x.checker_name ?? "")}</td><td className="text-xs">{String(x.target_dept ?? "")} {String(x.target_staff_id ?? "")}</td><td>{String(x.result ?? x.status)}</td><td>{x.mismatch ? <b className="text-red-700">LỆCH</b> : x.status === "XONG" ? "khớp" : ""}</td></tr>)}</tbody></table></div>
    {wb && <div className="card p-0 overflow-auto"><div className="px-3 py-2 bg-amber-50 rounded-t-xl font-bold">Phản ánh ẩn danh ({(wb.rows ?? []).filter((r) => r.status === "MOI").length} mới) — chỉ Chủ tịch/TGĐ/GĐ thấy; không lưu người gửi</div><table className="tbl text-sm"><thead><tr><th className="pl-3">Lúc</th><th>Loại</th><th>Phòng</th><th>Nội dung</th><th>TT</th><th></th></tr></thead><tbody>{(wb.rows ?? []).map((r) => <tr key={String(r.id)}><td className="pl-3 text-xs">{fmt.dt(r.created_at)}</td><td>{String(r.category)}</td><td>{String(r.target_dept ?? "")}</td><td className="text-sm max-w-lg">{String(r.content)}</td><td className="text-xs">{String(r.status)}</td><td className="whitespace-nowrap">{r.status !== "DA_XU_LY" && <><button className="btn-secondary !py-0.5 !px-2 !text-xs mr-1" onClick={async () => { const n = await prompt({ title: "Xử lý phản ánh", label: "Kết luận xử lý", type: "text" }); if (n === null) return; await act("whistle_handle", { id: r.id, status: "DA_XU_LY", note: n }); wb.reload(); }}>Đã xử lý</button><button className="text-xs underline" onClick={async () => { await act("whistle_handle", { id: r.id, status: "BO_QUA", note: "không đủ cơ sở" }); wb.reload(); }}>bỏ qua</button></>}</td></tr>)}</tbody></table></div>}
  </div>;
}

/** HÔM NAY CỦA GS — GS1 kiểm tuân thủ quy trình HẰNG NGÀY: cả thợ lẫn trưởng phòng; mọi lỗi hệ thống thấy mà GS không ghi = lỗi GS → mất thưởng */
function GsToday({ sess, crit }: { sess: Sess; crit: R[] }) {
  const q = useData<R>("gs_today"); const t = (q.rows ?? [])[0]?.t as R | undefined; const [msg, setMsg] = useState(""); const [openDept, setOpenDept] = useState<string>("");
  const { prompt, promptElement } = usePrompt();
  const reload = () => q.reload();
  if (!t) return <div className="card text-sm text-slate-500">đang tải…</div>;
  if (t.is_gs !== true) return <div className="card text-sm">Bạn không thuộc ngạch Giám sát. Trang này dành cho GS (GS1–GS3) đi kiểm hằng ngày. Trưởng phòng xem tab <b>Nhịp tuần & CAPA</b> để nhận lỗi và ghi biện pháp; mọi người xem <b>Bảng điểm tuần</b>.</div>;
  const depts = (t.depts as R[]) ?? []; const pend = (t.pending_auto as R[]) ?? []; const om = Number(t.omissions_month ?? 0); const omMax = Number(t.omissions_max ?? 3);
  const check = async (payload: R, result: string) => { let severity: string | null = null; let note: string | null = null; if (result === "LOI") { severity = await prompt({ title: "Ghi lỗi", label: "Mức độ: NHE / TRUNG / NANG", type: "text", defaultValue: "TRUNG" }); if (!severity) return; note = await prompt({ title: "Mô tả lỗi", label: "Mô tả lỗi + yêu cầu khắc phục (kèm link ảnh nếu có)", type: "text", required: false }); if (note === null) return; } const j = await act("sup_check", { ...payload, result, severity, note, client_ref: crypto.randomUUID() }); setMsg(j.error ? `${j.error}: ${j.detail ?? ""}` : result === "LOI" ? "Đã ghi LỖI → sẽ vào CAPA trưởng phòng thứ 6" : "Đã ghi ĐẠT"); reload(); };
  const ack = async (p: R, result: string) => { const note = await prompt({ title: result === "LOI" ? "Xác nhận LỖI" : "Xác nhận KHÔNG lỗi", label: result === "LOI" ? "Xác nhận LỖI — mô tả thêm" : "Đã xem, KHÔNG lỗi — lý do (bắt buộc, sẽ bị đối chiếu kiểm chéo)", type: "text", required: false }); if (note === null || (result === "DAT" && note.length < 5)) return; const j = await act("gs_ack", { staff_id: p.staff_id, criteria_id: p.criteria_id, item: p.criteria, result, note }); setMsg(j.error ? String(j.error) : "Đã xử lý"); reload(); };
  return <div className="space-y-3">{promptElement}
    <div className={`card flex flex-wrap gap-4 items-center ${om > omMax ? "ring-2 ring-red-400" : ""}`}>
      <div><div className="text-xs text-slate-500">Lỗi GS tháng này (máy ghi)</div><div className={`text-2xl font-black ${om > omMax ? "text-red-700" : om > 0 ? "text-amber-700" : "text-emerald-700"}`}>{om}<span className="text-sm text-slate-500"> / ngưỡng {omMax}</span></div><div className="text-xs">{om > omMax ? "⛔ Quá ngưỡng → tháng này KHÔNG có thưởng GS" : "Vượt ngưỡng là mất thưởng tháng"}</div></div>
      <div><div className="text-xs text-slate-500">Lượt kiểm tháng</div><div className="text-2xl font-black">{String(t.checks_month)}</div></div>
      <div><div className="text-xs text-slate-500">Ngày đi ca thật</div><div className="text-2xl font-black">{String(t.field_days_month)}</div></div>
      <div><div className="text-xs text-slate-500">Việc quá hạn trong các phòng tôi kiểm</div><div className="text-2xl font-black">{String(t.overdue_tasks)}</div></div>
      <div className="text-xs text-slate-600 max-w-md">Nguyên tắc: kiểm <b>hằng ngày</b>, không chờ có việc; kiểm <b>cả thợ lẫn trưởng phòng</b>; ghi lỗi <b>ngay lúc thấy</b>; lỗi hệ thống đã phát hiện mà GS không ghi/xác nhận trong 24h = <b>lỗi của GS</b>.</div>
      {msg && <div className="text-sm text-emerald-800 w-full">{msg}</div>}
    </div>
    {pend.length > 0 && <div className="card p-0 overflow-auto ring-2 ring-red-300"><div className="px-3 py-2 bg-red-50 rounded-t-xl font-bold">🔴 Hệ thống đã phát hiện {pend.length} lỗi — GS phải ghi hoặc xác nhận trong 24h</div><table className="tbl text-sm"><thead><tr><th className="pl-3">Tuần</th><th>Nhân sự</th><th>Phòng</th><th>Tiêu chí (auto)</th><th className="text-right">Giá trị / mục tiêu</th><th></th></tr></thead><tbody>
      {pend.map((p, i) => <tr key={i}><td className="pl-3 text-xs">{fmt.d(p.week)}</td><td>{String(p.name)}</td><td className="text-xs">{String(p.dept)}</td><td className="text-xs">{String(p.criteria)}</td><td className="text-right text-xs">{String(p.value)} / {String(p.target)}</td><td className="whitespace-nowrap"><button className="btn-secondary !py-0.5 !px-2 !text-xs !bg-red-50 mr-1" onClick={() => ack(p, "LOI")}>Ghi LỖI</button><button className="btn-secondary !py-0.5 !px-2 !text-xs" onClick={() => ack(p, "DAT")}>Đã xem, không lỗi</button></td></tr>)}</tbody></table></div>}
    {depts.map((d) => { const staff = (d.staff as R[]) ?? []; const procs = (d.processes as R[]) ?? []; const head = d.head as R | null; const due = procs.filter((p) => p.due === true); const open = openDept === String(d.dept) || depts.length === 1; return <div key={String(d.dept)} className="card">
      <div className="flex items-center gap-2 flex-wrap cursor-pointer" onClick={() => setOpenDept(open && depts.length > 1 ? "" : String(d.dept))}><b>{open ? "▾" : "▸"} Phòng {String(d.dept)} — {String(d.name ?? "")}</b><span className={`text-xs px-2 py-0.5 rounded-full ${Number(d.checks_today) >= Number(d.min_per_day) ? "bg-emerald-100 text-emerald-900" : "bg-red-100 text-red-900"}`}>hôm nay {String(d.checks_today)}/{String(d.min_per_day)} lượt</span><span className="text-xs text-slate-600">{due.length} quy trình đến hạn kiểm · {staff.length} nhân sự</span>{head && <span className={`text-xs px-2 py-0.5 rounded-full ${head.checked_this_week ? "bg-emerald-100" : "bg-amber-100"}`}>Trưởng phòng {String(head.name)}: {head.checked_this_week ? "đã kiểm tuần này" : "CHƯA kiểm tuần này"}</span>}</div>
      {open && <div className="grid lg:grid-cols-2 gap-3 mt-2">
        <div><div className="text-xs font-bold text-slate-500 uppercase mb-1">Quy trình của phòng — kiểm tuân thủ ({procs.length})</div><div className="max-h-96 overflow-auto divide-y">{procs.map((p) => <div key={String(p.id)} className={`py-1.5 flex items-start gap-2 ${p.due ? "" : "opacity-60"}`}><div className="flex-1 min-w-0"><div className="text-sm font-semibold truncate" title={String(p.what ?? "")}>{String(p.name)} <span className="text-[10px] rounded bg-slate-100 px-1">{String(p.freq)}</span></div><div className="text-xs text-slate-500 truncate">{String(p.what ?? "")}</div><div className="text-[11px] text-slate-400">lần cuối: {p.last_check ? fmt.d(p.last_check) : "chưa"}{p.due ? " · ĐẾN HẠN" : ""}</div></div><div className="shrink-0 whitespace-nowrap"><button className="btn-secondary !py-0.5 !px-2 !text-xs mr-1" onClick={() => check({ target_dept: d.dept, criteria_id: p.id, item: p.name, sop_code: null }, "DAT")}>Đạt</button><button className="btn-secondary !py-0.5 !px-2 !text-xs !bg-red-50" onClick={() => check({ target_dept: d.dept, criteria_id: p.id, item: p.name, sop_code: null }, "LOI")}>Lỗi</button></div></div>)}</div></div>
        <div><div className="text-xs font-bold text-slate-500 uppercase mb-1">Con người — thợ & trưởng phòng ({staff.length})</div><div className="max-h-96 overflow-auto divide-y">{staff.map((w) => { const isH = w.role === "tech_head" || w.role === "team_lead"; const cs = crit.filter((c) => (c.role_scope === "TRUONG_PHONG" ? isH : !c.role_scope) && c.method === "MANUAL" && !c.process_code && (!c.position_code || c.position_code === w.position_code) && (!c.dept_code || c.dept_code === d.dept)); return <div key={String(w.id)} className="py-1.5"><div className="flex items-center gap-2"><b className="text-sm">{String(w.name)}</b>{isH && <span className="text-[10px] rounded bg-amber-100 px-1">TRƯỞNG PHÒNG</span>}<span className="text-xs text-slate-500">{String(w.position ?? "")}</span><span className="text-[11px] text-slate-400 ml-auto">kiểm lần cuối: {w.last_check ? fmt.d(w.last_check) : "chưa"}{Number(w.auto_fails) > 0 ? <span className="text-red-700 font-bold"> · {String(w.auto_fails)} lỗi auto</span> : ""}</span></div><div className="flex flex-wrap gap-1 mt-1">{cs.map((c) => <span key={String(c.id)} className="inline-flex items-center gap-0.5 text-xs border rounded px-1"><span title={String(c.what ?? "")}>{String(c.name).slice(0, 34)}</span><button className="text-emerald-700 font-bold px-1" onClick={() => check({ target_staff_id: w.id, target_dept: d.dept, criteria_id: c.id, item: c.name }, "DAT")}>✓</button><button className="text-red-700 font-bold px-1" onClick={() => check({ target_staff_id: w.id, target_dept: d.dept, criteria_id: c.id, item: c.name }, "LOI")}>✗</button></span>)}</div></div>; })}</div></div>
      </div>}
    </div>; })}
    {depts.length === 0 && <div className="card text-sm text-slate-500">Bạn chưa được phân công phòng nào (supervision_assignments). HCNS/GS trưởng phân công hoặc chạy luân chuyển.</div>}
    <div className="card p-0 overflow-auto"><div className="px-3 py-2 bg-slate-100 rounded-t-xl font-bold">Lỗi GS của tôi (máy ghi, không sửa được) — 20 gần nhất</div><table className="tbl text-sm"><tbody>{((t.omissions_list as R[]) ?? []).map((o, i) => <tr key={i}><td className="pl-3 text-xs">{fmt.d(o.day)}</td><td className="text-xs">{String(o.kind)}</td><td>{String(o.detail)}</td><td className="text-right">−{String(o.points)}</td></tr>)}{((t.omissions_list as R[]) ?? []).length === 0 && <tr><td className="p-3 text-slate-500">Chưa có — tốt.</td></tr>}</tbody></table></div>
  </div>;
}
