"use client";
import { useMemo, useState } from "react";
import { useData, act, fmt } from "@/lib/client";
import { DataBoundary } from "@/components/ui/DataBoundary";
import type { Sess } from "@/components/Shell";
type R = Record<string, unknown>;
/** NHẬP LÔ ĐÀN — khai báo 1 lần cả lô: nguồn, ngày, giấy kiểm dịch, giá; dán danh sách con (mỗi dòng: RFID | thẻ | giới | ngày sinh | kg | giống) hoặc chỉ nhập SỐ CON → hệ thống sinh mã cá thể, thẻ, sự kiện NHẬP + CÁCH LY 21 ngày, tự vào sổ đàn */
export function HerdIntake({ sess, onDone }: { sess: Sess; onDone: () => void }) {
  const partners = useData("partners"); const groups = useData("animal_groups"); const locations = useData("locations"); const species = useData("species"); const classes = useData("animal_classes");
  const [lot, setLot] = useState<R>({ kind: "MUA", species: "BO", date: new Date().toISOString().slice(0, 10), quarantine_until: new Date(Date.now() + 21 * 86400e3).toISOString().slice(0, 10) });
  const [n, setN] = useState(10); const [text, setText] = useState(""); const [msg, setMsg] = useState(""); const [busy, setBusy] = useState(false);
  const rows = useMemo(() => { const out: R[] = []; const lines = text.split("\n").map((l) => l.trim()).filter(Boolean); if (lines.length) { for (const l of lines) { const [rfid, visual_tag, sex, birth_date, weight_kg, breed, class_code] = l.split(/[|;\t]/).map((x) => x?.trim()); out.push({ rfid: rfid || "", visual_tag: visual_tag || "", sex: (sex || "").toUpperCase().startsWith("F") || sex === "cái" ? "F" : sex ? "M" : null, birth_date: birth_date || null, weight_kg: weight_kg ? Number(weight_kg) : null, breed: breed || null, class_code: class_code || null }); } } else for (let i = 0; i < n; i++) out.push({ rfid: "", visual_tag: "", sex: lot.sex ?? null, birth_date: null, weight_kg: null }); return out; }, [text, n, lot.sex]);
  const submit = async () => { setBusy(true); const j = await act("intake_herd", { lot, animals: rows.map((r) => ({ ...r, species: lot.species, breed: r.breed ?? lot.breed, class_code: r.class_code ?? lot.class_code ?? null })) }); setBusy(false); if (j.ok) { setMsg(`Đã nhập lô ${j.lot_id}: ${(j.animals as string[]).length} con (${(j.animals as string[]).slice(0, 5).join(", ")}…) — đang cách ly, việc theo dõi đã sinh`); setText(""); onDone(); } else setMsg(String(j.error)); };
  return (<div className="card border-2 border-emerald-500 space-y-2">
    <b>Nhập lô đàn (nhiều con một lần)</b>
    <div className="grid sm:grid-cols-3 lg:grid-cols-6 gap-2 text-sm">
      <select className="input" value={String(lot.species)} onChange={(e) => setLot({ ...lot, species: e.target.value })}>{(species.rows ?? []).filter((s) => s.identify_level === "CA_THE").map((s) => <option key={String(s.code)} value={String(s.code)}>{String(s.name)}</option>)}</select>
      <select className="input" value={String(lot.kind)} onChange={(e) => setLot({ ...lot, kind: e.target.value })}><option value="MUA">Mua ngoài</option><option value="CHUYEN_TRAI">Chuyển từ trại khác</option><option value="NHAP_KHAU">Nhập khẩu</option><option value="GOP_VON">Góp vốn/hộ liên kết</option></select>
      <select className="input" value={String(lot.source_partner_id ?? "")} onChange={(e) => setLot({ ...lot, source_partner_id: e.target.value })}><option value="">Nguồn (NCC/hộ)</option>{(partners.rows ?? []).map((p) => <option key={String(p.id)} value={String(p.id)}>{String(p.name)}</option>)}</select>
      <input className="input" type="date" value={String(lot.date)} onChange={(e) => setLot({ ...lot, date: e.target.value })} />
      <input className="input" placeholder="Số giấy kiểm dịch" aria-label="Số giấy kiểm dịch" value={String(lot.vet_cert_no ?? "")} onChange={(e) => setLot({ ...lot, vet_cert_no: e.target.value })} />
      <input className="input" type="date" title="Cách ly đến" value={String(lot.quarantine_until)} onChange={(e) => setLot({ ...lot, quarantine_until: e.target.value })} />
      <input className="input" placeholder="Giống chung (Sind lai, Brahman…)" aria-label="Giống chung (Sind lai, Brahman…)" value={String(lot.breed ?? "")} onChange={(e) => setLot({ ...lot, breed: e.target.value })} />
      <select className="input" value={String(lot.class_code ?? "")} onChange={(e) => setLot({ ...lot, class_code: e.target.value })}><option value="">Lớp (bê/tơ/cái SS/vỗ béo)</option>{(classes.rows ?? []).filter((c) => c.species_code === lot.species).map((c) => <option key={String(c.code)} value={String(c.code)}>{String(c.name)}</option>)}</select>
      <select className="input" value={String(lot.sex ?? "")} onChange={(e) => setLot({ ...lot, sex: e.target.value })}><option value="">Giới (nếu chung)</option><option value="F">Cái</option><option value="M">Đực</option></select>
      <input className="input" type="number" placeholder="Giá/con (đ)" aria-label="Giá/con (đ)" value={String(lot.price ?? "")} onChange={(e) => setLot({ ...lot, price: Number(e.target.value) })} />
      <select className="input" value={String(lot.group_id ?? "")} onChange={(e) => setLot({ ...lot, group_id: e.target.value })}><option value="">Đàn/nhóm đích</option>{(groups.rows ?? []).map((g) => <option key={String(g.id)} value={String(g.id)}>{String(g.name)}</option>)}</select>
      <select className="input" value={String(lot.location_id ?? "")} onChange={(e) => setLot({ ...lot, location_id: e.target.value })}><option value="">Chuồng cách ly</option>{(locations.rows ?? []).map((l) => <option key={String(l.id)} value={String(l.id)}>{String(l.name)}</option>)}</select>
    </div>
    <div className="grid md:grid-cols-2 gap-2 text-sm">
      <div><div className="text-xs text-muted">Cách 1: chỉ nhập số con (mã sinh tự động, thẻ gắn sau — "chờ gắn tai")</div><input className="input !w-40" type="number" min={1} max={2000} value={n} onChange={(e) => setN(Number(e.target.value))} disabled={!!text.trim()} /></div>
      <div><div className="text-xs text-muted">Cách 2: dán danh sách (mỗi dòng: <b>RFID | thẻ mắt | giới(F/M) | ngày sinh | kg | giống | lớp</b>) — từ Excel/máy đọc RFID</div><textarea className="input font-mono text-xs" rows={4} placeholder={"704100000000021|B021|F|2024-03-10|320|Sind lai\n704100000000022|B022|M||280"} value={text} onChange={(e) => setText(e.target.value)} /></div>
    </div>
    <div className="text-xs text-muted">Xem trước: <b>{rows.length}</b> con · giá trị lô {fmt.vnd(rows.length * Number(lot.price ?? 0))} · {rows.filter((r) => r.rfid || r.visual_tag).length} con có thẻ · sau nhập: sổ đàn K8 +{rows.length}, sự kiện NHẬP + CÁCH LY, việc theo dõi (cân/vaccine/tẩy KST) tự sinh theo vòng thông số.</div>
    <div className="flex gap-2 items-center"><button className="btn-primary !py-2" disabled={busy || !rows.length} onClick={submit}>{busy ? "Đang tạo…" : `Nhập ${rows.length} con vào lô`}</button><a className="underline text-sm" href="/api/import/csv?template=animals">hoặc nhập CSV bảng animals</a>{msg && <span className="text-sm text-brand">{msg}</span>}</div>
  </div>);
}
/** VÒNG THÔNG SỐ THEO DÕI: mỗi con — tham số nào (cân 30 ngày, BCS, vaccine LMLM/THT 6 tháng, tẩy KST, khám thai sau phối 35 ngày, đẻ dự kiến 283 ngày…) → lần cuối · hạn kế · quá hạn; sửa tham số theo loài/lớp trong Quản trị DL */
export function MonitoringRing({ animalId }: { animalId?: string }) {
  const due = useData(animalId ? "animal_monitoring" : "monitoring_due", { animal: animalId });
  const rows = (due.rows ?? []).filter((r) => !animalId || r.animal_id === animalId);
  const today = new Date().toISOString().slice(0, 10);
  return (<div className="card p-0 overflow-auto"><div className="px-3 py-2 bg-surface-2 rounded-t-xl flex items-center gap-2"><b>🔄 Vòng theo dõi {animalId ? `— ${animalId}` : "— đến hạn 7 ngày tới (toàn trại)"} ({rows.length})</b><a className="ml-auto underline text-xs" href="/quan-tri?t=monitoring_params">sửa tham số theo loài/lớp</a></div>
    <DataBoundary loading={due.loading} error={due.error} empty={!rows.length} onRetry={due.reload} emptyText="Không có mục đến hạn."><table className="tbl text-sm"><thead><tr>{!animalId && <th className="pl-3">Con</th>}<th className="pl-3">Tham số</th><th>Sự kiện</th><th>Mức</th><th>Lần cuối</th><th>Hạn kế</th><th>Mục tiêu</th><th>Ai</th></tr></thead><tbody>{rows.map((r, i) => { const over = r.due_date && String(r.due_date).slice(0, 10) < today; const soon = r.due_date && String(r.due_date).slice(0, 10) <= today; return <tr key={i} className={over ? "bg-danger-soft-tok" : soon ? "bg-warning-soft-tok" : ""}>{!animalId && <td className="pl-3 font-mono text-xs"><a className="underline" href={`/dan/${r.animal_id}`}>{String(r.animal_id)}</a> <span className="text-muted">{String(r.class_code ?? "")}</span></td>}<td className="pl-3 font-semibold">{String(r.param_name)}</td><td className="text-xs font-mono">{String(r.event_type)}</td><td><span className={r.level === "CRITICAL" ? "b-red" : r.level === "MAJOR" ? "b-yel" : "b-gray"}>{String(r.level)}</span></td><td className="text-xs">{r.last_ts ? fmt.d(r.last_ts) : <span className="text-muted">chưa</span>}</td><td className={over ? "text-danger-tok font-bold" : soon ? "text-warning-tok font-bold" : ""}>{r.due_date ? fmt.d(r.due_date) : "—"}{over ? " (quá hạn)" : ""}</td><td className="text-xs">{r.target_min != null || r.target_max != null ? `${r.target_min ?? ""}–${r.target_max ?? ""} ${r.unit ?? ""}` : ""}</td><td className="text-xs">{String(r.role_hint ?? "")}</td></tr>; })}</tbody></table></DataBoundary></div>);
}
