"use client";
import { useState } from "react";
import { useData, act, fmt } from "@/lib/client";
import { LaborBudgetPanel } from "@/components/panels/CloseoutBits";
import type { Sess } from "@/components/Shell";
import Tabs from "@/components/Tabs";
import SupplyPlan from "@/components/panels/SupplyPlan";
import { ComposedChart, Bar, Line, XAxis, YAxis, Tooltip, Legend, CartesianGrid, ResponsiveContainer, ReferenceLine } from "recharts";
type R = Record<string, unknown>;
const adm = (t: string, row: R) => fetch(`/api/admin/${t}`, { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ row }) }).then((r) => r.json());
const ml = (m: string) => { const d = new Date(m); return `${d.getMonth() + 1}/${d.getFullYear()}`; };
const LINES: [string, string][] = [["DAN", "Đàn bò (con)"], ["TMR_KG", "Thức ăn cần (kg)"], ["CUNG_CO", "Cỏ tươi cung (kg)"], ["CUNG_BAP", "Bắp ủ thu (kg) · tồn cuối"], ["CUNG_ROM", "Rơm cung (kg) · tồn cuối"], ["MUA_DONG", "Mua nguyên liệu (đ)"], ["SX_D5_KG", "D5 sản xuất (kg)"], ["DOANH_THU", "Doanh thu (đ)"], ["CHI_PHI", "Chi phí (đ)"], ["LAI_GOP", "Lãi gộp (đ)"], ["DONG_TIEN", "Dòng tiền (đ)"]];
/** KẾ HOẠCH: Năm (mục tiêu · giả định tự tính · năng lực) → Đàn theo lứa → Lịch vụ 12 tháng → S&OP 12 tháng (cung–cầu theo tháng, tiền) → chốt phiên bản → ban hành việc → KH–TT lệch */
export default function KeHoachNam({ sess }: { sess: Sess }) {
  const [tab, setTab] = useState<"sop" | "nam" | "dan" | "vu" | "cungcau" | "khtt" | "luong">("sop");
  const years = useData("plan_years"); const asm = useData("plan_assumptions"); const cap = useData("plan_capacity"); const hb = useData("plan_herd_batches"); const cc = useData("plan_crop_calendar"); const plots = useData("plots"); const crops = useData("crops");
  const [from, setFrom] = useState(new Date().toISOString().slice(0, 7) + "-01"); const sop = useData("sop_monthly", { from }, [from]); const pva = useData("plan_vs_actual");
  const [msg, setMsg] = useState(""); const canW = ["owner", "director", "tech_head", "accountant"].includes(sess.role); const canPub = ["owner", "director"].includes(sess.role);
  const Y = (years.rows ?? [])[0]; const [hf, setHf] = useState<R>({ kind: "VO_BEO", head: 30, days: 180, in_weight_kg: 220, out_weight_kg: 430, adg: 1.15, price_in: 22000000, price_out: 82000 }); const [cf, setCf] = useState<R>({ crop_code: "BAP-SK", cycle_days: 85, expected_yield_kg_ha: 45000 });
  const S = sop.rows ?? []; const months = [...new Set(S.map((r) => String(r.month)))].sort(); const cell = (m: string, l: string) => S.find((r) => r.month === m && r.line === l);
  const chart = months.map((m) => { const b = cell(m, "CUNG_BAP"); const c = cell(m, "CUNG_CO"); const t = cell(m, "TMR_KG"); const d = cell(m, "DONG_TIEN"); const dt = (b?.detail ?? {}) as R; const ct = (c?.detail ?? {}) as R; return { m: ml(m), bap_thu: Number(b?.value ?? 0) / 1000, bap_can: Number(dt.demand ?? 0) / 1000, bap_ton: Number(dt.stock_end ?? 0) / 1000, co_cung: Number(c?.value ?? 0) / 1000, co_can: Number(ct.demand ?? 0) / 1000, tmr: Number(t?.value ?? 0) / 1000, dong_tien: Number(d?.value ?? 0) / 1e6, doanh_thu: Number(cell(m, "DOANH_THU")?.value ?? 0) / 1e6, chi_phi: Number(cell(m, "CHI_PHI")?.value ?? 0) / 1e6 }; });
  const fmtv = (l: string, v: unknown) => l.endsWith("(đ)") ? fmt.vnd(Number(v)) : fmt.n(Number(v));
  return <div className="space-y-3">
    <Tabs items={[["sop", "S&OP 12 tháng (cung–cầu · tiền)"], ["nam", `Năm · giả định · năng lực${Y ? ` (${Y.year} v${Y.version} · ${Y.status})` : ""}`], ["dan", `Đàn theo lứa (${(hb.rows ?? []).length})`], ["vu", `Lịch vụ 12 tháng (${(cc.rows ?? []).length})`], ["cungcau", "Cung–cầu theo kỳ (kịch bản)"], ["luong", "👥 Quỹ lương KH vs thực"], ["khtt", "KH – TT lệch"]]} value={tab} onChange={(k) => setTab(k as typeof tab)} right={<div className="flex gap-1">{canW && Y && <button className="btn-secondary !py-1.5 !px-3 text-sm" onClick={async () => { const j = await act("close_plan", { id: Y.id }); setMsg(j.ok ? `Đã chốt phiên bản kế hoạch (${j.n} dòng)` : String(j.error)); years.reload(); }}>Chốt phiên bản</button>}{canPub && Y && <button className="btn-primary !py-1.5 !px-3 text-sm" onClick={async () => { if (!confirm("Ban hành kế hoạch năm → sinh việc cho KTT/KD/kế toán theo tháng?")) return; const j = await act("publish_year_plan", { id: Y.id }); setMsg(j.ok ? `Đã ban hành: ${j.n} việc` : String(j.error)); years.reload(); }}>📣 Ban hành</button>}</div>} />
    {msg && <div className="rounded-xl bg-emerald-50 border border-emerald-300 px-3 py-2 text-sm">{msg}</div>}
    {tab === "sop" && <div className="space-y-3">
      <div className="card flex flex-wrap items-center gap-2 text-sm"><b>Kế hoạch tổng thể tháng (S&OP)</b><span className="text-xs text-slate-500">— tự dựng từ đàn thật + lứa kế hoạch + mùa vụ đang trồng + lịch vụ + giả định; cuốn chiếu 12 tháng từ</span><input className="input !w-40 !py-1" type="date" value={from} onChange={(e) => setFrom(e.target.value)} /><span className="text-xs text-slate-500">· vào tab Đàn/Lịch vụ để đổi kế hoạch → bảng tự tính lại</span></div>
      <div className="grid lg:grid-cols-2 gap-3"><div className="card !p-3"><div className="text-sm font-bold">Bắp ủ chua: thu (cột) vs cần (đường) & tồn hào ủ cuối tháng (tấn) — âm = đói</div><div style={{ height: 240 }}><ResponsiveContainer><ComposedChart data={chart}><CartesianGrid strokeDasharray="3 3" /><XAxis dataKey="m" tick={{ fontSize: 10 }} /><YAxis tick={{ fontSize: 10 }} /><Tooltip /><Legend wrapperStyle={{ fontSize: 10 }} /><ReferenceLine y={0} stroke="#dc2626" /><Bar dataKey="bap_thu" name="Thu hoạch (t ủ)" fill="#84cc16" /><Line dataKey="bap_can" name="Cần (t)" stroke="#f59e0b" strokeWidth={2} dot={false} /><Line dataKey="bap_ton" name="Tồn cuối (t)" stroke="#059669" strokeWidth={2} /></ComposedChart></ResponsiveContainer></div></div>
        <div className="card !p-3"><div className="text-sm font-bold">Cỏ tươi cung vs cần (tấn) · Doanh thu – chi phí – dòng tiền (triệu đ)</div><div style={{ height: 240 }}><ResponsiveContainer><ComposedChart data={chart}><CartesianGrid strokeDasharray="3 3" /><XAxis dataKey="m" tick={{ fontSize: 10 }} /><YAxis yAxisId="l" tick={{ fontSize: 10 }} /><YAxis yAxisId="r" orientation="right" tick={{ fontSize: 10 }} /><Tooltip /><Legend wrapperStyle={{ fontSize: 10 }} /><Bar yAxisId="l" dataKey="co_cung" name="Cỏ cung (t)" fill="#a7f3d0" /><Line yAxisId="l" dataKey="co_can" name="Cỏ cần (t)" stroke="#065f46" dot={false} /><Line yAxisId="r" dataKey="doanh_thu" name="Doanh thu (tr)" stroke="#0ea5e9" dot={false} /><Line yAxisId="r" dataKey="chi_phi" name="Chi phí (tr)" stroke="#ef4444" dot={false} /><Line yAxisId="r" dataKey="dong_tien" name="Dòng tiền (tr)" stroke="#8b5cf6" strokeWidth={2} /></ComposedChart></ResponsiveContainer></div></div></div>
      <div className="card p-0 overflow-auto"><table className="tbl text-xs"><thead><tr><th className="pl-3 sticky left-0 bg-white">Dòng</th>{months.map((m) => <th key={m} className="text-right whitespace-nowrap">{ml(m)}</th>)}</tr></thead><tbody>{LINES.map(([l, name]) => <tr key={l} className={l === "DONG_TIEN" || l === "LAI_GOP" ? "font-semibold" : ""}><td className="pl-3 sticky left-0 bg-white whitespace-nowrap">{name}</td>{months.map((m) => { const r = cell(m, l); const d = (r?.detail ?? {}) as R; const neg = (l.startsWith("CUNG_") && Number(d.gap ?? 0) < 0) || ((l === "LAI_GOP" || l === "DONG_TIEN") && Number(r?.value ?? 0) < 0) || (l === "DAN" && d.over_cap === true) || (l === "SX_D5_KG" && d.cap_tan_ngay != null && Number(d.tan_ngay) > Number(d.cap_tan_ngay)); return <td key={m} className={`text-right whitespace-nowrap ${neg ? "bg-red-50 text-red-700 font-bold" : ""}`} title={JSON.stringify(d)}>{r ? fmtv(name, r.value) : ""}{l.startsWith("CUNG_") && r ? <div className="text-[10px] text-slate-500">cần {fmt.n(Number(d.demand ?? 0))}{d.stock_end != null ? ` · tồn ${fmt.n(Number(d.stock_end))}` : ` · ${Number(d.gap ?? 0) >= 0 ? "dư" : "thiếu"} ${fmt.n(Math.abs(Number(d.gap ?? 0)))}`}</div> : null}{l === "DAN" && r ? <div className="text-[10px] text-slate-500">vỗ {String(d.vo_beo)} · nái {String(d.nai)} · tơ {String(d.to)} · bê {String(d.be)}{Number(d.sinh_du_kien) ? ` · +${d.sinh_du_kien} sinh` : ""}{Number(d.xuat_vo_beo_ke_hoach) ? ` · xuất ${d.xuat_vo_beo_ke_hoach}` : ""}</div> : null}</td>; })}</tr>)}</tbody></table><div className="p-2 text-xs text-slate-500">Ô đỏ = vấn đề tháng đó (đói bắp/rơm/cỏ, vượt chỗ chuồng/công suất D5, lỗ, dòng tiền âm). Rê chuột xem chi tiết. Sửa kế hoạch ở tab Đàn/Lịch vụ; "Chốt phiên bản" lưu để so KH–TT; "Ban hành" sinh việc: nhập lứa/cửa xuất (KTT/GĐ), gieo theo lịch (TT), mua trước 30 ngày tháng thiếu (kế toán/mua hàng), D5 vượt công suất.</div></div></div>}
    {tab === "nam" && <div className="grid lg:grid-cols-3 gap-3">
      <div className="card"><b>Kế hoạch năm</b>{Y ? <div className="text-sm mt-1"><div>{String(Y.name)} · phiên bản {String(Y.version)} · <span className="rounded-full px-2 bg-slate-100 text-xs">{String(Y.status)}</span></div><div className="mt-2 text-xs text-slate-500">Mục tiêu:</div><table className="tbl text-sm">{Object.entries((Y.targets as R) ?? {}).map(([k, v]) => <tr key={k}><td>{k}</td><td className="text-right font-semibold">{typeof v === "number" && v > 1e6 ? fmt.vnd(v) : String(v)}</td></tr>)}</table><a className="underline text-xs" href={`/quan-tri?t=plan_years&pk=${Y.id}`}>✎ sửa mục tiêu</a></div> : <div className="text-sm text-slate-500 mt-1">Chưa có kế hoạch năm — <a className="underline" href="/quan-tri?t=plan_years">tạo</a>.</div>}
        <div className="mt-3"><b>Năng lực (ràng buộc)</b><table className="tbl text-sm mt-1">{(cap.rows ?? []).map((c) => <tr key={String(c.id)}><td>{String(c.name)}</td><td className="text-right font-semibold">{fmt.n(Number(c.capacity))} {String(c.unit)}</td></tr>)}</table><a className="underline text-xs" href="/quan-tri?t=plan_capacity">✎ sửa</a></div></div>
      <div className="card lg:col-span-2 p-0 overflow-auto"><div className="px-3 py-2 bg-slate-100 rounded-t-xl font-bold flex items-center gap-2">Giả định — tự tính từ 30 tháng dữ liệu; sửa tay = ghi đè (MANUAL), để trống = quay về tự tính <button className="ml-auto btn-secondary !py-1 !px-2 text-xs" onClick={async () => { const j = await act("compute_assumptions", {}); setMsg(j.ok ? `Đã tính lại ${j.n} giả định` : String(j.error)); asm.reload(); sop.reload(); }}>⟳ tính lại</button></div><table className="tbl text-sm"><thead><tr><th className="pl-3">Khóa</th><th className="text-right">Giá trị</th><th>ĐV</th><th>Nguồn</th><th>Ghi chú</th><th></th></tr></thead><tbody>{(asm.rows ?? []).map((a) => <tr key={String(a.key)} className={a.source === "MANUAL" ? "bg-amber-50" : ""}><td className="pl-3 font-mono text-xs">{String(a.key)}</td><td className="text-right font-semibold">{fmt.n(Number(a.value))}</td><td className="text-xs">{String(a.unit ?? "")}</td><td className="text-xs">{String(a.source)}</td><td className="text-xs">{String(a.note ?? "")}</td><td className="text-xs">{canW && <button className="underline" onClick={async () => { const v = prompt(`${a.key} — giá trị mới (để trống = tự tính)`, String(a.value)); if (v === null) return; const j = await act("set_assumption", { key: a.key, value: v === "" ? null : Number(v), unit: a.unit }); setMsg(j.ok ? "Đã cập nhật" : String(j.error)); asm.reload(); sop.reload(); }}>sửa</button>}</td></tr>)}</tbody></table></div></div>}
    {tab === "dan" && <div className="space-y-3">{canW && <div className="card"><b>Thêm lứa</b> <span className="text-xs text-slate-500">— vỗ béo (nhập tơ → xuất sau N ngày), nái mới, gà đẻ/thịt, dê; ràng buộc chỗ chuồng hiện ở S&OP (ô đỏ)</span><div className="grid sm:grid-cols-3 lg:grid-cols-9 gap-2 mt-2"><select className="input" value={String(hf.kind)} onChange={(e) => setHf({ ...hf, kind: e.target.value })}>{[["VO_BEO", "Vỗ béo"], ["NAI_MOI", "Nái mới"], ["GA_DE", "Gà đẻ"], ["GA_THIT", "Gà thịt"], ["DE_THIT", "Dê thịt"], ["LUON", "Lươn"]].map(([k, l]) => <option key={k} value={k}>{l}</option>)}</select><input className="input" placeholder="Tên lứa" value={String(hf.name ?? "")} onChange={(e) => setHf({ ...hf, name: e.target.value })} /><input className="input" type="date" value={String(hf.start_date ?? "")} onChange={(e) => setHf({ ...hf, start_date: e.target.value })} /><input className="input" type="number" placeholder="Đầu con" value={String(hf.head)} onChange={(e) => setHf({ ...hf, head: e.target.value })} /><input className="input" type="number" placeholder="Ngày nuôi" value={String(hf.days)} onChange={(e) => setHf({ ...hf, days: e.target.value })} /><input className="input" type="number" placeholder="Kg vào" value={String(hf.in_weight_kg ?? "")} onChange={(e) => setHf({ ...hf, in_weight_kg: e.target.value })} /><input className="input" type="number" placeholder="Kg ra" value={String(hf.out_weight_kg ?? "")} onChange={(e) => setHf({ ...hf, out_weight_kg: e.target.value })} /><input className="input" type="number" placeholder="Giá bán/kg" value={String(hf.price_out ?? "")} onChange={(e) => setHf({ ...hf, price_out: e.target.value })} /><button className="btn-primary !py-2" disabled={!hf.start_date || !hf.head} onClick={async () => { const j = await adm("plan_herd_batches", { ...hf, plan_year_id: Y?.id ?? null, head: Number(hf.head), days: Number(hf.days), in_weight_kg: Number(hf.in_weight_kg) || null, out_weight_kg: Number(hf.out_weight_kg) || null, price_out: Number(hf.price_out) || null, price_in: Number(hf.price_in) || null, adg: Number(hf.adg) || null }); setMsg(j.ok ? "Đã thêm lứa — S&OP tính lại" : `${j.error}: ${j.detail ?? ""}`); hb.reload(); sop.reload(); }}>Thêm</button></div></div>}
      <div className="card p-0 overflow-auto"><table className="tbl text-sm"><thead><tr><th className="pl-3">Lứa</th><th>Loại</th><th>Nhập</th><th className="text-right">Con</th><th className="text-right">Ngày</th><th>Cửa xuất</th><th className="text-right">Kg vào→ra</th><th className="text-right">Doanh thu DK</th><th>TT</th><th></th></tr></thead><tbody>{(hb.rows ?? []).map((b) => { const out = new Date(new Date(String(b.start_date)).getTime() + Number(b.days ?? 180) * 864e5); return <tr key={String(b.id)}><td className="pl-3">{String(b.name ?? b.id)}</td><td className="text-xs">{String(b.kind)}</td><td>{fmt.d(String(b.start_date))}</td><td className="text-right">{String(b.head)}</td><td className="text-right">{String(b.days ?? "")}</td><td>{b.kind === "VO_BEO" || b.kind === "GA_THIT" || b.kind === "DE_THIT" ? fmt.d(out.toISOString()) : ""}</td><td className="text-right">{String(b.in_weight_kg ?? "")}→{String(b.out_weight_kg ?? "")}</td><td className="text-right">{b.out_weight_kg && b.price_out ? fmt.vnd(Number(b.head) * Number(b.out_weight_kg) * Number(b.price_out) * (1 - Number(b.mortality_pct ?? 2) / 100)) : ""}</td><td>{String(b.status)}</td><td className="text-xs">{canW && b.status === "KE_HOACH" && <button className="underline text-red-700" onClick={async () => { await adm("plan_herd_batches", { id: b.id, status: "HUY" }); hb.reload(); sop.reload(); }}>hủy</button>}</td></tr>; })}</tbody></table></div></div>}
    {tab === "vu" && <div className="space-y-3">{canW && <div className="card"><b>Thêm vụ vào lịch</b> <span className="text-xs text-slate-500">— mục tiêu: sinh khối về đều 12 tháng (nhìn cột "Bắp ủ thu" ở S&OP), luân canh, không để 4 ô cùng thu 1 tháng</span><div className="grid sm:grid-cols-3 lg:grid-cols-6 gap-2 mt-2"><select className="input" value={String(cf.plot_id ?? "")} onChange={(e) => setCf({ ...cf, plot_id: e.target.value })}><option value="">Ô</option>{(plots.rows ?? []).map((p) => <option key={String(p.id)} value={String(p.id)}>{String(p.name)} ({String(p.area_ha)} ha)</option>)}</select><select className="input" value={String(cf.crop_code)} onChange={(e) => setCf({ ...cf, crop_code: e.target.value })}>{(crops.rows ?? []).map((c) => <option key={String(c.code)} value={String(c.code)}>{String(c.name)}</option>)}</select><input className="input" type="date" value={String(cf.sow_date ?? "")} onChange={(e) => setCf({ ...cf, sow_date: e.target.value })} /><input className="input" type="number" placeholder="Ngày đến thu" value={String(cf.cycle_days)} onChange={(e) => setCf({ ...cf, cycle_days: e.target.value })} /><input className="input" type="number" placeholder="Năng suất kg/ha" value={String(cf.expected_yield_kg_ha)} onChange={(e) => setCf({ ...cf, expected_yield_kg_ha: e.target.value })} /><button className="btn-primary !py-2" disabled={!cf.plot_id || !cf.sow_date} onClick={async () => { const j = await adm("plan_crop_calendar", { ...cf, plan_year_id: Y?.id ?? null, cycle_days: Number(cf.cycle_days), expected_yield_kg_ha: Number(cf.expected_yield_kg_ha) }); setMsg(j.ok ? "Đã thêm vụ — S&OP tính lại" : `${j.error}: ${j.detail ?? ""}`); cc.reload(); sop.reload(); }}>Thêm</button></div></div>}
      <div className="card p-0 overflow-auto"><div className="px-3 py-2 bg-slate-100 rounded-t-xl font-bold">Lịch vụ theo ô × tháng (● gieo · ▲ thu)</div><table className="tbl text-xs"><thead><tr><th className="pl-3">Ô</th>{months.map((m) => <th key={m} className="text-center">{ml(m)}</th>)}</tr></thead><tbody>{(plots.rows ?? []).filter((p) => p.active !== false).map((p) => <tr key={String(p.id)}><td className="pl-3 whitespace-nowrap">{String(p.name)} <span className="text-slate-400">{String(p.area_ha)} ha</span></td>{months.map((m) => { const mm = m.slice(0, 7); const rows = (cc.rows ?? []).filter((c) => c.plot_id === p.id); const sow = rows.find((c) => String(c.sow_date).slice(0, 7) === mm); const hv = rows.find((c) => new Date(new Date(String(c.sow_date)).getTime() + Number(c.cycle_days ?? 85) * 864e5).toISOString().slice(0, 7) === mm); return <td key={m} className={`text-center ${sow ? "bg-emerald-50" : hv ? "bg-amber-50" : ""}`} title={sow ? `Gieo ${sow.crop_code}` : hv ? `Thu ${hv.crop_code}` : ""}>{sow ? "●" : ""}{hv ? "▲" : ""}</td>; })}</tr>)}</tbody></table></div>
      <div className="card p-0 overflow-auto"><table className="tbl text-sm"><thead><tr><th className="pl-3">Ô</th><th>Cây</th><th>Gieo</th><th>Thu DK</th><th className="text-right">ha</th><th className="text-right">Năng suất</th><th className="text-right">Sản lượng DK</th><th>TT</th><th></th></tr></thead><tbody>{(cc.rows ?? []).map((c) => <tr key={String(c.id)}><td className="pl-3">{String(c.plot_name)}</td><td>{String(c.crop_name ?? c.crop_code)}</td><td>{fmt.d(String(c.sow_date))}</td><td>{fmt.d(new Date(new Date(String(c.sow_date)).getTime() + Number(c.cycle_days ?? 85) * 864e5).toISOString())}</td><td className="text-right">{String(c.ha)}</td><td className="text-right">{fmt.n(Number(c.expected_yield_kg_ha))}</td><td className="text-right font-semibold">{fmt.n(Number(c.ha) * Number(c.expected_yield_kg_ha))} kg</td><td>{String(c.status)}</td><td className="text-xs">{canW && c.status === "KE_HOACH" && <button className="underline text-red-700" onClick={async () => { await adm("plan_crop_calendar", { id: c.id, status: "HUY" }); cc.reload(); sop.reload(); }}>hủy</button>}</td></tr>)}</tbody></table></div></div>}
    {tab === "cungcau" && <SupplyPlan sess={sess} />}
    {tab === "luong" && <LaborBudgetPanel sess={sess} />}
    {tab === "khtt" && <div className="card p-0 overflow-auto"><div className="px-3 py-2 bg-slate-100 rounded-t-xl font-bold">Kế hoạch (phiên bản chốt) vs thực tế theo tháng — lệch &gt;10% đỏ; nguyên nhân ghi ở sổ sự cố/CAPA</div><table className="tbl text-sm"><thead><tr><th className="pl-3">Tháng</th><th>Dòng</th><th className="text-right">KH</th><th className="text-right">TT</th><th className="text-right">Lệch %</th></tr></thead><tbody>{(pva.rows ?? []).map((r, i) => <tr key={i} className={Math.abs(Number(r.diff_pct ?? 0)) > 10 ? "bg-red-50" : ""}><td className="pl-3">{ml(String(r.month))}</td><td>{String(LINES.find(([l]) => l === r.line)?.[1] ?? r.line)}</td><td className="text-right">{fmt.n(Number(r.plan))}</td><td className="text-right">{r.actual != null ? fmt.n(Number(r.actual)) : "—"}</td><td className={`text-right font-bold ${Math.abs(Number(r.diff_pct ?? 0)) > 10 ? "text-red-700" : ""}`}>{r.diff_pct != null ? `${r.diff_pct}%` : ""}</td></tr>)}</tbody></table>{!(pva.rows ?? []).length && <div className="p-3 text-sm text-slate-500">Chưa có phiên bản chốt hoặc chưa tới tháng thực tế — bấm "Chốt phiên bản" ở đầu trang.</div>}</div>}
  </div>;
}
