"use client";
import Tabs from "@/components/Tabs";
import { useMemo, useState } from "react";
import AnyChart from "@/components/AnyChart";
import ChartIcon from "@/components/ChartIcon";
import ThreeTap from "@/components/ThreeTap";
import { buildForms, type Ref } from "@/lib/forms";
import { useData, act, fmt } from "@/lib/client";
import { usePrompt } from "@/components/ui/PromptDialog";
import { toast } from "@/components/ui/Toast";
import { useUrlTab } from "@/lib/useUrlTab";
import { Term } from "@/components/ui/Term";
import type { Sess } from "@/components/Shell";
type R = Record<string, unknown>;

export default function KhoPanel({ sess }: { sess: Sess }) {
  const { prompt, promptElement } = usePrompt();
  const stock = useData("stock"); const dos = useData("days_of_stock"); const fefo = useData("fefo_red"); const adj = useData("adjustments_pending"); const silage = useData("days_silage"); const herd = useData("herd_value");
  const animals = useData("animals"), groups = useData("animal_groups"), warehouses = useData("warehouses"), products = useData("products"), plots = useData("plots"), recipes = useData("recipes"), locations = useData("locations"), sops = useData("sops"), devices = useData("devices"), partners = useData("partners"), bins = useData("bins"); const binStock = useData("bin_stock"); const repl = useData("replenishment"); const abc = useData("abc_suggest"); const cold = useData("cold_chain"); const vehicles = useData("vehicles"); const trips = useData("trips"); const [tripSel, setTripSel] = useState<string | null>(null); const stops = useData(tripSel ? "trip_stops" : null, { trip: tripSel ?? undefined }, [tripSel]); const score = useData("supplier_scorecard"); const cct = useData("cycle_count_tasks"); const pkb = useData("picking_bins"); const [pw, setPw] = useState<R>({}); const put = useData(pw.wh && pw.sku ? "putaway" : null, { wh: String(pw.wh ?? ""), sku: String(pw.sku ?? ""), qty: String(pw.qty ?? "1") }, [pw.wh, pw.sku, pw.qty]); const [cardSku, setCardSku] = useState<string | null>(null); const card = useData(cardSku ? "stock_card" : null, { sku: cardSku ?? undefined }, [cardSku]); const [trF, setTrF] = useState<R>({ kind: "GIAO_HANG" }); const [msg2, setMsg2] = useState(""); const sval = useData("stock_value");
  const [tab, setTab] = useUrlTab(["ton", "ghi", "kiemke", "so", "bin", "rop", "lanh", "van", "ncc", "the", "giatri", "bieudo"] as const, "ton"); const [form, setForm] = useState("stock_in"); const [sku, setSku] = useState<string | null>(null); const [openSku, setOpenSku] = useState<string | null>(null);
  const ledger = useData(sku ? "stock_ledger" : null, { sku: sku ?? undefined });
  const ref: Ref | null = useMemo(() => animals.rows && groups.rows && warehouses.rows && products.rows && plots.rows && recipes.rows && locations.rows && sops.rows && devices.rows && partners.rows ? { animals: animals.rows, groups: groups.rows, warehouses: warehouses.rows, products: products.rows, plots: plots.rows, recipes: recipes.rows, locations: locations.rows, sops: sops.rows, devices: devices.rows, partners: partners.rows, bins: bins.rows ?? [] } : null, [animals.rows, groups.rows, warehouses.rows, products.rows, plots.rows, recipes.rows, locations.rows, sops.rows, devices.rows, partners.rows, bins.rows]);
  const forms = ref ? buildForms(ref, sess.farmId) : null;
  const byWh = useMemo(() => { const m = new Map<string, Record<string, unknown>[]>(); for (const r of stock.rows ?? []) m.set(String(r.warehouse_code), [...(m.get(String(r.warehouse_code)) ?? []), r]); return [...m.entries()].sort(); }, [stock.rows]);
  const canApprove = ["tech_head","director","accountant"].includes(sess.role);
  const ds = silage.rows?.[0]; const hv = herd.rows?.[0];
  return (
    <div className="space-y-3">
      {promptElement}
      <div className="grid grid-cols-2 sm:grid-cols-4 gap-2">
        <div className="kpi"><div className="l"><Term k="NGAY-TON">Ngày-tồn</Term> ủ chua (<Term k="K3" />)</div><div className={`v ${ds && Number(ds.days_silage) < 30 ? "text-red-700" : ds && Number(ds.days_silage) < 45 ? "text-amber-700" : ""}`}>{ds?.days_silage != null ? fmt.n(ds.days_silage) : "—"}</div><div className="text-xs">{fmt.n(ds?.k3_kg)} kg / {fmt.n(ds?.kg_per_day)} kg·ngày</div></div>
        <div className="kpi"><div className="l">Sổ đàn (<Term k="K8" />)</div><div className="v">{fmt.n(hv?.head_count)} con</div><div className="text-xs">{fmt.vnd(hv?.value)}</div></div>
        <div className="kpi"><div className="l"><Term k="FEFO" /> đỏ (&lt;20% hạn)</div><div className={`v ${(fefo.rows?.length ?? 0) > 0 ? "text-red-700" : ""}`}>{fefo.rows?.length ?? "—"}</div></div>
        <div className="kpi"><div className="l">Điều chỉnh chờ duyệt</div><div className="v">{adj.rows?.length ?? "—"}</div></div>
      </div>
      <Tabs items={[["ton", "Tồn · Tồn kho"], ["so", "Tồn · Ngày-tồn nguyên liệu"], ["the", "Tồn · Thẻ kho theo lô"], ["giatri", "Tồn · 💰 Giá trị tồn"], ["bieudo", "Tồn · 📈 Biểu đồ"], ["ghi", "Nhập/Xuất · Ghi nhập / xuất"], ["bin", `Nhập/Xuất · Vị trí bin (${(bins.rows ?? []).length})`], ["kiemke", "Kiểm soát · Kiểm kê, điều chỉnh"], ["rop", `Kiểm soát · Bổ sung ROP (${(repl.rows ?? []).filter((r) => Number(r.suggest_qty) > 0).length})`], ["lanh", "Kiểm soát · Kho lạnh"], ["van", `Vận tải · Chuyến xe (${(trips.rows ?? []).filter((t) => t.status !== "XONG" && t.status !== "HUY").length})`], ["ncc", "Vận tải · NCC scorecard"]]} value={tab} onChange={(k) => setTab(k as typeof tab)} />
      {tab === "ton" && byWh.map(([wh, rows]) => { const bySku = new Map<string, Record<string, unknown>[]>(); for (const r of rows) bySku.set(String(r.sku), [...(bySku.get(String(r.sku)) ?? []), r]); return (
        <div key={wh} className="card p-0 overflow-auto"><div className="px-3 py-2 font-bold bg-stone-100 rounded-t-2xl flex justify-between"><span>{wh} · {String(warehouses.rows?.find((w) => w.code === wh)?.name ?? "")}</span><span className="text-sm font-normal">{bySku.size} mặt hàng · {rows.length} lô</span></div>
          <table className="tbl"><thead><tr><th className="pl-3">Hàng (bấm mở lô)</th><th className="text-right">Số lô</th><th className="text-right">Tồn</th><th>Hạn gần nhất</th><th className="text-right">Giá vốn BQ</th><th></th></tr></thead><tbody>
            {[...bySku.entries()].map(([sku, ls]) => { const open = openSku === sku; const qty = ls.reduce((a, r) => a + Number(r.qty), 0); const exp = ls.map((r) => r.expiry_date).filter(Boolean).sort()[0]; const cost = ls.reduce((a, r) => a + Number(r.qty) * Number(r.avg_cost ?? 0), 0) / (qty || 1); return [
              <tr key={sku} className="cursor-pointer hover:bg-green-50" role="button" tabIndex={0} aria-expanded={open} aria-label={`${open ? "Đóng" : "Mở"} danh sách lô của ${String(ls[0].product_name)}`} onKeyDown={(e) => { if (e.key === "Enter" || e.key === " ") { e.preventDefault(); setOpenSku(open ? null : sku); } }} onClick={() => setOpenSku(open ? null : sku)}><td className="pl-3 font-semibold">{open ? "▾" : "▸"} {String(ls[0].product_name)}<div className="text-xs text-stone-500 font-normal">{sku}</div></td><td className="text-right">{ls.length}</td><td className="text-right font-bold">{fmt.n(qty, 1)} {String(ls[0].unit ?? "")}</td><td className="text-sm">{exp ? fmt.d(exp) : "—"}</td><td className="text-right">{fmt.vnd(cost)}</td><td><ChartIcon type="product" id={sku} label={String(ls[0].product_name)} /> <button className="underline text-sm" onClick={(e) => { e.stopPropagation(); setSku(sku); setTab("so"); }}>thẻ kho</button></td></tr>,
              ...(open ? [<tr key={sku + "-chart"} className="bg-white"><td colSpan={6} className="p-2"><div className="grid md:grid-cols-2 gap-2"><AnyChart title="Nhập kho theo ngày" table="inventory_moves" col="qty" dim="reason" filters={{ sku, direction: "1" }} height={180} /><AnyChart title="Xuất kho theo ngày" table="inventory_moves" col="qty" dim="reason" filters={{ sku, direction: "-1" }} height={180} /></div></td></tr>, ...ls.map((r, i) => <tr key={sku + i} className="bg-stone-50"><td className="pl-8 text-sm">lô <span className="font-mono">{String(r.lot_id ?? "").split("-").slice(3).join("-") || "—"}</span>{r.lot_status !== "KHA_DUNG" && r.lot_status ? <span className="b-red ml-1">{String(r.lot_status)}</span> : null}</td><td></td><td className="text-right">{fmt.n(r.qty, 1)}</td><td className="text-sm">{fmt.d(r.expiry_date)}</td><td className="text-right text-sm">{fmt.vnd(r.avg_cost)}</td><td></td></tr>)] : [])]; })}
          </tbody></table></div>); })}
      {tab === "ghi" && forms && (<div className="space-y-2"><div className="flex gap-2 flex-wrap">{["stock_in", "stock_out", "fuel_out", "egg_in"].map((k) => <button key={k} className={`btn !py-2 !text-base ${form === k ? "bg-green-700 text-white" : "bg-white border"}`} onClick={() => setForm(k)}>{forms[k].title}</button>)}</div><ThreeTap spec={{ ...forms[form], onDone: () => stock.reload() }} /></div>)}
      {tab === "kiemke" && (<div className="space-y-3">
        {forms && <ThreeTap spec={{ ...forms.stocktake, onDone: () => adj.reload() }} />}
        <div className="card"><h3 className="font-bold">Phiếu điều chỉnh tồn (cần KTT/GĐ/KT duyệt — người khác người đề nghị)</h3>
          <AdjForm sess={sess} warehouses={warehouses.rows ?? []} products={products.rows ?? []} onDone={() => adj.reload()} />
          <table className="tbl mt-2"><thead><tr><th>Lúc</th><th>Kho</th><th>Hàng</th><th>±</th><th>Lý do</th><th>Đề nghị</th><th></th></tr></thead><tbody>
            {(adj.rows ?? []).map((r) => <tr key={String(r.id)}><td>{fmt.dt(r.ts)}</td><td>{String(r.warehouse_id ?? "").slice(-2)}</td><td>{String(r.sku ?? r.target_table)}</td><td className="font-bold">{fmt.n(r.delta, 1)}</td><td>{String(r.reason)}</td><td>{String(r.created_by)}</td><td>{canApprove && <><button className="btn-primary !py-1 !px-2 !text-sm mr-1" onClick={async () => { const j = await act("approve_adjustment", { id: r.id, approve: true }); if (j.error) toast.err(j.error); adj.reload(); stock.reload(); }}>Duyệt</button><button className="btn-secondary !py-1 !px-2 !text-sm" onClick={async () => { await act("approve_adjustment", { id: r.id, approve: false }); adj.reload(); }}>Từ chối</button></>}</td></tr>)}
          </tbody></table></div></div>)}
      {tab === "bieudo" && (<div className="space-y-3">
        <div className="card"><AnyChart title="Sản lượng NHẬP kho theo mặt hàng (thu hoạch cỏ/ngô, mua, sản xuất D5…)" table="inventory_moves" col="qty" dim="sku" filters={{ direction: "1" }} bucket="week" height={300} compare /></div>
        <div className="card"><AnyChart title="XUẤT kho theo mặt hàng (cho ăn, bán, hao hụt…)" table="inventory_moves" col="qty" dim="sku" filters={{ direction: "-1" }} bucket="week" height={300} compare /></div>
        <div className="grid md:grid-cols-2 gap-3"><div className="card"><AnyChart title="Giá trị nhập mua (đ)" table="inventory_moves" col="qty" agg="sum" dim="from_to" filters={{ reason: "NHAP_MUA" }} bucket="week" height={220} /></div><div className="card"><AnyChart title="Thu hoạch/cắt sinh khối theo giống (kg)" table="crop_logs" col="qty_kg" dim="variety" bucket="week" height={220} /></div></div>
        <div className="text-sm text-stone-600">Muốn biểu đồ cho bất kỳ trường nào khác → <a className="underline" href="/so-lieu?tab=any">Số liệu › Mọi trường</a>.</div>
      </div>)}
      {tab === "bin" && <div className="space-y-3">
        <div className="card p-0 overflow-auto"><div className="px-3 py-2 bg-stone-100 rounded-t-2xl font-bold flex items-center gap-2 flex-wrap">Vị trí bin: kho → khu → dãy → kệ → tầng → ô; sức chứa, dải nhiệt, thứ tự pick <a className="ml-auto underline text-sm font-normal" href="/quan-tri?t=bins">＋ bin</a></div><table className="tbl text-sm"><thead><tr><th className="pl-3">Kho</th><th>Bin</th><th>Khu/dãy/kệ/tầng</th><th>Loại</th><th className="text-right">Sức chứa kg</th><th className="text-right">Đang chứa</th><th className="text-right">SKU</th><th>Nhiệt</th><th className="text-right">Pick #</th></tr></thead><tbody>{(bins.rows ?? []).map((b) => { const full = b.capacity_kg ? Number(b.qty) / Number(b.capacity_kg) : 0; return <tr key={String(b.id)} className={full > 0.9 ? "bg-amber-50" : ""}><td className="pl-3">{String(b.warehouse_code)}</td><td className="font-mono">{String(b.code)}</td><td className="text-xs">{[b.zone, b.aisle, b.rack, b.level, b.position].filter(Boolean).join(" / ")}</td><td>{String(b.kind)}</td><td className="text-right">{String(b.capacity_kg ?? "")}</td><td className="text-right">{fmt.n(Number(b.qty))} {b.capacity_kg ? <span className="text-xs text-stone-500">({Math.round(full * 100)}%)</span> : null}</td><td className="text-right">{String(b.skus)}</td><td className="text-xs">{b.temp_min != null ? `${b.temp_min}–${b.temp_max}°C` : ""}</td><td className="text-right">{String(b.pick_seq)}</td></tr>; })}</tbody></table></div>
        <div className="grid lg:grid-cols-2 gap-3"><div className="card"><b>Gợi ý putaway (xếp hàng vào bin)</b> — cùng SKU → bin trống → còn chỗ; theo loại hàng cho phép & sức chứa<div className="flex gap-2 mt-2 flex-wrap"><select className="input !w-40" value={String(pw.wh ?? "")} onChange={(e) => setPw({ ...pw, wh: e.target.value })}><option value="">Kho</option>{(warehouses.rows ?? []).map((w) => <option key={String(w.id)} value={String(w.id)}>{String(w.code)} {String(w.name)}</option>)}</select><select className="input !w-56" value={String(pw.sku ?? "")} onChange={(e) => setPw({ ...pw, sku: e.target.value })}><option value="">Mặt hàng</option>{(products.rows ?? []).map((p) => <option key={String(p.sku)} value={String(p.sku)}>{String(p.name)}</option>)}</select><input className="input !w-24" type="number" placeholder="kg" aria-label="kg" value={String(pw.qty ?? "")} onChange={(e) => setPw({ ...pw, qty: e.target.value })} /></div><table className="tbl text-sm mt-2"><tbody>{(put.rows ?? []).map((r) => <tr key={String(r.bin_id)}><td className="font-mono">{String(r.bin_code)}</td><td>{String(r.reason)}</td><td className="text-right">còn {fmt.n(Number(r.free_kg))} kg</td></tr>)}</tbody></table>{!!pw.wh && !!pw.sku && put.rows?.length === 0 && <div className="text-sm text-stone-500 mt-1">Không có bin phù hợp (hết chỗ / kho chưa khai bin).</div>}</div>
          <div className="card p-0 overflow-auto"><div className="px-3 py-2 bg-stone-100 rounded-t-2xl font-bold">Tồn theo bin & lô (FEFO)</div><table className="tbl text-sm"><thead><tr><th className="pl-3">Kho</th><th>Bin</th><th>SKU</th><th>Lô</th><th>HSD</th><th className="text-right">Tồn</th></tr></thead><tbody>{(binStock.rows ?? []).slice(0, 200).map((r, i) => <tr key={i} className={!r.bin_id ? "text-stone-400" : ""}><td className="pl-3">{String(r.warehouse_code)}</td><td className="font-mono">{String(r.bin_code ?? "— chưa gán bin")}</td><td>{String(r.product_name)}</td><td className="font-mono text-xs">{String(r.lot_id ?? "")}</td><td>{r.expiry_date ? fmt.d(String(r.expiry_date)) : ""}</td><td className="text-right">{fmt.n(Number(r.qty))}</td></tr>)}</tbody></table></div></div>
        <div className="card p-0 overflow-auto"><div className="px-3 py-2 bg-stone-100 rounded-t-2xl font-bold">Phiếu soạn theo bin (đơn đã giữ chỗ FEFO → bin có lô, thứ tự đường đi)</div><table className="tbl text-sm"><thead><tr><th className="pl-3">Đơn</th><th>Khách</th><th>SKU</th><th>Lô</th><th>Bin</th><th className="text-right">Pick #</th><th className="text-right">SL</th></tr></thead><tbody>{(pkb.rows ?? []).map((r, i) => <tr key={i}><td className="pl-3 font-mono text-xs">{String(r.order_id)}</td><td>{String(r.partner_name ?? "")}</td><td>{String(r.product_name)}</td><td className="font-mono text-xs">{String(r.lot_id ?? "")}</td><td className="font-mono">{String(r.bin_code ?? "—")}</td><td className="text-right">{String(r.pick_seq ?? "")}</td><td className="text-right">{fmt.n(Number(r.qty))}</td></tr>)}</tbody></table>{pkb.rows?.length === 0 && <div className="p-3 text-sm text-stone-500">Không có đơn đang giữ chỗ.</div>}</div></div>}
      {tab === "rop" && <div className="space-y-3">
        <div className="card p-0 overflow-auto"><div className="px-3 py-2 bg-stone-100 rounded-t-2xl font-bold flex items-center gap-2 flex-wrap">Bổ sung tồn: ROP / min–max / theo ngày-tồn → số lượng gợi ý đặt (MOQ, lead time, NCC ưu tiên) — cảnh báo AL-ROP hàng ngày <a className="ml-auto underline text-sm font-normal" href="/quan-tri?t=stock_policies">＋ chính sách</a></div><table className="tbl text-sm"><thead><tr><th className="pl-3">SKU</th><th>PP</th><th className="text-right">Tồn KD</th><th className="text-right">Dùng/ngày</th><th className="text-right">Ngày tồn</th><th className="text-right">ROP/min</th><th className="text-right">Max</th><th className="text-right">Lead</th><th>ABC</th><th className="text-right">Gợi ý đặt</th><th>NCC</th><th></th></tr></thead><tbody>{(repl.rows ?? []).map((r) => <tr key={String(r.sku)} className={Number(r.suggest_qty) > 0 ? "bg-red-50" : ""}><td className="pl-3">{String(r.product_name)} <span className="font-mono text-xs text-stone-500">{String(r.sku)}</span></td><td>{String(r.method)}</td><td className="text-right">{fmt.n(Number(r.available))}</td><td className="text-right">{r.use_per_day ? fmt.n(Number(r.use_per_day)) : ""}</td><td className="text-right">{r.days ? fmt.n(Number(r.days)) : ""}</td><td className="text-right">{String(r.rop_qty ?? r.min_qty ?? r.min_days ?? "")}</td><td className="text-right">{String(r.max_qty ?? "")}</td><td className="text-right">{String(r.lead_time_days)}d</td><td>{String(r.abc_class ?? "")}</td><td className={`text-right font-bold ${Number(r.suggest_qty) > 0 ? "text-red-700" : ""}`}>{fmt.n(Number(r.suggest_qty))}</td><td className="text-xs">{String(r.supplier_name ?? "")}</td><td className="text-xs">{Number(r.suggest_qty) > 0 && <a className="underline" href={`/ktt?tab=po&sku=${r.sku}&qty=${Math.round(Number(r.suggest_qty))}&supplier=${r.preferred_supplier_id ?? ""}`}>tạo PO</a>}</td></tr>)}</tbody></table></div>
        <div className="grid lg:grid-cols-2 gap-3"><div className="card p-0 overflow-auto"><div className="px-3 py-2 bg-stone-100 rounded-t-2xl font-bold">Phân loại ABC theo giá trị xuất 90 ngày (A ≤80% · B ≤95% · C còn lại) → điền vào chính sách</div><table className="tbl text-sm"><thead><tr><th className="pl-3">SKU</th><th className="text-right">Giá trị xuất</th><th className="text-right">Lũy kế %</th><th>ABC</th></tr></thead><tbody>{(abc.rows ?? []).slice(0, 40).map((r) => <tr key={String(r.sku)}><td className="pl-3">{String(r.product_name)}</td><td className="text-right">{fmt.vnd(Number(r.val))}</td><td className="text-right">{String(r.cum_pct)}</td><td className="font-bold">{String(r.abc)}</td></tr>)}</tbody></table></div>
          <div className="card p-0 overflow-auto"><div className="px-3 py-2 bg-stone-100 rounded-t-2xl font-bold">Kiểm kê chu kỳ (A 30 ngày · B 90 · C 180) — việc tự sinh trong job đêm</div><table className="tbl text-sm"><thead><tr><th className="pl-3">Việc</th><th>Hạn</th><th>Vai</th></tr></thead><tbody>{(cct.rows ?? []).map((t) => <tr key={String(t.id)}><td className="pl-3">{String(t.title)}</td><td>{fmt.dt(String(t.due_at))}</td><td>{String(t.role_hint ?? "")}</td></tr>)}</tbody></table>{cct.rows?.length === 0 && <div className="p-3 text-sm text-stone-500">Không có việc kiểm kê mở — ghi kiểm kê ở tab Kiểm kê.</div>}</div></div></div>}
      {tab === "lanh" && <div className="space-y-3"><div className="card p-0 overflow-auto"><div className="px-3 py-2 bg-stone-100 rounded-t-2xl font-bold">Kho lạnh — dải nhiệt, thiết bị đo (sensor_reads), lệch dải 24h → cảnh báo AL-COLD (ĐỎ) · gán thiết bị: <a className="underline" href="/quan-tri?t=warehouses">warehouses.temp_device_id</a></div><table className="tbl text-sm"><thead><tr><th className="pl-3">Kho</th><th>Dải</th><th>Thiết bị</th><th className="text-right">Nhiệt hiện tại</th><th>Lúc</th><th className="text-right">Lệch 24h</th></tr></thead><tbody>{(cold.rows ?? []).map((r) => { const bad = r.last_temp != null && (Number(r.last_temp) < Number(r.temp_min) || Number(r.last_temp) > Number(r.temp_max)); return <tr key={String(r.warehouse_id)} className={bad ? "bg-red-50" : ""}><td className="pl-3">{String(r.code)} {String(r.name)}</td><td>{String(r.temp_min)}–{String(r.temp_max)}°C</td><td className="font-mono text-xs">{String(r.temp_device_id ?? "chưa gán")}</td><td className={`text-right font-bold ${bad ? "text-red-700" : ""}`}>{r.last_temp != null ? `${r.last_temp}°C` : "—"}</td><td className="text-xs">{r.last_ts ? fmt.dt(String(r.last_ts)) : ""}</td><td className="text-right">{String(r.excursions_24h)}</td></tr>; })}</tbody></table></div><div className="card"><AnyChart title="Nhiệt độ cảm biến (°C) — chọn thiết bị kho lạnh" table="sensor_reads" col="value" dim="device_id" bucket="day" agg="avg" height={240} /></div><div className="text-xs text-stone-500">Bin loại LANH/DONG có dải riêng (2–8°C / −20…−15°C). Xe lạnh ghi nhiệt lúc giao ở điểm dừng (temp_at_delivery) — chuỗi lạnh liền mạch kho → xe → khách.</div></div>}
      {tab === "van" && <div className="space-y-3">
        <div className="grid lg:grid-cols-3 gap-3"><div className="card p-0 overflow-auto lg:col-span-1"><div className="px-3 py-2 bg-stone-100 rounded-t-2xl font-bold flex items-center gap-2">Đội xe <a className="ml-auto underline text-sm font-normal" href="/quan-tri?t=vehicles">＋ xe</a></div><table className="tbl text-sm"><thead><tr><th className="pl-3">Biển</th><th>Loại</th><th className="text-right">Tải kg</th><th>Lạnh</th><th>Đăng kiểm</th><th>BH</th></tr></thead><tbody>{(vehicles.rows ?? []).map((v) => <tr key={String(v.id)}><td className="pl-3 font-mono">{String(v.plate)}</td><td>{String(v.kind)}</td><td className="text-right">{String(v.capacity_kg ?? "")}</td><td>{v.refrigerated ? `❄ ${v.temp_min}–${v.temp_max}°C` : ""}</td><td className="text-xs">{String(v.inspection_due ?? "")}</td><td className="text-xs">{String(v.insurance_due ?? "")}</td></tr>)}</tbody></table></div>
          <div className="card lg:col-span-2"><b>Tạo chuyến</b><div className="grid sm:grid-cols-3 lg:grid-cols-5 gap-2 mt-2"><select className="input" value={String(trF.vehicle_id ?? "")} onChange={(e) => setTrF({ ...trF, vehicle_id: e.target.value })}><option value="">Xe</option>{(vehicles.rows ?? []).map((v) => <option key={String(v.id)} value={String(v.id)}>{String(v.plate)}</option>)}</select><select className="input" value={String(trF.kind)} onChange={(e) => setTrF({ ...trF, kind: e.target.value })}>{[["GIAO_HANG", "Giao hàng"], ["THU_MUA", "Thu mua"], ["NOI_BO", "Nội bộ"], ["KHAC", "Khác"]].map(([k, l]) => <option key={k} value={k}>{l}</option>)}</select><input className="input" type="datetime-local" value={String(trF.planned_at ?? "")} onChange={(e) => setTrF({ ...trF, planned_at: e.target.value })} /><input className="input" placeholder="Tuyến / ghi chú" aria-label="Tuyến / ghi chú" value={String(trF.route_note ?? "")} onChange={(e) => setTrF({ ...trF, route_note: e.target.value })} /><button className="btn-primary !py-2" disabled={!trF.vehicle_id} onClick={async () => { const j = await fetch("/api/admin/trips", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ row: { ...trF, driver_id: sess.staffId, cold_chain: !!(vehicles.rows ?? []).find((v) => v.id === trF.vehicle_id)?.refrigerated } }) }).then((r) => r.json()); setMsg2(j.ok ? "Đã tạo chuyến — thêm điểm dừng ở Quản trị DL › trip_stops hoặc bấm chuyến" : `${j.error}: ${j.detail ?? ""}`); trips.reload(); }}>Tạo</button></div>{msg2 && <div className="text-sm mt-1 text-emerald-700">{msg2}</div>}
            <table className="tbl text-sm mt-2"><thead><tr><th className="pl-3">Chuyến</th><th>Xe</th><th>Tài xế</th><th>Loại</th><th>KH</th><th className="text-right">Điểm</th><th className="text-right">Đã giao</th><th className="text-right">km</th><th className="text-right">L/100</th><th>TT</th><th></th></tr></thead><tbody>{(trips.rows ?? []).map((t) => <tr key={String(t.id)} className={tripSel === t.id ? "bg-emerald-50" : ""}><td className="pl-3 font-mono text-xs"><button className="underline" onClick={() => setTripSel(String(t.id))}>{String(t.id)}</button></td><td>{String(t.plate ?? "")}{t.refrigerated ? " ❄" : ""}</td><td>{String(t.driver_name ?? "")}</td><td>{String(t.kind)}</td><td className="text-xs">{t.planned_at ? fmt.dt(String(t.planned_at)) : ""}</td><td className="text-right">{String(t.stops)}</td><td className="text-right">{String(t.delivered)}</td><td className="text-right">{String(t.km ?? "")}</td><td className="text-right">{String(t.l_per_100km ?? "")}</td><td>{String(t.status)}</td><td className="text-xs whitespace-nowrap">{t.status === "KE_HOACH" && <button className="underline mr-2" onClick={async () => { await fetch("/api/admin/trips", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ row: { id: t.id, status: "DANG_DI", depart_at: new Date().toISOString() } }) }); trips.reload(); }}>▶ xuất phát</button>}{t.status === "DANG_DI" && <button className="underline mr-2" onClick={async () => { const km = await prompt({ title: "Kết thúc chuyến", label: "Odometer về (km)?", type: "number", min: 0, required: false }); const fuel = await prompt({ title: "Kết thúc chuyến", label: "Nhiên liệu (lít)?", type: "number", min: 0, required: false }); await fetch("/api/admin/trips", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ row: { id: t.id, status: "XONG", return_at: new Date().toISOString(), odometer_end: km ? Number(km) : null, fuel_l: fuel ? Number(fuel) : null } }) }); trips.reload(); }}>✓ về</button>}<a className="underline" href={`/quan-tri?t=trip_stops`}>＋ điểm</a></td></tr>)}</tbody></table>
            {tripSel && <div className="mt-2 rounded-xl bg-stone-50 p-2"><b>Điểm dừng chuyến {tripSel}</b><table className="tbl text-sm"><thead><tr><th>#</th><th>Khách</th><th>Đơn</th><th>Địa chỉ</th><th className="text-right">kg</th><th>Đến</th><th>Nhiệt giao</th><th>POD</th><th>TT</th><th></th></tr></thead><tbody>{(stops.rows ?? []).map((st) => <tr key={String(st.id)}><td>{String(st.seq)}</td><td>{String(st.partner_name ?? "")}</td><td className="font-mono text-xs">{String(st.order_id ?? "")}</td><td className="text-xs">{String(st.address ?? "")}</td><td className="text-right">{String(st.qty_kg ?? "")}</td><td className="text-xs">{st.arrived_at ? fmt.dt(String(st.arrived_at)) : ""}</td><td>{st.temp_at_delivery != null ? `${st.temp_at_delivery}°C` : ""}</td><td>{st.pod_url ? <a className="underline" href={String(st.pod_url)}>ảnh</a> : ""}</td><td>{String(st.status)}</td><td className="text-xs">{st.status === "CHO" && <button className="underline" onClick={async () => { const temp = await prompt({ title: "Đã giao (POD)", label: "Nhiệt độ hàng lúc giao (°C, để trống nếu không lạnh)", type: "number", required: false }); await fetch("/api/admin/trip_stops", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ row: { id: st.id, status: "DA_GIAO", arrived_at: new Date().toISOString(), left_at: new Date().toISOString(), temp_at_delivery: temp ? Number(temp) : null, pod_by: sess.staffId } }) }); stops.reload(); trips.reload(); }}>✓ đã giao (POD)</button>}</td></tr>)}</tbody></table>{stops.rows?.length === 0 && <div className="text-sm text-stone-500">Chưa có điểm dừng.</div>}</div>}</div></div></div>}
      {tab === "ncc" && <div className="card p-0 overflow-auto"><div className="px-3 py-2 bg-stone-100 rounded-t-2xl font-bold">Scorecard nhà cung cấp 12 tháng — đúng hạn 30 · đủ đơn 20 · có COA 25 · QC đạt 25 (điểm/100); NCC phê duyệt & hạn rà soát (ISO22000/GlobalG.A.P: NCC được phê duyệt)</div><table className="tbl text-sm"><thead><tr><th className="pl-3">NCC</th><th>Duyệt</th><th>Rà soát</th><th className="text-right">PO</th><th className="text-right">Chi</th><th className="text-right">Đúng hạn %</th><th className="text-right">Đủ đơn %</th><th className="text-right">Lô</th><th className="text-right">COA %</th><th className="text-right">QC đạt %</th><th className="text-right">Điểm</th></tr></thead><tbody>{(score.rows ?? []).map((r) => <tr key={String(r.supplier_id)} className={Number(r.score) < 60 ? "bg-red-50" : Number(r.score) >= 85 ? "bg-emerald-50" : ""}><td className="pl-3">{String(r.name)}</td><td>{r.approved ? "✓" : <span className="text-red-700">chưa</span>}</td><td className="text-xs">{String(r.review_due ?? "")}</td><td className="text-right">{String(r.n_po ?? 0)}</td><td className="text-right">{fmt.vnd(Number(r.spend ?? 0))}</td><td className="text-right">{String(r.on_time_pct ?? "—")}</td><td className="text-right">{String(r.fulfilled_pct ?? "—")}</td><td className="text-right">{String(r.n_lots ?? 0)}</td><td className="text-right">{String(r.coa_pct ?? "—")}</td><td className="text-right">{String(r.qc_pass_pct ?? "—")}</td><td className="text-right font-bold">{String(r.score)}</td></tr>)}</tbody></table><div className="p-2 text-xs text-stone-500">Đúng hạn cần điền purchase_orders.expected_at & received_at khi nhận hàng (form nhận PO ở KTT).</div></div>}
      {tab === "the" && <div className="card p-0 overflow-auto"><div className="px-3 py-2 bg-stone-100 rounded-t-2xl font-bold flex items-center gap-2">Thẻ kho theo lô (số dư lũy kế từng lô) <select className="input !w-72 !py-1 font-normal" value={cardSku ?? ""} onChange={(e) => setCardSku(e.target.value || null)}><option value="">Chọn mặt hàng</option>{(products.rows ?? []).map((p) => <option key={String(p.sku)} value={String(p.sku)}>{String(p.name)}</option>)}</select>{cardSku && <a className="ml-auto underline text-sm font-normal" href={`/api/exports/stock-card?sku=${cardSku}`}>xuất CSV</a>}</div><table className="tbl text-sm"><thead><tr><th className="pl-3">Lúc</th><th>Kho</th><th>Lô</th><th>Bin</th><th>Lý do</th><th>Đối tác/nơi</th><th className="text-right">Nhập</th><th className="text-right">Xuất</th><th className="text-right">Đơn giá</th><th className="text-right">Số dư lô</th><th>Người</th></tr></thead><tbody>{(card.rows ?? []).map((r, i) => <tr key={i}><td className="pl-3 text-xs">{fmt.dt(String(r.ts))}</td><td>{String(r.warehouse_code)}</td><td className="font-mono text-xs">{String(r.lot_id ?? "")}</td><td className="font-mono text-xs">{String(r.bin_id ?? "")}</td><td>{String(r.reason)}</td><td className="text-xs">{String(r.from_to ?? "")}</td><td className="text-right">{Number(r.direction) === 1 ? fmt.n(Number(r.qty)) : ""}</td><td className="text-right">{Number(r.direction) === -1 ? fmt.n(Number(r.qty)) : ""}</td><td className="text-right">{r.unit_cost ? fmt.vnd(Number(r.unit_cost)) : ""}</td><td className="text-right font-bold">{fmt.n(Number(r.balance))}</td><td className="text-xs">{String(r.created_by ?? "")}</td></tr>)}</tbody></table>{!cardSku && <div className="p-3 text-sm text-stone-500">Chọn mặt hàng để xem thẻ kho.</div>}</div>}
      {tab === "giatri" && <div className="card p-0 overflow-auto"><div className="px-3 py-2 bg-slate-100 rounded-t-xl font-bold">Giá trị tồn kho (giá bình quân lô / giá mua gần nhất) — tổng {fmt.vnd((sval.rows ?? []).reduce((a, r) => a + Number(r.value), 0))} · đầu vào {fmt.vnd((sval.rows ?? []).filter((r) => r.block === "DAU_VAO").reduce((a, r) => a + Number(r.value), 0))} · đầu ra {fmt.vnd((sval.rows ?? []).filter((r) => r.block === "DAU_RA").reduce((a, r) => a + Number(r.value), 0))}</div><table className="tbl text-sm"><thead><tr><th className="pl-3">Kho</th><th>Khối</th><th>Nhóm</th><th>Mặt hàng</th><th className="text-right">SL</th><th className="text-right">Giá trị</th></tr></thead><tbody>{(sval.rows ?? []).map((r, i) => <tr key={i}><td className="pl-3">{String(r.warehouse_code)}</td><td className="text-xs">{String(r.block)}</td><td className="text-xs">{String(r.group_name ?? "")}</td><td>{String(r.product_name)}</td><td className="text-right">{fmt.n(Number(r.qty))} {String(r.unit)}</td><td className="text-right font-semibold">{fmt.vnd(Number(r.value))}</td></tr>)}</tbody></table></div>}
      {tab === "so" && (<div className="space-y-3">
        <div className="card p-0 overflow-auto"><div className="px-3 py-2 font-bold bg-stone-100 rounded-t-2xl">Ngày-tồn theo mặt hàng (tồn / tiêu thụ TB 14 ngày) — R7: ≤35%/nguồn, tồn 60 ngày</div><table className="tbl"><thead><tr><th className="pl-3">Hàng</th><th className="text-right">Tồn</th><th className="text-right">Dùng/ngày</th><th className="text-right">Ngày còn</th></tr></thead><tbody>{(dos.rows ?? []).map((r, i) => <tr key={i}><td className="pl-3">{String(r.product_name)}</td><td className="text-right">{fmt.n(r.qty)}</td><td className="text-right">{fmt.n(r.use_per_day, 1)}</td><td className={`text-right font-bold ${r.days != null && Number(r.days) < 30 ? "text-red-700" : r.days != null && Number(r.days) < 45 ? "text-amber-700" : ""}`}>{r.days != null ? fmt.n(r.days) : "—"}</td></tr>)}</tbody></table></div>
        {sku && <div className="card"><AnyChart title={`Biến động ${sku} (nhập +, xuất −) theo kỳ`} table="inventory_moves" col="qty" dim="direction" filters={{ sku }} chart="bar" height={220} compare /></div>}
        {sku && <div className="card p-0 overflow-auto"><div className="px-3 py-2 font-bold bg-stone-100 rounded-t-2xl">Thẻ kho {sku}</div><table className="tbl"><thead><tr><th className="pl-3">Lúc</th><th>Kho</th><th>Lô</th><th>±</th><th>Lý do</th><th>Điểm ghi</th><th className="text-right">Tồn sau</th></tr></thead><tbody>{(ledger.rows ?? []).map((r) => <tr key={String(r.id)}><td className="pl-3">{fmt.dt(r.ts)}</td><td>{String(r.warehouse_id).slice(-2)}</td><td className="font-mono text-xs">{String(r.lot_id ?? "")}</td><td className={Number(r.direction) > 0 ? "text-green-700" : "text-red-700"}>{Number(r.direction) > 0 ? "+" : "−"}{fmt.n(r.qty, 1)}</td><td>{String(r.reason)}</td><td className="text-xs">{String(r.weigh_point ?? "")}</td><td className="text-right font-bold">{fmt.n(r.balance_after, 1)}</td></tr>)}</tbody></table></div>}
      </div>)}
    </div>);
}
function AdjForm({ warehouses, products, onDone }: { sess: Sess; warehouses: Record<string, unknown>[]; products: Record<string, unknown>[]; onDone: () => void }) {
  const [wh, setWh] = useState(""); const [sku, setSku] = useState(""); const [delta, setDelta] = useState(""); const [reason, setReason] = useState("");
  return (<div className="flex flex-wrap gap-2 items-center">
    <select className="input !w-auto" value={wh} onChange={(e) => setWh(e.target.value)}><option value="">Kho</option>{warehouses.map((w) => <option key={String(w.id)} value={String(w.id)}>{String(w.code)}</option>)}</select>
    <select className="input !w-auto" value={sku} onChange={(e) => setSku(e.target.value)}><option value="">Hàng</option>{products.map((p) => <option key={String(p.sku)} value={String(p.sku)}>{String(p.name)}</option>)}</select>
    <input className="input !w-32" type="number" placeholder="± số lượng" aria-label="± số lượng" value={delta} onChange={(e) => setDelta(e.target.value)} />
    <input className="input !w-64" placeholder="Lý do (bắt buộc)" aria-label="Lý do (bắt buộc)" value={reason} onChange={(e) => setReason(e.target.value)} />
    <button className="btn-secondary !py-2" onClick={async () => { if (!wh || !sku || !delta || reason.length < 3) { toast.err("Thiếu thông tin"); return; } const r = await fetch("/api/events/adjustments", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ client_ref: crypto.randomUUID(), target_table: "inventory_moves", warehouse_id: wh, sku, delta: Number(delta), reason }) }); const j = await r.json(); if (j.results?.[0]?.status !== "CREATED") toast.err(JSON.stringify(j)); setDelta(""); setReason(""); onDone(); }}>Tạo phiếu điều chỉnh</button>
  </div>);
}
