"use client";
import { useMemo, useState } from "react";
import { useData, fmt } from "@/lib/client";
import type { Sess } from "@/components/Shell";
import AnyChart from "@/components/AnyChart";
import { usePrompt } from "@/components/ui/PromptDialog";
type R = Record<string, unknown>;
const adminPost = (t: string, row: R) => fetch(`/api/admin/${t}`, { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ row }) }).then((r) => r.json());
const STAGES = ["MOI", "LIEN_HE", "BAO_GIA", "DAM_PHAN", "THANG", "THUA"];
/** CRM pipeline (kéo qua giai đoạn) · lead → đối tác */
export function CrmPanel({ sess }: { sess: Sess }) {
  const leads = useData("crm_leads"); const channels = useData("sales_channels"); const [f, setF] = useState<R | null>(null); const [msg, setMsg] = useState("");
  const { prompt, promptElement } = usePrompt();
  const L = leads.rows ?? []; const byStage = useMemo(() => STAGES.map((s) => ({ s, rows: L.filter((l) => l.stage === s) })), [L]);
  return (<div className="space-y-3">{promptElement}
    <div className="flex items-center gap-2"><b>Pipeline ({L.length} lead · {fmt.vnd(L.filter((l) => !["THUA"].includes(String(l.stage))).reduce((a, l) => a + Number(l.est_value ?? 0), 0))})</b><button className="ml-auto btn-secondary !py-1 !px-3 !text-sm" onClick={() => setF({ stage: "MOI", source: "GIOI_THIEU", owner_id: sess.staffId })}>＋ Lead</button><a className="underline text-sm" href="/quan-tri?t=crm_leads&tab=nhap">nhập CSV</a></div>
    {msg && <div className="text-sm text-green-800">{msg}</div>}
    {f && <div className="card grid sm:grid-cols-3 lg:grid-cols-6 gap-2"><input className="input" placeholder="Tên" aria-label="Tên" value={String(f.name ?? "")} onChange={(e) => setF({ ...f, name: e.target.value })} /><input className="input" placeholder="Công ty" aria-label="Công ty" value={String(f.company ?? "")} onChange={(e) => setF({ ...f, company: e.target.value })} /><input className="input" placeholder="SĐT" aria-label="SĐT" value={String(f.phone ?? "")} onChange={(e) => setF({ ...f, phone: e.target.value })} /><select className="input" value={String(f.source)} onChange={(e) => setF({ ...f, source: e.target.value })}>{["HOI_CHO", "GIOI_THIEU", "WEB", "ZALO", "GOI_DEN", "SU_KIEN", "THAM_TRAI"].map((s) => <option key={s}>{s}</option>)}</select><select className="input" value={String(f.channel_code ?? "")} onChange={(e) => setF({ ...f, channel_code: e.target.value })}><option value="">Kênh</option>{(channels.rows ?? []).map((c) => <option key={String(c.code)} value={String(c.code)}>{String(c.name)}</option>)}</select><input className="input" type="number" placeholder="Giá trị ước (đ)" aria-label="Giá trị ước (đ)" value={String(f.est_value ?? "")} onChange={(e) => setF({ ...f, est_value: Number(e.target.value) })} /><input className="input lg:col-span-3" placeholder="Quan tâm (SKU/dịch vụ)" aria-label="Quan tâm (SKU/dịch vụ)" value={String(f.interest ?? "")} onChange={(e) => setF({ ...f, interest: e.target.value })} /><input className="input lg:col-span-2" placeholder="Việc kế tiếp" aria-label="Việc kế tiếp" value={String(f.next_action ?? "")} onChange={(e) => setF({ ...f, next_action: e.target.value })} /><div className="flex gap-2"><button className="btn-primary !py-2" onClick={async () => { const j = await adminPost("crm_leads", f); setMsg(j.ok ? "Đã lưu lead" : `${j.error}: ${j.detail ?? ""}`); setF(null); leads.reload(); }}>Lưu</button><button className="btn-secondary !py-2" onClick={() => setF(null)}>Hủy</button></div></div>}
    <div className="grid grid-cols-2 md:grid-cols-6 gap-2">{byStage.map(({ s, rows }) => <div key={s} className="card !p-2 min-h-[120px]"><div className={`text-xs font-bold ${s === "THANG" ? "text-green-700" : s === "THUA" ? "text-red-700" : ""}`}>{s} ({rows.length})</div>{rows.map((l) => <div key={String(l.id)} className="mt-1 rounded-lg bg-stone-50 p-1.5 text-xs cursor-pointer hover:bg-green-50" onClick={() => setF({ ...l })}><b>{String(l.name)}</b> {l.company ? `· ${l.company}` : ""}<div className="text-stone-500">{fmt.vnd(l.est_value)} · {String(l.owner_name ?? "")}</div><div className="flex gap-1 mt-1">{STAGES.indexOf(s) > 0 && <button className="underline" onClick={async (e) => { e.stopPropagation(); await adminPost("crm_leads", { id: l.id, stage: STAGES[STAGES.indexOf(s) - 1] }); leads.reload(); }}>◀</button>}{STAGES.indexOf(s) < 4 && <button className="underline" onClick={async (e) => { e.stopPropagation(); await adminPost("crm_leads", { id: l.id, stage: STAGES[STAGES.indexOf(s) + 1] }); leads.reload(); }}>▶</button>}{s !== "THUA" && s !== "THANG" && <button className="underline text-red-700 ml-auto" onClick={async (e) => { e.stopPropagation(); const reason = await prompt({ title: "Đánh dấu thua", label: "Lý do thua", type: "text", required: false }); await adminPost("crm_leads", { id: l.id, stage: "THUA", lost_reason: reason ?? "" }); leads.reload(); }}>thua</button>}{s === "DAM_PHAN" && <button className="underline text-green-700 ml-auto" onClick={async (e) => { e.stopPropagation(); const j = await adminPost("partners", { name: l.company ?? l.name, kind: "KH", phone: l.phone, active: true, approved: true }); if (j.ok) { await adminPost("crm_leads", { id: l.id, stage: "THANG", partner_id: j.row?.id }); setMsg(`Đã tạo đối tác ${String(j.row?.id)}`); } leads.reload(); }}>thắng → đối tác</button>}</div></div>)}</div>)}</div>
  </div>);
}
/** POS cửa hàng: mở ca → thêm hàng → khuyến mãi → thanh toán (→ sales tự sinh) → chốt ca */
export function PosPanel({ sess }: { sess: Sess }) {
  const shifts = useData("pos_shifts"); const products = useData("products"); const promos = useData("promotions"); const receipts = useData("pos_receipts");
  const { prompt, promptElement } = usePrompt();
  const [cart, setCart] = useState<{ sku: string; name: string; qty: number; price: number }[]>([]); const [sku, setSku] = useState(""); const [pay, setPay] = useState("TM"); const [promo, setPromo] = useState(""); const [msg, setMsg] = useState("");
  const open = (shifts.rows ?? []).find((s) => s.status === "MO"); const P = (products.rows ?? []).filter((p) => ["THANH_PHAM", "LANH", "DICH_VU"].includes(String(p.kind)));
  const sub = cart.reduce((a, l) => a + l.qty * l.price, 0); const pr = (promos.rows ?? []).find((p) => p.id === promo); const disc = pr ? (pr.kind === "GIAM_PCT" ? (sub * Number(pr.value)) / 100 : pr.kind === "GIAM_TIEN" ? Number(pr.value) : 0) : 0; const total = Math.max(0, sub - disc);
  const add = async () => { const p = P.find((x) => x.sku === sku); if (!p) return; const raw = await prompt({ title: "Giá bán", label: `Giá bán ${String(p.name)}`, type: "number", min: 0, unit: "đ" }); if (raw == null) return; setCart([...cart, { sku: String(p.sku), name: String(p.name), qty: 1, price: Number(raw) }]); };
  return (<div className="grid md:grid-cols-3 gap-3">{promptElement}
    <div className="md:col-span-2 space-y-2">
      <div className="card flex items-center gap-2 flex-wrap"><b>Ca bán hàng:</b>{open ? <span className="b-grn">MỞ từ {fmt.dt(open.opened_at)} · két đầu {fmt.vnd(open.cash_open)}</span> : <span className="b-gray">chưa mở</span>}{!open ? <button className="btn-secondary !py-1 !px-3 !text-sm" onClick={async () => { const raw = await prompt({ title: "Mở ca bán hàng", label: "Tiền két đầu ca", type: "number", min: 0, unit: "đ", defaultValue: 0 }); if (raw == null) return; await adminPost("pos_shifts", { id: `${sess.farmId}-POS-${new Date().toISOString().slice(2, 16).replace(/[-:T]/g, "")}`, opened_by: sess.staffId, cash_open: Number(raw), status: "MO" }); shifts.reload(); }}>Mở ca</button> : <button className="btn-secondary !py-1 !px-3 !text-sm ml-auto" onClick={async () => { const raw = await prompt({ title: "Chốt ca bán hàng", label: "Đếm tiền két cuối ca", type: "number", min: 0, unit: "đ", defaultValue: 0 }); if (raw == null) return; const cash = Number(raw); const expected = Number(open.cash_open ?? 0) + (receipts.rows ?? []).filter((r) => r.shift_id === open.id && r.payment === "TM").reduce((a, r) => a + Number(r.total), 0); await adminPost("pos_shifts", { id: open.id, closed_by: sess.staffId, closed_at: new Date().toISOString(), cash_close: cash, cash_expected: expected, diff: cash - expected, status: "DONG" }); setMsg(`Chốt ca: chênh ${fmt.vnd(cash - expected)}`); shifts.reload(); }}>Chốt ca</button>}</div>
      <div className="card"><div className="flex gap-2"><select className="input" value={sku} onChange={(e) => setSku(e.target.value)}><option value="">Chọn hàng…</option>{P.map((p) => <option key={String(p.sku)} value={String(p.sku)}>{String(p.name)} ({String(p.sku)})</option>)}</select><button className="btn-secondary !py-2" onClick={add} disabled={!open}>＋</button></div>
        <table className="tbl text-sm mt-2"><tbody>{cart.map((l, i) => <tr key={i}><td className="pl-2">{l.name}</td><td><input className="input !w-20 !py-1" type="number" value={l.qty} onChange={(e) => setCart(cart.map((x, j) => j === i ? { ...x, qty: Number(e.target.value) } : x))} /></td><td className="text-right">{fmt.vnd(l.price)}</td><td className="text-right font-bold">{fmt.vnd(l.qty * l.price)}</td><td><button className="text-red-700" onClick={() => setCart(cart.filter((_, j) => j !== i))}>✕</button></td></tr>)}</tbody></table>
        <div className="flex flex-wrap gap-2 items-center mt-2 text-sm"><select className="input !w-56 !py-1" value={promo} onChange={(e) => setPromo(e.target.value)}><option value="">Không KM</option>{(promos.rows ?? []).filter((p) => p.active).map((p) => <option key={String(p.id)} value={String(p.id)}>{String(p.name)}</option>)}</select><select className="input !w-32 !py-1" value={pay} onChange={(e) => setPay(e.target.value)}>{["TM", "CK", "QR", "THE"].map((p) => <option key={p}>{p}</option>)}</select><span className="ml-auto">Tạm tính {fmt.vnd(sub)} − KM {fmt.vnd(disc)} = <b className="text-lg">{fmt.vnd(total)}</b></span>
          <button className="btn-primary !py-2" disabled={!open || !cart.length} onClick={async () => { const j = await fetch("/api/events/pos_receipts", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ client_ref: crypto.randomUUID(), shift_id: open?.id, receipt_no: `HD-${Date.now().toString().slice(-8)}`, lines: cart.map((l) => ({ ...l, amount: l.qty * l.price })), subtotal: sub, discount: disc, promotion_id: promo || null, total, payment: pay, paid: total }) }).then((r) => r.json()); const r = j.results?.[0]; setMsg(r?.status === "CREATED" ? `Đã thanh toán ${fmt.vnd(total)} — doanh thu đã vào sổ bán hàng` : JSON.stringify(r?.errors ?? j)); setCart([]); receipts.reload(); }}>Thanh toán</button></div></div>
      {msg && <div className="text-sm text-green-800">{msg}</div>}
    </div>
    <div className="space-y-2"><div className="card p-0 overflow-auto"><div className="px-3 py-2 bg-stone-100 rounded-t-2xl font-bold text-sm">Hóa đơn gần đây</div><table className="tbl text-xs"><tbody>{(receipts.rows ?? []).slice(0, 20).map((r) => <tr key={String(r.id)}><td className="pl-2">{fmt.dt(r.ts)}</td><td>{String(r.receipt_no)}</td><td>{String(r.payment)}</td><td className="text-right font-bold">{fmt.vnd(r.total)}</td></tr>)}</tbody></table></div><div className="card"><AnyChart title="Doanh thu POS/ngày" table="pos_receipts" col="total" bucket="day" height={160} /></div><div className="text-xs text-stone-500">Khuyến mãi: <a className="underline" href="/quan-tri?t=promotions">tạo/sửa</a> · Ca: <a className="underline" href="/quan-tri?t=pos_shifts">lịch sử</a></div></div>
  </div>);
}
export function KenhPanel() {
  const rows = useData("sales_by_channel"); const ch = useData("sales_channels");
  return (<div className="grid md:grid-cols-2 gap-3"><div className="card"><AnyChart title="Doanh thu theo kênh (đ)" table="sales" col="amount" dim="channel_code" bucket="month" from={new Date(Date.now() - 180 * 86400e3).toISOString().slice(0, 10)} height={260} compare /></div><div className="card p-0 overflow-auto"><div className="px-3 py-2 bg-stone-100 rounded-t-2xl font-bold">Kênh bán ({(ch.rows ?? []).length}) · <a className="underline text-sm font-normal" href="/quan-tri?t=sales_channels">sửa</a></div><table className="tbl text-sm"><tbody>{(ch.rows ?? []).map((c) => { const t = (rows.rows ?? []).filter((r) => r.channel_code === c.code).reduce((a, r) => a + Number(r.amount), 0); return <tr key={String(c.code)}><td className="pl-3 font-mono">{String(c.code)}</td><td>{String(c.name)}</td><td className="text-xs">{String(c.kind)}</td><td className="text-right font-bold">{fmt.vnd(t)}</td></tr>; })}</tbody></table></div></div>);
}
