"use client";
import { useState } from "react";
import { useData, act, fmt } from "@/lib/client";
import type { Sess } from "@/components/Shell";
import Tabs from "@/components/Tabs";
import { BarChart, Bar, LineChart, Line, PieChart, Pie, Cell, XAxis, YAxis, Tooltip, Legend, CartesianGrid, ResponsiveContainer } from "recharts";
type R = Record<string, unknown>;
const COL = ["#059669", "#0ea5e9", "#f59e0b", "#8b5cf6", "#ef4444", "#14b8a6", "#64748b", "#84cc16"];
const CH = ["FACEBOOK", "ZALO", "TIKTOK", "YOUTUBE", "WEBSITE", "EMAIL", "BAO_CHI", "SU_KIEN", "POS", "GOOGLE"];
const KIND = ["BAI_VIET", "VIDEO", "LIVE", "EVENT", "PR", "EMAIL"];
const dm = (d: unknown) => new Date(String(d)).toLocaleDateString("vi-VN", { day: "2-digit", month: "2-digit" });
const ST_LABEL: Record<string, string> = { Y_TUONG: "Ý tưởng", DANG_LAM: "Đang làm", CHO_DUYET: "Chờ duyệt", DUYET: "Đã duyệt", DA_DANG: "Đã đăng", HUY: "Hủy" };
/** MARKETING – TRUYỀN THÔNG (KDM): chiến dịch → lịch nội dung → duyệt (người khác) → đăng → đo → gắn lead/đơn/booking → ROI · thương hiệu · lắng nghe & khủng hoảng */
export default function Marketing({ sess }: { sess: Sess }) {
  const [tab, setTab] = useState<"tq" | "cd" | "lich" | "th" | "tt">((typeof window !== "undefined" && (new URLSearchParams(window.location.search).get("tab") as "tq" | null)) || "tq");
  const camps = useData<R>("mkt_campaigns"); const contents = useData<R>("mkt_contents"); const weekly = useData<R>("mkt_weekly"); const leads = useData<R>("leads_by_channel"); const assets = useData<R>("mkt_assets"); const mentions = useData<R>("mkt_mentions"); const staff = useData<R>("staff_all");
  const [msg, setMsg] = useState(""); const canLead = ["tech_head", "team_lead", "director", "owner"].includes(sess.role); const canWrite = canLead || sess.dept === "KDM" || sess.role === "worker";
  const reload = () => { camps.reload(); contents.reload(); weekly.reload(); mentions.reload(); assets.reload(); };
  const C = camps.rows ?? []; const K = contents.rows ?? []; const M = mentions.rows ?? [];
  const spend = C.reduce((a, c) => a + Number(c.content_cost ?? 0), 0); const rev = C.reduce((a, c) => a + Number(c.revenue ?? 0) + Number(c.booking_revenue ?? 0), 0); const nLeads = C.reduce((a, c) => a + Number(c.leads ?? 0), 0);
  const weekData = (() => { const ws = [...new Set((weekly.rows ?? []).map((r) => String(r.week)))].sort(); return ws.map((w) => { const o: R = { week: dm(w) }; let reach = 0, posted = 0, planned = 0, cost = 0; for (const r of (weekly.rows ?? []).filter((x) => String(x.week) === w)) { reach += Number(r.reach); posted += Number(r.posted); planned += Number(r.planned); cost += Number(r.cost); } return { ...o, reach, posted, planned, cost }; }); })();
  const chanData = (() => { const m = new Map<string, number>(); for (const r of weekly.rows ?? []) m.set(String(r.channel), (m.get(String(r.channel)) ?? 0) + Number(r.reach)); return [...m.entries()].map(([name, value]) => ({ name, value })); })();
  const leadData = (() => { const m = new Map<string, { leads: number; won: number }>(); for (const r of leads.rows ?? []) { const o = m.get(String(r.source)) ?? { leads: 0, won: 0 }; o.leads += Number(r.leads); o.won += Number(r.won); m.set(String(r.source), o); } return [...m.entries()].map(([name, v]) => ({ name, ...v })); })();
  return <div className="space-y-3">
    <Tabs items={[["tq", "📊 Tổng quan"], ["cd", `Chiến dịch & ROI (${C.length})`], ["lich", `Lịch nội dung (${K.filter((k) => k.status !== "DA_DANG" && k.status !== "HUY").length} chưa đăng)`], ["th", `Thương hiệu · tài sản (${(assets.rows ?? []).length})`], ["tt", `Lắng nghe & khủng hoảng (${M.filter((m) => m.status === "MOI").length} mới)`]]} value={tab} onChange={(k) => setTab(k as typeof tab)} />
    {msg && <div className="text-sm text-emerald-800">{msg}</div>}
    {tab === "tq" && <div className="space-y-3">
      <div className="grid grid-cols-2 md:grid-cols-5 gap-2">{[["Chi phí nội dung 6 th", fmt.n(spend)], ["Doanh thu gắn chiến dịch", fmt.n(rev)], ["ROAS", spend ? (rev / spend).toFixed(1) + "×" : "—"], ["Lead từ chiến dịch", nLeads], ["Chi phí / lead", nLeads ? fmt.n(spend / nLeads) : "—"]].map(([l, v]) => <div key={String(l)} className="card"><div className="text-xs text-slate-500">{l}</div><div className="text-2xl font-black">{String(v)}</div></div>)}</div>
      <div className="grid md:grid-cols-2 gap-3">
        <div className="card"><div className="text-sm font-bold">Bài đăng vs kế hoạch & tiếp cận theo tuần</div><div style={{ height: 260 }}><ResponsiveContainer><BarChart data={weekData}><CartesianGrid strokeDasharray="3 3" /><XAxis dataKey="week" tick={{ fontSize: 10 }} /><YAxis yAxisId="l" tick={{ fontSize: 10 }} /><YAxis yAxisId="r" orientation="right" tick={{ fontSize: 10 }} /><Tooltip /><Legend wrapperStyle={{ fontSize: 11 }} /><Bar yAxisId="l" dataKey="planned" name="Kế hoạch" fill="#cbd5e1" /><Bar yAxisId="l" dataKey="posted" name="Đã đăng" fill="#059669" /><Line yAxisId="r" type="monotone" dataKey="reach" name="Tiếp cận" stroke="#0ea5e9" /></BarChart></ResponsiveContainer></div></div>
        <div className="card"><div className="text-sm font-bold">Tiếp cận theo kênh (12 tuần)</div><div style={{ height: 260 }}><ResponsiveContainer><PieChart><Pie data={chanData} dataKey="value" nameKey="name" outerRadius={90} label={(e) => String(e.name)}>{chanData.map((_, i) => <Cell key={i} fill={COL[i % COL.length]} />)}</Pie><Tooltip /></PieChart></ResponsiveContainer></div></div>
        <div className="card md:col-span-2"><div className="text-sm font-bold">Lead theo nguồn (12 tháng) — thắng / tổng</div><div style={{ height: 240 }}><ResponsiveContainer><BarChart data={leadData}><CartesianGrid strokeDasharray="3 3" /><XAxis dataKey="name" tick={{ fontSize: 10 }} /><YAxis tick={{ fontSize: 10 }} /><Tooltip /><Legend wrapperStyle={{ fontSize: 11 }} /><Bar dataKey="leads" name="Lead" fill="#0ea5e9" /><Bar dataKey="won" name="Thắng" fill="#059669" /></BarChart></ResponsiveContainer></div></div>
      </div>
      <div className="card text-sm"><b>Nhịp làm việc phòng Marketing</b> (quy trình P-MK-01..03, GS kiểm được): thứ 6 lập lịch tuần sau theo kế hoạch bán/tour/mùa vụ → viết → <b>người khác duyệt</b> → đăng đúng giờ → đo sau 48h/7 ngày → báo cáo tuần; mọi phản hồi tiêu cực ghi trong ngày, mức CAO tự tạo việc KHẨN (xác minh 2h, phản hồi 24h). Chiến dịch có mã UTM/KM để lead–đơn–booking gắn nguồn → ROI thật.</div>
    </div>}
    {tab === "cd" && <div className="space-y-3">
      {canLead && <NewCampaign onDone={reload} />}
      <div className="card p-0 overflow-auto"><table className="tbl text-sm"><thead><tr><th className="pl-3">Mã · Tên</th><th>Kênh</th><th>Thời gian</th><th>TT</th><th className="text-right">Ngân sách</th><th className="text-right">Chi ND</th><th className="text-right">Bài</th><th className="text-right">Tiếp cận</th><th className="text-right">Lead</th><th className="text-right">Đơn</th><th className="text-right">Doanh thu</th><th className="text-right">Booking</th><th className="text-right">ROAS</th><th>Mục tiêu</th></tr></thead><tbody>
        {C.map((c) => { const cost = Number(c.content_cost); const r = Number(c.revenue) + Number(c.booking_revenue); const kt = (c.kpi_target ?? {}) as R; return <tr key={String(c.id)}><td className="pl-3"><b>{String(c.code)}</b> {String(c.name)}<div className="text-xs text-slate-500">{String(c.utm_code ?? "")}</div></td><td className="text-xs">{((c.channels as string[]) ?? []).join(", ")}</td><td className="text-xs">{fmt.d(c.starts_on)} → {fmt.d(c.ends_on)}</td><td className="text-xs">{canLead ? <select className="input !py-0 !text-xs" value={String(c.status)} onChange={async (e) => { await act("mkt_campaign", { id: c.id, status: e.target.value }); reload(); }}>{["NHAP", "DANG_CHAY", "TAM_DUNG", "XONG", "HUY"].map((s) => <option key={s}>{s}</option>)}</select> : String(c.status)}</td><td className="text-right">{fmt.n(c.budget)}</td><td className="text-right">{fmt.n(cost)}</td><td className="text-right">{String(c.posts)}</td><td className="text-right">{fmt.n(c.reach)}</td><td className="text-right">{String(c.leads)}{Number(kt.leads) ? <span className="text-slate-400">/{String(kt.leads)}</span> : ""}</td><td className="text-right">{String(c.orders)}{Number(kt.orders) ? <span className="text-slate-400">/{String(kt.orders)}</span> : ""}</td><td className="text-right">{fmt.n(c.revenue)}</td><td className="text-right">{String(c.bookings)} · {fmt.n(c.booking_revenue)}</td><td className={`text-right font-bold ${cost && r / cost >= 2 ? "text-emerald-700" : "text-amber-700"}`}>{cost ? (r / cost).toFixed(1) + "×" : "—"}</td><td className="text-xs">{Object.entries(kt).map(([k, v]) => `${k}:${String(v)}`).join(" ")}</td></tr>; })}</tbody></table></div>
    </div>}
    {tab === "lich" && <ContentCalendar rows={K} camps={C} sess={sess} canLead={canLead} canWrite={canWrite} onDone={reload} setMsg={setMsg} />}
    {tab === "th" && <div className="space-y-3">
      <div className="card text-sm"><b>Thương hiệu & tài sản truyền thông</b> — logo, bộ nhận diện, ảnh/video chuẩn, chứng nhận (bản dùng ngoài), FAQ/mẫu phản hồi. Chỉ dùng tài sản <b>đã duyệt</b> khi đăng. {canWrite && <AddAsset onDone={reload} />}</div>
      <div className="grid md:grid-cols-2 gap-2">{(assets.rows ?? []).map((a) => <div key={String(a.id)} className={`card ${a.approved ? "" : "opacity-70 ring-1 ring-amber-300"}`}><div className="flex items-center gap-2"><span className="text-xs rounded bg-slate-100 px-1.5">{String(a.kind)}</span><b>{String(a.title)}</b><span className="text-xs text-slate-500">{String(a.version ?? "")}</span>{a.approved ? <span className="b-grn ml-auto">đã duyệt</span> : canLead ? <button className="btn-secondary !py-0.5 !px-2 !text-xs ml-auto" onClick={async () => { await act("mkt_asset_approve", { id: a.id }); reload(); }}>Duyệt</button> : <span className="b-yel ml-auto">chưa duyệt</span>}</div><div className="text-xs text-slate-600 mt-1">{a.url ? <a className="underline" href={String(a.url)} target="_blank" rel="noreferrer">{String(a.url)}</a> : ""} · {((a.tags as string[]) ?? []).join(", ")}</div></div>)}</div>
    </div>}
    {tab === "tt" && <div className="space-y-3">
      <div className="card text-sm flex flex-wrap items-center gap-2"><b>Lắng nghe & khủng hoảng truyền thông (SOP-KD-05)</b><span className="text-xs text-slate-600">Ghi mọi bình luận/đánh giá/bài báo đáng chú ý trong ngày. Tiêu cực mức CAO/KHỦNG HOẢNG → tự tạo việc KHẨN cho trưởng KDM + báo GĐ: xác minh ≤2h, phản hồi công khai ≤24h, không tranh cãi/không xóa.</span>{canWrite && <AddMention onDone={reload} />}</div>
      <div className="card p-0 overflow-auto"><table className="tbl text-sm"><thead><tr><th className="pl-3">Lúc</th><th>Kênh</th><th>Nội dung</th><th>Cảm xúc</th><th>Mức</th><th>TT</th><th>Phản hồi</th><th></th></tr></thead><tbody>
        {M.map((m) => <tr key={String(m.id)} className={m.sentiment === "TIEU_CUC" && m.status === "MOI" ? "bg-red-50" : ""}><td className="pl-3 text-xs">{fmt.dt(m.ts)}</td><td className="text-xs">{String(m.channel)}</td><td className="max-w-md">{String(m.summary)}{m.source_url ? <a className="text-xs underline ml-1" href={String(m.source_url)} target="_blank" rel="noreferrer">link</a> : null}</td><td className="text-xs">{m.sentiment === "TIEU_CUC" ? <span className="b-red">tiêu cực</span> : m.sentiment === "TICH_CUC" ? <span className="b-grn">tích cực</span> : "trung tính"}</td><td className="text-xs">{String(m.severity)}</td><td className="text-xs">{String(m.status)}</td><td className="text-xs max-w-xs">{String(m.response ?? "")}</td><td className="whitespace-nowrap">{m.status !== "DONG" && canWrite && <><button className="btn-secondary !py-0.5 !px-2 !text-xs mr-1" onClick={async () => { const r = prompt("Nội dung phản hồi công khai"); if (r === null) return; await act("mkt_mention_update", { id: m.id, status: "DA_PHAN_HOI", response: r }); reload(); }}>Phản hồi</button><button className="text-xs underline" onClick={async () => { const n = prompt("Bài học rút ra"); if (n === null) return; await act("mkt_mention_update", { id: m.id, status: "DONG", note: n }); reload(); }}>đóng</button></>}</td></tr>)}</tbody></table></div>
    </div>}
    <div className="text-xs text-slate-500">Nhân sự KDM: {(staff.rows ?? []).filter((s) => s.dept === "KDM").map((s) => String(s.full_name)).join(", ") || "—"}</div>
  </div>;
}
function ContentCalendar({ rows, camps, sess, canLead, canWrite, onDone, setMsg }: { rows: R[]; camps: R[]; sess: Sess; canLead: boolean; canWrite: boolean; onDone: () => void; setMsg: (s: string) => void }) {
  const [f, setF] = useState<R | null>(null); const [view, setView] = useState<"list" | "week">("week");
  const upcoming = rows.filter((r) => new Date(String(r.planned_at)) >= new Date(Date.now() - 7 * 864e5)).sort((a, b) => String(a.planned_at).localeCompare(String(b.planned_at)));
  const weeks = (() => { const m = new Map<string, R[]>(); for (const r of upcoming) { const d = new Date(String(r.planned_at)); const mon = new Date(d); mon.setDate(d.getDate() - ((d.getDay() + 6) % 7)); const k = mon.toISOString().slice(0, 10); if (!m.has(k)) m.set(k, []); m.get(k)!.push(r); } return [...m.entries()].slice(0, 6); })();
  const setStatus = async (r: R, status: string) => { const extra: R = {}; if (status === "DUYET") extra.approved_by = sess.staffId; if (status === "DA_DANG") { const u = prompt("Link bài đã đăng"); if (u === null) return; extra.url = u; } if (status === "METRICS") { const s = prompt("Số đo: reach,clicks,likes,comments (phân cách dấu phẩy)", "1000,50,80,5"); if (!s) return; const [reach, clicks, likes, comments] = s.split(",").map(Number); await act("mkt_content", { id: r.id, metrics: { reach, clicks, likes, comments } }); onDone(); return; } const j = await act("mkt_content", { id: r.id, status, ...extra }); setMsg(j.error ? `${j.error}: ${j.detail ?? ""}` : "Đã cập nhật"); onDone(); };
  const Row = ({ r }: { r: R }) => <div className={`rounded-lg border p-2 text-xs ${r.status === "DA_DANG" ? "bg-emerald-50" : r.status === "CHO_DUYET" ? "bg-amber-50" : "bg-white"}`}><div className="flex items-center gap-1 flex-wrap"><span className="font-bold">{dm(r.planned_at)}</span><span className="rounded bg-slate-100 px-1">{String(r.channel)}</span><span className="rounded bg-slate-100 px-1">{String(r.kind)}</span><span className="ml-auto">{ST_LABEL[String(r.status)] ?? String(r.status)}</span></div><div className="font-semibold mt-0.5">{String(r.title)}</div><div className="text-slate-500">{String(r.campaign_name ?? "")} · {String(r.author_name ?? "")}{r.approved_by ? ` · duyệt: ${String(r.approver_name ?? r.approved_by)}` : ""}</div>{r.status === "DA_DANG" && <div className="text-slate-600">reach {String((r.metrics as R)?.reach ?? "—")} · click {String((r.metrics as R)?.clicks ?? "—")}{r.url ? <a className="underline ml-1" href={String(r.url)} target="_blank" rel="noreferrer">bài</a> : null}</div>}
    <div className="mt-1 flex flex-wrap gap-1">{canWrite && r.status === "Y_TUONG" && <button className="btn-secondary !py-0 !px-1.5 !text-[11px]" onClick={() => setStatus(r, "DANG_LAM")}>Bắt đầu</button>}{canWrite && r.status === "DANG_LAM" && <button className="btn-secondary !py-0 !px-1.5 !text-[11px]" onClick={() => setStatus(r, "CHO_DUYET")}>Gửi duyệt</button>}{canLead && r.status === "CHO_DUYET" && r.author_id !== sess.staffId && <button className="btn-primary !py-0 !px-1.5 !text-[11px]" onClick={() => setStatus(r, "DUYET")}>Duyệt</button>}{canLead && r.status === "CHO_DUYET" && r.author_id === sess.staffId && <span className="text-slate-400">người khác duyệt</span>}{canWrite && r.status === "DUYET" && <button className="btn-primary !py-0 !px-1.5 !text-[11px]" onClick={() => setStatus(r, "DA_DANG")}>Đã đăng</button>}{canWrite && r.status === "DA_DANG" && <button className="btn-secondary !py-0 !px-1.5 !text-[11px]" onClick={() => setStatus(r, "METRICS")}>Cập nhật số đo</button>}</div></div>;
  return <div className="space-y-3">
    <div className="flex items-center gap-2 flex-wrap"><button className={`btn-secondary !py-1 !text-xs ${view === "week" ? "!bg-emerald-100" : ""}`} onClick={() => setView("week")}>Theo tuần</button><button className={`btn-secondary !py-1 !text-xs ${view === "list" ? "!bg-emerald-100" : ""}`} onClick={() => setView("list")}>Danh sách</button>{canWrite && <button className="btn-primary !py-1 !text-xs" onClick={() => setF({ planned_at: new Date().toISOString().slice(0, 10), channel: "FACEBOOK", kind: "BAI_VIET", title: "", brief: "", campaign_id: "" })}>＋ Nội dung</button>}<span className="text-xs text-slate-500">Quy tắc: người viết ≠ người duyệt · đăng ≤30' so lịch · số đo sau 48h/7 ngày · chỉ dùng tài sản đã duyệt</span></div>
    {f && <div className="card grid sm:grid-cols-6 gap-2"><input className="input" type="date" value={String(f.planned_at)} onChange={(e) => setF({ ...f, planned_at: e.target.value })} /><select className="input" value={String(f.channel)} onChange={(e) => setF({ ...f, channel: e.target.value })}>{CH.map((c) => <option key={c}>{c}</option>)}</select><select className="input" value={String(f.kind)} onChange={(e) => setF({ ...f, kind: e.target.value })}>{KIND.map((c) => <option key={c}>{c}</option>)}</select><select className="input" value={String(f.campaign_id)} onChange={(e) => setF({ ...f, campaign_id: e.target.value })}><option value="">— chiến dịch —</option>{camps.map((c) => <option key={String(c.id)} value={String(c.id)}>{String(c.code)} {String(c.name)}</option>)}</select><input className="input sm:col-span-2" placeholder="Tiêu đề" value={String(f.title)} onChange={(e) => setF({ ...f, title: e.target.value })} /><input className="input sm:col-span-5" placeholder="Brief: thông điệp, hình/video cần, CTA, mã KM" value={String(f.brief)} onChange={(e) => setF({ ...f, brief: e.target.value })} /><div className="flex gap-1"><button className="btn-primary !py-1" onClick={async () => { const j = await act("mkt_content", { ...f, campaign_id: f.campaign_id || null }); setMsg(j.error ? String(j.error) : "Đã thêm vào lịch"); setF(null); onDone(); }}>Lưu</button><button className="btn-secondary !py-1" onClick={() => setF(null)}>Hủy</button></div></div>}
    {view === "week" ? <div className="grid md:grid-cols-3 gap-3">{weeks.map(([w, list]) => <div key={w} className="card"><div className="font-bold text-sm mb-1">Tuần {dm(w)} <span className="text-xs text-slate-500">({list.length} bài · {list.filter((r) => r.status === "DA_DANG").length} đã đăng)</span></div><div className="space-y-1">{list.map((r) => <Row key={String(r.id)} r={r} />)}</div></div>)}</div>
      : <div className="space-y-1">{upcoming.map((r) => <Row key={String(r.id)} r={r} />)}</div>}
  </div>;
}
function NewCampaign({ onDone }: { onDone: () => void }) {
  const [f, setF] = useState<R | null>(null);
  if (!f) return <button className="btn-primary !py-1 !text-xs" onClick={() => setF({ code: "MK-" + new Date().toISOString().slice(2, 7).replace("-", ""), name: "", objective: "", channels: "FACEBOOK,ZALO", audience: "", starts_on: new Date().toISOString().slice(0, 10), ends_on: new Date(Date.now() + 30 * 864e5).toISOString().slice(0, 10), budget: 0, kpi_leads: 50, kpi_orders: 30, kpi_revenue: 100000000 })}>＋ Chiến dịch</button>;
  return <div className="card grid sm:grid-cols-4 gap-2 text-sm"><input className="input" placeholder="Mã" value={String(f.code)} onChange={(e) => setF({ ...f, code: e.target.value })} /><input className="input sm:col-span-2" placeholder="Tên chiến dịch" value={String(f.name)} onChange={(e) => setF({ ...f, name: e.target.value })} /><input className="input" placeholder="Kênh (phẩy)" value={String(f.channels)} onChange={(e) => setF({ ...f, channels: e.target.value })} /><input className="input sm:col-span-2" placeholder="Mục tiêu" value={String(f.objective)} onChange={(e) => setF({ ...f, objective: e.target.value })} /><input className="input sm:col-span-2" placeholder="Đối tượng" value={String(f.audience)} onChange={(e) => setF({ ...f, audience: e.target.value })} /><input className="input" type="date" value={String(f.starts_on)} onChange={(e) => setF({ ...f, starts_on: e.target.value })} /><input className="input" type="date" value={String(f.ends_on)} onChange={(e) => setF({ ...f, ends_on: e.target.value })} /><input className="input" type="number" placeholder="Ngân sách" value={String(f.budget)} onChange={(e) => setF({ ...f, budget: e.target.value })} /><div className="flex gap-1 items-center text-xs">KPI: lead <input className="input !py-0 !w-14" value={String(f.kpi_leads)} onChange={(e) => setF({ ...f, kpi_leads: e.target.value })} /> đơn <input className="input !py-0 !w-14" value={String(f.kpi_orders)} onChange={(e) => setF({ ...f, kpi_orders: e.target.value })} /></div><div className="flex gap-1 sm:col-span-4"><button className="btn-primary !py-1" onClick={async () => { await act("mkt_campaign", { ...f, channels: String(f.channels).split(",").map((s) => s.trim().toUpperCase()).filter(Boolean), kpi_target: { leads: Number(f.kpi_leads), orders: Number(f.kpi_orders), revenue: Number(f.kpi_revenue) }, status: "DANG_CHAY" }); setF(null); onDone(); }}>Tạo & chạy</button><button className="btn-secondary !py-1" onClick={() => setF(null)}>Hủy</button></div></div>;
}
function AddAsset({ onDone }: { onDone: () => void }) {
  const [f, setF] = useState<R | null>(null);
  if (!f) return <button className="btn-secondary !py-1 !text-xs ml-2" onClick={() => setF({ kind: "HINH_ANH", title: "", url: "", tags: "" })}>＋ Tài sản</button>;
  return <span className="inline-flex flex-wrap gap-1 ml-2"><select className="input !py-1" value={String(f.kind)} onChange={(e) => setF({ ...f, kind: e.target.value })}>{["LOGO", "BO_NHAN_DIEN", "HINH_ANH", "VIDEO", "CHUNG_NHAN", "TAI_LIEU"].map((k) => <option key={k}>{k}</option>)}</select><input className="input !py-1" placeholder="Tên" value={String(f.title)} onChange={(e) => setF({ ...f, title: e.target.value })} /><input className="input !py-1" placeholder="Link" value={String(f.url)} onChange={(e) => setF({ ...f, url: e.target.value })} /><input className="input !py-1" placeholder="tags" value={String(f.tags)} onChange={(e) => setF({ ...f, tags: e.target.value })} /><button className="btn-primary !py-1 !text-xs" onClick={async () => { await act("mkt_asset", { ...f, tags: String(f.tags).split(",").map((s) => s.trim()).filter(Boolean) }); setF(null); onDone(); }}>Lưu</button></span>;
}
function AddMention({ onDone }: { onDone: () => void }) {
  const [f, setF] = useState<R | null>(null);
  if (!f) return <button className="btn-primary !py-1 !text-xs ml-auto" onClick={() => setF({ channel: "FACEBOOK", summary: "", source_url: "", sentiment: "TIEU_CUC", severity: "TRUNG" })}>＋ Ghi phản hồi</button>;
  return <span className="inline-flex flex-wrap gap-1 w-full"><select className="input !py-1" value={String(f.channel)} onChange={(e) => setF({ ...f, channel: e.target.value })}>{CH.map((c) => <option key={c}>{c}</option>)}</select><input className="input !py-1 flex-1" placeholder="Nội dung tóm tắt" value={String(f.summary)} onChange={(e) => setF({ ...f, summary: e.target.value })} /><input className="input !py-1" placeholder="Link" value={String(f.source_url)} onChange={(e) => setF({ ...f, source_url: e.target.value })} /><select className="input !py-1" value={String(f.sentiment)} onChange={(e) => setF({ ...f, sentiment: e.target.value })}><option value="TICH_CUC">Tích cực</option><option value="TRUNG_TINH">Trung tính</option><option value="TIEU_CUC">Tiêu cực</option></select><select className="input !py-1" value={String(f.severity)} onChange={(e) => setF({ ...f, severity: e.target.value })}>{["THAP", "TRUNG", "CAO", "KHUNG_HOANG"].map((s) => <option key={s}>{s}</option>)}</select><button className="btn-primary !py-1 !text-xs" onClick={async () => { if (!f.summary) return; await act("mkt_mention", f); setF(null); onDone(); }}>Ghi</button></span>;
}
