"use client";
import { useMemo, useState } from "react";
import { useData, act, fmt } from "@/lib/client";
import type { Sess } from "@/components/Shell";
import AnyChart from "@/components/AnyChart";
import { vietqr, vietqrImage, BANK_BINS } from "@/lib/vietqr";
import { solveRation, type Ingredient, type Constraint } from "@/lib/ration";
import { useConfirm } from "@/components/ui/ConfirmDialog";
import { DataBoundary } from "@/components/ui/DataBoundary";
type R = Record<string, unknown>;
const adminPost = (t: string, row: R) => fetch(`/api/admin/${t}`, { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ row }) }).then((r) => r.json());

/** KẾ TOÁN KÉP: sổ cái · cân đối phát sinh (tự hạch toán từ bán hàng/chi/mua) · VietQR thu tiền */
export function GlPanel({ sess }: { sess: Sess }) {
  const tb = useData("gl_trial_balance"); const led = useData("gl_ledger"); const acc = useData("gl_accounts"); const farms = useData("farms"); const [tab, setTab] = useState<"tb" | "ledger" | "qr">("tb"); const [amt, setAmt] = useState(0); const [memo, setMemo] = useState("");
  const f = (farms.rows ?? []).find((x) => x.id === sess.farmId); const bin = String(f?.bank_bin ?? ""); const acct = String(f?.bank_account ?? "").replace(/\s/g, "");
  const periods = [...new Set((tb.rows ?? []).map((r) => String(r.period)))].sort().reverse(); const [period, setPeriod] = useState<string>("");
  const cur = period || periods[0]; const rows = (tb.rows ?? []).filter((r) => String(r.period) === cur);
  const sum = (k: string) => rows.filter((r) => r.kind === k).reduce((a, r) => a + Number(r.debit) - Number(r.credit), 0);
  return (<div className="card space-y-2"><div className="flex items-center gap-2 flex-wrap"><b>Kế toán kép (GL) — hạch toán tự động, chuẩn TT200 rút gọn</b>{[["tb", "Cân đối phát sinh"], ["ledger", "Sổ cái"], ["qr", "VietQR thu tiền"]].map(([k, l]) => <button key={k} className={`px-3 py-1 rounded-lg text-sm min-h-[40px] ${tab === k ? "bg-brand-tok text-white" : "bg-surface border"}`} onClick={() => setTab(k as typeof tab)}>{l}</button>)}<a className="ml-auto underline text-sm" href="/quan-tri?t=journal_entries">bút toán</a><a className="underline text-sm" href="/api/admin/journal_entries?csv=1">xuất CSV (MISA/Fast import)</a></div>
    {tab === "tb" && <div><div className="flex gap-2 items-center text-sm"><span>Kỳ</span><select className="input !w-40 !py-1" value={cur ?? ""} onChange={(e) => setPeriod(e.target.value)}>{periods.map((p) => <option key={p} value={p}>{fmt.d(p)}</option>)}</select><span className="ml-auto">Doanh thu {fmt.vnd(-sum("DOANH_THU"))} · Chi phí {fmt.vnd(sum("CHI_PHI"))} · <b>Lãi/lỗ {fmt.vnd(-sum("DOANH_THU") - sum("CHI_PHI"))}</b></span></div><DataBoundary loading={tb.loading} error={tb.error} empty={!rows.length} onRetry={tb.reload} emptyText="Chưa có bút toán kỳ này."><table className="tbl text-sm mt-2"><thead><tr><th className="pl-2">TK</th><th>Tên</th><th>Loại</th><th className="text-right">Nợ</th><th className="text-right">Có</th><th className="text-right">Số dư</th></tr></thead><tbody>{rows.map((r) => <tr key={String(r.acct)}><td className="pl-2 font-mono">{String(r.acct)}</td><td>{String(r.name ?? "")}</td><td className="text-xs">{String(r.kind ?? "")}</td><td className="text-right">{fmt.vnd(r.debit)}</td><td className="text-right">{fmt.vnd(r.credit)}</td><td className="text-right font-bold">{fmt.vnd(Number(r.debit) - Number(r.credit))}</td></tr>)}</tbody></table></DataBoundary></div>}
    {tab === "ledger" && <div className="overflow-auto max-h-[60vh]"><table className="tbl text-xs"><thead><tr><th className="pl-2">Lúc</th><th>TK</th><th>Diễn giải</th><th className="text-right">Nợ</th><th className="text-right">Có</th><th>CC</th><th>Chứng từ</th></tr></thead><tbody>{(led.rows ?? []).map((r, i) => <tr key={i}><td className="pl-2">{fmt.dt(r.ts)}</td><td className="font-mono">{String(r.acct)}</td><td>{String(r.memo ?? "")}</td><td className="text-right">{Number(r.debit) ? fmt.vnd(r.debit) : ""}</td><td className="text-right">{Number(r.credit) ? fmt.vnd(r.credit) : ""}</td><td>{String(r.cc ?? "")}</td><td className="font-mono">{String(r.ref_table)}:{String(r.ref_id).slice(0, 8)}</td></tr>)}</tbody></table></div>}
    {tab === "qr" && <div className="grid md:grid-cols-2 gap-3"><div className="text-sm space-y-2"><div>Tài khoản nhận: <b>{bin ? BANK_BINS.find(([b]) => b === bin)?.[1] ?? bin : "chưa khai báo"}</b> · {acct || "—"} — khai ở <a className="underline" href={`/hq/trai/${sess.farmId}`}>Hồ sơ trại</a> (bank_bin, bank_account)</div><input className="input" type="number" placeholder="Số tiền" aria-label="Số tiền" value={amt || ""} onChange={(e) => setAmt(Number(e.target.value))} /><input className="input" placeholder="Nội dung (đơn/hóa đơn)" aria-label="Nội dung (đơn/hóa đơn)" value={memo} onChange={(e) => setMemo(e.target.value)} />{bin && acct && <div className="font-mono text-[10px] break-all bg-surface-2 p-2 rounded">{vietqr(bin, acct, amt || undefined, memo || undefined)}</div>}<div className="text-xs text-muted">Chuỗi EMVCo (VietQR/NAPAS 247) in lên hóa đơn/phiếu; khách quét bằng bất kỳ app ngân hàng nào — không tốn phí dịch vụ.</div></div><div className="text-center">{bin && acct ? <img src={vietqrImage(bin, acct, amt || undefined, memo || undefined, String(f?.legal_entity ?? "ITRAN FARM"))} alt="VietQR" className="mx-auto max-h-72" /> : <div className="text-muted">Khai báo BIN + số TK để hiện QR</div>}</div></div>}
    <div className="text-xs text-muted">Bút toán tự sinh: bán hàng (131/111/112 ↔ 511), chi đã thanh toán (627/641/642 ↔ 111), nhập mua (152 ↔ 331). Bút toán tay: Quản trị DL › journal_entries (cân Nợ = Có, không sửa — đảo bút toán bằng reversed_of).</div></div>);
}
/** CHẤM CÔNG · NGHỈ PHÉP · CÔNG THÁNG (check-in bằng app, có vị trí; tổ trưởng chấm hộ; nghỉ phép → Phê duyệt) */
export function AttendancePanel({ sess }: { sess: Sess }) {
  const my = useData("my_attendance"); const today = useData("attendance_today"); const month = useData("attendance_month"); const leaves = useData("leave_all"); const staff = useData("staff_all"); const deleg = useData("my_delegations"); const [msg, setMsg] = useState(""); const [lf, setLf] = useState<R | null>(null); const { confirm, confirmElement } = useConfirm();
  const mine = (today.rows ?? []).find((r) => r.staff_id === sess.staffId); const canMgr = ["team_lead", "tech_head", "director", "owner", "accountant"].includes(sess.role);
  const geo = () => new Promise<{ lat?: number; lng?: number }>((res) => { if (!navigator.geolocation) return res({}); navigator.geolocation.getCurrentPosition((p) => res({ lat: p.coords.latitude, lng: p.coords.longitude }), () => res({}), { timeout: 4000 }); });
  const checkIn = async () => { const g = await geo(); const j = await adminPost("attendance", { staff_id: sess.staffId, day: new Date().toISOString().slice(0, 10), check_in: new Date().toISOString(), shift: new Date().getHours() < 12 ? "SANG" : "CHIEU", ...g }); setMsg(j.ok ? "Đã chấm công vào" : `${j.error}: ${j.detail ?? ""}`); today.reload(); my.reload(); };
  const checkOut = async () => { if (!mine) return; const out = new Date(); const hrs = mine.check_in ? Math.round(((out.getTime() - new Date(String(mine.check_in)).getTime()) / 3.6e6) * 10) / 10 : null; const j = await adminPost("attendance", { id: mine.id, check_out: out.toISOString(), hours: hrs }); setMsg(j.ok ? `Đã chấm công ra (${hrs} giờ)` : `${j.error}`); today.reload(); my.reload(); };
  return (<div className="space-y-3">{confirmElement}
    <div className="card flex items-center gap-3 flex-wrap"><b>Chấm công hôm nay</b>{!mine ? <button className="btn-primary !py-2" onClick={checkIn}>▶ Vào ca</button> : !mine.check_out ? <><span className="b-grn">Vào {fmt.dt(mine.check_in)}</span><button className="btn-secondary !py-2" onClick={checkOut}>■ Ra ca</button></> : <span className="b-gray">Vào {fmt.dt(mine.check_in)} · ra {fmt.dt(mine.check_out)} · {String(mine.hours)} giờ</span>}<button className="btn-secondary !py-2 ml-auto" onClick={() => setLf({ kind: "PHEP", from_date: new Date().toISOString().slice(0, 10), to_date: new Date().toISOString().slice(0, 10), days: 1, delegate_id: "", handover_note: "" })}>＋ Xin nghỉ</button>{msg && <span className="text-sm text-brand">{msg}</span>}</div>
    {lf && <div className="card grid sm:grid-cols-5 gap-2"><select className="input" value={String(lf.kind)} onChange={(e) => setLf({ ...lf, kind: e.target.value })}>{["PHEP", "OM", "VIEC_RIENG", "KHONG_LUONG", "THAI_SAN"].map((k) => <option key={k}>{k}</option>)}</select><input className="input" type="date" value={String(lf.from_date)} onChange={(e) => setLf({ ...lf, from_date: e.target.value })} /><input className="input" type="date" value={String(lf.to_date)} onChange={(e) => setLf({ ...lf, to_date: e.target.value, days: Math.max(1, Math.round((new Date(e.target.value).getTime() - new Date(String(lf.from_date)).getTime()) / 86400e3) + 1) })} /><input className="input" placeholder="Lý do" aria-label="Lý do" value={String(lf.reason ?? "")} onChange={(e) => setLf({ ...lf, reason: e.target.value })} /><DelegatePick from={String(lf.from_date)} to={String(lf.to_date)} value={String(lf.delegate_id ?? "")} onChange={(v) => setLf({ ...lf, delegate_id: v })} /><input className="input sm:col-span-3" placeholder="Bàn giao gì: việc dở dang, sổ ghi, chìa khóa, báo cáo phải nộp…" value={String(lf.handover_note ?? "")} onChange={(e) => setLf({ ...lf, handover_note: e.target.value })} /><div className="flex gap-2"><button className="btn-primary !py-2" onClick={async () => { if (!lf.delegate_id) { if (!(await confirm({ title: "Chưa chọn người thay — việc của bạn sẽ không ai nhận trong kỳ nghỉ. Vẫn gửi?", danger: true }))) return; } const j = await adminPost("leave_requests", { ...lf, delegate_id: lf.delegate_id || null, staff_id: sess.staffId }); setMsg(j.ok ? "Đã gửi đơn — quản lý trực tiếp đã nhận tin; khi duyệt, việc sẽ tự chuyển sang người thay" : `${j.error}`); setLf(null); leaves.reload(); }}>Gửi</button><button className="btn-secondary !py-2" onClick={() => setLf(null)}>Hủy</button></div></div>}
    <div className="grid md:grid-cols-2 gap-3">
      <div className="card p-0 overflow-auto"><div className="px-3 py-2 bg-surface-2 rounded-t-xl font-bold">Hôm nay ({(today.rows ?? []).length} người){canMgr && <span className="text-xs font-normal text-muted"> — tổ trưởng chấm hộ ở Quản trị DL › attendance</span>}</div><DataBoundary loading={today.loading} error={today.error} empty={!today.rows?.length} onRetry={today.reload} emptyText="Chưa có ai chấm công hôm nay."><table className="tbl text-sm"><tbody>{(today.rows ?? []).map((r) => <tr key={String(r.id)}><td className="pl-3">{String(r.full_name)}</td><td className="text-xs">{String(r.shift ?? "")}</td><td>{fmt.dt(r.check_in)}</td><td>{r.check_out ? fmt.dt(r.check_out) : <span className="b-grn">đang làm</span>}</td><td className="text-right">{r.hours ? `${r.hours}h` : ""}</td></tr>)}</tbody></table></DataBoundary></div>
      <div className="card p-0 overflow-auto"><div className="px-3 py-2 bg-surface-2 rounded-t-xl font-bold">Công tháng</div><table className="tbl text-sm"><thead><tr><th className="pl-3">Tháng</th><th>Nhân sự</th><th className="text-right">Ngày công</th><th className="text-right">Giờ</th></tr></thead><tbody>{(month.rows ?? []).map((r, i) => <tr key={i}><td className="pl-3">{fmt.d(r.month)}</td><td>{String(r.full_name)}</td><td className="text-right font-bold">{String(r.days)}</td><td className="text-right">{String(r.hours)}</td></tr>)}</tbody></table></div>
    </div>
    <div className="card p-0 overflow-auto"><div className="px-3 py-2 bg-surface-2 rounded-t-xl font-bold">Nghỉ phép ({(leaves.rows ?? []).length})</div><table className="tbl text-sm"><thead><tr><th className="pl-3">Nhân sự</th><th>Loại</th><th>Từ</th><th>Đến</th><th className="text-right">Ngày</th><th>Lý do</th><th>TT</th></tr></thead><tbody>{(leaves.rows ?? []).map((r) => <tr key={String(r.id)}><td className="pl-3">{String(r.full_name)}</td><td>{String(r.kind)}</td><td>{fmt.d(r.from_date)}</td><td>{fmt.d(r.to_date)}</td><td className="text-right">{String(r.days)}</td><td className="text-xs">{String(r.reason ?? "")}</td><td><span className={r.status === "DUYET" ? "b-grn" : r.status === "TU_CHOI" ? "b-red" : "b-yel"}>{String(r.status)}</span></td></tr>)}</tbody></table></div>
    <div className="card p-0 overflow-auto"><div className="px-3 py-2 bg-surface-2 rounded-t-xl font-bold flex items-center gap-2">Thay người / ủy quyền ({(deleg.rows ?? []).filter((r) => r.status === "ACTIVE").length} đang hiệu lực)<span className="text-xs font-normal text-muted">— nghỉ được duyệt có người thay ⇒ việc tự chuyển; hết kỳ tự trả về</span><ManualDelegate onDone={() => deleg.reload()} /></div><table className="tbl text-sm"><thead><tr><th className="pl-3">Người nghỉ/vắng</th><th>Người thay</th><th>Từ</th><th>Đến</th><th>Lý do</th><th className="text-right">Việc chuyển</th><th>TT</th><th></th></tr></thead><tbody>{(deleg.rows ?? []).map((r) => <tr key={String(r.id)}><td className="pl-3">{String(r.from_name)}</td><td>{String(r.to_name)}</td><td>{fmt.d(r.from_date)}</td><td>{fmt.d(r.to_date)}</td><td>{String(r.reason ?? "")}</td><td className="text-right">{String(r.tasks_moved)}</td><td>{r.status === "ACTIVE" ? <span className="b-grn">đang thay</span> : <span className="b-gray">{String(r.status)}</span>}</td><td>{r.status === "ACTIVE" && (r.from_staff === sess.staffId || r.to_staff === sess.staffId || canMgr) && <button className="text-xs underline py-2 -my-2" onClick={async () => { await act("end_delegation", { id: r.id }); deleg.reload(); }}>kết thúc sớm</button>}</td></tr>)}</tbody></table></div>
    <div className="text-xs text-muted">{(staff.rows ?? []).length} nhân sự · lương = KPI→lương lớp 2 (bảng KPI) × ngày công (attendance) − nghỉ không lương; xuất CSV bảng công: <a className="underline" href="/api/admin/attendance?csv=1">tải</a>.</div>
  </div>);
}
/** BẢN ĐỒ TRẠI: vẽ ô thửa từ plots.geom (GeoJSON) + khu/vị trí (grid) + trạng thái đàn/mùa vụ — SVG, không cần dịch vụ ngoài */
export function MapPanel({ sess }: { sess: Sess }) {
  const plots = useData("plots"); const locs = useData("location_summary"); const seasons = useData("crop_dossier"); const farms = useData("farms");
  const f = (farms.rows ?? []).find((x) => x.id === sess.farmId);
  const polys = useMemo(() => (plots.rows ?? []).map((p) => { const g = p.geom as { type?: string; coordinates?: number[][][] } | null; const ring = g?.type === "Polygon" ? g.coordinates?.[0] : null; return { p, ring }; }).filter((x) => x.ring && x.ring.length > 2), [plots.rows]);
  const bbox = useMemo(() => { const pts = polys.flatMap((x) => x.ring!); if (!pts.length) return null; const xs = pts.map((c) => c[0]), ys = pts.map((c) => c[1]); return { minX: Math.min(...xs), maxX: Math.max(...xs), minY: Math.min(...ys), maxY: Math.max(...ys) }; }, [polys]);
  const W = 900, H = 520; const sx = (x: number) => bbox ? ((x - bbox.minX) / (bbox.maxX - bbox.minX || 1)) * (W - 40) + 20 : 0; const sy = (y: number) => bbox ? H - (((y - bbox.minY) / (bbox.maxY - bbox.minY || 1)) * (H - 40) + 20) : 0;
  const color = (p: R) => { const s = (seasons.rows ?? []).find((x) => x.plot_id === p.id && ["DANG_TRONG", "THU_HOACH"].includes(String(x.status))); if (!s) return "var(--line)"; if (s.phi_until && new Date(String(s.phi_until)) > new Date()) return "var(--danger-soft)"; return String(s.status) === "THU_HOACH" ? "var(--warning-soft)" : "var(--success-soft)"; };
  return (<div className="space-y-3">
    <div className="card"><div className="flex items-center gap-2 flex-wrap text-sm"><b>Bản đồ ô thửa {sess.farmId}</b><span className="text-muted">{polys.length} ô có tọa độ · {(plots.rows ?? []).length} ô tổng</span>{f?.lat ? <a className="ml-auto underline" href={`https://www.google.com/maps?q=${f.lat},${f.lng}`} target="_blank">Mở Google Maps ({String(f.lat)}, {String(f.lng)})</a> : <span className="ml-auto text-muted">chưa có tọa độ trại (Hồ sơ trại › lat/lng)</span>}</div>
      {polys.length ? <div className="overflow-auto"><svg width={W} height={H} className="border rounded-xl" style={{ background: "var(--surface-2)", borderColor: "var(--line)" }}>{polys.map(({ p, ring }) => { const d = ring!.map((c, i) => `${i ? "L" : "M"}${sx(c[0])},${sy(c[1])}`).join(" ") + " Z"; const cx = ring!.reduce((a, c) => a + sx(c[0]), 0) / ring!.length, cy = ring!.reduce((a, c) => a + sy(c[1]), 0) / ring!.length; return <g key={String(p.id)} className="cursor-pointer" onClick={() => (location.href = `/xem/plot/${p.id}`)}><path d={d} fill={color(p)} stroke="var(--muted)" strokeWidth={1.5} /><text x={cx} y={cy} textAnchor="middle" fontSize={11} fontWeight={700} fill="var(--ink)">{String(p.name)}</text><text x={cx} y={cy + 13} textAnchor="middle" fontSize={10} fill="var(--muted)">{String(p.crop_code ?? p.current_crop ?? "")} · {fmt.n(p.area_ha, 2)} ha</text></g>; })}</svg><div className="text-xs mt-1 flex gap-3"><span><i className="inline-block w-3 h-3 border mr-1" style={{ background: "var(--success-soft)" }} />đang trồng</span><span><i className="inline-block w-3 h-3 border mr-1" style={{ background: "var(--warning-soft)" }} />thu hoạch</span><span><i className="inline-block w-3 h-3 border mr-1" style={{ background: "var(--danger-soft)" }} />đang cách ly PHI</span><span><i className="inline-block w-3 h-3 border mr-1" style={{ background: "var(--line)" }} />trống</span> · bấm ô để xem 360</div></div> : <div className="text-muted text-sm">Chưa có ô nào có tọa độ (plots.geom = GeoJSON Polygon). Nhập bằng Quản trị DL › plots (cột geom) hoặc CSV; hoặc dùng sơ đồ lưới ở /so-do.</div>}</div>
    <div className="card p-0 overflow-auto"><div className="px-3 py-2 bg-surface-2 rounded-t-xl font-bold">Khu / vị trí & đàn tại chỗ</div><table className="tbl text-sm"><tbody>{(locs.rows ?? []).map((l) => <tr key={String(l.id)}><td className="pl-3 font-semibold">{String(l.name)}</td><td className="text-xs">{String(l.kind)}</td><td>{fmt.n(l.head_count ?? l.head)} con</td><td className="text-xs">{String(l.capacity ? `sức chứa ${l.capacity}` : "")}</td><td><a className="underline text-xs" href={`/xem/location/${l.id}`}>360</a></td></tr>)}</tbody></table></div>
  </div>);
}
/** PHÁT THẢI CO2e ước tính (IPCC Tier 1, hệ số trong norms) + tuần hoàn */
export function GhgPanel() {
  const g = useData("ghg_month"); const rows = g.rows ?? []; const total = rows.reduce((a, r) => a + Number(r.co2e_kg), 0);
  return (<div className="space-y-3"><div className="grid grid-cols-2 sm:grid-cols-4 gap-2"><div className="kpi"><div className="l">CO2e (kg, tổng các tháng có dữ liệu)</div><div className="v">{fmt.n(total)}</div></div><div className="kpi"><div className="l">CH4 (kg)</div><div className="v">{fmt.n(rows.reduce((a, r) => a + Number(r.ch4_kg), 0))}</div></div><div className="kpi"><div className="l">Phương pháp</div><div className="text-sm font-bold">IPCC 2006/2019 Tier 1</div><div className="text-xs">hệ số: norms GHG_*</div></div><div className="kpi"><div className="l">Bù trừ</div><div className="text-sm font-bold">biogas/compost/cây viền</div><div className="text-xs">ghi sensor biogas_m3, solar_kwh để tính</div></div></div>
    <div className="card"><AnyChart title="Đầu con TB theo tháng & loài (CƠ SỞ tính CO₂e — số CO₂e thật xem KPI + bảng dưới)" table="herd_daily" col="head" agg="avg" dim="species" bucket="month" height={220} /></div>
    <div className="card p-0 overflow-auto"><table className="tbl text-sm"><thead><tr><th className="pl-3">Tháng</th><th>Loài</th><th className="text-right">Đầu con TB</th><th className="text-right">CH4 kg</th><th className="text-right">CO2e kg</th></tr></thead><tbody>{rows.map((r, i) => <tr key={i}><td className="pl-3">{fmt.d(r.month)}</td><td>{String(r.species)}</td><td className="text-right">{fmt.n(r.avg_head)}</td><td className="text-right">{fmt.n(r.ch4_kg, 1)}</td><td className="text-right font-bold">{fmt.n(r.co2e_kg, 1)}</td></tr>)}</tbody></table></div>
    <div className="text-xs text-muted">Đây là ước tính Tier 1 (đầu con × hệ số mặc định IPCC), đủ cho báo cáo nội bộ/ICFS 2.3; muốn Tier 2 (theo khẩu phần, DMI, năng suất) cần bổ sung hệ số theo công thức TMR — sửa trong Quản trị DL › norms.</div></div>);
}
/** TỐI ƯU KHẨU PHẦN GIÁ RẺ NHẤT (LP): nguyên liệu trong kho (giá theo lô) + dinh dưỡng → khẩu phần rẻ nhất đạt DM/CP/ME/NDF */
export function RationPanel({ sess }: { sess: Sess }) {
  const products = useData("products"); const stock = useData("stock");
  const [ings, setIngs] = useState<Ingredient[]>([{ sku: "NL-BAP-U", name: "Bắp ủ chua", price_per_kg_dm: 4200, dm_pct: 32, nutrients: { CP: 8, ME: 2.4, NDF: 45 } }, { sku: "NL-CO-TUOI", name: "Cỏ tươi", price_per_kg_dm: 3000, dm_pct: 20, nutrients: { CP: 9, ME: 2.2, NDF: 60 } }, { sku: "NL-ROM", name: "Rơm", price_per_kg_dm: 2500, dm_pct: 88, nutrients: { CP: 4, ME: 1.6, NDF: 72 } }, { sku: "NL-BA-BIA", name: "Bã bia", price_per_kg_dm: 5500, dm_pct: 22, nutrients: { CP: 25, ME: 2.7, NDF: 45 } }, { sku: "NL-RI-MAT", name: "Rỉ mật", price_per_kg_dm: 6000, dm_pct: 75, nutrients: { CP: 4, ME: 2.9, NDF: 0 }, max_kg: 0.8 }, { sku: "NL-KHOANG", name: "Khoáng", price_per_kg_dm: 25000, dm_pct: 98, nutrients: { CP: 0, ME: 0, NDF: 0 }, min_kg: 0.1, max_kg: 0.15 }]);
  const [dm, setDm] = useState(9); const [cons, setCons] = useState<Constraint[]>([{ nutrient: "CP", min: 12, per: "pct" }, { nutrient: "ME", min: 2.3, per: "pct" }, { nutrient: "NDF", min: 30, max: 55, per: "pct" }]);
  const res = useMemo(() => solveRation(ings, dm, cons), [ings, dm, cons]);
  const upd = (i: number, k: string, v: string) => setIngs(ings.map((g, j) => j === i ? (["CP", "ME", "NDF"].includes(k) ? { ...g, nutrients: { ...g.nutrients, [k]: Number(v) } } : { ...g, [k]: k === "name" || k === "sku" ? v : Number(v) }) : g));
  return (<div className="space-y-3">
    <div className="card"><div className="flex items-center gap-2 flex-wrap text-sm"><b>Tối ưu khẩu phần giá rẻ nhất (LP đơn hình)</b><span>DM mục tiêu (kg/con/ngày)</span><input className="input !w-24 !py-1" type="number" step="0.5" value={dm} onChange={(e) => setDm(Number(e.target.value))} /><button className="btn-secondary !py-1 !px-3 !text-sm ml-auto" onClick={() => setIngs([...ings, { sku: "", name: "Mới", price_per_kg_dm: 0, dm_pct: 30, nutrients: { CP: 0, ME: 0, NDF: 0 } }])}>＋ nguyên liệu</button><button className="btn-secondary !py-1 !px-3 !text-sm" onClick={() => { const st = stock.rows ?? []; setIngs(ings.map((g) => { const s = st.find((x) => x.sku === g.sku); const price = s ? Number(s.avg_cost ?? 0) / ((g.dm_pct ?? 100) / 100) : g.price_per_kg_dm; return s && price > 0 ? { ...g, price_per_kg_dm: Math.round(price) } : g; })); }}>Lấy giá từ kho (đ/kg DM)</button></div>
      <table className="tbl text-sm mt-2"><thead><tr><th className="pl-2">SKU</th><th>Tên</th><th>đ/kg DM</th><th>DM%</th><th>CP%</th><th>ME Mcal</th><th>NDF%</th><th>min kg</th><th>max kg</th><th></th></tr></thead><tbody>{ings.map((g, i) => <tr key={i}>{["sku", "name", "price_per_kg_dm", "dm_pct", "CP", "ME", "NDF", "min_kg", "max_kg"].map((k) => <td key={k} className="pl-1"><input className="input !py-0.5 !text-xs !w-24" list={k === "sku" ? "skus" : undefined} value={String(["CP", "ME", "NDF"].includes(k) ? g.nutrients[k] ?? "" : (g as unknown as R)[k] ?? "")} onChange={(e) => upd(i, k, e.target.value)} /></td>)}<td><button className="text-danger-tok p-1 -m-1" onClick={() => setIngs(ings.filter((_, j) => j !== i))}>✕</button></td></tr>)}</tbody></table><datalist id="skus">{(products.rows ?? []).map((p) => <option key={String(p.sku)} value={String(p.sku)}>{String(p.name)}</option>)}</datalist>
      <div className="mt-2 text-sm"><b>Ràng buộc (% DM):</b> {cons.map((c, i) => <span key={i} className="inline-flex items-center gap-1 ml-2 border rounded-lg px-2 py-0.5"><b>{c.nutrient}</b> ≥<input className="input !w-16 !py-0 !text-xs" type="number" step="0.1" value={c.min ?? ""} onChange={(e) => setCons(cons.map((x, j) => j === i ? { ...x, min: e.target.value === "" ? undefined : Number(e.target.value) } : x))} /> ≤<input className="input !w-16 !py-0 !text-xs" type="number" step="0.1" value={c.max ?? ""} onChange={(e) => setCons(cons.map((x, j) => j === i ? { ...x, max: e.target.value === "" ? undefined : Number(e.target.value) } : x))} /></span>)}</div>
    </div>
    <div className={`card ${res.ok ? "border-2 border-emerald-500" : "border-2 border-danger-tok"}`}>{res.ok ? <div><div className="text-lg font-black">Khẩu phần rẻ nhất: {fmt.vnd(res.cost)}/con/ngày ({dm} kg DM)</div><table className="tbl text-sm mt-1"><tbody>{Object.entries(res.kg).map(([sku, kg]) => { const g = ings.find((x) => x.sku === sku); const asFed = kg / ((g?.dm_pct ?? 100) / 100); return <tr key={sku}><td className="pl-2 font-semibold">{g?.name ?? sku}</td><td className="text-right">{kg} kg DM</td><td className="text-right">= <b>{fmt.n(asFed, 1)} kg tươi</b></td><td className="text-right">{fmt.vnd(kg * (g?.price_per_kg_dm ?? 0))}</td></tr>; })}</tbody></table><div className="text-sm mt-1">Đạt: {Object.entries(res.nutrients).map(([k, v]) => `${k} ${(Number(v) / dm).toFixed(1)}%${k === "ME" ? " (Mcal/kg)" : ""}`).join(" · ")}</div><div className="text-xs text-muted mt-1">Lưu thành công thức: sao chép % vào Quản trị DL › recipes (components). Giá theo lô kho, đổi mỗi ngày → chạy lại.</div></div> : <div className="text-danger-tok font-semibold">{res.message}</div>}</div>
    <div className="text-xs text-muted">Dinh dưỡng mặc định là ví dụ (NRC 2016 xấp xỉ) — KTT nhập số phân tích thật (COA/lab) cho từng lô nguyên liệu tại {sess.farmId}.</div>
  </div>);
}
/** IN PDF: chọn biểu mẫu → trang in (Ctrl+P → PDF): hóa đơn/phiếu bán, phiếu cân, HĐ nhận nuôi, nhãn lô QR, biểu mẫu trắng BM01–BM10, báo cáo tuần */
export function PrintCenter({ sess }: { sess: Sess }) {
  const sales = useData("sales_recent"); const lots = useData("lots"); const custody = useData("custody"); const [kind, setKind] = useState("hoa-don"); const [id, setId] = useState("");
  const kinds = [["hoa-don", "Hóa đơn / phiếu bán (kèm VietQR)"], ["phieu-can", "Phiếu cân"], ["hd-nhan-nuoi", "Hợp đồng chăm sóc hộ / nhận nuôi"], ["nhan-lo", "Nhãn lô + QR truy xuất (A4 nhiều nhãn)"], ["bm", "Biểu mẫu giấy trắng BM01–BM10"], ["bao-cao-tuan", "Báo cáo tuần cho chủ (1 trang)"], ["the-tai", "Danh sách thẻ tai / cá thể (bảng kiểm)"]];
  const list = kind === "hoa-don" ? (sales.rows ?? []).map((s) => [String(s.id), `${fmt.dt(s.ts)} · ${s.sku} · ${fmt.vnd(s.amount)}`]) : kind === "nhan-lo" ? (lots.rows ?? []).map((l) => [String(l.id), `${l.id} · ${l.sku ?? ""}`]) : kind === "hd-nhan-nuoi" ? (custody.rows ?? []).map((c) => [String(c.id), `${c.id} · ${c.partner_name ?? c.partner_id}`]) : [];
  return (<div className="card space-y-2"><b>🖨 Trung tâm in ấn — mở trang in rồi Ctrl+P → "Lưu thành PDF"</b>
    <div className="flex flex-wrap gap-2 items-center text-sm"><select className="input !w-80" value={kind} onChange={(e) => { setKind(e.target.value); setId(""); }}>{kinds.map(([k, l]) => <option key={k} value={k}>{l}</option>)}</select>{list.length > 0 && <select className="input !w-96" value={id} onChange={(e) => setId(e.target.value)}><option value="">— chọn —</option>{list.map(([v, l]) => <option key={v} value={v}>{l}</option>)}</select>}{kind === "phieu-can" && <input className="input !w-64" placeholder="mã phiếu cân (uuid)" aria-label="mã phiếu cân (uuid)" value={id} onChange={(e) => setId(e.target.value)} />}<a className={`btn-primary !py-2 !px-4 !text-sm ${list.length && !id ? "pointer-events-none opacity-50" : ""}`} href={`/in/${kind}/${encodeURIComponent(id || "all")}?farm=${sess.farmId}`} target="_blank">Mở trang in ↗</a></div>
    <div className="text-xs text-muted">Mẫu in dùng CSS @media print (A4/A5/nhãn 70×40). Hóa đơn điện tử: hệ thống xuất dữ liệu chuẩn (bảng kê CSV/JSON) — phát hành HĐĐT phải qua nhà cung cấp được Tổng cục Thuế cấp phép (Viettel/VNPT/MISA meInvoice…) — xem mục "Kế toán" bên dưới.</div></div>);
}
export { act as _act };

/** Chọn người thay khi nghỉ: gợi ý cùng phòng/cùng vị trí, đang rảnh, không nghỉ trùng */
function DelegatePick({ from, to, value, onChange }: { from: string; to: string; value: string; onChange: (v: string) => void }) {
  const sug = useData("suggest_delegates", { from, to }, [from, to]);
  return <select className="input" value={value} onChange={(e) => onChange(e.target.value)} title="Người thay tôi ghi chép & báo cáo trong kỳ nghỉ">
    <option value="">— Người thay (bắt buộc nên chọn) —</option>
    {(sug.rows ?? []).map((r) => <option key={String(r.staff_id)} value={String(r.staff_id)}>{String(r.full_name)} · {String(r.position_name ?? r.dept ?? "")}{r.same_position ? " ✓ cùng vị trí" : ""} · {String(r.load)} việc</option>)}
  </select>;
}
/** Ủy quyền thủ công (đi công tác/họp/vắng không phải nghỉ phép) */
function ManualDelegate({ onDone }: { onDone: () => void }) {
  const [f, setF] = useState<{ to: string; from_date: string; to_date: string; reason: string } | null>(null); const [m, setM] = useState("");
  if (!f) return <button className="ml-auto btn-secondary !py-1 !text-xs min-h-[40px]" onClick={() => setF({ to: "", from_date: new Date().toISOString().slice(0, 10), to_date: new Date().toISOString().slice(0, 10), reason: "Đi công tác" })}>＋ Ủy quyền</button>;
  return <div className="ml-auto flex flex-wrap gap-1 items-center font-normal"><DelegatePick from={f.from_date} to={f.to_date} value={f.to} onChange={(v) => setF({ ...f, to: v })} /><input className="input !py-1" type="date" value={f.from_date} onChange={(e) => setF({ ...f, from_date: e.target.value })} /><input className="input !py-1" type="date" value={f.to_date} onChange={(e) => setF({ ...f, to_date: e.target.value })} /><input className="input !py-1" value={f.reason} onChange={(e) => setF({ ...f, reason: e.target.value })} /><button className="btn-primary !py-1 !text-xs min-h-[40px]" onClick={async () => { const j = await act("delegate", f); setM(j.error ? String(j.error) : "OK"); if (!j.error) { setF(null); onDone(); } }}>Lưu</button><button className="btn-secondary !py-1 !text-xs min-h-[40px]" onClick={() => setF(null)}>Hủy</button><span className="text-xs">{m}</span></div>;
}
