"use client";
import { useState } from "react";
import { useData, act, fmt } from "@/lib/client";
import { SupplierReturnPanel } from "@/components/panels/CloseoutBits";
import type { Sess } from "@/components/Shell";
import AnyChart from "@/components/AnyChart";
import Tabs from "@/components/Tabs";
type R = Record<string, unknown>;
const KINDS: [string, string][] = [["VAT_TU", "Vật tư / nguyên liệu"], ["GIONG", "Giống (cây/vật nuôi/tinh)"], ["THIET_BI", "Thiết bị / máy"], ["CONG_CU", "Công cụ – dụng cụ"], ["DICH_VU", "Dịch vụ"], ["TAI_SAN", "Tài sản (XDCB)"]];
/** MUA HÀNG cho người mua: gợi ý cần mua (ROP + MRP + dự trữ) → tạo PO (mọi loại: vật tư, giống, thiết bị, công cụ) → duyệt theo ma trận → NHẬN HÀNG = nhập kho tự động (lô, NCC, HSD, COA) → biểu đồ mua theo tháng/nhóm */
export default function MuaHang({ sess }: { sess: Sess }) {
  const [tab, setTab] = useState<"goiy" | "tao" | "ds" | "nhan" | "bieudo" | "tra">("goiy");
  const pos = useData("po_list"); const sug = useData("po_suggest"); const partners = useData("partners"); const products = useData("products"); const wh = useData("warehouses"); const pm = useData("purchases_month"); const groups = useData("stock_groups");
  const [f, setF] = useState<R>({ kind: "VAT_TU", lines: [] as R[] }); const [msg, setMsg] = useState(""); const [rcv, setRcv] = useState<R | null>(null); const [rl, setRl] = useState<R[]>([]);
  const L = (f.lines as R[]) ?? []; const canApprove = ["tech_head", "director", "accountant", "team_lead", "owner"].includes(sess.role);
  const P = (products.rows ?? []).filter((p) => p.kind !== "DICH_VU" || f.kind === "DICH_VU");
  const addLine = (sku: string, qty = 1, price = 0) => { const p = (products.rows ?? []).find((x) => x.sku === sku); setF({ ...f, lines: [...L, { sku, name: p?.name, unit: p?.unit, qty, price: price || Number(p?.ref_price ?? 0) }] }); setTab("tao"); };
  const total = L.reduce((a, l) => a + Number(l.qty) * Number(l.price ?? 0), 0);
  const create = async () => { const j = await act("create_po_full", { ...f, lines: L }); setMsg(j.ok ? `Đã tạo ${j.id} (${fmt.vnd(Number(j.total))}) — chờ duyệt theo ma trận ủy quyền` : String(j.error)); if (j.ok) { setF({ kind: "VAT_TU", lines: [] }); pos.reload(); setTab("ds"); } };
  const openReceive = (po: R) => { setRcv(po); setRl(((po.lines as R[]) ?? []).map((l) => ({ ...l, received_qty: l.qty, lot_no: "", expiry: "", warehouse_id: "" }))); setTab("nhan"); };
  const doReceive = async () => { if (!rcv) return; const j = await act("receive_po", { id: rcv.id, lines: rl.map((l) => ({ ...l, lot_no: l.lot_no || null, expiry: l.expiry || null, warehouse_id: l.warehouse_id || null })) }); setMsg(j.ok ? `Đã nhận ${j.n} dòng → nhập kho, sinh lô; công nợ NCC ghi nhận` : String(j.error)); if (j.ok) { setRcv(null); pos.reload(); setTab("ds"); } };
  const G = groups.rows ?? [];
  return <div className="space-y-3">
    <Tabs items={[["goiy", `Gợi ý cần mua (${(sug.rows ?? []).length})`], ["tao", `Tạo PO${L.length ? ` (${L.length} dòng)` : ""}`], ["ds", `PO (${(pos.rows ?? []).filter((p) => !["DA_NHAN", "HUY", "TU_CHOI"].includes(String(p.po_status))).length} đang mở)`], ["nhan", "Nhận hàng → nhập kho"], ["tra", "↩ Trả nhà cung cấp"], ["bieudo", "📈 Biểu đồ mua"]]} value={tab} onChange={(k) => setTab(k as typeof tab)} />
    {tab === "tra" && <SupplierReturnPanel sess={sess} />}
    {msg && <div className="rounded-xl bg-brand-soft border border-emerald-300 px-3 py-2 text-sm">{msg}</div>}
    {tab === "goiy" && <div className="card p-0 overflow-auto"><div className="px-3 py-2 bg-surface-2 rounded-t-xl font-bold">Gợi ý cần mua — từ điểm đặt hàng lại (ROP), MRP (kế hoạch SX/đơn), dashboard dự trữ (dự kiến âm)</div><table className="tbl text-sm"><thead><tr><th className="pl-3">Nguồn</th><th>Mặt hàng</th><th className="text-right">Cần mua</th><th>NCC ưu tiên</th><th className="text-right">Lead</th><th></th></tr></thead><tbody>{(sug.rows ?? []).map((r, i) => <tr key={i}><td className="pl-3 text-xs">{String(r.src)}</td><td>{String(r.product_name)} <span className="font-mono text-xs text-muted">{String(r.sku)}</span></td><td className="text-right font-bold text-danger-tok">{fmt.n(Number(r.qty))}</td><td className="text-xs">{String(r.supplier_name ?? "")}</td><td className="text-right">{String(r.lead ?? "")}</td><td><button className="underline text-sm py-2 -my-2" onClick={() => { if (r.supplier_id && !f.supplier_id) setF({ ...f, supplier_id: r.supplier_id }); addLine(String(r.sku), Math.ceil(Number(r.qty))); }}>＋ vào PO</button></td></tr>)}</tbody></table>{sug.rows?.length === 0 && <div className="p-3 text-sm text-muted">Không có gợi ý — mọi thứ đủ.</div>}</div>}
    {tab === "tao" && <div className="card"><div className="grid sm:grid-cols-2 lg:grid-cols-5 gap-2"><select className="input" value={String(f.kind)} onChange={(e) => setF({ ...f, kind: e.target.value })}>{KINDS.map(([k, l]) => <option key={k} value={k}>{l}</option>)}</select><select className="input lg:col-span-2" value={String(f.supplier_id ?? "")} onChange={(e) => setF({ ...f, supplier_id: e.target.value })}><option value="">Nhà cung cấp</option>{(partners.rows ?? []).filter((p) => String(p.kind).includes("NCC")).map((p) => <option key={String(p.id)} value={String(p.id)}>{String(p.name)}{p.approved ? " ✓" : " (chưa duyệt NCC)"}</option>)}</select><input className="input" type="date" value={String(f.expected_at ?? "")} onChange={(e) => setF({ ...f, expected_at: e.target.value })} title="Ngày hàng về dự kiến" /><input className="input" placeholder="Bộ phận yêu cầu (TT/D5/BO…)" aria-label="Bộ phận yêu cầu (TT/D5/BO…)" value={String(f.dept ?? "")} onChange={(e) => setF({ ...f, dept: e.target.value })} /></div>
      <div className="flex gap-2 mt-2 flex-wrap"><select className="input !w-96" onChange={(e) => { if (e.target.value) addLine(e.target.value); e.target.value = ""; }}><option value="">＋ thêm mặt hàng (mọi loại: nguyên liệu, giống, thuốc, thiết bị, công cụ, bao bì…)</option>{G.map((g) => <optgroup key={String(g.code)} label={`${g.icon ?? ""} ${g.name}`}>{P.filter((p) => p.stock_group === g.code).map((p) => <option key={String(p.sku)} value={String(p.sku)}>{String(p.name)} ({String(p.unit)})</option>)}</optgroup>)}<optgroup label="Khác / chưa phân nhóm">{P.filter((p) => !p.stock_group).map((p) => <option key={String(p.sku)} value={String(p.sku)}>{String(p.name)} · {String(p.kind)}</option>)}</optgroup></select><a className="underline text-sm self-center" href="/quan-tri?t=products">mặt hàng mới chưa có → thêm ở danh mục</a></div>
      <table className="tbl text-sm mt-2"><thead><tr><th>Mặt hàng</th><th className="text-right">SL</th><th>ĐV</th><th className="text-right">Đơn giá</th><th className="text-right">Thành tiền</th><th></th></tr></thead><tbody>{L.map((l, i) => <tr key={i}><td>{String(l.name)} <span className="font-mono text-xs text-muted">{String(l.sku)}</span></td><td><input className="input !w-24 !py-1 text-right" type="number" value={String(l.qty)} onChange={(e) => setF({ ...f, lines: L.map((x, j) => j === i ? { ...x, qty: Number(e.target.value) } : x) })} /></td><td>{String(l.unit ?? "")}</td><td><input className="input !w-32 !py-1 text-right" type="number" value={String(l.price)} onChange={(e) => setF({ ...f, lines: L.map((x, j) => j === i ? { ...x, price: Number(e.target.value) } : x) })} /></td><td className="text-right">{fmt.vnd(Number(l.qty) * Number(l.price ?? 0))}</td><td><button className="text-danger-tok p-1 -m-1" onClick={() => setF({ ...f, lines: L.filter((_, j) => j !== i) })}>✕</button></td></tr>)}</tbody></table>
      <div className="flex items-center gap-3 mt-2 flex-wrap"><input className="input flex-1" placeholder="Ghi chú / điều kiện giao / COA yêu cầu" aria-label="Ghi chú / điều kiện giao / COA yêu cầu" value={String(f.note ?? "")} onChange={(e) => setF({ ...f, note: e.target.value })} /><div className="text-lg">Tổng: <b>{fmt.vnd(total)}</b></div><button className="btn-primary !py-2" disabled={!L.length || !f.supplier_id} onClick={create}>Tạo PO</button></div><div className="text-xs text-muted mt-1">Hạn mức duyệt PO theo <a className="underline" href="/ke-toan">ma trận ủy quyền</a> (KTT ≤30tr, GĐ ≤500tr, &gt;50tr 2 chữ ký). NCC chưa phê duyệt (approved) → QA rà trước khi nhận (ISO 22000/GlobalG.A.P).</div></div>}
    {tab === "ds" && <div className="card p-0 overflow-auto"><table className="tbl text-sm"><thead><tr><th className="pl-3">PO</th><th>Loại</th><th>NCC</th><th>Người tạo</th><th>Ngày</th><th>Về DK</th><th className="text-right">Tổng</th><th>TT</th><th></th></tr></thead><tbody>{(pos.rows ?? []).map((p) => <tr key={String(p.id)} className={p.po_status === "CHO_DUYET" ? "bg-warning-soft-tok" : p.po_status === "DUYET" ? "bg-brand-soft/40" : ""}><td className="pl-3 font-mono text-xs">{String(p.id)}<div className="text-[10px] text-muted max-w-[280px] truncate">{((p.lines as R[]) ?? []).map((l) => `${l.sku}×${l.qty}`).join(", ")}</div></td><td className="text-xs">{String(p.kind ?? "")}</td><td>{String(p.supplier_name ?? "")}</td><td className="text-xs">{String(p.created_name ?? p.created_by)}</td><td className="text-xs">{fmt.d(String(p.ts))}</td><td className="text-xs">{p.expected_at ? fmt.d(String(p.expected_at)) : ""}</td><td className="text-right">{fmt.vnd(Number(p.total))}</td><td><span className="rounded-full px-2 text-xs bg-surface-2">{String(p.po_status)}</span></td><td className="text-xs whitespace-nowrap">{canApprove && p.po_status === "CHO_DUYET" && <><button className="underline mr-2 py-2 -my-2" onClick={async () => { const j = await act("po_status", { id: p.id, status: "DUYET" }); setMsg(j.ok ? "Đã duyệt" : String(j.error)); pos.reload(); }}>duyệt</button><button className="underline mr-2 text-danger-tok py-2 -my-2" onClick={async () => { await act("po_status", { id: p.id, status: "TU_CHOI" }); pos.reload(); }}>từ chối</button></>}{["DUYET", "NHAN_MOT_PHAN"].includes(String(p.po_status)) && <button className="underline mr-2 font-semibold py-2 -my-2" onClick={() => openReceive(p)}>📥 nhận hàng</button>}<a className="underline py-2 -my-2" href={`/quan-tri?t=purchase_orders&pk=${p.id}`}>chi tiết</a></td></tr>)}</tbody></table></div>}
    {tab === "nhan" && <div className="card">{!rcv ? <div className="text-sm text-muted">Chọn PO đã duyệt ở tab PO → “📥 nhận hàng”. Nhận hàng = nhập kho từng dòng (kho tự chọn theo loại: thuốc/giống → K1, nguyên liệu → K2, nhiên liệu → K7, bao bì → K9, công cụ → KCC), sinh lô kèm NCC + HSD + COA; PO chuyển ĐÃ NHẬN (hoặc một phần), ghi received_at cho scorecard đúng hạn và công nợ phải trả.</div> : <div><b>Nhận hàng {String(rcv.id)} — {String(rcv.supplier_name)}</b><table className="tbl text-sm mt-2"><thead><tr><th>Mặt hàng</th><th className="text-right">Đặt</th><th className="text-right">Nhận</th><th>Kho</th><th>Số lô NCC</th><th>HSD</th><th>COA (URL)</th></tr></thead><tbody>{rl.map((l, i) => <tr key={i}><td>{String(l.sku)}</td><td className="text-right">{String(l.qty)}</td><td><input className="input !w-24 !py-1 text-right" type="number" value={String(l.received_qty)} onChange={(e) => setRl(rl.map((x, j) => j === i ? { ...x, received_qty: Number(e.target.value) } : x))} /></td><td><select className="input !py-1" value={String(l.warehouse_id ?? "")} onChange={(e) => setRl(rl.map((x, j) => j === i ? { ...x, warehouse_id: e.target.value } : x))}><option value="">tự chọn theo loại</option>{(wh.rows ?? []).map((w) => <option key={String(w.id)} value={String(w.id)}>{String(w.code)} {String(w.name)}</option>)}</select></td><td><input className="input !w-32 !py-1" value={String(l.lot_no ?? "")} onChange={(e) => setRl(rl.map((x, j) => j === i ? { ...x, lot_no: e.target.value } : x))} /></td><td><input className="input !w-36 !py-1" type="date" value={String(l.expiry ?? "")} onChange={(e) => setRl(rl.map((x, j) => j === i ? { ...x, expiry: e.target.value } : x))} /></td><td><input className="input !w-40 !py-1" placeholder="link phiếu COA" aria-label="link phiếu COA" value={String(l.coa_url ?? "")} onChange={(e) => setRl(rl.map((x, j) => j === i ? { ...x, coa_url: e.target.value } : x))} /></td></tr>)}</tbody></table><div className="flex gap-2 mt-2"><button className="btn-primary !py-2" onClick={doReceive}>Xác nhận nhận hàng → nhập kho</button><button className="btn-secondary !py-2" onClick={() => setRcv(null)}>Hủy</button></div></div>}</div>}
    {tab === "bieudo" && <div className="space-y-3"><div className="grid md:grid-cols-2 gap-3"><div className="card"><AnyChart title="Nhập mua theo mặt hàng (kg/đv, theo tháng)" table="inventory_moves" col="qty" dim="sku" bucket="month" filters={{ reason: "NHAP_MUA" }} from={new Date(Date.now() - 365 * 864e5).toISOString().slice(0, 10)} height={260} compare /></div><div className="card"><AnyChart title="Giá trị mua (đ = qty×đơn giá chưa có → xem bảng)" table="inventory_moves" col="unit_cost" agg="avg" dim="sku" bucket="month" filters={{ reason: "NHAP_MUA" }} from={new Date(Date.now() - 365 * 864e5).toISOString().slice(0, 10)} height={260} /></div></div>
      <div className="card p-0 overflow-auto"><div className="px-3 py-2 bg-surface-2 rounded-t-xl font-bold">Mua theo tháng × nhóm dự trữ (13 tháng)</div><table className="tbl text-sm"><thead><tr><th className="pl-3">Tháng</th><th>Nhóm</th><th className="text-right">Số lượng</th><th className="text-right">Giá trị</th></tr></thead><tbody>{(pm.rows ?? []).map((r, i) => <tr key={i}><td className="pl-3">{String(r.month)}</td><td>{String(r.group_name ?? r.stock_group ?? "—")}</td><td className="text-right">{fmt.n(Number(r.qty))}</td><td className="text-right">{fmt.vnd(Number(r.amount))}</td></tr>)}</tbody></table></div><div className="text-xs text-muted">Mỗi mặt hàng có 📈 riêng ở Dự trữ/Kho (bấm cuối dòng) — biến động nhập/xuất/tồn so kỳ trước; NCC: <a className="underline" href="/kho?tab=ncc">scorecard</a>.</div></div>}
  </div>;
}
