"use client";
import { useEffect, useState } from "react";
import { fmt } from "@/lib/client";
import type { Sess } from "@/components/Shell";
import AnyChart, { RecordsTable } from "@/components/AnyChart";
import Attachments from "@/components/Attachments";
type R = Record<string, unknown>;
/** Cấu hình 360: đối tượng → bảng nguồn thuộc tính + các biểu đồ/sự kiện liên quan (lọc theo cột khóa). Thêm đối tượng = thêm 1 mục. */
export const CFG: Record<string, { label: string; table: string; pk: string; charts: { title: string; table: string; col: string; agg?: "sum" | "avg" | "count"; dim?: string; filter: string; unit?: string; extra?: Record<string, string>; bucket?: string; days?: number }[]; events: { table: string; filter: string; label: string }[]; links?: (id: string) => { href: string; label: string }[] }> = {
  animal: { label: "Cá thể vật nuôi", table: "animals", pk: "id", charts: [{ title: "Cân nặng (kg)", table: "animal_events", col: "value", agg: "avg", filter: "animal_id", extra: { event_type: "CAN" }, bucket: "month", days: 400 }, { title: "Thức ăn nạp (kg/con, phân bổ từ đàn)", table: "v_animal_feed_daily", col: "feed_kg", agg: "sum", filter: "animal_id", unit: "kg" }, { title: "Khẩu phần theo LOẠI (thức ăn hỗn hợp)", table: "v_animal_feed_daily", col: "feed_kg", agg: "sum", dim: "recipe", filter: "animal_id", unit: "kg" }, { title: "FCR — kg ăn/kg tăng (THẤP = hấp thụ tốt)", table: "v_animal_growth_month", col: "fcr", agg: "avg", filter: "animal_id", bucket: "month", days: 400 }, { title: "ADG — tăng trọng (g/ngày, CAO = tốt)", table: "v_animal_growth_month", col: "adg_g", agg: "avg", filter: "animal_id", unit: "g/ngày", bucket: "month", days: 400 }, { title: "Sự kiện theo loại", table: "animal_events", col: "id", agg: "count", dim: "event_type", filter: "animal_id" }], events: [{ table: "animal_events", filter: "animal_id", label: "Sự kiện cá thể" }], links: (id) => [{ href: `/dan/${id}`, label: "Hồ sơ đầy đủ" }] },
  group: { label: "Đàn / nhóm", table: "animal_groups", pk: "id", charts: [{ title: "Thức ăn (kg)", table: "feed_logs", col: "qty_kg", filter: "dest_group_id", dim: "meal" }, { title: "Sự kiện đàn", table: "animal_events", col: "id", agg: "count", dim: "event_type", filter: "group_id" }, { title: "Số lượng ghi nhận (SO_LUONG)", table: "animal_events", col: "value", filter: "group_id", extra: { event_type: "SO_LUONG" } }], events: [{ table: "animal_events", filter: "group_id", label: "Sự kiện" }, { table: "feed_logs", filter: "dest_group_id", label: "Cho ăn" }] },
  plot: { label: "Ô / thửa", table: "plots", pk: "id", charts: [{ title: "Năng suất (kg/ha, cao = tốt)", table: "v_plot_yield", col: "kg_per_ha", agg: "avg", dim: "crop", filter: "plot_id", unit: "kg/ha", bucket: "quarter", days: 730 }, { title: "Thu hoạch (kg)", table: "harvests", col: "qty_kg", dim: "crop", filter: "plot_id" }, { title: "Tưới (m³)", table: "irrigation_logs", col: "volume_m3", dim: "method", filter: "plot_id" }, { title: "Dịch hại: mật độ", table: "pest_scouting", col: "density", dim: "pest", filter: "plot_id" }, { title: "Cắt/thu từ nhật ký (kg)", table: "crop_logs", col: "qty_kg", dim: "activity", filter: "plot_id" }, { title: "Vật tư (kg)", table: "crop_inputs", col: "qty", dim: "kind", filter: "plot_id" }, { title: "Giờ máy", table: "crop_logs", col: "machine_hours", filter: "plot_id" }], events: [{ table: "crop_logs", filter: "plot_id", label: "Nhật ký ruộng" }, { table: "crop_inputs", filter: "plot_id", label: "Vật tư" }, { table: "harvests", filter: "plot_id", label: "Thu hoạch" }], links: () => [{ href: "/canh-tac", label: "Hồ sơ canh tác" }] },
  season: { label: "Mùa vụ", table: "crop_seasons", pk: "id", charts: [{ title: "Thu hoạch (kg)", table: "harvests", col: "qty_kg", filter: "season_id" }, { title: "Tưới (m³)", table: "irrigation_logs", col: "volume_m3", filter: "season_id" }, { title: "Dịch hại: mật độ", table: "pest_scouting", col: "density", dim: "pest", filter: "season_id" }, { title: "Vật tư (kg)", table: "crop_inputs", col: "qty", dim: "kind", filter: "season_id" }], events: [{ table: "harvests", filter: "season_id", label: "Thu hoạch" }, { table: "crop_inputs", filter: "season_id", label: "Vật tư" }], links: (id) => [{ href: `/api/exports/crop-dossier?season=${id}`, label: "Xuất Nhật ký sản xuất" }] },
  crop: { label: "Cây trồng", table: "crops", pk: "code", charts: [{ title: "Năng suất theo ô (kg/ha)", table: "v_plot_yield", col: "kg_per_ha", agg: "avg", dim: "plot_id", filter: "crop", unit: "kg/ha", bucket: "quarter", days: 730 }, { title: "Năng suất theo MÙA (kg/ha, bấm Năm/Quý)", table: "v_plot_yield", col: "kg_per_ha", agg: "avg", filter: "crop", unit: "kg/ha", bucket: "quarter", days: 1095 }, { title: "Thu hoạch (kg) mọi ô", table: "harvests", col: "qty_kg", dim: "plot_id", filter: "crop" }], events: [{ table: "harvests", filter: "crop", label: "Thu hoạch" }], links: () => [{ href: "/canh-tac", label: "Canh tác" }, { href: "/doi-tuong", label: "Đối tượng" }] },
  species: { label: "Loài", table: "species", pk: "code", charts: [{ title: "Đàn theo ngày", table: "herd_daily", col: "head", dim: "status", filter: "species" }, { title: "Chết", table: "animal_events", col: "id", agg: "count", filter: "event_type", extra: { event_type: "CHET" } }], events: [], links: () => [{ href: "/dan", label: "Đàn" }] },
  product: { label: "Mặt hàng / SKU", table: "products", pk: "sku", charts: [{ title: "Nhập kho", table: "inventory_moves", col: "qty", dim: "reason", filter: "sku", extra: { direction: "1" } }, { title: "Xuất kho", table: "inventory_moves", col: "qty", dim: "reason", filter: "sku", extra: { direction: "-1" } }, { title: "Bán (đ)", table: "sales", col: "amount", dim: "channel_code", filter: "sku" }, { title: "Tồn theo ngày (snapshot)", table: "stock_daily", col: "qty", dim: "warehouse_id", filter: "sku" }], events: [{ table: "inventory_moves", filter: "sku", label: "Nhập/xuất" }, { table: "sales", filter: "sku", label: "Bán" }], links: () => [{ href: "/kho", label: "Kho" }] },
  staff: { label: "Nhân sự", table: "staff", pk: "id", charts: [{ title: "Số bản ghi theo bảng", table: "animal_events", col: "id", agg: "count", filter: "created_by" }, { title: "Việc hoàn thành", table: "tasks", col: "id", agg: "count", dim: "kind", filter: "done_by" }, { title: "KPI điểm", table: "kpi_results", col: "score", agg: "avg", filter: "staff_id" }], events: [{ table: "tasks", filter: "done_by", label: "Việc đã làm" }, { table: "checklist_runs", filter: "created_by", label: "Checklist" }], links: () => [{ href: "/nhan-su", label: "Nhân sự" }] },
  partner: { label: "Đối tác", table: "partners", pk: "id", charts: [{ title: "Doanh thu (đ)", table: "sales", col: "amount", dim: "sku", filter: "partner_id" }, { title: "Mua vào (nhập kho)", table: "inventory_moves", col: "qty", dim: "sku", filter: "from_to" }], events: [{ table: "sales", filter: "partner_id", label: "Bán hàng" }, { table: "orders", filter: "partner_id", label: "Đơn" }], links: () => [{ href: "/ban-hang", label: "Bán hàng" }] },
  device: { label: "Thiết bị", table: "devices", pk: "id", charts: [{ title: "Cảm biến (TB)", table: "sensor_reads", col: "value", agg: "avg", dim: "metric", filter: "device_id" }, { title: "Giờ máy", table: "crop_logs", col: "machine_hours", filter: "machine_id" }], events: [{ table: "calibrations", filter: "target_device_id", label: "Hiệu chuẩn" }], links: () => [{ href: "/thiet-bi", label: "Thiết bị" }] },
  facility: { label: "Nhà công năng", table: "facilities", pk: "id", charts: [], events: [], links: (id) => [{ href: `/quan-tri?t=facilities&pk=${id}`, label: "Sửa / lịch sử" }] },
  location: { label: "Khu / vị trí", table: "locations", pk: "id", charts: [{ title: "Sự kiện tại vị trí", table: "animal_events", col: "id", agg: "count", dim: "event_type", filter: "location_id" }, { title: "Mẻ khu D", table: "batch_logs", col: "id", agg: "count", dim: "line", filter: "location_id" }], events: [{ table: "batch_logs", filter: "location_id", label: "Mẻ" }], links: () => [{ href: "/so-do", label: "Sơ đồ" }] },
  warehouse: { label: "Kho", table: "warehouses", pk: "id", charts: [{ title: "Nhập", table: "inventory_moves", col: "qty", dim: "sku", filter: "warehouse_id", extra: { direction: "1" } }, { title: "Xuất", table: "inventory_moves", col: "qty", dim: "sku", filter: "warehouse_id", extra: { direction: "-1" } }], events: [{ table: "inventory_moves", filter: "warehouse_id", label: "Nhập/xuất" }], links: () => [{ href: "/kho", label: "Kho" }] },
  lot: { label: "Lô", table: "lots", pk: "id", charts: [{ title: "Nhập/xuất lô", table: "inventory_moves", col: "qty", dim: "direction", filter: "lot_id" }], events: [{ table: "inventory_moves", filter: "lot_id", label: "Nhập/xuất" }, { table: "sales", filter: "lot_id", label: "Bán" }], links: (id) => [{ href: `/trace/${id}`, label: "Truy xuất QR" }] },
  process: { label: "Quy trình", table: "processes", pk: "code", charts: [], events: [], links: (id) => [{ href: `/to-chuc?tab=quytrinh&p=${id}`, label: "Xem quy trình" }] },
  department: { label: "Phòng ban", table: "departments", pk: "code", charts: [], events: [], links: () => [{ href: "/to-chuc", label: "Tổ chức" }] },
  booking: { label: "Booking", table: "hosp_bookings", pk: "id", charts: [{ title: "Folio (đ)", table: "hosp_folio", col: "amount", dim: "kind", filter: "booking_id" }], events: [{ table: "hosp_folio", filter: "booking_id", label: "Folio" }], links: () => [{ href: "/du-lich", label: "Du lịch" }] },
};
export default function Obj360({ sess, type, id }: { sess: Sess; type: string; id: string }) {
  const cfg = CFG[type]; const [row, setRow] = useState<R | null>(null); const [ev, setEv] = useState<Record<string, R[]>>({}); const [err, setErr] = useState("");
  useEffect(() => { if (!cfg) return; fetch(`/api/admin/${cfg.table}?q=${encodeURIComponent(id)}&all=1&inactive=1&limit=50`).then((r) => r.json()).then(async (j) => { const r = (j.rows ?? []).find((x: R) => x[cfg.pk] === id) ?? null; if (!r) { const g = await fetch(`/api/list?kind=${type}s&q=${encodeURIComponent(id)}`).then((x) => x.json()).catch(() => null); setRow((g?.rows ?? []).find((x: R) => x[cfg.pk] === id) ?? null); if (!g) setErr(j.error ?? "Không tìm thấy"); } else setRow(r); }); for (const e of cfg.events) { const u = new URLSearchParams({ table: e.table, col: "id", agg: "count", bucket: "year", from: "2000-01-01", to: "2100-01-01", records: "1", t: "" }); u.set(`f.${e.filter}`, id); fetch(`/api/series/any?table=${e.table}&col=id&agg=count&bucket=year&from=2000-01-01&to=2100-01-01&f.${e.filter}=${encodeURIComponent(id)}`).then((r) => r.json()).then(async (jj) => { const t = jj.rows?.[jj.rows.length - 1]?.t; if (!t) return; const rec = await fetch(`/api/series/any?table=${e.table}&col=id&agg=count&bucket=year&records=1&t=${encodeURIComponent(t)}&f.${e.filter}=${encodeURIComponent(id)}`).then((r) => r.json()); setEv((prev) => ({ ...prev, [e.label]: rec.rows ?? [] })); }); } // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [type, id]);
  if (!cfg) return <div className="card">Chưa hỗ trợ loại đối tượng “{type}”. Thêm 1 mục vào CFG (Obj360.tsx).</div>;
  const attrs = row ? Object.entries(row).filter(([k, v]) => v !== null && v !== "" && !["farm_id", "org_id", "pin_hash", "qr_token", "search"].includes(k)) : [];
  return (
    <div className="space-y-3">
      <div className="card"><div className="flex items-center gap-2 flex-wrap"><span className="b-yel">{cfg.label}</span><b className="text-xl">{String(row?.name ?? row?.full_name ?? row?.title ?? row?.visual_tag ?? id)}</b><span className="font-mono text-sm text-stone-500">{id}</span><span className="ml-auto flex gap-2 text-sm">{cfg.links?.(id).map((l) => <a key={l.href} className="underline" href={l.href}>{l.label}</a>)}<a className="underline" href={`/quan-tri?t=${cfg.table}&pk=${encodeURIComponent(id)}`}>lịch sử</a></span></div>
        {err && <div className="text-red-700 text-sm">{err}</div>}
        {row ? <div className="grid grid-cols-2 sm:grid-cols-4 lg:grid-cols-6 gap-1 mt-2 text-sm">{attrs.slice(0, 36).map(([k, v]) => <div key={k} className="rounded-lg bg-stone-50 px-2 py-1"><div className="text-[10px] text-stone-500">{k}</div><div className="truncate font-semibold" title={String(typeof v === "object" ? JSON.stringify(v) : v)}>{typeof v === "object" ? JSON.stringify(v).slice(0, 40) : /^\d{4}-\d\d-\d\dT/.test(String(v)) ? fmt.dt(String(v)) : String(v)}</div></div>)}</div> : <div className="text-stone-500 text-sm mt-1">Đang tải thuộc tính…</div>}</div>
      <Attachments refTable={cfg.table} refId={id} />
      {cfg.charts.length > 0 && <div className="grid md:grid-cols-2 gap-3">{cfg.charts.map((ch) => <div key={ch.title} className="card"><AnyChart title={ch.title} table={ch.table} col={ch.col} agg={ch.agg ?? "sum"} dim={ch.dim ?? null} filters={{ [ch.filter]: id, ...(ch.extra ?? {}) }} bucket={ch.bucket ?? "week"} from={new Date(Date.now() - (ch.days ?? 90) * 86400e3).toISOString().slice(0, 10)} height={200} compare /></div>)}</div>}
      {Object.entries(ev).map(([label, rows]) => <div key={label} className="card p-0 overflow-auto"><div className="px-3 py-2 bg-stone-100 rounded-t-2xl font-bold">{label} — {rows.length} bản ghi gần nhất</div><RecordsTable rows={rows} /></div>)}
      <div className="text-xs text-stone-500">Trang 360 của {sess.farmId}: mọi số liệu ở đây đều là bản ghi gốc, bấm vào cột/điểm để xem ai ghi lúc nào. Muốn thêm số liệu cho đối tượng này → ghi bằng form 3 chạm (Ca của tôi) hoặc nhập CSV.</div>
    </div>);
}
