"use client";
import Tabs from "@/components/Tabs";
import { Term } from "@/components/ui/Term";
import { useUrlTab } from "@/lib/useUrlTab";
import { AlertSettings } from "@/components/panels/Notify";
import { CrmPanel, PosPanel, KenhPanel } from "@/components/panels/KinhDoanh";
import { KhachMessages } from "@/components/panels/Extra";
import { OrderActions, ReturnsPanel } from "@/components/panels/Fulfillment";
import { GiaPanel, BaoGiaPanel, ChiTieuPanel, DiemPanel, CongNoPanel, LichHDPanel } from "@/components/panels/SalesMore";
import { EpiPanel } from "@/components/panels/Pedigree";
import { useMemo, useState } from "react";
import Link from "next/link";
import ThreeTap from "@/components/ThreeTap";
import { buildForms, type Ref } from "@/lib/forms";
import { useData, act, fmt } from "@/lib/client";
import { OrderMarginPanel } from "@/components/panels/CloseoutBits";
import { toast } from "@/components/ui/Toast";
import type { Sess } from "@/components/Shell";
import { KpiTile, HourHistogram } from "./Dashboards";

const LV = (l: string) => (l === "DO" ? "b-red" : l === "VANG" || l === "CAM" ? "b-yel" : l === "OK" ? "b-grn" : "b-gray");

export function DoiSoatPanel({ sess }: { sess: Sess }) {
  const latest = useData("recon_latest"); const [rule, setRule] = useState<string | null>(null); const hist = useData(rule ? "recon_history" : null, { rule: rule ?? undefined });
  const [busy, setBusy] = useState(false); const [date, setDate] = useState(new Date(Date.now() - 86400e3).toISOString().slice(0, 10));
  return (
    <div className="space-y-3">
      <div className="card flex flex-wrap items-center gap-2"><b>Đối soát tự động</b> — <Term k="RC1" />, <Term k="RC2" />, <Term k="RC4" />, <Term k="RC7" />, <Term k="RC10" /> · <Term k="RC11">RC11 giấy–số</Term> · <Term k="RC12">RC12 tem</Term>. Chạy đêm 01:00; chạy tay: <input type="date" className="input !w-44" value={date} onChange={(e) => setDate(e.target.value)} />
        {["tech_head","director","owner","it_engineer"].includes(sess.role) && <button className="btn-primary !py-2" disabled={busy} onClick={async () => { setBusy(true); await fetch(`/api/jobs/recon?farm=${sess.farmId}&date=${date}`, { method: "POST" }); setBusy(false); latest.reload(); }}>{busy ? "…" : "▶ Chạy đối soát"}</button>}
        <a className="btn-secondary !py-2 ml-auto" href="/api/exports/recon">⬇ CSV</a></div>
      <div className="card p-0 overflow-auto"><table className="tbl"><thead><tr><th className="pl-3">Mã</th><th>Đối soát</th><th>Kỳ</th><th className="text-right">Vế A</th><th className="text-right">Vế B</th><th className="text-right">Lệch</th><th>Trạng thái</th><th></th></tr></thead><tbody>
        {(latest.rows ?? []).map((r) => <tr key={String(r.id)} className={r.status === "DO" ? "bg-red-50" : r.status === "VANG" ? "bg-amber-50" : ""}><td className="pl-3 font-bold"><button className="underline" onClick={() => setRule(String(r.rule_code))}>{String(r.rule_code)}</button></td><td>{String(r.name)}</td><td>{fmt.d(r.period)}</td><td className="text-right">{fmt.n(r.expected, 1)}</td><td className="text-right">{fmt.n(r.actual, 1)}</td><td className="text-right font-bold">{r.diff_pct != null ? fmt.n(r.diff_pct, 2) : "—"}</td><td><span className={LV(String(r.status))}>{String(r.status)}</span>{(r.detail as Record<string, unknown>)?.err ? <div className="text-xs text-red-700">{String((r.detail as Record<string, unknown>).err).slice(0, 80)}</div> : null}</td><td>{["DO","VANG"].includes(String(r.status)) && !r.acked_by && ["tech_head","director","owner"].includes(sess.role) && <button className="btn-secondary !py-1 !px-2 !text-sm" onClick={async () => { await act("ack_recon", { id: r.id }); latest.reload(); }}>Đã xem</button>}{r.acked_by ? <span className="text-xs">✓ {String(r.acked_by)}</span> : null}</td></tr>)}
        {latest.rows?.length === 0 && <tr><td colSpan={8} className="p-4 text-stone-500">Chưa có kết quả — bấm "Chạy đối soát".</td></tr>}</tbody></table></div>
      {rule && <div className="card"><h3 className="font-bold">Lịch sử {rule}</h3><table className="tbl"><thead><tr><th>Kỳ</th><th className="text-right">A</th><th className="text-right">B</th><th className="text-right">Lệch</th><th>TT</th></tr></thead><tbody>{(hist.rows ?? []).map((r) => <tr key={String(r.id)}><td>{fmt.d(r.period)}</td><td className="text-right">{fmt.n(r.expected, 1)}</td><td className="text-right">{fmt.n(r.actual, 1)}</td><td className="text-right">{fmt.n(r.diff_pct, 2)}</td><td><span className={LV(String(r.status))}>{String(r.status)}</span></td></tr>)}</tbody></table></div>}
    </div>);
}

export function CanhBaoPanel({ sess }: { sess: Sess }) {
  const open = useData("alerts_open"); const all = useData("alerts_all"); const grouped = useData("alerts_grouped"); const [tab, setTab] = useUrlTab(["open", "all", "group", "caidat"] as const, "group");
  const rows = tab === "open" ? open.rows : all.rows;
  return (
    <div className="space-y-3">
      <div className="flex gap-2 items-center">{[["group", "Theo luật (30 ngày)"], ["open", `Chưa xử lý (${open.rows?.length ?? 0})`], ["all", "Tất cả"], ["caidat", "⚙ Cài đặt cảnh báo · Hộp thư"]].map(([k, l]) => <button key={k} className={`px-4 py-2 rounded-xl font-semibold ${tab === k ? "bg-green-700 text-white" : "bg-white border"}`} onClick={() => setTab(k as typeof tab)}>{l}</button>)}
        {["tech_head","director","owner","it_engineer"].includes(sess.role) && <button className="btn-secondary !py-2 ml-auto" onClick={async () => { await fetch(`/api/jobs/alerts?farm=${sess.farmId}`, { method: "POST" }); open.reload(); all.reload(); }}>▶ Quét cảnh báo ngay</button>}</div>
      {tab === "caidat" && <AlertSettings sess={sess} />}
      {tab === "group" && <div className="card p-0 overflow-auto"><table className="tbl"><thead><tr><th className="pl-3">Luật</th><th>Mức</th><th className="text-right">Số lần</th><th className="text-right">Chưa xử lý</th><th>Lần cuối</th><th>Nội dung gần nhất</th></tr></thead><tbody>{(grouped.rows ?? []).map((g, i) => <tr key={i} className={Number(g.open) ? (g.level === "DO" ? "bg-red-50" : "bg-amber-50") : ""}><td className="pl-3 font-bold">{String(g.rule_code)}</td><td><span className={LV(String(g.level))}>{String(g.level)}</span></td><td className="text-right">{String(g.n)}</td><td className="text-right font-bold">{String(g.open)}</td><td className="text-sm">{fmt.dt(g.last_ts)}</td><td className="text-sm">{String(g.last_subject ?? "").slice(0, 90)}</td></tr>)}</tbody></table><div className="text-xs text-stone-500 px-3 py-2">Ở quy mô lớn xem theo luật trước; mở tab "Chưa xử lý" để ack từng cái. Cảnh báo lặp mỗi đêm (RC) không tràn màn.</div></div>}
      {tab !== "group" && <div className="space-y-2">{(rows ?? []).map((a) => <div key={String(a.id)} className={`card flex items-start gap-3 ${a.level === "DO" ? "border-red-400" : a.level === "VANG" ? "border-amber-300" : ""}`}><span className={LV(String(a.level))}>{String(a.level)}</span><div className="flex-1"><div className="font-semibold">{String(a.rule_code)} · {String(a.subject)}</div><div className="text-xs text-stone-500">{fmt.dt(a.ts)} {a.acked_by ? `· đã nhận ${String(a.acked_by)} ${fmt.dt(a.acked_at)}` : ""}</div></div>{!a.acked_by && <button className="btn-primary !py-1 !px-3 !text-sm" onClick={async () => { await act("ack_alert", { id: a.id }); open.reload(); all.reload(); }}>Đã nhận</button>}</div>)}{!rows?.length && <div className="card text-stone-500">Không có cảnh báo.</div>}</div>}
    </div>);
}

export function SopPanel({ code }: { code?: string }) {
  const sops = useData("sops"); const one = useData(code ? "sop" : null, { code });
  if (code) { const v = one.rows?.[0]; if (!v) return <div className="card">Đang tải…</div>;
    return (<div className="card space-y-2"><Link href="/sop" className="underline text-sm">← Thư viện</Link><h2 className="text-2xl font-bold">{String(v.code)} · {String(v.title)} <span className="b-gray">v{String(v.version)} {String(v.status)}</span></h2>
      <div className="grid sm:grid-cols-2 gap-2 text-sm"><div><b>Mục đích:</b> {String(v.purpose ?? "")}</div><div><b>Người được làm:</b> {String(v.allowed_roles ?? "")}</div><div><b>Công cụ:</b> {String(v.tools ?? "")}</div><div><b>Tần suất:</b> {String(v.frequency ?? "")}</div></div>
      <ol className="list-decimal pl-6 space-y-1">{((v.steps as { n: number; a: string }[]) ?? []).map((s) => <li key={s.n}>{s.a}</li>)}</ol>
      <div className="grid sm:grid-cols-2 gap-2 text-sm"><div><b>Chuẩn ĐẠT:</b> {String(v.pass_criteria ?? "")}</div><div><b>Lỗi thường gặp:</b> {String(v.common_errors ?? "")}</div><div><b>Bằng chứng:</b> {String(v.evidence ?? "")}</div><div><b>An toàn:</b> {String(v.safety ?? "")}</div><div><b>Điều khoản chuẩn (trường 11):</b> {String(v.std_clause ?? "")}</div><div><b>Ký:</b> {String(v.signed_by ?? "chưa")} · rà hạn {fmt.d(v.review_due)}</div></div>
      {v.video_url ? <a className="underline" href={String(v.video_url)}>▶ Video ≤5'</a> : null}</div>); }
  return (<div className="card p-0 overflow-auto"><div className="px-3 py-2 font-bold bg-stone-100 rounded-t-2xl">Thư viện SOP (chuẩn 10+1 trường) — không SOP ký = không giao việc</div><table className="tbl"><thead><tr><th className="pl-3">Mã</th><th>Tên</th><th>Bộ phận</th><th>Chuỗi/L2</th><th>Phiên bản</th><th>Rà hạn</th><th>Trạng thái</th></tr></thead><tbody>{(sops.rows ?? []).map((s) => <tr key={String(s.code)}><td className="pl-3 font-mono"><Link className="underline" href={`/sop/${s.code}`}>{String(s.code)}</Link></td><td>{String(s.title)}</td><td>{String(s.dept)}</td><td className="text-sm">{String(s.l2_group ?? "")}</td><td>{s.version ? `v${s.version}` : "—"}</td><td className={s.review_due && new Date(String(s.review_due)) < new Date(Date.now() + 30 * 86400e3) ? "text-amber-700" : ""}>{fmt.d(s.review_due)}</td><td><span className={s.status === "BAN_HANH" ? "b-grn" : "b-yel"}>{String(s.status)}</span></td></tr>)}</tbody></table></div>);
}

export function BanHangPanel({ sess }: { sess: Sess }) {
  const sales = useData("sales_recent"); const recv = useData("receivables"); const price = useData("price_list"); const orders = useData("orders"); const contracts = useData("contracts"); const cov = useData("contract_coverage"); const custody = useData("custody"); const aging = useData("receivable_aging");
  const [tab, setTab] = useUrlTab(["ban", "don", "hd", "nn", "crm", "pos", "kenh", "tra", "gia", "bg", "ct", "diem", "no", "lich", "margin"] as const, "ban", { "nhan-nuoi": "nn" }); const [of, setOf] = useState<Record<string, string>>({});
  const animals = useData("animals"), groups = useData("animal_groups"), warehouses = useData("warehouses"), products = useData("products"), plots = useData("plots"), recipes = useData("recipes"), locations = useData("locations"), sops = useData("sops"), devices = useData("devices"), partners = useData("partners");
  const ref: Ref | null = useMemo(() => animals.rows && groups.rows && warehouses.rows && products.rows && plots.rows && recipes.rows && locations.rows && sops.rows && devices.rows && partners.rows ? { animals: animals.rows, groups: groups.rows, warehouses: warehouses.rows, products: products.rows, plots: plots.rows, recipes: recipes.rows, locations: locations.rows, sops: sops.rows, devices: devices.rows, partners: partners.rows } : null, [animals.rows, groups.rows, warehouses.rows, products.rows, plots.rows, recipes.rows, locations.rows, sops.rows, devices.rows, partners.rows]);
  const forms = ref ? buildForms(ref, sess.farmId) : null;
  const floor = (sku: string) => price.rows?.find((p) => p.kind === "SAN" && p.subject === sku)?.price;
  const byChannel = useMemo(() => { const m: Record<string, number> = {}; for (const s of sales.rows ?? []) m[String(s.channel)] = (m[String(s.channel)] ?? 0) + Number(s.amount); return m; }, [sales.rows]);
  const tot = Object.values(byChannel).reduce((a, b) => a + b, 0);
  return (
    <div className="space-y-3">
      <div className="grid grid-cols-2 sm:grid-cols-5 gap-2">{[1, 2, 3, 4, 5].map((c) => <KpiTile key={c} l={`Kênh ${c}`} v={tot ? `${Math.round((100 * (byChannel[String(c)] ?? 0)) / tot)}%` : "—"} sub={fmt.vnd(byChannel[String(c)] ?? 0)} warn={tot && (byChannel[String(c)] ?? 0) / tot > 0.4 ? "yel" : null} />)}</div>
      <div className="text-xs text-stone-500">Luật: không kênh nào &gt;40% doanh thu một SKU · ≥70% sản lượng có hợp đồng trước · công nợ ≤15 ngày, &gt;30 ngày ngừng giao · giá sàn (bảng giá SAN) — bán dưới sàn cần GĐ duyệt.</div>
      <Tabs items={[["ban", "Bán hàng · Bán / giao"], ["don", `Bán hàng · Đơn hàng (${(orders.rows ?? []).filter((o) => !["HOAN_TAT","HUY"].includes(String(o.status))).length})`], ["tra", "Bán hàng · Trả hàng"], ["bg", "Bán hàng · Báo giá"], ["gia", "Giá · Giá theo khách, bậc CK"], ["hd", "Hợp đồng · Bao tiêu"], ["lich", "Hợp đồng · Lịch giao"], ["nn", "Hợp đồng · Nhận nuôi / chăm sóc hộ"], ["crm", "Khách · CRM tiềm năng"], ["diem", "Khách · Điểm thưởng"], ["no", "Khách · Công nợ hạn, nhắc nợ"], ["margin", "💰 Lãi gộp theo đơn"], ["pos", "Kênh · POS cửa hàng"], ["kenh", "Kênh · Online, khuyến mãi"], ["ct", "NVKD · Chỉ tiêu, hoa hồng"]]} value={tab} onChange={(k) => setTab(k as typeof tab)} />
      {tab === "margin" && <OrderMarginPanel sess={sess} />}
      {tab === "nn" && <KhachMessages />}
      {tab === "tra" && <ReturnsPanel sess={sess} />}
      {tab === "gia" && <GiaPanel sess={sess} />}{tab === "bg" && <BaoGiaPanel sess={sess} />}{tab === "ct" && <ChiTieuPanel />}{tab === "diem" && <DiemPanel />}{tab === "no" && <CongNoPanel sess={sess} />}{tab === "lich" && <LichHDPanel />}
      {tab === "crm" && <CrmPanel sess={sess} />}
      {tab === "pos" && <PosPanel sess={sess} />}
      {tab === "kenh" && <KenhPanel />}
      {tab === "don" && <div className="space-y-3">
        <div className="card"><h3 className="font-bold">Đơn hàng — chốt trước 15h → lệnh sản xuất/đóng gói hôm sau (SLA10)</h3><div className="flex flex-wrap gap-2 mt-2"><select className="input !w-56" value={of.partner_id ?? ""} onChange={(e) => setOf({ ...of, partner_id: e.target.value })}><option value="">Khách</option>{(partners.rows ?? []).filter((p) => String(p.kind).includes("KH")).map((p) => <option key={String(p.id)} value={String(p.id)}>{String(p.name)}</option>)}</select><select className="input !w-56" value={of.sku ?? ""} onChange={(e) => setOf({ ...of, sku: e.target.value })}><option value="">SKU</option>{(products.rows ?? []).filter((p) => ["THANH_PHAM","BAN_TP"].includes(String(p.kind))).map((p) => <option key={String(p.sku)} value={String(p.sku)}>{String(p.name)}</option>)}</select><input className="input !w-24" type="number" placeholder="SL" value={of.qty ?? ""} onChange={(e) => setOf({ ...of, qty: e.target.value })} /><input className="input !w-32" type="number" placeholder="Giá" value={of.price ?? ""} onChange={(e) => setOf({ ...of, price: e.target.value })} /><input className="input !w-40" type="date" value={of.deliver_date ?? ""} onChange={(e) => setOf({ ...of, deliver_date: e.target.value })} /><button className="btn-primary !py-2" onClick={async () => { if (!of.partner_id || !of.sku || !of.qty) return; const j = await act("create_order", { partner_id: of.partner_id, channel: 1, deliver_date: of.deliver_date || null, lines: [{ sku: of.sku, qty: Number(of.qty), price: Number(of.price || 0) }] }); if (j.id) toast.ok(`Đơn ${j.id}`); else toast.err(j.error); setOf({}); orders.reload(); }}>Chốt đơn</button></div></div>
        <div className="card p-0 overflow-auto"><table className="tbl"><thead><tr><th className="pl-3">Đơn</th><th>Khách</th><th>Giao</th><th>Hàng</th><th className="text-right">Tiền</th><th>Chốt ≤15h</th><th>TT</th><th></th></tr></thead><tbody>{(orders.rows ?? []).map((o) => <tr key={String(o.id)}><td className="pl-3 font-mono">{String(o.id)}</td><td>{String(o.partner_name)}</td><td>{fmt.d(o.deliver_date)}</td><td className="text-sm">{(o.lines as { sku: string; qty: number }[]).map((l) => `${l.sku}×${l.qty}`).join(", ")}</td><td className="text-right">{fmt.vnd(o.total)}</td><td>{o.cutoff_ok ? <span className="b-grn">đúng</span> : <span className="b-yel">trễ</span>}</td><td><span className="b-gray">{String(o.status)}</span></td><td><OrderActions o={o} onDone={() => orders.reload()} /></td></tr>)}</tbody></table></div>
        <div className="text-xs text-slate-500">Luồng: Nhập → <b>Giữ hàng</b> (FEFO theo lô; thiếu → tự sinh lệnh SX cho D5) → Chốt → <b>Phiếu soạn</b> (in cho kho) → <b>Xuất kho</b> (từng lô, → GIAO) → Hoàn tất. Đơn từ sàn/portal cũng vào đây.</div></div>}
      {tab === "hd" && <div className="space-y-3">
        <div className="grid grid-cols-2 sm:grid-cols-3 gap-2"><KpiTile l="Sản lượng cam kết (HĐ hiệu lực)" v={fmt.n(cov.rows?.[0]?.committed)} /><KpiTile l="Đã bán quý này" v={fmt.n(cov.rows?.[0]?.sold_q)} /><KpiTile l="Luật ≥70% sản lượng có HĐ trước khi tăng đàn" v="theo dõi" sub="ghi HĐ đầy đủ để tính" /></div>
        <div className="card"><div className="flex flex-wrap gap-2"><select className="input !w-56" value={of.c_partner ?? ""} onChange={(e) => setOf({ ...of, c_partner: e.target.value })}><option value="">Đối tác</option>{(partners.rows ?? []).map((p) => <option key={String(p.id)} value={String(p.id)}>{String(p.name)}</option>)}</select><select className="input !w-40" value={of.c_kind ?? "BAO_TIEU"} onChange={(e) => setOf({ ...of, c_kind: e.target.value })}>{["BAO_TIEU","B2B","LIEN_KET_HO","NHUONG_QUYEN","NHAP_KHAU","XUAT_KHAU"].map((k) => <option key={k}>{k}</option>)}</select><select className="input !w-48" value={of.c_sku ?? ""} onChange={(e) => setOf({ ...of, c_sku: e.target.value })}><option value="">SKU</option>{(products.rows ?? []).map((p) => <option key={String(p.sku)} value={String(p.sku)}>{String(p.name)}</option>)}</select><input className="input !w-32" type="number" placeholder="SL cam kết" value={of.c_qty ?? ""} onChange={(e) => setOf({ ...of, c_qty: e.target.value })} /><input className="input !w-32" type="number" placeholder="Giá" value={of.c_price ?? ""} onChange={(e) => setOf({ ...of, c_price: e.target.value })} /><input className="input !w-40" type="date" value={of.c_end ?? ""} onChange={(e) => setOf({ ...of, c_end: e.target.value })} /><button className="btn-secondary !py-2" onClick={async () => { if (!of.c_partner) return; await act("create_contract", { partner_id: of.c_partner, kind: of.c_kind ?? "BAO_TIEU", sku: of.c_sku || null, qty_committed: Number(of.c_qty || 0) || null, price: Number(of.c_price || 0) || null, start_date: new Date().toISOString().slice(0, 10), end_date: of.c_end || null }); setOf({}); contracts.reload(); cov.reload(); }}>+ Hợp đồng</button></div></div>
        <div className="card p-0 overflow-auto"><table className="tbl"><thead><tr><th className="pl-3">HĐ</th><th>Đối tác</th><th>Loại</th><th>SKU</th><th className="text-right">Cam kết</th><th className="text-right">Đã giao</th><th>Hết hạn</th></tr></thead><tbody>{(contracts.rows ?? []).map((c) => <tr key={String(c.id)}><td className="pl-3 font-mono">{String(c.id)}</td><td>{String(c.partner_name)}</td><td>{String(c.kind)}</td><td>{String(c.sku ?? "")}</td><td className="text-right">{fmt.n(c.qty_committed)}</td><td className="text-right font-bold">{fmt.n(c.delivered)}</td><td>{fmt.d(c.end_date)}</td></tr>)}</tbody></table></div></div>}
      {tab === "nn" && <div className="space-y-3">
        <div className="card"><h3 className="font-bold">Chăm sóc hộ / nhận nuôi (thu trước = nợ dịch vụ, đối ứng 30%; khách xem hồ sơ + QR con vật)</h3><div className="flex flex-wrap gap-2 mt-2"><select className="input !w-56" value={of.n_partner ?? ""} onChange={(e) => setOf({ ...of, n_partner: e.target.value })}><option value="">Khách</option>{(partners.rows ?? []).filter((p) => String(p.kind).includes("KH")).map((p) => <option key={String(p.id)} value={String(p.id)}>{String(p.name)}</option>)}</select><select className="input !w-40" value={of.n_kind ?? "NHAN_NUOI"} onChange={(e) => setOf({ ...of, n_kind: e.target.value })}>{["NHAN_NUOI","KY_GUI","DAU_TU","TANG"].map((k) => <option key={k}>{k}</option>)}</select><input className="input !w-64" placeholder="Mã con (F01-BO-…, cách nhau dấu phẩy)" value={of.n_animals ?? ""} onChange={(e) => setOf({ ...of, n_animals: e.target.value })} /><input className="input !w-32" type="number" placeholder="Phí/kỳ" value={of.n_fee ?? ""} onChange={(e) => setOf({ ...of, n_fee: e.target.value })} /><input className="input !w-24" type="number" placeholder="Tháng" value={of.n_m ?? ""} onChange={(e) => setOf({ ...of, n_m: e.target.value })} /><input className="input !w-36" type="number" placeholder="Thu trước" value={of.n_pre ?? ""} onChange={(e) => setOf({ ...of, n_pre: e.target.value })} /><button className="btn-primary !py-2" onClick={async () => { if (!of.n_partner) return; const j = await act("create_custody", { partner_id: of.n_partner, kind: of.n_kind ?? "NHAN_NUOI", animal_ids: (of.n_animals ?? "").split(",").map((x) => x.trim()).filter(Boolean), fee: Number(of.n_fee || 0) || null, period_months: Number(of.n_m || 0) || null, prepaid: Number(of.n_pre || 0) || null }); if (j.id) toast.ok(`Hợp đồng ${j.id}`); else toast.err(j.error); setOf({}); custody.reload(); }}>+ Hợp đồng chăm sóc</button></div></div>
        <div className="card p-0 overflow-auto"><table className="tbl"><thead><tr><th className="pl-3">Mã</th><th>Khách</th><th>Loại</th><th>Con</th><th className="text-right">Phí/kỳ</th><th className="text-right">Thu trước</th><th>Bắt đầu</th><th>TT</th></tr></thead><tbody>{(custody.rows ?? []).map((c) => <tr key={String(c.id)}><td className="pl-3 font-mono">{String(c.id)}</td><td>{String(c.partner_name)}</td><td>{String(c.kind)}</td><td className="text-sm">{(c.animal_ids as string[]).map((a) => <Link key={a} className="underline mr-1" href={`/dan/${a}`}>{a.slice(-5)}</Link>)}</td><td className="text-right">{fmt.vnd(c.fee)}</td><td className="text-right">{fmt.vnd(c.prepaid)}</td><td>{fmt.d(c.start_date)}</td><td><span className="b-grn">{String(c.status)}</span></td></tr>)}</tbody></table></div>
        <div className="text-xs text-stone-500">Đợt sau: cổng khách hàng (ảnh mốc, camera theo khung giờ, chat SLA), báo cáo tháng tự sinh cho từng khách.</div></div>}
      {tab === "ban" && forms && ["worker","team_lead","director","accountant"].includes(sess.role) && <ThreeTap spec={{ ...forms.sale, onDone: () => { sales.reload(); recv.reload(); } }} />}
      {tab === "ban" && <div className="grid md:grid-cols-2 gap-3">
        <div className="card p-0 overflow-auto"><div className="px-3 py-2 font-bold bg-stone-100 rounded-t-2xl">Bán gần đây</div><table className="tbl"><thead><tr><th className="pl-3">Lúc</th><th>Khách</th><th>SKU</th><th className="text-right">SL</th><th className="text-right">Giá</th><th className="text-right">Tiền</th><th>Kênh</th><th>TT</th></tr></thead><tbody>{(sales.rows ?? []).map((s) => <tr key={String(s.id)} className={floor(String(s.sku)) && Number(s.price) < Number(floor(String(s.sku))) ? "bg-red-50" : ""}><td className="pl-3">{fmt.dt(s.ts)}</td><td>{String(s.partner_name)}</td><td className="text-xs">{String(s.sku)}</td><td className="text-right">{fmt.n(s.qty)}</td><td className="text-right">{fmt.vnd(s.price)}{floor(String(s.sku)) && Number(s.price) < Number(floor(String(s.sku))) ? <span className="b-red ml-1">dưới sàn</span> : null}</td><td className="text-right font-bold">{fmt.vnd(s.amount)}</td><td>{String(s.channel)}</td><td>{s.paid ? <span className="b-grn">{String(s.payment)}</span> : <span className="b-yel">nợ</span>}</td></tr>)}</tbody></table></div>
        <div className="card"><h3 className="font-bold">Công nợ</h3><table className="tbl"><tbody>{(recv.rows ?? []).map((r) => <tr key={String(r.id)}><td>{String(r.name)}</td><td className="text-right">{fmt.vnd(r.unpaid)}</td><td className={Number(r.days) > 30 ? "text-red-700 font-bold" : Number(r.days) > 15 ? "text-amber-700" : ""}>{String(r.days)} ngày {Number(r.days) > 30 && "· NGỪNG GIAO"}</td></tr>)}</tbody></table>
          <h3 className="font-bold mt-3">Tuổi nợ</h3><table className="tbl"><tbody>{(aging.rows ?? []).map((r) => <tr key={String(r.partner_id)}><td>{String(r.name)}</td><td className="text-right">{fmt.vnd(r.d0_15 ?? 0)}</td><td className="text-right">{fmt.vnd(r.d16_30 ?? 0)}</td><td className={`text-right ${Number(r.d30p) > 0 ? "text-red-700 font-bold" : ""}`}>{fmt.vnd(r.d30p ?? 0)}</td></tr>)}</tbody></table>
          <h3 className="font-bold mt-3">Bảng giá tham chiếu</h3><table className="tbl"><tbody>{(price.rows ?? []).map((p) => <tr key={String(p.id)}><td>{String(p.kind)}</td><td>{String(p.subject)}</td><td className="text-right">{fmt.vnd(p.price)}</td><td className="text-xs">{String(p.unit ?? "")} · {String(p.source ?? "")}</td></tr>)}</tbody></table></div>
      </div>}
    </div>);
}

export function TracePanel({ lot: initial }: { lot?: string }) {
  const [lot, setLot] = useState(initial ?? ""); const [q, setQ] = useState(initial ?? "");
  const tree = useData(q ? "trace_lot" : null, { lot: q }); const cust = useData(q ? "trace_customers" : null, { lot: q }); const l = useData(q ? "lot" : null, { lot: q });
  const [recall, setRecall] = useState<{ start: number; end?: number } | null>(null);
  const back = (tree.rows ?? []).filter((r) => r.dir === "BACK"), fwd = (tree.rows ?? []).filter((r) => r.dir === "FWD");
  return (
    <div className="space-y-3">
      <div className="card flex flex-wrap gap-2 items-center"><input className="input flex-1 !min-w-[260px]" placeholder="Mã lô / mã mẻ (F01-LOT-… hoặc F01-ME-…)" value={lot} onChange={(e) => setLot(e.target.value)} /><button className="btn-primary !py-2" onClick={() => { setQ(lot.trim()); setRecall({ start: Date.now() }); }}>Truy xuất 2 chiều</button>{q && <a className="btn-secondary !py-2" href={`/api/exports/epcis?lot=${encodeURIComponent(q)}`} target="_blank">EPCIS 2.0 JSON-LD</a>}</div>
      {q && (<div className="grid md:grid-cols-3 gap-3">
        <div className="card"><h3 className="font-bold">Lô</h3>{l.rows?.[0] ? <div className="text-sm">{String(l.rows[0].product_name)}<br />lô {String(l.rows[0].lot_no)} · NCC {String(l.rows[0].supplier_id ?? "nội bộ")}<br />hạn {fmt.d(l.rows[0].expiry_date)} · <span className={l.rows[0].status === "KHA_DUNG" ? "b-grn" : "b-red"}>{String(l.rows[0].status)}</span></div> : <div className="text-stone-500 text-sm">Không thấy trong bảng lots (có thể là mã mẻ).</div>}</div>
        <div className="card"><h3 className="font-bold">← 1 bước lùi (nguyên liệu)</h3><ul className="text-sm">{back.map((r, i) => <li key={i}>{"—".repeat(Number(r.depth))} {String(r.input_lot)} <span className="text-stone-500">(mẻ {String(r.batch_code)})</span></li>)}{!back.length && <li className="text-stone-500">Không có mẻ dùng lô này làm đầu ra.</li>}</ul></div>
        <div className="card"><h3 className="font-bold">→ 1 bước tiến (sản phẩm · khách)</h3><ul className="text-sm">{fwd.map((r, i) => <li key={i}>{"—".repeat(Number(r.depth))} {String(r.output_lot)} <span className="text-stone-500">(mẻ {String(r.batch_code)})</span></li>)}</ul><h4 className="font-semibold mt-2">Khách đã nhận lô này</h4><ul className="text-sm">{(cust.rows ?? []).map((c, i) => <li key={i}>{fmt.dt(c.ts)} · <b>{String(c.name)}</b> {String(c.phone ?? "")} · {fmt.n(c.qty)} {String(c.unit ?? "")}</li>)}{cust.rows?.length === 0 && <li className="text-stone-500">Chưa bán lô này.</li>}</ul>
          {recall && cust.rows && <div className="mt-2 text-xs text-stone-500">Mock recall: danh sách khách nhận trong {((Date.now() - recall.start) / 1000).toFixed(1)}s (chuẩn ≤ 4h).</div>}</div>
      </div>)}
    </div>);
}

const Q = ({ q, v, ok }: { q: string; v: React.ReactNode; ok: boolean }) => <div className={`card ${ok ? "" : "border-red-300 bg-red-50"}`}><div className="text-sm">{q}</div><div className="text-2xl font-bold">{v}</div></div>;
export function SucKhoePanel({ sess }: { sess: Sess }) {
  const g = useData("governance"); const r = g.rows?.[0] as Record<string, unknown> | undefined;
  const hist = (r?.hour_hist as { h: number; n: number }[] | null) ?? []; const byStaff = (r?.by_staff as { name: string; n: number }[] | null) ?? [];
  const rows = hist.flatMap((x) => Array.from({ length: Number(x.n) }, () => ({ ts: new Date(2026, 0, 1, Number(x.h)).toISOString() })));
  return (
    <div className="space-y-4">
      <EpiPanel />
      <p className="text-sm text-stone-600">7 bộ câu chất vấn (chủ đầu tư/GĐ/kế toán hỏi định kỳ). Số đỏ = phải xử lý.</p>
      <h3 className="font-bold">Bộ 1 · Nền có đúng không</h3>
      <div className="grid sm:grid-cols-3 gap-2"><Q q="Thêm trại F02 có phải sửa code?" v={`Không — ${String(r?.farms_total ?? "…")} trại trong bảng farms`} ok /><Q q="Đổi giờ cữ ăn/ngưỡng phải sửa code?" v={`Không — bảng settings (${String(r?.farm_setting_overrides ?? 0)} ghi đè theo trại)`} ok /><Q q="Có bản ghi nào bị UPDATE/DELETE?" v="Không — trigger chặn ở DB, chỉ supersede/void" ok /></div>
      <div className="grid sm:grid-cols-3 gap-2"><Q q="Rút toàn bộ dữ liệu 1 lệnh?" v={<a className="underline" href="/api/exports/all">/api/exports/all (ZIP)</a>} ok /><Q q="Dựng lại trên Postgres trắng 1 buổi?" v="pnpm db:migrate (7 migration) — diễn tập quý" ok /><Q q="Tính năng mới chỉ ra được ai ghi/bao nhiêu/RC nào?" v="Bắt buộc trong DoD" ok /></div>
      <h3 className="font-bold">Bộ 2 · Số có tin được không (thứ 6)</h3>
      <div className="grid sm:grid-cols-3 gap-2"><Q q="RC lệch treo >48h chưa ai xem" v={String(r?.rc_hanging_48h ?? "…")} ok={Number(r?.rc_hanging_48h ?? 0) === 0} /><Q q="Phiếu giấy >24h chưa số hóa" v={String(r?.paper_late ?? "…")} ok={Number(r?.paper_late ?? 0) === 0} /><Q q="Số bấm 2 lần ra bản ghi gốc + tên người ghi?" v="Đàn → sự kiện → người ghi; Kho → thẻ kho" ok /></div>
      <h3 className="font-bold">Bộ 3 · Công nhân có dùng thật không (tháng)</h3>
      <div className="grid sm:grid-cols-3 gap-2"><Q q="% nhập bù (sự kiện vật nuôi / cho ăn) 30 ngày" v={`${String(r?.backfill_pct_animal ?? 0)}% / ${String(r?.backfill_pct_feed ?? 0)}%`} ok={Number(r?.backfill_pct_animal ?? 0) <= 5 && Number(r?.backfill_pct_feed ?? 0) <= 5} /><Q q="Công nhân 7 ngày không ghi gì (quay lại sổ giấy riêng?)" v={String(r?.workers_silent_7d ?? "…")} ok={Number(r?.workers_silent_7d ?? 0) === 0} /><div className="card"><div className="text-sm">Giờ ghi 7 ngày: rải theo ca hay dồn cục cuối ngày (ghi hồi ký)?</div><HourHistogram rows={rows} /><div className="text-xs text-stone-500">0h → 23h</div></div></div>
      <div className="card"><div className="text-sm font-semibold">Bản ghi 7 ngày theo người</div><div className="flex flex-wrap gap-2 mt-1">{byStaff.map((s) => <span key={s.name} className="b-gray">{s.name}: {s.n}</span>)}</div></div>
      <h3 className="font-bold">Bộ 5 · Tiền có khớp không (kế toán) — 4 số phải bằng 0</h3>
      <div className="grid sm:grid-cols-4 gap-2"><Q q="Chi >20tr thiếu chữ ký thứ 2" v={String(r?.expense_missing_sig ?? "…")} ok={Number(r?.expense_missing_sig ?? 0) === 0} /><Q q="Nhập mua không có PO duyệt (30 ngày)" v={String(r?.receipts_without_po ?? "…")} ok={Number(r?.receipts_without_po ?? 0) === 0} /><Q q="Bán dưới giá sàn (30 ngày)" v={String(r?.sales_below_floor ?? "…")} ok={Number(r?.sales_below_floor ?? 0) === 0} /><Q q="Khách nợ >30 ngày vẫn được giao (7 ngày)" v={String(r?.delivered_to_overdue ?? "…")} ok={Number(r?.delivered_to_overdue ?? 0) === 0} /></div>
      <h3 className="font-bold">Bộ 4 · 6 · 7</h3>
      <div className="grid sm:grid-cols-3 gap-2 text-sm"><div className="card"><b>Mất thứ X thì sao (diễn tập quý)</b><ul className="list-disc pl-5"><li>Mất mạng 3 ngày: app ghi offline (hàng đợi), phiếu giấy BM01–10</li><li>Mất điện thoại: thu hồi phiên (Tài khoản → thu hồi)</li><li>DB sập: restore backup + <code>pnpm db:migrate</code></li><li>Mất dev: repo + 7 migration + CLAUDE.md dựng lại</li></ul></div><div className="card"><b>Phần mềm có đi trước trại không (tháng)</b><ul className="list-disc pl-5"><li>Module &lt;10 bản ghi/ngày đang xây? → xem bảng người ghi ở trên</li><li>Connector chỉ mở khi có doanh thu thật (luật file 05 §6b)</li></ul></div><div className="card"><b>Sẵn sàng audit & nhân rộng</b><ul className="list-disc pl-5"><li><a className="underline" href="/audit">Gói audit 24h</a> — thử thật</li><li><a className="underline" href="/truy-xuat">Mock recall</a> — đo giây</li><li>Thế số F02: thêm dòng farms + Phụ lục</li></ul></div></div>
      <div className="text-xs text-stone-500">Trại {sess.farmId} · dữ liệu tính trực tiếp từ bảng sự kiện.</div>
    </div>);
}
