"use client";
import { useState } from "react";
import { useData, act, fmt } from "@/lib/client";
import type { Sess } from "@/components/Shell";
type R = Record<string, unknown>;
const adminPost = (t: string, row: R) => fetch(`/api/admin/${t}`, { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ row }) }).then((r) => r.json());
/** BẢNG LƯƠNG ĐẦY ĐỦ: lương cơ bản × công (chấm công) + thưởng KPI + phụ cấp − BHXH/BHYT/BHTN − thuế TNCN lũy tiến − tạm ứng → net; duyệt → GL 622/334/338/333 */
export function PayrollPanel({ sess }: { sess: Sess }) {
  const runs = useData("payroll_runs"); const [month, setMonth] = useState(new Date().toISOString().slice(0, 7)); const slips = useData("payslips", { month: month + "-01" }); const [msg, setMsg] = useState("");
  const canA = ["owner", "director", "accountant"].includes(sess.role); const run = (runs.rows ?? []).find((r) => String(r.month).slice(0, 7) === month);
  const S = slips.rows ?? []; const sum = (k: string) => S.reduce((a, r) => a + Number(r[k] ?? 0), 0);
  return (<div className="card space-y-2"><div className="flex items-center gap-2 flex-wrap"><b>Bảng lương</b><input type="month" className="input !w-40 !py-1" value={month} onChange={(e) => setMonth(e.target.value)} />{run && <span className={run.status === "DUYET" ? "b-grn" : "b-yel"}>{String(run.status)}</span>}{canA && <button className="btn-secondary !py-1 !px-3 !text-sm" onClick={async () => { const j = await act("compute_payroll", { month: month + "-01" }); setMsg(j.ok ? "Đã tính bảng lương (từ chấm công, KPI, nghỉ phép, tạm ứng)" : String(j.error)); runs.reload(); slips.reload(); }}>▶ Tính lương</button>}{canA && run && run.status === "NHAP" && <button className="btn-primary !py-1 !px-3 !text-sm" onClick={async () => { const j = await act("approve_payroll", { run_id: run.id }); setMsg(j.ok ? "Đã duyệt → hạch toán 622/334/338/333" : String(j.error)); runs.reload(); }}>Duyệt & hạch toán</button>}<a className="underline text-sm ml-auto" href={`/api/admin/payslips?csv=1`}>xuất CSV (ngân hàng/BHXH)</a><a className="underline text-sm" href="/quan-tri?t=settings">tham số (BH%, giảm trừ, công chuẩn)</a></div>
    {msg && <div className="text-sm text-emerald-800">{msg}</div>}
    <div className="grid grid-cols-2 sm:grid-cols-5 gap-2 text-sm">{[["Tổng gross", sum("gross")], ["BH người LĐ", sum("bhxh") + sum("bhyt") + sum("bhtn")], ["Thuế TNCN", sum("pit")], ["Thực lĩnh", sum("net")], ["BH chủ trả", sum("employer_ins")]].map(([l, v]) => <div key={String(l)} className="kpi !p-2"><div className="l">{String(l)}</div><div className="font-bold">{fmt.vnd(v)}</div></div>)}</div>
    <div className="overflow-auto"><table className="tbl text-xs"><thead><tr><th className="pl-2">NV</th><th className="text-right">Cơ bản</th><th className="text-right">Công</th><th className="text-right">Theo công</th><th className="text-right">KPI</th><th className="text-right">Thưởng KPI</th><th className="text-right">Phụ cấp</th><th className="text-right">Gross</th><th className="text-right">BHXH/YT/TN</th><th className="text-right">Thuế</th><th className="text-right">Tạm ứng</th><th className="text-right">Thực lĩnh</th><th></th></tr></thead><tbody>{S.map((r) => <tr key={String(r.id)}><td className="pl-2 font-mono">{String(r.staff_id)} <span className="text-slate-500">{String(r.full_name ?? "")}</span>{(r.detail as R)?.note ? <div className="text-amber-700">{String((r.detail as R).note)}</div> : null}</td><td className="text-right">{fmt.vnd(r.base_salary)}</td><td className="text-right">{String(r.work_days)}{Number(r.paid_leave_days) ? `+${r.paid_leave_days}P` : ""}/{String(r.standard_days)}</td><td className="text-right">{fmt.vnd(r.salary_by_days)}</td><td className="text-right">{r.kpi_score != null ? String(r.kpi_score) : "—"}</td><td className="text-right">{fmt.vnd(r.kpi_bonus)}</td><td className="text-right">{fmt.vnd(r.allowances)}</td><td className="text-right font-semibold">{fmt.vnd(r.gross)}</td><td className="text-right">{fmt.vnd(Number(r.bhxh) + Number(r.bhyt) + Number(r.bhtn))}</td><td className="text-right">{fmt.vnd(r.pit)}</td><td className="text-right">{fmt.vnd(r.advances)}</td><td className="text-right font-bold">{fmt.vnd(r.net)}</td><td><a className="underline" href={`/in/phieu-luong/${r.id}`} target="_blank">phiếu</a></td></tr>)}</tbody></table>{!S.length && <div className="text-slate-500 text-sm p-2">Chưa tính tháng này.</div>}</div>
    <div className="text-xs text-slate-500">Lương cơ bản/phụ cấp/người phụ thuộc/lương BH: sửa ở Quản trị DL › staff (salary_base, allowances JSON, dependents, insurance_salary). Chưa chấm công → tạm tính đủ công (ghi chú vàng).</div></div>);
}
/** TÀI SẢN CỐ ĐỊNH & KHẤU HAO đường thẳng hằng tháng → 214 */
export function AssetsPanel({ sess }: { sess: Sess }) {
  const assets = useData("fixed_assets"); const [f, setF] = useState<R | null>(null); const [msg, setMsg] = useState(""); const canA = ["owner", "director", "accountant"].includes(sess.role);
  const A = assets.rows ?? [];
  return (<div className="card space-y-2"><div className="flex items-center gap-2 flex-wrap"><b>Tài sản cố định ({A.length}) — nguyên giá {fmt.vnd(A.reduce((a, r) => a + Number(r.cost), 0))} · còn lại {fmt.vnd(A.reduce((a, r) => a + Number(r.remaining), 0))}</b>{canA && <button className="btn-secondary !py-1 !px-3 !text-sm" onClick={() => setF({ kind: "MAY_MOC", life_months: 60, start_date: new Date().toISOString().slice(0, 10), gl_expense: "627" })}>＋ Tài sản</button>}{canA && <button className="btn-primary !py-1 !px-3 !text-sm" onClick={async () => { const j = await act("run_depreciation", {}); setMsg(j.ok ? `Đã trích khấu hao ${j.n} tài sản tháng này → GL 627/642 ↔ 214` : String(j.error)); assets.reload(); }}>▶ Trích khấu hao tháng</button>}<span className="text-xs text-slate-500 ml-auto">Tự chạy 01:15 mỗi đầu tháng (job đêm)</span></div>
    {msg && <div className="text-sm text-emerald-800">{msg}</div>}
    {f && <div className="grid sm:grid-cols-3 lg:grid-cols-6 gap-2 text-sm"><input className="input lg:col-span-2" placeholder="Tên tài sản" aria-label="Tên tài sản" value={String(f.name ?? "")} onChange={(e) => setF({ ...f, name: e.target.value })} /><select className="input" value={String(f.kind)} onChange={(e) => setF({ ...f, kind: e.target.value })}>{["NHA_XUONG", "MAY_MOC", "PHUONG_TIEN", "THIET_BI", "VAT_NUOI_SS", "CAY_LAU_NAM", "KHAC"].map((k) => <option key={k}>{k}</option>)}</select><input className="input" type="number" placeholder="Nguyên giá" aria-label="Nguyên giá" value={String(f.cost ?? "")} onChange={(e) => setF({ ...f, cost: Number(e.target.value) })} /><input className="input" type="number" placeholder="Số tháng KH" aria-label="Số tháng KH" value={String(f.life_months ?? "")} onChange={(e) => setF({ ...f, life_months: Number(e.target.value) })} /><input className="input" type="date" value={String(f.start_date)} onChange={(e) => setF({ ...f, start_date: e.target.value })} /><input className="input" placeholder="CC (F01-CC-D5)" aria-label="CC (F01-CC-D5)" value={String(f.cost_center ?? "")} onChange={(e) => setF({ ...f, cost_center: e.target.value })} /><select className="input" value={String(f.gl_expense)} onChange={(e) => setF({ ...f, gl_expense: e.target.value })}><option value="627">627 SX chung</option><option value="641">641 Bán hàng</option><option value="642">642 Quản lý</option></select><input className="input" type="number" placeholder="Giá trị thu hồi" aria-label="Giá trị thu hồi" value={String(f.salvage ?? "")} onChange={(e) => setF({ ...f, salvage: Number(e.target.value) })} /><div className="flex gap-2"><button className="btn-primary !py-2" onClick={async () => { const j = await adminPost("fixed_assets", { ...f, created_by: sess.staffId }); setMsg(j.ok ? "Đã thêm tài sản" : `${j.error}: ${j.detail ?? ""}`); setF(null); assets.reload(); }}>Lưu</button><button className="btn-secondary !py-2" onClick={() => setF(null)}>Hủy</button></div></div>}
    <div className="overflow-auto"><table className="tbl text-sm"><thead><tr><th className="pl-2">Mã</th><th>Tài sản</th><th>Loại</th><th className="text-right">Nguyên giá</th><th className="text-right">KH/tháng</th><th className="text-right">Lũy kế</th><th className="text-right">Còn lại</th><th className="text-right">%</th><th>Bắt đầu</th><th>TT</th></tr></thead><tbody>{A.map((a) => <tr key={String(a.id)}><td className="pl-2 font-mono text-xs">{String(a.id)}</td><td className="font-semibold">{String(a.name)}</td><td className="text-xs">{String(a.kind)}</td><td className="text-right">{fmt.vnd(a.cost)}</td><td className="text-right">{fmt.vnd((Number(a.cost) - Number(a.salvage ?? 0)) / Number(a.life_months))}</td><td className="text-right">{fmt.vnd(a.accumulated)}</td><td className="text-right font-bold">{fmt.vnd(a.remaining)}</td><td className="text-right">{String(a.pct_dep ?? 0)}%</td><td className="text-xs">{fmt.d(a.start_date)}</td><td><span className={a.status === "DANG_DUNG" ? "b-grn" : "b-gray"}>{String(a.status)}</span></td></tr>)}</tbody></table></div></div>);
}
