"use client";
import { useState } from "react";
import { useData, fmt } from "@/lib/client";
type R = Record<string, unknown>;
/** PHẢ HỆ nhiều đời: tổ tiên (mẹ/cha–tinh) 4 đời · hậu duệ · kiểm cận huyết trước khi phối */
export function PedigreePanel({ animalId }: { animalId: string }) {
  const anc = useData("pedigree", { animal: animalId }); const des = useData("descendants", { animal: animalId }); const [mate, setMate] = useState(""); const [risk, setRisk] = useState<R | null>(null);
  const A = anc.rows ?? []; const D = des.rows ?? [];
  return (<div className="card"><div className="flex items-center gap-2 flex-wrap"><b>🧬 Phả hệ — {animalId}</b><span className="text-xs text-muted">tổ tiên {A.length} · hậu duệ {D.length}</span><span className="ml-auto flex items-center gap-1 text-sm"><input className="input !w-40 !py-1 !text-xs" placeholder="mã con định phối" aria-label="mã con định phối" value={mate} onChange={(e) => setMate(e.target.value)} /><button className="btn-secondary !py-1 !px-2 !text-xs" onClick={async () => { const j = await fetch(`/api/data/inbreeding?animal=${animalId}&mate=${encodeURIComponent(mate)}`).then((r) => r.json()); setRisk(j.rows?.[0]?.risk ?? null); }}>Kiểm cận huyết</button></span></div>
    {risk && <div className={`text-sm mt-1 rounded-lg p-2 ${(risk.is_parent || ((risk.shared_ancestors as string[]) ?? []).length) ? "bg-danger-soft-tok text-danger-tok" : "bg-brand-soft text-brand"}`}>{risk.is_parent ? "⛔ Là cha/mẹ–con — KHÔNG phối." : ((risk.shared_ancestors as string[]) ?? []).length ? `⚠ Có tổ tiên chung 3 đời: ${(risk.shared_ancestors as string[]).join(", ")} — cân nhắc đổi tinh.` : "✓ Không thấy tổ tiên chung trong 3 đời."}</div>}
    <div className="grid md:grid-cols-2 gap-3 mt-2 text-sm"><div><b>Tổ tiên</b>{[1, 2, 3, 4].map((g) => { const rows = A.filter((r) => Number(r.generation) === g); return rows.length ? <div key={g} className="mt-1"><div className="text-xs text-muted">Đời {g}</div><div className="flex flex-wrap gap-1">{rows.map((r, i) => <a key={i} href={`/dan/${r.ancestor_id}`} className={`rounded-lg border px-2 py-1 text-xs ${r.side === "DAM" ? "bg-pink-50 border-pink-300" : "bg-sky-50 border-sky-300"}`}>{r.side === "DAM" ? "♀" : "♂"} {String(r.ancestor_id)} <span className="text-muted">{String(r.breed ?? "")} {r.birth_date ? fmt.d(r.birth_date) : ""}</span></a>)}</div></div> : null; })}{!A.length && <div className="text-muted text-xs">Chưa có mẹ/cha (dam_id/sire_id). Cha từ mã tinh (sire_code) tự gán khi ghi PHOI có semen_lot rồi ĐẺ.</div>}</div>
      <div><b>Hậu duệ</b><div className="flex flex-wrap gap-1 mt-1">{D.map((r, i) => <a key={i} href={`/dan/${r.descendant_id}`} className="rounded-lg border px-2 py-1 text-xs bg-white">đời {String(r.generation)} · {String(r.descendant_id)} {r.sex === "F" ? "♀" : "♂"} <span className="text-muted">{r.birth_date ? fmt.d(r.birth_date) : ""} · {String(r.status)}</span></a>)}{!D.length && <span className="text-muted text-xs">chưa có</span>}</div></div></div>
  </div>);
}
/** DỊCH TỄ theo VÙNG (gộp trại cùng vùng): bệnh/chết 7 ngày vs nền 8 tuần */
export function EpiPanel() {
  const sum = useData("epi_region_sum"); const det = useData("epi_region");
  const lv = (l: string) => (l === "DO" ? "b-red" : l === "CAM" || l === "VANG" ? "b-yel" : "b-grn");
  return (<div className="card p-0 overflow-auto"><div className="px-3 py-2 bg-surface-2 rounded-t-xl font-bold">🦠 Dịch tễ theo vùng — bệnh/chết 7 ngày so với nền 8 tuần (gộp mọi trại cùng vùng); ĐỎ = chết ≥3 & gấp đôi nền → cách ly, báo thú y vùng</div>
    <table className="tbl text-sm"><thead><tr><th className="pl-3">Vùng</th><th className="text-right">Trại</th><th className="text-right">Đầu con</th><th className="text-right">Bệnh 7 ngày</th><th className="text-right">Nền/tuần</th><th className="text-right">Chết 7 ngày</th><th className="text-right">Nền/tuần</th><th>Mức</th></tr></thead><tbody>{(sum.rows ?? []).map((r) => <tr key={String(r.region_id)}><td className="pl-3 font-semibold">{String(r.region_id)}</td><td className="text-right">{String(r.farms)}</td><td className="text-right">{String(r.head)}</td><td className="text-right font-bold">{String(r.sick_7d)}</td><td className="text-right">{String(r.sick_base_wk)}</td><td className="text-right font-bold">{String(r.dead_7d)}</td><td className="text-right">{String(r.dead_base_wk)}</td><td><span className={lv(String(r.level))}>{String(r.level)}</span></td></tr>)}</tbody></table>
    <table className="tbl text-xs"><thead><tr><th className="pl-3">Trại</th><th className="text-right">Bệnh 7d</th><th className="text-right">Chết 7d</th><th className="text-right">Đầu con</th></tr></thead><tbody>{(det.rows ?? []).map((r) => <tr key={String(r.farm_id)}><td className="pl-3">{String(r.farm_id)} <span className="text-muted">{String(r.region_id)}</span></td><td className="text-right">{String(r.sick_7d)}</td><td className="text-right">{String(r.dead_7d)}</td><td className="text-right">{String(r.head)}</td></tr>)}</tbody></table></div>);
}
