"use client";
import { useData, act, fmt } from "@/lib/client";
import { toast } from "@/components/ui/Toast";
import { useConfirm } from "@/components/ui/ConfirmDialog";
import type { Sess } from "@/components/Shell";
type R = Record<string, unknown>;
/** HỘP PHÊ DUYỆT: mọi thứ đang chờ tôi duyệt (đề nghị chi 2 chữ ký, điều chỉnh kho, checklist, PO, đơn giảm giá, nghỉ phép, NC) — bấm 1 nút; không ai duyệt việc của mình (DB chặn) */
export default function PheDuyet({ sess }: { sess: Sess }) {
  const exp = useData("expenses_pending"); const adj = useData("adjustments_pending"); const chk = useData("checklists_pending"); const po = useData("po_pending"); const leave = useData("leave_pending"); const nc = useData("nc_open"); const rets = useData("returns_pending");
  const role = sess.role; const canMoney = ["director", "owner", "accountant"].includes(role); const canOps = ["tech_head", "director", "owner"].includes(role);
  const reload = () => { exp.reload(); adj.reload(); chk.reload(); po.reload(); leave.reload(); nc.reload(); rets.reload(); };
  const total = (exp.rows?.length ?? 0) + (adj.rows?.length ?? 0) + (chk.rows?.length ?? 0) + (po.rows?.length ?? 0) + (leave.rows?.length ?? 0) + (rets.rows?.length ?? 0);
  const { confirm, confirmElement } = useConfirm();
  return (<div className="space-y-3">{confirmElement}
    <div className="grid grid-cols-2 sm:grid-cols-6 gap-2">{[["Tổng chờ", total], ["Đề nghị chi", exp.rows?.length], ["Điều chỉnh kho", adj.rows?.length], ["Checklist", chk.rows?.length], ["PO", po.rows?.length], ["Nghỉ phép", leave.rows?.length]].map(([l, v]) => <div key={String(l)} className="kpi !p-2"><div className="l">{String(l)}</div><div className="text-2xl font-black">{String(v ?? 0)}</div></div>)}</div>
    {canMoney && <Sec title="Đề nghị chi (>20tr cần 2 chữ ký · >50tr báo chủ)" rows={exp.rows ?? []} cols={[["ts", "Lúc"], ["requested_by", "Người đề nghị"], ["amount", "Số tiền"], ["cost_center", "CC"], ["purpose", "Mục đích"], ["status", "TT"]]} actions={(r) => <><button className="btn-primary !py-1 !px-2 !text-xs mr-1" onClick={async () => { const j = await act("approve_expense", { id: r.id, approve: true }); if (j.error) toast.err(j.error); reload(); }}>Duyệt</button><button className="btn-secondary !py-1 !px-2 !text-xs" onClick={async () => { await act("approve_expense", { id: r.id, approve: false }); reload(); }}>Từ chối</button></>} />}
    {canOps && <Sec title="Điều chỉnh kho / kiểm kê" rows={adj.rows ?? []} cols={[["ts", "Lúc"], ["created_by", "Người tạo"], ["sku", "Hàng"], ["delta", "±"], ["reason", "Lý do"]]} actions={(r) => <><button className="btn-primary !py-1 !px-2 !text-xs mr-1" onClick={async () => { const j = await act("approve_adjustment", { id: r.id, approve: true }); if (j.error) toast.err(j.error); reload(); }}>Duyệt</button><button className="btn-secondary !py-1 !px-2 !text-xs" onClick={async () => { await act("approve_adjustment", { id: r.id, approve: false }); reload(); }}>Từ chối</button></>} />}
    {(canOps || role === "team_lead") && <Sec title="Checklist chờ duyệt" rows={chk.rows ?? []} cols={[["ts", "Lúc"], ["created_by", "Người ghi"], ["sop_code", "SOP"], ["shift", "Ca"], ["all_green", "Xanh hết"]]} actions={(r) => <button className="btn-primary !py-1 !px-2 !text-xs" onClick={async () => { const j = await act("approve_checklist", { id: r.id }); if (j.error) toast.err(j.error); reload(); }}>Duyệt</button>} />}
    {canMoney && <Sec title="Đơn mua (PO) chờ duyệt" rows={po.rows ?? []} cols={[["ts", "Lúc"], ["created_by", "Người tạo"], ["supplier_id", "NCC"], ["total", "Tổng"], ["po_status", "TT"]]} actions={(r) => <><button className="btn-primary !py-1 !px-2 !text-xs mr-1" onClick={async () => { const j = await act("po_status", { id: r.id, status: "DUYET" }); if (j.error) toast.err(j.error); reload(); }}>Duyệt</button><button className="btn-secondary !py-1 !px-2 !text-xs" onClick={async () => { await act("po_status", { id: r.id, status: "HUY" }); reload(); }}>Hủy</button></>} />}
    {(canOps || canMoney || role === "team_lead") && <Sec title="Nghỉ phép chờ duyệt" rows={leave.rows ?? []} cols={[["created_at", "Lúc"], ["staff_id", "Nhân sự"], ["kind", "Loại"], ["from_date", "Từ"], ["to_date", "Đến"], ["days", "Ngày"], ["reason", "Lý do"], ["delegate_id", "Người thay"], ["handover_note", "Bàn giao"]]} actions={(r) => <><button className="btn-primary !py-1 !px-2 !text-xs mr-1" onClick={async () => { if (!r.delegate_id && !(await confirm({ title: "Đơn này CHƯA có người thay — duyệt thì việc của người nghỉ không ai nhận. Vẫn duyệt?", danger: true }))) return; await fetch("/api/admin/leave_requests", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ row: { id: r.id, status: "DUYET", approved_by: sess.staffId, approved_at: new Date().toISOString() } }) }); reload(); }}>Duyệt</button><button className="btn-secondary !py-1 !px-2 !text-xs" onClick={async () => { await fetch("/api/admin/leave_requests", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ row: { id: r.id, status: "TU_CHOI", approved_by: sess.staffId, approved_at: new Date().toISOString() } }) }); reload(); }}>Từ chối</button></>} />}
    {canMoney && <Sec title="Trả hàng / credit note chờ duyệt" rows={rets.rows ?? []} cols={[["ts", "Lúc"], ["created_by", "Người tạo"], ["sku", "Hàng"], ["qty", "SL"], ["amount", "Tiền hoàn"], ["reason", "Lý do"], ["disposition", "Xử lý"]]} actions={(r) => <><button className="btn-primary !py-1 !px-2 !text-xs mr-1" onClick={async () => { const j = await act("approve_return", { id: r.id }); if (j.error) toast.err(j.error); reload(); }}>Duyệt</button></>} />}
    <Sec title="Điểm không phù hợp (NC) đang mở — theo dõi khắc phục" rows={nc.rows ?? []} cols={[["checked_at", "Lúc"], ["standard_code", "Chuẩn"], ["nc_severity", "Mức"], ["evidence", "Bằng chứng"], ["due_date", "Hạn"]]} actions={() => <a className="underline text-xs py-1 -my-1" href="/tuan-thu">xử lý</a>} />
  </div>);
}
function Sec({ title, rows, cols, actions }: { title: string; rows: R[]; cols: [string, string][]; actions: (r: R) => React.ReactNode }) {
  return <div className="card p-0 overflow-auto"><div className="px-3 py-2 bg-surface-2 rounded-t-xl font-bold">{title} ({rows.length})</div>{rows.length ? <table className="tbl text-sm"><thead><tr>{cols.map(([k, l]) => <th key={k} className="pl-2">{l}</th>)}<th></th></tr></thead><tbody>{rows.map((r, i) => <tr key={String(r.id ?? i)}>{cols.map(([k]) => <td key={k} className="pl-2">{/ts|_at|date/.test(k) && r[k] ? (String(r[k]).length > 10 ? fmt.dt(r[k]) : fmt.d(r[k])) : k === "amount" || k === "total" ? fmt.vnd(r[k]) : typeof r[k] === "boolean" ? (r[k] ? "✓" : "✗") : String(r[k] ?? "")}</td>)}<td className="whitespace-nowrap">{actions(r)}</td></tr>)}</tbody></table> : <div className="p-3 text-muted text-sm">Không có.</div>}</div>;
}
