"use client";
import { useEffect, useState } from "react";
import { useData, act, fmt } from "@/lib/client";
import type { Sess } from "@/components/Shell";
type R = Record<string, unknown>;
const ROLES = ["worker", "team_lead", "tech_head", "director", "accountant", "it_engineer", "auditor", "owner"];
const OBJ = [["VAT_NUOI", "Vật nuôi"], ["CAY_TRONG", "Cây trồng"], ["SAN_XUAT", "Sản xuất/chế biến"], ["VAT_TU_KHO", "Vật tư/kho"], ["KHACH_HANG", "Khách hàng/bán/DL/XNK"], ["CON_NGUOI", "Con người"], ["TAI_CHINH", "Tài chính"], ["THIET_BI_DU_LIEU", "Thiết bị/dữ liệu"], ["CHAT_LUONG", "Chất lượng"], ["TRI_THUC", "R&D"], ["TRAI", "Trại/nhân rộng"], ["QUAN_TRI", "Quản trị"]];
const FORMS = ["", "animal_events", "feed_logs", "crop_logs", "crop_inputs", "harvests", "batch_logs", "inventory_moves", "weigh_tickets", "gate_logs", "sales", "checklist_runs", "incidents", "stocktakes", "calibrations", "pos_receipts", "hosp_folio"];

/** THIẾT KẾ QUY TRÌNH: khai báo quy trình → thêm/xóa/sắp bước → mỗi bước: phòng ban · vai · công cụ · vật tư · đầu vào · đầu ra · biểu mẫu · SLA → XUẤT BẢN (thông báo phòng ban/nhân sự) → CHẠY (sinh việc theo bước) */
export default function ProcessDesigner({ sess, initialCode, tab: initialTab }: { sess: Sess; initialCode?: string; tab?: string }) {
  const procs = useData("processes"); const steps = useData("process_steps"); const depts = useData("departments"); const devices = useData("devices"); const products = useData("products"); const runs = useData("process_runs"); const runSteps = useData("process_run_steps"); const topics = useData("event_topics");
  const [code, setCode] = useState<string | null>(initialCode ?? null); const [meta, setMeta] = useState<R>({}); const [newP, setNewP] = useState(false); const [editStep, setEditStep] = useState<R | null>(null); const [msg, setMsg] = useState(""); const [tab, setTab] = useState<"tk" | "chay">(initialTab === "chay" ? "chay" : "tk"); const [runTitle, setRunTitle] = useState("");
  const canW = ["owner", "director", "it_engineer", "tech_head"].includes(sess.role);
  const P = procs.rows ?? []; const p = P.find((x) => x.code === code); const S = (steps.rows ?? []).filter((s) => s.process_code === code).sort((a, b) => Number(a.step_no) - Number(b.step_no));
  useEffect(() => { if (p) setMeta({ ...p }); }, [p]);
  const reload = () => { procs.reload(); steps.reload(); runs.reload(); runSteps.reload(); };
  const saveMeta = async () => { const j = await act("save_process", { ...meta, code: meta.code ?? code, scope: meta.farm_id ? "FARM" : "GLOBAL" }); if (j.ok) { setMsg("Đã lưu quy trình"); setCode(String(j.code)); setNewP(false); reload(); } else setMsg(String(j.error)); };
  const saveStep = async () => { if (!editStep || !code) return; const j = await act("save_step", { code, step: editStep }); if (j.ok) { setMsg(`Đã lưu bước ${j.step_no}`); setEditStep(null); steps.reload(); } else setMsg(String(j.error)); };
  const mat = (editStep?.materials as R[] | undefined) ?? [];
  const runsActive = (runs.rows ?? []).filter((r) => r.status === "DANG_CHAY");
  return (
    <div className="space-y-3">
      <div className="flex gap-2 items-center flex-wrap"><button className={`px-3 py-1.5 rounded-xl font-semibold ${tab === "tk" ? "bg-green-700 text-white" : "bg-white border"}`} onClick={() => setTab("tk")}>🛠 Thiết kế quy trình</button><button className={`px-3 py-1.5 rounded-xl font-semibold ${tab === "chay" ? "bg-green-700 text-white" : "bg-white border"}`} onClick={() => setTab("chay")}>▶ Đang chạy ({runsActive.length})</button>{msg && <span className="text-sm text-green-800 ml-2">{msg}</span>}</div>
      {tab === "tk" && <div className="grid md:grid-cols-3 gap-3">
        <div className="card p-0 overflow-auto max-h-[80vh]"><div className="px-3 py-2 bg-stone-100 rounded-t-2xl flex items-center"><b>Quy trình ({P.length})</b>{canW && <button className="ml-auto btn-secondary !py-1 !px-2 !text-xs" onClick={() => { setNewP(true); setCode(null); setMeta({ code: "P-", kind: "CORE", dept_code: depts.rows?.[0]?.code, name: "" }); }}>＋ Mới</button>}</div>
          {(depts.rows ?? []).map((d) => { const list = P.filter((q) => q.dept_code === d.code); return list.length ? <div key={String(d.code)}><div className="px-3 py-1 text-xs font-bold text-stone-500 bg-stone-50">{String(d.short ?? d.name)}</div>{list.map((q) => <button key={String(q.code)} className={`block w-full text-left px-3 py-1.5 text-sm border-b hover:bg-green-50 ${code === q.code ? "bg-green-100" : ""}`} onClick={() => { setCode(String(q.code)); setNewP(false); setEditStep(null); }}><span className="font-mono text-xs">{String(q.code)}</span> {String(q.name)} <span className="text-xs text-stone-500">· {String(q.steps_n)} bước</span> {q.status === "NHAP" ? <span className="b-yel">nháp</span> : q.status === "NGUNG" ? <span className="b-gray">ngưng</span> : null}</button>)}</div> : null; })}</div>
        <div className="md:col-span-2 space-y-3">
          {(p || newP) && <div className="card"><div className="flex items-center gap-2 flex-wrap"><b className="text-lg">{newP ? "Khai báo quy trình mới" : String(p?.name)}</b>{p && <span className={p.status === "BAN_HANH" ? "b-grn" : "b-yel"}>{String(p.status)} v{String(p.version)}</span>}{p && p.status === "BAN_HANH" && canW && <button className="btn-primary !py-1 !px-3 !text-sm ml-auto" onClick={async () => { const t = prompt("Tiêu đề lần chạy (vd: Ô R3 vụ 2 / Đơn KH-012)", runTitle) ?? ""; if (t === null) return; const j = await act("start_run", { code, title: t }); if (j.ok) { setMsg("Đã khởi chạy — việc bước 1 đã tạo & thông báo"); setRunTitle(t); setTab("chay"); reload(); } else setMsg(String(j.error)); }}>▶ Chạy quy trình</button>}</div>
            <div className="grid sm:grid-cols-2 lg:grid-cols-4 gap-2 mt-2 text-sm">
              <label>Mã<input className="input" value={String(meta.code ?? "")} disabled={!newP} onChange={(e) => setMeta({ ...meta, code: e.target.value.toUpperCase() })} placeholder="P-XX-NN" /></label>
              <label className="lg:col-span-2">Tên quy trình<input className="input" value={String(meta.name ?? "")} disabled={!canW} onChange={(e) => setMeta({ ...meta, name: e.target.value })} /></label>
              <label>Phòng chủ trì<select className="input" value={String(meta.dept_code ?? "")} disabled={!canW} onChange={(e) => setMeta({ ...meta, dept_code: e.target.value })}>{(depts.rows ?? []).map((d) => <option key={String(d.code)} value={String(d.code)}>{String(d.short ?? d.name)}</option>)}</select></label>
              <label>Đối tượng<select className="input" value={String(meta.object_type ?? "")} disabled={!canW} onChange={(e) => setMeta({ ...meta, object_type: e.target.value })}><option value="">—</option>{OBJ.map(([k, l]) => <option key={k} value={k}>{l}</option>)}</select></label>
              <label>Loại<select className="input" value={String(meta.kind ?? "CORE")} disabled={!canW} onChange={(e) => setMeta({ ...meta, kind: e.target.value })}><option value="CORE">Lõi</option><option value="SUPPORT">Hỗ trợ</option><option value="MANAGEMENT">Quản lý</option></select></label>
              <label>Kích hoạt khi<input className="input" value={String(meta.trigger_text ?? "")} disabled={!canW} onChange={(e) => setMeta({ ...meta, trigger_text: e.target.value })} placeholder="vd: có lô nhập / lịch tuần" /></label>
              <label>Tự chạy theo sự kiện<select className="input" value={String((meta.auto_start as R | undefined)?.topic ?? "")} disabled={!canW} onChange={(e) => setMeta({ ...meta, auto_start: e.target.value ? { topic: e.target.value } : {} })}><option value="">— không —</option>{(topics.rows ?? []).map((t) => <option key={String(t.topic)} value={String(t.topic)}>{String(t.topic)}</option>)}</select></label>
              <label>SLA<input className="input" value={String(meta.sla ?? "")} disabled={!canW} onChange={(e) => setMeta({ ...meta, sla: e.target.value })} /></label>
              <label>Chủ trì (vai)<select className="input" value={String(meta.owner_role ?? "")} disabled={!canW} onChange={(e) => setMeta({ ...meta, owner_role: e.target.value })}><option value="">—</option>{ROLES.map((r) => <option key={r}>{r}</option>)}</select></label>
              <label>KPI<input className="input" value={String(meta.kpi ?? "")} disabled={!canW} onChange={(e) => setMeta({ ...meta, kpi: e.target.value })} /></label>
              <label>Màn hình<input className="input" value={String(meta.ui_path ?? "")} disabled={!canW} onChange={(e) => setMeta({ ...meta, ui_path: e.target.value })} placeholder="/canh-tac" /></label>
              <label className="lg:col-span-4">Mô tả / mục đích<textarea className="input" rows={2} value={String(meta.description ?? "")} disabled={!canW} onChange={(e) => setMeta({ ...meta, description: e.target.value })} /></label>
            </div>
            {canW && <div className="flex gap-2 mt-2 flex-wrap"><button className="btn-secondary !py-2" onClick={saveMeta}>Lưu thông tin</button>{p && (p.status !== "BAN_HANH" ? <button className="btn-primary !py-2" onClick={async () => { if (!S.length) return setMsg("Cần ít nhất 1 bước"); const j = await act("publish_process", { code }); setMsg(j.ok ? "ĐÃ XUẤT BẢN — mọi phòng ban/nhân sự trong các bước đã được thông báo và đưa vào quy trình" : String(j.error)); reload(); }}>📣 Xuất bản & thông báo</button> : <><button className="btn-secondary !py-2" onClick={async () => { const j = await act("publish_process", { code }); setMsg(j.ok ? "Đã phát hành phiên bản mới & thông báo lại" : String(j.error)); reload(); }}>🔁 Phát hành lại (v+1)</button><button className="btn-secondary !py-2" onClick={async () => { await act("unpublish_process", { code, status: "NGUNG" }); reload(); }}>Ngưng</button></>)}</div>}
          </div>}
          {p && <div className="card p-0 overflow-auto"><div className="px-3 py-2 bg-stone-100 rounded-t-2xl flex items-center"><b>Các bước ({S.length}) — mỗi bước: bộ phận · người · công cụ · vật tư · đầu vào → đầu ra</b>{canW && <button className="ml-auto btn-secondary !py-1 !px-2 !text-xs" onClick={() => setEditStep({ step_no: S.length + 1, name: "", dept_code: p.dept_code, actor_role: "worker", required: true, tools: [], materials: [], sla_hours: 24 })}>＋ Thêm bước</button>}</div>
            <table className="tbl text-sm"><thead><tr><th className="pl-3">#</th><th>Bước</th><th>Bộ phận / vai</th><th>Công cụ</th><th>Vật tư</th><th>Đầu vào → Đầu ra</th><th>Biểu mẫu / SLA</th><th></th></tr></thead><tbody>
              {S.map((s, i) => <tr key={String(s.id)}><td className="pl-3 font-black">{String(s.step_no)}{s.parallel_group ? <span className="text-xs text-stone-500">∥{String(s.parallel_group)}</span> : ""}</td><td><b>{String(s.name)}</b><div className="text-xs text-stone-600">{String(s.action ?? "")}</div></td><td className="text-xs"><b>{String(s.dept_code ?? "")}</b><br />{String(s.actor_role ?? "")}</td><td className="text-xs">{((s.tools as string[]) ?? []).join(", ")}</td><td className="text-xs">{((s.materials as R[]) ?? []).map((m) => `${m.sku ?? m.name} ${m.qty ?? ""}${m.unit ?? ""}`).join(", ")}</td><td className="text-xs">{String(s.inputs ?? "")} <b>→</b> {String(s.outputs ?? s.output ?? "")}</td><td className="text-xs font-mono">{String(s.form_table ?? "")}<br />{s.sla_hours ? `${s.sla_hours}h` : ""}</td><td className="text-xs whitespace-nowrap">{canW && <><button className="underline mr-1" onClick={() => setEditStep({ ...s })}>sửa</button>{i > 0 && <button className="mr-1" onClick={async () => { await act("move_step", { code, step_no: s.step_no, dir: -1 }); steps.reload(); }}>↑</button>}{i < S.length - 1 && <button className="mr-1" onClick={async () => { await act("move_step", { code, step_no: s.step_no, dir: 1 }); steps.reload(); }}>↓</button>}<button className="underline text-red-700" onClick={async () => { if (confirm(`Xóa bước ${s.step_no}: ${s.name}?`)) { await act("delete_step", { code, step_no: s.step_no }); steps.reload(); } }}>xóa</button></>}</td></tr>)}
            </tbody></table>{!S.length && <div className="p-3 text-stone-500 text-sm">Chưa có bước — bấm ＋ Thêm bước.</div>}</div>}
          {editStep && <div className="card border-2 border-green-600"><b>Bước {String(editStep.step_no)}</b>
            <div className="grid sm:grid-cols-2 lg:grid-cols-3 gap-2 mt-2 text-sm">
              <label className="lg:col-span-2">Tên bước<input className="input" value={String(editStep.name ?? "")} onChange={(e) => setEditStep({ ...editStep, name: e.target.value })} /></label>
              <label>Thứ tự<input className="input" type="number" value={String(editStep.step_no ?? "")} onChange={(e) => setEditStep({ ...editStep, step_no: Number(e.target.value) })} /></label>
              <label>Bộ phận thực hiện<select className="input" value={String(editStep.dept_code ?? "")} onChange={(e) => setEditStep({ ...editStep, dept_code: e.target.value })}>{(depts.rows ?? []).map((d) => <option key={String(d.code)} value={String(d.code)}>{String(d.short ?? d.name)}</option>)}</select></label>
              <label>Vai thực hiện (nhận việc)<select className="input" value={String(editStep.actor_role ?? "")} onChange={(e) => setEditStep({ ...editStep, actor_role: e.target.value })}>{ROLES.map((r) => <option key={r}>{r}</option>)}</select></label>
              <label>SLA (giờ) · thời lượng (phút)<div className="flex gap-1"><input className="input" type="number" value={String(editStep.sla_hours ?? "")} onChange={(e) => setEditStep({ ...editStep, sla_hours: Number(e.target.value) })} /><input className="input" type="number" value={String(editStep.duration_min ?? "")} onChange={(e) => setEditStep({ ...editStep, duration_min: Number(e.target.value) })} /></div></label>
              <label className="lg:col-span-3">Làm gì (mô tả thao tác)<input className="input" value={String(editStep.action ?? "")} onChange={(e) => setEditStep({ ...editStep, action: e.target.value })} /></label>
              <label>Công cụ / thiết bị (chọn hoặc gõ, cách nhau dấu phẩy)<input className="input" list="devlist" value={Array.isArray(editStep.tools) ? (editStep.tools as string[]).join(", ") : String(editStep.tools ?? "")} onChange={(e) => setEditStep({ ...editStep, tools: e.target.value })} /><datalist id="devlist">{(devices.rows ?? []).map((d) => <option key={String(d.id)} value={String(d.name)} />)}</datalist></label>
              <label>Đầu vào (cần gì trước khi làm)<input className="input" value={String(editStep.inputs ?? "")} onChange={(e) => setEditStep({ ...editStep, inputs: e.target.value })} /></label>
              <label>Đầu ra (tạo ra gì)<input className="input" value={String(editStep.outputs ?? "")} onChange={(e) => setEditStep({ ...editStep, outputs: e.target.value })} /></label>
              <label>Biểu mẫu/bảng phải ghi để xong bước<select className="input" value={String(editStep.form_table ?? "")} onChange={(e) => setEditStep({ ...editStep, form_table: e.target.value })}>{FORMS.map((f) => <option key={f} value={f}>{f || "— không —"}</option>)}</select></label>
              <label>Ở đâu trong hệ thống<input className="input" value={String(editStep.system_where ?? "")} onChange={(e) => setEditStep({ ...editStep, system_where: e.target.value })} placeholder="/ca A6 · /kho" /></label>
              <label>Kiểm soát / điều kiện qua bước<input className="input" value={String(editStep.control ?? "")} onChange={(e) => setEditStep({ ...editStep, control: e.target.value })} /></label>
              <label>Nhóm song song (cùng số = làm đồng thời)<input className="input" type="number" value={String(editStep.parallel_group ?? "")} onChange={(e) => setEditStep({ ...editStep, parallel_group: e.target.value ? Number(e.target.value) : null })} /></label>
              <label className="flex items-center gap-2 mt-5"><input type="checkbox" checked={editStep.required !== false} onChange={(e) => setEditStep({ ...editStep, required: e.target.checked })} /> Bắt buộc</label>
              <div className="lg:col-span-3"><b>Vật tư / tư liệu sản xuất</b> <button className="underline text-xs ml-2" onClick={() => setEditStep({ ...editStep, materials: [...mat, { sku: "", qty: 0, unit: "" }] })}>+ thêm dòng</button>
                {mat.map((m, i) => <div key={i} className="flex gap-1 mt-1"><select className="input !w-72 !py-1" value={String(m.sku ?? "")} onChange={(e) => setEditStep({ ...editStep, materials: mat.map((x, j) => j === i ? { ...x, sku: e.target.value } : x) })}><option value="">— SKU —</option>{(products.rows ?? []).map((pr) => <option key={String(pr.sku)} value={String(pr.sku)}>{String(pr.name)} ({String(pr.sku)})</option>)}</select><input className="input !w-28 !py-1" type="number" placeholder="SL" value={String(m.qty ?? "")} onChange={(e) => setEditStep({ ...editStep, materials: mat.map((x, j) => j === i ? { ...x, qty: Number(e.target.value) } : x) })} /><input className="input !w-28 !py-1" placeholder="đv (kg/ha…)" value={String(m.unit ?? "")} onChange={(e) => setEditStep({ ...editStep, materials: mat.map((x, j) => j === i ? { ...x, unit: e.target.value } : x) })} /><button className="text-red-700" onClick={() => setEditStep({ ...editStep, materials: mat.filter((_, j) => j !== i) })}>✕</button></div>)}</div>
            </div>
            <div className="flex gap-2 mt-2"><button className="btn-primary !py-2" onClick={saveStep}>Lưu bước</button><button className="btn-secondary !py-2" onClick={() => setEditStep(null)}>Hủy</button></div></div>}
          {!p && !newP && <div className="card text-stone-500">Chọn quy trình bên trái, hoặc ＋ Mới để khai báo. Xuất bản xong → mọi phòng ban/nhân sự trong các bước nhận thông báo; bấm ▶ Chạy để hệ thống sinh việc theo từng bước (người làm nhận việc trong Ca của tôi, xong bước → bước kế tự kích hoạt).</div>}
        </div>
      </div>}
      {tab === "chay" && <div className="space-y-3">
        {!runsActive.length && <div className="card text-stone-500">Chưa có quy trình đang chạy. Vào Thiết kế → chọn quy trình đã xuất bản → ▶ Chạy.</div>}
        {(runs.rows ?? []).map((r) => { const rs = (runSteps.rows ?? []).filter((x) => x.run_id === r.id); return <div key={String(r.id)} className="card"><div className="flex items-center gap-2 flex-wrap"><b>{String(r.process_code)} · {String(r.title)}</b><span className={r.status === "DANG_CHAY" ? "b-yel" : r.status === "XONG" ? "b-grn" : "b-gray"}>{String(r.status)}</span><span className="text-sm text-stone-600">{String(r.steps_done)}/{String(r.steps_total)} bước · bắt đầu {fmt.dt(r.started_at)} bởi {String(r.started_by)}</span>{r.status === "DANG_CHAY" && canW && <button className="ml-auto underline text-sm text-red-700" onClick={async () => { if (confirm("Hủy lần chạy này?")) { await act("cancel_run", { run_id: r.id }); reload(); } }}>hủy</button>}</div>
          {r.status === "DANG_CHAY" && <div className="mt-2 flex flex-wrap gap-1">{rs.map((s) => <div key={String(s.id)} className={`rounded-xl px-2 py-1 text-xs border ${s.status === "XONG" ? "bg-green-100 border-green-400" : s.status === "DANG_LAM" ? "bg-amber-100 border-amber-400 font-bold" : "bg-stone-50"}`}>{String(s.step_no)}. {String(s.name)} <span className="text-stone-500">{String(s.dept_code ?? "")}/{String(s.actor_role ?? "")}</span>{s.status === "DANG_LAM" && <button className="ml-2 underline" onClick={async () => { const note = prompt("Ghi chú/tham chiếu kết quả (tùy chọn)") ?? ""; const j = await act("complete_step", { run_id: r.id, step_no: s.step_no, note }); setMsg(j.ok ? `Bước ${s.step_no} xong → ${j.result}` : String(j.error)); reload(); }}>✓ xong</button>}</div>)}</div>}
          {r.status !== "DANG_CHAY" && <div className="text-xs text-stone-500 mt-1">{String(r.current_names ?? "")}</div>}</div>; })}
      </div>}
    </div>);
}
