"use client";
import { useEffect, useState } from "react";
import { useData, act, fmt } from "@/lib/client";
import type { Sess } from "@/components/Shell";
import { ProcessFlow } from "@/components/ProcessFlow";
import { usePrompt } from "@/components/ui/PromptDialog";
import { useConfirm } from "@/components/ui/ConfirmDialog";
type R = Record<string, unknown>;
const ROLES = ["worker", "team_lead", "tech_head", "director", "accountant", "it_engineer", "auditor", "owner"];
const OBJ = [["VAT_NUOI", "Vật nuôi"], ["CAY_TRONG", "Cây trồng"], ["SAN_XUAT", "Sản xuất/chế biến"], ["VAT_TU_KHO", "Vật tư/kho"], ["KHACH_HANG", "Khách hàng/bán/DL/XNK"], ["CON_NGUOI", "Con người"], ["TAI_CHINH", "Tài chính"], ["THIET_BI_DU_LIEU", "Thiết bị/dữ liệu"], ["CHAT_LUONG", "Chất lượng"], ["TRI_THUC", "R&D"], ["TRAI", "Trại/nhân rộng"], ["QUAN_TRI", "Quản trị"]];
const FORMS = ["", "animal_events", "feed_logs", "crop_logs", "crop_inputs", "harvests", "batch_logs", "inventory_moves", "weigh_tickets", "gate_logs", "sales", "checklist_runs", "incidents", "stocktakes", "calibrations", "pos_receipts", "hosp_folio"];

/** THIẾT KẾ QUY TRÌNH: khai báo quy trình → thêm/xóa/sắp bước → mỗi bước: phòng ban · vai · công cụ · vật tư · đầu vào · đầu ra · biểu mẫu · SLA → XUẤT BẢN (thông báo phòng ban/nhân sự) → CHẠY (sinh việc theo bước) */
export default function ProcessDesigner({ sess, initialCode, tab: initialTab }: { sess: Sess; initialCode?: string; tab?: string }) {
  const procs = useData("processes"); const steps = useData("process_steps"); const depts = useData("departments"); const devices = useData("devices"); const products = useData("products"); const runs = useData("process_runs"); const runSteps = useData("process_run_steps"); const topics = useData("event_topics");
  const [code, setCode] = useState<string | null>(initialCode ?? null); const [meta, setMeta] = useState<R>({}); const [newP, setNewP] = useState(false); const [editStep, setEditStep] = useState<R | null>(null); const [msg, setMsg] = useState(""); const [tab, setTab] = useState<"tk" | "chay">(initialTab === "chay" ? "chay" : "tk"); const [runTitle, setRunTitle] = useState("");
  const { prompt, promptElement } = usePrompt(); const { confirm, confirmElement } = useConfirm();
  const canW = ["owner", "director", "it_engineer", "tech_head"].includes(sess.role);
  const me = useData("me"); const myDept = String(me.rows?.[0]?.dept ?? ""); const limited = ["worker", "team_lead"].includes(sess.role);
  const P = (procs.rows ?? []).filter((x) => !limited || !myDept || ((x.visible_depts as string[]) ?? []).includes(myDept) || x.dept_code === myDept); const p = P.find((x) => x.code === code); const S = (steps.rows ?? []).filter((s) => s.process_code === code).sort((a, b) => Number(a.step_no) - Number(b.step_no));
  useEffect(() => { if (p) setMeta({ ...p }); }, [p]);
  const reload = () => { procs.reload(); steps.reload(); runs.reload(); runSteps.reload(); };
  const saveMeta = async () => { const j = await act("save_process", { ...meta, code: meta.code ?? code, scope: meta.farm_id ? "FARM" : "GLOBAL" }); if (j.ok) { setMsg("Đã lưu quy trình"); setCode(String(j.code)); setNewP(false); reload(); } else setMsg(String(j.error)); };
  const saveStep = async () => { if (!editStep || !code) return; const j = await act("save_step", { code, step: editStep }); if (j.ok) { setMsg(`Đã lưu bước ${j.step_no}`); setEditStep(null); steps.reload(); } else setMsg(String(j.error)); };
  const mat = (editStep?.materials as R[] | undefined) ?? [];
  const runsActive = (runs.rows ?? []).filter((r) => r.status === "DANG_CHAY");
  return (
    <div className="space-y-3">
      {promptElement}{confirmElement}
      <div className="flex gap-2 items-center flex-wrap"><button className={`px-3 py-1.5 rounded-xl font-semibold ${tab === "tk" ? "bg-brand-tok text-white" : "bg-white border"}`} onClick={() => setTab("tk")}>🛠 Thiết kế quy trình</button><button className={`px-3 py-1.5 rounded-xl font-semibold ${tab === "chay" ? "bg-brand-tok text-white" : "bg-white border"}`} onClick={() => setTab("chay")}>▶ Đang chạy ({runsActive.length})</button>{msg && <span className="text-sm text-brand ml-2">{msg}</span>}</div>
      {tab === "tk" && <div className="grid md:grid-cols-3 gap-3">
        <div className="card p-0 overflow-auto max-h-[80vh]"><div className="px-3 py-2 bg-surface-2 rounded-t-2xl flex items-center"><b>Quy trình ({P.length})</b>{canW && <button className="ml-auto btn-secondary !py-1 !px-2 !text-xs" onClick={() => { setNewP(true); setCode(null); setMeta({ code: "P-", kind: "CORE", dept_code: depts.rows?.[0]?.code, name: "" }); }}>＋ Mới</button>}</div>
          {(depts.rows ?? []).map((d) => { const list = P.filter((q) => q.dept_code === d.code); return list.length ? <div key={String(d.code)}><div className="px-3 py-1 text-xs font-bold text-muted bg-surface-2">{String(d.short ?? d.name)}</div>{list.map((q) => <button key={String(q.code)} className={`block w-full text-left px-3 py-1.5 text-sm border-b hover:bg-green-50 ${code === q.code ? "bg-brand-soft" : ""}`} onClick={() => { setCode(String(q.code)); setNewP(false); setEditStep(null); }}><span className="font-mono text-xs">{String(q.code)}</span> {String(q.name)} <span className="text-xs text-muted">· {String(q.steps_n)} bước</span> {q.status === "NHAP" ? <span className="b-yel">nháp</span> : q.status === "NGUNG" ? <span className="b-gray">ngưng</span> : null}</button>)}</div> : null; })}</div>
        <div className="md:col-span-2 space-y-3">
          {(p || newP) && <div className="card"><div className="flex items-center gap-2 flex-wrap"><b className="text-lg">{newP ? "Khai báo quy trình mới" : String(p?.name)}</b>{p && <span className={p.status === "BAN_HANH" ? "b-grn" : "b-yel"}>{String(p.status)} v{String(p.version)}</span>}{p && p.status === "BAN_HANH" && canW && <button className="btn-primary !py-1 !px-3 !text-sm ml-auto" onClick={async () => { const t = await prompt({ title: "Chạy quy trình", label: "Tiêu đề lần chạy (vd: Ô R3 vụ 2 / Đơn KH-012)", type: "text", defaultValue: runTitle, required: false }); if (t == null) return; const j = await act("start_run", { code, title: t }); if (j.ok) { setMsg("Đã khởi chạy — việc bước 1 đã tạo & thông báo"); setRunTitle(t); setTab("chay"); reload(); } else setMsg(String(j.error)); }}>▶ Chạy quy trình</button>}</div>
            <div className="grid sm:grid-cols-2 lg:grid-cols-4 gap-2 mt-2 text-sm">
              <label>Mã<input className="input" value={String(meta.code ?? "")} disabled={!newP} onChange={(e) => setMeta({ ...meta, code: e.target.value.toUpperCase() })} placeholder="P-XX-NN" /></label>
              <label className="lg:col-span-2">Tên quy trình<input className="input" value={String(meta.name ?? "")} disabled={!canW} onChange={(e) => setMeta({ ...meta, name: e.target.value })} /></label>
              <label>Phòng chủ trì<select className="input" value={String(meta.dept_code ?? "")} disabled={!canW} onChange={(e) => setMeta({ ...meta, dept_code: e.target.value })}>{(depts.rows ?? []).map((d) => <option key={String(d.code)} value={String(d.code)}>{String(d.short ?? d.name)}</option>)}</select></label>
              <label>Đối tượng<select className="input" value={String(meta.object_type ?? "")} disabled={!canW} onChange={(e) => setMeta({ ...meta, object_type: e.target.value })}><option value="">—</option>{OBJ.map(([k, l]) => <option key={k} value={k}>{l}</option>)}</select></label>
              <label>Loại<select className="input" value={String(meta.kind ?? "CORE")} disabled={!canW} onChange={(e) => setMeta({ ...meta, kind: e.target.value })}><option value="CORE">Lõi</option><option value="SUPPORT">Hỗ trợ</option><option value="MANAGEMENT">Quản lý</option></select></label>
              <label>Kích hoạt khi<input className="input" value={String(meta.trigger_text ?? "")} disabled={!canW} onChange={(e) => setMeta({ ...meta, trigger_text: e.target.value })} placeholder="vd: có lô nhập / lịch tuần" /></label>
              <label>Tự chạy theo sự kiện<select className="input" value={String((meta.auto_start as R | undefined)?.topic ?? "")} disabled={!canW} onChange={(e) => setMeta({ ...meta, auto_start: e.target.value ? { topic: e.target.value } : {} })}><option value="">— không —</option>{(topics.rows ?? []).map((t) => <option key={String(t.topic)} value={String(t.topic)}>{String(t.topic)}</option>)}</select></label>
              <label>SLA<input className="input" value={String(meta.sla ?? "")} disabled={!canW} onChange={(e) => setMeta({ ...meta, sla: e.target.value })} /></label>
              <label>Chủ trì (vai)<select className="input" value={String(meta.owner_role ?? "")} disabled={!canW} onChange={(e) => setMeta({ ...meta, owner_role: e.target.value })}><option value="">—</option>{ROLES.map((r) => <option key={r}>{r}</option>)}</select></label>
              <label>KPI<input className="input" value={String(meta.kpi ?? "")} disabled={!canW} onChange={(e) => setMeta({ ...meta, kpi: e.target.value })} /></label>
              <label>Màn hình<input className="input" value={String(meta.ui_path ?? "")} disabled={!canW} onChange={(e) => setMeta({ ...meta, ui_path: e.target.value })} placeholder="/canh-tac" /></label>
              <label className="lg:col-span-4">Mô tả / mục đích<textarea className="input" rows={2} value={String(meta.description ?? "")} disabled={!canW} onChange={(e) => setMeta({ ...meta, description: e.target.value })} /></label>
            </div>
            <div className="grid lg:grid-cols-2 gap-3 mt-3 text-sm">
              <div className="rounded-xl bg-warning-soft-tok border border-amber-200 p-2"><div className="flex items-center"><b>ĐẦU VÀO — nhận từ bộ phận nào</b>{canW && <button className="ml-auto underline text-xs" onClick={() => setMeta({ ...meta, inputs: [...((meta.inputs as R[]) ?? []), { from: "", what: "", via: "" }] })}>+ thêm</button>}</div>
                {(((meta.inputs as R[]) ?? [])).map((i, k) => <div key={k} className="flex gap-1 mt-1"><select className="input !w-32 !py-1 !text-xs" value={String(i.from ?? "")} onChange={(e) => setMeta({ ...meta, inputs: ((meta.inputs as R[]) ?? []).map((x, j) => j === k ? { ...x, from: e.target.value } : x) })}><option value="">bộ phận</option><option value="*">* mọi</option>{(depts.rows ?? []).map((d) => <option key={String(d.code)} value={String(d.code)}>{String(d.short ?? d.code)}</option>)}</select><input className="input !py-1 !text-xs" placeholder="nhận gì" aria-label="nhận gì" value={String(i.what ?? "")} onChange={(e) => setMeta({ ...meta, inputs: ((meta.inputs as R[]) ?? []).map((x, j) => j === k ? { ...x, what: e.target.value } : x) })} /><input className="input !w-36 !py-1 !text-xs" placeholder="qua bảng/file" aria-label="qua bảng/file" value={String(i.via ?? "")} onChange={(e) => setMeta({ ...meta, inputs: ((meta.inputs as R[]) ?? []).map((x, j) => j === k ? { ...x, via: e.target.value } : x) })} />{canW && <button className="text-danger-tok" onClick={() => setMeta({ ...meta, inputs: ((meta.inputs as R[]) ?? []).filter((_, j) => j !== k) })}>✕</button>}</div>)}</div>
              <div className="rounded-xl bg-brand-soft border border-brand-soft p-2"><div className="flex items-center"><b>ĐẦU RA — cấp cho bộ phận nào (1 → nhiều)</b>{canW && <button className="ml-auto underline text-xs" onClick={() => setMeta({ ...meta, outputs: [...((meta.outputs as R[]) ?? []), { to: "", what: "", via: "" }] })}>+ thêm</button>}</div>
                {(((meta.outputs as R[]) ?? [])).map((o, k) => <div key={k} className="flex gap-1 mt-1"><select className="input !w-32 !py-1 !text-xs" value={String(o.to ?? "")} onChange={(e) => setMeta({ ...meta, outputs: ((meta.outputs as R[]) ?? []).map((x, j) => j === k ? { ...x, to: e.target.value } : x) })}><option value="">bộ phận</option><option value="*">* mọi</option>{(depts.rows ?? []).map((d) => <option key={String(d.code)} value={String(d.code)}>{String(d.short ?? d.code)}</option>)}</select><input className="input !py-1 !text-xs" placeholder="cấp gì" aria-label="cấp gì" value={String(o.what ?? "")} onChange={(e) => setMeta({ ...meta, outputs: ((meta.outputs as R[]) ?? []).map((x, j) => j === k ? { ...x, what: e.target.value } : x) })} /><input className="input !w-36 !py-1 !text-xs" placeholder="qua bảng/file" aria-label="qua bảng/file" value={String(o.via ?? "")} onChange={(e) => setMeta({ ...meta, outputs: ((meta.outputs as R[]) ?? []).map((x, j) => j === k ? { ...x, via: e.target.value } : x) })} />{canW && <button className="text-danger-tok" onClick={() => setMeta({ ...meta, outputs: ((meta.outputs as R[]) ?? []).filter((_, j) => j !== k) })}>✕</button>}</div>)}</div>
              <div className="lg:col-span-2 rounded-xl bg-surface-2 border border-line p-2"><div className="flex items-center"><b>TÀI LIỆU · BIỂU MẪU · FILE · CÔNG CỤ · PHẦN MỀM cần cho quy trình</b>{canW && <button className="ml-auto underline text-xs" onClick={() => setMeta({ ...meta, documents: [...((meta.documents as R[]) ?? []), { kind: "BIEU_MAU", name: "", ref: "", required: true }] })}>+ thêm</button>}</div>
                {(((meta.documents as R[]) ?? [])).map((d, k) => <div key={k} className="flex gap-1 mt-1 items-center"><select className="input !w-32 !py-1 !text-xs" value={String(d.kind ?? "")} onChange={(e) => setMeta({ ...meta, documents: ((meta.documents as R[]) ?? []).map((x, j) => j === k ? { ...x, kind: e.target.value } : x) })}>{[["BIEU_MAU", "Biểu mẫu"], ["SOP", "SOP"], ["HO_SO", "Hồ sơ/sổ"], ["FILE", "File/giấy tờ"], ["CONG_CU", "Công cụ/thiết bị"], ["PHAN_MEM", "Màn hình/app"]].map(([v, l]) => <option key={v} value={v}>{l}</option>)}</select><input className="input !py-1 !text-xs" placeholder="tên" aria-label="tên" value={String(d.name ?? "")} onChange={(e) => setMeta({ ...meta, documents: ((meta.documents as R[]) ?? []).map((x, j) => j === k ? { ...x, name: e.target.value } : x) })} /><input className="input !w-44 !py-1 !text-xs" placeholder="bảng/đường dẫn/mã" aria-label="bảng/đường dẫn/mã" value={String(d.ref ?? "")} onChange={(e) => setMeta({ ...meta, documents: ((meta.documents as R[]) ?? []).map((x, j) => j === k ? { ...x, ref: e.target.value } : x) })} /><label className="text-xs whitespace-nowrap"><input type="checkbox" checked={d.required !== false} onChange={(e) => setMeta({ ...meta, documents: ((meta.documents as R[]) ?? []).map((x, j) => j === k ? { ...x, required: e.target.checked } : x) })} /> bắt buộc</label>{canW && <button className="text-danger-tok" onClick={() => setMeta({ ...meta, documents: ((meta.documents as R[]) ?? []).filter((_, j) => j !== k) })}>✕</button>}</div>)}</div>
            </div>
            {canW && <div className="flex gap-2 mt-2 flex-wrap"><button className="btn-secondary !py-2" onClick={saveMeta}>Lưu thông tin</button>{p && (p.status !== "BAN_HANH" ? <button className="btn-primary !py-2" onClick={async () => { if (!S.length) return setMsg("Cần ít nhất 1 bước"); const j = await act("publish_process", { code }); setMsg(j.ok ? "ĐÃ XUẤT BẢN — mọi phòng ban/nhân sự trong các bước đã được thông báo và đưa vào quy trình" : String(j.error)); reload(); }}>📣 Xuất bản & thông báo</button> : <><button className="btn-secondary !py-2" onClick={async () => { const j = await act("publish_process", { code }); setMsg(j.ok ? "Đã phát hành phiên bản mới & thông báo lại" : String(j.error)); reload(); }}>🔁 Phát hành lại (v+1)</button><button className="btn-secondary !py-2" onClick={async () => { await act("unpublish_process", { code, status: "NGUNG" }); reload(); }}>Ngưng</button></>)}</div>}
          </div>}
          {p && <div className="card"><div className="flex items-center mb-1"><b>Sơ đồ luồng: bộ phận nguồn ⇒ bước 1 → … → bước n ⇒ bộ phận nhận (tự vẽ theo khai báo)</b></div><ProcessFlow process={{ ...p, ...meta }} steps={S} depts={depts.rows ?? []} onStep={(st) => canW && setEditStep({ ...st })} />
            <div className="grid sm:grid-cols-3 gap-2 mt-2 text-xs"><div className="rounded-lg bg-warning-soft-tok p-2"><b>Nhận từ:</b> {[...new Set((((meta.inputs ?? p.inputs) as R[]) ?? []).map((i) => String(i.from)))].join(", ") || "—"}</div><div className="rounded-lg bg-surface-2 p-2"><b>Bộ phận thực hiện:</b> {[...new Set(S.map((st) => String(st.dept_code ?? "")))].filter(Boolean).join(" → ") || "—"}</div><div className="rounded-lg bg-brand-soft p-2"><b>Cấp cho:</b> {[...new Set((((meta.outputs ?? p.outputs) as R[]) ?? []).map((o) => String(o.to)))].join(", ") || "—"}</div></div>
            <div className="mt-2 text-xs"><b>Tài liệu/công cụ:</b> {(((meta.documents ?? p.documents) as R[]) ?? []).map((d, k) => <span key={k} className={`inline-block mr-1 mb-1 rounded-full px-2 py-0.5 border ${d.required !== false ? "bg-white border-line" : "bg-surface-2 border-line text-muted"}`}>{String(d.kind)}: {String(d.name)}</span>)}</div></div>}
          {p && <div className="card p-0 overflow-auto"><div className="px-3 py-2 bg-surface-2 rounded-t-2xl flex items-center"><b>Các bước ({S.length}) — mỗi bước: bộ phận · người · công cụ · vật tư · đầu vào → đầu ra</b>{canW && <button className="ml-auto btn-secondary !py-1 !px-2 !text-xs" onClick={() => setEditStep({ step_no: S.length + 1, name: "", dept_code: p.dept_code, actor_role: "worker", required: true, tools: [], materials: [], sla_hours: 24 })}>＋ Thêm bước</button>}</div>
            <table className="tbl text-sm"><thead><tr><th className="pl-3">#</th><th>Bước</th><th>Bộ phận / vai</th><th>Công cụ</th><th>Vật tư</th><th>Đầu vào → Đầu ra</th><th>Biểu mẫu / SLA</th><th></th></tr></thead><tbody>
              {S.map((s, i) => <tr key={String(s.id)}><td className="pl-3 font-black">{String(s.step_no)}{s.parallel_group ? <span className="text-xs text-muted">∥{String(s.parallel_group)}</span> : ""}</td><td><b>{String(s.name)}</b><div className="text-xs text-muted">{String(s.action ?? "")}</div></td><td className="text-xs"><b>{String(s.dept_code ?? "")}</b><br />{String(s.actor_role ?? "")}</td><td className="text-xs">{((s.tools as string[]) ?? []).join(", ")}</td><td className="text-xs">{((s.materials as R[]) ?? []).map((m) => `${m.sku ?? m.name} ${m.qty ?? ""}${m.unit ?? ""}`).join(", ")}</td><td className="text-xs">{String(s.inputs ?? "")} <b>→</b> {String(s.outputs ?? s.output ?? "")}</td><td className="text-xs font-mono">{String(s.form_table ?? "")}<br />{s.sla_hours ? `${s.sla_hours}h` : ""}</td><td className="text-xs whitespace-nowrap">{canW && <><button className="underline mr-1" onClick={() => setEditStep({ ...s })}>sửa</button>{i > 0 && <button className="mr-1" onClick={async () => { await act("move_step", { code, step_no: s.step_no, dir: -1 }); steps.reload(); }}>↑</button>}{i < S.length - 1 && <button className="mr-1" onClick={async () => { await act("move_step", { code, step_no: s.step_no, dir: 1 }); steps.reload(); }}>↓</button>}<button className="underline text-danger-tok" onClick={async () => { if (await confirm({ title: `Xóa bước ${s.step_no}: ${s.name}?`, danger: true })) { await act("delete_step", { code, step_no: s.step_no }); steps.reload(); } }}>xóa</button></>}</td></tr>)}
            </tbody></table>{!S.length && <div className="p-3 text-muted text-sm">Chưa có bước — bấm ＋ Thêm bước.</div>}</div>}
          {editStep && <div className="card border-2 border-brand-tok"><b>Bước {String(editStep.step_no)}</b>
            <div className="grid sm:grid-cols-2 lg:grid-cols-3 gap-2 mt-2 text-sm">
              <label className="lg:col-span-2">Tên bước<input className="input" value={String(editStep.name ?? "")} onChange={(e) => setEditStep({ ...editStep, name: e.target.value })} /></label>
              <label>Thứ tự<input className="input" type="number" value={String(editStep.step_no ?? "")} onChange={(e) => setEditStep({ ...editStep, step_no: Number(e.target.value) })} /></label>
              <label>Bộ phận thực hiện<select className="input" value={String(editStep.dept_code ?? "")} onChange={(e) => setEditStep({ ...editStep, dept_code: e.target.value })}>{(depts.rows ?? []).map((d) => <option key={String(d.code)} value={String(d.code)}>{String(d.short ?? d.name)}</option>)}</select></label>
              <label>Vai thực hiện (nhận việc)<select className="input" value={String(editStep.actor_role ?? "")} onChange={(e) => setEditStep({ ...editStep, actor_role: e.target.value })}>{ROLES.map((r) => <option key={r}>{r}</option>)}</select></label>
              <label>SLA (giờ) · thời lượng (phút)<div className="flex gap-1"><input className="input" type="number" value={String(editStep.sla_hours ?? "")} onChange={(e) => setEditStep({ ...editStep, sla_hours: Number(e.target.value) })} /><input className="input" type="number" value={String(editStep.duration_min ?? "")} onChange={(e) => setEditStep({ ...editStep, duration_min: Number(e.target.value) })} /></div></label>
              <label className="lg:col-span-3">Làm gì (mô tả thao tác)<input className="input" value={String(editStep.action ?? "")} onChange={(e) => setEditStep({ ...editStep, action: e.target.value })} /></label>
              <label>Công cụ / thiết bị (chọn hoặc gõ, cách nhau dấu phẩy)<input className="input" list="devlist" value={Array.isArray(editStep.tools) ? (editStep.tools as string[]).join(", ") : String(editStep.tools ?? "")} onChange={(e) => setEditStep({ ...editStep, tools: e.target.value })} /><datalist id="devlist">{(devices.rows ?? []).map((d) => <option key={String(d.id)} value={String(d.name)} />)}</datalist></label>
              <label>Đầu vào (cần gì trước khi làm)<input className="input" value={String(editStep.inputs ?? "")} onChange={(e) => setEditStep({ ...editStep, inputs: e.target.value })} /></label>
              <label>Đầu ra (tạo ra gì)<input className="input" value={String(editStep.outputs ?? "")} onChange={(e) => setEditStep({ ...editStep, outputs: e.target.value })} /></label>
              <label>Biểu mẫu/bảng phải ghi để xong bước<select className="input" value={String(editStep.form_table ?? "")} onChange={(e) => setEditStep({ ...editStep, form_table: e.target.value })}>{FORMS.map((f) => <option key={f} value={f}>{f || "— không —"}</option>)}</select></label>
              <label>Ở đâu trong hệ thống<input className="input" value={String(editStep.system_where ?? "")} onChange={(e) => setEditStep({ ...editStep, system_where: e.target.value })} placeholder="/ca A6 · /kho" /></label>
              <label>Kiểm soát / điều kiện qua bước<input className="input" value={String(editStep.control ?? "")} onChange={(e) => setEditStep({ ...editStep, control: e.target.value })} /></label>
              <label>Nhóm song song (cùng số = làm đồng thời)<input className="input" type="number" value={String(editStep.parallel_group ?? "")} onChange={(e) => setEditStep({ ...editStep, parallel_group: e.target.value ? Number(e.target.value) : null })} /></label>
              <label className="lg:col-span-3">Tài liệu/biểu mẫu/file riêng của bước (mỗi dòng: loại|tên|tham chiếu)<textarea className="input font-mono text-xs" rows={2} value={((editStep.documents as R[]) ?? []).map((d) => `${d.kind ?? "BIEU_MAU"}|${d.name ?? ""}|${d.ref ?? ""}`).join("\n")} onChange={(e) => setEditStep({ ...editStep, documents: e.target.value.split("\n").filter((l) => l.trim()).map((l) => { const [kind, name, ref] = l.split("|"); return { kind: kind?.trim() || "BIEU_MAU", name: name?.trim() ?? "", ref: ref?.trim() ?? "", required: true }; }) })} placeholder="BIEU_MAU|Phiếu cân|weigh_tickets" /></label>
              <label className="flex items-center gap-2 mt-5"><input type="checkbox" checked={editStep.required !== false} onChange={(e) => setEditStep({ ...editStep, required: e.target.checked })} /> Bắt buộc</label>
              <div className="lg:col-span-3"><b>Vật tư / tư liệu sản xuất</b> <button className="underline text-xs ml-2" onClick={() => setEditStep({ ...editStep, materials: [...mat, { sku: "", qty: 0, unit: "" }] })}>+ thêm dòng</button>
                {mat.map((m, i) => <div key={i} className="flex gap-1 mt-1"><select className="input !w-72 !py-1" value={String(m.sku ?? "")} onChange={(e) => setEditStep({ ...editStep, materials: mat.map((x, j) => j === i ? { ...x, sku: e.target.value } : x) })}><option value="">— SKU —</option>{(products.rows ?? []).map((pr) => <option key={String(pr.sku)} value={String(pr.sku)}>{String(pr.name)} ({String(pr.sku)})</option>)}</select><input className="input !w-28 !py-1" type="number" placeholder="SL" aria-label="SL" value={String(m.qty ?? "")} onChange={(e) => setEditStep({ ...editStep, materials: mat.map((x, j) => j === i ? { ...x, qty: Number(e.target.value) } : x) })} /><input className="input !w-28 !py-1" placeholder="đv (kg/ha…)" aria-label="đv (kg/ha…)" value={String(m.unit ?? "")} onChange={(e) => setEditStep({ ...editStep, materials: mat.map((x, j) => j === i ? { ...x, unit: e.target.value } : x) })} /><button className="text-danger-tok" onClick={() => setEditStep({ ...editStep, materials: mat.filter((_, j) => j !== i) })}>✕</button></div>)}</div>
            </div>
            <div className="flex gap-2 mt-2"><button className="btn-primary !py-2" onClick={saveStep}>Lưu bước</button><button className="btn-secondary !py-2" onClick={() => setEditStep(null)}>Hủy</button></div></div>}
          {!p && !newP && <div className="card text-muted">Chọn quy trình bên trái, hoặc ＋ Mới để khai báo. Xuất bản xong → mọi phòng ban/nhân sự trong các bước nhận thông báo; bấm ▶ Chạy để hệ thống sinh việc theo từng bước (người làm nhận việc trong Ca của tôi, xong bước → bước kế tự kích hoạt).</div>}
        </div>
      </div>}
      {tab === "chay" && <div className="space-y-3">
        {!runsActive.length && <div className="card text-muted">Chưa có quy trình đang chạy. Vào Thiết kế → chọn quy trình đã xuất bản → ▶ Chạy.</div>}
        {(runs.rows ?? []).map((r) => { const rs = (runSteps.rows ?? []).filter((x) => x.run_id === r.id); return <div key={String(r.id)} className="card"><div className="flex items-center gap-2 flex-wrap"><b>{String(r.process_code)} · {String(r.title)}</b><span className={r.status === "DANG_CHAY" ? "b-yel" : r.status === "XONG" ? "b-grn" : "b-gray"}>{String(r.status)}</span><span className="text-sm text-muted">{String(r.steps_done)}/{String(r.steps_total)} bước · bắt đầu {fmt.dt(r.started_at)} bởi {String(r.started_by)}</span>{r.status === "DANG_CHAY" && canW && <button className="ml-auto underline text-sm text-danger-tok" onClick={async () => { if (await confirm({ title: "Hủy lần chạy này?", danger: true })) { await act("cancel_run", { run_id: r.id }); reload(); } }}>hủy</button>}</div>
          {r.status === "DANG_CHAY" && <div className="mt-2 flex flex-wrap gap-1">{rs.map((s) => <div key={String(s.id)} className={`rounded-xl px-2 py-1 text-xs border ${s.status === "XONG" ? "bg-brand-soft border-green-400" : s.status === "DANG_LAM" ? "bg-warning-soft-tok border-amber-400 font-bold" : "bg-surface-2"}`}>{String(s.step_no)}. {String(s.name)} <span className="text-muted">{String(s.dept_code ?? "")}/{String(s.actor_role ?? "")}</span>{s.status === "DANG_LAM" && <button className="ml-2 underline" onClick={async () => { const note = (await prompt({ title: "Hoàn thành bước", label: "Ghi chú/tham chiếu kết quả (tùy chọn)", type: "text", required: false })) ?? ""; const j = await act("complete_step", { run_id: r.id, step_no: s.step_no, note }); setMsg(j.ok ? `Bước ${s.step_no} xong → ${j.result}` : String(j.error)); reload(); }}>✓ xong</button>}</div>)}</div>}
          {r.status !== "DANG_CHAY" && <div className="text-xs text-muted mt-1">{String(r.current_names ?? "")}</div>}</div>; })}
      </div>}
    </div>);
}
