"use client";
import { useState } from "react";
import { useData, act, fmt } from "@/lib/client";
import type { Sess } from "@/components/Shell";
import { usePrompt } from "@/components/ui/PromptDialog";
type R = Record<string, unknown>;
const adm = (t: string, row: R) => fetch(`/api/admin/${t}`, { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ row }) }).then((r) => r.json());
/** Bán hàng nâng cao: bảng giá theo khách/nhóm + bậc CK (price_for), báo giá → đơn, chỉ tiêu/hoa hồng, điểm thưởng, công nợ theo hạn + nhắc nợ 3 mức, lịch giao HĐ bao tiêu */
export function GiaPanel({ sess }: { sess: Sess }) {
  const cp = useData("customer_prices"); const dt = useData("discount_tiers"); const partners = useData("partners"); const products = useData("products");
  const [f, setF] = useState<R>({ qty: "1" }); const [res, setRes] = useState<R | null>(null);
  const canW = ["owner", "director", "accountant", "it_engineer"].includes(sess.role);
  return <div className="space-y-3">
    <div className="card"><b>Tra giá áp dụng</b> <span className="text-xs text-stone-500">— thứ tự: giá riêng khách → giá nhóm → niêm yết (THI_TRUONG) → bậc chiết khấu số lượng; không dưới giá sàn (SAN) nếu chưa được duyệt</span><div className="flex gap-2 flex-wrap mt-2"><select className="input !w-64" value={String(f.partner_id ?? "")} onChange={(e) => setF({ ...f, partner_id: e.target.value })}><option value="">Khách (lẻ)</option>{(partners.rows ?? []).filter((p) => p.kind === "KH").map((p) => <option key={String(p.id)} value={String(p.id)}>{String(p.name)} {p.customer_group ? `· ${p.customer_group}` : ""}</option>)}</select><select className="input !w-64" value={String(f.sku ?? "")} onChange={(e) => setF({ ...f, sku: e.target.value })}><option value="">Sản phẩm</option>{(products.rows ?? []).filter((p) => ["THANH_PHAM", "BAN_TP", "DICH_VU"].includes(String(p.kind))).map((p) => <option key={String(p.sku)} value={String(p.sku)}>{String(p.name)}</option>)}</select><input className="input !w-24" type="number" value={String(f.qty)} onChange={(e) => setF({ ...f, qty: e.target.value })} /><button className="btn-primary !py-2" disabled={!f.sku} onClick={async () => setRes(await act("price_for", { partner_id: f.partner_id || null, sku: f.sku, qty: Number(f.qty) }))}>Tra</button></div>
      {res && (res.ok ? <div className={`mt-2 rounded-xl p-3 ${res.below_floor ? "bg-red-50 border border-red-300" : "bg-emerald-50"}`}><b className="text-xl">{fmt.vnd(Number(res.price))}</b> <span className="text-sm">niêm yết {fmt.vnd(Number(res.list_price))} · CK {String(res.discount_pct)}% · nguồn {String(res.source)} · sàn {fmt.vnd(Number(res.floor_price ?? 0))}{res.below_floor ? " — DƯỚI SÀN: cần GĐ duyệt (discount_approved_by)" : ""}</span></div> : <div className="text-red-700 text-sm">{String(res.error)}</div>)}</div>
    <div className="grid lg:grid-cols-2 gap-3"><div className="card p-0 overflow-auto"><div className="px-3 py-2 bg-stone-100 rounded-t-2xl font-bold flex items-center gap-2">Giá riêng theo khách / nhóm khách {canW && <a className="ml-auto underline text-sm font-normal" href="/quan-tri?t=customer_prices">＋</a>}</div><table className="tbl text-sm"><thead><tr><th className="pl-3">Khách / nhóm</th><th>SP</th><th className="text-right">Giá</th><th className="text-right">CK %</th><th className="text-right">Từ SL</th><th>Hiệu lực</th></tr></thead><tbody>{(cp.rows ?? []).map((r) => <tr key={String(r.id)}><td className="pl-3">{String(r.partner_name ?? r.customer_group)}</td><td>{String(r.product_name)}</td><td className="text-right">{r.price ? fmt.vnd(Number(r.price)) : ""}</td><td className="text-right">{String(r.discount_pct ?? "")}</td><td className="text-right">{String(r.min_qty ?? 0)}</td><td className="text-xs">{String(r.valid_from)} → {String(r.valid_to ?? "∞")}</td></tr>)}</tbody></table></div>
      <div className="card p-0 overflow-auto"><div className="px-3 py-2 bg-stone-100 rounded-t-2xl font-bold flex items-center gap-2">Bậc chiết khấu số lượng {canW && <a className="ml-auto underline text-sm font-normal" href="/quan-tri?t=discount_tiers">＋</a>}</div><table className="tbl text-sm"><thead><tr><th className="pl-3">SP</th><th>Nhóm</th><th className="text-right">Từ SL</th><th className="text-right">CK %</th><th>Ghi chú</th></tr></thead><tbody>{(dt.rows ?? []).map((r) => <tr key={String(r.id)}><td className="pl-3">{String(r.product_name ?? "Mọi SP")}</td><td>{String(r.customer_group ?? "Mọi nhóm")}</td><td className="text-right">{String(r.min_qty)}</td><td className="text-right">{String(r.discount_pct)}</td><td className="text-xs">{String(r.note ?? "")}</td></tr>)}</tbody></table></div></div></div>;
}
export function BaoGiaPanel({ sess }: { sess: Sess }) {
  const quotes = useData("quotes"); const partners = useData("partners"); const products = useData("products"); const [q, setQ] = useState<R | null>(null); const [msg, setMsg] = useState("");
  const L = (q?.lines as R[]) ?? [];
  const recalc = (lines: R[], vat: number, disc: number) => { const sub = lines.reduce((a, l) => a + Number(l.qty) * Number(l.price) * (1 - Number(l.discount_pct ?? 0) / 100), 0); return { subtotal: Math.round(sub), total: Math.round((sub - disc) * (1 + vat / 100)) }; };
  const addLine = async (sku: string) => { if (!q) return; const p = (products.rows ?? []).find((x) => x.sku === sku); const pr = await act("price_for", { partner_id: q.partner_id || null, sku, qty: 1 }); const nl = [...L, { sku, name: p?.name, qty: 1, unit: p?.unit, price: Number(pr.price ?? 0), discount_pct: 0 }]; setQ({ ...q, lines: nl, ...recalc(nl, Number(q.vat_pct ?? 0), Number(q.discount ?? 0)) }); };
  const save = async () => { if (!q) return; const lines = L.map((l) => ({ ...l, amount: Math.round(Number(l.qty) * Number(l.price) * (1 - Number(l.discount_pct ?? 0) / 100)) })); const j = await adm("quotes", { ...q, lines, sales_rep_id: q.sales_rep_id ?? sess.staffId, ...recalc(lines, Number(q.vat_pct ?? 0), Number(q.discount ?? 0)) }); setMsg(j.ok ? `Đã lưu ${j.row?.id ?? ""}` : `${j.error}: ${j.detail ?? ""}`); if (j.ok) { setQ(null); quotes.reload(); } };
  return <div className="space-y-3">
    <div className="flex gap-2 items-center"><button className="btn-primary !py-2" onClick={() => setQ({ quote_date: new Date().toISOString().slice(0, 10), valid_until: new Date(Date.now() + 7 * 864e5).toISOString().slice(0, 10), lines: [], vat_pct: 0, discount: 0, status: "NHAP", payment_terms: "COD", delivery_terms: "Giao tại kho trại" })}>＋ Báo giá mới</button>{msg && <span className="text-sm text-emerald-700">{msg}</span>}</div>
    {q && <div className="card"><div className="grid sm:grid-cols-3 lg:grid-cols-6 gap-2"><select className="input lg:col-span-2" value={String(q.partner_id ?? "")} onChange={(e) => setQ({ ...q, partner_id: e.target.value })}><option value="">Khách</option>{(partners.rows ?? []).filter((p) => p.kind === "KH").map((p) => <option key={String(p.id)} value={String(p.id)}>{String(p.name)}</option>)}</select><input className="input" type="date" value={String(q.valid_until)} onChange={(e) => setQ({ ...q, valid_until: e.target.value })} /><input className="input" placeholder="Thanh toán" value={String(q.payment_terms ?? "")} onChange={(e) => setQ({ ...q, payment_terms: e.target.value })} /><input className="input" placeholder="Giao hàng" value={String(q.delivery_terms ?? "")} onChange={(e) => setQ({ ...q, delivery_terms: e.target.value })} /><input className="input" type="number" placeholder="VAT %" value={String(q.vat_pct ?? 0)} onChange={(e) => setQ({ ...q, vat_pct: e.target.value, ...recalc(L, Number(e.target.value), Number(q.discount ?? 0)) })} /></div>
      <div className="flex gap-2 mt-2"><select className="input !w-80" onChange={(e) => { if (e.target.value) addLine(e.target.value); e.target.value = ""; }}><option value="">＋ thêm sản phẩm (giá tự tra theo khách)</option>{(products.rows ?? []).filter((p) => ["THANH_PHAM", "BAN_TP", "DICH_VU"].includes(String(p.kind))).map((p) => <option key={String(p.sku)} value={String(p.sku)}>{String(p.name)}</option>)}</select></div>
      <table className="tbl text-sm mt-2"><thead><tr><th>SP</th><th className="text-right">SL</th><th className="text-right">Giá</th><th className="text-right">CK %</th><th className="text-right">Thành tiền</th><th></th></tr></thead><tbody>{L.map((l, i) => <tr key={i}><td>{String(l.name)}</td><td><input className="input !w-20 !py-1 text-right" type="number" value={String(l.qty)} onChange={(e) => { const nl = L.map((x, j) => j === i ? { ...x, qty: Number(e.target.value) } : x); setQ({ ...q, lines: nl, ...recalc(nl, Number(q.vat_pct ?? 0), Number(q.discount ?? 0)) }); }} /></td><td><input className="input !w-28 !py-1 text-right" type="number" value={String(l.price)} onChange={(e) => { const nl = L.map((x, j) => j === i ? { ...x, price: Number(e.target.value) } : x); setQ({ ...q, lines: nl, ...recalc(nl, Number(q.vat_pct ?? 0), Number(q.discount ?? 0)) }); }} /></td><td><input className="input !w-16 !py-1 text-right" type="number" value={String(l.discount_pct ?? 0)} onChange={(e) => { const nl = L.map((x, j) => j === i ? { ...x, discount_pct: Number(e.target.value) } : x); setQ({ ...q, lines: nl, ...recalc(nl, Number(q.vat_pct ?? 0), Number(q.discount ?? 0)) }); }} /></td><td className="text-right">{fmt.vnd(Number(l.qty) * Number(l.price) * (1 - Number(l.discount_pct ?? 0) / 100))}</td><td><button className="text-red-700" onClick={() => { const nl = L.filter((_, j) => j !== i); setQ({ ...q, lines: nl, ...recalc(nl, Number(q.vat_pct ?? 0), Number(q.discount ?? 0)) }); }}>✕</button></td></tr>)}</tbody></table>
      <div className="flex gap-3 items-center mt-2 flex-wrap"><textarea className="input flex-1" rows={2} placeholder="Điều khoản / ghi chú" value={String(q.terms ?? "")} onChange={(e) => setQ({ ...q, terms: e.target.value })} /><div className="text-right"><div>Cộng: <b>{fmt.vnd(Number(q.subtotal ?? 0))}</b></div><div className="text-lg">Tổng: <b>{fmt.vnd(Number(q.total ?? 0))}</b></div></div><button className="btn-primary !py-2" disabled={!L.length || !q.partner_id} onClick={save}>Lưu</button><button className="btn-secondary !py-2" onClick={() => setQ(null)}>Hủy</button></div></div>}
    <div className="card p-0 overflow-auto"><table className="tbl text-sm"><thead><tr><th className="pl-3">Số</th><th>Khách</th><th>Ngày</th><th>Hiệu lực</th><th className="text-right">Tổng</th><th>NV</th><th>TT</th><th>Đơn</th><th></th></tr></thead><tbody>{(quotes.rows ?? []).map((r) => <tr key={String(r.id)}><td className="pl-3 font-mono text-xs">{String(r.id)}</td><td>{String(r.partner_name ?? "")}</td><td>{fmt.d(String(r.quote_date))}</td><td>{fmt.d(String(r.valid_until))}</td><td className="text-right">{fmt.vnd(Number(r.total))}</td><td className="text-xs">{String(r.rep_name ?? "")}</td><td><span className={`rounded-full px-2 text-xs ${r.status === "THANH_DON" ? "bg-emerald-100" : r.status === "GUI" ? "bg-amber-100" : "bg-stone-100"}`}>{String(r.status)}</span></td><td className="font-mono text-xs">{String(r.order_id ?? "")}</td><td className="text-xs whitespace-nowrap"><a className="underline mr-2" href={`/in/bao-gia/${r.id}`} target="_blank">in PDF</a>{r.status === "NHAP" && <button className="underline mr-2" onClick={async () => { await act("send_quote", { id: r.id }); quotes.reload(); }}>gửi</button>}{["NHAP", "GUI", "CHAP_NHAN"].includes(String(r.status)) && <button className="underline mr-2" onClick={async () => { const j = await act("quote_to_order", { id: r.id }); setMsg(j.ok ? `Đã tạo đơn ${j.order_id}` : String(j.error)); quotes.reload(); }}>→ tạo đơn</button>}<button className="underline" onClick={() => setQ({ ...r })}>sửa</button></td></tr>)}</tbody></table></div></div>;
}
export function ChiTieuPanel() {
  const perf = useData("sales_performance");
  return <div className="card p-0 overflow-auto"><div className="px-3 py-2 bg-stone-100 rounded-t-2xl font-bold flex items-center gap-2">Chỉ tiêu & hoa hồng NVKD theo tháng/kênh (sales.sales_rep_id hoặc người ghi) <a className="ml-auto underline text-sm font-normal" href="/quan-tri?t=sales_targets">＋ chỉ tiêu</a></div><table className="tbl text-sm"><thead><tr><th className="pl-3">Kỳ</th><th>NVKD</th><th>Kênh</th><th className="text-right">Chỉ tiêu</th><th className="text-right">Thực đạt</th><th className="text-right">%</th><th className="text-right">Khách</th><th className="text-right">HH %</th><th className="text-right">Hoa hồng</th></tr></thead><tbody>{(perf.rows ?? []).map((r, i) => <tr key={i} className={Number(r.pct) >= 100 ? "bg-emerald-50" : ""}><td className="pl-3">{String(r.period)}</td><td>{String(r.full_name ?? "Toàn trại")}</td><td>{String(r.channel_code ?? "tất cả")}</td><td className="text-right">{fmt.vnd(Number(r.target_amount ?? 0))}</td><td className="text-right">{fmt.vnd(Number(r.actual_amount))}</td><td className="text-right font-bold">{String(r.pct ?? "")}</td><td className="text-right">{String(r.customers)}</td><td className="text-right">{String(r.commission_pct)}</td><td className="text-right">{fmt.vnd(Number(r.commission))}</td></tr>)}</tbody></table>{perf.rows?.length === 0 && <div className="p-3 text-sm text-stone-500">Chưa có chỉ tiêu.</div>}<div className="p-2 text-xs text-stone-500">Hoa hồng ghi vào bảng lương qua phụ cấp (payroll: allowances) — KTT duyệt.</div></div>;
}
export function DiemPanel() {
  const top = useData("loyalty_top"); const led = useData("loyalty_ledger"); const [msg, setMsg] = useState(""); const { prompt, promptElement } = usePrompt();
  return <div className="grid lg:grid-cols-2 gap-3">{promptElement}<div className="card p-0 overflow-auto"><div className="px-3 py-2 bg-stone-100 rounded-t-2xl font-bold">Điểm thưởng khách (1 điểm/10.000đ — settings loyalty.points_per_10k) · hạng BẠC &lt;1000 · VÀNG ≥1000 · KIM CƯƠNG ≥5000</div><table className="tbl text-sm"><thead><tr><th className="pl-3">Khách</th><th>Nhóm</th><th className="text-right">Điểm</th><th>Hạng</th><th>TT</th><th></th></tr></thead><tbody>{(top.rows ?? []).map((r) => <tr key={String(r.id)}><td className="pl-3">{String(r.name)}</td><td>{String(r.customer_group ?? "")}</td><td className="text-right font-bold">{fmt.n(Number(r.loyalty_points ?? 0))}</td><td>{String(r.loyalty_tier ?? "")}</td><td className="text-xs">{String(r.payment_terms ?? "")}</td><td className="text-xs">{Number(r.loyalty_points) > 0 && <button className="underline" onClick={async () => { const raw = await prompt({ title: "Đổi điểm thưởng", label: `Đổi bao nhiêu điểm (có ${r.loyalty_points})?`, type: "number", min: 0 }); if (raw == null) return; const j = await act("redeem_points", { partner_id: r.id, points: Number(raw) }); setMsg(j.ok ? `Đã đổi, còn ${j.balance}` : String(j.error)); top.reload(); led.reload(); }}>đổi điểm</button>}</td></tr>)}</tbody></table>{msg && <div className="p-2 text-sm text-emerald-700">{msg}</div>}</div>
    <div className="card p-0 overflow-auto"><div className="px-3 py-2 bg-stone-100 rounded-t-2xl font-bold">Sổ điểm</div><table className="tbl text-sm"><thead><tr><th className="pl-3">Lúc</th><th>Khách</th><th className="text-right">Điểm</th><th>Lý do</th><th>Tham chiếu</th></tr></thead><tbody>{(led.rows ?? []).map((r) => <tr key={String(r.id)}><td className="pl-3 text-xs">{fmt.dt(String(r.ts))}</td><td>{String(r.partner_name)}</td><td className={`text-right ${Number(r.points) < 0 ? "text-red-700" : ""}`}>{String(r.points)}</td><td>{String(r.reason)}</td><td className="font-mono text-xs">{String(r.ref_id ?? "")}</td></tr>)}</tbody></table></div></div>;
}
export function CongNoPanel({ sess }: { sess: Sess }) {
  const ar = useData("ar_summary"); const dl = useData("dunning_log"); const [sel, setSel] = useState<string | null>(null); const rows = useData(sel ? "ar_aging_rows" : null, { partner: sel ?? undefined }, [sel]); const [msg, setMsg] = useState("");
  const canRun = ["owner", "director", "accountant"].includes(sess.role);
  const tot = (k: string) => (ar.rows ?? []).reduce((a, r) => a + Number(r[k] ?? 0), 0);
  return <div className="space-y-3"><div className="grid grid-cols-2 sm:grid-cols-5 gap-2"><div className="kpi"><div className="l">Tổng nợ</div><div className="v">{fmt.vnd(tot("unpaid"))}</div></div><div className="kpi"><div className="l">Chưa đến hạn</div><div className="v">{fmt.vnd(tot("not_due"))}</div></div><div className="kpi"><div className="l">1–30 ngày</div><div className="v text-amber-700">{fmt.vnd(tot("d1_30"))}</div></div><div className="kpi"><div className="l">31–60</div><div className="v text-orange-700">{fmt.vnd(tot("d31_60"))}</div></div><div className="kpi"><div className="l">&gt;60</div><div className="v text-red-700">{fmt.vnd(tot("d60p"))}</div></div></div>
    <div className="card p-0 overflow-auto"><div className="px-3 py-2 bg-stone-100 rounded-t-2xl font-bold flex items-center gap-2 flex-wrap">Công nợ theo hạn (payment_terms COD/NET7/15/30 hoặc credit_days) — nhắc nợ 3 mức: 1–7 ngày nhắc nhẹ · 8–30 nhắc + KTT · &gt;30 khóa bán chịu + báo GĐ (job đêm) {canRun && <button className="ml-auto btn-secondary !py-1 !px-3 !text-sm" onClick={async () => { const j = await act("run_dunning", {}); setMsg(j.ok ? `Đã nhắc ${j.n} khách` : String(j.error)); dl.reload(); ar.reload(); }}>Chạy nhắc nợ ngay</button>}</div>{msg && <div className="px-3 py-1 text-sm text-emerald-700">{msg}</div>}<table className="tbl text-sm"><thead><tr><th className="pl-3">Khách</th><th className="text-right">Nợ</th><th className="text-right">Chưa hạn</th><th className="text-right">1–30</th><th className="text-right">31–60</th><th className="text-right">&gt;60</th><th className="text-right">Quá hạn max</th><th className="text-right">HĐ</th><th>Hạn mức</th></tr></thead><tbody>{(ar.rows ?? []).map((r) => <tr key={String(r.partner_id)} className={`${Number(r.d60p) > 0 ? "bg-red-50" : Number(r.d31_60) > 0 ? "bg-orange-50" : ""} ${sel === r.partner_id ? "outline outline-emerald-400" : ""}`}><td className="pl-3"><button className="underline text-left" onClick={() => setSel(String(r.partner_id))}>{String(r.partner_name)}</button></td><td className="text-right font-bold">{fmt.vnd(Number(r.unpaid))}</td><td className="text-right">{fmt.vnd(Number(r.not_due ?? 0))}</td><td className="text-right">{fmt.vnd(Number(r.d1_30 ?? 0))}</td><td className="text-right">{fmt.vnd(Number(r.d31_60 ?? 0))}</td><td className="text-right text-red-700">{fmt.vnd(Number(r.d60p ?? 0))}</td><td className="text-right">{String(r.max_overdue)} ngày</td><td className="text-right">{String(r.n_inv)}</td><td className="text-xs">{r.credit_limit != null ? `${fmt.vnd(Number(r.credit_limit))}${r.over_limit ? " ⚠ vượt" : ""}` : ""}</td></tr>)}</tbody></table>{ar.rows?.length === 0 && <div className="p-3 text-sm text-stone-500">Không có công nợ.</div>}</div>
    {sel && <div className="card p-0 overflow-auto"><div className="px-3 py-2 bg-stone-100 rounded-t-2xl font-bold">Chi tiết hóa đơn chưa thu — {sel}</div><table className="tbl text-sm"><thead><tr><th className="pl-3">Ngày bán</th><th>HĐ</th><th className="text-right">Số tiền</th><th>Đến hạn</th><th className="text-right">Quá hạn</th><th></th></tr></thead><tbody>{(rows.rows ?? []).map((r) => <tr key={String(r.sale_id)} className={Number(r.days_overdue) > 0 ? "bg-amber-50" : ""}><td className="pl-3">{fmt.d(String(r.ts))}</td><td className="font-mono text-xs">{String(r.invoice_no ?? r.sale_id)}</td><td className="text-right">{fmt.vnd(Number(r.amount))}</td><td>{fmt.d(String(r.due_date))}</td><td className="text-right">{String(r.days_overdue)} ngày</td><td className="text-xs"><a className="underline" href={`/in/hoa-don/${r.sale_id}`} target="_blank">in HĐ + VietQR</a></td></tr>)}</tbody></table></div>}
    <div className="card p-0 overflow-auto"><div className="px-3 py-2 bg-stone-100 rounded-t-2xl font-bold">Nhật ký nhắc nợ</div><table className="tbl text-sm"><thead><tr><th className="pl-3">Lúc</th><th>Khách</th><th>Mức</th><th className="text-right">Nợ</th><th>Kênh</th><th>Ghi chú</th></tr></thead><tbody>{(dl.rows ?? []).map((r) => <tr key={String(r.id)}><td className="pl-3 text-xs">{fmt.dt(String(r.sent_at))}</td><td>{String(r.partner_name)}</td><td>{String(r.level)}</td><td className="text-right">{fmt.vnd(Number(r.amount))}</td><td>{String(r.channel)}</td><td className="text-xs">{String(r.note ?? "")}</td></tr>)}</tbody></table></div></div>;
}
export function LichHDPanel() {
  const sch = useData("contract_schedule"); const contracts = useData("contracts"); const [msg, setMsg] = useState(""); const { prompt, promptElement } = usePrompt();
  return <div className="space-y-3">{promptElement}<div className="card flex gap-2 items-center flex-wrap"><b>Sinh lịch giao từ hợp đồng bao tiêu</b>{(contracts.rows ?? []).filter((c) => c.status !== "HET_HAN").slice(0, 10).map((c) => <button key={String(c.id)} className="btn-secondary !py-1 !px-3 !text-sm" onClick={async () => { const d = await prompt({ title: "Sinh lịch giao", label: "Chu kỳ giao (ngày)?", type: "number", min: 0, defaultValue: "7" }); if (!d) return; const j = await act("gen_contract_deliveries", { id: c.id, every_days: Number(d) }); setMsg(j.ok ? `Đã sinh ${j.n} kỳ giao cho ${c.id}` : String(j.error)); sch.reload(); }}>{String(c.id)} · {String(c.sku)}</button>)}{msg && <span className="text-sm text-emerald-700">{msg}</span>}</div>
    <div className="card p-0 overflow-auto"><table className="tbl text-sm"><thead><tr><th className="pl-3">Ngày giao</th><th>HĐ</th><th>Khách</th><th>SP</th><th className="text-right">KH</th><th className="text-right">Đã giao</th><th>Đơn</th><th>TT</th></tr></thead><tbody>{(sch.rows ?? []).map((r) => <tr key={String(r.id)} className={r.late ? "bg-red-50" : r.status === "DA_GIAO" ? "bg-emerald-50" : ""}><td className="pl-3">{fmt.d(String(r.planned_date))}</td><td className="font-mono text-xs">{String(r.contract_id)}</td><td>{String(r.partner_name ?? "")}</td><td>{String(r.product_name ?? r.sku)}</td><td className="text-right">{fmt.n(Number(r.planned_qty))} {String(r.unit ?? "")}</td><td className="text-right">{fmt.n(Number(r.delivered_qty ?? 0))}</td><td className="font-mono text-xs">{String(r.order_id ?? "")}</td><td>{String(r.status)}{r.late ? " ⚠ trễ" : ""}</td></tr>)}</tbody></table>{sch.rows?.length === 0 && <div className="p-3 text-sm text-stone-500">Chưa có lịch giao — bấm hợp đồng ở trên để sinh.</div>}<div className="p-2 text-xs text-stone-500">Trễ → cảnh báo AL-CONTRACT-LATE. Cập nhật đã giao ở <a className="underline" href="/quan-tri?t=contract_deliveries">contract_deliveries</a> hoặc gắn order_id.</div></div></div>;
}
