"use client";
import { useState } from "react";
import { useData, fmt } from "@/lib/client";
import type { Sess } from "@/components/Shell";
import AnyChart from "@/components/AnyChart";
import Tabs from "@/components/Tabs";
type R = Record<string, unknown>;
const LINES: [string, string, string][] = [["TRUN_NAP", "Trùn: nạp phân", "kg phân ủ sơ nạp luống"], ["TRUN_THU", "Trùn: thu phân trùn", "kg phân trùn / trùn tươi"], ["BSF", "BSF ấu trùng", "kg rác hữu cơ vào → ấu trùng + compost"], ["BIOGAS", "Biogas", "kg phân vào → kWh điện / m³ khí"], ["COMPOST", "Compost – biochar – giấm gỗ", "mẻ ủ hiếu khí, than sinh học"], ["IMO_EM", "Nhân men IMO/EM", "lít men vi sinh"], ["ANOLYTE", "Trạm anolyte", "lít nước điện hóa · ppm"]];
/** SINH HỌC TUẦN HOÀN (khu D): mỗi dây chuyền có mẻ (batch_logs.line), đầu vào phân/rác → đầu ra phân trùn/BSF/điện/compost/men/anolyte; KPI 30 ngày; luống trùn; nối kho (K5 phân trùn) và CO2e */
export default function SinhHoc({ sess }: { sess: Sess }) {
  const [tab, setTab] = useState<string>("tong");
  const pb = useData("bio_batches"); const luong = useData("bio_beds");
  const B = pb.rows ?? []; const last30 = (line: string) => B.filter((b) => b.line === line && new Date(String(b.ts)) > new Date(Date.now() - 30 * 864e5));
  const sumIn = (rows: R[]) => rows.reduce((a, b) => a + ((b.inputs as R[]) ?? []).reduce((x, i) => x + Number(i.kg ?? 0), 0), 0); const sumOut = (rows: R[]) => rows.reduce((a, b) => a + ((b.outputs as R[]) ?? []).reduce((x, o) => x + Number(o.kg ?? 0), 0), 0);
  const canW = ["worker", "team_lead", "tech_head", "director", "owner"].includes(sess.role);
  return <div className="space-y-3">
    <div className="grid grid-cols-2 sm:grid-cols-4 lg:grid-cols-7 gap-2">{LINES.map(([l, n]) => { const r = last30(l); return <div key={l} className="kpi !p-2"><div className="l">{n} · 30 ngày</div><div className="text-lg font-black">{fmt.n(sumOut(r) || sumIn(r))} <span className="text-xs font-normal">{sumOut(r) ? "ra" : "vào"} kg</span></div><div className="text-[10px] text-slate-500">{r.length} mẻ · vào {fmt.n(sumIn(r))} kg</div></div>; })}</div>
    <Tabs items={[["tong", "Tổng quan · vòng tuần hoàn"], ...LINES.map(([l, n]) => [l, n] as [string, string]), ["luong", `Luống trùn (${(luong.rows ?? []).length})`]]} value={tab} onChange={setTab} right={canW ? <a className="btn-primary !py-1.5 !px-3 text-sm" href="/ca">＋ Ghi mẻ (Ca của tôi › Mẻ khu D)</a> : undefined} />
    {tab === "tong" && <div className="space-y-3"><div className="card text-sm"><b>Vòng tuần hoàn khu D</b>: phân chuồng/RAS + rác bếp/BSF → <b>trùn</b> (phân trùn K5 · trùn tươi cho gà/lươn) · <b>BSF</b> (ấu trùng đạm · compost) · <b>biogas</b> (điện, đuốc dư khí) · <b>compost/biochar/giấm gỗ</b> (ruộng) · <b>IMO/EM</b> (men) · <b>anolyte</b> (khử trùng chuồng/trứng). Đầu ra ghi vào kho (K5 phân trùn, TH-ANOLYTE, NL-MEN-VS) qua mẻ; phát thải xem <a className="underline" href="/co2e">CO2e</a>; SOP-SH-01…06.</div>
      <div className="grid md:grid-cols-2 gap-3"><div className="card"><AnyChart title="Số mẻ khu D theo dây chuyền (tuần)" table="batch_logs" col="id" agg="count" dim="line" bucket="week" filters={{ location_id: `${sess.farmId}-KHU-D` }} height={240} /></div><div className="card"><AnyChart title="Nhiệt độ luống/mẻ (°C) theo dây chuyền" table="batch_logs" col="temp_c" agg="avg" dim="line" bucket="week" height={240} /></div><div className="card"><AnyChart title="Phân trùn nhập kho K5 (bao)" table="inventory_moves" col="qty" dim="reason" bucket="month" filters={{ sku: "SKU-PTR-25", direction: "1" }} height={240} /></div><div className="card"><AnyChart title="Anolyte sản xuất (lít)" table="batch_logs" col="id" agg="count" bucket="week" filters={{ line: "ANOLYTE" }} height={240} /></div></div></div>}
    {LINES.some(([l]) => l === tab) && <div className="card p-0 overflow-auto"><div className="px-3 py-2 bg-slate-100 rounded-t-xl font-bold">{LINES.find(([l]) => l === tab)?.[1]} — {LINES.find(([l]) => l === tab)?.[2]}</div><table className="tbl text-sm"><thead><tr><th className="pl-3">Lúc</th><th>Mã mẻ</th><th>Vị trí</th><th>Đầu vào</th><th>Đầu ra</th><th className="text-right">°C</th><th className="text-right">Ẩm %</th><th>QC/CCP</th><th>Người</th></tr></thead><tbody>{B.filter((b) => b.line === tab).slice(0, 120).map((b) => <tr key={String(b.id)}><td className="pl-3 text-xs">{fmt.dt(String(b.ts))}</td><td className="font-mono text-xs">{String(b.batch_code)}</td><td className="text-xs">{String(b.location_id ?? "")}</td><td className="text-xs">{((b.inputs as R[]) ?? []).map((i) => `${i.sku} ${fmt.n(Number(i.kg))}`).join(", ")}</td><td className="text-xs">{((b.outputs as R[]) ?? []).map((o) => `${o.sku} ${fmt.n(Number(o.kg))}`).join(", ")}</td><td className="text-right">{String(b.temp_c ?? "")}</td><td className="text-right">{String(b.moisture_pct ?? "")}</td><td className="text-xs">{JSON.stringify(b.qc ?? {}).slice(0, 50)}</td><td className="text-xs">{String(b.created_by ?? "")}</td></tr>)}</tbody></table>{!B.filter((b) => b.line === tab).length && <div className="p-3 text-sm text-slate-500">Chưa có mẻ.</div>}</div>}
    {tab === "luong" && <div className="card p-0 overflow-auto"><div className="px-3 py-2 bg-slate-100 rounded-t-xl font-bold">Luống trùn / ô khu D — lần nạp, lần thu gần nhất, nhiệt độ</div><table className="tbl text-sm"><thead><tr><th className="pl-3">Luống</th><th>Nạp gần nhất</th><th>Thu gần nhất</th><th className="text-right">°C gần nhất</th><th className="text-right">Mẻ 30 ngày</th></tr></thead><tbody>{(luong.rows ?? []).map((l) => <tr key={String(l.id)}><td className="pl-3">{String(l.name)}</td><td className="text-xs">{l.last_nap ? fmt.dt(String(l.last_nap)) : "—"}</td><td className="text-xs">{l.last_thu ? fmt.dt(String(l.last_thu)) : "—"}</td><td className={`text-right ${Number(l.temp_c) > 35 ? "text-red-700 font-bold" : ""}`}>{String(l.temp_c ?? "")}</td><td className="text-right">{String(l.n30)}</td></tr>)}</tbody></table></div>}
  </div>;
}
