"use client";
import { useState } from "react";
import { useData, act, fmt } from "@/lib/client";
import type { Sess } from "@/components/Shell";
import { useConfirm } from "@/components/ui/ConfirmDialog";
import { DataBoundary } from "@/components/ui/DataBoundary";
type R = Record<string, unknown>;
const adm = (t: string, row: R) => fetch(`/api/admin/${t}`, { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ row }) }).then((r) => r.json());
/** BAN KẾ HOẠCH — chuỗi cung–cầu: đàn (thật/kịch bản) → khẩu phần/ngày → nguyên liệu/kỳ → so tồn kho + PO + thu hoạch dự kiến → ha cần trồng vs đang trồng → thiếu → BAN HÀNH xuống phòng ban */
export default function SupplyPlan({ sess }: { sess: Sess }) {
  const scs = useData("plan_scenarios"); const classes = useData("animal_classes"); const herd = useData("herd_by_class"); const norms = useData("feed_norms"); const map = useData("sku_crop_map"); const ptasks = useData("plan_tasks");
  const [sel, setSel] = useState<string>(""); const [edit, setEdit] = useState<R | null>(null); const [msg, setMsg] = useState("");
  const fd = useData("plan_feed_demand", { scenario: sel }, [sel]); const sp = useData("plan_supply", { scenario: sel }, [sel]);
  const canW = ["owner", "director", "tech_head"].includes(sess.role);
  const { confirm, confirmElement } = useConfirm();
  const cur = (scs.rows ?? []).find((s) => s.id === sel);
  const H = (edit?.herd as R[] | null) ?? [];
  const save = async () => { if (!edit) return; const j = await adm("plan_scenarios", { ...edit, herd: H.filter((h) => Number(h.head) > 0), horizon_days: Number(edit.horizon_days ?? 180), safety_pct: Number(edit.safety_pct ?? 10), status: "NHAP" }); setMsg(j.ok ? `Đã lưu kịch bản ${j.row?.id ?? ""} — bảng dưới đã tính lại` : `${j.error}: ${j.detail ?? ""}`); if (j.ok) { setSel(String(j.row?.id ?? edit.id ?? "")); setEdit(null); scs.reload(); fd.reload(); sp.reload(); } };
  const publish = async () => { if (!sel) return; if (!(await confirm({ title: "Ban hành kế hoạch → tạo việc cho Trồng trọt (trồng thêm ha), Mua hàng (PO bù), D5 (kg/ngày) và thông báo phòng ban?", danger: true }))) return; const j = await act("publish_plan", { id: sel }); setMsg(j.ok ? `Đã ban hành: ${j.n} việc gửi các bộ phận (xem Việc/Thông báo)` : String(j.error)); scs.reload(); ptasks.reload(); };
  const totFeedDay = (fd.rows ?? []).reduce((a, r) => a + Number(r.kg_per_day), 0); const totShort = (sp.rows ?? []).filter((r) => Number(r.shortage_kg) > 0);
  return <div className="space-y-3">{confirmElement}
    <div className="card"><div className="flex flex-wrap items-center gap-2"><b>Kịch bản đàn</b><select className="input !w-auto min-w-[260px]" value={sel} onChange={(e) => setSel(e.target.value)}><option value="">— Đàn THẬT hiện tại (animals + nhóm) · 180 ngày —</option>{(scs.rows ?? []).map((s) => <option key={String(s.id)} value={String(s.id)}>{String(s.name)} · {String(s.horizon_days)} ngày {s.status === "BAN_HANH" ? "· ĐÃ BAN HÀNH" : ""}</option>)}</select>
      {canW && <button className="btn-secondary !py-1.5 !px-3 text-sm" onClick={() => setEdit({ name: "Kịch bản mới", horizon_days: 180, safety_pct: 10, herd: (herd.rows ?? []).map((h) => ({ class_code: h.class_code, head: Number(h.head) })) })}>＋ Kịch bản (từ đàn thật)</button>}
      {canW && cur && <button className="btn-secondary !py-1.5 !px-3 text-sm" onClick={() => setEdit({ ...cur })}>✎ sửa</button>}
      {canW && cur && cur.status !== "BAN_HANH" && <button className="btn-primary !py-1.5 !px-3 text-sm" onClick={publish}>📣 Ban hành → phòng ban</button>}
      {cur?.status === "BAN_HANH" && <span className="text-sm text-brand">Đã ban hành {fmt.dt(String(cur.published_at))}</span>}
      <span className="ml-auto text-xs text-muted">Định mức ăn: <a className="underline" href="/quan-tri?t=norms">norms TA_KG_*</a> · SKU↔cây: <a className="underline" href="/quan-tri?t=sku_crop_map">sku_crop_map</a> · năng suất: <a className="underline" href="/doi-tuong">crops</a></span></div>
      {msg && <div className="mt-2 text-sm text-brand">{msg}</div>}
      {edit && <div className="mt-3 rounded-xl border border-emerald-300 bg-brand-soft/40 p-3"><div className="grid sm:grid-cols-4 gap-2"><input className="input sm:col-span-2" placeholder="Tên kịch bản" aria-label="Tên kịch bản" value={String(edit.name ?? "")} onChange={(e) => setEdit({ ...edit, name: e.target.value })} /><label className="text-sm">Kỳ (ngày)<input className="input" type="number" value={String(edit.horizon_days ?? 180)} onChange={(e) => setEdit({ ...edit, horizon_days: e.target.value })} /></label><label className="text-sm">Dự phòng %<input className="input" type="number" value={String(edit.safety_pct ?? 10)} onChange={(e) => setEdit({ ...edit, safety_pct: e.target.value })} /></label></div>
        <table className="tbl text-sm mt-2"><thead><tr><th className="pl-2">Hạng vật nuôi</th><th className="text-right">Đầu con</th><th className="text-right">Định mức kg/con/ngày</th><th></th></tr></thead><tbody>{H.map((h, i) => { const c = (classes.rows ?? []).find((x) => x.code === h.class_code); const n = (norms.rows ?? []).find((x) => x.class_code === h.class_code); return <tr key={i}><td className="pl-2">{String(c?.name ?? h.class_code)} <span className="text-xs text-muted">{String(h.class_code)}</span></td><td><input className="input !w-28 !py-1 text-right" type="number" value={String(h.head)} onChange={(e) => setEdit({ ...edit, herd: H.map((x, j) => j === i ? { ...x, head: Number(e.target.value) } : x) })} /></td><td className="text-right">{String(n?.value ?? "—")}</td><td><button className="text-danger-tok" onClick={() => setEdit({ ...edit, herd: H.filter((_, j) => j !== i) })}>✕</button></td></tr>; })}</tbody></table>
        <div className="flex gap-2 mt-2 flex-wrap"><select className="input !w-72" onChange={(e) => { if (e.target.value) setEdit({ ...edit, herd: [...H, { class_code: e.target.value, head: 0 }] }); e.target.value = ""; }}><option value="">＋ thêm hạng vật nuôi</option>{(classes.rows ?? []).filter((c) => !H.some((h) => h.class_code === c.code)).map((c) => <option key={String(c.code)} value={String(c.code)}>{String(c.name)}</option>)}</select><button className="btn-primary !py-2" onClick={save}>Lưu & tính</button><button className="btn-secondary !py-2" onClick={() => setEdit(null)}>Hủy</button></div></div>}</div>
    <div className="grid grid-cols-2 sm:grid-cols-4 gap-2"><div className="kpi"><div className="l">Tổng đầu con</div><div className="v">{fmt.n((fd.rows ?? []).reduce((a, r) => a + Number(r.head), 0))}</div></div><div className="kpi"><div className="l">Thức ăn / ngày</div><div className="v">{fmt.n(totFeedDay)} kg</div></div><div className="kpi"><div className="l">Thức ăn / kỳ ({String(cur?.horizon_days ?? 180)} ngày, +DP)</div><div className="v">{fmt.n((fd.rows ?? []).reduce((a, r) => a + Number(r.kg_period), 0) / 1000)} tấn</div></div><div className="kpi"><div className="l">Nguyên liệu thiếu</div><div className={`v ${totShort.length ? "text-danger-tok" : "text-brand"}`}>{totShort.length} loại</div></div></div>
    <div className="grid lg:grid-cols-5 gap-3">
      <div className="card p-0 overflow-auto lg:col-span-2"><div className="px-3 py-2 bg-surface-2 rounded-t-xl font-bold">① Đàn → thức ăn (định mức × đầu con)</div><table className="tbl text-sm"><thead><tr><th className="pl-3">Hạng</th><th className="text-right">Con</th><th className="text-right">kg/con/ng</th><th className="text-right">kg/ngày</th><th className="text-right">kg/kỳ</th><th>Công thức</th></tr></thead><tbody>{(fd.rows ?? []).map((r) => <tr key={String(r.class_code)}><td className="pl-3">{String(r.class_name ?? r.class_code)}</td><td className="text-right">{fmt.n(Number(r.head))}</td><td className="text-right">{String(r.kg_per_head_day)}</td><td className="text-right font-bold">{fmt.n(Number(r.kg_per_day))}</td><td className="text-right">{fmt.n(Number(r.kg_period))}</td><td className="text-xs">{String(r.recipe_id ?? "chưa map")}</td></tr>)}<tr className="font-bold bg-surface-2"><td className="pl-3">Tổng</td><td className="text-right">{fmt.n((fd.rows ?? []).reduce((a, r) => a + Number(r.head), 0))}</td><td></td><td className="text-right">{fmt.n(totFeedDay)}</td><td className="text-right">{fmt.n((fd.rows ?? []).reduce((a, r) => a + Number(r.kg_period), 0))}</td><td></td></tr></tbody></table>{(fd.rows ?? []).some((r) => !r.recipe_id) && <div className="p-2 text-xs text-warning-tok">Hạng chưa có công thức mặc định → không tính được nguyên liệu: gán ở <a className="underline" href="/quan-tri?t=class_recipes">class_recipes</a>.</div>}</div>
      <div className="card p-0 overflow-auto lg:col-span-3"><div className="px-3 py-2 bg-surface-2 rounded-t-xl font-bold">② Thức ăn → nguyên liệu → so TỒN KHO + PO đang về + THU HOẠCH dự kiến → ③ đất cần trồng vs đang trồng → THIẾU & việc cần làm</div><DataBoundary loading={sp.loading} error={sp.error} empty={!sp.rows?.length} onRetry={sp.reload} emptyText="Chưa có dữ liệu — hạng vật nuôi cần map công thức (class_recipes) và công thức có thành phần."><table className="tbl text-sm"><thead><tr><th className="pl-3">Nguyên liệu</th><th>Nguồn</th><th className="text-right">Cần/kỳ</th><th className="text-right">kg/ngày</th><th className="text-right">Tồn</th><th className="text-right">PO về</th><th className="text-right">Thu hoạch DK</th><th className="text-right">THIẾU</th><th className="text-right">ha cần</th><th className="text-right">ha đang</th><th className="text-right">ha thêm</th><th>Bộ phận</th><th>Việc</th></tr></thead><tbody>{(sp.rows ?? []).map((r) => <tr key={String(r.sku)} className={Number(r.shortage_kg) > 0 ? "bg-danger-soft-tok" : "bg-brand-soft/40"}><td className="pl-3">{String(r.sku_name)}<div className="text-xs text-muted">{String(r.crop_name ?? "")}</div></td><td className="text-xs">{String(r.source)}</td><td className="text-right font-bold">{fmt.n(Number(r.demand_kg))}</td><td className="text-right">{fmt.n(Number(r.per_day_kg))}</td><td className="text-right">{fmt.n(Number(r.stock_kg))}</td><td className="text-right">{fmt.n(Number(r.po_kg))}</td><td className="text-right">{fmt.n(Number(r.harvest_expected_kg))}</td><td className={`text-right font-bold ${Number(r.shortage_kg) > 0 ? "text-danger-tok" : "text-brand"}`}>{fmt.n(Number(r.shortage_kg))}</td><td className="text-right">{r.ha_needed != null ? String(r.ha_needed) : ""}</td><td className="text-right">{r.ha_current != null ? String(r.ha_current) : ""}</td><td className={`text-right font-bold ${Number(r.ha_gap) > 0 ? "text-danger-tok" : ""}`}>{r.ha_gap != null ? String(r.ha_gap) : ""}</td><td className="text-xs">{String(r.dept)}</td><td className="text-xs max-w-[260px]">{String(r.action)}</td></tr>)}</tbody></table></DataBoundary><div className="p-2 text-xs text-muted">ha cần = kg × hao hụt ủ ÷ (năng suất/ha × số lứa × kỳ/365) — năng suất/lứa lấy từ danh mục cây (crops), hao hụt/lead time từ sku_crop_map. Thu hoạch DK = mùa vụ đang trồng (target − đã thu). "Ban hành" tạo việc: Trồng trọt (trồng thêm ha), Mua hàng (PO bù), D5 (kg/ngày) + thông báo phòng ban + sự kiện plan.published.</div></div></div>
    <div className="grid lg:grid-cols-2 gap-3"><div className="card p-0 overflow-auto"><div className="px-3 py-2 bg-surface-2 rounded-t-xl font-bold">Việc đã ban hành từ kế hoạch (đang mở)</div><DataBoundary loading={ptasks.loading} error={ptasks.error} empty={!ptasks.rows?.length} onRetry={ptasks.reload} emptyText="Chưa ban hành kế hoạch nào."><table className="tbl text-sm"><thead><tr><th className="pl-3">Loại</th><th>Việc</th><th>Vai</th><th>Hạn</th></tr></thead><tbody>{(ptasks.rows ?? []).map((t) => <tr key={String(t.id)}><td className="pl-3 text-xs">{String(t.kind)}</td><td>{String(t.title)}<div className="text-xs text-muted">{String(t.detail ?? "")}</div></td><td className="text-xs">{String(t.role_hint ?? "")}</td><td className="text-xs">{fmt.dt(String(t.due_at))}</td></tr>)}</tbody></table></DataBoundary></div>
      <div className="card p-0 overflow-auto"><div className="px-3 py-2 bg-surface-2 rounded-t-xl font-bold">Tham số (dữ liệu, sửa được): SKU ↔ cây · năng suất · hao hụt · lead time</div><table className="tbl text-sm"><thead><tr><th className="pl-3">SKU</th><th>Nguồn</th><th>Cây</th><th className="text-right">kg tươi/kg SKU</th><th className="text-right">Năng suất kg/ha/lứa</th><th className="text-right">Lứa/năm</th><th className="text-right">Lead ngày</th></tr></thead><tbody>{(map.rows ?? []).map((m) => <tr key={String(m.sku)}><td className="pl-3">{String(m.sku_name)}</td><td className="text-xs">{String(m.source)}</td><td>{String(m.crop_name ?? "—")}</td><td className="text-right">{String(m.fresh_per_sku)}</td><td className="text-right">{m.yield_norm_kg_ha ? fmt.n(Number(m.yield_norm_kg_ha)) : ""}</td><td className="text-right">{String(m.cuts_per_year ?? "")}</td><td className="text-right">{String(m.lead_days)}</td></tr>)}</tbody></table></div></div>
  </div>;
}
