"use client";
import Tabs from "@/components/Tabs";
import { useMemo, useState } from "react";
import { useData } from "@/lib/client";
import type { Sess } from "@/components/Shell";
import ProcessDesigner from "@/components/panels/ProcessDesigner";
import { ProcessFlow, DeptGraph } from "@/components/ProcessFlow";
import { SopSignoffPanel } from "@/components/panels/CloseoutBits";
type R = Record<string, unknown>;
const BLOCK: Record<string, [string, string]> = { DIEU_HANH: ["Điều hành", "bg-stone-800 text-white"], SAN_XUAT: ["Sản xuất", "bg-brand-tok text-white"], CHUOI_CUNG_UNG: ["Chuỗi cung ứng", "bg-amber-600 text-white"], KINH_DOANH: ["Kinh doanh", "bg-blue-700 text-white"], HO_TRO: ["Hỗ trợ", "bg-stone-500 text-white"], CHIEN_LUOC: ["Chiến lược", "bg-purple-700 text-white"] };
const arr = (v: unknown): string[] => (Array.isArray(v) ? (v as string[]) : []);

/** TỔ CHỨC: sơ đồ phòng ban → chức năng nhiệm vụ → quy trình A–Z từng phòng → đầu vào/đầu ra giữa phòng ban → event bus → hồ sơ */
export default function ToChuc({ sess, initialTab, initialProcess }: { sess: Sess; initialTab?: string; initialProcess?: string }) {
  const depts = useData("departments"); const procs = useData("processes"); const steps = useData("process_steps"); const io = useData("dept_io"); const topics = useData("event_topics"); const recs = useData("records_catalog"); const staff = useData("staff_all");
  const [tab, setTab] = useState<"sodo" | "quytrinh" | "thietke" | "chay" | "io" | "bus" | "hoso" | "phu" | "sop" | "kysop">((initialTab as "sodo") ?? "sodo"); const [sel, setSel] = useState<string | null>(null); const [selP, setSelP] = useState<string | null>(initialProcess ?? null); const cov = useData("process_coverage"); const lib = useData("sop_library"); const [libQ, setLibQ] = useState("");
  const me = useData("me"); const myDept = String(me.rows?.[0]?.dept ?? ""); const limited = ["worker", "team_lead"].includes(sess.role);
  const D = depts.rows ?? []; const P = (procs.rows ?? []).filter((x) => !limited || !myDept || ((x.visible_depts as string[]) ?? []).includes(myDept) || x.dept_code === myDept); const S = steps.rows ?? []; const IO = io.rows ?? []; const T = topics.rows ?? []; const RC = recs.rows ?? [];
  const canW = ["owner", "director", "it_engineer"].includes(sess.role);
  const byBlock = useMemo(() => { const m = new Map<string, R[]>(); for (const d of D) m.set(String(d.block), [...(m.get(String(d.block)) ?? []), d]); return m; }, [D]);
  const d = D.find((x) => x.code === sel); const dp = P.filter((p) => p.dept_code === sel); const dStaff = (staff.rows ?? []).filter((s) => s.dept === sel);
  const p = P.find((x) => x.code === selP); const ps = S.filter((s) => s.process_code === selP);
  const matrix = useMemo(() => { const m = new Map<string, R[]>(); for (const r of IO) { const k = `${r.from_dept}→${r.to_dept}`; m.set(k, [...(m.get(k) ?? []), r]); } return m; }, [IO]);
  const codes = D.map((x) => String(x.code));
  return (
    <div className="space-y-3">
      <Tabs items={[["sodo", `Tổ chức · Phòng ban (${D.length})`], ["io", "Tổ chức · Đầu vào ↔ đầu ra"], ["bus", `Tổ chức · Event bus (${T.length})`], ["quytrinh", `Quy trình · A–Z (${P.length})`], ["sop", `Quy trình · Thư viện SOP (${(lib.rows ?? []).length})`], ["kysop", "Quy trình · ✍ Ký SOP & video"], ["thietke", "Quy trình · 🛠 Khai báo"], ["chay", "Quy trình · ▶ Đang chạy"], ["phu", "Quy trình · Độ phủ theo đối tượng"], ["hoso", `Hồ sơ · Danh mục (${RC.length})`]]} value={tab} onChange={(k) => setTab(k as typeof tab)} right={<>{canW && <a className="ml-auto underline text-sm self-center whitespace-nowrap" href="/quan-tri?t=departments">✎ sửa trong Quản trị DL</a>}</>} />
      {tab === "sodo" && <div className="space-y-3">
        <div className="card"><div className="font-bold mb-1">Sơ đồ liên kết phòng ban — mũi tên = luồng dữ liệu (đầu ra quy trình → phòng nhận), độ dày = số luồng; bấm phòng để lọc, rê chuột lên đường để xem gì · qua bảng nào</div><DeptGraph depts={D} io={IO} processes={P} focus={sel} onFocus={setSel} /></div>
        <div className="text-sm text-muted">Bấm phòng ban để xem chức năng nhiệm vụ · KPI · hồ sơ · quy trình · nhân sự · màn hình.</div>
        {[...byBlock.entries()].map(([b, list]) => <div key={b}><div className={`inline-block px-3 py-1 rounded-t-xl text-sm font-bold ${BLOCK[b]?.[1] ?? "bg-stone-300"}`}>{BLOCK[b]?.[0] ?? b}</div>
          <div className="grid sm:grid-cols-2 lg:grid-cols-4 gap-2 border rounded-b-2xl rounded-tr-2xl p-2 bg-surface">{list.map((x) => <button key={String(x.code)} className={`text-left rounded-xl border p-2 hover:bg-green-50 ${sel === x.code ? "ring-2 ring-green-600" : ""}`} onClick={() => setSel(String(x.code))}><div className="font-bold">{String(x.short ?? x.name)} <span className="text-xs font-normal text-muted">{String(x.code)}{x.per_farm ? " · mỗi trại" : " · công ty"}</span></div><div className="text-xs text-muted line-clamp-2">{String(x.mission)}</div><div className="text-xs mt-1">{arr(x.functions).length} chức năng · {P.filter((q) => q.dept_code === x.code).length} quy trình · {(staff.rows ?? []).filter((s) => s.dept === x.code).length} người</div></button>)}</div></div>)}
        {d && <div className="card"><div className="flex items-start gap-2 flex-wrap"><div><div className="text-xl font-black">{String(d.name)}</div><div className="text-sm text-muted">Trực thuộc: {String(D.find((x) => x.code === d.parent_code)?.short ?? "—")} · Trưởng: <b>{String(d.head_role)}</b> · Vai tham gia: {arr(d.roles).join(", ")} · Module: {arr(d.modules).join(", ")}</div><div className="mt-1 italic">{String(d.mission)}</div></div><button className="ml-auto p-2 min-h-[44px]" onClick={() => setSel(null)}>✕</button></div>
          <div className="grid md:grid-cols-3 gap-3 mt-3 text-sm">
            <div><b>Chức năng – nhiệm vụ</b><ol className="list-decimal pl-5">{arr(d.functions).map((f) => <li key={f}>{f}</li>)}</ol></div>
            <div><b>KPI phòng</b><ul className="list-disc pl-5">{arr(d.kpis).map((f) => <li key={f}>{f}</li>)}</ul><b className="block mt-2">Hồ sơ phụ trách</b><ul className="list-disc pl-5">{arr(d.records).map((f) => <li key={f}><a className="underline py-1 -my-1" href="#" onClick={(e) => { e.preventDefault(); setTab("hoso"); }}>{f}</a> {String(RC.find((r) => r.code === f)?.name ?? "")}</li>)}</ul></div>
            <div><b>Màn hình / dashboard</b><ul className="list-disc pl-5">{arr(d.dashboards).map((f) => <li key={f}><a className="underline py-1 -my-1" href={f}>{f}</a></li>)}</ul><b className="block mt-2">Nhân sự ({dStaff.length})</b><div className="text-xs">{dStaff.map((s) => <span key={String(s.id)} className="inline-block mr-2">{String(s.full_name)} <span className="text-muted">({String(s.position ?? s.role)}, {String(s.farm_id ?? "HQ")})</span></span>)}{!dStaff.length && <span className="text-muted">chưa gán — sửa cột dept trong Nhân sự</span>}</div></div>
          </div>
          <div className="mt-3"><b className="text-sm">Quy trình của phòng ({dp.length})</b><div className="grid md:grid-cols-2 gap-2 mt-1">{dp.map((q) => <button key={String(q.code)} className="text-left border rounded-xl p-2 hover:bg-green-50 text-sm" onClick={() => { setSelP(String(q.code)); setTab("quytrinh"); }}><span className="font-mono text-xs">{String(q.code)}</span> <b>{String(q.name)}</b><div className="text-xs text-muted">Kích hoạt: {String(q.trigger_text ?? "")} · SLA: {String(q.sla ?? "")} · KPI: {String(q.kpi ?? "")}</div></button>)}</div></div>
          <div className="mt-3 grid md:grid-cols-2 gap-3 text-sm"><div><b>Nhận từ phòng khác (đầu vào)</b><ul className="list-disc pl-5">{IO.filter((r) => r.to_dept === sel && r.dir === "IN").map((r, i) => <li key={i}><b>{String(r.from_dept)}</b>: {String(r.what)} <span className="text-muted">via {String(r.via)}</span></li>)}</ul></div><div><b>Cung cấp cho phòng khác (đầu ra)</b><ul className="list-disc pl-5">{IO.filter((r) => r.from_dept === sel && r.dir === "OUT").map((r, i) => <li key={i}>→ <b>{String(r.to_dept)}</b>: {String(r.what)} <span className="text-muted">via {String(r.via)}</span></li>)}</ul></div></div>
        </div>}
      </div>}
      {tab === "quytrinh" && <div className="grid md:grid-cols-3 gap-3">
        <div className="card p-0 overflow-auto max-h-[75vh]"><div className="px-3 py-2 bg-surface-2 rounded-t-2xl font-bold">Danh mục quy trình</div>{D.map((x) => { const list = P.filter((q) => q.dept_code === x.code); return list.length ? <div key={String(x.code)}><div className="px-3 py-1 text-xs font-bold text-muted bg-surface-2">{String(x.short ?? x.name)}</div>{list.map((q) => <button key={String(q.code)} className={`block w-full text-left px-3 py-1.5 text-sm min-h-[40px] border-b hover:bg-green-50 ${selP === q.code ? "bg-brand-soft" : ""}`} onClick={() => setSelP(String(q.code))}><span className="font-mono text-xs">{String(q.code)}</span> {String(q.name)}</button>)}</div> : null; })}</div>
        <div className="md:col-span-2 card">{p ? <div className="space-y-2 text-sm"><div className="text-lg font-black flex items-center gap-2 flex-wrap">{String(p.name)} <span className="text-xs font-mono font-normal">{String(p.code)} · {String(p.kind)} · {String(p.status ?? "")} v{String(p.version ?? 1)}</span>{p.ui_path ? <a className="text-sm underline font-normal py-2 -my-2" href={String(p.ui_path)}>mở màn hình</a> : null}{canW && <button className="btn-secondary !py-1 !px-3 !text-sm font-normal" onClick={() => setTab("thietke")}>✎ Sửa bước / chạy</button>}</div>
          <ProcessFlow process={p} steps={ps} depts={D} />
          <div className="grid sm:grid-cols-3 gap-2"><div className="kpi !p-2"><div className="l">Kích hoạt</div><div className="text-sm font-semibold">{String(p.trigger_text ?? "")}</div></div><div className="kpi !p-2"><div className="l">SLA</div><div className="text-sm font-semibold">{String(p.sla ?? "")}</div></div><div className="kpi !p-2"><div className="l">KPI · chủ trì</div><div className="text-sm font-semibold">{String(p.kpi ?? "")} · {String(p.owner_role ?? "")}</div></div></div>
          <div className="grid sm:grid-cols-2 gap-2"><div className="bg-warning-soft-tok rounded-xl p-2"><b>ĐẦU VÀO</b><ul className="list-disc pl-5">{(p.inputs as R[] ?? []).map((i, k) => <li key={k}><b>{String(i.from)}</b>: {String(i.what)} <span className="text-muted">via {String(i.via)}</span></li>)}</ul></div><div className="bg-brand-soft rounded-xl p-2"><b>ĐẦU RA</b><ul className="list-disc pl-5">{(p.outputs as R[] ?? []).map((o, k) => <li key={k}>→ <b>{String(o.to)}</b>: {String(o.what)} <span className="text-muted">via {String(o.via)}</span></li>)}</ul></div></div>
          <div><b>Bước A → Z</b>{ps.length ? <ol className="mt-1 space-y-1">{ps.map((s) => <li key={String(s.id)} className="border rounded-xl p-2 flex gap-2"><span className="w-7 h-7 rounded-full bg-brand-tok text-white flex items-center justify-center font-bold shrink-0">{String(s.step_no)}</span><div><b>{String(s.name)}</b> <span className="text-xs text-muted">{String(s.actor_role)} · {String(s.dept_code)}</span><div>{String(s.action)}</div><div className="text-xs text-muted">Ở đâu: <span className="font-mono">{String(s.system_where ?? "")}</span> · Kiểm soát: {String(s.control ?? "—")} · Kết quả: <span className="font-mono">{String(s.output ?? "")}</span></div></div></li>)}</ol> : <div className="text-muted">Chưa mô tả bước chi tiết — thêm ở <a className="underline" href="/quan-tri?t=process_steps">Quản trị DL › process_steps</a>. Bảng liên quan: {arr(p.tables).join(", ")}</div>}</div>
          <div><b>Tài liệu · biểu mẫu · file · công cụ · phần mềm cần dùng</b><ul className="list-disc pl-5 mt-1">{(((p.documents as R[]) ?? [])).map((d, k) => <li key={k}><span className="b-gray !text-xs">{String(d.kind)}</span> {String(d.name)} {d.ref ? <span className="text-muted font-mono text-xs">[{String(d.ref)}]</span> : null}{d.required === false ? <span className="text-xs text-muted"> (tùy chọn)</span> : null}</li>)}{!((p.documents as R[]) ?? []).length && <li className="text-muted">chưa khai báo — thêm ở Khai báo quy trình</li>}</ul></div>
          <div className="text-xs text-muted">Dữ liệu chạy thẳng: bảng <span className="font-mono">{arr(p.tables).join(", ")}</span>{arr(p.topics).length ? <> · chủ đề bus <span className="font-mono">{arr(p.topics).join(", ")}</span></> : null}{arr(p.forms).length ? <> · form 3 chạm: {arr(p.forms).join(", ")}</> : null}</div>
        </div> : <div className="text-muted">Chọn quy trình bên trái.</div>}</div>
      </div>}
      {tab === "thietke" && <ProcessDesigner sess={sess} initialCode={selP ?? undefined} />}
      {tab === "chay" && <ProcessDesigner sess={sess} tab="chay" />}
      {tab === "phu" && <div className="card p-0 overflow-auto"><div className="px-3 py-2 bg-surface-2 rounded-t-2xl font-bold">Kiểm kê quy trình theo ĐỐI TƯỢNG × mức phủ (DA_CO = có bảng + màn hình + form · MOT_PHAN = có bảng, dùng qua Quản trị DL · CHUA = chưa)</div><table className="tbl text-sm"><thead><tr><th className="pl-3">Đối tượng</th><th className="text-right">Đã có</th><th className="text-right">Một phần</th><th className="text-right">Chưa</th><th>Quy trình</th></tr></thead><tbody>{[...new Set(P.map((q) => String(q.object_type ?? "")))].map((o) => { const c = (cov.rows ?? []).filter((x) => x.object_type === o); const n = (k: string) => Number(c.find((x) => x.coverage === k)?.n ?? 0); return <tr key={o}><td className="pl-3 font-bold">{o}</td><td className="text-right text-brand font-bold">{n("DA_CO")}</td><td className="text-right text-warning-tok">{n("MOT_PHAN")}</td><td className="text-right text-danger-tok">{n("CHUA")}</td><td className="text-xs">{P.filter((q) => q.object_type === o).map((q) => <button key={String(q.code)} className={`mr-1 underline py-1 -my-1 ${q.coverage === "MOT_PHAN" ? "text-warning-tok" : ""}`} onClick={() => { setSelP(String(q.code)); setTab("quytrinh"); }}>{String(q.code)}</button>)}</td></tr>; })}</tbody></table><div className="p-3 text-xs text-muted">Tổng {P.length} quy trình · thêm quy trình mới ở tab Khai báo (không cần lập trình).</div></div>}
      {tab === "sop" && <div className="card p-0 overflow-auto"><div className="px-3 py-2 bg-surface-2 rounded-t-2xl flex items-center gap-2 flex-wrap"><b>Thư viện SOP theo bộ gốc (Quyển 3 §15): 8 chuỗi L1 · 81 quy trình L2 · 422 SOP L3</b><input className="input !w-64 !py-1 text-sm" placeholder="tìm SOP…" aria-label="tìm SOP…" value={libQ} onChange={(e) => setLibQ(e.target.value)} /><a className="ml-auto underline text-sm py-2 -my-2" href="/quan-tri?t=sops">sửa · nhập CSV · ban hành</a><a className="underline text-sm py-2 -my-2" href="/api/admin/sops?csv=1">xuất</a></div>
        {[...new Set((lib.rows ?? []).map((r) => String(r.l1_chain ?? "")))].filter(Boolean).map((l1) => <div key={l1}><div className="px-3 py-1 text-xs font-bold text-brand bg-brand-soft">{l1}</div>{[...new Set((lib.rows ?? []).filter((r) => r.l1_chain === l1).map((r) => String(r.l2_code)))].map((l2) => { const rows = (lib.rows ?? []).filter((r) => r.l2_code === l2 && (!libQ || JSON.stringify(r).toLowerCase().includes(libQ.toLowerCase()))); return rows.length ? <div key={l2} className="border-b"><div className="px-3 py-1 text-sm font-semibold flex items-center gap-2"><button className="underline py-1 -my-1" onClick={() => { setSelP(l2); setTab("quytrinh"); }}>{l2}</button> {String(rows[0].l2_name)} <span className="text-xs text-muted">· {String(rows[0].dept_code)} · {rows.length} SOP</span></div><div className="px-3 pb-1 flex flex-wrap gap-1">{rows.map((r) => <span key={String(r.code)} className={`rounded-lg border px-2 py-0.5 text-xs ${r.ccp ? "border-danger-tok bg-danger-soft-tok" : r.published_at ? "bg-brand-soft border-emerald-300" : "bg-surface"}`} title={`${r.tools ?? ""} · ${r.evidence ?? ""}${r.ccp ? ` · CCP: ${r.ccp_limit}` : ""}`}><span className="font-mono">{String(r.code)}</span> {String(r.title)}{Array.isArray(r.std_clauses) && (r.std_clauses as string[]).length ? <span className="text-muted"> [{(r.std_clauses as string[]).join(",")}]</span> : null}</span>)}</div></div> : null; })}</div>)}
        <div className="p-3 text-xs text-muted">Đỏ = SOP có CCP (giới hạn tới hạn + hành động khắc phục) · [mã] = điều khoản chuẩn SOP phục vụ (trường 11) · xanh = đã ban hành. Mỗi SOP L3 = 1 bước trong quy trình L2 (Khai báo quy trình → sửa/thêm bước; xuất bản → thông báo bộ phận).</div></div>}
      {tab === "io" && <div className="space-y-3"><div className="card"><DeptGraph depts={D} io={IO} processes={P} focus={sel} onFocus={setSel} /></div><div className="card p-0 overflow-auto"><div className="px-3 py-2 bg-surface-2 rounded-t-2xl font-bold">Ma trận liên hệ: hàng = phòng CUNG CẤP, cột = phòng NHẬN (số luồng dữ liệu; rê chuột để xem)</div>
        <table className="tbl text-xs"><thead><tr><th className="pl-2">từ ↓ / đến →</th>{codes.map((c) => <th key={c} className="text-center">{c}</th>)}</tr></thead><tbody>{codes.map((f) => <tr key={f}><td className="pl-2 font-bold">{f}</td>{codes.map((t) => { const cell = [...(matrix.get(`${f}→${t}`) ?? []), ...(f === "*" ? [] : [])]; const star = matrix.get(`*→${t}`) ?? []; const n = cell.length; return <td key={t} className={`text-center ${n ? "bg-brand-soft font-bold" : ""}`} title={[...cell, ...(f === t ? star : [])].map((r) => `${r.what} (${r.via})`).join("\n")}>{n || ""}</td>; })}</tr>)}</tbody></table>
        <div className="p-3 text-xs text-muted">Ô "*" = mọi phòng. Mỗi luồng là một bảng/view/export/chủ đề event bus cụ thể → phòng nhận thấy ngay số liệu (realtime), không phải đi hỏi; mọi bảng đều xuất/nhập CSV được ở Quản trị DL.</div></div></div>}
      {tab === "bus" && <div className="card p-0 overflow-auto"><div className="px-3 py-2 bg-surface-2 rounded-t-2xl font-bold">Chủ đề event bus (outbox <span className="font-mono">event_bus</span> + pg_notify → hộp thư người/nhóm · webhook)</div>
        <table className="tbl text-sm"><thead><tr><th className="pl-2">Chủ đề</th><th>Phát</th><th>Nhận</th><th>Mô tả</th><th>Nguồn</th><th>Đã nối</th></tr></thead><tbody>{T.map((t) => <tr key={String(t.topic)}><td className="pl-2 font-mono">{String(t.topic)}</td><td>{String(t.producer_dept)}</td><td className="text-xs">{arr(t.consumer_depts).join(", ")}</td><td>{String(t.description)}</td><td className="font-mono text-xs">{String(t.source_table ?? "")}</td><td>{t.wired ? <span className="b-grn">trigger</span> : <span className="b-yel">kế hoạch</span>}</td></tr>)}</tbody></table>
        <div className="p-3 text-xs text-muted">Luồng: bảng nghiệp vụ → trigger <span className="font-mono">publish_event()</span> → <span className="font-mono">event_bus</span> → job dispatch (mỗi phút/đêm) → <span className="font-mono">notifications</span> theo luật & sở thích từng người (app/Zalo/SMS) → webhook đối tác. Thêm chủ đề = thêm 1 dòng + 1 trigger.</div></div>}
      {tab === "kysop" && <SopSignoffPanel sess={sess} />}
      {tab === "hoso" && <div className="card p-0 overflow-auto"><div className="px-3 py-2 bg-surface-2 rounded-t-2xl font-bold">Danh mục hồ sơ bắt buộc/khuyến nghị (mỗi hồ sơ = bảng dữ liệu + bản xuất chuẩn; thêm hồ sơ mới = thêm 1 dòng)</div>
        <table className="tbl text-sm"><thead><tr><th className="pl-2">Mã</th><th>Hồ sơ</th><th>Lĩnh vực</th><th>Căn cứ pháp lý / chuẩn</th><th>Bảng dữ liệu</th><th>Xuất</th><th>Lưu (năm)</th><th>Phụ trách</th><th>Cần cho</th></tr></thead><tbody>{RC.map((r) => <tr key={String(r.code)}><td className="pl-2 font-mono text-xs">{String(r.code)}</td><td><b>{String(r.name)}</b><div className="text-xs text-muted">{String(r.description ?? "")}</div></td><td className="text-xs">{String(r.domain)}</td><td className="text-xs">{String(r.legal_basis ?? "")}</td><td className="font-mono text-xs">{arr(r.tables).join(", ")}</td><td>{r.export_kind ? <a className="underline text-xs" href={`/api/exports/${String(r.export_kind)}`}>{String(r.export_kind)}</a> : ""}</td><td className="text-center">{String(r.retention_years ?? "")}</td><td className="text-xs">{String(r.owner_role ?? "")}</td><td className="text-xs">{arr(r.required_for).join(", ")}</td></tr>)}</tbody></table></div>}
    </div>);
}
