"use client";
import { useState } from "react";
import { useData, fmt } from "@/lib/client";
import { usePrompt } from "@/components/ui/PromptDialog";
import type { Sess } from "@/components/Shell";
type R = Record<string, unknown>;
const arr = (v: unknown): string[] => (Array.isArray(v) ? (v as string[]) : []);
const adminPost = (t: string, row: R) => fetch(`/api/admin/${t}`, { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ row }) }).then((r) => r.json());
/** TUÂN THỦ & CHỨNG NHẬN: chuẩn (VietGAP/GlobalG.A.P./ISO 22000/HACCP/Halal/EU-USDA-JAS Organic/ASC/BRC/GACC/PLS) → yêu cầu → bằng chứng dữ liệu (bảng có bản ghi 90 ngày) → tự đánh giá (ĐẠT/KHÔNG/NA) → NC & khắc phục → sổ chứng nhận */
export default function TuanThu({ sess }: { sess: Sess }) {
  const { prompt, promptElement } = usePrompt();
  const comp = useData("compliance"); const stds = useData("standards"); const reqs = useData("standard_requirements"); const certs = useData("certifications"); const checks = useData("compliance_checks"); const depts = useData("departments");
  const icfs = useData("icfs_score"); const icfsSum = useData("icfs_summary"); const cov = useData("compliance_coverage"); const ctls = useData("controls"); const gaps = useData("compliance_gaps"); const cc = useData("clause_controls"); const [ev, setEv] = useState<{ id: string; rows: R[] } | null>(null);
  const [sel, setSel] = useState<string | null>(null); const [msg, setMsg] = useState(""); const [cf, setCf] = useState<R | null>(null);
  const canW = ["owner", "director", "tech_head", "auditor", "it_engineer"].includes(sess.role);
  const S = stds.rows ?? []; const s = S.find((x) => x.code === sel); const RQ = (reqs.rows ?? []).filter((r) => r.standard_code === sel);
  const lastCheck = (rid: unknown) => (checks.rows ?? []).filter((c) => c.requirement_id === rid).sort((a, b) => String(b.checked_at).localeCompare(String(a.checked_at)))[0];
  const check = async (r: R, result: string) => { const evidence = result === "KHONG_DAT" ? (await prompt({ title: "Điểm không phù hợp", label: "Mô tả điểm không phù hợp / bằng chứng", type: "text", required: false })) ?? "" : (await prompt({ title: "Bằng chứng", label: "Bằng chứng (tùy chọn)", type: "text", required: false })) ?? ""; const j = await fetch("/api/admin/compliance_checks", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ row: { standard_code: sel, requirement_id: r.id, result, evidence, checked_by: sess.staffId, nc_severity: result === "KHONG_DAT" ? r.level : null } }) }).then((x) => x.json()); setMsg(j.ok ? `Đã ghi ${result} cho ${r.clause}` : `${j.error}: ${j.detail ?? ""}`); checks.reload(); comp.reload(); };
  return (
    <div className="space-y-3">
      {promptElement}
      <div className="card border-2 border-emerald-500"><div className="flex items-center gap-3 flex-wrap"><div><div className="text-xs uppercase tracking-widest text-emerald-700 font-bold">Tiêu chuẩn của riêng ITRAN</div><b className="text-lg">ITRAN Circular Farm Standard (ICFS) v1.0</b></div>{(icfsSum.rows ?? []).map((f) => <div key={String(f.farm_id)} className="kpi !p-2"><div className="l">{String(f.farm_id)}</div><div className="text-xl font-black">{String(f.pct)}% · {String(f.level)}</div><div className="text-xs">CRITICAL lỗi: {String(f.critical_fail)}</div></div>)}<a className="ml-auto underline text-sm" href="/chuan" target="_blank">Trang công khai /chuan ↗</a><a className="underline text-sm" href="/api/public/standard" target="_blank">API</a></div>
        <div className="overflow-auto mt-2"><table className="tbl text-sm"><thead><tr><th className="pl-2">Điều</th><th>Yêu cầu</th><th>Mức</th><th>Ngưỡng</th><th className="text-right">Đo được (realtime)</th><th>KQ</th></tr></thead><tbody>{(icfs.rows ?? []).map((d) => <tr key={String(d.clause)}><td className="pl-2 font-mono">{String(d.clause)}</td><td>{String(d.title)}</td><td><span className={d.level === "CRITICAL" ? "b-red" : d.level === "MAJOR" ? "b-yel" : "b-gray"}>{String(d.level)}</span></td><td>{String(d.threshold ?? "")}</td><td className="text-right font-bold">{String(d.value ?? "—")}</td><td>{d.pass === true ? <span className="b-grn">ĐẠT</span> : d.pass === false ? <span className="b-red">CHƯA</span> : <span className="b-gray">n/a</span>}</td></tr>)}</tbody></table></div>
        <div className="text-xs text-slate-600 mt-1">Điểm tính tự động từ dữ liệu vận hành (không tự khai). Sửa điều khoản/ngưỡng/công thức đo: <a className="underline" href="/quan-tri?t=standard_requirements">Quản trị DL</a> (có lịch sử công khai).</div></div>
      <div className="card"><div className="flex items-center gap-2 flex-wrap"><b>Độ phủ theo SPEC-05: điều khoản → CONTROL (vật thật trong app)</b><span className="text-xs text-slate-500">chuẩn = cặp kính soi vào 1 bộ quy trình; điều khoản không trỏ được control = gap đỏ</span><span className="ml-auto text-sm">Gap mở: <b className={(gaps.rows ?? []).length ? "text-red-700" : "text-emerald-700"}>{(gaps.rows ?? []).length}</b></span></div>
        <div className="flex flex-wrap gap-1 mt-2">{(cov.rows ?? []).map((c) => <span key={String(c.standard_code)} className={`rounded-full px-2 py-1 text-xs border ${Number(c.pct) === 100 ? "bg-emerald-50 border-emerald-400" : Number(c.pct) >= 80 ? "bg-amber-50 border-amber-400" : "bg-red-50 border-red-400"}`} title={`ưu tiên ${c.priority} · ${c.spec_code ?? ""}`}>{String(c.standard_code)} {String(c.with_control)}/{String(c.clauses)} · MAJOR {String(c.major_with_control)}/{String(c.major)}</span>)}</div>
        <div className="mt-2 text-sm"><b>{(ctls.rows ?? []).length} control</b> — bấm để chạy bằng chứng sống:</div>
        <div className="flex flex-wrap gap-1 mt-1">{(ctls.rows ?? []).map((c) => <button key={String(c.id)} className={`rounded-lg border px-2 py-1 text-xs text-left ${ev?.id === c.id ? "bg-emerald-100 border-emerald-500" : "bg-white"}`} title={`${c.kind} · ${c.ref}`} onClick={async () => { const j = await fetch(`/api/compliance/evidence?control=${c.id}`).then((r) => r.json()); setEv({ id: String(c.id), rows: j.rows ?? [{ error: j.error, detail: j.detail }] }); }}><b>{String(c.id)}</b> <span className="text-slate-500">{String(c.kind)} · {String(c.clauses)} đk</span></button>)}</div>
        {ev && <div className="mt-2 rounded-xl bg-slate-50 p-2 text-sm"><b>{ev.id}</b> — {String((ctls.rows ?? []).find((c) => c.id === ev.id)?.description ?? "")}<div className="text-xs text-slate-500">ref: {String((ctls.rows ?? []).find((c) => c.id === ev.id)?.ref ?? "")}</div><pre className="text-xs mt-1 overflow-auto">{JSON.stringify(ev.rows, null, 1)}</pre><div className="text-xs">Điều khoản: {(cc.rows ?? []).filter((x) => x.control_id === ev.id).map((x) => `${x.standard_code}:${x.clause}`).join(" · ")}</div></div>}
        {(gaps.rows ?? []).length > 0 && <table className="tbl text-xs mt-2"><thead><tr><th className="pl-2">Chuẩn</th><th>Điều</th><th>Yêu cầu</th><th>Mức</th><th>Kế hoạch</th></tr></thead><tbody>{(gaps.rows ?? []).map((g) => <tr key={String(g.id)} className="bg-red-50"><td className="pl-2">{String(g.standard_code)}</td><td>{String(g.clause)}</td><td>{String(g.title)}</td><td>{String(g.level)}</td><td>{String(g.plan ?? "")}</td></tr>)}</tbody></table>}
        <div className="text-xs text-slate-500 mt-1">Thêm/sửa control & map: <a className="underline" href="/quan-tri?t=controls">controls</a> · <a className="underline" href="/quan-tri?t=clause_controls">clause_controls</a> · gói audit theo chuẩn: <a className="underline" href={`/api/exports/audit-std?std=${sel ?? "VIETGAP-TT"}`}>tải ZIP</a></div></div>
      <div className="text-sm text-slate-600">Số điều khoản là bản tóm tắt để lập ma trận yêu cầu → bằng chứng; đối chiếu văn bản gốc (cột Nguồn). Thêm chuẩn/yêu cầu mới không cần lập trình (<a className="underline" href="/quan-tri?t=standard_requirements">Quản trị DL</a>).</div>
      <div className="grid sm:grid-cols-2 lg:grid-cols-3 xl:grid-cols-4 gap-2">{(comp.rows ?? []).map((c) => { const pct = Number(c.requirements) ? Math.round((Number(c.with_evidence_90d) / Number(c.requirements)) * 100) : 0; return <button key={String(c.standard_code)} className={`text-left card !p-3 ${sel === c.standard_code ? "ring-2 ring-emerald-600" : ""}`} onClick={() => setSel(String(c.standard_code))}><div className="font-bold text-sm">{String(c.standard_name)}</div><div className="text-xs text-slate-500">{String(c.scope)} · {String(c.requirements)} yêu cầu</div><div className="mt-1 h-2 rounded bg-slate-100 overflow-hidden"><div className="h-2 bg-emerald-500" style={{ width: `${pct}%` }} /></div><div className="text-xs mt-1 flex gap-2"><span>bằng chứng {pct}%</span><span className="text-emerald-700">đạt {String(c.checked_ok)}</span><span className="text-red-700">NC {String(c.checked_nc)}</span>{c.cert_status ? <span className={`ml-auto ${c.cert_status === "HIEU_LUC" ? "b-grn" : "b-yel"} !text-[10px]`}>{String(c.cert_status)}{c.cert_valid_to ? ` → ${fmt.d(c.cert_valid_to)}` : ""}</span> : <span className="ml-auto text-slate-400">chưa CN</span>}</div></button>; })}</div>
      {msg && <div className="text-sm bg-emerald-50 border border-emerald-200 rounded-xl px-3 py-2">{msg}</div>}
      {s && <div className="card"><div className="flex items-center gap-2 flex-wrap"><b className="text-lg">{String(s.name)}</b><span className="b-gray">{String(s.issuer)}</span><span className="text-sm text-slate-600">{String(s.description)}</span><span className="ml-auto text-xs text-slate-500">Nguồn: {String(s.url ?? "")}</span></div>
        <div className="text-xs mt-1">Cần cho: {arr(s.required_for).join(", ") || "—"}</div>
        <div className="overflow-auto mt-2"><table className="tbl text-sm"><thead><tr><th className="pl-2">Điều</th><th>Yêu cầu</th><th>Mức</th><th>Bằng chứng (bảng dữ liệu)</th><th>Hồ sơ · Quy trình</th><th>Tần suất · Phòng</th><th>Tự đánh giá gần nhất</th><th></th></tr></thead><tbody>
          {RQ.map((r) => { const lc = lastCheck(r.id); return <tr key={String(r.id)}><td className="pl-2 font-mono text-xs">{String(r.clause)}</td><td><b>{String(r.title)}</b><div className="text-xs text-slate-600">{String(r.requirement ?? "")}</div></td><td><span className={r.level === "CRITICAL" ? "b-red" : r.level === "MAJOR" ? "b-yel" : "b-gray"}>{String(r.level)}</span></td><td className="text-xs font-mono">{arr(r.evidence_tables).map((t) => <a key={t} className="underline mr-1" href={`/so-lieu?tab=any&table=${t}`}>{t}</a>)}</td><td className="text-xs">{arr(r.evidence_records).join(", ")}<br />{arr(r.process_codes).map((pc) => <a key={pc} className="underline mr-1" href={`/to-chuc?tab=quytrinh&p=${pc}`}>{pc}</a>)}</td><td className="text-xs">{String(r.frequency ?? "")} · {String(depts.rows?.find((d) => d.code === r.owner_dept)?.short ?? r.owner_dept ?? "")}</td><td className="text-xs">{lc ? <span className={lc.result === "DAT" ? "b-grn" : lc.result === "KHONG_DAT" ? "b-red" : "b-gray"}>{String(lc.result)} · {fmt.d(lc.checked_at)}</span> : <span className="text-slate-400">chưa</span>}{lc?.evidence ? <div className="text-slate-500">{String(lc.evidence)}</div> : null}</td><td className="text-xs whitespace-nowrap">{canW && <><button className="underline text-emerald-700 mr-1" onClick={() => check(r, "DAT")}>đạt</button><button className="underline text-red-700 mr-1" onClick={() => check(r, "KHONG_DAT")}>NC</button><button className="underline text-slate-500" onClick={() => check(r, "KHONG_AP_DUNG")}>N/A</button></>}</td></tr>; })}
        </tbody></table>{!RQ.length && <div className="p-3 text-slate-500 text-sm">Chưa nhập yêu cầu chi tiết cho chuẩn này — thêm ở Quản trị DL › standard_requirements (điều khoản, yêu cầu, bảng bằng chứng, quy trình).</div>}</div>
      </div>}
      <div className="card p-0 overflow-auto"><div className="px-3 py-2 bg-slate-100 rounded-t-xl flex items-center"><b>Sổ chứng nhận ({(certs.rows ?? []).length})</b>{canW && <button className="ml-auto btn-secondary !py-1 !px-3 !text-sm" onClick={() => setCf({ standard_code: sel ?? S[0]?.code, status: "CHUAN_BI" })}>＋ Chứng nhận</button>}</div>
        {cf && <div className="p-3 grid sm:grid-cols-3 lg:grid-cols-6 gap-2 border-b bg-emerald-50"><select className="input" value={String(cf.standard_code ?? "")} onChange={(e) => setCf({ ...cf, standard_code: e.target.value })}>{S.map((x) => <option key={String(x.code)} value={String(x.code)}>{String(x.name)}</option>)}</select><input className="input" placeholder="Tổ chức chứng nhận" aria-label="Tổ chức chứng nhận" value={String(cf.body ?? "")} onChange={(e) => setCf({ ...cf, body: e.target.value })} /><input className="input" placeholder="Số chứng nhận" aria-label="Số chứng nhận" value={String(cf.cert_number ?? "")} onChange={(e) => setCf({ ...cf, cert_number: e.target.value })} /><input className="input" type="date" value={String(cf.issued_on ?? "")} onChange={(e) => setCf({ ...cf, issued_on: e.target.value })} /><input className="input" type="date" value={String(cf.valid_to ?? "")} onChange={(e) => setCf({ ...cf, valid_to: e.target.value })} /><select className="input" value={String(cf.status)} onChange={(e) => setCf({ ...cf, status: e.target.value })}>{["CHUAN_BI", "DANH_GIA", "HIEU_LUC", "TAM_DINH_CHI", "HET_HAN", "THU_HOI"].map((x) => <option key={x}>{x}</option>)}</select><input className="input lg:col-span-3" placeholder="Phạm vi (sản phẩm/ô/đàn)" aria-label="Phạm vi (sản phẩm/ô/đàn)" value={String(cf.scope ?? "")} onChange={(e) => setCf({ ...cf, scope: e.target.value })} /><input className="input" type="date" placeholder="Đánh giá kế" aria-label="Đánh giá kế" value={String(cf.next_audit ?? "")} onChange={(e) => setCf({ ...cf, next_audit: e.target.value })} /><div className="flex gap-2"><button className="btn-primary !py-2" onClick={async () => { const j = await adminPost("certifications", { ...cf, id: `${sess.farmId}-CERT-${String(cf.standard_code)}-${new Date().getFullYear()}` }); setMsg(j.ok ? "Đã lưu chứng nhận" : `${j.error}: ${j.detail ?? ""}`); setCf(null); certs.reload(); comp.reload(); }}>Lưu</button><button className="btn-secondary !py-2" onClick={() => setCf(null)}>Hủy</button></div></div>}
        <table className="tbl text-sm"><thead><tr><th className="pl-3">Chuẩn</th><th>Tổ chức</th><th>Số</th><th>Phạm vi</th><th>Cấp</th><th>Hết hạn</th><th>Đánh giá kế</th><th>TT</th></tr></thead><tbody>{(certs.rows ?? []).map((c) => <tr key={String(c.id)}><td className="pl-3 font-semibold">{String(S.find((x) => x.code === c.standard_code)?.name ?? c.standard_code)}</td><td>{String(c.body ?? "")}</td><td className="font-mono text-xs">{String(c.cert_number ?? "")}</td><td className="text-xs">{String(c.scope ?? "")}</td><td>{c.issued_on ? fmt.d(c.issued_on) : ""}</td><td className={c.valid_to && new Date(String(c.valid_to)) < new Date(Date.now() + 90 * 86400e3) ? "text-red-700 font-bold" : ""}>{c.valid_to ? fmt.d(c.valid_to) : ""}</td><td>{c.next_audit ? fmt.d(c.next_audit) : ""}</td><td><span className={c.status === "HIEU_LUC" ? "b-grn" : "b-yel"}>{String(c.status)}</span></td></tr>)}</tbody></table>{certs.rows?.length === 0 && <div className="p-3 text-slate-500 text-sm">Chưa có chứng nhận — hệ thống nhắc trước 90 ngày hết hạn (luật AL-CERT-EXPIRE).</div>}</div>
      <div className="card p-0 overflow-auto"><div className="px-3 py-2 bg-slate-100 rounded-t-xl font-bold">Điểm không phù hợp (NC) đang mở</div><table className="tbl text-sm"><thead><tr><th className="pl-3">Lúc</th><th>Chuẩn</th><th>Yêu cầu</th><th>Mức</th><th>Bằng chứng</th><th>Khắc phục</th><th>Hạn</th><th></th></tr></thead><tbody>{(checks.rows ?? []).filter((c) => c.result === "KHONG_DAT" && !c.closed_at).map((c) => { const r = (reqs.rows ?? []).find((x) => x.id === c.requirement_id); return <tr key={String(c.id)}><td className="pl-3 text-xs">{fmt.dt(c.checked_at)}</td><td className="text-xs">{String(c.standard_code)}</td><td>{String(r?.clause ?? "")} {String(r?.title ?? "")}</td><td><span className="b-red">{String(c.nc_severity ?? "")}</span></td><td className="text-xs">{String(c.evidence ?? "")}</td><td className="text-xs">{String(c.corrective_action ?? "")}</td><td className="text-xs">{c.due_date ? fmt.d(c.due_date) : ""}</td><td className="text-xs">{canW && <button className="underline" onClick={async () => { const ca = (await prompt({ title: "Đóng NC", label: "Hành động khắc phục đã thực hiện", type: "text", required: false })) ?? ""; await adminPost("compliance_checks", { id: c.id, corrective_action: ca, closed_at: new Date().toISOString() }); checks.reload(); comp.reload(); }}>đóng NC</button>}</td></tr>; })}</tbody></table></div>
    </div>);
}
