"use client";
import { use, useEffect, useState } from "react";
type R = Record<string, unknown>;
const vnd = (v: unknown) => Number(v ?? 0).toLocaleString("vi-VN") + " đ"; const d = (v: unknown) => (v ? new Date(String(v)).toLocaleDateString("vi-VN") : "");
/** PORTAL ĐỐI TÁC B2B (không cần tài khoản, theo link riêng): đặt hàng theo bảng giá · đơn của tôi · công nợ · lô đã mua + COA + truy xuất · chứng nhận & ICFS của trại */
export default function P({ params }: { params: Promise<{ token: string }> }) {
  const { token } = use(params); const [j, setJ] = useState<R | null>(null); const [cart, setCart] = useState<Record<string, number>>({}); const [dd, setDd] = useState(""); const [msg, setMsg] = useState("");
  const load = () => fetch(`/api/public/partner/${token}`).then((r) => r.json()).then(setJ);
  useEffect(() => { load(); }, [token]); // eslint-disable-line react-hooks/exhaustive-deps
  if (!j) return <main className="min-h-screen flex items-center justify-center text-slate-500">Đang tải…</main>; if (j.error) return <main className="min-h-screen flex items-center justify-center">Liên kết không hợp lệ.</main>;
  const pt = j.partner as R; const P = (j.products as R[]) ?? []; const total = P.reduce((a, p) => a + (cart[String(p.sku)] ?? 0) * Number(p.price ?? 0), 0);
  return (<main className="min-h-screen bg-slate-50"><div className="max-w-3xl mx-auto p-4 space-y-4">
    <div className="rounded-2xl bg-white p-4 shadow"><div className="text-xs uppercase tracking-widest text-emerald-700 font-bold">ITRAN FARM · cổng đối tác</div><h1 className="text-xl font-black">{String(pt.name)}</h1><div className="text-sm text-slate-600">Hạn mức {vnd(pt.credit_limit)} · {String(pt.credit_days ?? 0)} ngày · công nợ hiện tại <b className={Number(j.receivable) > 0 ? "text-red-700" : ""}>{vnd(j.receivable)}</b> · trại đạt ICFS {String((j.icfs as R)?.pct ?? "—")}% ({String((j.icfs as R)?.level ?? "")}) · <a className="underline" href="/chuan" target="_blank">tiêu chuẩn</a></div><div className="text-xs mt-1">Chứng nhận hiệu lực: {((j.certs as R[]) ?? []).map((c) => `${c.name} (${c.body ?? ""}, đến ${d(c.valid_to)})`).join(" · ") || "đang cập nhật"}</div></div>
    <div className="rounded-2xl bg-white p-4 shadow"><b>Đặt hàng</b><table className="w-full text-sm mt-2"><tbody>{P.map((p) => <tr key={String(p.sku)} className="border-t"><td className="py-1">{String(p.name)} <span className="text-xs text-slate-500">{String(p.unit ?? "")}</span></td><td className="text-right">{p.price ? vnd(p.price) : "liên hệ"}</td><td className="text-right w-28"><input type="number" min={0} className="w-24 rounded-lg border px-2 py-1 text-right" value={cart[String(p.sku)] ?? ""} onChange={(e) => setCart({ ...cart, [String(p.sku)]: Number(e.target.value) })} /></td></tr>)}</tbody></table><div className="flex gap-2 items-center mt-2 text-sm"><input type="date" className="rounded-lg border px-2 py-1" value={dd} onChange={(e) => setDd(e.target.value)} /><span className="ml-auto font-bold">Tạm tính {vnd(total)}</span><button className="rounded-xl bg-emerald-600 text-white px-4 py-2 font-bold" disabled={!total} onClick={async () => { const lines = Object.entries(cart).filter(([, q]) => q > 0).map(([sku, qty]) => ({ sku, qty })); const r = await fetch(`/api/public/partner/${token}`, { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ lines, deliver_date: dd || null }) }).then((x) => x.json()); setMsg(r.ok ? `Đã đặt đơn ${r.id} — trại sẽ xác nhận` : r.error); setCart({}); load(); }}>Đặt hàng</button></div>{msg && <div className="text-sm text-emerald-700 mt-1">{msg}</div>}</div>
    <div className="rounded-2xl bg-white p-4 shadow"><b>Đơn của tôi</b><table className="w-full text-sm mt-1"><tbody>{((j.orders as R[]) ?? []).map((o) => <tr key={String(o.id)} className="border-t"><td className="py-1 font-mono text-xs">{String(o.id)}</td><td>{d(o.order_date)} → giao {d(o.deliver_date)}</td><td className="text-xs">{((o.lines as R[]) ?? []).map((l) => `${l.sku}×${l.qty}`).join(", ")}</td><td className="text-right">{vnd(o.total)}</td><td><span className="rounded-full bg-slate-100 px-2 text-xs">{String(o.status)}</span></td></tr>)}</tbody></table></div>
    <div className="rounded-2xl bg-white p-4 shadow"><b>Đã mua · lô · truy xuất · COA</b><table className="w-full text-sm mt-1"><tbody>{((j.sales as R[]) ?? []).slice(0, 30).map((s, i) => <tr key={i} className="border-t"><td className="py-1 text-xs">{d(s.ts)}</td><td>{String(s.sku)}</td><td className="font-mono text-xs">{s.lot_id ? <a className="underline" href={`/trace/${s.lot_id}`} target="_blank">{String(s.lot_id)}</a> : ""}</td><td className="text-right">{String(s.qty)}</td><td className="text-right">{vnd(s.amount)}</td><td>{s.paid ? "✓" : <span className="text-red-700">chưa TT</span>}</td></tr>)}</tbody></table><div className="text-xs mt-1">COA theo lô: {((j.lots as R[]) ?? []).filter((l) => l.coa_url).map((l) => <a key={String(l.id)} className="underline mr-2" href={String(l.coa_url)} target="_blank">{String(l.id)}</a>)}</div></div>
    <div className="text-center text-xs text-slate-500">Dữ liệu trực tiếp từ ITRAN AGRI · <a className="underline" href="/chuan">ICFS công khai</a></div>
  </div></main>);
}
