import { adminPool } from "@/lib/db";
type R = Record<string, unknown>;
export const dynamic = "force-dynamic";
/** Trang CÔNG KHAI (không cần đăng nhập): ITRAN Circular Farm Standard — minh bạch điều khoản, cách đo, điểm từng trại/hộ */
export default async function P({ searchParams }: { searchParams: Promise<{ farm?: string }> }) {
  const { farm } = await searchParams; const p = adminPool();
  const std = (await p.query("select * from standards where code='ITRAN-STD'")).rows[0] as R | undefined;
  const reqs = (await p.query("select * from standard_requirements where standard_code='ITRAN-STD' and public order by clause")).rows as R[];
  const farms = (await p.query("select * from v_icfs_summary order by farm_id")).rows as R[];
  const detail = farm ? ((await p.query("select * from icfs_score($1)", [farm])).rows as R[]) : [];
  const pillars = ["1 An toàn & truy xuất", "2 Tuần hoàn tài nguyên", "3 Định danh & phúc lợi vật nuôi", "4 Đất – nước – đa dạng sinh học", "5 Con người & cộng đồng", "6 Dữ liệu minh bạch", "7 Quản trị & cải tiến"];
  const arr = (v: unknown) => (Array.isArray(v) ? (v as string[]) : []);
  return (<main className="min-h-screen bg-surface-2 text-ink"><div className="max-w-5xl mx-auto px-4 py-8 space-y-6">
    <div><div className="text-xs uppercase tracking-widest text-brand font-bold">ITRAN FARM · công khai</div><h1 className="text-3xl font-black">{String(std?.name ?? "ITRAN Circular Farm Standard")}</h1><p className="mt-2 text-ink">{String(std?.description ?? "")}</p><div className="text-xs text-muted mt-1">Phiên bản {String(std?.version ?? "")} · Chủ sở hữu: ITRAN FARM · Mọi điều khoản đo bằng dữ liệu vận hành (không tự khai) · Lịch sử sửa đổi công khai · API: <code>/api/public/standard</code></div></div>
    <div className="grid sm:grid-cols-3 gap-3">{arr(std?.levels ? (std.levels as R[]).map((l) => JSON.stringify(l)) : []).map((l) => { const o = JSON.parse(l) as R; return <div key={String(o.level)} className={`rounded-xl border p-4 ${o.level === "VÀNG" ? "bg-warning-soft-tok border-amber-300" : o.level === "BẠC" ? "bg-surface-2 border-line" : "bg-orange-50 border-orange-300"}`}><div className="text-xl font-black">{String(o.level)}</div><div className="text-sm">≥ {String(o.min_pct)}% điểm · {String(o.desc)}</div></div>; })}</div>
    <div className="rounded-xl bg-white border p-4"><h2 className="font-bold text-lg mb-2">Trại / hộ đang áp dụng</h2><table className="w-full text-sm"><thead><tr className="text-left text-xs uppercase text-muted"><th>Mã</th><th>Tên</th><th className="text-right">Điểm</th><th>Hạng</th><th>Vi phạm CRITICAL</th><th></th></tr></thead><tbody>{farms.map((f) => <tr key={String(f.farm_id)} className="border-t"><td className="font-mono py-1">{String(f.farm_id)}</td><td>{String(f.name)}</td><td className="text-right font-bold">{String(f.pct)}%</td><td><span className={`rounded-full px-2 py-0.5 text-xs font-bold ${f.level === "VÀNG" ? "bg-amber-200" : f.level === "BẠC" ? "bg-surface-2" : f.level === "ĐỒNG" ? "bg-orange-200" : "bg-danger-soft-tok text-danger-tok"}`}>{String(f.level)}</span></td><td>{String(f.critical_fail)}</td><td><a className="underline text-brand" href={`/chuan?farm=${f.farm_id}`}>chi tiết</a></td></tr>)}</tbody></table></div>
    {farm && <div className="rounded-xl bg-white border p-4"><h2 className="font-bold text-lg mb-2">Kết quả đo theo điều khoản — {farm} (thời gian thực)</h2><table className="w-full text-sm"><thead><tr className="text-left text-xs uppercase text-muted"><th>Điều</th><th>Yêu cầu</th><th>Mức</th><th>Ngưỡng</th><th className="text-right">Đo được</th><th>Kết quả</th></tr></thead><tbody>{detail.map((d) => <tr key={String(d.clause)} className="border-t"><td className="font-mono py-1">{String(d.clause)}</td><td>{String(d.title)}</td><td className="text-xs">{String(d.level)}</td><td>{String(d.threshold ?? "")}</td><td className="text-right font-bold">{String(d.value ?? "—")}</td><td>{d.pass === true ? <span className="text-brand font-bold">ĐẠT</span> : d.pass === false ? <span className="text-danger-tok font-bold">CHƯA</span> : <span className="text-muted">n/a</span>}</td></tr>)}</tbody></table></div>}
    <div className="rounded-xl bg-white border p-4"><h2 className="font-bold text-lg mb-2">Điều khoản ({reqs.length}) theo 7 trụ cột</h2>{pillars.map((pl, i) => <div key={pl} className="mt-3"><div className="font-bold text-brand">{pl}</div><table className="w-full text-sm mt-1"><tbody>{reqs.filter((r) => String(r.clause).startsWith(`${i + 1}.`)).map((r) => <tr key={String(r.clause)} className="border-t align-top"><td className="font-mono py-1 w-12">{String(r.clause)}</td><td><b>{String(r.title)}</b><div className="text-xs text-muted">{String(r.requirement ?? "")}</div><div className="text-xs text-muted">Đo bằng: {arr(r.evidence_tables).join(", ")} · Ngưỡng {String(r.threshold ?? "")} · {String(r.points)} điểm · Kế thừa: {arr(r.basis).join(", ") || "riêng ITRAN"}</div></td><td className="text-xs w-20">{String(r.level)}</td></tr>)}</tbody></table></div>)}</div>
    <div className="text-xs text-muted">Cách sinh chuẩn: kế thừa điều khoản mạnh nhất của VietGAP · GlobalG.A.P. · EU Organic · ISO 22000/HACCP · Halal · ASC (cột "Kế thừa"), bổ sung 4 điều ITRAN riêng (tuần hoàn đo được, định danh cá thể suốt đời, dữ liệu append-only + đối soát đêm, công khai). Hộ liên kết dùng cùng ITRAN AGRI → cùng biểu mẫu, cùng cách đo, audit chéo. Nguồn mở: github.com/ztrandinh/itranagri</div>
  </div></main>);
}
