import { qrSvg, publicBase } from "@/lib/qr";
import { getSession } from "@/lib/auth";
import { withCtx } from "@/lib/db";
import { vietqr, vietqrImage } from "@/lib/vietqr";
type R = Record<string, unknown>;
export const dynamic = "force-dynamic";
const vnd = (v: unknown) => Number(v ?? 0).toLocaleString("vi-VN") + " đ";
const d = (v: unknown) => (v ? new Date(String(v)).toLocaleString("vi-VN") : "");
const BM: Record<string, [string, string[]]> = { BM01: ["Phiếu mẻ TMR / cho ăn", ["Ngày giờ", "Nhóm/chuồng", "Công thức", "Bữa", "Kg kế hoạch", "Kg thực", "Người trộn", "Ghi chú"]], BM02: ["Sổ sự kiện vật nuôi (sinh sản · thú y · cân)", ["Ngày giờ", "Mã con/đàn", "Sự kiện", "Giá trị", "Thuốc/lô", "Ngưng thuốc đến", "Người ghi"]], BM03: ["Nhật ký ruộng", ["Ngày", "Ô/thửa", "Hoạt động", "Giống/vật tư", "Kg", "Giờ máy", "Nhiên liệu", "Người"]], BM04: ["Phiếu mẻ khu D / D5", ["Ngày", "Dây chuyền", "Mã mẻ", "Đầu vào (kg)", "Đầu ra (kg)", "Nhiệt độ/QC", "Người"]], BM05: ["Phiếu nhập/xuất kho", ["Ngày", "Kho", "Mặt hàng", "Lô", "±", "Số lượng", "Lý do", "Người"]], BM06: ["Phiếu bán hàng", ["Ngày", "Khách", "Mặt hàng", "Lô", "SL", "Đơn giá", "Thành tiền", "Thanh toán"]], BM07: ["Checklist SOP", ["Ngày", "SOP", "Ca", "Mục", "Đạt/Không", "Ghi chú", "Người"]], BM08: ["Sổ cổng", ["Giờ", "Biển số", "Vào/Ra", "Mục đích", "Cân?", "Sát trùng?", "Người"]], BM09: ["Biên bản kiểm kê", ["Kho", "Mặt hàng", "Lô", "Sổ", "Đếm", "Chênh", "Người đếm 1", "Người đếm 2"]], BM10: ["Báo cáo sự cố", ["Ngày giờ", "Loại", "Mức", "Mô tả", "Vị trí", "Xử lý ngay", "Người báo"]] };
/** TRANG IN (Ctrl+P → PDF): hóa đơn/phiếu bán + VietQR · phiếu cân · HĐ nhận nuôi · nhãn lô QR · biểu mẫu trắng BM01–BM10 · báo cáo tuần · bảng kiểm thẻ tai */
export default async function P({ params, searchParams }: { params: Promise<{ kind: string; id: string }>; searchParams: Promise<{ farm?: string; n?: string }> }) {
  const { kind, id: rawId } = await params; const id = decodeURIComponent(rawId); const { farm: fq } = await searchParams; const s = await getSession(); if (!s) return <main className="p-8">Cần đăng nhập.</main>;
  const farm = fq ?? s.farmId; const ctx = { ...s, farmId: farm };
  const q = (sql: string, p: unknown[] = []) => withCtx(ctx, async (c) => (await c.query(sql, p)).rows as R[]);
  const f = (await q("select * from farms where id=$1", [farm]))[0] ?? {};
  const head = <div className="flex justify-between border-b-2 border-black pb-2 mb-3"><div><div className="text-lg font-black">{String(f.legal_entity ?? "ITRAN FARM")}</div><div className="text-xs">{String(f.address ?? "")} · MST {String(f.tax_code ?? "")} · {String(f.phone ?? "")}</div></div><div className="text-right text-xs">Trại {farm} · in {new Date().toLocaleString("vi-VN")} · bởi {s.staffName}</div></div>;
  let body: React.ReactNode = null; let size = "A4";
  const dmy = (v: unknown) => { if (!v) return ""; const d = new Date(v as string); return isNaN(d.getTime()) ? String(v).slice(0, 10) : d.toLocaleDateString("vi-VN"); };
  if (kind === "hoa-don") { const sale = (await q("select s.*, p.name as partner_name, p.address as partner_address, p.tax_code as partner_tax, pr.name as product_name from sales s left join partners p on p.id=s.partner_id left join products pr on pr.sku=s.sku where s.id=$1", [id]))[0]; if (!sale) body = <p>Không tìm thấy.</p>; else { const bin = String(f.bank_bin ?? ""), acct = String(f.bank_account ?? "").replace(/\s/g, ""); const memo = `${String(sale.invoice_no ?? sale.id).slice(0, 12)}`; body = <div><h1 className="text-center text-2xl font-black">PHIẾU BÁN HÀNG / HÓA ĐƠN</h1><div className="text-center text-sm mb-4">Số: {String(sale.invoice_no ?? String(sale.id).slice(0, 8).toUpperCase())} · Ngày {d(sale.ts)}</div><div className="grid grid-cols-2 gap-4 text-sm mb-3"><div><b>Khách hàng:</b> {String(sale.partner_name ?? "Khách lẻ")}<br />{String(sale.partner_address ?? "")}<br />{sale.partner_tax ? `MST ${sale.partner_tax}` : ""}</div><div><b>Kênh:</b> {String(sale.channel_code ?? sale.channel)} · <b>Thanh toán:</b> {String(sale.payment ?? "")} {sale.paid ? "(đã thu)" : "(chưa thu)"}</div></div><table className="w-full text-sm border-collapse"><thead><tr className="border-y-2 border-black"><th className="text-left py-1">Mặt hàng</th><th>Lô</th><th className="text-right">SL</th><th className="text-right">Đơn giá</th><th className="text-right">Thành tiền</th></tr></thead><tbody><tr className="border-b"><td className="py-1">{String(sale.product_name ?? sale.sku)}</td><td className="text-center font-mono text-xs">{String(sale.lot_id ?? "")}</td><td className="text-right">{String(sale.qty)} {String(sale.unit ?? "")}</td><td className="text-right">{vnd(sale.price)}</td><td className="text-right">{vnd(sale.amount)}</td></tr></tbody><tfoot><tr><td colSpan={4} className="text-right font-bold py-2">TỔNG CỘNG</td><td className="text-right font-black text-lg">{vnd(sale.amount)}</td></tr></tfoot></table><div className="grid grid-cols-2 gap-4 mt-6 text-sm"><div>{bin && acct ? <div className="flex gap-3 items-center"><img src={vietqrImage(bin, acct, Number(sale.amount), memo, String(f.legal_entity ?? ""))} alt="VietQR" className="h-40" /><div className="text-xs">Quét VietQR để chuyển khoản<br />STK {acct}<br />Nội dung: {memo}<div className="font-mono text-[8px] break-all mt-1">{vietqr(bin, acct, Number(sale.amount), memo)}</div></div></div> : <div className="text-xs text-slate-500">(khai báo bank_bin/bank_account ở Hồ sơ trại để in VietQR)</div>}<div className="text-xs mt-2">Truy xuất lô: {sale.lot_id ? `/trace/${sale.lot_id}` : "—"}</div></div><div className="text-center"><div>Người bán</div><div className="h-16" /><div>{s.staffName}</div></div></div></div>; } }
  else if (kind === "phieu-soan") { const rows = await q("select * from v_picking where order_id=$1", [id]); const o = (await q("select o.*, pt.name as partner_name, pt.address as partner_address from orders o left join partners pt on pt.id=o.partner_id where o.id=$1", [id]))[0]; body = <div><h1 className="text-center text-2xl font-black">PHIẾU SOẠN HÀNG (PICKING LIST)</h1><div className="text-center text-sm mb-3">Đơn {id} · giao {String(o?.deliver_date ?? "")} · {String(o?.partner_name ?? "")} · {String(o?.partner_address ?? "")}</div><table className="w-full text-sm border-collapse"><thead><tr className="border-y-2 border-black"><th className="text-left">Kho</th><th className="text-left">Mặt hàng</th><th>Lô (FEFO)</th><th>HSD</th><th className="text-right">SL</th><th>Đã lấy ☐</th></tr></thead><tbody>{rows.map((r, i) => <tr key={i} className="border-b"><td className="py-1 font-bold">{String(r.warehouse_code ?? "")}</td><td>{String(r.product_name ?? r.sku)}</td><td className="font-mono text-xs text-center">{String(r.lot_id ?? "")}</td><td className="text-center text-xs">{String(r.expiry_date ?? "")}</td><td className="text-right font-bold">{String(r.qty)}</td><td className="text-center">☐</td></tr>)}</tbody></table>{!rows.length && <p className="text-sm">Chưa giữ hàng cho đơn này (bấm Giữ hàng ở Bán hàng › Đơn).</p>}<div className="grid grid-cols-3 gap-4 mt-8 text-center text-sm"><div>Người soạn<div className="h-16" /></div><div>Thủ kho<div className="h-16" /></div><div>Lái xe/giao<div className="h-16" /></div></div></div>; }
  else if (kind === "phieu-luong") { const ps = (await q("select p.*, s.full_name, s.position, s.bank_account from payslips p join staff s on s.id=p.staff_id where p.id::text=$1", [id]))[0]; body = ps ? <div className="text-sm"><h1 className="text-center text-xl font-black">PHIẾU LƯƠNG THÁNG {String(ps.month).slice(0, 7)}</h1><div className="text-center mb-3">{String(ps.full_name)} · {String(ps.staff_id)} · {String(ps.position ?? "")}</div><table className="w-full">{[["Lương cơ bản", ps.base_salary], ["Ngày công / chuẩn", `${ps.work_days}${Number(ps.paid_leave_days) ? ` + ${ps.paid_leave_days} phép` : ""} / ${ps.standard_days}`], ["Lương theo công", ps.salary_by_days], ["Điểm KPI · thưởng KPI", `${ps.kpi_score ?? "—"} · ${vnd(ps.kpi_bonus)}`], ["Phụ cấp", ps.allowances], ["TỔNG THU NHẬP (gross)", ps.gross], ["BHXH (8%) · BHYT (1,5%) · BHTN (1%)", `${vnd(ps.bhxh)} · ${vnd(ps.bhyt)} · ${vnd(ps.bhtn)}`], ["Thu nhập tính thuế", ps.taxable], ["Thuế TNCN", ps.pit], ["Tạm ứng", ps.advances], ["THỰC LĨNH", ps.net]].map(([k, v]) => <tr key={String(k)} className={`border-b ${k === "THỰC LĨNH" || k === "TỔNG THU NHẬP (gross)" ? "font-black" : ""}`}><td className="py-1">{String(k)}</td><td className="text-right">{typeof v === "number" || /^\d+(\.\d+)?$/.test(String(v)) ? vnd(v) : String(v)}</td></tr>)}</table><div className="text-xs mt-2">TK nhận: {String(ps.bank_account ?? "—")} · BH doanh nghiệp đóng: {vnd(ps.employer_ins)}</div><div className="grid grid-cols-2 gap-4 mt-8 text-center"><div>Kế toán<div className="h-14" /></div><div>Người nhận<div className="h-14" /></div></div></div> : <p>Không tìm thấy phiếu lương.</p>; }
  else if (kind === "phieu-can") { const w = (await q("select w.*, p.name as partner_name from weigh_tickets w left join partners p on p.id=w.partner_id where w.id::text=$1", [id]))[0]; body = w ? <div><h1 className="text-center text-2xl font-black">PHIẾU CÂN</h1><div className="text-center text-sm mb-4">Số {String(w.id).slice(0, 8).toUpperCase()} · {d(w.ts)} · cân {String(w.scale_device_id ?? "")}</div><table className="w-full text-base"><tbody>{[["Biển số xe", w.plate], ["Mục đích", w.purpose], ["Mặt hàng", w.sku], ["Đối tác", w.partner_name ?? w.partner_id], ["Tổng (gross)", `${w.gross_kg} kg`], ["Bì (tare)", `${w.tare_kg} kg`], ["Thực (net)", `${w.net_kg} kg`], ["Người cân", w.created_by], ["Phiếu giấy", w.paper_serial]].map(([k, v]) => <tr key={String(k)} className="border-b"><td className="py-1.5 font-semibold w-48">{String(k)}</td><td className={k === "Thực (net)" ? "font-black text-xl" : ""}>{String(v ?? "")}</td></tr>)}</tbody></table><div className="grid grid-cols-3 gap-4 mt-8 text-center text-sm"><div>Người cân<div className="h-16" /></div><div>Lái xe<div className="h-16" /></div><div>Thủ kho<div className="h-16" /></div></div></div> : <p>Không tìm thấy phiếu cân.</p>; }
  else if (kind === "hd-nhan-nuoi") { const c = (await q("select c.*, p.name as partner_name, p.phone as partner_phone, p.address as partner_address from custody_contracts c left join partners p on p.id=c.partner_id where c.id=$1", [id]))[0]; const animals = c ? await q("select id, visual_tag, species, breed, sex, birth_date, last_weight_kg from animals where id = any($1)", [c.animal_ids ?? []]) : []; body = c ? <div className="text-sm leading-relaxed"><h1 className="text-center text-xl font-black">HỢP ĐỒNG CHĂM SÓC HỘ / NHẬN NUÔI</h1><div className="text-center mb-4">Số {String(c.id)} · Ngày {d(c.created_at)}</div><p><b>Bên A (Trại):</b> {String(f.legal_entity ?? "ITRAN FARM")} — {String(f.address ?? "")} — MST {String(f.tax_code ?? "")}</p><p><b>Bên B (Khách):</b> {String(c.partner_name)} — {String(c.partner_phone ?? "")} — {String(c.partner_address ?? "")}</p><p className="mt-3"><b>Điều 1. Đối tượng:</b> Bên A chăm sóc hộ cho Bên B các cá thể sau (định danh suốt đời, mọi sự kiện ghi vào ITRAN OS, Bên B xem qua portal /khach/{String(c.portal_token)}):</p><table className="w-full border-collapse my-2"><thead><tr className="border-y"><th className="text-left">Mã</th><th>Thẻ</th><th>Loài/giống</th><th>Giới</th><th>Sinh</th><th>Cân (kg)</th></tr></thead><tbody>{animals.map((a) => <tr key={String(a.id)} className="border-b"><td className="font-mono">{String(a.id)}</td><td>{String(a.visual_tag ?? "")}</td><td>{String(a.species)} {String(a.breed ?? "")}</td><td>{String(a.sex ?? "")}</td><td>{String(a.birth_date ?? "")}</td><td>{String(a.last_weight_kg ?? "")}</td></tr>)}</tbody></table><p><b>Điều 2. Gói & phí:</b> {String(c.package ?? c.kind)} · phí {vnd(c.fee)}/{String(c.period_months ?? "")} tháng · trả trước {vnd(c.prepaid)} · dự phòng {String(c.reserve_pct ?? 0)}% · từ {String(c.start_date)} đến {String(c.end_date ?? "…")} · kết thúc: {String(c.end_option ?? "")}.</p><p><b>Điều 3. Nghĩa vụ Bên A:</b> chăm sóc theo SOP & tiêu chuẩn ICFS, ghi chép đầy đủ, thông báo sự kiện lớn ≤24h, cho xem live theo giờ đăng ký, bảo hiểm rủi ro theo tỷ lệ dự phòng.</p><p><b>Điều 4. Nghĩa vụ Bên B:</b> thanh toán đúng hạn; không can thiệp kỹ thuật; sản phẩm/lợi ích chia theo gói.</p><p><b>Điều 5. Dữ liệu:</b> Bên B được truy cập dữ liệu cá thể của mình; Bên A không chia sẻ cho bên thứ ba.</p><div className="grid grid-cols-2 gap-4 mt-8 text-center"><div>ĐẠI DIỆN BÊN A<div className="h-20" /></div><div>ĐẠI DIỆN BÊN B<div className="h-20" /></div></div></div> : <p>Không tìm thấy HĐ.</p>; }
  else if (kind === "nhan-lo") { const lots = id === "all" ? await q("select l.*, p.name as product_name from lots l left join products p on p.sku=l.sku where l.farm_id=$1 and l.status='KHA_DUNG' order by l.created_at desc limit 24", [farm]) : await q("select l.*, p.name as product_name from lots l left join products p on p.sku=l.sku where l.id=$1", [id]); const base = publicBase(); const svgs = await Promise.all(lots.map((l) => qrSvg(base + "/trace/" + l.id, 120))); body = <div className="grid grid-cols-3 gap-2">{lots.map((l, i) => <div key={String(l.id)} className="border border-black p-2 h-[40mm] flex gap-2 items-center break-inside-avoid"><div className="h-[32mm] w-[32mm]" dangerouslySetInnerHTML={{ __html: svgs[i] }} /><div className="text-[10px] leading-tight"><div className="font-black text-xs">{String(l.product_name ?? l.sku)}</div><div className="font-mono">{String(l.id)}</div><div>NSX {String(l.mfg_date ?? "")}</div><div>HSD {String(l.expiry_date ?? "")}</div><div>{String(f.legal_entity ?? "ITRAN FARM")}</div><div>Quét để truy xuất</div></div></div>)}</div>; }
  else if (kind === "tem") { const n = Math.min(Number((await searchParams).n ?? 24), 200); const rows = await q("select * from v_lot_label where lot_id=$1", [id]); const l = rows[0]; if (!l) body = <p>Không thấy lô {id}.</p>; else { const svg = await qrSvg(publicBase() + "/trace/" + l.lot_id, 140); const nut = (l.nutrition as Record<string, unknown>) ?? {}; const al = (l.allergen_names as string[] | null) ?? (l.allergens as string[] | null) ?? []; const NUT: Record<string, string> = { energy_kcal: "Năng lượng (kcal)", protein_g: "Đạm (g)", fat_g: "Béo (g)", sat_fat_g: "Béo bão hòa (g)", carb_g: "Carbohydrate (g)", sugar_g: "Đường (g)", fiber_g: "Xơ (g)", sodium_mg: "Natri (mg)", dm_pct: "VCK %", cp_pct: "Đạm thô %", me_mcal: "ME Mcal", ndf_pct: "NDF %" }; const nutKeys = Object.keys(NUT).filter((k) => k in nut).concat(Object.keys(nut).filter((k) => !(k in NUT) && k !== "per")); body = <div className="grid grid-cols-2 gap-2">{Array.from({ length: n }).map((_, i) => <div key={i} className="border border-black p-2 h-[62mm] flex gap-2 break-inside-avoid text-[9px] leading-tight"><div className="w-[34mm] shrink-0"><div dangerouslySetInnerHTML={{ __html: svg }} /><div className="font-mono text-[8px] text-center mt-1">{String(l.lot_id)}</div></div><div className="flex-1"><div className="font-black text-[12px]">{String(l.product_name ?? l.sku_name)}</div><div><b>Thành phần:</b> {String(l.ingredients ?? "")}</div>{al.length > 0 && <div><b>Chứa:</b> {al.join(", ")}</div>}{Array.isArray(l.may_contain) && (l.may_contain as string[]).length > 0 && <div>Có thể chứa: {(l.may_contain as string[]).join(", ")}</div>}<div><b>KL tịnh:</b> {String(l.net_content ?? "")}</div><div><b>NSX:</b> {dmy(l.mfg_date)} · <b>HSD:</b> {dmy(l.expiry_date)}</div><div><b>Bảo quản:</b> {String(l.storage ?? "")}</div>{l.usage_instr ? <div><b>HDSD:</b> {String(l.usage_instr)}</div> : null}{Object.keys(nut).length > 0 && <div><b>Dinh dưỡng/{String(nut.per ?? "100g")}:</b> {nutKeys.map((k) => `${NUT[k] ?? k} ${String(nut[k])}`).join(" · ")}</div>}<div><b>SX:</b> {String(l.producer)} · {String(l.address ?? "")} {l.hotline ? `· ${String(l.hotline)}` : ""}</div><div>Xuất xứ: {String(l.origin ?? "Việt Nam")}{l.gtin ? ` · GTIN ${String(l.gtin)}` : ""}</div>{Array.isArray(l.std_marks) && (l.std_marks as string[]).length > 0 && <div className="font-bold">{(l.std_marks as string[]).join(" · ")}{l.halal ? " · HALAL" : ""}{l.organic ? " · HỮU CƠ" : ""}</div>}{Array.isArray(l.claims) && (l.claims as string[]).length > 0 && <div className="italic">{(l.claims as string[]).join(" · ")}</div>}<div className="mt-1">Quét QR để truy xuất nguồn gốc lô</div></div></div>)}</div>; } }
  else if (kind === "bao-gia") { const qq = (await q("select q.*, p.name as partner_name, p.address as partner_address, p.tax_code as partner_tax, p.phone as partner_phone, s.full_name as rep_name, s.phone as rep_phone from quotes q left join partners p on p.id=q.partner_id left join staff s on s.id=q.sales_rep_id where q.id=$1", [id]))[0]; if (!qq) body = <p>Không thấy báo giá.</p>; else { const L = (qq.lines as R[]) ?? []; body = <div><h1 className="text-2xl font-black text-center">BÁO GIÁ</h1><div className="text-center text-sm mb-3">Số {String(qq.id)} · ngày {dmy(qq.quote_date)} · hiệu lực đến {dmy(qq.valid_until)}</div><div className="grid grid-cols-2 gap-4 text-sm mb-3"><div><b>Kính gửi:</b> {String(qq.partner_name ?? "")}<br />{String(qq.partner_address ?? "")}<br />MST {String(qq.partner_tax ?? "")} · {String(qq.partner_phone ?? "")}</div><div><b>Người phụ trách:</b> {String(qq.rep_name ?? "")} {String(qq.rep_phone ?? "")}<br /><b>Thanh toán:</b> {String(qq.payment_terms ?? "")}<br /><b>Giao hàng:</b> {String(qq.delivery_terms ?? "")}</div></div><table className="w-full text-sm border-collapse"><thead><tr className="border-b-2 border-black"><th className="text-left py-1">#</th><th className="text-left">Sản phẩm</th><th className="text-right">SL</th><th>ĐV</th><th className="text-right">Đơn giá</th><th className="text-right">CK %</th><th className="text-right">Thành tiền</th></tr></thead><tbody>{L.map((l, i) => <tr key={i} className="border-b"><td className="py-1">{i + 1}</td><td>{String(l.name ?? l.sku)}</td><td className="text-right">{String(l.qty)}</td><td className="text-center">{String(l.unit ?? "")}</td><td className="text-right">{Number(l.price).toLocaleString("vi-VN")}</td><td className="text-right">{String(l.discount_pct ?? 0)}</td><td className="text-right">{Number(l.amount ?? Number(l.qty) * Number(l.price) * (1 - Number(l.discount_pct ?? 0) / 100)).toLocaleString("vi-VN")}</td></tr>)}</tbody><tfoot><tr><td colSpan={6} className="text-right py-1">Cộng</td><td className="text-right">{Number(qq.subtotal).toLocaleString("vi-VN")}</td></tr>{Number(qq.discount) > 0 && <tr><td colSpan={6} className="text-right">Chiết khấu</td><td className="text-right">−{Number(qq.discount).toLocaleString("vi-VN")}</td></tr>}<tr><td colSpan={6} className="text-right">VAT {String(qq.vat_pct ?? 0)}%</td><td className="text-right">{Math.round((Number(qq.subtotal) - Number(qq.discount ?? 0)) * Number(qq.vat_pct ?? 0) / 100).toLocaleString("vi-VN")}</td></tr><tr className="font-black border-t-2 border-black"><td colSpan={6} className="text-right py-1">TỔNG</td><td className="text-right">{Number(qq.total).toLocaleString("vi-VN")} đ</td></tr></tfoot></table><div className="text-sm mt-3 whitespace-pre-wrap">{String(qq.terms ?? "")}</div><div className="grid grid-cols-2 mt-8 text-center text-sm"><div>Khách hàng<br /><br /><br />(ký, ghi rõ họ tên)</div><div>Đại diện {String(f.legal_entity ?? "ITRAN FARM")}<br /><br /><br />(ký, đóng dấu)</div></div></div>; } }
  else if (kind === "bm") { body = <div className="space-y-8">{Object.entries(BM).map(([code, [name, cols]]) => <div key={code} className="break-after-page"><div className="flex justify-between"><b>{code} · {name}</b><span className="text-xs">Trại {farm} · Số phiếu: ______ · Ngày: ___/___/______ · Ca: ______</span></div><table className="w-full border-collapse mt-1"><thead><tr>{cols.map((c) => <th key={c} className="border border-black text-xs py-1">{c}</th>)}</tr></thead><tbody>{Array.from({ length: 18 }).map((_, i) => <tr key={i}>{cols.map((c) => <td key={c} className="border border-black h-7" />)}</tr>)}</tbody></table><div className="text-xs mt-1">Người ghi: __________ · Tổ trưởng: __________ · Số hóa vào ITRAN OS (paper_serial) trong 24h.</div></div>)}</div>; }
  else if (kind === "bao-cao-tuan") { const k = (await q("select * from v_kpi_owner_weekly where farm_id=$1", [farm]).catch(() => []))[0]; const alerts = await q("select level, count(*) as n from alerts where farm_id=$1 and acked_at is null group by 1", [farm]); const herd = (await q("select * from v_herd_value where farm_id=$1", [farm]))[0]; const sales = (await q("select coalesce(sum(amount),0) as v from sales where farm_id=$1 and status='ACTIVE' and ts>now()-interval '7 days'", [farm]))[0]; const icfs = (await q("select * from v_icfs_summary where farm_id=$1", [farm]))[0]; body = <div className="text-sm"><h1 className="text-xl font-black">BÁO CÁO TUẦN — {farm} — {new Date().toLocaleDateString("vi-VN")}</h1><div className="grid grid-cols-3 gap-3 mt-3">{[["Đàn (con)", herd?.head_count], ["Giá trị đàn", vnd(herd?.value)], ["Doanh thu 7 ngày", vnd(sales?.v)], ["Cảnh báo mở", alerts.map((a) => `${a.level}: ${a.n}`).join(" · ") || "0"], ["ICFS", `${icfs?.pct ?? "—"}% · ${icfs?.level ?? ""}`], ["KPI khác", k ? JSON.stringify(k).slice(0, 120) : "(v_kpi_owner_weekly)"]].map(([l, v]) => <div key={String(l)} className="border p-2"><div className="text-xs text-slate-500">{String(l)}</div><div className="font-bold">{String(v ?? "—")}</div></div>)}</div><p className="mt-4 text-xs">Chi tiết: /gd · /so-lieu · /canh-bao · /tuan-thu. Bản in này chụp số liệu tại thời điểm in.</p></div>; }
  else if (kind === "the-tai") { const rows = await q("select id, visual_tag, rfid, species, breed, sex, birth_date, class_code, status, location_id from animals where farm_id=$1 and status not in ('CHET','XUAT','LOAI') order by id", [farm]); body = <div><h1 className="text-lg font-black">BẢNG KIỂM CÁ THỂ / THẺ TAI — {farm} ({rows.length} con)</h1><table className="w-full text-xs border-collapse mt-2"><thead><tr>{["Mã", "Thẻ", "RFID", "Loài/giống", "Giới", "Sinh", "Lớp", "TT", "Vị trí", "Kiểm ☐"].map((c) => <th key={c} className="border border-black py-1">{c}</th>)}</tr></thead><tbody>{rows.map((r) => <tr key={String(r.id)}>{[r.id, r.visual_tag, r.rfid, `${r.species} ${r.breed ?? ""}`, r.sex, r.birth_date, r.class_code, r.status, r.location_id, ""].map((v, i) => <td key={i} className="border border-black px-1 py-0.5">{String(v ?? "")}</td>)}</tr>)}</tbody></table></div>; }
  else if (kind === "phu-luc-luong") {
    const st = (await q("select s.*, (pay_base($1, s.id)) as pb from staff s where s.id=$2", [farm, id]))[0];
    if (!st) body = <p>Không tìm thấy nhân sự.</p>; else {
      const pb = (st.pb ?? {}) as R; const gr = (await q("select gs.name, gs.salary_coef from staff_grades sg join grade_scales gs on gs.track=sg.track and gs.code=sg.grade_code and gs.active where sg.staff_id=$1 and sg.until is null order by (sg.track='GS') desc, sg.since desc limit 1", [id]))[0] ?? {};
      const base = Number(pb.base ?? st.salary_base ?? 0); const alw = Number(pb.allowance_key_position ?? 0) + Number(pb.allowance_gs ?? 0);
      body = <div className="text-sm">
        <h1 className="text-center text-xl font-black">PHỤ LỤC HỢP ĐỒNG LAO ĐỘNG</h1>
        <div className="text-center text-xs mb-3">(về tiền lương, phụ cấp — đính kèm HĐLĐ)</div>
        <table className="w-full mb-3"><tbody>
          {[["Họ tên", st.full_name], ["Ngày sinh", dmy(st.dob)], ["CCCD/CMND", st.id_number], ["Địa chỉ", st.address], ["Chức danh / vị trí", `${st.position ?? ""}${st.position_code ? ` (${st.position_code})` : ""}`], ["Phòng ban", st.dept], ["Loại hợp đồng", st.contract_kind], ["Ngày vào làm", dmy(st.hired_on)], ["Bậc lương", `${gr.name ?? "—"} · hệ số ${gr.salary_coef ?? pb.coef ?? 1}`]].map(([k, v]) => <tr key={String(k)} className="border-b"><td className="py-1 w-1/3 text-stone-600">{String(k)}</td><td className="font-semibold">{String(v ?? "—")}</td></tr>)}
        </tbody></table>
        <div className="font-black border-b-2 border-black pb-1 mb-1">1. Tiền lương & phụ cấp</div>
        <table className="w-full mb-3"><tbody>
          {[["Lương vị trí (thang lương)", vnd(pb.scale_amount)], ["Hệ số bậc", String(pb.coef ?? 1)], ["Lương lớp 1 (thang × hệ số)", vnd(base)], ["Phụ cấp (ghế/biệt phái)", vnd(alw)], ["Lương đóng BHXH", vnd(st.insurance_salary ?? base)], ["Số người phụ thuộc", String(st.dependents ?? 0)]].map(([k, v]) => <tr key={String(k)} className="border-b"><td className="py-1">{String(k)}</td><td className="text-right font-semibold">{String(v)}</td></tr>)}
        </tbody></table>
        <div className="text-xs text-stone-600 mb-1">2. Thưởng theo hiệu quả (KPI tháng), thưởng cống hiến quý và các khoản khác thực hiện theo Quy chế lương–thưởng của Công ty. Bậc lương được xét lại định kỳ theo Quy chế thăng hạng. Các khoản trích BHXH/BHYT/BHTN và thuế TNCN theo quy định pháp luật hiện hành.</div>
        <div className="grid grid-cols-2 gap-4 mt-10 text-center"><div>NGƯỜI LAO ĐỘNG<div className="text-xs">(ký, ghi rõ họ tên)</div><div className="h-16" /></div><div>NGƯỜI SỬ DỤNG LAO ĐỘNG<div className="text-xs">(ký, đóng dấu)</div><div className="h-16" /></div></div>
      </div>;
    }
  }
  else body = <p>Không có mẫu in “{kind}”.</p>;
  if (kind === "nhan-lo" || kind === "tem") size = "A4";
  return (<main className="bg-white text-black p-8 max-w-[210mm] mx-auto print:p-0 print:max-w-none">
    <style>{`@media print { @page { size: ${size}; margin: 12mm } .no-print { display: none } } .break-after-page { break-after: page }`}</style>
    <div className="no-print mb-3 flex gap-2 text-sm"><button className="rounded-lg bg-emerald-600 text-white px-4 py-2 font-bold" onClick={undefined} type="button" data-print>In / Lưu PDF (Ctrl+P)</button><a className="underline self-center" href="javascript:history.back()">← quay lại</a></div>
    {head}{body}
    <script dangerouslySetInnerHTML={{ __html: `document.querySelector('[data-print]')?.addEventListener('click',()=>window.print());` }} />
  </main>);
}
