"use client";
import { useEffect, useState } from "react";
import { fmt } from "@/lib/client";
type Doc = { id: string; kind: string; title: string; file: string; mime: string | null; size_bytes: number | null; tags: string[]; expires_on: string | null; uploaded_by: string; created_at: string; status: string };
const KINDS = [["FILE", "File"], ["GIAY_PHEP", "Giấy phép/chứng nhận"], ["HOP_DONG", "Hợp đồng"], ["HOA_DON", "Hóa đơn/chứng từ"], ["COA", "COA/kết quả xét nghiệm"], ["ANH", "Ảnh"], ["BAN_VE", "Bản vẽ/sơ đồ"], ["BIEN_BAN", "Biên bản"], ["KHAC", "Khác"]];
/** TÀI LIỆU ĐÍNH KÈM cho mọi đối tượng (ref_table + ref_id): tải lên, loại, thẻ, hạn; hết hạn báo đỏ */
export default function Attachments({ refTable, refId, compact }: { refTable: string; refId: string; compact?: boolean }) {
  const [docs, setDocs] = useState<Doc[]>([]); const [kind, setKind] = useState("FILE"); const [title, setTitle] = useState(""); const [exp, setExp] = useState(""); const [busy, setBusy] = useState(false); const [msg, setMsg] = useState("");
  const load = () => fetch(`/api/admin/documents?q=&limit=200`).then((r) => r.json()).then((j) => setDocs(((j.rows ?? []) as Doc[]).filter((d) => (d as unknown as { ref_table: string; ref_id: string }).ref_table === refTable && (d as unknown as { ref_id: string }).ref_id === refId && d.status !== "ARCHIVED")));
  useEffect(() => { load(); }, [refTable, refId]); // eslint-disable-line react-hooks/exhaustive-deps
  const up = async (f: File) => { setBusy(true); const fd = new FormData(); fd.set("file", f); fd.set("ref_table", refTable); fd.set("ref_id", refId); fd.set("kind", kind); fd.set("title", title || f.name); if (exp) fd.set("expires_on", exp); const j = await fetch("/api/upload", { method: "POST", body: fd }).then((r) => r.json()); setBusy(false); setMsg(j.document ? "Đã đính kèm" : j.error ?? "lỗi"); setTitle(""); load(); };
  return (<div className={compact ? "" : "card"}>
    <div className="flex items-center gap-2 flex-wrap text-sm"><b>📎 Tài liệu đính kèm ({docs.length})</b><select className="input !w-44 !py-1 !text-xs" value={kind} onChange={(e) => setKind(e.target.value)}>{KINDS.map(([k, l]) => <option key={k} value={k}>{l}</option>)}</select><input className="input !w-44 !py-1 !text-xs" placeholder="tiêu đề (tùy chọn)" aria-label="tiêu đề (tùy chọn)" value={title} onChange={(e) => setTitle(e.target.value)} /><input type="date" className="input !w-36 !py-1 !text-xs" title="hết hạn" value={exp} onChange={(e) => setExp(e.target.value)} /><label className="btn-secondary !py-1 !px-3 !text-sm cursor-pointer">{busy ? "…" : "＋ Tải lên"}<input type="file" className="hidden" onChange={(e) => e.target.files?.[0] && up(e.target.files[0])} /></label>{msg && <span className="text-emerald-700">{msg}</span>}</div>
    <div className="mt-2 flex flex-wrap gap-2">{docs.map((d) => { const expired = d.expires_on && new Date(d.expires_on) < new Date(); return <a key={d.id} href={d.file} target="_blank" className={`rounded-lg border px-2 py-1 text-xs flex items-center gap-1 ${expired ? "border-red-400 bg-red-50" : "bg-white"}`}>{d.mime?.startsWith("image/") ? <img src={d.file} alt="" className="h-8 w-8 object-cover rounded" /> : "📄"}<span><b>{d.title}</b> <span className="text-slate-500">{d.kind}</span>{d.expires_on ? <span className={expired ? "text-red-700" : "text-slate-500"}> · hạn {fmt.d(d.expires_on)}</span> : null}<div className="text-[10px] text-slate-400">{fmt.dt(d.created_at)} · {d.uploaded_by}</div></span></a>; })}{!docs.length && <span className="text-xs text-slate-500">Chưa có tài liệu.</span>}</div>
  </div>);
}
