"use client";
import Tabs from "@/components/Tabs";
import { useEffect, useMemo, useState } from "react";
import { fmt } from "@/lib/client";
import Attachments from "@/components/Attachments";
import { usePrompt } from "@/components/ui/PromptDialog";
type R = Record<string, unknown>;
export type ModTab = { table: string; label: string; cols: string[]; kpi?: (rows: R[]) => [string, string][]; statusCol?: string; flow?: string[]; children?: { table: string; fk: string; label: string; cols: string[] } };
/** MÀN MODULE CHUNG (XNK · R&D · Nhân rộng · …): mỗi tab = 1 bảng (qua /api/admin) — danh sách · KPI · trạng thái theo luồng · thêm/sửa nhanh · con (chi tiết) · đính kèm · xuất CSV. Thêm module mới = khai báo tabs. */
export default function ModulePanel({ tabs, intro }: { tabs: ModTab[]; intro?: string }) {
  const [ti, setTi] = useState(0); const t = tabs[ti]; const [rows, setRows] = useState<R[]>([]); const [meta, setMeta] = useState<{ cols: { name: string; type: string }[]; canWrite: boolean; table: { pk: string; codePrefix?: string } } | null>(null); const [edit, setEdit] = useState<R | null>(null); const [sel, setSel] = useState<R | null>(null); const [kids, setKids] = useState<R[]>([]); const [q, setQ] = useState(""); const [msg, setMsg] = useState("");
  const { prompt, promptElement } = usePrompt();
  const load = () => { fetch(`/api/admin/${t.table}?limit=500&q=${encodeURIComponent(q)}`).then((r) => r.json()).then((j) => setRows(j.rows ?? [])); fetch(`/api/admin/${t.table}?meta=1`).then((r) => r.json()).then(setMeta); };
  useEffect(() => { setSel(null); setEdit(null); load(); }, [ti, q]); // eslint-disable-line react-hooks/exhaustive-deps
  useEffect(() => { if (sel && t.children) fetch(`/api/admin/${t.children.table}?limit=500`).then((r) => r.json()).then((j) => setKids(((j.rows ?? []) as R[]).filter((k) => k[t.children!.fk] === sel[meta?.table.pk ?? "id"]))); }, [sel, t, meta]);
  const pk = meta?.table.pk ?? "id"; const cols = useMemo(() => (meta?.cols ?? []).filter((c) => !["created_at", "updated_at", "created_by", "org_id", "attrs"].includes(c.name)), [meta]);
  const save = async (table: string, row: R) => { const j = await fetch(`/api/admin/${table}`, { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ row }) }).then((r) => r.json()); setMsg(j.ok ? `Đã lưu ${String(j.row?.[pk] ?? "")}` : `${j.error}: ${j.detail ?? ""}`); if (j.ok) { setEdit(null); load(); if (sel) setSel(j.row?.[pk] === sel[pk] ? j.row : sel); } };
  const kpis = t.kpi ? t.kpi(rows) : [];
  return (<div className="space-y-3">
    {promptElement}
    {intro && <div className="text-sm text-slate-600">{intro}</div>}
    <Tabs items={tabs.map((x, i) => [String(i), x.label] as [string, string])} value={String(ti)} onChange={(k) => setTi(Number(k))} />
    {kpis.length > 0 && <div className="grid grid-cols-2 sm:grid-cols-4 lg:grid-cols-6 gap-2">{kpis.map(([l, v]) => <div key={l} className="kpi !p-2"><div className="l">{l}</div><div className="text-xl font-black">{v}</div></div>)}</div>}
    {t.flow && t.statusCol && <div className="flex flex-wrap gap-1 text-xs">{t.flow.map((s, i) => <span key={s} className={`rounded-full px-2 py-1 border ${rows.some((r) => r[t.statusCol!] === s) ? "bg-emerald-50 border-emerald-400" : "bg-white"}`}>{i + 1}. {s} <b>{rows.filter((r) => r[t.statusCol!] === s).length}</b></span>)}</div>}
    {msg && <div className="text-sm text-emerald-800">{msg}</div>}
    <div className="card p-0 overflow-auto"><div className="px-3 py-2 bg-slate-100 rounded-t-xl flex items-center gap-2 text-sm"><b>{t.label} ({rows.length})</b><input className="input !w-56 !py-1" placeholder="tìm…" aria-label="tìm…" value={q} onChange={(e) => setQ(e.target.value)} />{meta?.canWrite && <button className="btn-secondary !py-1 !px-3 !text-sm" onClick={() => setEdit({})}>＋ Thêm</button>}<a className="ml-auto underline" href={`/api/admin/${t.table}?csv=1`}>xuất CSV</a><a className="underline" href={`/quan-tri?t=${t.table}&tab=nhap`}>nhập CSV</a><a className="underline" href={`/quan-tri?t=${t.table}`}>đầy đủ</a></div>
      <table className="tbl text-sm"><thead><tr>{t.cols.map((c) => <th key={c} className="pl-2">{c}</th>)}<th></th></tr></thead><tbody>{rows.map((r) => <tr key={String(r[pk])} className={`cursor-pointer ${sel?.[pk] === r[pk] ? "bg-emerald-50" : ""}`} onClick={() => setSel(r)}>{t.cols.map((c) => <td key={c} className="pl-2 max-w-[240px] truncate">{cell(r[c], c)}</td>)}<td className="text-xs whitespace-nowrap">{meta?.canWrite && <button className="underline" onClick={(e) => { e.stopPropagation(); setEdit({ ...r }); }}>sửa</button>}</td></tr>)}</tbody></table>{!rows.length && <div className="p-3 text-slate-500 text-sm">Chưa có dữ liệu — bấm ＋ Thêm hoặc nhập CSV.</div>}</div>
    {edit && <div className="card border-2 border-emerald-500"><b>{edit[pk] ? `Sửa ${String(edit[pk])}` : "Thêm mới"}</b><div className="grid sm:grid-cols-2 lg:grid-cols-4 gap-2 mt-2 text-sm">{cols.map((c) => { const v = edit[c.name]; const isJson = c.type === "jsonb"; const isNum = ["numeric", "integer", "bigint"].includes(c.type); const isDate = c.type === "date"; const isBool = c.type === "boolean"; const isArr = c.type === "ARRAY"; return <label key={c.name} className={isJson ? "lg:col-span-2" : ""}><span className="text-xs text-slate-500">{c.name}{c.name === pk && meta?.table.codePrefix ? " (trống = tự sinh)" : ""}</span>{isBool ? <select className="input" value={v == null ? "" : String(v)} onChange={(e) => setEdit({ ...edit, [c.name]: e.target.value === "" ? null : e.target.value === "true" })}><option value="">—</option><option value="true">Có</option><option value="false">Không</option></select> : isJson ? <textarea className="input font-mono text-xs" rows={2} value={typeof v === "string" ? v : v == null ? "" : JSON.stringify(v)} onChange={(e) => setEdit({ ...edit, [c.name]: e.target.value })} /> : <input className="input" type={isNum ? "number" : isDate ? "date" : "text"} step="any" value={isArr && Array.isArray(v) ? v.join(", ") : v == null ? "" : c.type.startsWith("timestamp") ? String(v).slice(0, 16) : String(v)} onChange={(e) => setEdit({ ...edit, [c.name]: e.target.value })} />}</label>; })}</div><div className="flex gap-2 mt-2"><button className="btn-primary !py-2" onClick={() => save(t.table, edit)}>Lưu</button><button className="btn-secondary !py-2" onClick={() => setEdit(null)}>Hủy</button></div></div>}
    {sel && <div className="card"><div className="flex items-center gap-2 flex-wrap"><b>{String(sel.name ?? sel.title ?? sel.code ?? sel[pk])}</b><span className="font-mono text-xs text-slate-500">{String(sel[pk])}</span>{t.statusCol && <span className="b-yel">{String(sel[t.statusCol] ?? "")}</span>}{t.statusCol && t.flow && meta?.canWrite && <select className="input !w-auto !py-1 !text-sm ml-auto" value={String(sel[t.statusCol] ?? "")} onChange={(e) => save(t.table, { [pk]: sel[pk], [t.statusCol!]: e.target.value })}>{t.flow.map((s) => <option key={s}>{s}</option>)}</select>}</div>
      <div className="grid grid-cols-2 sm:grid-cols-4 lg:grid-cols-6 gap-1 mt-2 text-sm">{Object.entries(sel).filter(([k, v]) => v !== null && v !== "" && !["farm_id", "org_id", "attrs"].includes(k)).slice(0, 30).map(([k, v]) => <div key={k} className="rounded-lg bg-slate-50 px-2 py-1"><div className="text-[10px] text-slate-500">{k}</div><div className="truncate font-semibold" title={String(typeof v === "object" ? JSON.stringify(v) : v)}>{cell(v, k)}</div></div>)}</div>
      {t.children && <div className="mt-3"><div className="flex items-center"><b className="text-sm">{t.children.label} ({kids.length})</b>{meta?.canWrite && <button className="ml-auto btn-secondary !py-1 !px-2 !text-xs" onClick={async () => { const row: R = { [t.children!.fk]: sel[pk] }; const extra = await prompt({ title: "Thêm dòng", label: `Nhập ${t.children!.cols.slice(1, 3).join(" | ")}`, type: "text", required: false }); if (extra == null) return; const parts = extra.split("|").map((x) => x.trim()); t.children!.cols.slice(1, 3).forEach((c, i) => { if (parts[i]) row[c] = parts[i]; }); save(t.children!.table, row).then(() => setSel({ ...sel })); }}>＋</button>}</div><table className="tbl text-xs mt-1"><thead><tr>{t.children.cols.map((c) => <th key={c} className="pl-2">{c}</th>)}</tr></thead><tbody>{kids.map((k, i) => <tr key={i}>{t.children!.cols.map((c) => <td key={c} className="pl-2">{cell(k[c], c)}</td>)}</tr>)}</tbody></table></div>}
      <div className="mt-3"><Attachments refTable={t.table} refId={String(sel[pk])} compact /></div></div>}
  </div>);
}
function cell(v: unknown, c: string): string { if (v == null) return ""; if (typeof v === "boolean") return v ? "✓" : "✗"; if (typeof v === "object") return JSON.stringify(v).slice(0, 80); if (/_at$|^ts$/.test(c) && /^\d{4}-\d\d-\d\dT/.test(String(v))) return fmt.dt(String(v)); if (/date|_on$|^day$|^etd$|^eta$|^atd$|^ata$/.test(c) && /^\d{4}-\d\d-\d\d/.test(String(v))) return fmt.d(String(v)); if (/amount|total|value|price|cost|budget|fee|duties|vat|quote|deposit|paid|landed/.test(c) && typeof v === "string" && /^\d+(\.\d+)?$/.test(v)) return fmt.vnd(v); return String(v); }
