import io
R="F:/ITRAN FARM/itran-os/"
def rw(p, fn): s=io.open(R+p,encoding="utf-8").read(); n=fn(s); assert n!=s, p; io.open(R+p,"w",encoding="utf-8",newline="\n").write(n); print("ok",p)
rw("src/lib/queries.ts", lambda s: s.replace("  gs_today:", '''  my_pay_estimate: { sql: "select pay_estimate($1, app_staff()) as e" },
  my_payslips: { sql: "select month, work_days, base_salary, salary_by_days, kpi_bonus, allowances, other_add, gross, ins_salary, bhxh, bhyt, bhtn, taxable, pit, advances, net, employer_ins from payslips where farm_id=$1 and staff_id=app_staff() order by month desc limit 12" },
  pit_brackets: { sql: "select * from v_pit_brackets order by bac" },
  my_dependent_claims: { sql: "select * from dependent_claims where farm_id=$1 and staff_id=app_staff() order by created_at desc limit 5" },
  dependent_claims_pending: { sql: "select d.*, s.full_name from dependent_claims d join staff s on s.id=d.staff_id where d.farm_id=$1 and d.status='CHO' order by d.created_at" },
  pay_settings: { sql: "select distinct on (key) key, value, farm_id, version from settings where farm_id in ('GLOBAL',$1) and (key like 'payroll.%' or key like 'bonus.%' or key like 'gs.%' or key like 'pay.%' or key like 'contrib.%' or key like 'grade.%' or key like 'supervision.%' or key like 'training.%') order by key, (farm_id=$1) desc, version desc" },
  gs_today:''',1))
rw("src/app/api/actions/route.ts", lambda s: s.replace('        case "gs_ack":', '''        case "dependent_claim": { const n = Number(b.dependents); if (!(n >= 0 && n <= 20)) throw new Error("ERR_VALUE"); await c.query("insert into dependent_claims(farm_id,staff_id,dependents,note) values ($1,$2,$3,$4)", [s.farmId, s.staffId, n, b.note ?? null]); await c.query("insert into notifications(farm_id,staff_id,level,title,body,link,source) select $1, id, 'INFO', $2, $3, '/nhan-su?tab=bac', 'dependent' from staff where farm_id=$1 and dept='HCNS' and active limit 2", [s.farmId, `Khai người phụ thuộc: ${s.staffName} → ${n}`, String(b.note ?? "")]); return { ok: true }; }
        case "dependent_decide": { if (!["owner","director","accountant"].includes(s.role) && s.dept !== "HCNS") throw new Error("ERR_FORBIDDEN_ROLE"); const r = await c.query("update dependent_claims set status=$3, decided_by=$4, decided_at=now() where id=$1 and farm_id=$2 and staff_id<>$4 returning staff_id, dependents", [b.id, s.farmId, b.approve ? "DUYET" : "TU_CHOI", s.staffId]); if (b.approve && r.rows[0]) await c.query("update staff set dependents=$2 where id=$1", [r.rows[0].staff_id, r.rows[0].dependents]); return { ok: true }; }
        case "gs_ack":''',1))
# MyPath: pay block replaced with full breakdown
def car(s):
    s=s.replace('const pay = useData<R>("my_pay"); const p = (pay.rows ?? [])[0];','const pay = useData<R>("my_pay"); const p = (pay.rows ?? [])[0]; const est = useData<R>("my_pay_estimate"); const e2 = (est.rows ?? [])[0]?.e as R | undefined;',1)
    old_start=s.index('    {p && <div className="text-sm rounded-xl border p-2 bg-slate-50">💰 <b>Lương của tôi tính thế nào</b>')
    old_end=s.index('\n', old_start)
    s=s[:old_start]+'    {p && e2 && <MyPayBox p={p} e={e2} />}'+s[old_end:]
    s=s.replace('function InitiativeForm() {', r'''function MyPayBox({ p, e }: { p: R; e: R }) {
  const claims = useData<R>("my_dependent_claims"); const slips = useData<R>("my_payslips"); const br = useData<R>("pit_brackets"); const [dep, setDep] = useState(String(e.dependents ?? 0)); const [m, setM] = useState(""); const [open, setOpen] = useState(false);
  const last = e.last_payslip as R | null; const n = (v: unknown) => fmt.n(v);
  return <div className="text-sm rounded-xl border p-3 bg-slate-50 space-y-2">
    <div className="flex items-center gap-2 flex-wrap"><b>💰 Lương – bảo hiểm – thuế của tôi</b><span className="text-xs text-slate-500">(ước tính tháng đủ công, KPI 100%; số thật xem phiếu lương bên dưới)</span><button className="ml-auto text-xs underline" onClick={() => setOpen(!open)}>{open ? "thu gọn" : "chi tiết"}</button></div>
    <div className="grid grid-cols-2 md:grid-cols-4 gap-2 text-xs">
      <div className="rounded-lg bg-white p-2"><div className="text-slate-500">Lớp 1 · thang × hệ số</div><div className="font-bold text-base">{n(e.base_l1)}</div><div>{n(p.scale_amount)} × {String(p.coef)} ({String(p.grade_gs ?? p.grade_cm)})</div></div>
      <div className="rounded-lg bg-white p-2"><div className="text-slate-500">KPI tối đa + phụ cấp</div><div className="font-bold text-base">{n(Number(e.kpi_max) + Number(e.allowances))}</div><div>KPI {n(e.kpi_max)} · PC {n(e.allowances)}</div></div>
      <div className="rounded-lg bg-white p-2"><div className="text-slate-500">Bảo hiểm tôi đóng ({String(e.bhxh_pct)}+{String(e.bhyt_pct)}+{String(e.bhtn_pct)}%)</div><div className="font-bold text-base text-amber-800">−{n(Number(e.bhxh) + Number(e.bhyt) + Number(e.bhtn))}</div><div>trên lương BH {n(e.ins_salary)}{e.contract_kind ? ` · HĐ ${String(e.contract_kind)}` : ""}</div></div>
      <div className="rounded-lg bg-white p-2"><div className="text-slate-500">Thuế TNCN</div><div className="font-bold text-base text-amber-800">−{n(e.pit)}</div><div>TN tính thuế {n(e.taxable)}</div></div>
      <div className="rounded-lg bg-emerald-50 p-2 col-span-2"><div className="text-slate-500">Thực nhận ước tính</div><div className="font-black text-lg text-emerald-800">{n(e.net)}</div><div>Công ty đóng thêm BH cho tôi: {n(e.employer_ins)}/tháng</div></div>
      <div className="rounded-lg bg-white p-2 col-span-2"><div className="text-slate-500">Giảm trừ gia cảnh</div><div>Bản thân {n(e.giam_tru_ban_than)} · Phụ thuộc {String(e.dependents)} người × {n(Number(e.giam_tru_phu_thuoc) / Math.max(1, Number(e.dependents)))} = {n(e.giam_tru_phu_thuoc)}</div>
        <div className="flex items-center gap-1 mt-1">Khai người phụ thuộc: <input className="input !py-0 !w-14 text-right" value={dep} onChange={(ev) => setDep(ev.target.value)} /><button className="btn-secondary !py-0.5 !px-2 !text-xs" onClick={async () => { const j = await act("dependent_claim", { dependents: Number(dep), note: "khai từ Tài khoản" }); setM(j.error ? String(j.error) : "Đã gửi HCNS duyệt (kèm hồ sơ giấy)"); claims.reload(); }}>Gửi HCNS</button><span className="text-[11px]">{m}{(claims.rows ?? [])[0] ? ` · lần gần nhất: ${String((claims.rows ?? [])[0].dependents)} người — ${String((claims.rows ?? [])[0].status)}` : ""}</span></div></div>
    </div>
    {open && <div className="space-y-2">
      <div className="text-xs text-slate-600">Cách tính: Lớp 1 = thang lương vị trí × hệ số bậc × ngày công/26 · Lớp 2 = KPI ({n(e.kpi_max)} khi 100%) + thưởng điều kiện tháng · Lớp 3 = phụ cấp · Lớp 4 = thưởng cống hiến quý. BH tính trên lương đóng BH (trần {n(e.ins_cap)}); TNCN = (tổng − BH − giảm trừ) × biểu lũy tiến. Mọi tham số là cấu hình (HCNS › Cơ chế lương–thưởng).</div>
      <div className="grid md:grid-cols-2 gap-2">
        <div className="rounded-lg bg-white p-2 overflow-auto"><div className="text-xs font-bold text-slate-500 uppercase">Biểu thuế TNCN lũy tiến (tháng)</div><table className="tbl text-xs"><tbody>{(br.rows ?? []).map((b) => <tr key={String(b.bac)}><td className="pl-2">Bậc {String(b.bac)}</td><td>{n(b.tu)} → {b.den ? n(b.den) : "∞"}</td><td className="text-right">{String(b.thue_pct)}%</td></tr>)}</tbody></table></div>
        <div className="rounded-lg bg-white p-2 overflow-auto"><div className="text-xs font-bold text-slate-500 uppercase">Phiếu lương của tôi (12 tháng)</div><table className="tbl text-xs"><thead><tr><th className="pl-2">Tháng</th><th className="text-right">Công</th><th className="text-right">Tổng</th><th className="text-right">BH</th><th className="text-right">Thuế</th><th className="text-right">Thực nhận</th></tr></thead><tbody>{(slips.rows ?? []).map((r) => <tr key={String(r.month)}><td className="pl-2">{fmt.d(r.month).slice(3)}</td><td className="text-right">{String(r.work_days)}</td><td className="text-right">{n(r.gross)}</td><td className="text-right">{n(Number(r.bhxh) + Number(r.bhyt) + Number(r.bhtn))}</td><td className="text-right">{n(r.pit)}</td><td className="text-right font-bold">{n(r.net)}</td></tr>)}{(slips.rows ?? []).length === 0 && <tr><td className="p-2 text-slate-500" colSpan={6}>Chưa có phiếu lương{last ? "" : "."}</td></tr>}</tbody></table></div>
      </div>
    </div>}
  </div>;
}
function InitiativeForm() {''',1)
    # PayPanel: settings editor + dependent claims approval
    s=s.replace('  const ps = useData<R>("pay_structure"); const sc = useData<R>("salary_scales"); const hc = useData<R>("headcount"); const cb = useData<R>("contribution_bonus"); const [msg, setMsg] = useState("");','  const ps = useData<R>("pay_structure"); const sc = useData<R>("salary_scales"); const hc = useData<R>("headcount"); const cb = useData<R>("contribution_bonus"); const st = useData<R>("pay_settings"); const dc = useData<R>("dependent_claims_pending"); const [msg, setMsg] = useState("");',1)
    s=s.replace('    <div className="card p-0 overflow-auto"><div className="px-3 py-2 bg-slate-100 rounded-t-xl font-bold">Thưởng cống hiến đã chốt (lớp 4)</div>', r'''    <div className="grid md:grid-cols-2 gap-3">
      <div className="card p-0 overflow-auto"><div className="px-3 py-2 bg-slate-100 rounded-t-xl font-bold">⚙ Tham số lương · BH · thuế · thưởng · giám sát (cấu hình, có phiên bản)</div><table className="tbl text-sm"><tbody>{(st.rows ?? []).map((r) => <tr key={String(r.key)}><td className="pl-3 text-xs">{String(r.key)}<div className="text-[10px] text-slate-400">{SETTING_LABEL[String(r.key)] ?? ""} · {String(r.farm_id)} v{String(r.version)}</div></td><td className="text-right">{canMoney || canHR ? <input className="input !py-0 !w-32 text-right" defaultValue={String(typeof r.value === "string" ? r.value : JSON.stringify(r.value)).replace(/^"|"$/g, "")} onBlur={async (e) => { const v = e.target.value; const cur = String(typeof r.value === "string" ? r.value : JSON.stringify(r.value)).replace(/^"|"$/g, ""); if (v === cur) return; const j = await act("set_setting", { key: r.key, value: isNaN(Number(v)) ? v : Number(v) }); setMsg(j.error ? String(j.error) : `Đã lưu ${r.key} = ${v} (v${j.version})`); st.reload(); }} /> : String(typeof r.value === "string" ? r.value : JSON.stringify(r.value))}</td></tr>)}
        {[["payroll.insurance_cap", "Trần lương đóng BH (20× lương cơ sở)"], ["payroll.insure_probation", "Thử việc/thời vụ có đóng BH? (0/1)"], ["gs.omissions_max_month", "Ngưỡng lỗi GS/tháng trước khi mất thưởng"], ["gs.daily_checks_min", "Lượt kiểm tối thiểu/phòng/ngày"], ["pay.gs_secondment_allowance", "Phụ cấp biệt phái GS"], ["bonus.contribution_unit", "Đơn giá 1 điểm cống hiến"], ["bonus.contribution_cap", "Trần thưởng cống hiến/quý"], ["bonus.base_gs", "Thưởng tháng cơ sở GS"], ["bonus.head_repeat_points", "Điểm trừ trưởng phòng/lỗi lặp"], ["bonus.head_capa_points", "Điểm trừ trưởng phòng/CAPA quá hạn"]].filter(([k]) => !(st.rows ?? []).some((r) => r.key === k)).map(([k, l]) => <tr key={k}><td className="pl-3 text-xs">{k}<div className="text-[10px] text-slate-400">{l} · mặc định</div></td><td className="text-right">{(canMoney || canHR) && <input className="input !py-0 !w-32 text-right" placeholder="nhập để ghi đè" onBlur={async (e) => { if (!e.target.value) return; const j = await act("set_setting", { key: k, value: Number(e.target.value) }); setMsg(j.error ? String(j.error) : `Đã lưu ${k}`); st.reload(); }} />}</td></tr>)}</tbody></table></div>
      <div className="card p-0 overflow-auto"><div className="px-3 py-2 bg-slate-100 rounded-t-xl font-bold">Khai người phụ thuộc chờ HCNS duyệt ({(dc.rows ?? []).length})</div><table className="tbl text-sm"><tbody>{(dc.rows ?? []).map((r) => <tr key={String(r.id)}><td className="pl-3">{String(r.full_name)}</td><td className="text-right">{String(r.dependents)} người</td><td className="text-xs">{String(r.note ?? "")}</td><td className="whitespace-nowrap">{canHR && <><button className="btn-primary !py-0.5 !px-2 !text-xs mr-1" onClick={async () => { await act("dependent_decide", { id: r.id, approve: true }); dc.reload(); }}>Duyệt</button><button className="text-xs underline" onClick={async () => { await act("dependent_decide", { id: r.id, approve: false }); dc.reload(); }}>từ chối</button></>}</td></tr>)}{(dc.rows ?? []).length === 0 && <tr><td className="p-3 text-slate-500 text-sm">Không có.</td></tr>}</tbody></table></div>
    </div>
    <div className="card p-0 overflow-auto"><div className="px-3 py-2 bg-slate-100 rounded-t-xl font-bold">Thưởng cống hiến đã chốt (lớp 4)</div>''',1)
    s=s.replace('/** CƠ CHẾ LƯƠNG – THƯỞNG 4 lớp + định biên */', '''const SETTING_LABEL: Record<string, string> = { "payroll.bhxh_employee_pct": "BHXH người LĐ %", "payroll.bhyt_employee_pct": "BHYT người LĐ %", "payroll.bhtn_employee_pct": "BHTN người LĐ %", "payroll.bhxh_employer_pct": "BHXH công ty %", "payroll.bhyt_employer_pct": "BHYT công ty %", "payroll.bhtn_employer_pct": "BHTN công ty %", "payroll.giam_tru_ban_than": "Giảm trừ bản thân/tháng", "payroll.giam_tru_phu_thuoc": "Giảm trừ mỗi người phụ thuộc", "payroll.kpi_bonus_base_pct": "KPI tối đa = % lương L1", "payroll.standard_days": "Ngày công chuẩn", "payroll.insurance_cap": "Trần lương đóng BH", "payroll.insure_probation": "Thử việc có đóng BH (0/1)", "bonus.deduct_per_point": "Tiền trừ mỗi điểm lỗi", "bonus.max_deduct_pct": "Trừ tối đa % thưởng", "supervision.checks_per_week": "Lượt kiểm/tuần mặc định", "training.hours_per_week": "Giờ học/tuần", "training.pass_score": "Điểm đậu bài thi" };
/** CƠ CHẾ LƯƠNG – THƯỞNG 4 lớp + định biên */''',1)
    return s
rw("src/components/panels/Career.tsx", car)
rw("src/lib/admin.ts", lambda s: s.replace('  { table: "salary_scales",', '''  { table: "dependent_claims", pk: "id", label: "Lương · khai người phụ thuộc (giảm trừ gia cảnh) chờ duyệt", group: "Nhân sự", farmScoped: true, softDelete: null, writeRoles: ["owner", "director", "accountant", "it_engineer"] },
  { table: "salary_scales",''',1))
