import io
p="F:/ITRAN FARM/itran-os/src/components/panels/DuTru.tsx"; s=io.open(p,encoding="utf-8").read()
def rep(a,b):
    global s
    assert a in s, a[:70]; s=s.replace(a,b,1)
rep('import { LineChart, Line, BarChart, Bar, XAxis, YAxis, Tooltip, Legend, CartesianGrid, ResponsiveContainer, ReferenceLine } from "recharts";','import { LineChart, Line, BarChart, Bar, XAxis, YAxis, Tooltip, Legend, CartesianGrid, ResponsiveContainer, ReferenceLine, PieChart, Pie, Cell } from "recharts";\nconst COLORS = ["#059669", "#0ea5e9", "#f59e0b", "#8b5cf6", "#ef4444", "#14b8a6", "#64748b", "#84cc16", "#f97316", "#a855f7", "#0891b2", "#be185d", "#4d7c0f", "#b45309"];')
# replace group card grid with charts + compact controls
i=s.index('      <div className="grid grid-cols-2 sm:grid-cols-3 lg:grid-cols-5 xl:grid-cols-7 gap-2">{G.map((g) => {'); j=s.index('      {pick && <div className="card">', i)
new='''      <div className="grid lg:grid-cols-3 gap-3">
        <div className="card !p-3"><div className="text-sm font-bold">Cơ cấu tồn theo nhóm dự trữ</div><div style={{ height: 230 }}><ResponsiveContainer><PieChart><Pie data={G.map((g) => ({ name: String(g.name), value: R0.filter((r) => r.stock_group === g.code).reduce((a, r) => a + Number(r.qty), 0) })).filter((d) => d.value > 0)} dataKey="value" nameKey="name" innerRadius={45} outerRadius={85} paddingAngle={2} onClick={(d) => { const g = G.find((x) => x.name === (d as { name?: string }).name); if (g) setGsel(gsel === g.code ? "" : String(g.code)); }}>{G.map((g, k) => <Cell key={String(g.code)} fill={COLORS[k % COLORS.length]} />)}</Pie><Tooltip formatter={(v) => fmt.n(Number(v))} /><Legend wrapperStyle={{ fontSize: 10 }} /></PieChart></ResponsiveContainer></div></div>
        <div className="card !p-3"><div className="text-sm font-bold">Theo nhóm: ngày còn (min) & số mặt hàng cần bổ sung <span className="text-xs font-normal text-slate-500">— bấm cột để lọc</span></div><div style={{ height: 230 }}><ResponsiveContainer><BarChart data={G.map((g) => { const rows = R0.filter((r) => r.stock_group === g.code); const d = Math.min(...rows.map((r) => r.days_left == null ? 9e9 : Number(r.days_left))); return { code: String(g.code), name: String(g.icon ?? "") + " " + String(g.name).split(" ").slice(0, 2).join(" "), ngay: d < 9e9 ? Math.min(d, 365) : 0, thieu: rows.filter((r) => !["OK", "TRONG"].includes(String(r.flag))).length, tong: rows.length }; })} onClick={(e) => { const c = (e as { activePayload?: { payload?: { code?: string } }[] })?.activePayload?.[0]?.payload?.code; if (c) setGsel(gsel === c ? "" : c); }}><CartesianGrid strokeDasharray="3 3" /><XAxis dataKey="name" tick={{ fontSize: 9 }} interval={0} angle={-20} height={50} /><YAxis yAxisId="l" tick={{ fontSize: 10 }} width={35} /><YAxis yAxisId="r" orientation="right" tick={{ fontSize: 10 }} width={30} /><Tooltip /><Legend wrapperStyle={{ fontSize: 10 }} /><Bar yAxisId="l" dataKey="ngay" name="Ngày còn (min, ≤365)" fill="#059669" /><Bar yAxisId="r" dataKey="thieu" name="Cần bổ sung (mặt hàng)" fill="#ef4444" /></BarChart></ResponsiveContainer></div></div>
        <div className="card !p-3 space-y-2"><div className="text-sm font-bold">Nhóm dự trữ & mặt hàng theo dõi</div>
          <select className="input" value={gsel} onChange={(e) => setGsel(e.target.value)}><option value="">— Tất cả nhóm ({R0.length} mặt hàng theo dõi) —</option>{G.map((g) => { const rows = R0.filter((r) => r.stock_group === g.code); const nbad = rows.filter((r) => !["OK", "TRONG"].includes(String(r.flag))).length; return <option key={String(g.code)} value={String(g.code)}>{String(g.icon ?? "")} {String(g.name)} · {rows.length} mh · {rows.filter((r) => Number(r.qty) > 0).length} có tồn{nbad ? ` · ${nbad} cần bổ sung` : ""}</option>; })}</select>
          <div className="flex gap-2 flex-wrap"><button type="button" className="btn-secondary !py-1.5 !px-3 text-sm" onClick={() => setPick(pick ? "" : (gsel || String(G[0]?.code ?? "")))}>☑ Chọn mặt hàng theo dõi ▾</button><button type="button" className="btn-secondary !py-1.5 !px-3 text-sm" onClick={() => setShowRcv(!showRcv)}>📥 Nhập kho nhanh ▾</button></div>
          {gsel && <div className="text-xs text-slate-500">Ví dụ nhóm: {String(G.find((g) => g.code === gsel)?.examples ?? "")}</div>}
          <div className="text-xs text-slate-500">Nhóm là danh mục (<a className="underline" href="/quan-tri?t=stock_groups">stock_groups</a>); mặt hàng theo dõi = tick trong danh sách; mặt hàng mới thêm ngay tại đây.</div></div></div>
'''
s=s[:i]+new+s[j:]
# picker: group selector inside
rep('<b>Chọn mặt hàng theo dõi dự trữ — nhóm {String(G.find((g) => g.code === pick)?.name)}</b>','<b>Chọn mặt hàng theo dõi dự trữ</b><select className="input !w-72 !py-1" value={pick} onChange={(e) => setPick(e.target.value)}>{G.map((g) => <option key={String(g.code)} value={String(g.code)}>{String(g.icon ?? "")} {String(g.name)}</option>)}</select>')
# receipt collapsible
rep('      <div className="card"><div className="flex items-center gap-2 flex-wrap"><b>Nhập kho nhanh</b>','      {showRcv && <div className="card"><div className="flex items-center gap-2 flex-wrap"><b>Nhập kho nhanh</b>')
rep('<button className="btn-primary !py-2" disabled={!rf.warehouse_id || !rf.sku || !rf.qty} onClick={receipt}>Nhập</button></div>{msg2 && <div className="text-sm mt-1 text-emerald-700">{msg2}</div>}</div>','<button className="btn-primary !py-2" disabled={!rf.warehouse_id || !rf.sku || !rf.qty} onClick={receipt}>Nhập</button></div>{msg2 && <div className="text-sm mt-1 text-emerald-700">{msg2}</div>}</div>}')
rep('const [rf, setRf] = useState<R>({ reason: "NHAP_MUA" }); const [msg2, setMsg2] = useState("");','const [rf, setRf] = useState<R>({ reason: "NHAP_MUA" }); const [msg2, setMsg2] = useState(""); const [showRcv, setShowRcv] = useState(false);')
io.open(p,"w",encoding="utf-8",newline="\n").write(s); print("ok")
