import io, os
R="F:/ITRAN FARM/itran-os/"
def rw(p, fn): s=io.open(R+p,encoding="utf-8").read(); n=fn(s); assert n!=s, p; io.open(R+p,"w",encoding="utf-8",newline="\n").write(n); print("ok",p)
rw("src/lib/queries.ts", lambda s: s.replace("  plan_years: {", '''  herd_actions: { sql: "select h.*, a.location_id, a.group_id from v_herd_actions h join animals a on a.id=h.animal_id where h.farm_id=$1 order by h.due, h.priority" },
  plot_cost: { sql: "select *, input_cost+machine_cost+water_cost+labor_cost as total_cost, case when yield_kg>0 then round((input_cost+machine_cost+water_cost+labor_cost)/yield_kg) end as cost_per_kg, case when area_ha>0 then round((input_cost+machine_cost+water_cost+labor_cost)/area_ha) end as cost_per_ha from v_plot_cost where farm_id=$1 order by sow_date desc" },
  stock_value: { sql: "select * from v_stock_value where farm_id=$1 order by value desc" },
  occupancy_month: { sql: "select * from v_occupancy_month where farm_id=$1 order by month" },
  plan_years: {''',1))
rw("src/app/api/jobs/[job]/route.ts", lambda s: s.replace('out[`compliance:${f}`] = (await adminPool().query("select gen_compliance_tasks($1) as n", [f])).rows[0].n;','out[`compliance:${f}`] = (await adminPool().query("select gen_compliance_tasks($1) as n", [f])).rows[0].n; out[`herd:${f}`] = (await adminPool().query("select gen_herd_actions($1) as n", [f])).rows[0].n;',1))
# DanPanel tab
def dan(s):
    s=s.replace('useState<"tong" | "cathe" | "dan" | "lo" | "chuky" | "nhaplo" | "theodoi">("tong");','useState<"tong" | "cathe" | "dan" | "lo" | "chuky" | "nhaplo" | "theodoi" | "viec">("tong"); const acts = useData("herd_actions");',1)
    s=s.replace('["chuky", "Chu kỳ"]]','["chuky", "Chu kỳ"], ["viec", `📋 Việc đàn · lịch sinh sản (${(acts.rows ?? []).length})`]]',1)
    s=s.replace('      {tab === "chuky" && (','''      {tab === "viec" && <div className="card p-0 overflow-auto"><div className="px-3 py-2 bg-slate-100 rounded-t-xl font-bold">Lịch sinh sản & hành động 30 ngày tới — tự suy từ sự kiện: khám thai (phối +60), chuẩn bị đẻ (phối +283 −14), tái phối (đẻ +60), cai sữa (180 ngày), cân 14 ngày, loại thải (không đậu ≥3 / &gt;8 tuổi), vỗ béo đủ ngày xuất, đang ngưng thuốc; việc ≤3 ngày tự sinh trong "Ca của tôi"</div><table className="tbl text-sm"><thead><tr><th className="pl-3">Hạn</th><th>Việc</th><th>Con</th><th>Hạng</th><th>Ghi chú</th><th>Ưu tiên</th><th></th></tr></thead><tbody>{(acts.rows ?? []).map((r, i) => <tr key={i} className={new Date(String(r.due)) < new Date() ? "bg-red-50" : r.priority === "CAO" ? "bg-amber-50" : ""}><td className="pl-3">{fmt.d(String(r.due))}</td><td className="font-semibold">{String(r.action)}</td><td><a className="underline" href={`/xem/animal/${r.animal_id}`}>{String(r.visual_tag ?? r.animal_id)}</a></td><td className="text-xs">{String(r.class_code)}</td><td className="text-xs">{String(r.note)}</td><td className="text-xs">{String(r.priority)}</td><td><ChartIcon type="animal" id={String(r.animal_id)} /></td></tr>)}</tbody></table>{!(acts.rows ?? []).length && <div className="p-3 text-sm text-slate-500">Không có việc đàn trong 30 ngày.</div>}</div>}
      {tab === "chuky" && (''',1)
    return s
rw("src/components/panels/DanPanel.tsx", dan)
def canh(s):
    s=s.replace('useState<"mua" | "vattu" | "thu" | "nuoc" | "dat" | "luancanh" | "bieudo">("mua")','useState<"mua" | "vattu" | "thu" | "nuoc" | "dat" | "luancanh" | "giathanh" | "bieudo">("mua")',1)
    s=s.replace('["luancanh", "Đất đai · Luân canh, liên kết hộ"], ["bieudo", "Mùa vụ · 📈 Biểu đồ"]','["luancanh", "Đất đai · Luân canh, liên kết hộ"], ["giathanh", "Mùa vụ · 💰 Giá thành ô"], ["bieudo", "Mùa vụ · 📈 Biểu đồ"]',1)
    s=s.replace('const kc = useData("crop_kc");','const kc = useData("crop_kc"); const pcost = useData("plot_cost");',1)
    s=s.replace('      {tab === "bieudo" &&','''      {tab === "giathanh" && <div className="card p-0 overflow-auto"><div className="px-3 py-2 bg-slate-100 rounded-t-xl font-bold">Giá thành theo ô/vụ = vật tư (giá mua) + máy (dầu + giờ máy) + tưới (điện + công) + công lao động — đơn giá ở <a className="underline font-normal" href="/quan-tri?t=settings">settings price.*/cost.*</a>; so đ/kg giữa các ô để chọn giống/ô/cách làm</div><table className="tbl text-sm"><thead><tr><th className="pl-3">Mùa vụ</th><th>Ô</th><th>Cây</th><th className="text-right">ha</th><th className="text-right">Sản lượng kg</th><th className="text-right">Vật tư</th><th className="text-right">Máy</th><th className="text-right">Tưới</th><th className="text-right">Công</th><th className="text-right">Tổng</th><th className="text-right">đ/ha</th><th className="text-right">đ/kg</th><th>TT</th></tr></thead><tbody>{(pcost.rows ?? []).map((r) => <tr key={String(r.season_id)}><td className="pl-3 font-mono text-xs">{String(r.code)}</td><td>{String(r.plot_name)}</td><td>{String(r.crop)}</td><td className="text-right">{String(r.area_ha)}</td><td className="text-right">{fmt.n(Number(r.yield_kg))}</td><td className="text-right">{fmt.vnd(Number(r.input_cost))}</td><td className="text-right">{fmt.vnd(Number(r.machine_cost))}</td><td className="text-right">{fmt.vnd(Number(r.water_cost))}</td><td className="text-right">{fmt.vnd(Number(r.labor_cost))}</td><td className="text-right font-bold">{fmt.vnd(Number(r.total_cost))}</td><td className="text-right">{r.cost_per_ha ? fmt.vnd(Number(r.cost_per_ha)) : ""}</td><td className="text-right font-bold">{r.cost_per_kg ? fmt.vnd(Number(r.cost_per_kg)) : "—"}</td><td className="text-xs">{String(r.status)}</td></tr>)}</tbody></table></div>}
      {tab === "bieudo" &&''',1)
    return s
rw("src/components/panels/CanhTac.tsx", canh)
def kho(s):
    s=s.replace('| "bin" | "rop" | "lanh" | "van" | "ncc" | "the" | "bieudo">','| "bin" | "rop" | "lanh" | "van" | "ncc" | "the" | "giatri" | "bieudo">',1)
    s=s.replace('["the", "Tồn · Thẻ kho theo lô"], ["bieudo", "Tồn · 📈 Biểu đồ"]','["the", "Tồn · Thẻ kho theo lô"], ["giatri", "Tồn · 💰 Giá trị tồn"], ["bieudo", "Tồn · 📈 Biểu đồ"]',1)
    s=s.replace('const [msg2, setMsg2] = useState("");','const [msg2, setMsg2] = useState(""); const sval = useData("stock_value");',1)
    s=s.replace('      {tab === "so" && (','''      {tab === "giatri" && <div className="card p-0 overflow-auto"><div className="px-3 py-2 bg-slate-100 rounded-t-xl font-bold">Giá trị tồn kho (giá bình quân lô / giá mua gần nhất) — tổng {fmt.vnd((sval.rows ?? []).reduce((a, r) => a + Number(r.value), 0))} · đầu vào {fmt.vnd((sval.rows ?? []).filter((r) => r.block === "DAU_VAO").reduce((a, r) => a + Number(r.value), 0))} · đầu ra {fmt.vnd((sval.rows ?? []).filter((r) => r.block === "DAU_RA").reduce((a, r) => a + Number(r.value), 0))}</div><table className="tbl text-sm"><thead><tr><th className="pl-3">Kho</th><th>Khối</th><th>Nhóm</th><th>Mặt hàng</th><th className="text-right">SL</th><th className="text-right">Giá trị</th></tr></thead><tbody>{(sval.rows ?? []).map((r, i) => <tr key={i}><td className="pl-3">{String(r.warehouse_code)}</td><td className="text-xs">{String(r.block)}</td><td className="text-xs">{String(r.group_name ?? "")}</td><td>{String(r.product_name)}</td><td className="text-right">{fmt.n(Number(r.qty))} {String(r.unit)}</td><td className="text-right font-semibold">{fmt.vnd(Number(r.value))}</td></tr>)}</tbody></table></div>}
      {tab === "so" && (''',1)
    return s
rw("src/components/panels/KhoPanel.tsx", kho)
def dl(s):
    s=s.replace('      {tab === "kpi" && <div className="grid md:grid-cols-2 gap-3">','      {tab === "kpi" && <div className="grid md:grid-cols-2 gap-3"><div className="card p-0 overflow-auto md:col-span-2"><div className="px-3 py-2 bg-slate-100 rounded-t-xl font-bold">Công suất phòng theo tháng (occupancy) & doanh thu phòng</div><table className="tbl text-sm"><thead><tr><th className="pl-3">Tháng</th><th className="text-right">Phòng</th><th className="text-right">Đêm bán</th><th className="text-right">Công suất %</th><th className="text-right">Doanh thu phòng</th></tr></thead><tbody>{(occ.rows ?? []).map((r) => <tr key={String(r.month)}><td className="pl-3">{fmt.d(String(r.month))}</td><td className="text-right">{String(r.rooms)}</td><td className="text-right">{String(r.room_nights)}</td><td className={`text-right font-bold ${Number(r.occupancy_pct) < 40 ? "text-red-700" : ""}`}>{String(r.occupancy_pct)}</td><td className="text-right">{fmt.vnd(Number(r.room_revenue ?? 0))}</td></tr>)}</tbody></table></div>',1)
    return s
rw("src/components/panels/DuLich.tsx", dl)
