import io
R="F:/ITRAN FARM/itran-os/"
def rw(p, fn): s=io.open(R+p,encoding="utf-8").read(); n=fn(s); assert n!=s, p; io.open(R+p,"w",encoding="utf-8",newline="\n").write(n); print("ok",p)
rw("src/lib/queries.ts", lambda s: s.replace("  my_inbox:", '''  collusion_pairs: { sql: "select * from v_collusion_pairs where farm_id=$1 order by level='DO' desc, n_signals desc", ttl: 300 },
  collusion_signals: { sql: "select v.*, s.full_name as supervisor_name from v_collusion_signals v left join staff s on s.id=v.supervisor_id where v.farm_id=$1 order by v.week_start desc, v.severity", ttl: 300 },
  my_cross_checks: { sql: "select x.*, c.item, c.note as original_note, cr.name as criteria_name, s.full_name as target_name from cross_checks x join supervision_checks c on c.id=x.original_check_id left join supervision_criteria cr on cr.id=x.criteria_id left join staff s on s.id=x.target_staff_id where x.farm_id=$1 and x.checker_id=app_staff() and x.status='MO' order by x.created_at" },
  cross_checks_all: { sql: "select x.*, o.full_name as original_name, k.full_name as checker_name from cross_checks x left join staff o on o.id=x.original_supervisor left join staff k on k.id=x.checker_id where x.farm_id=$1 order by x.created_at desc limit 200" },
  whistle_reports: { sql: "select * from whistle_reports where farm_id=$1 order by status='MOI' desc, created_at desc limit 200" },
  my_inbox:''',1))
rw("src/app/api/actions/route.ts", lambda s: s.replace('        case "delegate": {', '''        case "cross_check_submit": { const r = await c.query("select submit_cross_check($1::uuid,$2,$3,$4,$5) as j", [b.id, s.staffId, b.result, b.note ?? null, b.evidence_url ?? null]); return { ok: true, ...r.rows[0].j }; }
        case "gen_cross_checks": { if (!["owner","director","auditor","it_engineer"].includes(s.role)) throw new Error("ERR_FORBIDDEN_ROLE"); const a = await c.query("select gen_cross_checks($1) as n", [s.farmId]); const b2 = await c.query("select gen_random_spot_checks($1) as n", [s.farmId]); const c2 = await c.query("select gen_collusion_audits($1) as n", [s.farmId]); return { ok: true, cross: a.rows[0].n, spots: b2.rows[0].n, audits: c2.rows[0].n }; }
        case "whistle": { const r = await c.query("select whistle_submit($1,$2,$3,$4,$5) as id", [s.farmId, b.category ?? "KHAC", b.target_dept ?? null, b.content, s.staffId]); return { ok: true, id: r.rows[0].id }; }
        case "whistle_handle": { if (!["owner","director"].includes(s.role)) throw new Error("ERR_FORBIDDEN_ROLE"); await c.query("update whistle_reports set status=$3, handled_by=$4, handled_at=now(), note=$5 where id=$1 and farm_id=$2", [b.id, s.farmId, b.status, s.staffId, b.note ?? null]); return { ok: true }; }
        case "delegate": {''',1))
rw("src/app/api/jobs/[job]/route.ts", lambda s: s.replace('    if (job === "capa" || (job === "all" && new Date().getDay() === 5)) {', '''    if (job === "anticollusion" || (job === "all" && [1, 4, 5].includes(new Date().getDay()))) { const d = new Date().getDay(); if (d === 1 || job !== "all") { out[`spots:${f}`] = (await adminPool().query("select gen_random_spot_checks($1) as n", [f])).rows[0].n; out[`collusion_audits:${f}`] = (await adminPool().query("select gen_collusion_audits($1) as n", [f])).rows[0].n; } if (d >= 4 || job !== "all") out[`cross_checks:${f}`] = (await adminPool().query("select gen_cross_checks($1) as n", [f])).rows[0].n; }
    if (job === "capa" || (job === "all" && new Date().getDay() === 5)) {''',1))
rw("src/lib/admin.ts", lambda s: s.replace('  { table: "supervision_criteria",', '''  { table: "cross_checks", pk: "id", label: "Giám sát · kiểm chéo mù (máy bốc mẫu)", group: "Nhân sự", farmScoped: true, softDelete: null, writeRoles: ["owner", "director", "it_engineer", "auditor"] },
  { table: "whistle_reports", pk: "id", label: "Phản ánh ẩn danh (chỉ Chủ tịch/TGĐ/GĐ xem)", group: "Nhân sự", farmScoped: true, softDelete: null, writeRoles: ["owner", "director"] },
  { table: "supervision_criteria",''',1))
# GiamSat: tab chong
def gs(s):
    s=s.replace('const [tab, setTab] = useState<"tuan" | "cham" | "tieuchi" | "loi" | "xuhuong" | "nhip">("tuan");','const [tab, setTab] = useState<"tuan" | "cham" | "tieuchi" | "loi" | "xuhuong" | "nhip" | "chong">(typeof window !== "undefined" && new URLSearchParams(window.location.search).get("tab") === "chong" ? "chong" : "tuan");',1)
    s=s.replace('["nhip", "🔁 Nhịp tuần & CAPA · đi ca · chấm ngược"],','["nhip", "🔁 Nhịp tuần & CAPA · đi ca · chấm ngược"], ["chong", "🛡 Chống thông đồng · kiểm chéo mù · phản ánh"],',1)
    s=s.replace('    {tab === "nhip" && <NhipTuan sess={sess} />}','    {tab === "nhip" && <NhipTuan sess={sess} />}\n    {tab === "chong" && <ChongThongDong sess={sess} />}',1)
    s += r'''
/** CHỐNG THÔNG ĐỒNG: máy bốc mẫu · kiểm chéo mù · 8 tín hiệu tự tính · cờ đỏ → tuyến 3 kiểm đột xuất · phản ánh ẩn danh · hậu quả vào bậc */
function ChongThongDong({ sess }: { sess: Sess }) {
  const pairs = useData<R>("collusion_pairs"); const sig = useData<R>("collusion_signals"); const mine = useData<R>("my_cross_checks"); const all = useData<R>("cross_checks_all"); const wb = useData<R>(["owner", "director"].includes(sess.role) ? "whistle_reports" : null);
  const [msg, setMsg] = useState(""); const top = ["owner", "director", "auditor", "it_engineer"].includes(sess.role);
  const LV: Record<string, string> = { DO: "bg-red-100 text-red-900 ring-red-300", VANG: "bg-amber-100 text-amber-900 ring-amber-300", XANH: "bg-emerald-50 text-emerald-900" };
  return <div className="space-y-3">
    <div className="card text-sm"><b>6 lớp chống thông đồng — không phụ thuộc lòng tin</b>
      <ol className="list-decimal ml-5 mt-1 text-slate-700"><li><b>Máy chọn mẫu</b>: mỗi tuần GS phải chấm N mục do máy bốc ngẫu nhiên (ai/cái gì), bắt buộc ảnh — không tự chọn chỗ dễ.</li><li><b>Đối chiếu dữ liệu tự động</b>: chấm ĐẠT cho người mà dữ liệu vận hành báo lỗi → tín hiệu S1.</li><li><b>Kiểm chéo mù</b>: máy bốc 20% mẫu ĐẠT của mỗi GS giao GS khác/audit chấm lại độc lập; lệch → S5, khớp% vào bậc GS.</li><li><b>8 tín hiệu tự tính</b> (chấm quá nhanh, không lỗi bất thường, xác nhận CAPA quá nhanh, không ảnh, kiểm phòng gốc, chấm ngược đổi chác…) → cờ đỏ cặp GS↔phòng.</li><li><b>Cờ đỏ → tuyến 3 kiểm đột xuất</b> (audit/GĐ, không báo trước) + báo Chủ tịch/TGĐ; cờ đỏ chặn lên bậc GS; lỗi lặp trừ trưởng phòng.</li><li><b>Phản ánh ẩn danh</b> lên Chủ tịch/TGĐ từ Tài khoản (không lưu người gửi). Luân chuyển GS theo quý phá vỡ quan hệ lâu ngày; GS bị chặn chấm phòng gốc ngay lúc ghi.</li></ol>
      {top && <button className="btn-secondary !py-1 !text-xs mt-1" onClick={async () => { const j = await act("gen_cross_checks", {}); setMsg(j.error ? String(j.error) : `Máy bốc: ${j.spots} mẫu ngẫu nhiên · ${j.cross} kiểm chéo · ${j.audits} kiểm đột xuất`); pairs.reload(); mine.reload(); all.reload(); }}>🎲 Chạy bốc mẫu / kiểm chéo / cờ đỏ ngay</button>}{msg && <span className="ml-2 text-emerald-800">{msg}</span>}</div>
    {(mine.rows ?? []).length > 0 && <div className="card"><b>Kiểm chéo mù giao cho tôi ({(mine.rows ?? []).length})</b> <span className="text-xs text-slate-500">— chấm ĐỘC LẬP, không hỏi người chấm gốc, không xem kết quả gốc</span>
      <table className="tbl text-sm mt-1"><tbody>{(mine.rows ?? []).map((x) => <tr key={String(x.id)}><td className="pl-3">{String(x.criteria_name ?? x.item)}</td><td>{String(x.target_name ?? x.target_dept ?? "")}</td><td className="text-xs">tuần {fmt.d(x.week_start)}</td><td className="whitespace-nowrap"><button className="btn-primary !py-0.5 !px-2 !text-xs mr-1" onClick={async () => { const n = prompt("Ghi chú (bắt buộc ảnh: dán link ảnh sau dấu | )", ""); if (n === null) return; const [note, ev] = n.split("|"); const j = await act("cross_check_submit", { id: x.id, result: "DAT", note, evidence_url: ev?.trim() || null }); setMsg(j.error ? String(j.error) : "Đã ghi ĐẠT"); mine.reload(); all.reload(); }}>ĐẠT</button><button className="btn-secondary !py-0.5 !px-2 !text-xs !bg-red-50" onClick={async () => { const n = prompt("Mô tả lỗi (bắt buộc ảnh: dán link ảnh sau dấu | )", ""); if (!n) return; const [note, ev] = n.split("|"); const j = await act("cross_check_submit", { id: x.id, result: "LOI", note, evidence_url: ev?.trim() || null }); setMsg(j.error ? String(j.error) : j.mismatch ? "Đã ghi LỖI — LỆCH với chấm gốc, đã báo GĐ" : "Đã ghi LỖI"); mine.reload(); all.reload(); }}>LỖI</button></td></tr>)}</tbody></table></div>}
    <div className="grid md:grid-cols-2 gap-3">
      <div className="card p-0 overflow-auto"><div className="px-3 py-2 bg-slate-100 rounded-t-xl font-bold">Cặp GS ↔ phòng theo mức cảnh báo (8 tuần)</div><table className="tbl text-sm"><thead><tr><th className="pl-3">Giám sát viên</th><th>Phòng</th><th>Mức</th><th className="text-right">Tín hiệu</th><th>Loại</th></tr></thead><tbody>
        {(pairs.rows ?? []).map((p, i) => <tr key={i}><td className="pl-3">{String(p.supervisor_name ?? p.supervisor_id)}</td><td>{String(p.dept ?? "")}</td><td><span className={`px-2 py-0.5 rounded text-xs font-bold ring-1 ${LV[String(p.level)] ?? ""}`}>{p.level === "DO" ? "CỜ ĐỎ" : p.level === "VANG" ? "vàng" : "xanh"}</span></td><td className="text-right">{String(p.n_signals)}</td><td className="text-xs">{((p.signals as string[]) ?? []).map((x) => x.split("_")[0]).join(", ")}</td></tr>)}
        {(pairs.rows ?? []).length === 0 && <tr><td colSpan={5} className="p-3 text-slate-500 text-sm">Không có tín hiệu — sạch.</td></tr>}</tbody></table></div>
      <div className="card p-0 overflow-auto"><div className="px-3 py-2 bg-slate-100 rounded-t-xl font-bold">Tín hiệu chi tiết</div><table className="tbl text-sm"><thead><tr><th className="pl-3">Tuần</th><th>GS</th><th>Phòng</th><th>Tín hiệu</th><th className="text-right">Giá trị</th><th>Mức</th></tr></thead><tbody>
        {(sig.rows ?? []).slice(0, 60).map((r, i) => <tr key={i} className={r.severity === "CAO" ? "bg-red-50" : ""}><td className="pl-3 text-xs">{fmt.d(r.week_start)}</td><td className="text-xs">{String(r.supervisor_name ?? r.supervisor_id)}</td><td className="text-xs">{String(r.dept ?? "")}</td><td className="text-xs">{String(r.label)}</td><td className="text-right">{String(r.value)}</td><td className="text-xs">{String(r.severity)}</td></tr>)}</tbody></table></div>
    </div>
    <div className="card p-0 overflow-auto"><div className="px-3 py-2 bg-slate-100 rounded-t-xl font-bold">Kiểm chéo mù gần đây ({(all.rows ?? []).length}) — lệch = người chấm gốc bị hạ khớp%</div><table className="tbl text-sm"><thead><tr><th className="pl-3">Tuần</th><th>Chấm gốc</th><th>Người kiểm chéo</th><th>Đối tượng</th><th>KQ</th><th>Lệch?</th></tr></thead><tbody>{(all.rows ?? []).slice(0, 40).map((x) => <tr key={String(x.id)} className={x.mismatch ? "bg-red-50" : ""}><td className="pl-3 text-xs">{fmt.d(x.week_start)}</td><td>{String(x.original_name ?? "")}</td><td>{String(x.checker_name ?? "")}</td><td className="text-xs">{String(x.target_dept ?? "")} {String(x.target_staff_id ?? "")}</td><td>{String(x.result ?? x.status)}</td><td>{x.mismatch ? <b className="text-red-700">LỆCH</b> : x.status === "XONG" ? "khớp" : ""}</td></tr>)}</tbody></table></div>
    {wb && <div className="card p-0 overflow-auto"><div className="px-3 py-2 bg-amber-50 rounded-t-xl font-bold">Phản ánh ẩn danh ({(wb.rows ?? []).filter((r) => r.status === "MOI").length} mới) — chỉ Chủ tịch/TGĐ/GĐ thấy; không lưu người gửi</div><table className="tbl text-sm"><thead><tr><th className="pl-3">Lúc</th><th>Loại</th><th>Phòng</th><th>Nội dung</th><th>TT</th><th></th></tr></thead><tbody>{(wb.rows ?? []).map((r) => <tr key={String(r.id)}><td className="pl-3 text-xs">{fmt.dt(r.created_at)}</td><td>{String(r.category)}</td><td>{String(r.target_dept ?? "")}</td><td className="text-sm max-w-lg">{String(r.content)}</td><td className="text-xs">{String(r.status)}</td><td className="whitespace-nowrap">{r.status !== "DA_XU_LY" && <><button className="btn-secondary !py-0.5 !px-2 !text-xs mr-1" onClick={async () => { const n = prompt("Kết luận xử lý"); if (n === null) return; await act("whistle_handle", { id: r.id, status: "DA_XU_LY", note: n }); wb.reload(); }}>Đã xử lý</button><button className="text-xs underline" onClick={async () => { await act("whistle_handle", { id: r.id, status: "BO_QUA", note: "không đủ cơ sở" }); wb.reload(); }}>bỏ qua</button></>}</td></tr>)}</tbody></table></div>}
  </div>;
}
'''
    return s
rw("src/components/panels/GiamSat.tsx", gs)
# TaiKhoan: whistle form
rw("src/components/panels/TaiKhoan.tsx", lambda s: s.replace('    <MyPath sess={sess} />\n','    <MyPath sess={sess} />\n    <Whistle />\n',1).replace('export default function TaiKhoan(', '''function Whistle() {
  const [open, setOpen] = useState(false); const [cat, setCat] = useState("BAO_CHE"); const [dept, setDept] = useState(""); const [txt, setTxt] = useState(""); const [m, setM] = useState("");
  if (!open) return <div className="text-xs text-slate-500">🛡 Thấy bao che, gian dối, lười biếng, mất an toàn? <button className="underline" onClick={() => setOpen(true)}>Phản ánh ẩn danh tới Chủ tịch/TGĐ</button> — hệ thống KHÔNG lưu người gửi.</div>;
  return <div className="card text-sm space-y-2"><b>🛡 Phản ánh ẩn danh</b> <span className="text-xs text-slate-500">— chỉ Chủ tịch/TGĐ/GĐ đọc; không lưu tên/ID người gửi (chỉ băm chống spam, tối đa 5 lượt/tuần)</span>
    <div className="flex gap-2 flex-wrap"><select className="input !py-1" value={cat} onChange={(e) => setCat(e.target.value)}>{[["BAO_CHE", "Bao che / bỏ qua lỗi"], ["GIAN_DOI", "Gian dối số liệu"], ["LUOI", "Lười / bỏ việc"], ["AN_TOAN", "Mất an toàn / dịch bệnh"], ["THAM_NHUNG", "Ăn chặn / thông đồng NCC"], ["KHAC", "Khác"]].map(([k, l]) => <option key={k} value={k}>{l}</option>)}</select><input className="input !py-1" placeholder="Phòng liên quan (tùy chọn)" value={dept} onChange={(e) => setDept(e.target.value)} /></div>
    <textarea className="input w-full" rows={3} placeholder="Chuyện gì, ở đâu, khi nào, ai — càng cụ thể càng dễ xác minh" value={txt} onChange={(e) => setTxt(e.target.value)} />
    <div className="flex gap-2 items-center"><button className="btn-primary !py-1" disabled={txt.length < 10} onClick={async () => { const j = await act("whistle", { category: cat, target_dept: dept || null, content: txt }); setM(j.error ? String(j.error) : "Đã gửi ẩn danh. Cảm ơn bạn."); setTxt(""); }}>Gửi ẩn danh</button><button className="btn-secondary !py-1" onClick={() => setOpen(false)}>Đóng</button><span className="text-xs">{m}</span></div></div>;
}
export default function TaiKhoan(''',1))
