import io, os
R="F:/ITRAN FARM/itran-os/"
def rw(p, fn): s=io.open(R+p,encoding="utf-8").read(); n=fn(s); assert n!=s, p; io.open(R+p,"w",encoding="utf-8",newline="\n").write(n); print("ok",p)
# events: bin_id
rw("src/lib/events.ts", lambda s: s.replace("    reason: z.string(), from_to: z.string().nullable().optional(), weigh_point: z.string().nullable().optional(), ref_type: z.string().nullable().optional(), ref_id: z.string().nullable().optional(),",
 "    reason: z.string(), from_to: z.string().nullable().optional(), weigh_point: z.string().nullable().optional(), ref_type: z.string().nullable().optional(), ref_id: z.string().nullable().optional(), bin_id: z.string().nullable().optional(), to_bin_id: z.string().nullable().optional(),",1))
# forms: Ref.bins optional + bin field
def fm(s):
    s=s.replace("animals: Record<string, unknown>[]; groups: Record<string, unknown>[]; warehouses: Record<string, unknown>[]; products: Record<string, unknown>[];","animals: Record<string, unknown>[]; groups: Record<string, unknown>[]; warehouses: Record<string, unknown>[]; products: Record<string, unknown>[]; bins?: Record<string, unknown>[];",1)
    s=s.replace('const whOpts = (r: Ref, codes?: string[]): Option[] =>','const binOpts = (r: Ref): Option[] => (r.bins ?? []).map((b) => ({ id: s(b.id), label: `${s(b.warehouse_code)} · ${s(b.code)}`, sub: s(b.zone) }));\nconst whOpts = (r: Ref, codes?: string[]): Option[] =>',1)
    s=s.replace('''        { key: "lot_no", label: "Số lô (NCC / mẻ)", type: "text", required: true, placeholder: "R2608-03" },''','''        { key: "lot_no", label: "Số lô (NCC / mẻ)", type: "text", required: true, placeholder: "R2608-03" },
        { key: "bin_id", label: "Vị trí bin (kệ/pallet)", type: "choice", options: binOpts(r) },''',1)
    i=s.index("    stock_out: {"); j=s.index('{ key: "qty", label: "Số lượng", type: "number", min: 0, step: 1, required: true },', i)
    s=s[:j]+'{ key: "qty", label: "Số lượng", type: "number", min: 0, step: 1, required: true },\n        { key: "bin_id", label: "Lấy từ bin", type: "choice", options: binOpts(r) },'+s[j+len('{ key: "qty", label: "Số lượng", type: "number", min: 0, step: 1, required: true },'):]
    return s
rw("src/lib/forms.ts", fm)
# queries
rw("src/lib/queries.ts", lambda s: s.replace("  bom_headers: {", '''  bins: { sql: "select b.*, w.code as warehouse_code, w.name as warehouse_name, (select coalesce(sum(qty),0) from v_bin_stock s where s.bin_id=b.id) as qty, (select count(distinct sku) from v_bin_stock s where s.bin_id=b.id) as skus from bins b join warehouses w on w.id=b.warehouse_id where b.farm_id=$1 and b.active order by w.code, b.pick_seq, b.code" },
  bin_stock: { sql: "select * from v_bin_stock where farm_id=$1 order by warehouse_code, pick_seq, bin_code, expiry_date" },
  putaway: { sql: "select * from suggest_putaway($1, $2, $3, coalesce($4::numeric, 1))", params: ["wh", "sku", "qty"] },
  picking_bins: { sql: "select * from v_picking_bins where farm_id=$1 order by order_id, pick_seq" },
  replenishment: { sql: "select * from v_replenishment where farm_id=$1 order by suggest_qty desc, sku" },
  abc_suggest: { sql: "select a.*, p.name as product_name from v_abc_suggest a join products p on p.sku=a.sku where a.farm_id=$1 order by a.val desc" },
  cold_chain: { sql: "select * from v_cold_chain where farm_id=$1 order by code" },
  cold_temps: { sql: "select s.ts, s.value, s.device_id from sensor_reads s join warehouses w on w.temp_device_id=s.device_id and w.farm_id=s.farm_id where s.farm_id=$1 and s.metric in ('temp','temp_c','temperature') and s.ts>now()-interval '48 hours' order by s.ts" },
  vehicles: { sql: "select v.*, s.full_name as driver_name from vehicles v left join staff s on s.id=v.driver_id where v.farm_id=$1 and v.active order by v.plate" },
  trips: { sql: "select * from v_trips where farm_id=$1 order by coalesce(planned_at, created_at) desc limit 200" },
  trip_stops: { sql: "select ts.*, p.name as partner_name from trip_stops ts left join partners p on p.id=ts.partner_id where ts.trip_id=$2 order by ts.seq", params: ["trip"] },
  supplier_scorecard: { sql: "select * from v_supplier_scorecard where farm_id=$1 or farm_id is null order by score desc nulls last" },
  stock_card: { sql: "select * from v_stock_card where farm_id=$1 and sku=$2 order by ts desc limit 500", params: ["sku"] },
  cycle_count_tasks: { sql: "select * from tasks where farm_id=$1 and kind='KIEM_KE_CHU_KY' and status='MO' order by due_at" },
  bom_headers: {''',1))
# admin
rw("src/lib/admin.ts", lambda s: s.replace('  { table: "bom_headers", pk: "id",', '''  { table: "bins", pk: "id", label: "Kho · vị trí bin (kệ/tầng/ô/pallet)", group: "Kho", farmScoped: true, softDelete: "active", writeRoles: OPS, codePrefix: "BIN" },
  { table: "stock_policies", pk: "id", label: "Kho · chính sách tồn (ROP/min-max/ngày, ABC, chu kỳ kiểm kê)", group: "Kho", farmScoped: true, softDelete: "active", writeRoles: OPS, codePrefix: "SP" },
  { table: "vehicles", pk: "id", label: "Vận tải · đội xe", group: "Kho", farmScoped: true, softDelete: "active", writeRoles: OPS, codePrefix: "XE" },
  { table: "trips", pk: "id", label: "Vận tải · chuyến xe", group: "Kho", farmScoped: true, softDelete: "status", writeRoles: [...OPS, "worker"], codePrefix: "TRIP" },
  { table: "trip_stops", pk: "id", label: "Vận tải · điểm giao/nhận (POD)", group: "Kho", farmScoped: false, softDelete: null, writeRoles: [...OPS, "worker"], codePrefix: "STOP" },
  { table: "bom_headers", pk: "id",''',1))
# jobs: gen_cycle_counts
rw("src/app/api/jobs/[job]/route.ts", lambda s: s.replace('out[`compliance:${f}`] = (await adminPool().query("select gen_compliance_tasks($1) as n", [f])).rows[0].n;','out[`compliance:${f}`] = (await adminPool().query("select gen_compliance_tasks($1) as n", [f])).rows[0].n; out[`cyclecount:${f}`] = (await adminPool().query("select gen_cycle_counts($1) as n", [f])).rows[0].n;',1))
# KhoPanel
def kp(s):
    s=s.replace('devices = useData("devices"), partners = useData("partners");','devices = useData("devices"), partners = useData("partners"), bins = useData("bins"); const binStock = useData("bin_stock"); const repl = useData("replenishment"); const abc = useData("abc_suggest"); const cold = useData("cold_chain"); const vehicles = useData("vehicles"); const trips = useData("trips"); const [tripSel, setTripSel] = useState<string | null>(null); const stops = useData(tripSel ? "trip_stops" : null, { trip: tripSel ?? undefined }, [tripSel]); const score = useData("supplier_scorecard"); const cct = useData("cycle_count_tasks"); const pkb = useData("picking_bins"); const [pw, setPw] = useState<R>({}); const put = useData(pw.wh && pw.sku ? "putaway" : null, { wh: String(pw.wh ?? ""), sku: String(pw.sku ?? ""), qty: String(pw.qty ?? "1") }, [pw.wh, pw.sku, pw.qty]); const [cardSku, setCardSku] = useState<string | null>(null); const card = useData(cardSku ? "stock_card" : null, { sku: cardSku ?? undefined }, [cardSku]); const [trF, setTrF] = useState<R>({ kind: "GIAO_HANG" }); const [msg2, setMsg2] = useState("");',1)
    s=s.replace('useState<"ton" | "ghi" | "kiemke" | "so" | "bieudo">("ton")','useState<"ton" | "ghi" | "kiemke" | "so" | "bin" | "rop" | "lanh" | "van" | "ncc" | "the" | "bieudo">((typeof window !== "undefined" && (new URLSearchParams(window.location.search).get("tab") as "ton" | null)) || "ton")',1)
    s=s.replace('{ animals: animals.rows, groups: groups.rows, warehouses: warehouses.rows, products: products.rows, plots: plots.rows, recipes: recipes.rows, locations: locations.rows, sops: sops.rows, devices: devices.rows, partners: partners.rows } : null, [animals.rows, groups.rows, warehouses.rows, products.rows, plots.rows, recipes.rows, locations.rows, sops.rows, devices.rows, partners.rows]);',
                '{ animals: animals.rows, groups: groups.rows, warehouses: warehouses.rows, products: products.rows, plots: plots.rows, recipes: recipes.rows, locations: locations.rows, sops: sops.rows, devices: devices.rows, partners: partners.rows, bins: bins.rows ?? [] } : null, [animals.rows, groups.rows, warehouses.rows, products.rows, plots.rows, recipes.rows, locations.rows, sops.rows, devices.rows, partners.rows, bins.rows]);',1)
    s=s.replace('["so", "Ngày-tồn nguyên liệu"], ["bieudo", "📈 Biểu đồ kho"]','["so", "Ngày-tồn nguyên liệu"], ["bin", `📍 Vị trí bin (${(bins.rows ?? []).length})`], ["rop", `🔁 Bổ sung ROP (${(repl.rows ?? []).filter((r) => Number(r.suggest_qty) > 0).length})`], ["lanh", "❄ Kho lạnh"], ["van", `🚚 Vận tải (${(trips.rows ?? []).filter((t) => t.status !== "XONG" && t.status !== "HUY").length})`], ["ncc", "⭐ NCC scorecard"], ["the", "📒 Thẻ kho theo lô"], ["bieudo", "📈 Biểu đồ kho"]',1)
    old='      {tab === "so" && (<div className="space-y-3">'
    new='''      {tab === "bin" && <div className="space-y-3">
        <div className="card p-0 overflow-auto"><div className="px-3 py-2 bg-stone-100 rounded-t-2xl font-bold flex items-center gap-2 flex-wrap">Vị trí bin: kho → khu → dãy → kệ → tầng → ô; sức chứa, dải nhiệt, thứ tự pick <a className="ml-auto underline text-sm font-normal" href="/quan-tri?t=bins">＋ bin</a></div><table className="tbl text-sm"><thead><tr><th className="pl-3">Kho</th><th>Bin</th><th>Khu/dãy/kệ/tầng</th><th>Loại</th><th className="text-right">Sức chứa kg</th><th className="text-right">Đang chứa</th><th className="text-right">SKU</th><th>Nhiệt</th><th className="text-right">Pick #</th></tr></thead><tbody>{(bins.rows ?? []).map((b) => { const full = b.capacity_kg ? Number(b.qty) / Number(b.capacity_kg) : 0; return <tr key={String(b.id)} className={full > 0.9 ? "bg-amber-50" : ""}><td className="pl-3">{String(b.warehouse_code)}</td><td className="font-mono">{String(b.code)}</td><td className="text-xs">{[b.zone, b.aisle, b.rack, b.level, b.position].filter(Boolean).join(" / ")}</td><td>{String(b.kind)}</td><td className="text-right">{String(b.capacity_kg ?? "")}</td><td className="text-right">{fmt.n(Number(b.qty))} {b.capacity_kg ? <span className="text-xs text-stone-500">({Math.round(full * 100)}%)</span> : null}</td><td className="text-right">{String(b.skus)}</td><td className="text-xs">{b.temp_min != null ? `${b.temp_min}–${b.temp_max}°C` : ""}</td><td className="text-right">{String(b.pick_seq)}</td></tr>; })}</tbody></table></div>
        <div className="grid lg:grid-cols-2 gap-3"><div className="card"><b>Gợi ý putaway (xếp hàng vào bin)</b> — cùng SKU → bin trống → còn chỗ; theo loại hàng cho phép & sức chứa<div className="flex gap-2 mt-2 flex-wrap"><select className="input !w-40" value={String(pw.wh ?? "")} onChange={(e) => setPw({ ...pw, wh: e.target.value })}><option value="">Kho</option>{(warehouses.rows ?? []).map((w) => <option key={String(w.id)} value={String(w.id)}>{String(w.code)} {String(w.name)}</option>)}</select><select className="input !w-56" value={String(pw.sku ?? "")} onChange={(e) => setPw({ ...pw, sku: e.target.value })}><option value="">Mặt hàng</option>{(products.rows ?? []).map((p) => <option key={String(p.sku)} value={String(p.sku)}>{String(p.name)}</option>)}</select><input className="input !w-24" type="number" placeholder="kg" value={String(pw.qty ?? "")} onChange={(e) => setPw({ ...pw, qty: e.target.value })} /></div><table className="tbl text-sm mt-2"><tbody>{(put.rows ?? []).map((r) => <tr key={String(r.bin_id)}><td className="font-mono">{String(r.bin_code)}</td><td>{String(r.reason)}</td><td className="text-right">còn {fmt.n(Number(r.free_kg))} kg</td></tr>)}</tbody></table>{pw.wh && pw.sku && !(put.rows ?? []).length && <div className="text-sm text-stone-500 mt-1">Không có bin phù hợp (hết chỗ / kho chưa khai bin).</div>}</div>
          <div className="card p-0 overflow-auto"><div className="px-3 py-2 bg-stone-100 rounded-t-2xl font-bold">Tồn theo bin & lô (FEFO)</div><table className="tbl text-sm"><thead><tr><th className="pl-3">Kho</th><th>Bin</th><th>SKU</th><th>Lô</th><th>HSD</th><th className="text-right">Tồn</th></tr></thead><tbody>{(binStock.rows ?? []).slice(0, 200).map((r, i) => <tr key={i} className={!r.bin_id ? "text-stone-400" : ""}><td className="pl-3">{String(r.warehouse_code)}</td><td className="font-mono">{String(r.bin_code ?? "— chưa gán bin")}</td><td>{String(r.product_name)}</td><td className="font-mono text-xs">{String(r.lot_id ?? "")}</td><td>{r.expiry_date ? fmt.d(String(r.expiry_date)) : ""}</td><td className="text-right">{fmt.n(Number(r.qty))}</td></tr>)}</tbody></table></div></div>
        <div className="card p-0 overflow-auto"><div className="px-3 py-2 bg-stone-100 rounded-t-2xl font-bold">Phiếu soạn theo bin (đơn đã giữ chỗ FEFO → bin có lô, thứ tự đường đi)</div><table className="tbl text-sm"><thead><tr><th className="pl-3">Đơn</th><th>Khách</th><th>SKU</th><th>Lô</th><th>Bin</th><th className="text-right">Pick #</th><th className="text-right">SL</th></tr></thead><tbody>{(pkb.rows ?? []).map((r, i) => <tr key={i}><td className="pl-3 font-mono text-xs">{String(r.order_id)}</td><td>{String(r.partner_name ?? "")}</td><td>{String(r.product_name)}</td><td className="font-mono text-xs">{String(r.lot_id ?? "")}</td><td className="font-mono">{String(r.bin_code ?? "—")}</td><td className="text-right">{String(r.pick_seq ?? "")}</td><td className="text-right">{fmt.n(Number(r.qty))}</td></tr>)}</tbody></table>{!(pkb.rows ?? []).length && <div className="p-3 text-sm text-stone-500">Không có đơn đang giữ chỗ.</div>}</div></div>}
      {tab === "rop" && <div className="space-y-3">
        <div className="card p-0 overflow-auto"><div className="px-3 py-2 bg-stone-100 rounded-t-2xl font-bold flex items-center gap-2 flex-wrap">Bổ sung tồn: ROP / min–max / theo ngày-tồn → số lượng gợi ý đặt (MOQ, lead time, NCC ưu tiên) — cảnh báo AL-ROP hàng ngày <a className="ml-auto underline text-sm font-normal" href="/quan-tri?t=stock_policies">＋ chính sách</a></div><table className="tbl text-sm"><thead><tr><th className="pl-3">SKU</th><th>PP</th><th className="text-right">Tồn KD</th><th className="text-right">Dùng/ngày</th><th className="text-right">Ngày tồn</th><th className="text-right">ROP/min</th><th className="text-right">Max</th><th className="text-right">Lead</th><th>ABC</th><th className="text-right">Gợi ý đặt</th><th>NCC</th><th></th></tr></thead><tbody>{(repl.rows ?? []).map((r) => <tr key={String(r.sku)} className={Number(r.suggest_qty) > 0 ? "bg-red-50" : ""}><td className="pl-3">{String(r.product_name)} <span className="font-mono text-xs text-stone-500">{String(r.sku)}</span></td><td>{String(r.method)}</td><td className="text-right">{fmt.n(Number(r.available))}</td><td className="text-right">{r.use_per_day ? fmt.n(Number(r.use_per_day)) : ""}</td><td className="text-right">{r.days ? fmt.n(Number(r.days)) : ""}</td><td className="text-right">{String(r.rop_qty ?? r.min_qty ?? r.min_days ?? "")}</td><td className="text-right">{String(r.max_qty ?? "")}</td><td className="text-right">{String(r.lead_time_days)}d</td><td>{String(r.abc_class ?? "")}</td><td className={`text-right font-bold ${Number(r.suggest_qty) > 0 ? "text-red-700" : ""}`}>{fmt.n(Number(r.suggest_qty))}</td><td className="text-xs">{String(r.supplier_name ?? "")}</td><td className="text-xs">{Number(r.suggest_qty) > 0 && <a className="underline" href={`/ktt?tab=po&sku=${r.sku}&qty=${Math.round(Number(r.suggest_qty))}&supplier=${r.preferred_supplier_id ?? ""}`}>tạo PO</a>}</td></tr>)}</tbody></table></div>
        <div className="grid lg:grid-cols-2 gap-3"><div className="card p-0 overflow-auto"><div className="px-3 py-2 bg-stone-100 rounded-t-2xl font-bold">Phân loại ABC theo giá trị xuất 90 ngày (A ≤80% · B ≤95% · C còn lại) → điền vào chính sách</div><table className="tbl text-sm"><thead><tr><th className="pl-3">SKU</th><th className="text-right">Giá trị xuất</th><th className="text-right">Lũy kế %</th><th>ABC</th></tr></thead><tbody>{(abc.rows ?? []).slice(0, 40).map((r) => <tr key={String(r.sku)}><td className="pl-3">{String(r.product_name)}</td><td className="text-right">{fmt.vnd(Number(r.val))}</td><td className="text-right">{String(r.cum_pct)}</td><td className="font-bold">{String(r.abc)}</td></tr>)}</tbody></table></div>
          <div className="card p-0 overflow-auto"><div className="px-3 py-2 bg-stone-100 rounded-t-2xl font-bold">Kiểm kê chu kỳ (A 30 ngày · B 90 · C 180) — việc tự sinh trong job đêm</div><table className="tbl text-sm"><thead><tr><th className="pl-3">Việc</th><th>Hạn</th><th>Vai</th></tr></thead><tbody>{(cct.rows ?? []).map((t) => <tr key={String(t.id)}><td className="pl-3">{String(t.title)}</td><td>{fmt.dt(String(t.due_at))}</td><td>{String(t.role_hint ?? "")}</td></tr>)}</tbody></table>{!(cct.rows ?? []).length && <div className="p-3 text-sm text-stone-500">Không có việc kiểm kê mở — ghi kiểm kê ở tab Kiểm kê.</div>}</div></div></div>}
      {tab === "lanh" && <div className="space-y-3"><div className="card p-0 overflow-auto"><div className="px-3 py-2 bg-stone-100 rounded-t-2xl font-bold">Kho lạnh — dải nhiệt, thiết bị đo (sensor_reads), lệch dải 24h → cảnh báo AL-COLD (ĐỎ) · gán thiết bị: <a className="underline" href="/quan-tri?t=warehouses">warehouses.temp_device_id</a></div><table className="tbl text-sm"><thead><tr><th className="pl-3">Kho</th><th>Dải</th><th>Thiết bị</th><th className="text-right">Nhiệt hiện tại</th><th>Lúc</th><th className="text-right">Lệch 24h</th></tr></thead><tbody>{(cold.rows ?? []).map((r) => { const bad = r.last_temp != null && (Number(r.last_temp) < Number(r.temp_min) || Number(r.last_temp) > Number(r.temp_max)); return <tr key={String(r.warehouse_id)} className={bad ? "bg-red-50" : ""}><td className="pl-3">{String(r.code)} {String(r.name)}</td><td>{String(r.temp_min)}–{String(r.temp_max)}°C</td><td className="font-mono text-xs">{String(r.temp_device_id ?? "chưa gán")}</td><td className={`text-right font-bold ${bad ? "text-red-700" : ""}`}>{r.last_temp != null ? `${r.last_temp}°C` : "—"}</td><td className="text-xs">{r.last_ts ? fmt.dt(String(r.last_ts)) : ""}</td><td className="text-right">{String(r.excursions_24h)}</td></tr>; })}</tbody></table></div><div className="card"><AnyChart title="Nhiệt độ cảm biến (°C) — chọn thiết bị kho lạnh" table="sensor_reads" col="value" dim="device_id" bucket="day" agg="avg" height={240} /></div><div className="text-xs text-stone-500">Bin loại LANH/DONG có dải riêng (2–8°C / −20…−15°C). Xe lạnh ghi nhiệt lúc giao ở điểm dừng (temp_at_delivery) — chuỗi lạnh liền mạch kho → xe → khách.</div></div>}
      {tab === "van" && <div className="space-y-3">
        <div className="grid lg:grid-cols-3 gap-3"><div className="card p-0 overflow-auto lg:col-span-1"><div className="px-3 py-2 bg-stone-100 rounded-t-2xl font-bold flex items-center gap-2">Đội xe <a className="ml-auto underline text-sm font-normal" href="/quan-tri?t=vehicles">＋ xe</a></div><table className="tbl text-sm"><thead><tr><th className="pl-3">Biển</th><th>Loại</th><th className="text-right">Tải kg</th><th>Lạnh</th><th>Đăng kiểm</th><th>BH</th></tr></thead><tbody>{(vehicles.rows ?? []).map((v) => <tr key={String(v.id)}><td className="pl-3 font-mono">{String(v.plate)}</td><td>{String(v.kind)}</td><td className="text-right">{String(v.capacity_kg ?? "")}</td><td>{v.refrigerated ? `❄ ${v.temp_min}–${v.temp_max}°C` : ""}</td><td className="text-xs">{String(v.inspection_due ?? "")}</td><td className="text-xs">{String(v.insurance_due ?? "")}</td></tr>)}</tbody></table></div>
          <div className="card lg:col-span-2"><b>Tạo chuyến</b><div className="grid sm:grid-cols-3 lg:grid-cols-5 gap-2 mt-2"><select className="input" value={String(trF.vehicle_id ?? "")} onChange={(e) => setTrF({ ...trF, vehicle_id: e.target.value })}><option value="">Xe</option>{(vehicles.rows ?? []).map((v) => <option key={String(v.id)} value={String(v.id)}>{String(v.plate)}</option>)}</select><select className="input" value={String(trF.kind)} onChange={(e) => setTrF({ ...trF, kind: e.target.value })}>{[["GIAO_HANG", "Giao hàng"], ["THU_MUA", "Thu mua"], ["NOI_BO", "Nội bộ"], ["KHAC", "Khác"]].map(([k, l]) => <option key={k} value={k}>{l}</option>)}</select><input className="input" type="datetime-local" value={String(trF.planned_at ?? "")} onChange={(e) => setTrF({ ...trF, planned_at: e.target.value })} /><input className="input" placeholder="Tuyến / ghi chú" value={String(trF.route_note ?? "")} onChange={(e) => setTrF({ ...trF, route_note: e.target.value })} /><button className="btn-primary !py-2" disabled={!trF.vehicle_id} onClick={async () => { const j = await fetch("/api/admin/trips", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ row: { ...trF, driver_id: sess.staffId, cold_chain: !!(vehicles.rows ?? []).find((v) => v.id === trF.vehicle_id)?.refrigerated } }) }).then((r) => r.json()); setMsg2(j.ok ? "Đã tạo chuyến — thêm điểm dừng ở Quản trị DL › trip_stops hoặc bấm chuyến" : `${j.error}: ${j.detail ?? ""}`); trips.reload(); }}>Tạo</button></div>{msg2 && <div className="text-sm mt-1 text-emerald-700">{msg2}</div>}
            <table className="tbl text-sm mt-2"><thead><tr><th className="pl-3">Chuyến</th><th>Xe</th><th>Tài xế</th><th>Loại</th><th>KH</th><th className="text-right">Điểm</th><th className="text-right">Đã giao</th><th className="text-right">km</th><th className="text-right">L/100</th><th>TT</th><th></th></tr></thead><tbody>{(trips.rows ?? []).map((t) => <tr key={String(t.id)} className={tripSel === t.id ? "bg-emerald-50" : ""}><td className="pl-3 font-mono text-xs"><button className="underline" onClick={() => setTripSel(String(t.id))}>{String(t.id)}</button></td><td>{String(t.plate ?? "")}{t.refrigerated ? " ❄" : ""}</td><td>{String(t.driver_name ?? "")}</td><td>{String(t.kind)}</td><td className="text-xs">{t.planned_at ? fmt.dt(String(t.planned_at)) : ""}</td><td className="text-right">{String(t.stops)}</td><td className="text-right">{String(t.delivered)}</td><td className="text-right">{String(t.km ?? "")}</td><td className="text-right">{String(t.l_per_100km ?? "")}</td><td>{String(t.status)}</td><td className="text-xs whitespace-nowrap">{t.status === "KE_HOACH" && <button className="underline mr-2" onClick={async () => { await fetch("/api/admin/trips", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ row: { id: t.id, status: "DANG_DI", depart_at: new Date().toISOString() } }) }); trips.reload(); }}>▶ xuất phát</button>}{t.status === "DANG_DI" && <button className="underline mr-2" onClick={async () => { const km = prompt("Odometer về (km)?"); const fuel = prompt("Nhiên liệu (lít)?"); await fetch("/api/admin/trips", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ row: { id: t.id, status: "XONG", return_at: new Date().toISOString(), odometer_end: km ? Number(km) : null, fuel_l: fuel ? Number(fuel) : null } }) }); trips.reload(); }}>✓ về</button>}<a className="underline" href={`/quan-tri?t=trip_stops`}>＋ điểm</a></td></tr>)}</tbody></table>
            {tripSel && <div className="mt-2 rounded-xl bg-stone-50 p-2"><b>Điểm dừng chuyến {tripSel}</b><table className="tbl text-sm"><thead><tr><th>#</th><th>Khách</th><th>Đơn</th><th>Địa chỉ</th><th className="text-right">kg</th><th>Đến</th><th>Nhiệt giao</th><th>POD</th><th>TT</th><th></th></tr></thead><tbody>{(stops.rows ?? []).map((st) => <tr key={String(st.id)}><td>{String(st.seq)}</td><td>{String(st.partner_name ?? "")}</td><td className="font-mono text-xs">{String(st.order_id ?? "")}</td><td className="text-xs">{String(st.address ?? "")}</td><td className="text-right">{String(st.qty_kg ?? "")}</td><td className="text-xs">{st.arrived_at ? fmt.dt(String(st.arrived_at)) : ""}</td><td>{st.temp_at_delivery != null ? `${st.temp_at_delivery}°C` : ""}</td><td>{st.pod_url ? <a className="underline" href={String(st.pod_url)}>ảnh</a> : ""}</td><td>{String(st.status)}</td><td className="text-xs">{st.status === "CHO" && <button className="underline" onClick={async () => { const temp = prompt("Nhiệt độ hàng lúc giao (°C, để trống nếu không lạnh)"); await fetch("/api/admin/trip_stops", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ row: { id: st.id, status: "DA_GIAO", arrived_at: new Date().toISOString(), left_at: new Date().toISOString(), temp_at_delivery: temp ? Number(temp) : null, pod_by: sess.staffId } }) }); stops.reload(); trips.reload(); }}>✓ đã giao (POD)</button>}</td></tr>)}</tbody></table>{!(stops.rows ?? []).length && <div className="text-sm text-stone-500">Chưa có điểm dừng.</div>}</div>}</div></div></div>}
      {tab === "ncc" && <div className="card p-0 overflow-auto"><div className="px-3 py-2 bg-stone-100 rounded-t-2xl font-bold">Scorecard nhà cung cấp 12 tháng — đúng hạn 30 · đủ đơn 20 · có COA 25 · QC đạt 25 (điểm/100); NCC phê duyệt & hạn rà soát (ISO22000/GlobalG.A.P: NCC được phê duyệt)</div><table className="tbl text-sm"><thead><tr><th className="pl-3">NCC</th><th>Duyệt</th><th>Rà soát</th><th className="text-right">PO</th><th className="text-right">Chi</th><th className="text-right">Đúng hạn %</th><th className="text-right">Đủ đơn %</th><th className="text-right">Lô</th><th className="text-right">COA %</th><th className="text-right">QC đạt %</th><th className="text-right">Điểm</th></tr></thead><tbody>{(score.rows ?? []).map((r) => <tr key={String(r.supplier_id)} className={Number(r.score) < 60 ? "bg-red-50" : Number(r.score) >= 85 ? "bg-emerald-50" : ""}><td className="pl-3">{String(r.name)}</td><td>{r.approved ? "✓" : <span className="text-red-700">chưa</span>}</td><td className="text-xs">{String(r.review_due ?? "")}</td><td className="text-right">{String(r.n_po ?? 0)}</td><td className="text-right">{fmt.vnd(Number(r.spend ?? 0))}</td><td className="text-right">{String(r.on_time_pct ?? "—")}</td><td className="text-right">{String(r.fulfilled_pct ?? "—")}</td><td className="text-right">{String(r.n_lots ?? 0)}</td><td className="text-right">{String(r.coa_pct ?? "—")}</td><td className="text-right">{String(r.qc_pass_pct ?? "—")}</td><td className="text-right font-bold">{String(r.score)}</td></tr>)}</tbody></table><div className="p-2 text-xs text-stone-500">Đúng hạn cần điền purchase_orders.expected_at & received_at khi nhận hàng (form nhận PO ở KTT).</div></div>}
      {tab === "the" && <div className="card p-0 overflow-auto"><div className="px-3 py-2 bg-stone-100 rounded-t-2xl font-bold flex items-center gap-2">Thẻ kho theo lô (số dư lũy kế từng lô) <select className="input !w-72 !py-1 font-normal" value={cardSku ?? ""} onChange={(e) => setCardSku(e.target.value || null)}><option value="">Chọn mặt hàng</option>{(products.rows ?? []).map((p) => <option key={String(p.sku)} value={String(p.sku)}>{String(p.name)}</option>)}</select>{cardSku && <a className="ml-auto underline text-sm font-normal" href={`/api/exports/stock-card?sku=${cardSku}`}>xuất CSV</a>}</div><table className="tbl text-sm"><thead><tr><th className="pl-3">Lúc</th><th>Kho</th><th>Lô</th><th>Bin</th><th>Lý do</th><th>Đối tác/nơi</th><th className="text-right">Nhập</th><th className="text-right">Xuất</th><th className="text-right">Đơn giá</th><th className="text-right">Số dư lô</th><th>Người</th></tr></thead><tbody>{(card.rows ?? []).map((r, i) => <tr key={i}><td className="pl-3 text-xs">{fmt.dt(String(r.ts))}</td><td>{String(r.warehouse_code)}</td><td className="font-mono text-xs">{String(r.lot_id ?? "")}</td><td className="font-mono text-xs">{String(r.bin_id ?? "")}</td><td>{String(r.reason)}</td><td className="text-xs">{String(r.from_to ?? "")}</td><td className="text-right">{Number(r.direction) === 1 ? fmt.n(Number(r.qty)) : ""}</td><td className="text-right">{Number(r.direction) === -1 ? fmt.n(Number(r.qty)) : ""}</td><td className="text-right">{r.unit_cost ? fmt.vnd(Number(r.unit_cost)) : ""}</td><td className="text-right font-bold">{fmt.n(Number(r.balance))}</td><td className="text-xs">{String(r.created_by ?? "")}</td></tr>)}</tbody></table>{!cardSku && <div className="p-3 text-sm text-stone-500">Chọn mặt hàng để xem thẻ kho.</div>}</div>}
      {tab === "so" && (<div className="space-y-3">'''
    assert old in s; s=s.replace(old,new,1)
    return s
rw("src/components/panels/KhoPanel.tsx", kp)
# export stock-card csv
rw("src/app/api/exports/[kind]/route.ts", lambda s: s.replace('        case "recon": return csvRes(', '''        case "stock-card": return csvRes(`the-kho-${sku ?? "all"}-${farm}.csv`, await q("select * from v_stock_card where farm_id=$1 and ($2::text is null or sku=$2) and ts::date between $3 and $4 order by sku, lot_id, ts", [farm, sku, from, to]));
        case "recon": return csvRes(''',1))
