import io, os
R="F:/ITRAN FARM/itran-os/"
def w(p, s): os.makedirs(os.path.dirname(R+p) or R, exist_ok=True); io.open(R+p,"w",encoding="utf-8",newline="\n").write(s); print("w",p)
def rw(p, fn): s=io.open(R+p,encoding="utf-8").read(); n=fn(s); assert n!=s, p; io.open(R+p,"w",encoding="utf-8",newline="\n").write(n); print("ok",p)
rw("src/lib/queries.ts", lambda s: s.replace("  plan_scenarios: {", '''  stock_dashboard: { sql: "select * from v_stock_dashboard where farm_id=$1 order by block, case flag when 'HET' then 0 when 'THIEU_SOM' then 1 when 'CHAM_ROP' then 2 when 'AM_30_NGAY' then 3 else 9 end, days_left nulls last" },
  warehouse_fill: { sql: "select * from v_warehouse_fill where farm_id=$1 order by block, code" },
  tool_stock: { sql: "select * from v_tool_stock where farm_id=$1 order by warehouse_code, tool_group, name" },
  tool_issued: { sql: "select * from v_tool_issued where farm_id=$1 order by overdue desc, issued_at desc" },
  tool_catalog: { sql: "select sku, name, unit, tool_group, life_months, ref_price, needs_cert from products where kind='CONG_CU' and active order by tool_group, name" },
  tool_history: { sql: "select t.*, p.name as tool_name, s.full_name as staff_name from tool_issues t join products p on p.sku=t.sku left join staff s on s.id=t.staff_id where t.farm_id=$1 order by t.issued_at desc limit 200" },
  plan_scenarios: {''',1))
rw("src/lib/admin.ts", lambda s: s.replace('  { table: "plan_scenarios", pk: "id",', '''  { table: "tool_issues", pk: "id", label: "Công cụ · cấp phát / thu hồi / hỏng mất", group: "Kho", farmScoped: true, softDelete: null, writeRoles: [...OPS, "worker"] },
  { table: "plan_scenarios", pk: "id",''',1))
rw("src/app/api/actions/route.ts", lambda s: s.replace('        case "publish_plan": {', '''        case "tool_issue": { const r = await c.query("insert into tool_issues(farm_id, warehouse_id, sku, qty, staff_id, dept, purpose, due_back) values ($1,$2,$3,$4,$5,$6,$7,$8) returning id", [s.farmId, b.warehouse_id, b.sku, Number(b.qty ?? 1), b.staff_id ?? null, b.dept ?? null, b.purpose ?? null, b.due_back ?? null]); return { ok: true, id: r.rows[0].id }; }
        case "tool_return": { const t = (await c.query("select * from tool_issues where id=$1 and farm_id=$2", [b.id, s.farmId])).rows[0]; if (!t) throw new Error("ERR_NOT_FOUND"); const cond = String(b.condition ?? "TOT"); const rq = Number(b.returned_qty ?? t.qty); await c.query("update tool_issues set returned_at=now(), returned_qty=$2, condition=$3, note=coalesce(note,'')||$4 where id=$1", [b.id, rq, cond, b.note ? " · " + b.note : ""]); if ((cond === "HONG" || cond === "MAT") && Number(t.qty) - rq > 0) { await c.query("insert into inventory_moves(farm_id, created_by, warehouse_id, sku, direction, qty, unit, reason, from_to, ref_type, ref_id, client_ref) values ($1,$2,$3,$4,-1,$5,(select unit from products where sku=$4),$6,$7,'tool_issue',$8,$9)", [s.farmId, s.staffId, t.warehouse_id, t.sku, Number(t.qty) - rq, cond, "Cấp phát #" + b.id, String(b.id), "tool-" + b.id + "-" + cond]); } return { ok: true }; }
        case "tool_move": { const q = Number(b.qty); if (!(q > 0)) throw new Error("ERR_QTY"); const u = (await c.query("select unit from products where sku=$1", [b.sku])).rows[0]?.unit; const ref = "toolmove-" + Date.now(); await c.query("insert into inventory_moves(farm_id, created_by, warehouse_id, sku, direction, qty, unit, reason, from_to, client_ref) values ($1,$2,$3,$4,-1,$5,$6,'CHUYEN',$7,$8)", [s.farmId, s.staffId, b.from_wh, b.sku, q, u, "→ " + b.to_wh, ref + "-out"]); await c.query("insert into inventory_moves(farm_id, created_by, warehouse_id, sku, direction, qty, unit, reason, from_to, client_ref) values ($1,$2,$3,$4,1,$5,$6,'CHUYEN',$7,$8)", [s.farmId, s.staffId, b.to_wh, b.sku, q, u, "← " + b.from_wh, ref + "-in"]); return { ok: true }; }
        case "publish_plan": {''',1))
w("src/app/du-tru/page.tsx", '''import { Page } from "@/components/withSession"; import DuTru from "@/components/panels/DuTru";
export default function P() { return <Page title="Dự trữ — kho đầu vào · kho đầu ra · kho công cụ theo khu vực">{(s) => <DuTru sess={s} />}</Page>; }
''')
w("src/components/panels/DuTru.tsx", r'''"use client";
import { useState } from "react";
import { useData, act, fmt } from "@/lib/client";
import type { Sess } from "@/components/Shell";
import AnyChart from "@/components/AnyChart";
import ChartIcon from "@/components/ChartIcon";
import Tabs from "@/components/Tabs";
type R = Record<string, unknown>;
const FLAG: Record<string, [string, string]> = { HET: ["HẾT", "bg-red-600 text-white"], THIEU_SOM: ["Thiếu sớm", "bg-red-100 text-red-800"], CHAM_ROP: ["Chạm ROP", "bg-orange-100 text-orange-800"], AM_30_NGAY: ["Âm 30 ngày", "bg-amber-100 text-amber-800"], OK: ["OK", "bg-emerald-100 text-emerald-800"] };
/** DASHBOARD DỰ TRỮ tách 3 khối: ĐẦU VÀO (nguyên liệu/thức ăn cho vật nuôi, giống, phân/thuốc, bao bì, nhiên liệu) · ĐẦU RA (thành phẩm) · CÔNG CỤ (từng cuốc/xẻng/búa, nhiều kho theo khu vực, cấp phát/thu hồi/hỏng) */
export default function DuTru({ sess }: { sess: Sess }) {
  const [tab, setTab] = useState<"vao" | "ra" | "cc">("vao");
  const dash = useData("stock_dashboard"); const fill = useData("warehouse_fill"); const tools = useData("tool_stock"); const issued = useData("tool_issued"); const cat = useData("tool_catalog"); const hist = useData("tool_history"); const staff = useData("staff_list"); const wh = useData("warehouses");
  const [msg, setMsg] = useState(""); const [isF, setIsF] = useState<R>({}); const [mvF, setMvF] = useState<R>({}); const [grp, setGrp] = useState<string>("");
  const canW = ["owner", "director", "tech_head", "team_lead", "worker", "it_engineer"].includes(sess.role);
  const rows = (b: string) => (dash.rows ?? []).filter((r) => r.block === b);
  const Block = ({ b, title, hint }: { b: string; title: string; hint: string }) => { const R0 = rows(b); const bad = R0.filter((r) => r.flag !== "OK"); const W = (fill.rows ?? []).filter((w) => w.block === b);
    return <div className="space-y-3">
      <div className="grid grid-cols-2 sm:grid-cols-4 gap-2"><div className="kpi"><div className="l">Mặt hàng có tồn</div><div className="v">{R0.length}</div></div><div className="kpi"><div className="l">Cần bổ sung</div><div className={`v ${bad.length ? "text-red-700" : ""}`}>{bad.length}</div></div><div className="kpi"><div className="l">Đang về (PO/thu hoạch/SX)</div><div className="v">{fmt.n(R0.reduce((a, r) => a + Number(r.incoming_po) + Number(r.incoming_harvest) + Number(r.incoming_production), 0))}</div></div><div className="kpi"><div className="l">Kho · % sức chứa</div><div className="v text-xl">{W.map((w) => `${w.code} ${w.pct_full != null ? w.pct_full + "%" : "—"}`).join(" · ")}</div></div></div>
      <div className="grid md:grid-cols-3 gap-2">{W.map((w) => <div key={String(w.warehouse_id)} className="card !p-3"><div className="flex items-center gap-2"><b>{String(w.code)}</b> <span className="text-sm">{String(w.name)}</span><span className="ml-auto text-xs text-slate-500">{String(w.area ?? "")}</span></div><div className="h-2 rounded bg-slate-100 mt-2 overflow-hidden"><div className={`h-2 ${Number(w.pct_full) > 90 ? "bg-red-500" : Number(w.pct_full) > 70 ? "bg-amber-500" : "bg-emerald-500"}`} style={{ width: `${Math.min(100, Number(w.pct_full ?? 0))}%` }} /></div><div className="text-xs text-slate-600 mt-1">{fmt.n(Number(w.qty))} {String(w.unit_kind).toLowerCase()} / sức chứa {w.capacity ? fmt.n(Number(w.capacity)) : "—"} · {String(w.skus)} SKU · {String(w.bins)} bin</div></div>)}</div>
      <div className="card p-0 overflow-auto"><div className="px-3 py-2 bg-slate-100 rounded-t-xl font-bold flex items-center gap-2 flex-wrap">{title} <span className="text-xs font-normal text-slate-500">{hint}</span></div>
        <table className="tbl text-sm"><thead><tr><th className="pl-3">Mặt hàng</th><th>TT</th><th className="text-right">Còn</th><th className="text-right">% max</th><th className="text-right">{b === "DAU_RA" ? "Bán/ngày" : "Dùng/ngày"}</th><th className="text-right">Ngày còn</th><th className="text-right">Đang về</th><th className="text-right">{b === "DAU_RA" ? "Đơn chốt" : "KH nhu cầu/ng"}</th><th className="text-right">DK 30ng</th><th className="text-right">DK 60ng</th><th className="text-right">DK 90ng</th><th className="text-right">{b === "DAU_RA" ? "Cần SX thêm" : "Cần bổ sung"}</th><th></th></tr></thead>
          <tbody>{R0.map((r) => { const f = FLAG[String(r.flag)] ?? FLAG.OK; return <tr key={String(r.sku)} className={r.flag !== "OK" ? "bg-red-50/60" : ""}><td className="pl-3">{String(r.name)}<div className="text-xs text-slate-500">{String(r.kind)} · {String(r.sku)}</div></td><td><span className={`rounded-full px-2 py-0.5 text-xs font-semibold ${f[1]}`}>{f[0]}</span></td><td className="text-right font-bold">{fmt.n(Number(r.qty))} <span className="text-xs font-normal">{String(r.unit)}</span></td><td className="text-right">{r.pct_full != null ? `${r.pct_full}%` : ""}</td><td className="text-right">{fmt.n(Number(r.use_per_day))}</td><td className={`text-right font-semibold ${r.days_left != null && Number(r.days_left) < 14 ? "text-red-700" : ""}`}>{r.days_left != null ? String(r.days_left) : "—"}</td><td className="text-right">{fmt.n(Number(r.incoming_po) + Number(r.incoming_harvest) + Number(r.incoming_production))}{Number(r.incoming_harvest) > 0 && <span className="text-xs text-emerald-700"> (thu {fmt.n(Number(r.incoming_harvest))})</span>}</td><td className="text-right">{b === "DAU_RA" ? fmt.n(Number(r.committed_orders)) : fmt.n(Number(r.use_per_day))}</td><td className={`text-right ${Number(r.proj_30) < 0 ? "text-red-700 font-bold" : ""}`}>{fmt.n(Number(r.proj_30))}</td><td className={`text-right ${Number(r.proj_60) < 0 ? "text-red-700" : ""}`}>{fmt.n(Number(r.proj_60))}</td><td className={`text-right ${Number(r.proj_90) < 0 ? "text-red-700" : ""}`}>{fmt.n(Number(r.proj_90))}</td><td className={`text-right font-bold ${Number(r.need_qty) > 0 ? "text-red-700" : "text-emerald-700"}`}>{fmt.n(Number(r.need_qty))}</td><td className="text-xs whitespace-nowrap"><ChartIcon type="product" id={String(r.sku)} />{Number(r.need_qty) > 0 && (b === "DAU_RA" ? <a className="underline ml-1" href="/che-bien">→ KHSX</a> : <a className="underline ml-1" href={`/kho?tab=rop`}>→ PO</a>)}</td></tr>; })}</tbody></table>
        {!R0.length && <div className="p-3 text-sm text-slate-500">Chưa có tồn trong khối này.</div>}<div className="p-2 text-xs text-slate-500">DK = tồn + đang về (PO/thu hoạch/SX) − đơn đã chốt − dùng/ngày × N. Dùng/ngày = kế hoạch cung–cầu đã ban hành (nếu có) hoặc trung bình xuất 14 ngày. Cần bổ sung = max của chính sách (stock_policies) hoặc 60 ngày dùng − (tồn + đang về − dùng trong lead time). Sức chứa kho: <a className="underline" href="/quan-tri?t=warehouses">warehouses.capacity</a>.</div></div>
      <div className="grid md:grid-cols-2 gap-3"><div className="card"><AnyChart title={`${b === "DAU_RA" ? "Xuất bán" : "Xuất dùng"} theo mặt hàng (14 tuần)`} table="inventory_moves" col="qty" dim="sku" bucket="week" filters={{ direction: "-1" }} height={240} /></div><div className="card"><AnyChart title="Nhập theo lý do (14 tuần)" table="inventory_moves" col="qty" dim="reason" bucket="week" filters={{ direction: "1" }} height={240} /></div></div></div>; };
  const groups = [...new Set((tools.rows ?? []).map((t) => String(t.tool_group ?? "")))].filter(Boolean);
  return <div className="space-y-3">
    <Tabs items={[["vao", `🌾 KHO ĐẦU VÀO — nguyên liệu, thức ăn, giống, phân/thuốc, bao bì, nhiên liệu (${rows("DAU_VAO").length})`], ["ra", `📦 KHO ĐẦU RA — thành phẩm bán (${rows("DAU_RA").length})`], ["cc", `🔧 KHO CÔNG CỤ – DỤNG CỤ theo khu vực (${(tools.rows ?? []).length} dòng · ${(issued.rows ?? []).length} đang cấp phát)`]]} value={tab} onChange={(k) => setTab(k as typeof tab)} />
    {msg && <div className="rounded-xl bg-emerald-50 border border-emerald-300 px-3 py-2 text-sm">{msg}</div>}
    {tab === "vao" && <Block b="DAU_VAO" title="Kho đầu vào: còn bao nhiêu · dùng bao nhiêu/ngày · đang về · dự kiến tồn · cần bổ sung" hint="K1 thuốc/vaccine · K2 nguyên liệu · K3 hào ủ/silo · K4 thức ăn TP · K7 nhiên liệu · K9 bao bì (giống trong K1)" />}
    {tab === "ra" && <Block b="DAU_RA" title="Kho đầu ra: thành phẩm còn · bán/ngày · đơn đã chốt · dự kiến tồn · cần sản xuất thêm" hint="K5 thành phẩm SKU · K6 kho lạnh" />}
    {tab === "cc" && <div className="space-y-3">
      <div className="grid grid-cols-2 sm:grid-cols-4 gap-2"><div className="kpi"><div className="l">Kho công cụ (khu vực)</div><div className="v">{(fill.rows ?? []).filter((w) => w.block === "CONG_CU").length}</div></div><div className="kpi"><div className="l">Dụng cụ định nghĩa</div><div className="v">{(cat.rows ?? []).length}</div></div><div className="kpi"><div className="l">Đang cấp phát</div><div className="v">{(issued.rows ?? []).length}</div></div><div className="kpi"><div className="l">Quá hạn trả</div><div className={`v ${(issued.rows ?? []).some((i) => i.overdue) ? "text-red-700" : ""}`}>{(issued.rows ?? []).filter((i) => i.overdue).length}</div></div></div>
      <div className="grid md:grid-cols-4 gap-2">{(fill.rows ?? []).filter((w) => w.block === "CONG_CU").map((w) => <div key={String(w.warehouse_id)} className="card !p-3"><b>{String(w.code)}</b> <span className="text-sm">{String(w.name)}</span><div className="text-xs text-slate-500">{String(w.area ?? "")} · {fmt.n(Number(w.qty))} cái · {String(w.skus)} loại</div></div>)}</div>
      {canW && <div className="grid lg:grid-cols-2 gap-3"><div className="card"><b>Cấp phát công cụ</b><div className="grid sm:grid-cols-3 lg:grid-cols-6 gap-2 mt-2"><select className="input" value={String(isF.warehouse_id ?? "")} onChange={(e) => setIsF({ ...isF, warehouse_id: e.target.value })}><option value="">Kho</option>{(wh.rows ?? []).filter((w) => w.block === "CONG_CU").map((w) => <option key={String(w.id)} value={String(w.id)}>{String(w.code)}</option>)}</select><select className="input lg:col-span-2" value={String(isF.sku ?? "")} onChange={(e) => setIsF({ ...isF, sku: e.target.value })}><option value="">Dụng cụ</option>{(tools.rows ?? []).filter((t) => !isF.warehouse_id || t.warehouse_id === isF.warehouse_id).map((t) => <option key={String(t.warehouse_id) + String(t.sku)} value={String(t.sku)}>{String(t.name)} (còn {String(t.available)})</option>)}</select><input className="input" type="number" placeholder="SL" value={String(isF.qty ?? 1)} onChange={(e) => setIsF({ ...isF, qty: e.target.value })} /><select className="input" value={String(isF.staff_id ?? "")} onChange={(e) => setIsF({ ...isF, staff_id: e.target.value })}><option value="">Người nhận</option>{(staff.rows ?? []).map((s) => <option key={String(s.id)} value={String(s.id)}>{String(s.full_name)}</option>)}</select><input className="input" type="date" value={String(isF.due_back ?? "")} onChange={(e) => setIsF({ ...isF, due_back: e.target.value })} /><input className="input lg:col-span-5" placeholder="Mục đích / vị trí dùng" value={String(isF.purpose ?? "")} onChange={(e) => setIsF({ ...isF, purpose: e.target.value })} /><button className="btn-primary !py-2" disabled={!isF.warehouse_id || !isF.sku} onClick={async () => { const j = await act("tool_issue", { ...isF, qty: Number(isF.qty ?? 1) }); setMsg(j.ok ? "Đã cấp phát" : String(j.error)); issued.reload(); tools.reload(); hist.reload(); }}>Cấp</button></div></div>
        <div className="card"><b>Chuyển kho công cụ giữa khu vực</b><div className="grid sm:grid-cols-5 gap-2 mt-2"><select className="input" value={String(mvF.from_wh ?? "")} onChange={(e) => setMvF({ ...mvF, from_wh: e.target.value })}><option value="">Từ kho</option>{(wh.rows ?? []).filter((w) => w.block === "CONG_CU").map((w) => <option key={String(w.id)} value={String(w.id)}>{String(w.code)}</option>)}</select><select className="input" value={String(mvF.to_wh ?? "")} onChange={(e) => setMvF({ ...mvF, to_wh: e.target.value })}><option value="">Đến kho</option>{(wh.rows ?? []).filter((w) => w.block === "CONG_CU").map((w) => <option key={String(w.id)} value={String(w.id)}>{String(w.code)}</option>)}</select><select className="input" value={String(mvF.sku ?? "")} onChange={(e) => setMvF({ ...mvF, sku: e.target.value })}><option value="">Dụng cụ</option>{(cat.rows ?? []).map((t) => <option key={String(t.sku)} value={String(t.sku)}>{String(t.name)}</option>)}</select><input className="input" type="number" placeholder="SL" value={String(mvF.qty ?? "")} onChange={(e) => setMvF({ ...mvF, qty: e.target.value })} /><button className="btn-secondary !py-2" disabled={!mvF.from_wh || !mvF.to_wh || !mvF.sku || !mvF.qty} onClick={async () => { const j = await act("tool_move", mvF); setMsg(j.ok ? "Đã chuyển" : String(j.error)); tools.reload(); fill.reload(); }}>Chuyển</button></div><div className="text-xs text-slate-500 mt-1">Nhập mua công cụ mới: form Kho › Nhập (chọn kho KCC-*) hoặc PO. Định nghĩa dụng cụ mới: <a className="underline" href="/quan-tri?t=products">products kind=CONG_CU</a> (nhóm, đơn vị, tuổi thọ, giá, cần chứng chỉ).</div></div></div>}
      <div className="card p-0 overflow-auto"><div className="px-3 py-2 bg-slate-100 rounded-t-xl font-bold flex items-center gap-2 flex-wrap">Tồn công cụ theo kho/khu vực <select className="input !w-48 !py-1 font-normal text-sm" value={grp} onChange={(e) => setGrp(e.target.value)}><option value="">Mọi nhóm</option>{groups.map((g) => <option key={g}>{g}</option>)}</select><a className="ml-auto underline text-sm font-normal" href="/api/admin/products?csv=1">xuất danh mục</a></div>
        <table className="tbl text-sm"><thead><tr><th className="pl-3">Kho · khu vực</th><th>Dụng cụ</th><th>Nhóm</th><th className="text-right">Có</th><th className="text-right">Đang cấp</th><th className="text-right">Sẵn</th><th className="text-right">Min</th><th className="text-right">Hỏng/mất 12th</th><th className="text-right">Tuổi thọ (th)</th><th></th></tr></thead><tbody>{(tools.rows ?? []).filter((t) => !grp || t.tool_group === grp).map((t) => <tr key={String(t.warehouse_id) + String(t.sku)} className={t.min_qty != null && Number(t.available) < Number(t.min_qty) ? "bg-red-50" : ""}><td className="pl-3"><b>{String(t.warehouse_code)}</b> <span className="text-xs text-slate-500">{String(t.area ?? "")}</span></td><td>{String(t.name)}{t.needs_cert ? <span className="text-xs text-amber-700"> · cần chứng chỉ</span> : null}</td><td className="text-xs">{String(t.tool_group ?? "")}</td><td className="text-right font-bold">{String(t.on_hand)}</td><td className="text-right">{String(t.issued)}</td><td className="text-right">{String(t.available)}</td><td className="text-right">{String(t.min_qty ?? "")}</td><td className="text-right">{String(t.lost_broken_12m ?? 0)}</td><td className="text-right">{String(t.life_months ?? "")}</td><td><ChartIcon type="product" id={String(t.sku)} /></td></tr>)}</tbody></table></div>
      <div className="grid lg:grid-cols-2 gap-3"><div className="card p-0 overflow-auto"><div className="px-3 py-2 bg-slate-100 rounded-t-xl font-bold">Đang cấp phát (chưa thu hồi)</div><table className="tbl text-sm"><thead><tr><th className="pl-3">Dụng cụ</th><th>Người</th><th>Kho</th><th className="text-right">SL</th><th>Từ</th><th>Hạn trả</th><th></th></tr></thead><tbody>{(issued.rows ?? []).map((i) => <tr key={String(i.id)} className={i.overdue ? "bg-red-50" : ""}><td className="pl-3">{String(i.tool_name)}</td><td>{String(i.staff_name ?? i.dept ?? "")}</td><td className="text-xs">{String(i.warehouse_code)}</td><td className="text-right">{String(i.qty)}</td><td className="text-xs">{fmt.d(String(i.issued_at))}</td><td className="text-xs">{i.due_back ? fmt.d(String(i.due_back)) : ""}{i.overdue ? " ⚠" : ""}</td><td className="text-xs whitespace-nowrap">{canW && ["TOT", "HAO_MON", "HONG", "MAT"].map((c) => <button key={c} className={`underline mr-1 ${c === "HONG" || c === "MAT" ? "text-red-700" : ""}`} onClick={async () => { const rq = c === "MAT" ? "0" : c === "HONG" ? prompt(`Số còn dùng được (đã cấp ${i.qty})?`, "0") : String(i.qty); if (rq == null) return; const j = await act("tool_return", { id: i.id, condition: c, returned_qty: Number(rq) }); setMsg(j.ok ? `Đã thu hồi (${c})` : String(j.error)); issued.reload(); tools.reload(); hist.reload(); }}>{c === "TOT" ? "trả tốt" : c === "HAO_MON" ? "hao mòn" : c === "HONG" ? "hỏng" : "mất"}</button>)}</td></tr>)}</tbody></table>{!(issued.rows ?? []).length && <div className="p-3 text-sm text-slate-500">Không có công cụ đang cấp phát.</div>}</div>
        <div className="card"><AnyChart title="Xuất công cụ (hỏng/mất/chuyển) theo lý do" table="inventory_moves" col="qty" dim="reason" bucket="month" filters={{ direction: "-1" }} height={220} /><div className="text-xs text-slate-500 mt-1">Bấm 📈 ở từng dòng để xem biến động riêng dụng cụ đó (nhập/xuất, so kỳ trước). Lịch sử cấp phát: <a className="underline" href="/quan-tri?t=tool_issues">tool_issues</a>.</div></div></div>
      <div className="card p-0 overflow-auto"><div className="px-3 py-2 bg-slate-100 rounded-t-xl font-bold">Danh mục dụng cụ đã định nghĩa ({(cat.rows ?? []).length})</div><div className="p-2 flex flex-wrap gap-1">{(cat.rows ?? []).map((t) => <span key={String(t.sku)} className="rounded-lg border px-2 py-0.5 text-xs" title={`${t.tool_group} · ${t.unit} · ${t.life_months} tháng · ${fmt.vnd(Number(t.ref_price ?? 0))}`}>{String(t.name)}</span>)}</div></div></div>}
  </div>;
}
''')
rw("src/components/Shell.tsx", lambda s: s.replace('items: [{ href: "/kho", label: "Kho" },', 'items: [{ href: "/du-tru", label: "Dự trữ (dashboard)" }, { href: "/kho", label: "Kho" },',1))
