import io
R="F:/ITRAN FARM/itran-os/"
def rw(p, fn): s=io.open(R+p,encoding="utf-8").read(); n=fn(s); assert n!=s, p; io.open(R+p,"w",encoding="utf-8",newline="\n").write(n); print("ok",p)
# queries
def q(s):
    s=s.replace('  my_inbox: { sql: "select * from my_inbox($1, app_staff(), app_role()) limit 400", ttl: 20 },','  my_inbox: { sql: "select * from (select * from my_inbox($1, app_staff(), app_role()) union all select * from my_inbox_gs($1, app_staff())) x order by case priority when \'KHAN\' then 0 when \'CAO\' then 1 when \'BINH_THUONG\' then 2 else 3 end, due_at nulls last limit 400", ttl: 20 },',1)
    s=s.replace('  my_inbox_counts: { sql: "select kind, count(*)::int as n, min(due_at) as first_due from my_inbox($1, app_staff(), app_role()) group by 1", ttl: 20 },','  my_inbox_counts: { sql: "select kind, count(*)::int as n, min(due_at) as first_due from (select * from my_inbox($1, app_staff(), app_role()) union all select * from my_inbox_gs($1, app_staff())) x group by 1", ttl: 20 },',1)
    s=s.replace('  supervision_targets: { sql: "select s.id, s.full_name, s.dept, s.position_code, s.role from staff s join supervision_assignments a on a.farm_id=s.farm_id and a.active and (a.target_staff_id=s.id or (a.target_staff_id is null and (a.target_dept=s.dept or a.target_dept is null))) where s.farm_id=$1 and s.active and s.role in (\'worker\',\'team_lead\')','  supervision_targets: { sql: "select s.id, s.full_name, s.dept, s.position_code, s.role from staff s join supervision_assignments a on a.farm_id=s.farm_id and a.active and (a.target_staff_id=s.id or (a.target_staff_id is null and (a.target_dept=s.dept or a.target_dept is null))) where s.farm_id=$1 and s.active and s.role in (\'worker\',\'team_lead\',\'tech_head\')',1)
    s=s.replace("  collusion_pairs:", '''  gs_today: { sql: "select gs_today($1, app_staff()) as t" },
  gs_omissions_all: { sql: "select o.*, s.full_name from gs_omissions o join staff s on s.id=o.supervisor_id where o.farm_id=$1 order by o.day desc limit 300" },
  pay_structure: { sql: "select * from v_pay_structure where farm_id=$1 or farm_id is null order by dept, full_name", ttl: 120 },
  my_pay: { sql: "select * from v_pay_structure where staff_id=app_staff()" },
  salary_scales: { sql: "select * from salary_scales where active order by scope_kind desc, scope_code" },
  headcount: { sql: "select * from v_headcount where farm_id=$1 order by year desc, dept, position_code" },
  contribution_bonus: { sql: "select b.*, s.full_name from bonus_ledger b join staff s on s.id=b.staff_id where b.farm_id=$1 and b.kind in ('THUONG_QUY','THUONG_NAM') order by b.created_at desc limit 200" },
  collusion_pairs:''',1)
    return s
rw("src/lib/queries.ts", q)
# actions
rw("src/app/api/actions/route.ts", lambda s: s.replace('        case "cross_check_submit":', '''        case "gs_ack": { // GS đã xem lỗi hệ thống báo, kết luận (không lỗi / có lỗi) — tính là đã xử lý, hết bỏ sót
          const res = b.result === "LOI" ? "LOI" : "DAT"; const note = (res === "DAT" ? "[đã xem auto] " : "[từ dữ liệu auto] ") + String(b.note ?? "");
          const r = await c.query("insert into supervision_checks(farm_id, created_by, client_ref, supervisor_id, target_staff_id, criteria_id, week_start, item, result, severity, note) values ($1,$2,$3,$2,$4,$5,date_trunc('week', current_date)::date,$6,$7,$8,$9) returning id, points", [s.farmId, s.staffId, crypto.randomUUID(), b.staff_id, b.criteria_id, b.item ?? "auto", res, res === "LOI" ? (b.severity ?? "TRUNG") : null, note]); return { ok: true, ...r.rows[0] }; }
        case "sync_process_criteria": { if (!["owner","director","auditor","it_engineer"].includes(s.role)) throw new Error("ERR_FORBIDDEN_ROLE"); const r = await c.query("select sync_process_criteria() as n"); return { ok: true, n: r.rows[0].n }; }
        case "gen_gs_omissions": { if (!["owner","director","auditor","it_engineer"].includes(s.role)) throw new Error("ERR_FORBIDDEN_ROLE"); const r = await c.query("select gen_gs_omissions($1, coalesce($2::date, current_date-1)) as n", [s.farmId, b.day ?? null]); return { ok: true, n: r.rows[0].n }; }
        case "suggest_headcount": { if (!["owner","director","accountant","it_engineer"].includes(s.role) && s.dept !== "HCNS") throw new Error("ERR_FORBIDDEN_ROLE"); const r = await c.query("select suggest_headcount($1,$2,$3) as n", [s.farmId, Number(b.year ?? new Date().getFullYear()), s.staffId]); return { ok: true, n: r.rows[0].n }; }
        case "headcount_set": { if (!["owner","director","accountant","it_engineer"].includes(s.role) && s.dept !== "HCNS") throw new Error("ERR_FORBIDDEN_ROLE"); await c.query("update headcount_plans set planned=$3, budget_month=$4 where id=$1 and farm_id=$2", [b.id, s.farmId, Number(b.planned), b.budget_month == null ? null : Number(b.budget_month)]); return { ok: true }; }
        case "close_contribution_bonus": { if (!["owner","director","accountant"].includes(s.role)) throw new Error("ERR_FORBIDDEN_ROLE"); const r = await c.query("select close_contribution_bonus($1,$2,$3) as n", [s.farmId, b.quarter, s.staffId]); return { ok: true, n: r.rows[0].n }; }
        case "cross_check_submit":''',1))
# jobs
rw("src/app/api/jobs/[job]/route.ts", lambda s: s.replace('    if (job === "grade" ||', '''    if (job === "gsdaily" || job === "all") { out[`gs_omissions:${f}`] = (await adminPool().query("select gen_gs_omissions($1, current_date-1) as n", [f])).rows[0].n; }
    if (job === "grade" ||''',1))
# admin registry
rw("src/lib/admin.ts", lambda s: s.replace('  { table: "cross_checks",', '''  { table: "salary_scales", pk: "id", label: "Lương · thang lương vị trí/vai (lớp 1 = thang × hệ số bậc)", group: "Nhân sự", farmScoped: false, softDelete: "active", writeRoles: ["owner", "director", "accountant"] },
  { table: "headcount_plans", pk: "id", label: "Định biên theo năm (kế hoạch nhân sự & quỹ lương)", group: "Nhân sự", farmScoped: true, softDelete: null, writeRoles: ["owner", "director", "accountant", "it_engineer"] },
  { table: "gs_block_sops", pk: "block", label: "Giám sát · SOP cốt lõi theo khối (điều kiện khối đạt)", group: "Nhân sự", farmScoped: false, softDelete: null, writeRoles: ["owner", "director", "auditor", "it_engineer"] },
  { table: "gs_omissions", pk: "id", label: "Giám sát · LỖI CỦA GS (máy ghi: bỏ sót/không kiểm/không kiểm trưởng phòng)", group: "Nhân sự", farmScoped: true, softDelete: null, writeRoles: ["owner", "it_engineer"] },
  { table: "cross_checks",''',1))
# GiamSat: tab "ngay" + head criteria scope
def gs(s):
    s=s.replace('const [tab, setTab] = useState<"tuan" | "cham" | "tieuchi" | "loi" | "xuhuong" | "nhip" | "chong">(typeof window !== "undefined" && new URLSearchParams(window.location.search).get("tab") === "chong" ? "chong" : "tuan");',
                'const [tab, setTab] = useState<"ngay" | "tuan" | "cham" | "tieuchi" | "loi" | "xuhuong" | "nhip" | "chong">(typeof window !== "undefined" && new URLSearchParams(window.location.search).get("tab") === "chong" ? "chong" : "ngay");',1)
    s=s.replace('<Tabs items={[["tuan", `Bảng điểm tuần này','<Tabs items={[["ngay", "📅 Hôm nay của GS (kiểm hằng ngày theo quy trình)"], ["tuan", `Bảng điểm tuần này',1)
    s=s.replace('  const critFor = (t: R | undefined) => C.filter((c) => (!c.position_code || c.position_code === t?.position_code) && (!c.dept_code || c.dept_code === t?.dept));',
                '  const isHeadT = (t: R | undefined) => t?.role === "tech_head" || t?.role === "team_lead";\n  const critFor = (t: R | undefined) => C.filter((c) => (c.role_scope === "TRUONG_PHONG" ? isHeadT(t) : !c.role_scope) && (!c.position_code || c.position_code === t?.position_code) && (!c.dept_code || c.dept_code === t?.dept) && !c.process_code);',1)
    s=s.replace('    {tab === "nhip" && <NhipTuan sess={sess} />}','    {tab === "ngay" && <GsToday sess={sess} crit={C} />}\n    {tab === "nhip" && <NhipTuan sess={sess} />}',1)
    s += r'''
/** HÔM NAY CỦA GS — GS1 kiểm tuân thủ quy trình HẰNG NGÀY: cả thợ lẫn trưởng phòng; mọi lỗi hệ thống thấy mà GS không ghi = lỗi GS → mất thưởng */
function GsToday({ sess, crit }: { sess: Sess; crit: R[] }) {
  const q = useData<R>("gs_today"); const t = (q.rows ?? [])[0]?.t as R | undefined; const [msg, setMsg] = useState(""); const [openDept, setOpenDept] = useState<string>("");
  const reload = () => q.reload();
  if (!t) return <div className="card text-sm text-slate-500">đang tải…</div>;
  if (t.is_gs !== true) return <div className="card text-sm">Bạn không thuộc ngạch Giám sát. Trang này dành cho GS (GS1–GS3) đi kiểm hằng ngày. Trưởng phòng xem tab <b>Nhịp tuần & CAPA</b> để nhận lỗi và ghi biện pháp; mọi người xem <b>Bảng điểm tuần</b>.</div>;
  const depts = (t.depts as R[]) ?? []; const pend = (t.pending_auto as R[]) ?? []; const om = Number(t.omissions_month ?? 0); const omMax = Number(t.omissions_max ?? 3);
  const check = async (payload: R, result: string) => { let severity: string | null = null; let note: string | null = null; if (result === "LOI") { severity = prompt("Mức độ: NHE / TRUNG / NANG", "TRUNG"); if (!severity) return; note = prompt("Mô tả lỗi + yêu cầu khắc phục (kèm link ảnh nếu có)"); if (note === null) return; } const j = await act("sup_check", { ...payload, result, severity, note, client_ref: crypto.randomUUID() }); setMsg(j.error ? `${j.error}: ${j.detail ?? ""}` : result === "LOI" ? "Đã ghi LỖI → sẽ vào CAPA trưởng phòng thứ 6" : "Đã ghi ĐẠT"); reload(); };
  const ack = async (p: R, result: string) => { const note = prompt(result === "LOI" ? "Xác nhận LỖI — mô tả thêm" : "Đã xem, KHÔNG lỗi — lý do (bắt buộc, sẽ bị đối chiếu kiểm chéo)"); if (note === null || (result === "DAT" && note.length < 5)) return; const j = await act("gs_ack", { staff_id: p.staff_id, criteria_id: p.criteria_id, item: p.criteria, result, note }); setMsg(j.error ? String(j.error) : "Đã xử lý"); reload(); };
  return <div className="space-y-3">
    <div className={`card flex flex-wrap gap-4 items-center ${om > omMax ? "ring-2 ring-red-400" : ""}`}>
      <div><div className="text-xs text-slate-500">Lỗi GS tháng này (máy ghi)</div><div className={`text-2xl font-black ${om > omMax ? "text-red-700" : om > 0 ? "text-amber-700" : "text-emerald-700"}`}>{om}<span className="text-sm text-slate-500"> / ngưỡng {omMax}</span></div><div className="text-xs">{om > omMax ? "⛔ Quá ngưỡng → tháng này KHÔNG có thưởng GS" : "Vượt ngưỡng là mất thưởng tháng"}</div></div>
      <div><div className="text-xs text-slate-500">Lượt kiểm tháng</div><div className="text-2xl font-black">{String(t.checks_month)}</div></div>
      <div><div className="text-xs text-slate-500">Ngày đi ca thật</div><div className="text-2xl font-black">{String(t.field_days_month)}</div></div>
      <div><div className="text-xs text-slate-500">Việc quá hạn trong các phòng tôi kiểm</div><div className="text-2xl font-black">{String(t.overdue_tasks)}</div></div>
      <div className="text-xs text-slate-600 max-w-md">Nguyên tắc: kiểm <b>hằng ngày</b>, không chờ có việc; kiểm <b>cả thợ lẫn trưởng phòng</b>; ghi lỗi <b>ngay lúc thấy</b>; lỗi hệ thống đã phát hiện mà GS không ghi/xác nhận trong 24h = <b>lỗi của GS</b>.</div>
      {msg && <div className="text-sm text-emerald-800 w-full">{msg}</div>}
    </div>
    {pend.length > 0 && <div className="card p-0 overflow-auto ring-2 ring-red-300"><div className="px-3 py-2 bg-red-50 rounded-t-xl font-bold">🔴 Hệ thống đã phát hiện {pend.length} lỗi — GS phải ghi hoặc xác nhận trong 24h</div><table className="tbl text-sm"><thead><tr><th className="pl-3">Tuần</th><th>Nhân sự</th><th>Phòng</th><th>Tiêu chí (auto)</th><th className="text-right">Giá trị / mục tiêu</th><th></th></tr></thead><tbody>
      {pend.map((p, i) => <tr key={i}><td className="pl-3 text-xs">{fmt.d(p.week)}</td><td>{String(p.name)}</td><td className="text-xs">{String(p.dept)}</td><td className="text-xs">{String(p.criteria)}</td><td className="text-right text-xs">{String(p.value)} / {String(p.target)}</td><td className="whitespace-nowrap"><button className="btn-secondary !py-0.5 !px-2 !text-xs !bg-red-50 mr-1" onClick={() => ack(p, "LOI")}>Ghi LỖI</button><button className="btn-secondary !py-0.5 !px-2 !text-xs" onClick={() => ack(p, "DAT")}>Đã xem, không lỗi</button></td></tr>)}</tbody></table></div>}
    {depts.map((d) => { const staff = (d.staff as R[]) ?? []; const procs = (d.processes as R[]) ?? []; const head = d.head as R | null; const due = procs.filter((p) => p.due === true); const open = openDept === String(d.dept) || depts.length === 1; return <div key={String(d.dept)} className="card">
      <div className="flex items-center gap-2 flex-wrap cursor-pointer" onClick={() => setOpenDept(open && depts.length > 1 ? "" : String(d.dept))}><b>{open ? "▾" : "▸"} Phòng {String(d.dept)} — {String(d.name ?? "")}</b><span className={`text-xs px-2 py-0.5 rounded-full ${Number(d.checks_today) >= Number(d.min_per_day) ? "bg-emerald-100 text-emerald-900" : "bg-red-100 text-red-900"}`}>hôm nay {String(d.checks_today)}/{String(d.min_per_day)} lượt</span><span className="text-xs text-slate-600">{due.length} quy trình đến hạn kiểm · {staff.length} nhân sự</span>{head && <span className={`text-xs px-2 py-0.5 rounded-full ${head.checked_this_week ? "bg-emerald-100" : "bg-amber-100"}`}>Trưởng phòng {String(head.name)}: {head.checked_this_week ? "đã kiểm tuần này" : "CHƯA kiểm tuần này"}</span>}</div>
      {open && <div className="grid lg:grid-cols-2 gap-3 mt-2">
        <div><div className="text-xs font-bold text-slate-500 uppercase mb-1">Quy trình của phòng — kiểm tuân thủ ({procs.length})</div><div className="max-h-96 overflow-auto divide-y">{procs.map((p) => <div key={String(p.id)} className={`py-1.5 flex items-start gap-2 ${p.due ? "" : "opacity-60"}`}><div className="flex-1 min-w-0"><div className="text-sm font-semibold truncate" title={String(p.what ?? "")}>{String(p.name)} <span className="text-[10px] rounded bg-slate-100 px-1">{String(p.freq)}</span></div><div className="text-xs text-slate-500 truncate">{String(p.what ?? "")}</div><div className="text-[11px] text-slate-400">lần cuối: {p.last_check ? fmt.d(p.last_check) : "chưa"}{p.due ? " · ĐẾN HẠN" : ""}</div></div><div className="shrink-0 whitespace-nowrap"><button className="btn-secondary !py-0.5 !px-2 !text-xs mr-1" onClick={() => check({ target_dept: d.dept, criteria_id: p.id, item: p.name, sop_code: null }, "DAT")}>Đạt</button><button className="btn-secondary !py-0.5 !px-2 !text-xs !bg-red-50" onClick={() => check({ target_dept: d.dept, criteria_id: p.id, item: p.name, sop_code: null }, "LOI")}>Lỗi</button></div></div>)}</div></div>
        <div><div className="text-xs font-bold text-slate-500 uppercase mb-1">Con người — thợ & trưởng phòng ({staff.length})</div><div className="max-h-96 overflow-auto divide-y">{staff.map((w) => { const isH = w.role === "tech_head" || w.role === "team_lead"; const cs = crit.filter((c) => (c.role_scope === "TRUONG_PHONG" ? isH : !c.role_scope) && c.method === "MANUAL" && !c.process_code && (!c.position_code || c.position_code === w.position_code) && (!c.dept_code || c.dept_code === d.dept)); return <div key={String(w.id)} className="py-1.5"><div className="flex items-center gap-2"><b className="text-sm">{String(w.name)}</b>{isH && <span className="text-[10px] rounded bg-amber-100 px-1">TRƯỞNG PHÒNG</span>}<span className="text-xs text-slate-500">{String(w.position ?? "")}</span><span className="text-[11px] text-slate-400 ml-auto">kiểm lần cuối: {w.last_check ? fmt.d(w.last_check) : "chưa"}{Number(w.auto_fails) > 0 ? <span className="text-red-700 font-bold"> · {String(w.auto_fails)} lỗi auto</span> : ""}</span></div><div className="flex flex-wrap gap-1 mt-1">{cs.map((c) => <span key={String(c.id)} className="inline-flex items-center gap-0.5 text-xs border rounded px-1"><span title={String(c.what ?? "")}>{String(c.name).slice(0, 34)}</span><button className="text-emerald-700 font-bold px-1" onClick={() => check({ target_staff_id: w.id, target_dept: d.dept, criteria_id: c.id, item: c.name }, "DAT")}>✓</button><button className="text-red-700 font-bold px-1" onClick={() => check({ target_staff_id: w.id, target_dept: d.dept, criteria_id: c.id, item: c.name }, "LOI")}>✗</button></span>)}</div></div>; })}</div></div>
      </div>}
    </div>; })}
    {depts.length === 0 && <div className="card text-sm text-slate-500">Bạn chưa được phân công phòng nào (supervision_assignments). HCNS/GS trưởng phân công hoặc chạy luân chuyển.</div>}
    <div className="card p-0 overflow-auto"><div className="px-3 py-2 bg-slate-100 rounded-t-xl font-bold">Lỗi GS của tôi (máy ghi, không sửa được) — 20 gần nhất</div><table className="tbl text-sm"><tbody>{((t.omissions_list as R[]) ?? []).map((o, i) => <tr key={i}><td className="pl-3 text-xs">{fmt.d(o.day)}</td><td className="text-xs">{String(o.kind)}</td><td>{String(o.detail)}</td><td className="text-right">−{String(o.points)}</td></tr>)}{((t.omissions_list as R[]) ?? []).length === 0 && <tr><td className="p-3 text-slate-500">Chưa có — tốt.</td></tr>}</tbody></table></div>
  </div>;
}
'''
    return s
rw("src/components/panels/GiamSat.tsx", gs)
# Career: pay tab
def car(s):
    s=s.replace('const [tab, setTab] = useState<"tong" | "xet" | "ghe" | "gs" | "conghien" | "tieuchi">("tong");','const [tab, setTab] = useState<"tong" | "xet" | "ghe" | "gs" | "conghien" | "tieuchi" | "luong">("tong");',1)
    s=s.replace('["conghien", "Điểm cống hiến & sáng kiến"], ["tieuchi", "Bảng bậc & tiêu chí"]]}','["conghien", "Điểm cống hiến & sáng kiến"], ["luong", "💰 Cơ chế lương–thưởng · định biên"], ["tieuchi", "Bảng bậc & tiêu chí"]]}',1)
    s=s.replace('    {tab === "tieuchi" && <div className="space-y-3">','    {tab === "luong" && <PayPanel sess={sess} canHR={canHR} />}\n    {tab === "tieuchi" && <div className="space-y-3">',1)
    s += r'''
/** CƠ CHẾ LƯƠNG – THƯỞNG 4 lớp + định biên */
function PayPanel({ sess, canHR }: { sess: Sess; canHR: boolean }) {
  const ps = useData<R>("pay_structure"); const sc = useData<R>("salary_scales"); const hc = useData<R>("headcount"); const cb = useData<R>("contribution_bonus"); const [msg, setMsg] = useState("");
  const yr = new Date().getFullYear(); const canMoney = ["owner", "director", "accountant"].includes(sess.role);
  const prevQ = (() => { const d = new Date(); const q = Math.floor(d.getMonth() / 3); return q === 0 ? `${d.getFullYear() - 1}-Q4` : `${d.getFullYear()}-Q${q}`; })();
  return <div className="space-y-3">
    <div className="card text-sm"><b>Thu nhập = 4 lớp, minh bạch, ai cũng tự tính được</b>
      <ol className="list-decimal ml-5 mt-1 text-slate-700"><li><b>Lớp 1 — Lương vị trí × hệ số bậc × ngày công</b>: thang lương theo vị trí (A1–A14) hoặc vai; hệ số bậc B1 1.00 → B4 1.60, GS1 1.35 → PGĐ 2.20. Lên bậc = tăng lương ngay, không xin-cho.</li><li><b>Lớp 2 — KPI & thưởng điều kiện tháng</b>: KPI ghi chép (× % lương) + thưởng tháng theo điều kiện học/dạy/thi/giám sát; lỗi giám sát trừ; <b>GS quá ngưỡng lỗi bỏ sót → mất thưởng</b>; trưởng phòng bị trừ theo lỗi lặp/CAPA quá hạn của phòng.</li><li><b>Lớp 3 — Phụ cấp</b>: ghế then chốt (theo ghế), biệt phái GS, độc hại/ca đêm (hồ sơ).</li><li><b>Lớp 4 — Thưởng cống hiến quý/năm</b>: điểm cống hiến × đơn giá (trần), chốt cuối quý, trả vào lương tháng đầu quý sau.</li></ol>
      <div className="text-xs text-slate-500 mt-1">Thang lương & hệ số là dữ liệu có phiên bản (Quản trị DL › salary_scales, grade_scales) — in được phụ lục HĐLĐ, đăng ký Sở LĐ. Bảng lương thật (Kế toán › Lương) đã dùng công thức này, ghi rõ nguồn từng người.</div>
      {canMoney && <button className="btn-secondary !py-1 !text-xs mt-1" onClick={async () => { const j = await act("close_contribution_bonus", { quarter: prevQ }); setMsg(j.error ? String(j.error) : `Đã chốt thưởng cống hiến ${prevQ}: ${j.n} người`); cb.reload(); }}>Chốt thưởng cống hiến {prevQ}</button>}{msg && <span className="ml-2 text-emerald-800 text-xs">{msg}</span>}</div>
    <div className="card p-0 overflow-auto"><div className="px-3 py-2 bg-slate-100 rounded-t-xl font-bold">Cơ cấu thu nhập từng người ({(ps.rows ?? []).length})</div><table className="tbl text-sm"><thead><tr><th className="pl-3">Nhân sự</th><th>Phòng</th><th>Bậc</th><th className="text-right">Thang</th><th className="text-right">Hệ số</th><th className="text-right">Lớp 1</th><th className="text-right">Phụ cấp</th><th className="text-right">Thưởng tháng tối đa</th><th>Nguồn</th></tr></thead><tbody>
      {(ps.rows ?? []).map((r) => <tr key={String(r.staff_id)}><td className="pl-3">{String(r.full_name)}<div className="text-xs text-slate-500">{String(r.position ?? r.role)}</div></td><td>{String(r.dept ?? "")}</td><td><Badge g={r.grade_gs ?? r.grade_cm} /></td><td className="text-right">{fmt.n(r.scale_amount)}</td><td className="text-right">{String(r.coef)}</td><td className="text-right font-bold">{fmt.n(r.base_l1)}</td><td className="text-right">{fmt.n(r.allowances_l3)}</td><td className="text-right">{fmt.n(r.bonus_l2_max)}</td><td className="text-xs">{String(r.source)}</td></tr>)}</tbody></table></div>
    <div className="grid md:grid-cols-2 gap-3">
      <div className="card p-0 overflow-auto"><div className="px-3 py-2 bg-slate-100 rounded-t-xl font-bold">Thang lương (lớp 1 cơ sở)</div><table className="tbl text-sm"><tbody>{(sc.rows ?? []).map((r) => <tr key={String(r.id)}><td className="pl-3 text-xs">{String(r.scope_kind)}</td><td>{String(r.scope_code)}</td><td className="text-xs">{String(r.note ?? "")}</td><td className="text-right">{fmt.n(r.base_amount)}</td><td className="text-xs">từ {fmt.d(r.effective_from)} · v{String(r.version)}</td></tr>)}</tbody></table></div>
      <div className="card p-0 overflow-auto"><div className="px-3 py-2 bg-slate-100 rounded-t-xl font-bold flex items-center gap-2">Định biên {yr} vs thực tế{canHR && <button className="ml-auto btn-secondary !py-0.5 !text-xs" onClick={async () => { const j = await act("suggest_headcount", { year: yr }); setMsg(j.error ? String(j.error) : `Đã gợi ý ${j.n} dòng định biên từ thực tế`); hc.reload(); }}>Gợi ý từ thực tế</button>}</div><table className="tbl text-sm"><thead><tr><th className="pl-3">Phòng</th><th>Vị trí</th><th className="text-right">Định biên</th><th className="text-right">Thực tế</th><th className="text-right">Quỹ lương L1/tháng</th></tr></thead><tbody>{(hc.rows ?? []).map((r) => <tr key={String(r.id ?? `${r.dept}${r.position_code}`)} className={Number(r.actual) > Number(r.planned) ? "bg-red-50" : ""}><td className="pl-3">{String(r.dept)}</td><td className="text-xs">{String(r.position_code ?? "")} {String(r.title ?? "")}</td><td className="text-right">{canHR ? <input className="input !py-0 !w-14 text-right" defaultValue={String(r.planned)} onBlur={async (e) => { if (Number(e.target.value) !== Number(r.planned)) { await act("headcount_set", { id: r.id, planned: Number(e.target.value), budget_month: r.budget_month }); hc.reload(); } }} /> : String(r.planned)}</td><td className="text-right font-bold">{String(r.actual)}</td><td className="text-right">{fmt.n(r.actual_base_month)}</td></tr>)}{(hc.rows ?? []).length === 0 && <tr><td colSpan={5} className="p-3 text-slate-500 text-sm">Chưa có định biên — bấm "Gợi ý từ thực tế" rồi sửa theo kế hoạch năm.</td></tr>}</tbody></table></div>
    </div>
    <div className="card p-0 overflow-auto"><div className="px-3 py-2 bg-slate-100 rounded-t-xl font-bold">Thưởng cống hiến đã chốt (lớp 4)</div><table className="tbl text-sm"><tbody>{(cb.rows ?? []).slice(0, 30).map((r) => <tr key={String(r.id)}><td className="pl-3">{String(r.full_name)}</td><td className="text-xs">{String(r.ref_id)} → trả tháng {String(r.period)}</td><td className="text-right">{String(r.points)} đ</td><td className="text-right font-bold">{fmt.n(r.amount)}</td></tr>)}</tbody></table></div>
  </div>;
}
'''
    return s
rw("src/components/panels/Career.tsx", car)
# MyPath: my pay
rw("src/components/panels/Career.tsx", lambda s: s.replace('  const cm = useData<R>("my_path", { track: "CM" }); const gs = useData<R>("my_path", { track: "GS" }); const cov = useData<R>("gs_coverage_me"); const contrib = useData<R>("my_contribution");','  const cm = useData<R>("my_path", { track: "CM" }); const gs = useData<R>("my_path", { track: "GS" }); const cov = useData<R>("gs_coverage_me"); const contrib = useData<R>("my_contribution"); const pay = useData<R>("my_pay"); const p = (pay.rows ?? [])[0];',1).replace('    <div className="text-xs text-slate-500">Vai của {sess.staffName}: {sess.role}. Muốn góp sáng kiến? <InitiativeForm /></div>','    {p && <div className="text-sm rounded-xl border p-2 bg-slate-50">💰 <b>Lương của tôi tính thế nào</b>: lớp 1 = thang {fmt.n(p.scale_amount)} × hệ số bậc {String(p.coef)} = <b>{fmt.n(p.base_l1)}</b>/tháng đủ công · phụ cấp {fmt.n(p.allowances_l3)} · thưởng tháng tối đa {fmt.n(p.bonus_l2_max)} (theo điều kiện học/dạy/thi/giám sát, trừ lỗi) · thưởng cống hiến quý theo điểm. <span className="text-xs text-slate-500">({String(p.source)})</span></div>}\n    <div className="text-xs text-slate-500">Vai của {sess.staffName}: {sess.role}. Muốn góp sáng kiến? <InitiativeForm /></div>',1))
# TodayBar KIND label
rw("src/components/TodayBar.tsx", lambda s: s.replace('THAY: ["Thay người", "bg-slate-200 text-slate-800"] };','THAY: ["Thay người", "bg-slate-200 text-slate-800"], GS_NGAY: ["Giám sát hôm nay", "bg-red-100 text-red-900"] };',1))
