import io, os
R="F:/ITRAN FARM/itran-os/"
def w(p, s): os.makedirs(os.path.dirname(R+p), exist_ok=True); io.open(R+p,"w",encoding="utf-8",newline="\n").write(s); print("w",p)
def rw(p, fn): s=io.open(R+p,encoding="utf-8").read(); n=fn(s); assert n!=s, p; io.open(R+p,"w",encoding="utf-8",newline="\n").write(n); print("ok",p)
w("src/app/marketing/page.tsx", 'import { Page } from "@/components/withSession"; import Marketing from "@/components/panels/Marketing";\nexport default function P() { return <Page title="Marketing – Truyền thông — chiến dịch · lịch nội dung · thương hiệu · lắng nghe & khủng hoảng">{(s) => <Marketing sess={s} />}</Page>; }\n')
rw("src/lib/queries.ts", lambda s: s.replace("  gs_today:", '''  mkt_campaigns: { sql: "select * from v_campaign_perf where farm_id=$1 order by starts_on desc" },
  mkt_contents: { sql: "select k.*, c.name as campaign_name, a.full_name as author_name, ap.full_name as approver_name from mkt_contents k left join mkt_campaigns c on c.id=k.campaign_id left join staff a on a.id=k.author_id left join staff ap on ap.id=k.approved_by where k.farm_id=$1 and k.planned_at >= current_date - 120 order by k.planned_at" },
  mkt_weekly: { sql: "select * from v_mkt_weekly where farm_id=$1 order by week" },
  mkt_assets: { sql: "select * from mkt_assets where farm_id=$1 order by approved desc, kind, title" },
  mkt_mentions: { sql: "select m.*, h.full_name as handler_name from mkt_mentions m left join staff h on h.id=m.handler_id where m.farm_id=$1 order by m.status='MOI' desc, m.ts desc limit 200" },
  gs_today:''',1))
rw("src/app/api/actions/route.ts", lambda s: s.replace('        case "gs_ack":', '''        case "mkt_campaign": { if (b.id) { const sets: string[] = []; const vals: unknown[] = [b.id, s.farmId]; for (const k of ["name","status","budget","ends_on","starts_on","objective","audience","kpi_target","channels","note"]) if (b[k] !== undefined) { vals.push(k === "kpi_target" ? JSON.stringify(b[k]) : b[k]); sets.push(`${k}=$${vals.length}`); } if (sets.length) await c.query(`update mkt_campaigns set ${sets.join(",")} where id=$1 and farm_id=$2`, vals); return { ok: true }; }
          const r = await c.query("insert into mkt_campaigns(farm_id,code,name,objective,channels,audience,starts_on,ends_on,budget,kpi_target,status,owner_id,utm_code,created_by) values ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,$12) returning id", [s.farmId, b.code, b.name, b.objective ?? null, b.channels ?? [], b.audience ?? null, b.starts_on ?? null, b.ends_on ?? null, Number(b.budget ?? 0), JSON.stringify(b.kpi_target ?? {}), b.status ?? "NHAP", s.staffId, String(b.code ?? "").toLowerCase()]); return { ok: true, id: r.rows[0].id }; }
        case "mkt_content": { if (b.id) { const sets: string[] = []; const vals: unknown[] = [b.id, s.farmId]; for (const k of ["status","approved_by","url","metrics","title","brief","planned_at","channel","kind","campaign_id","cost","note"]) if (b[k] !== undefined) { vals.push(k === "metrics" ? JSON.stringify(b[k]) : b[k]); sets.push(`${k}=$${vals.length}`); } if (b.status === "DUYET") { vals.push(s.staffId); sets.push(`approved_by=$${vals.length}`, "approved_at=now()"); } if (sets.length) await c.query(`update mkt_contents set ${sets.join(",")} where id=$1 and farm_id=$2`, vals); return { ok: true }; }
          const r = await c.query("insert into mkt_contents(farm_id,campaign_id,planned_at,channel,kind,title,brief,author_id,created_by,status) values ($1,$2,$3,$4,$5,$6,$7,$8,$8,'Y_TUONG') returning id", [s.farmId, b.campaign_id ?? null, b.planned_at, b.channel, b.kind ?? "BAI_VIET", b.title, b.brief ?? null, s.staffId]); return { ok: true, id: r.rows[0].id }; }
        case "mkt_asset": { await c.query("insert into mkt_assets(farm_id,kind,title,url,tags,version,created_by) values ($1,$2,$3,$4,$5,$6,$7)", [s.farmId, b.kind, b.title, b.url ?? null, b.tags ?? [], b.version ?? null, s.staffId]); return { ok: true }; }
        case "mkt_asset_approve": { if (!["tech_head","team_lead","director","owner"].includes(s.role)) throw new Error("ERR_FORBIDDEN_ROLE"); await c.query("update mkt_assets set approved=true, approved_by=$3 where id=$1 and farm_id=$2 and created_by is distinct from $3", [b.id, s.farmId, s.staffId]); return { ok: true }; }
        case "mkt_mention": { const r = await c.query("insert into mkt_mentions(farm_id,channel,source_url,author,summary,sentiment,severity,created_by) values ($1,$2,$3,$4,$5,$6,$7,$8) returning id", [s.farmId, b.channel, b.source_url ?? null, b.author ?? null, b.summary, b.sentiment ?? "TRUNG_TINH", b.severity ?? "THAP", s.staffId]); return { ok: true, id: r.rows[0].id }; }
        case "mkt_mention_update": { await c.query("update mkt_mentions set status=$3, response=coalesce($4,response), handler_id=$5, resolved_at=case when $3='DONG' then now() else resolved_at end where id=$1 and farm_id=$2", [b.id, s.farmId, b.status, b.response ?? null, s.staffId]); if (b.status === "DONG") await c.query("update tasks set status='XONG', done_by=$3, done_at=now() where farm_id=$1 and ref_table='mkt_mentions' and ref_id=$2 and status<>'XONG'", [s.farmId, b.id, s.staffId]); return { ok: true }; }
        case "gs_ack":''',1))
rw("src/lib/roles.ts", lambda s: s.replace('"/giam-sat": [...MGMT_ROLES, "team_lead", "worker"],','"/giam-sat": [...MGMT_ROLES, "team_lead", "worker"], "/marketing": [...MGMT_ROLES, "team_lead", "worker"],',1))
rw("src/components/Shell.tsx", lambda s: s.replace('items: [{ href: "/ban-hang", label: "Kinh doanh" }] },','items: [{ href: "/ban-hang", label: "Kinh doanh (bán hàng · CRM · POS · công nợ)" }, { href: "/marketing", label: "Marketing – Truyền thông" }] },',1).replace('desc: "Bán 5 kênh, báo giá, hợp đồng, khách, điểm, công nợ, POS", dept: "KDM"','desc: "Bán 5 kênh, báo giá, hợp đồng, khách, điểm, công nợ, POS · marketing, lịch nội dung, thương hiệu, khủng hoảng truyền thông", dept: "KDM"',1))
rw("src/lib/modules.ts", lambda s: s.replace('  "/du-lich": {', '''  "/marketing": { name: "Marketing – Truyền thông", dept: "KDM — Kinh doanh, marketing, CSKH", purpose: "Chiến dịch có mục tiêu/ngân sách/UTM → lịch nội dung đa kênh (người viết ≠ người duyệt) → đăng đúng giờ → đo → gắn lead/đơn/booking → ROI thật; kho tài sản thương hiệu đã duyệt; lắng nghe & xử lý khủng hoảng truyền thông theo SOP-KD-05.", users: "Trưởng KDM, nhân viên marketing/CSKH, GĐ (khủng hoảng)", steps: ["Thứ 6: lập lịch nội dung tuần sau theo kế hoạch bán/tour/mùa vụ", "Viết → gửi duyệt → người khác duyệt → đăng → cập nhật số đo 48h/7 ngày", "Ghi mọi phản hồi tiêu cực trong ngày; mức CAO → việc KHẨN xác minh 2h, phản hồi 24h", "Đóng chiến dịch → ROI"], sops: ["SOP-KD-02", "SOP-KD-05"], start: "Tab Tổng quan → Lịch nội dung.", kpis: ["Bài đúng lịch %", "Chi phí/lead", "ROAS", "Tiêu cực chưa phản hồi >24h = 0"] },
  "/du-lich": {''',1))
rw("src/lib/admin.ts", lambda s: s.replace('  { table: "dependent_claims",', '''  { table: "mkt_campaigns", pk: "id", label: "Marketing · chiến dịch", group: "Kinh doanh", farmScoped: true, softDelete: null, writeRoles: ["owner", "director", "tech_head", "team_lead", "it_engineer"] },
  { table: "mkt_contents", pk: "id", label: "Marketing · lịch nội dung", group: "Kinh doanh", farmScoped: true, softDelete: null, writeRoles: ["owner", "director", "tech_head", "team_lead", "worker", "it_engineer"] },
  { table: "mkt_assets", pk: "id", label: "Marketing · tài sản thương hiệu", group: "Kinh doanh", farmScoped: true, softDelete: null, writeRoles: ["owner", "director", "tech_head", "team_lead", "it_engineer"] },
  { table: "mkt_mentions", pk: "id", label: "Marketing · lắng nghe & khủng hoảng truyền thông", group: "Kinh doanh", farmScoped: true, softDelete: null, writeRoles: ["owner", "director", "tech_head", "team_lead", "worker", "it_engineer"] },
  { table: "dependent_claims",''',1))
rw("scripts/seed-history.ts", lambda s: s.replace('"scripts/seed-career.sql"]','"scripts/seed-career.sql", "scripts/seed-marketing.sql"]',1))
