import io
R = "F:/ITRAN FARM/itran-os/"
def rw(p, fn): s = io.open(R + p, encoding="utf-8").read(); n = fn(s); assert n != s, p; io.open(R + p, "w", encoding="utf-8", newline="\n").write(n); print("ok", p)

# actions: save_process handles inputs/outputs/documents/tools/visible_depts
def act(s):
    s = s.replace('''          else await c.query("update processes set dept_code=$2,name=$3,kind=$4,object_type=$5,trigger_text=$6,description=$7,sla=$8,owner_role=$9,kpi=$10,ui_path=$11,auto_start=$12 where code=$1", [code, b.dept_code, b.name, b.kind ?? "CORE", b.object_type ?? null, b.trigger_text ?? null, b.description ?? null, b.sla ?? null, b.owner_role ?? null, b.kpi ?? null, b.ui_path ?? null, JSON.stringify(b.auto_start ?? {})]);''',
    '''          else await c.query("update processes set dept_code=$2,name=$3,kind=$4,object_type=$5,trigger_text=$6,description=$7,sla=$8,owner_role=$9,kpi=$10,ui_path=$11,auto_start=$12, inputs=coalesce($13::jsonb,inputs), outputs=coalesce($14::jsonb,outputs), documents=coalesce($15::jsonb,documents), tools=coalesce($16::text[],tools), visible_depts=array_remove(array[$2::text] || coalesce((select array_agg(distinct x) from (select jsonb_array_elements(coalesce($13::jsonb,inputs))->>'from' as x union select jsonb_array_elements(coalesce($14::jsonb,outputs))->>'to') t where x is not null and x<>'*'), '{}'), null) where code=$1", [code, b.dept_code, b.name, b.kind ?? "CORE", b.object_type ?? null, b.trigger_text ?? null, b.description ?? null, b.sla ?? null, b.owner_role ?? null, b.kpi ?? null, b.ui_path ?? null, JSON.stringify(b.auto_start ?? {}), b.inputs ? JSON.stringify(b.inputs) : null, b.outputs ? JSON.stringify(b.outputs) : null, b.documents ? JSON.stringify(b.documents) : null, Array.isArray(b.tools) ? b.tools : null]);''')
    s = s.replace('''            [code, stepNo, st.name ?? `Bước ${stepNo}`, st.actor_role ?? null, st.dept_code ?? null, st.action ?? null, st.system_where ?? null, st.control ?? null, st.output ?? null, tools, JSON.stringify(st.materials ?? []), st.inputs ?? null, st.outputs ?? null, st.duration_min ?? null, st.sla_hours ?? null, st.form_table ?? null, Array.isArray(st.notify_roles) ? st.notify_roles : [], st.required ?? true, st.parallel_group ?? null, JSON.stringify(st.checklist ?? [])]);
          return { ok: true, step_no: stepNo };''', '''            [code, stepNo, st.name ?? `Bước ${stepNo}`, st.actor_role ?? null, st.dept_code ?? null, st.action ?? null, st.system_where ?? null, st.control ?? null, st.output ?? null, tools, JSON.stringify(st.materials ?? []), st.inputs ?? null, st.outputs ?? null, st.duration_min ?? null, st.sla_hours ?? null, st.form_table ?? null, Array.isArray(st.notify_roles) ? st.notify_roles : [], st.required ?? true, st.parallel_group ?? null, JSON.stringify(st.checklist ?? [])]);
          if (st.documents) await c.query("update process_steps set documents=$3 where process_code=$1 and step_no=$2", [code, stepNo, JSON.stringify(st.documents)]);
          // phòng ban trong bước tự vào visible_depts (mỗi bộ phận chỉ thấy quy trình liên quan)
          if (st.dept_code) await c.query("update processes set visible_depts = array(select distinct unnest(visible_depts || array[$2::text])) where code=$1", [code, st.dept_code]);
          return { ok: true, step_no: stepNo };''')
    return s
rw("src/app/api/actions/route.ts", act)

# queries: my dept
def q(s):
    return s.replace("  process_runs: {", '''  me: { sql: "select id, full_name, role, dept, position, position_code, farm_id, farm_ids from staff where id=app_staff()" },
  process_runs: {''', 1)
rw("src/lib/queries.ts", q)

# ProcessDesigner: side panel I/O + docs editor + flow diagram
def pd(s):
    s = s.replace('import AnyChart', 'import AnyChart') if False else s
    s = s.replace('import type { Sess } from "@/components/Shell";', 'import type { Sess } from "@/components/Shell";\nimport { ProcessFlow } from "@/components/ProcessFlow";', 1)
    # meta editor: after description label add I/O + docs editors (before the save buttons)
    marker = '            {canW && <div className="flex gap-2 mt-2 flex-wrap"><button className="btn-secondary !py-2" onClick={saveMeta}>Lưu thông tin</button>'
    assert marker in s
    io_editor = '''            <div className="grid lg:grid-cols-2 gap-3 mt-3 text-sm">
              <div className="rounded-xl bg-amber-50 border border-amber-200 p-2"><div className="flex items-center"><b>ĐẦU VÀO — nhận từ bộ phận nào</b>{canW && <button className="ml-auto underline text-xs" onClick={() => setMeta({ ...meta, inputs: [...((meta.inputs as R[]) ?? []), { from: "", what: "", via: "" }] })}>+ thêm</button>}</div>
                {(((meta.inputs as R[]) ?? [])).map((i, k) => <div key={k} className="flex gap-1 mt-1"><select className="input !w-32 !py-1 !text-xs" value={String(i.from ?? "")} onChange={(e) => setMeta({ ...meta, inputs: ((meta.inputs as R[]) ?? []).map((x, j) => j === k ? { ...x, from: e.target.value } : x) })}><option value="">bộ phận</option><option value="*">* mọi</option>{(depts.rows ?? []).map((d) => <option key={String(d.code)} value={String(d.code)}>{String(d.short ?? d.code)}</option>)}</select><input className="input !py-1 !text-xs" placeholder="nhận gì" value={String(i.what ?? "")} onChange={(e) => setMeta({ ...meta, inputs: ((meta.inputs as R[]) ?? []).map((x, j) => j === k ? { ...x, what: e.target.value } : x) })} /><input className="input !w-36 !py-1 !text-xs" placeholder="qua bảng/file" value={String(i.via ?? "")} onChange={(e) => setMeta({ ...meta, inputs: ((meta.inputs as R[]) ?? []).map((x, j) => j === k ? { ...x, via: e.target.value } : x) })} />{canW && <button className="text-red-700" onClick={() => setMeta({ ...meta, inputs: ((meta.inputs as R[]) ?? []).filter((_, j) => j !== k) })}>✕</button>}</div>)}</div>
              <div className="rounded-xl bg-emerald-50 border border-emerald-200 p-2"><div className="flex items-center"><b>ĐẦU RA — cấp cho bộ phận nào (1 → nhiều)</b>{canW && <button className="ml-auto underline text-xs" onClick={() => setMeta({ ...meta, outputs: [...((meta.outputs as R[]) ?? []), { to: "", what: "", via: "" }] })}>+ thêm</button>}</div>
                {(((meta.outputs as R[]) ?? [])).map((o, k) => <div key={k} className="flex gap-1 mt-1"><select className="input !w-32 !py-1 !text-xs" value={String(o.to ?? "")} onChange={(e) => setMeta({ ...meta, outputs: ((meta.outputs as R[]) ?? []).map((x, j) => j === k ? { ...x, to: e.target.value } : x) })}><option value="">bộ phận</option><option value="*">* mọi</option>{(depts.rows ?? []).map((d) => <option key={String(d.code)} value={String(d.code)}>{String(d.short ?? d.code)}</option>)}</select><input className="input !py-1 !text-xs" placeholder="cấp gì" value={String(o.what ?? "")} onChange={(e) => setMeta({ ...meta, outputs: ((meta.outputs as R[]) ?? []).map((x, j) => j === k ? { ...x, what: e.target.value } : x) })} /><input className="input !w-36 !py-1 !text-xs" placeholder="qua bảng/file" value={String(o.via ?? "")} onChange={(e) => setMeta({ ...meta, outputs: ((meta.outputs as R[]) ?? []).map((x, j) => j === k ? { ...x, via: e.target.value } : x) })} />{canW && <button className="text-red-700" onClick={() => setMeta({ ...meta, outputs: ((meta.outputs as R[]) ?? []).filter((_, j) => j !== k) })}>✕</button>}</div>)}</div>
              <div className="lg:col-span-2 rounded-xl bg-slate-50 border border-slate-200 p-2"><div className="flex items-center"><b>TÀI LIỆU · BIỂU MẪU · FILE · CÔNG CỤ · PHẦN MỀM cần cho quy trình</b>{canW && <button className="ml-auto underline text-xs" onClick={() => setMeta({ ...meta, documents: [...((meta.documents as R[]) ?? []), { kind: "BIEU_MAU", name: "", ref: "", required: true }] })}>+ thêm</button>}</div>
                {(((meta.documents as R[]) ?? [])).map((d, k) => <div key={k} className="flex gap-1 mt-1 items-center"><select className="input !w-32 !py-1 !text-xs" value={String(d.kind ?? "")} onChange={(e) => setMeta({ ...meta, documents: ((meta.documents as R[]) ?? []).map((x, j) => j === k ? { ...x, kind: e.target.value } : x) })}>{[["BIEU_MAU", "Biểu mẫu"], ["SOP", "SOP"], ["HO_SO", "Hồ sơ/sổ"], ["FILE", "File/giấy tờ"], ["CONG_CU", "Công cụ/thiết bị"], ["PHAN_MEM", "Màn hình/app"]].map(([v, l]) => <option key={v} value={v}>{l}</option>)}</select><input className="input !py-1 !text-xs" placeholder="tên" value={String(d.name ?? "")} onChange={(e) => setMeta({ ...meta, documents: ((meta.documents as R[]) ?? []).map((x, j) => j === k ? { ...x, name: e.target.value } : x) })} /><input className="input !w-44 !py-1 !text-xs" placeholder="bảng/đường dẫn/mã" value={String(d.ref ?? "")} onChange={(e) => setMeta({ ...meta, documents: ((meta.documents as R[]) ?? []).map((x, j) => j === k ? { ...x, ref: e.target.value } : x) })} /><label className="text-xs whitespace-nowrap"><input type="checkbox" checked={d.required !== false} onChange={(e) => setMeta({ ...meta, documents: ((meta.documents as R[]) ?? []).map((x, j) => j === k ? { ...x, required: e.target.checked } : x) })} /> bắt buộc</label>{canW && <button className="text-red-700" onClick={() => setMeta({ ...meta, documents: ((meta.documents as R[]) ?? []).filter((_, j) => j !== k) })}>✕</button>}</div>)}</div>
            </div>
'''
    s = s.replace(marker, io_editor + marker, 1)
    # flow diagram + side panel above steps table
    marker2 = '          {p && <div className="card p-0 overflow-auto"><div className="px-3 py-2 bg-stone-100 rounded-t-2xl flex items-center"><b>Các bước ({S.length})'
    assert marker2 in s
    flow = '''          {p && <div className="card"><div className="flex items-center mb-1"><b>Sơ đồ luồng: bộ phận nguồn ⇒ bước 1 → … → bước n ⇒ bộ phận nhận (tự vẽ theo khai báo)</b></div><ProcessFlow process={{ ...p, ...meta }} steps={S} depts={depts.rows ?? []} onStep={(st) => canW && setEditStep({ ...st })} />
            <div className="grid sm:grid-cols-3 gap-2 mt-2 text-xs"><div className="rounded-lg bg-amber-50 p-2"><b>Nhận từ:</b> {[...new Set((((meta.inputs ?? p.inputs) as R[]) ?? []).map((i) => String(i.from)))].join(", ") || "—"}</div><div className="rounded-lg bg-slate-50 p-2"><b>Bộ phận thực hiện:</b> {[...new Set(S.map((st) => String(st.dept_code ?? "")))].filter(Boolean).join(" → ") || "—"}</div><div className="rounded-lg bg-emerald-50 p-2"><b>Cấp cho:</b> {[...new Set((((meta.outputs ?? p.outputs) as R[]) ?? []).map((o) => String(o.to)))].join(", ") || "—"}</div></div>
            <div className="mt-2 text-xs"><b>Tài liệu/công cụ:</b> {(((meta.documents ?? p.documents) as R[]) ?? []).map((d, k) => <span key={k} className={`inline-block mr-1 mb-1 rounded-full px-2 py-0.5 border ${d.required !== false ? "bg-white border-slate-300" : "bg-slate-50 border-slate-200 text-slate-500"}`}>{String(d.kind)}: {String(d.name)}</span>)}</div></div>}
'''
    s = s.replace(marker2, flow + marker2, 1)
    # step editor: documents field
    s = s.replace('''              <label className="flex items-center gap-2 mt-5"><input type="checkbox" checked={editStep.required !== false}''', '''              <label className="lg:col-span-3">Tài liệu/biểu mẫu/file riêng của bước (mỗi dòng: loại|tên|tham chiếu)<textarea className="input font-mono text-xs" rows={2} value={((editStep.documents as R[]) ?? []).map((d) => `${d.kind ?? "BIEU_MAU"}|${d.name ?? ""}|${d.ref ?? ""}`).join("\\n")} onChange={(e) => setEditStep({ ...editStep, documents: e.target.value.split("\\n").filter((l) => l.trim()).map((l) => { const [kind, name, ref] = l.split("|"); return { kind: kind?.trim() || "BIEU_MAU", name: name?.trim() ?? "", ref: ref?.trim() ?? "", required: true }; }) })} placeholder="BIEU_MAU|Phiếu cân|weigh_tickets" /></label>
              <label className="flex items-center gap-2 mt-5"><input type="checkbox" checked={editStep.required !== false}''', 1)
    # visibility: staff sees only processes with own dept when worker/team_lead
    s = s.replace('  const P = procs.rows ?? []; const p = P.find((x) => x.code === code);', '  const me = useData("me"); const myDept = String(me.rows?.[0]?.dept ?? ""); const limited = ["worker", "team_lead"].includes(sess.role);\n  const P = (procs.rows ?? []).filter((x) => !limited || !myDept || ((x.visible_depts as string[]) ?? []).includes(myDept) || x.dept_code === myDept); const p = P.find((x) => x.code === code);', 1)
    return s
rw("src/components/panels/ProcessDesigner.tsx", pd)

# ToChuc: DeptGraph in sodo + io tabs; ProcessFlow in quytrinh; role visibility
def tc(s):
    s = s.replace('import ProcessDesigner from "@/components/panels/ProcessDesigner";', 'import ProcessDesigner from "@/components/panels/ProcessDesigner";\nimport { ProcessFlow, DeptGraph } from "@/components/ProcessFlow";', 1)
    s = s.replace('  const D = depts.rows ?? []; const P = procs.rows ?? []; const S = steps.rows ?? [];', '  const me = useData("me"); const myDept = String(me.rows?.[0]?.dept ?? ""); const limited = ["worker", "team_lead"].includes(sess.role);\n  const D = depts.rows ?? []; const P = (procs.rows ?? []).filter((x) => !limited || !myDept || ((x.visible_depts as string[]) ?? []).includes(myDept) || x.dept_code === myDept); const S = steps.rows ?? [];', 1)
    # sodo: add graph before block list
    s = s.replace('        <div className="text-sm text-stone-600">Công ty nông nghiệp tuần hoàn – hữu cơ – hướng xuất khẩu, mô hình công ty mẹ đa trại. Bấm phòng ban để xem chức năng nhiệm vụ · KPI · hồ sơ · quy trình · nhân sự · màn hình.</div>', '        <div className="card"><div className="font-bold mb-1">Sơ đồ liên kết phòng ban — mũi tên = luồng dữ liệu (đầu ra quy trình → phòng nhận), độ dày = số luồng; bấm phòng để lọc, rê chuột lên đường để xem gì · qua bảng nào</div><DeptGraph depts={D} io={IO} processes={P} focus={sel} onFocus={setSel} /></div>\n        <div className="text-sm text-stone-600">Bấm phòng ban để xem chức năng nhiệm vụ · KPI · hồ sơ · quy trình · nhân sự · màn hình.</div>', 1)
    # quytrinh detail: add flow diagram after header line
    s = s.replace('          <div className="grid sm:grid-cols-3 gap-2"><div className="kpi !p-2"><div className="l">Kích hoạt</div>', '          <ProcessFlow process={p} steps={ps} depts={D} />\n          <div className="grid sm:grid-cols-3 gap-2"><div className="kpi !p-2"><div className="l">Kích hoạt</div>', 1)
    # docs list in process detail
    s = s.replace('          <div className="text-xs text-stone-600">Dữ liệu chạy thẳng: bảng', '          <div><b>Tài liệu · biểu mẫu · file · công cụ · phần mềm cần dùng</b><ul className="list-disc pl-5 mt-1">{(((p.documents as R[]) ?? [])).map((d, k) => <li key={k}><span className="b-gray !text-xs">{String(d.kind)}</span> {String(d.name)} {d.ref ? <span className="text-stone-500 font-mono text-xs">[{String(d.ref)}]</span> : null}{d.required === false ? <span className="text-xs text-stone-400"> (tùy chọn)</span> : null}</li>)}{!((p.documents as R[]) ?? []).length && <li className="text-stone-500">chưa khai báo — thêm ở Khai báo quy trình</li>}</ul></div>\n          <div className="text-xs text-stone-600">Dữ liệu chạy thẳng: bảng', 1)
    # io tab: graph on top
    s = s.replace('      {tab === "io" && <div className="card p-0 overflow-auto"><div className="px-3 py-2 bg-stone-100 rounded-t-2xl font-bold">Ma trận liên hệ', '      {tab === "io" && <div className="space-y-3"><div className="card"><DeptGraph depts={D} io={IO} processes={P} focus={sel} onFocus={setSel} /></div><div className="card p-0 overflow-auto"><div className="px-3 py-2 bg-stone-100 rounded-t-2xl font-bold">Ma trận liên hệ', 1)
    s = s.replace('Ô "*" = mọi phòng. Mỗi luồng là một bảng/view/export/chủ đề event bus cụ thể → phòng nhận thấy ngay số liệu (realtime), không phải đi hỏi; mọi bảng đều xuất/nhập CSV được ở Quản trị DL.</div></div>}', 'Ô "*" = mọi phòng. Mỗi luồng là một bảng/view/export/chủ đề event bus cụ thể → phòng nhận thấy ngay số liệu (realtime), không phải đi hỏi; mọi bảng đều xuất/nhập CSV được ở Quản trị DL.</div></div></div>}', 1)
    return s
rw("src/components/panels/ToChuc.tsx", tc)
