import io
p="F:/ITRAN FARM/itran-os/src/components/panels/DuTru.tsx"; s=io.open(p,encoding="utf-8").read()
def rep(a,b):
    global s
    assert a in s, a[:60]; s=s.replace(a,b,1)
rep('function Block({ b, title, hint, R0, W }: { b: string; title: string; hint: string; R0: R[]; W: R[] }) { const bad = R0.filter((r) => r.flag !== "OK");',
'''function Block({ b, title, hint, R0, W, groups, sess, onChanged }: { b: string; title: string; hint: string; R0: R[]; W: R[]; groups: R[]; sess: Sess; onChanged: () => void }) {
  const [gsel, setGsel] = useState<string>(""); const [pick, setPick] = useState<string>(""); const cat = useData("reserve_catalog"); const [nf, setNf] = useState<R>({}); const [rf, setRf] = useState<R>({ reason: "NHAP_MUA" }); const [msg2, setMsg2] = useState("");
  const G = groups.filter((g) => g.block === b); const R1 = gsel ? R0.filter((r) => r.stock_group === gsel) : R0; const bad = R1.filter((r) => !["OK", "TRONG"].includes(String(r.flag)));
  const canPick = ["owner", "director", "tech_head", "it_engineer", "accountant", "team_lead"].includes(sess.role);
  const receipt = async () => { const j = await fetch("/api/events/inventory_moves", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ client_ref: crypto.randomUUID(), warehouse_id: rf.warehouse_id, sku: rf.sku, direction: 1, qty: Number(rf.qty), unit: (cat.rows ?? []).find((c) => c.sku === rf.sku)?.unit ?? "kg", lot_no: rf.lot_no || `L${new Date().toISOString().slice(2, 10).replace(/-/g, "")}`, unit_cost: rf.unit_cost ? Number(rf.unit_cost) : undefined, reason: rf.reason, from_to: rf.from_to || undefined }) }).then((r) => r.json()); const ok = j.results?.[0]?.status === "CREATED"; setMsg2(ok ? "Đã nhập kho — số liệu dự trữ cập nhật" : `Lỗi: ${JSON.stringify(j.results?.[0]?.errors ?? j.error)}`); if (ok) { setRf({ reason: rf.reason, warehouse_id: rf.warehouse_id }); onChanged(); } };''')
rep('''    return <div className="space-y-3">
      <div className="grid grid-cols-2 sm:grid-cols-4 gap-2"><div className="kpi"><div className="l">Mặt hàng có tồn</div>''','''    return <div className="space-y-3">
      <div className="grid grid-cols-2 sm:grid-cols-3 lg:grid-cols-5 xl:grid-cols-7 gap-2">{G.map((g) => { const rows = R0.filter((r) => r.stock_group === g.code); const nbad = rows.filter((r) => !["OK", "TRONG"].includes(String(r.flag))).length; const dmin = Math.min(...rows.map((r) => r.days_left == null ? 9e9 : Number(r.days_left))); return <div key={String(g.code)} role="button" onClick={() => setGsel(gsel === g.code ? "" : String(g.code))} className={`text-left rounded-xl border p-2 cursor-pointer ${gsel === g.code ? "border-emerald-600 bg-emerald-50" : nbad ? "border-red-300 bg-red-50/40" : "bg-white"}`}><div className="text-sm font-bold">{String(g.icon ?? "")} {String(g.name)}</div><div className="text-xs text-slate-600">{rows.length} mặt hàng · {rows.filter((r) => Number(r.qty) > 0).length} có tồn{nbad ? <span className="text-red-700 font-semibold"> · {nbad} cần bổ sung</span> : ""}</div><div className="text-xs text-slate-500">{dmin < 9e9 ? `còn ít nhất ${dmin} ngày` : "chưa có mức dùng"} · <button type="button" className="underline" onClick={(e) => { e.stopPropagation(); setPick(pick === g.code ? "" : String(g.code)); }}>chọn mặt hàng</button></div></div>; })}</div>
      {pick && <div className="card"><div className="flex items-center gap-2 flex-wrap"><b>Chọn mặt hàng theo dõi dự trữ — nhóm {String(G.find((g) => g.code === pick)?.name)}</b><span className="text-xs text-slate-500">ví dụ: {String(G.find((g) => g.code === pick)?.examples ?? "")}</span><button className="ml-auto text-sm underline" onClick={() => setPick("")}>đóng</button></div>
        <div className="flex flex-wrap gap-1 mt-2">{(cat.rows ?? []).filter((c) => c.stock_group === pick).map((c) => <label key={String(c.sku)} className={`rounded-lg border px-2 py-1 text-sm cursor-pointer ${c.reserve ? "bg-emerald-50 border-emerald-400" : "bg-white"}`}><input type="checkbox" className="mr-1" checked={!!c.reserve} disabled={!canPick} onChange={async (e) => { await act("set_reserve", { sku: c.sku, reserve: e.target.checked }); cat.reload(); onChanged(); }} />{String(c.name)} <span className="text-xs text-slate-400">({String(c.unit)})</span></label>)}</div>
        {canPick && <div className="flex gap-2 mt-2 flex-wrap"><input className="input !w-64" placeholder="Thêm mặt hàng mới (tên)" value={String(nf.name ?? "")} onChange={(e) => setNf({ ...nf, name: e.target.value })} /><input className="input !w-24" placeholder="đv" value={String(nf.unit ?? "")} onChange={(e) => setNf({ ...nf, unit: e.target.value })} /><input className="input !w-28" type="number" placeholder="HSD ngày" value={String(nf.shelf_life_days ?? "")} onChange={(e) => setNf({ ...nf, shelf_life_days: e.target.value })} /><button className="btn-primary !py-2" disabled={!nf.name} onClick={async () => { const j = await act("add_reserve_item", { ...nf, group: pick, shelf_life_days: nf.shelf_life_days ? Number(nf.shelf_life_days) : null }); if (j.ok) { setNf({}); cat.reload(); onChanged(); } else setMsg2(String(j.error)); }}>＋ Thêm & theo dõi</button></div>}</div>}
      <div className="card"><div className="flex items-center gap-2 flex-wrap"><b>Nhập kho nhanh</b><span className="text-xs text-slate-500">— mọi bộ phận tự nhập phần mình (ruộng → K3, khu D → K5, gà → K5, mua → K1/K2, D5 → K4); công nhân dùng form 3 chạm NHẬP/XUẤT kho trong Ca của tôi; sổ ghi ai nhập, lô nào, từ đâu</span></div>
        <div className="grid sm:grid-cols-3 lg:grid-cols-7 gap-2 mt-2"><select className="input" value={String(rf.warehouse_id ?? "")} onChange={(e) => setRf({ ...rf, warehouse_id: e.target.value })}><option value="">Kho</option>{W.map((w) => <option key={String(w.warehouse_id)} value={String(w.warehouse_id)}>{String(w.code)} {String(w.name)}</option>)}</select><select className="input lg:col-span-2" value={String(rf.sku ?? "")} onChange={(e) => setRf({ ...rf, sku: e.target.value })}><option value="">Mặt hàng (đang theo dõi)</option>{G.map((g) => <optgroup key={String(g.code)} label={String(g.name)}>{(cat.rows ?? []).filter((c) => c.stock_group === g.code && c.reserve).map((c) => <option key={String(c.sku)} value={String(c.sku)}>{String(c.name)}</option>)}</optgroup>)}</select><input className="input" type="number" placeholder="Số lượng" value={String(rf.qty ?? "")} onChange={(e) => setRf({ ...rf, qty: e.target.value })} /><input className="input" placeholder="Số lô (tự sinh nếu trống)" value={String(rf.lot_no ?? "")} onChange={(e) => setRf({ ...rf, lot_no: e.target.value })} /><select className="input" value={String(rf.reason)} onChange={(e) => setRf({ ...rf, reason: e.target.value })}>{[["NHAP_MUA", "Mua"], ["NHAP_SX", "Sản xuất/thu hoạch"], ["TRA", "Trả lại"], ["CHUYEN", "Chuyển đến"], ["DIEU_CHINH", "Điều chỉnh"]].map(([k, l]) => <option key={k} value={k}>{l}</option>)}</select><input className="input" placeholder="Từ (NCC/bộ phận/ô)" value={String(rf.from_to ?? "")} onChange={(e) => setRf({ ...rf, from_to: e.target.value })} /><input className="input" type="number" placeholder="Đơn giá" value={String(rf.unit_cost ?? "")} onChange={(e) => setRf({ ...rf, unit_cost: e.target.value })} /><button className="btn-primary !py-2" disabled={!rf.warehouse_id || !rf.sku || !rf.qty} onClick={receipt}>Nhập</button></div>{msg2 && <div className="text-sm mt-1 text-emerald-700">{msg2}</div>}</div>
      <div className="grid grid-cols-2 sm:grid-cols-4 gap-2"><div className="kpi"><div className="l">Mặt hàng theo dõi{gsel ? " (nhóm)" : ""}</div>''')
rep('<div className="v">{R0.length}</div></div><div className="kpi"><div className="l">Cần bổ sung</div>','<div className="v">{R1.length} <span className="text-base font-normal text-slate-500">· {R1.filter((r) => Number(r.qty) > 0).length} có tồn</span></div></div><div className="kpi"><div className="l">Cần bổ sung</div>')
rep('<div className="v">{fmt.n(R0.reduce((a, r) => a + Number(r.incoming_po)','<div className="v">{fmt.n(R1.reduce((a, r) => a + Number(r.incoming_po)')
rep('<div className="grid md:grid-cols-2 gap-3">{[...R0].sort(','<div className="grid md:grid-cols-2 gap-3">{[...R1].filter((r) => Number(r.qty) > 0 || Number(r.use_per_day) > 0).sort(')
rep('<tbody>{R0.map((r) => { const f = FLAG[String(r.flag)] ?? FLAG.OK;','<tbody>{R1.map((r) => { const f = FLAG[String(r.flag)] ?? FLAG.OK;')
rep('{!R0.length && <div className="p-3 text-sm text-slate-500">Chưa có tồn trong khối này.</div>}','{!R1.length && <div className="p-3 text-sm text-slate-500">Chưa có mặt hàng theo dõi — bấm "chọn mặt hàng" ở thẻ nhóm.</div>}')
rep('<td className="pl-3">{String(r.name)}<div className="text-xs text-slate-500">{String(r.kind)} · {String(r.sku)}</div></td>','<td className="pl-3">{String(r.name)}<div className="text-xs text-slate-500">{String(r.group_icon ?? "")} {String(r.group_name ?? r.kind)} · {String(r.sku)}</div></td>')
rep('const FLAG: Record<string, [string, string]> = { HET:','const FLAG: Record<string, [string, string]> = { TRONG: ["Trống", "bg-slate-100 text-slate-600"], HET:')
rep('const dash = useData("stock_dashboard");','const dash = useData("stock_dashboard"); const sgroups = useData("stock_groups");')
rep('<Block R0={rows("DAU_VAO")} W={(fill.rows ?? []).filter((w) => w.block === "DAU_VAO")} b="DAU_VAO"','<Block groups={sgroups.rows ?? []} sess={sess} onChanged={() => { dash.reload(); fill.reload(); }} R0={rows("DAU_VAO")} W={(fill.rows ?? []).filter((w) => w.block === "DAU_VAO")} b="DAU_VAO"')
rep('<Block R0={rows("DAU_RA")} W={(fill.rows ?? []).filter((w) => w.block === "DAU_RA")} b="DAU_RA"','<Block groups={sgroups.rows ?? []} sess={sess} onChanged={() => { dash.reload(); fill.reload(); }} R0={rows("DAU_RA")} W={(fill.rows ?? []).filter((w) => w.block === "DAU_RA")} b="DAU_RA"')
rep('{msg && <div className="rounded-xl bg-emerald-50','{!(dash.rows ?? []).some((r) => Number(r.qty) > 0) && dash.rows && <div className="rounded-xl bg-amber-50 border border-amber-300 px-3 py-2 text-sm">Trại {sess.farmId} chưa có tồn kho — chọn trại F01 (góc trên trái) để xem dữ liệu, hoặc nhập kho bên dưới.</div>}\n    {msg && <div className="rounded-xl bg-emerald-50')
io.open(p,"w",encoding="utf-8",newline="\n").write(s); print("ok")
