import io, os
R="F:/ITRAN FARM/itran-os/"
def w(p, s): os.makedirs(os.path.dirname(R+p) or R, exist_ok=True); io.open(R+p,"w",encoding="utf-8",newline="\n").write(s); print("w",p)
def rw(p, fn): s=io.open(R+p,encoding="utf-8").read(); n=fn(s); assert n!=s, p; io.open(R+p,"w",encoding="utf-8",newline="\n").write(n); print("ok",p)
# 1) queries: heavy views read from cache tables (fallback live if empty)
def q(s):
    s=s.replace('  stock_dashboard: { sql: "select * from v_stock_dashboard where farm_id=$1 order by block,','  stock_dashboard: { sql: "select * from cache_stock_dashboard where farm_id=$1 order by block,',1)
    s=s.replace('  herd_forecast_series: { sql: "select h.horizon, f.* from (values (0),(30),(60),(90)) h(horizon), lateral herd_forecast($1, h.horizon) f order by f.class_code, h.horizon" },','  herd_forecast_series: { sql: "select x.* from cache_kv k, jsonb_to_recordset(k.payload) as x(horizon int, class_code text, class_name text, head_now numeric, head_forecast numeric, births numeric, exits numeric) where k.farm_id=$1 and k.key=\'herd_forecast_series\' order by class_code, horizon", cache: true },',1)
    s=s.replace('  feed_forecast_series: { sql: "select h.horizon, sum(f.kg_day_forecast) as kg_day, sum(f.head_forecast) as head from (values (0),(30),(60),(90)) h(horizon), lateral feed_forecast($1, h.horizon) f group by h.horizon order by h.horizon" },','  feed_forecast_series: { sql: "select x.* from cache_kv k, jsonb_to_recordset(k.payload) as x(horizon int, kg_day numeric, head numeric) where k.farm_id=$1 and k.key=\'feed_forecast_series\' order by horizon", cache: true },',1)
    s=s.replace('  warehouse_fill: { sql: "select * from v_warehouse_fill where farm_id=$1 order by block, code" },','  warehouse_fill: { sql: "select x.* from cache_kv k, jsonb_to_recordset(k.payload) as x(farm_id text, warehouse_id text, code text, name text, block text, area text, unit_kind text, capacity numeric, qty numeric, pct_full numeric, skus int, bins int) where k.farm_id=$1 and k.key=\'warehouse_fill\' order by block, code", cache: true },',1)
    s=s.replace('export const QUERIES: Record<string, { sql: string; params?: string[] }> = {','export const QUERIES: Record<string, { sql: string; params?: string[]; cache?: boolean; ttl?: number }> = {\n  cache_status: { sql: "select farm_id, refreshed_at, (select dirty_at from cache_dirty d where d.farm_id=$1) as dirty_at from cache_kv where farm_id=$1 and key=\'warehouse_fill\'" },',1)
    return s
rw("src/lib/queries.ts", q)
# 2) data API: in-memory TTL cache + auto-refresh farm cache when dirty/stale (debounced) + Cache-Control
def api(s):
    s=s.replace('import { canView } from "@/lib/roles";','import { canView } from "@/lib/roles";\nimport { adminPool } from "@/lib/db";\nconst MEM = new Map<string, { at: number; rows: unknown[] }>(); const REFRESHING = new Set<string>();\nconst HEAVY = new Set(["stock_dashboard", "warehouse_fill", "herd_forecast_series", "feed_forecast_series", "supervision_weekly", "supervision_dept_weekly", "bonus_eval", "competency_matrix", "mrp_run", "plan_supply", "replenishment", "supplier_scorecard", "abc_suggest", "kpi_owner_weekly", "consolidated"]);\nasync function ensureFarmCache(farm: string) { const key = "cache:" + farm; if (REFRESHING.has(key)) return; try { const r = (await adminPool().query("select (select max(refreshed_at) from cache_kv where farm_id=$1) as at, (select dirty_at from cache_dirty where farm_id=$1) as dirty", [farm])).rows[0]; const stale = !r?.at || Date.now() - new Date(r.at).getTime() > 15 * 60e3 || (r?.dirty && new Date(r.dirty) > new Date(r.at)); if (!stale) return; REFRESHING.add(key); adminPool().query("select refresh_farm_cache($1)", [farm]).then(() => adminPool().query("delete from cache_dirty where farm_id=$1 and dirty_at <= (select max(refreshed_at) from cache_kv where farm_id=$1)", [farm])).catch(() => null).finally(() => { REFRESHING.delete(key); for (const k of MEM.keys()) if (k.startsWith(farm + "|")) MEM.delete(k); }); } catch { REFRESHING.delete(key); } }',1)
    s=s.replace('''  try {
    const rows = await withCtx(ctx, async (c) => (await c.query(qd.sql, args)).rows);
    return NextResponse.json({ rows });''','''  try {
    if (qd.cache || view === "stock_dashboard") { void ensureFarmCache(farm); }
    const memKey = `${farm}|${sess.role}|${view}|${args.join(",")}`; const ttl = (qd.ttl ?? (HEAVY.has(view) ? 60 : 0)) * 1000; const hit = ttl ? MEM.get(memKey) : undefined;
    if (hit && Date.now() - hit.at < ttl && !url.searchParams.has("fresh")) return NextResponse.json({ rows: hit.rows, cached: true }, { headers: { "x-cache": "HIT", "cache-control": "private, max-age=30" } });
    const rows = await withCtx(ctx, async (c) => (await c.query(qd.sql, args)).rows);
    if (ttl) { MEM.set(memKey, { at: Date.now(), rows }); if (MEM.size > 2000) MEM.delete(MEM.keys().next().value as string); }
    return NextResponse.json({ rows }, { headers: { "x-cache": ttl ? "MISS" : "BYPASS" } });''',1)
    return s
rw("src/app/api/data/[view]/route.ts", api)
# 3) jobs: cache refresh (every run of dispatch = mỗi phút → chỉ farm dirty), maint weekly, agg incremental (only yesterday) in /all
def jb(s):
    s=s.replace('    if (job === "agg") out[`agg:${f}`] = await backfillAgg(f, Number(url.searchParams.get("days") ?? 35));','''    if (job === "agg") out[`agg:${f}`] = await backfillAgg(f, Number(url.searchParams.get("days") ?? 35));
    if (job === "cache" || job === "dispatch" || job === "all") { const dirty = (await adminPool().query("select 1 from cache_dirty where farm_id=$1 and dirty_at > coalesce((select max(refreshed_at) from cache_kv where farm_id=$1), '1970-01-01')", [f])).rowCount; const old = (await adminPool().query("select coalesce(max(refreshed_at), '1970-01-01') < now() - interval '15 minutes' as old from cache_kv where farm_id=$1", [f])).rows[0]?.old; if (job === "cache" || job === "all" || dirty || old) { out[`cache:${f}`] = (await adminPool().query("select refresh_farm_cache($1) as r", [f])).rows[0].r; await adminPool().query("delete from cache_dirty where farm_id=$1", [f]); } }
    if (job === "maint" || (job === "all" && new Date().getDay() === 0)) { out[`maint:${f}`] = (await adminPool().query("select itran_maintenance() as r")).rows[0].r; }''',1)
    return s
rw("src/app/api/jobs/[job]/route.ts", jb)
# 4) instrumentation: cache every 5 min, maint Sunday 02:30
rw("src/instrumentation.ts", lambda s: s.replace('    if (hm === "06:00" && lastMorning !== day) { lastMorning = day; for (const f of await farms()) await call("tasks", f); }','    if (hm === "06:00" && lastMorning !== day) { lastMorning = day; for (const f of await farms()) await call("tasks", f); }\n    if (now.getMinutes() % 5 === 0 && now.getSeconds() < 30) { for (const f of await farms()) await call("cache", f); }\n    if (hm === "02:30" && now.getDay() === 0 && lastMorning !== "maint" + day) { for (const f of await farms()) { await call("maint", f); break; } }',1))
# 5) DuTru: show cache freshness + refresh button
rw("src/components/panels/DuTru.tsx", lambda s: s.replace('const dash = useData("stock_dashboard"); const sgroups = useData("stock_groups");','const dash = useData("stock_dashboard"); const sgroups = useData("stock_groups"); const cst = useData("cache_status");',1).replace('{msg && <div className="rounded-xl bg-emerald-50','<div className="text-xs text-slate-500 flex items-center gap-2">Số liệu dự trữ/dự báo tính từ bản cache theo trại (làm mới ≤15 phút hoặc ngay khi có nhập/xuất/đàn thay đổi){(cst.rows ?? [])[0]?.refreshed_at ? ` · cập nhật ${fmt.dt(String((cst.rows ?? [])[0].refreshed_at))}` : ""}<button className="underline" onClick={async () => { await fetch("/api/actions", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ action: "refresh_cache" }) }); dash.reload(); fill.reload(); cst.reload(); }}>⟳ làm mới ngay</button></div>\n    {msg && <div className="rounded-xl bg-emerald-50',1))
rw("src/app/api/actions/route.ts", lambda s: s.replace('        case "sup_check": {','        case "refresh_cache": { const r = await c.query("select refresh_farm_cache($1) as r", [s.farmId]); await c.query("delete from cache_dirty where farm_id=$1", [s.farmId]).catch(() => null); return { ok: true, ...r.rows[0].r }; }\n        case "sup_check": {',1))
