import io, os
R="F:/ITRAN FARM/itran-os/"
def w(p, s): os.makedirs(os.path.dirname(R+p) or R, exist_ok=True); io.open(R+p,"w",encoding="utf-8",newline="\n").write(s); print("w",p)
def rw(p, fn): s=io.open(R+p,encoding="utf-8").read(); n=fn(s); assert n!=s, p; io.open(R+p,"w",encoding="utf-8",newline="\n").write(n); print("ok",p)
# queries
rw("src/lib/queries.ts", lambda s: s.replace("  stock_dashboard: {", '''  my_supervision: { sql: "select a.*, coalesce(a.target_dept, s.full_name) as target_label from supervision_assignments a left join staff s on s.id=a.target_staff_id where a.farm_id=$1 and a.active and (a.supervisor_id=app_staff() or app_role() in ('owner','director','auditor','it_engineer')) order by a.id" },
  supervision_targets: { sql: "select s.id, s.full_name, s.dept, s.position_code, s.role from staff s join supervision_assignments a on a.farm_id=s.farm_id and a.active and (a.target_staff_id=s.id or (a.target_staff_id is null and (a.target_dept=s.dept or a.target_dept is null))) where s.farm_id=$1 and s.active and s.role in ('worker','team_lead') and (a.supervisor_id=app_staff() or app_role() in ('owner','director','auditor','it_engineer')) group by s.id order by s.dept, s.id" },
  supervision_criteria: { sql: "select * from supervision_criteria where active order by position, id" },
  supervision_week: { sql: "select ss.*, c.name as criteria_name, c.method as cmethod, st.full_name, st.dept, st.position_code from supervision_scores ss join supervision_criteria c on c.id=ss.criteria_id join staff st on st.id=ss.staff_id where ss.farm_id=$1 and ss.week_start=coalesce(nullif($2,'')::date, date_trunc('week', current_date)::date) order by st.dept, st.id, c.position", params: ["week"] },
  supervision_weekly: { sql: "select * from v_supervision_weekly where farm_id=$1 and week_start >= current_date - 100 order by week_start desc, dept, staff_id" },
  supervision_dept_weekly: { sql: "select * from v_supervision_dept_weekly where farm_id=$1 and week_start >= current_date - 100 order by week_start, dept" },
  supervision_checks_recent: { sql: "select sc.*, s.full_name as target_name, sv.full_name as supervisor_name from supervision_checks sc left join staff s on s.id=sc.target_staff_id left join staff sv on sv.id=sc.supervisor_id where sc.farm_id=$1 and sc.status='ACTIVE' order by sc.ts desc limit 200" },
  my_training: { sql: "select t.*, tr.full_name as trainer_name, te.full_name as trainee_name, (select score from training_tests x where x.session_id=t.id order by taken_at desc limit 1) as score from training_sessions t join staff tr on tr.id=t.trainer_id join staff te on te.id=t.trainee_id where t.farm_id=$1 and (t.trainer_id=app_staff() or t.trainee_id=app_staff() or app_role() in ('owner','director','tech_head','it_engineer','accountant','auditor')) and t.week_start >= current_date - 60 order by t.week_start desc, t.trainee_id" },
  training_stats: { sql: "select to_char(week_start,'IYYY-IW') as wk, week_start, count(*) as planned, count(*) filter (where status='XONG') as done, round(avg((select score from training_tests x where x.session_id=t.id limit 1)),1) as avg_score from training_sessions t where farm_id=$1 and week_start >= current_date - 180 group by 1,2 order by 2" },
  competency_matrix: { sql: "select vc.staff_id, vc.full_name, vc.dept, count(*) as n_sop, count(*) filter (where level in ('THUAN_THUC','DAY_DUOC')) as mastered, count(*) filter (where level='THUC_HANH') as practicing, count(*) filter (where level='CHUA_HOC') as not_started, round(100.0*count(*) filter (where level in ('THUAN_THUC','DAY_DUOC'))/count(*),0) as pct from v_training_curriculum vc where vc.farm_id=$1 group by 1,2,3 order by pct desc" },
  bonus_eval: { sql: "select * from bonus_eval($1, coalesce(nullif($2,''), to_char(current_date,'YYYY-MM')))", params: ["period"] },
  bonus_ledger: { sql: "select b.*, s.full_name from bonus_ledger b join staff s on s.id=b.staff_id where b.farm_id=$1 order by b.period desc, b.staff_id" },
  stock_dashboard: {''',1))
# actions
rw("src/app/api/actions/route.ts", lambda s: s.replace('        case "publish_plan": {', '''        case "sup_check": { const r = await c.query("insert into supervision_checks(farm_id, created_by, client_ref, supervisor_id, target_dept, target_staff_id, sop_code, criteria_id, week_start, item, result, severity, note, evidence_url, corrective, corrective_due) values ($1,$2,$3,$2,$4,$5,$6,$7,date_trunc('week', current_date)::date,$8,$9,$10,$11,$12,$13,$14) returning id, points", [s.farmId, s.staffId, b.client_ref ?? crypto.randomUUID(), b.target_dept ?? null, b.target_staff_id ?? null, b.sop_code ?? null, b.criteria_id ?? null, b.item, b.result, b.severity ?? null, b.note ?? null, b.evidence_url ?? null, b.corrective ?? null, b.corrective_due ?? null]); await c.query("select run_supervision_auto($1, date_trunc('week', current_date)::date)", [s.farmId]).catch(() => null); return { ok: true, ...r.rows[0] }; }
        case "run_supervision": { const r = await c.query("select run_supervision_auto($1, coalesce($2::date, date_trunc('week', current_date)::date)) as n", [s.farmId, b.week ?? null]); return { ok: true, n: r.rows[0].n }; }
        case "complete_training": { const r = await c.query("select complete_training($1,$2,$3,$4,$5) as j", [b.id, Number(b.hours ?? 2), Number(b.score ?? 0), b.examiner_id ?? null, b.notes ?? null]); return { ok: true, ...r.rows[0].j }; }
        case "gen_training_week": { if (!["owner","director","tech_head","it_engineer"].includes(s.role)) throw new Error("ERR_FORBIDDEN_ROLE"); const r = await c.query("select gen_training_week($1) as n", [s.farmId]); const r2 = await c.query("select gen_supervision_tasks($1) as n", [s.farmId]); return { ok: true, training: r.rows[0].n, supervision: r2.rows[0].n }; }
        case "close_bonus": { if (!["owner","director","accountant"].includes(s.role)) throw new Error("ERR_FORBIDDEN_ROLE"); const r = await c.query("select close_bonus($1,$2) as n", [s.farmId, b.period]); return { ok: true, n: r.rows[0].n }; }
        case "apply_bonus": { if (!["owner","director","accountant"].includes(s.role)) throw new Error("ERR_FORBIDDEN_ROLE"); const r = await c.query("select apply_bonus_to_payroll($1,$2::date) as n", [s.farmId, b.month]); return { ok: true, n: r.rows[0].n }; }
        case "publish_plan": {''',1))
# admin
rw("src/lib/admin.ts", lambda s: s.replace('  { table: "plan_scenarios", pk: "id",', '''  { table: "supervision_criteria", pk: "id", label: "Giám sát · TIÊU CHÍ & thang điểm theo vị trí (auto SQL / quan sát)", group: "Nhân sự", farmScoped: false, softDelete: "active", writeRoles: ["owner", "director", "auditor", "it_engineer", "tech_head"], codePrefix: "SC" },
  { table: "supervision_assignments", pk: "id", label: "Giám sát · phân công người giám sát ↔ bộ phận/người", group: "Nhân sự", farmScoped: true, softDelete: "active", writeRoles: ["owner", "director", "auditor", "it_engineer", "tech_head"], codePrefix: "GS" },
  { table: "training_sessions", pk: "id", label: "Đào tạo · buổi học tuần (người dạy = cấp trên)", group: "Nhân sự", farmScoped: true, softDelete: "status", writeRoles: OPS, codePrefix: "DT" },
  { table: "training_tests", pk: "id", label: "Đào tạo · bài kiểm tra", group: "Nhân sự", farmScoped: true, softDelete: null, writeRoles: OPS, codePrefix: "KT" },
  { table: "staff_competencies", pk: "staff_id", label: "Đào tạo · ma trận năng lực (nhân sự × SOP)", group: "Nhân sự", farmScoped: true, softDelete: null, writeRoles: OPS },
  { table: "bonus_ledger", pk: "id", label: "Thưởng · sổ thưởng tháng (giải trình)", group: "Nhân sự", farmScoped: true, softDelete: null, writeRoles: ["owner", "director", "accountant"] },
  { table: "plan_scenarios", pk: "id",''',1))
# jobs: weekly + daily
rw("src/app/api/jobs/[job]/route.ts", lambda s: s.replace('out[`dunning:${f}`] = (await adminPool().query("select run_dunning($1) as n", [f])).rows[0].n;','out[`dunning:${f}`] = (await adminPool().query("select run_dunning($1) as n", [f])).rows[0].n; out[`supervision:${f}`] = (await adminPool().query("select run_supervision_auto($1) as n", [f])).rows[0].n; if (new Date().getDay() === 1) { out[`training:${f}`] = (await adminPool().query("select gen_training_week($1) as n", [f])).rows[0].n; out[`sup_tasks:${f}`] = (await adminPool().query("select gen_supervision_tasks($1) as n", [f])).rows[0].n; await adminPool().query("select run_supervision_auto($1, (date_trunc(\'week\', current_date) - interval \'7 days\')::date)", [f]); }',1))
# roles: pages
rw("src/lib/roles.ts", lambda s: s.replace('export function canView','export const _x = 0;\nexport function canView',1).replace('"/mua-hang": [...MGMT_ROLES, "team_lead", "worker"],','"/mua-hang": [...MGMT_ROLES, "team_lead", "worker"], "/giam-sat": [...MGMT_ROLES, "team_lead"],',1))
# page giam-sat + panel
w("src/app/giam-sat/page.tsx", '''import { Page } from "@/components/withSession"; import GiamSat from "@/components/panels/GiamSat";
export default function P() { return <Page title="Giám sát — tiêu chí theo vị trí · chấm điểm tuần · lỗi & khắc phục">{(s) => <GiamSat sess={s} />}</Page>; }
''')
w("src/components/panels/GiamSat.tsx", r'''"use client";
import { useState } from "react";
import { useData, act, fmt } from "@/lib/client";
import type { Sess } from "@/components/Shell";
import Tabs from "@/components/Tabs";
import { LineChart, Line, XAxis, YAxis, Tooltip, Legend, CartesianGrid, ResponsiveContainer } from "recharts";
type R = Record<string, unknown>;
const COL = ["#059669", "#0ea5e9", "#f59e0b", "#8b5cf6", "#ef4444", "#14b8a6", "#64748b", "#84cc16"];
/** GIÁM SÁT: bộ tiêu chí theo vị trí (auto từ dữ liệu vận hành + quan sát tại chỗ) → điểm tuần 0–100/người & bộ phận → lỗi trừ điểm thưởng; giám sát viên đủ lượt = đủ điều kiện thưởng */
export default function GiamSat({ sess }: { sess: Sess }) {
  const [tab, setTab] = useState<"tuan" | "cham" | "tieuchi" | "loi" | "xuhuong">("tuan");
  const asg = useData("my_supervision"); const targets = useData("supervision_targets"); const crit = useData("supervision_criteria"); const wk = useData("supervision_week", { week: "" }); const weekly = useData("supervision_weekly"); const dept = useData("supervision_dept_weekly"); const checks = useData("supervision_checks_recent");
  const [sel, setSel] = useState<string>(""); const [msg, setMsg] = useState(""); const [busy, setBusy] = useState(false);
  const T = targets.rows ?? []; const tsel = T.find((t) => t.id === sel); const C = crit.rows ?? [];
  const critFor = (t: R | undefined) => C.filter((c) => (!c.position_code || c.position_code === t?.position_code) && (!c.dept_code || c.dept_code === t?.dept));
  const scoreOf = (sid: string, cid: string) => (wk.rows ?? []).find((r) => r.staff_id === sid && r.criteria_id === cid);
  const mark = async (t: R, c: R, result: string) => { let severity: string | null = null; let note: string | null = null; if (result === "LOI") { severity = prompt("Mức độ: NHE / TRUNG / NANG / NGHIEM_TRONG", "TRUNG"); if (!severity) return; note = prompt("Mô tả lỗi + yêu cầu khắc phục") ?? ""; } setBusy(true); const j = await act("sup_check", { target_staff_id: t.id, target_dept: t.dept, criteria_id: c.id, sop_code: c.sop_code, item: c.name, result, severity, note }); setBusy(false); setMsg(j.ok ? `Đã ghi ${result}${j.points ? ` (−${j.points} điểm)` : ""}` : String(j.error)); wk.reload(); checks.reload(); weekly.reload(); };
  const trend = (() => { const weeks = [...new Set((dept.rows ?? []).map((r) => String(r.week_start)))].sort(); const depts = [...new Set((dept.rows ?? []).map((r) => String(r.dept)))]; return { depts, data: weeks.map((w) => { const o: R = { week: fmt.d(w).slice(0, 5) }; for (const d of depts) o[d] = Number((dept.rows ?? []).find((r) => r.week_start === w && r.dept === d)?.score ?? null); return o; }) }; })();
  return <div className="space-y-3">
    <Tabs items={[["tuan", `Bảng điểm tuần này (${(wk.rows ?? []).length} dòng)`], ["cham", `Chấm quan sát tại chỗ (${T.length} người)`], ["loi", `Lỗi & khắc phục (${(checks.rows ?? []).filter((c) => c.result === "LOI").length})`], ["xuhuong", "📈 Xu hướng theo bộ phận"], ["tieuchi", `Tiêu chí (${C.length})`]]} value={tab} onChange={(k) => setTab(k as typeof tab)} right={<button className="btn-secondary !py-1.5 !px-3 text-sm" disabled={busy} onClick={async () => { const j = await act("run_supervision", {}); setMsg(j.ok ? `Đã chấm tự động ${j.n} tiêu chí` : String(j.error)); wk.reload(); weekly.reload(); }}>⟳ Chấm tự động ngay</button>} />
    {msg && <div className="rounded-xl bg-emerald-50 border border-emerald-300 px-3 py-2 text-sm">{msg}</div>}
    <div className="text-xs text-slate-600">Phân công của tôi: {(asg.rows ?? []).map((a) => <span key={String(a.id)} className="rounded-full border px-2 py-0.5 mr-1">{String(a.target_label ?? "toàn trại")} · {String(a.checks_per_week ?? 5)} lượt/tuần</span>)}{!(asg.rows ?? []).length && "— chưa được phân công giám sát (GĐ/QA phân ở /quan-tri?t=supervision_assignments)"}</div>
    {tab === "tuan" && <div className="card p-0 overflow-auto"><div className="px-3 py-2 bg-slate-100 rounded-t-xl font-bold">Điểm tuần {fmt.d(String((wk.rows ?? [])[0]?.week_start ?? new Date().toISOString()))} — tự động (từ ghi chép/việc/checklist) + quan sát; A ≥90 · B ≥75 · C ≥60 · D &lt;60</div>
      <table className="tbl text-sm"><thead><tr><th className="pl-3">Nhân sự</th><th>BP · vị trí</th><th className="text-right">Điểm</th><th>Xếp</th><th className="text-right">Tiêu chí</th><th>Chưa đạt (giá trị/mục tiêu)</th></tr></thead><tbody>{(weekly.rows ?? []).filter((r) => r.week_start === (wk.rows ?? [])[0]?.week_start || !(wk.rows ?? []).length).slice(0, 80).map((r) => <tr key={String(r.staff_id) + String(r.week_start)} className={r.grade === "D" ? "bg-red-50" : r.grade === "C" ? "bg-amber-50" : ""}><td className="pl-3">{String(r.full_name)}</td><td className="text-xs">{String(r.dept)} · {String(r.position_code ?? r.role)}</td><td className="text-right font-bold">{String(r.score)}</td><td><span className={`rounded-full px-2 text-xs font-bold ${r.grade === "A" ? "bg-emerald-100 text-emerald-800" : r.grade === "B" ? "bg-sky-100" : r.grade === "C" ? "bg-amber-100" : "bg-red-100 text-red-800"}`}>{String(r.grade)}</span></td><td className="text-right">{String(r.n_criteria)}{Number(r.n_manual) ? ` (${r.n_manual} QS)` : ""}</td><td className="text-xs max-w-[520px]">{String(r.shortfalls ?? "")}</td></tr>)}</tbody></table>{!(weekly.rows ?? []).length && <div className="p-3 text-sm text-slate-500">Chưa có điểm — bấm "Chấm tự động ngay".</div>}</div>}
    {tab === "cham" && <div className="grid lg:grid-cols-3 gap-3"><div className="card p-0 overflow-auto"><div className="px-3 py-2 bg-slate-100 rounded-t-xl font-bold">Người trong phạm vi giám sát</div>{T.map((t) => <button key={String(t.id)} className={`w-full text-left px-3 py-2 border-b text-sm ${sel === t.id ? "bg-emerald-50" : ""}`} onClick={() => setSel(String(t.id))}>{String(t.full_name)} <span className="text-xs text-slate-500">{String(t.dept)} · {String(t.position_code ?? t.role)}</span></button>)}{!T.length && <div className="p-3 text-sm text-slate-500">Không có người nào trong phạm vi.</div>}</div>
      <div className="card lg:col-span-2">{!tsel ? <div className="text-sm text-slate-500">Chọn người bên trái → checklist tiêu chí của vị trí đó: hệ thống đã chấm phần AUTO; anh/chị quan sát và chấm phần QUAN SÁT (đạt/lỗi), xác nhận điểm auto thấp.</div> : <div><b>{String(tsel.full_name)}</b> <span className="text-xs text-slate-500">{String(tsel.dept)} · {String(tsel.position_code ?? tsel.role)}</span>
        <table className="tbl text-sm mt-2"><thead><tr><th>Tiêu chí</th><th>Cách đo</th><th className="text-right">Trọng số</th><th className="text-right">Giá trị / mục tiêu</th><th className="text-right">Đạt</th><th>Chấm</th></tr></thead><tbody>{critFor(tsel).map((c) => { const sc = scoreOf(String(tsel.id), String(c.id)); return <tr key={String(c.id)} className={sc && Number(sc.achieved) < 0.8 ? "bg-amber-50" : ""}><td><b>{String(c.name)}</b><div className="text-xs text-slate-500">{String(c.what ?? "")}{c.sop_code ? ` · ${c.sop_code}` : ""}</div></td><td className="text-xs">{c.method === "AUTO" ? "tự động" : "quan sát"}</td><td className="text-right">{String(c.weight)}</td><td className="text-right">{sc ? `${sc.value ?? "—"} / ${sc.target ?? c.target ?? ""} ${c.unit ?? ""}` : "—"}</td><td className="text-right">{sc ? `${Math.round(Number(sc.achieved) * 100)}%` : ""}</td><td className="text-xs whitespace-nowrap"><button className="underline mr-2 text-emerald-700" disabled={busy} onClick={() => mark(tsel, c, "DAT")}>✓ đạt</button><button className="underline mr-2 text-red-700" disabled={busy} onClick={() => mark(tsel, c, "LOI")}>✗ lỗi</button><button className="underline text-slate-500" disabled={busy} onClick={() => mark(tsel, c, "TU_BAO_LOI")}>tự báo</button></td></tr>; })}</tbody></table>
        <div className="text-xs text-slate-500 mt-1">Lỗi → trừ điểm thưởng bộ phận theo mức độ (NHẸ 1 · TRUNG 3 · NẶNG 6 · NGHIÊM TRỌNG 12 điểm × {fmt.vnd(50000)}); "tự báo lỗi" không trừ. Lỗi phát sinh sự kiện supervision.fault → bộ phận nhận thông báo khắc phục.</div></div>}</div></div>}
    {tab === "loi" && <div className="card p-0 overflow-auto"><table className="tbl text-sm"><thead><tr><th className="pl-3">Lúc</th><th>Giám sát</th><th>Đối tượng</th><th>Tiêu chí</th><th>KQ</th><th>Mức</th><th className="text-right">Điểm</th><th>Ghi chú / khắc phục</th></tr></thead><tbody>{(checks.rows ?? []).map((c) => <tr key={String(c.id)} className={c.result === "LOI" ? "bg-red-50" : ""}><td className="pl-3 text-xs">{fmt.dt(String(c.ts))}</td><td className="text-xs">{String(c.supervisor_name ?? c.supervisor_id)}</td><td>{String(c.target_name ?? c.target_dept ?? "")}</td><td>{String(c.item)}</td><td>{String(c.result)}</td><td>{String(c.severity ?? "")}</td><td className="text-right">{String(c.points ?? 0)}</td><td className="text-xs">{String(c.note ?? "")} {c.corrective ? `→ ${c.corrective}` : ""}</td></tr>)}</tbody></table></div>}
    {tab === "xuhuong" && <div className="card"><div className="text-sm font-bold">Điểm giám sát TB theo bộ phận (12 tuần)</div><div style={{ height: 300 }}><ResponsiveContainer><LineChart data={trend.data}><CartesianGrid strokeDasharray="3 3" /><XAxis dataKey="week" tick={{ fontSize: 10 }} /><YAxis domain={[0, 100]} tick={{ fontSize: 10 }} /><Tooltip /><Legend wrapperStyle={{ fontSize: 11 }} />{trend.depts.map((d, i) => <Line key={d} type="monotone" dataKey={d} stroke={COL[i % COL.length]} dot={false} strokeWidth={2} connectNulls />)}</LineChart></ResponsiveContainer></div></div>}
    {tab === "tieuchi" && <div className="card p-0 overflow-auto"><div className="px-3 py-2 bg-slate-100 rounded-t-xl font-bold flex items-center gap-2">Tiêu chí giám sát & thang điểm (dữ liệu — sửa/thêm không cần lập trình) <a className="ml-auto underline text-sm font-normal" href="/quan-tri?t=supervision_criteria">✎ sửa</a></div><table className="tbl text-sm"><thead><tr><th className="pl-3">Vị trí</th><th>Tiêu chí</th><th>Giám sát cái gì</th><th>Cách đo</th><th className="text-right">Mục tiêu</th><th className="text-right">Trọng số</th><th>Mức lỗi</th><th>SOP</th></tr></thead><tbody>{C.map((c) => <tr key={String(c.id)}><td className="pl-3 font-mono text-xs">{String(c.position_code ?? c.dept_code ?? "Mọi vị trí")}</td><td><b>{String(c.name)}</b></td><td className="text-xs">{String(c.what ?? "")}</td><td className="text-xs">{c.method === "AUTO" ? "Tự động (SQL trên dữ liệu vận hành)" : "Quan sát tại chỗ"}</td><td className="text-right">{String(c.direction)} {String(c.target ?? "")} {String(c.unit ?? "")}</td><td className="text-right">{String(c.weight)}</td><td>{String(c.severity ?? "")}</td><td className="font-mono text-xs">{String(c.sop_code ?? "")}</td></tr>)}</tbody></table></div>}
  </div>;
}
''')
# NhanSu: add training & bonus tabs — wrap NhanSuPanel via new component in Depts
rw("src/components/panels/Depts.tsx", lambda s: s.replace('export function NhanSuPanel({ sess }: { sess: Sess }) {','import DaoTaoThuong from "@/components/panels/DaoTaoThuong";\nexport function NhanSuPanel({ sess }: { sess: Sess }) {\n  const [nsTab, setNsTab] = useState<"dt" | "ns">("dt");',1))
w("src/components/panels/DaoTaoThuong.tsx", r'''"use client";
import { useState } from "react";
import { useData, act, fmt } from "@/lib/client";
import type { Sess } from "@/components/Shell";
import Tabs from "@/components/Tabs";
import { BarChart, Bar, LineChart, Line, XAxis, YAxis, Tooltip, Legend, CartesianGrid, ResponsiveContainer } from "recharts";
type R = Record<string, unknown>;
/** ĐÀO TẠO (2–3h/tuần, cấp trên dạy cấp dưới toàn bộ SOP → thuần thục → học SOP cấp trên; kiểm tra người khác chấm) & THƯỞNG THÁNG (điều kiện dạy + học + kiểm tra + giám sát; trừ lỗi) → vào lương */
export default function DaoTaoThuong({ sess }: { sess: Sess }) {
  const [tab, setTab] = useState<"tuan" | "nangluc" | "thuong" | "so">("tuan");
  const my = useData("my_training"); const stats = useData("training_stats"); const cm = useData("competency_matrix"); const [period, setPeriod] = useState(new Date(Date.now() - 30 * 864e5).toISOString().slice(0, 7)); const be = useData("bonus_eval", { period }, [period]); const led = useData("bonus_ledger"); const staff = useData("staff");
  const [msg, setMsg] = useState(""); const canMgr = ["owner", "director", "tech_head", "it_engineer"].includes(sess.role); const canFin = ["owner", "director", "accountant"].includes(sess.role);
  const done = async (t: R) => { const hours = prompt("Số giờ thực dạy/học?", String(t.planned_hours ?? 2.5)); if (!hours) return; const score = prompt("Điểm kiểm tra (0–100, đạt ≥ 80)?", "85"); if (!score) return; let examiner = ""; if (String(t.trainer_id) === sess.staffId) { examiner = prompt("Người chấm (mã NS, PHẢI khác người dạy; để trống = hệ thống/QA)", "") ?? ""; } else examiner = sess.staffId === t.trainee_id ? "" : sess.staffId; const j = await act("complete_training", { id: t.id, hours: Number(hours), score: Number(score), examiner_id: examiner || null }); setMsg(j.ok ? `Đã ghi buổi học — ${j.passed ? "ĐẠT" : "chưa đạt"}, năng lực: ${j.level ?? ""}` : String(j.error)); my.reload(); cm.reload(); };
  const B = be.rows ?? []; const elig = B.filter((r) => r.eligible).length;
  return <div className="space-y-3">
    <Tabs items={[["tuan", `Đào tạo tuần (${(my.rows ?? []).filter((t) => t.status === "KE_HOACH").length} chưa xong)`], ["nangluc", "Ma trận năng lực"], ["thuong", `Thưởng tháng ${period} (${elig}/${B.length} đủ ĐK)`], ["so", "Sổ thưởng"]]} value={tab} onChange={(k) => setTab(k as typeof tab)} right={canMgr ? <button className="btn-secondary !py-1.5 !px-3 text-sm" onClick={async () => { const j = await act("gen_training_week", {}); setMsg(j.ok ? `Đã sinh lịch: ${j.training} buổi học, ${j.supervision} việc giám sát` : String(j.error)); my.reload(); }}>＋ Sinh lịch tuần này</button> : undefined} />
    {msg && <div className="rounded-xl bg-emerald-50 border border-emerald-300 px-3 py-2 text-sm">{msg}</div>}
    {tab === "tuan" && <div className="space-y-3"><div className="card p-0 overflow-auto"><div className="px-3 py-2 bg-slate-100 rounded-t-xl font-bold">Buổi dạy/học của tôi & cấp dưới (8 tuần) — chủ đề = SOP kế tiếp chưa thuần thục của người học; xong buổi → điểm kiểm tra → năng lực lên bậc; người chấm ≠ người dạy</div><table className="tbl text-sm"><thead><tr><th className="pl-3">Tuần</th><th>Người học</th><th>Người dạy</th><th>Chủ đề (SOP)</th><th className="text-right">Giờ KH</th><th className="text-right">Thực</th><th className="text-right">Điểm</th><th>TT</th><th></th></tr></thead><tbody>{(my.rows ?? []).map((t) => <tr key={String(t.id)} className={t.status === "KE_HOACH" ? "bg-amber-50" : t.status === "BO_LO" ? "bg-red-50" : ""}><td className="pl-3">{fmt.d(String(t.week_start))}</td><td>{String(t.trainee_name)}</td><td className="text-xs">{String(t.trainer_name)}</td><td>{String(t.topic_title ?? "")} <span className="font-mono text-xs text-slate-500">{String(t.topic_code ?? "")}</span></td><td className="text-right">{String(t.planned_hours)}</td><td className="text-right">{String(t.actual_hours ?? "")}</td><td className={`text-right font-bold ${t.score != null && Number(t.score) < 80 ? "text-red-700" : ""}`}>{String(t.score ?? "")}</td><td><span className="rounded-full px-2 text-xs bg-slate-100">{String(t.status)}</span></td><td className="text-xs">{t.status === "KE_HOACH" && (t.trainer_id === sess.staffId || t.trainee_id === sess.staffId || canMgr) && <button className="underline" onClick={() => done(t)}>✓ hoàn thành + chấm</button>}</td></tr>)}</tbody></table>{!(my.rows ?? []).length && <div className="p-3 text-sm text-slate-500">Chưa có lịch — GĐ/KTT bấm "Sinh lịch tuần này" (job đêm thứ Hai tự sinh).</div>}</div>
      <div className="card"><div className="text-sm font-bold">Đào tạo theo tuần: kế hoạch / hoàn thành / điểm TB (26 tuần)</div><div style={{ height: 220 }}><ResponsiveContainer><BarChart data={(stats.rows ?? []).map((r) => ({ wk: fmt.d(String(r.week_start)).slice(0, 5), planned: Number(r.planned), done: Number(r.done), score: Number(r.avg_score ?? 0) }))}><CartesianGrid strokeDasharray="3 3" /><XAxis dataKey="wk" tick={{ fontSize: 10 }} /><YAxis yAxisId="l" tick={{ fontSize: 10 }} /><YAxis yAxisId="r" orientation="right" domain={[0, 100]} tick={{ fontSize: 10 }} /><Tooltip /><Legend wrapperStyle={{ fontSize: 11 }} /><Bar yAxisId="l" dataKey="planned" name="Buổi kế hoạch" fill="#cbd5e1" /><Bar yAxisId="l" dataKey="done" name="Hoàn thành" fill="#059669" /><Line yAxisId="r" type="monotone" dataKey="score" name="Điểm TB" stroke="#f59e0b" strokeWidth={2} /></BarChart></ResponsiveContainer></div></div></div>}
    {tab === "nangluc" && <div className="card p-0 overflow-auto"><div className="px-3 py-2 bg-slate-100 rounded-t-xl font-bold">Ma trận năng lực: mỗi người × SOP vị trí (CHƯA HỌC → HỌC → THỰC HÀNH → THUẦN THỤC → DẠY ĐƯỢC); 100% thuần thục → học SOP cấp trên</div><table className="tbl text-sm"><thead><tr><th className="pl-3">Nhân sự</th><th>BP</th><th className="text-right">SOP vị trí</th><th className="text-right">Thuần thục</th><th className="text-right">Thực hành</th><th className="text-right">Chưa học</th><th>Tiến độ</th></tr></thead><tbody>{(cm.rows ?? []).map((r) => <tr key={String(r.staff_id)}><td className="pl-3">{String(r.full_name)}</td><td className="text-xs">{String(r.dept)}</td><td className="text-right">{String(r.n_sop)}</td><td className="text-right text-emerald-700 font-bold">{String(r.mastered)}</td><td className="text-right">{String(r.practicing)}</td><td className="text-right text-red-700">{String(r.not_started)}</td><td><div className="h-2 w-40 rounded bg-slate-100 overflow-hidden"><div className="h-2 bg-emerald-500" style={{ width: `${r.pct}%` }} /></div><span className="text-xs">{String(r.pct)}%</span></td></tr>)}</tbody></table></div>}
    {tab === "thuong" && <div className="space-y-3"><div className="card flex flex-wrap items-center gap-2 text-sm"><b>Kỳ</b><input className="input !w-32 !py-1" value={period} onChange={(e) => setPeriod(e.target.value)} /><span className="text-xs text-slate-500">Điều kiện: học ≥80% giờ (nếu chưa thuần thục hết SOP) · dạy ≥80% buổi (nếu có cấp dưới) · ≥1 bài kiểm tra ĐẠT · giám sát ≥80% lượt (nếu được phân công) → mức thưởng theo vai (settings bonus.base_*) − điểm lỗi × {fmt.vnd(50000)}</span>{canFin && <><button className="ml-auto btn-secondary !py-1 !px-3" onClick={async () => { const j = await act("close_bonus", { period }); setMsg(j.ok ? `Đã chốt thưởng ${j.n} người vào sổ` : String(j.error)); led.reload(); }}>Chốt sổ thưởng {period}</button><button className="btn-primary !py-1 !px-3" onClick={async () => { const j = await act("apply_bonus", { month: period + "-01" }); setMsg(j.ok ? `Đã đưa vào ${j.n} phiếu lương (kpi_bonus)` : String(j.error)); }}>→ Vào bảng lương</button></>}</div>
      <div className="card p-0 overflow-auto"><table className="tbl text-sm"><thead><tr><th className="pl-3">Nhân sự</th><th>Vai</th><th className="text-right">Học (h)</th><th className="text-right">Dạy (buổi)</th><th className="text-right">KT đạt</th><th className="text-right">Giám sát</th><th className="text-right">Điểm lỗi</th><th className="text-right">Trừ</th><th>Đủ ĐK</th><th className="text-right">Thưởng</th></tr></thead><tbody>{B.map((r) => <tr key={String(r.staff_id)} className={r.eligible ? "" : "bg-red-50"}><td className="pl-3">{String(r.full_name)}{r.mastered_all ? <span className="text-xs text-emerald-700"> · thuần thục 100%</span> : null}</td><td className="text-xs">{String(r.role)} · {String(r.dept)}</td><td className={`text-right ${!r.learn_ok ? "text-red-700 font-bold" : ""}`}>{fmt.n(Number(r.learn_hours))}/{fmt.n(Number(r.learn_required))}</td><td className={`text-right ${!r.teach_ok ? "text-red-700 font-bold" : ""}`}>{String(r.teach_sessions)}/{String(r.teach_required)}</td><td className={`text-right ${!r.test_ok ? "text-red-700 font-bold" : ""}`}>{String(r.tests_passed)}/{String(r.tests)}</td><td className={`text-right ${!r.supervise_ok ? "text-red-700 font-bold" : ""}`}>{String(r.supervise_checks)}/{String(r.supervise_required)}</td><td className="text-right">{fmt.n(Number(r.fault_points))}</td><td className="text-right text-red-700">{fmt.vnd(Number(r.deduction))}</td><td>{r.eligible ? "✓" : "✗"}</td><td className="text-right font-bold">{fmt.vnd(Number(r.bonus))}</td></tr>)}</tbody></table></div></div>}
    {tab === "so" && <div className="card p-0 overflow-auto"><table className="tbl text-sm"><thead><tr><th className="pl-3">Kỳ</th><th>Nhân sự</th><th>Loại</th><th className="text-right">Điểm lỗi</th><th className="text-right">Tiền</th><th>Giải trình</th></tr></thead><tbody>{(led.rows ?? []).map((r) => <tr key={String(r.id)}><td className="pl-3">{String(r.period)}</td><td>{String(r.full_name)}</td><td className="text-xs">{String(r.kind)}</td><td className="text-right">{String(r.points ?? 0)}</td><td className="text-right font-bold">{fmt.vnd(Number(r.amount))}</td><td className="text-xs">{String(r.note ?? "")}</td></tr>)}</tbody></table></div>}
  </div>;
}
''')
