import io
p="F:/ITRAN FARM/itran-os/src/components/panels/GiamSat.tsx"; s=io.open(p,encoding="utf-8").read()
s=s.replace('const [tab, setTab] = useState<"tuan" | "cham" | "tieuchi" | "loi" | "xuhuong">("tuan");','const [tab, setTab] = useState<"tuan" | "cham" | "tieuchi" | "loi" | "xuhuong" | "nhip">("tuan");',1)
s=s.replace('["xuhuong", "📈 Xu hướng theo bộ phận"], ["tieuchi",','["nhip", "🔁 Nhịp tuần & CAPA · đi ca · chấm ngược"], ["xuhuong", "📈 Xu hướng theo bộ phận"], ["tieuchi",',1)
s=s.replace('    {tab === "xuhuong" && <div className="card">','    {tab === "nhip" && <NhipTuan sess={sess} />}\n    {tab === "xuhuong" && <div className="card">',1)
s += r'''
/** NHỊP TUẦN GS ↔ TRƯỞNG PHÒNG: T6 lỗi → việc CAPA · T2 biện pháp · GS chấm lại · lỗi lặp 3 tuần · GS đi ca thật · trưởng phòng chấm ngược GS */
function NhipTuan({ sess }: { sess: Sess }) {
  const faults = useData<R>("faults_week"); const capa = useData<R>("capa_status"); const rep = useData<R>("repeat_faults"); const fd = useData<R>("my_field_days"); const gsl = useData<R>("gs_list");
  const [msg, setMsg] = useState(""); const isHead = ["tech_head", "team_lead", "director", "owner"].includes(sess.role);
  const isGS = (gsl.rows ?? []).some((g) => g.id === sess.staffId) || sess.role === "auditor";
  const [rate, setRate] = useState<{ supervisor_id: string; useful: number; fair: number; knows: number; note: string }>({ supervisor_id: "", useful: 4, fair: 4, knows: 4, note: "" });
  return <div className="space-y-3">
    <div className="card text-sm"><b>Nhịp tuần cố định</b>: T2–T5 GS kiểm (+1 ngày đi ca thật) → <b>T6</b> lỗi chưa có biện pháp tự đổ vào việc <b>CAPA</b> của trưởng phòng (hạn T2 12h) → trưởng phòng ghi biện pháp + người + hạn (nội dung dạy tuần tới lấy từ đây) → GS chấm lại lỗi cũ trước khi mở lỗi mới. Lỗi lặp 3 tuần → trừ điểm trưởng phòng. GS không giao việc/ra lệnh công nhân; bất đồng → GĐ quyết trong 48h.
      {(isGS || sess.role === "director") && <button className="btn-secondary !py-1 !text-xs ml-2" onClick={async () => { const j = await act("gen_capa", {}); setMsg(j.error ? String(j.error) : `Đã tạo ${j.n} việc CAPA`); }}>▶ Tạo việc CAPA tuần này</button>}{msg && <span className="ml-2 text-emerald-800">{msg}</span>}</div>
    <div className="card p-0 overflow-auto"><div className="px-3 py-2 bg-slate-100 rounded-t-xl font-bold">Lỗi 2 tuần gần đây ({(faults.rows ?? []).length}) — trưởng phòng ghi biện pháp, GS xác nhận</div><table className="tbl text-sm"><thead><tr><th className="pl-3">Lúc</th><th>Phòng/Người</th><th>Tiêu chí</th><th>Mức</th><th>Biện pháp · hạn</th><th>Xác nhận</th></tr></thead><tbody>
      {(faults.rows ?? []).map((c) => <tr key={String(c.id)} className={c.verified_at ? "" : c.corrective ? "bg-amber-50" : "bg-red-50"}><td className="pl-3 text-xs">{fmt.dt(String(c.ts))}</td><td>{String(c.target_dept ?? "")} {String(c.target_name ?? "")}</td><td className="text-xs">{String(c.criteria_name ?? c.item)}<div className="text-slate-500">{String(c.note ?? "")}</div></td><td>{String(c.severity ?? "")}</td>
        <td className="text-xs">{c.corrective ? <>{String(c.corrective)} <span className="text-slate-500">hạn {c.corrective_due ? fmt.d(c.corrective_due) : "—"}</span></> : isHead ? <button className="btn-secondary !py-0.5 !px-2 !text-xs" onClick={async () => { const m = prompt("Biện pháp khắc phục + người làm"); if (!m) return; const d = prompt("Hạn (YYYY-MM-DD)", new Date(Date.now() + 7 * 864e5).toISOString().slice(0, 10)); await act("capa_set", { id: c.id, corrective: m, due: d }); faults.reload(); }}>＋ biện pháp</button> : <i className="text-red-700">chưa có</i>}</td>
        <td className="text-xs">{c.verified_at ? <span className="b-grn">✓ {fmt.d(c.verified_at)}</span> : c.corrective && isGS ? <button className="btn-primary !py-0.5 !px-2 !text-xs" onClick={async () => { await act("capa_verify", { id: c.id }); faults.reload(); }}>Đã khắc phục</button> : ""}</td></tr>)}</tbody></table></div>
    <div className="grid md:grid-cols-2 gap-3">
      <div className="card p-0 overflow-auto"><div className="px-3 py-2 bg-slate-100 rounded-t-xl font-bold">CAPA theo phòng · 8 tuần</div><table className="tbl text-sm"><thead><tr><th className="pl-3">Tuần</th><th>Phòng</th><th className="text-right">Lỗi</th><th className="text-right">Có biện pháp</th><th className="text-right">Đã xác nhận</th><th className="text-right">Quá hạn</th></tr></thead><tbody>{(capa.rows ?? []).map((r, i) => <tr key={i} className={Number(r.qua_han) > 0 ? "bg-red-50" : ""}><td className="pl-3">{fmt.d(r.week_start)}</td><td>{String(r.dept ?? "")}</td><td className="text-right">{String(r.loi)}</td><td className="text-right">{String(r.co_bien_phap)}</td><td className="text-right">{String(r.da_xac_nhan)}</td><td className="text-right font-bold">{String(r.qua_han)}</td></tr>)}</tbody></table></div>
      <div className="space-y-3">
        <div className="card p-0 overflow-auto"><div className="px-3 py-2 bg-red-50 rounded-t-xl font-bold">Lỗi LẶP ≥ 3 tuần liền → trừ trưởng phòng ({(rep.rows ?? []).length})</div><table className="tbl text-sm"><tbody>{(rep.rows ?? []).map((r, i) => <tr key={i}><td className="pl-3">{String(r.dept)}</td><td>{String(r.name ?? r.criteria_id)}</td><td className="text-right">{String(r.weeks)} tuần</td></tr>)}{(rep.rows ?? []).length === 0 && <tr><td className="p-3 text-slate-500">Không có — tốt.</td></tr>}</tbody></table></div>
        {isGS && <div className="card text-sm"><b>Đi ca thật của tôi</b> <span className="text-xs text-slate-500">(≥ 1 ngày/tuần trong khối đang kiểm — điều kiện lên bậc GS)</span><div className="flex gap-1 mt-1 flex-wrap"><FieldDay onDone={() => fd.reload()} /></div><div className="text-xs mt-1">{(fd.rows ?? []).slice(0, 8).map((r) => <span key={String(r.id)} className="inline-block mr-2">{fmt.d(r.day)} {String(r.block ?? r.dept ?? "")}</span>)}</div></div>}
        {isHead && <div className="card text-sm"><b>Chấm ngược giám sát viên (tháng này)</b> <span className="text-xs text-slate-500">hữu ích · công tâm · hiểu nghề (1–5) — là điều kiện lên bậc GS</span>
          <div className="flex gap-1 mt-1 flex-wrap items-center"><select className="input !py-1" value={rate.supervisor_id} onChange={(e) => setRate({ ...rate, supervisor_id: e.target.value })}><option value="">— giám sát viên —</option>{(gsl.rows ?? []).filter((g) => g.id !== sess.staffId).map((g) => <option key={String(g.id)} value={String(g.id)}>{String(g.full_name)} ({String(g.grade_gs)})</option>)}</select>{(["useful", "fair", "knows"] as const).map((k) => <label key={k} className="text-xs">{k === "useful" ? "Hữu ích" : k === "fair" ? "Công tâm" : "Hiểu nghề"} <select className="input !py-1 !w-16" value={rate[k]} onChange={(e) => setRate({ ...rate, [k]: Number(e.target.value) })}>{[1, 2, 3, 4, 5].map((n) => <option key={n}>{n}</option>)}</select></label>)}<input className="input !py-1" placeholder="Góp ý" value={rate.note} onChange={(e) => setRate({ ...rate, note: e.target.value })} /><button className="btn-primary !py-1 !text-xs" disabled={!rate.supervisor_id} onClick={async () => { const j = await act("rate_supervisor", rate); setMsg(j.error ? String(j.error) : "Đã chấm"); }}>Chấm</button></div></div>}
      </div>
    </div>
  </div>;
}
function FieldDay({ onDone }: { onDone: () => void }) {
  const [d, setD] = useState(new Date().toISOString().slice(0, 10)); const [b, setB] = useState("CN"); const [n, setN] = useState("");
  return <><input className="input !py-1" type="date" value={d} onChange={(e) => setD(e.target.value)} /><select className="input !py-1" value={b} onChange={(e) => setB(e.target.value)}>{["CN", "TT", "SH", "D5", "KHO", "KD", "TCNS", "TB"].map((x) => <option key={x}>{x}</option>)}</select><input className="input !py-1" placeholder="Làm gì cùng tổ" value={n} onChange={(e) => setN(e.target.value)} /><button className="btn-secondary !py-1 !text-xs" onClick={async () => { await act("gs_field_day", { day: d, block: b, note: n }); setN(""); onDone(); }}>Ghi</button></>;
}
'''
io.open(p,"w",encoding="utf-8",newline="\n").write(s); print("ok")
