-- ================================================================================================
-- SEED PHẦN 2 — phủ kín các đối tượng còn lại, dữ liệu NHIỀU KỲ (30 tháng): cho ăn, mẻ D5/khu D, checklist ca, cổng, cảm biến, kiểm kê, sự cố,
-- chi phí, tài sản + khấu hao, trả nợ vay, bảo hiểm bồi thường, đơn hàng/báo giá/trả hàng, du lịch (booking/folio/POS), CRM, nhận nuôi, thẻ tai, lô nhập,
-- hiệu chuẩn, nghỉ phép, ngân sách, chỉ tiêu KD, chứng nhận, kiểm tra tuân thủ, kế hoạch SX, tài liệu, quy trình đã chạy. Idempotent theo client_ref/id.
-- ================================================================================================
set client_min_messages = warning;
select set_config('app.org_id','ITRAN',false), set_config('app.farm_id',:'farm',false), set_config('app.role','it_engineer',false), set_config('app.staff_id','NS-001',false);
do $$
declare F text := :'farm'; U text := coalesce((select id from staff where farm_id=:'farm' and role in ('team_lead','tech_head') and active order by id limit 1),'NS-001');
  M int := 30; d0 date := (date_trunc('month', current_date) - interval '30 months')::date; d date; i int; k int; n int; r record; v_id text; kg numeric; wh record; g record; hens int; v_uuid uuid; v_lot text; s_id uuid;
begin
  select (select id from warehouses where farm_id=F and code='K2') k2, (select id from warehouses where farm_id=F and code='K5') k5, (select id from warehouses where farm_id=F and code='K3') k3, (select id from warehouses where farm_id=F and code='K4') k4 into wh;
  insert into devices(id, farm_id, kind, name, active) values (F||'-TB-020',F,'SENSOR','Cảm biến DO bể RAS',true),(F||'-TB-021',F,'SENSOR','Cảm biến nhiệt kho lạnh',true),(F||'-TB-022',F,'SENSOR','Cảm biến nhiệt chuồng',true) on conflict (id) do nothing;
  update warehouses set temp_device_id=F||'-TB-021' where farm_id=F and code='K6' and temp_device_id is null;
  if not exists (select 1 from hosp_room_types where farm_id=F) then insert into hosp_room_types(id, farm_id, code, name, base_price, capacity) values (F||'-RT-BUNGALOW',F,'BUNGALOW','Bungalow vườn',900000,3),(F||'-RT-STD',F,'STD','Phòng tiêu chuẩn',600000,2) on conflict do nothing; end if;
  if not exists (select 1 from hosp_rooms where farm_id=F) then insert into hosp_rooms(id, farm_id, room_type_id, code, name, status, active) values (F||'-RM-B1',F,F||'-RT-BUNGALOW','B1','Bungalow 1','SAN_SANG',true),(F||'-RM-B2',F,F||'-RT-BUNGALOW','B2','Bungalow 2','SAN_SANG',true),(F||'-RM-S1',F,F||'-RT-STD','S1','Phòng 1','SAN_SANG',true) on conflict do nothing; end if;
  -- ---------- A. CHO ĂN (feed_logs) 2 cữ/ngày đàn bò + gà 1 cữ: ngày cho 120 ngày gần nhất, tuần cho phần trước ----------
  for i in 0..(current_date - d0) loop d := d0 + i;
    continue when i < (current_date - d0) - 120 and extract(dow from d) <> 1;
    kg := (select coalesce(sum(case when d - a.birth_date <= 180 then 8 when d - a.birth_date <= 540 then 20 else 32 end),0) from animals a where a.farm_id=F and a.species='BO' and a.created_at::date <= d and (a.status<>'XUAT' or a.id like F||'-BO-V%'));
    kg := greatest(kg, 45*32);
    if i < (current_date - d0) - 120 then kg := kg*7; end if;
    for r in select * from (values ('SANG',6),('CHIEU',15)) t(meal,h) loop
      insert into feed_logs(farm_id, ts, created_by, source, client_ref, batch_ref, recipe_id, recipe_version, dest_group_id, dest_location_id, planned_kg, qty_kg, meal, leftover_pct) values
       (F, d + make_time(r.h,0,0), U, 'IMPORT', 'h2-feed-'||i||'-'||r.meal, 'TMR-'||to_char(d,'MMDD')||'-'||r.meal, 'RC-TMR-VO', 1, F||'-DAN-NAI-01', F||'-CH-NAI-1', round(kg/2), round(kg/2*(1+((i*7)%9-4)*0.006)), r.meal, 2+(i%5)) on conflict do nothing;
    end loop;
    hens := 3000 - (i%456)/9;
    insert into feed_logs(farm_id, ts, created_by, source, client_ref, recipe_id, recipe_version, dest_group_id, dest_location_id, planned_kg, qty_kg, meal) values (F, d + time '06:30', U, 'IMPORT', 'h2-feedga-'||i, 'RC-GA-DE', 1, F||'-GA-L01', F||'-GA-DE', round(hens*0.115*(case when i < (current_date - d0) - 120 then 7 else 1 end)), round(hens*0.115*(case when i < (current_date - d0) - 120 then 7 else 1 end)*(1+((i*3)%7-3)*0.01)), 'SANG') on conflict do nothing;
  end loop;
  -- ---------- B. MẺ D5 / KHU D (batch_logs) hằng tuần 30 tháng: ép viên, trộn TMR, ủ chua (theo thu hoạch), trùn nạp/thu, BSF, biogas, IMO/EM, anolyte, đóng gói ----------
  for k in 0..(M*30/7) loop d := d0 + k*7; exit when d > current_date;
    insert into batch_logs(farm_id, ts, created_by, source, client_ref, batch_code, line, recipe_id, recipe_version, location_id, inputs, outputs, qc, ccp_readings, temp_c, moisture_pct, batch_status) values
     (F, d + time '05:00', U, 'IMPORT', 'h2-b-vien-'||k, F||'-ME-'||to_char(d,'YYMMDD')||'-V1', 'D5_VIEN', 'RC-GA-DE', 1, F||'-D5', jsonb_build_array(jsonb_build_object('sku','NL-BAP-U','kg',1350),jsonb_build_object('sku','NL-BA-BIA','kg',612),jsonb_build_object('sku','NL-KHOANG','kg',122),jsonb_build_object('sku','NL-RI-MAT','kg',122),jsonb_build_object('sku','NL-ROM','kg',245)), jsonb_build_array(jsonb_build_object('sku','TA-VIEN-GA','kg',2450)), jsonb_build_object('protein_pct', 16.5+(k%6)*0.2, 'mix_err_pct', 0.5+(k%5)*0.4, 'moisture_pct', 12+(k%3)), jsonb_build_array(jsonb_build_object('ccp','KIM_LOAI','ok',true),jsonb_build_object('ccp','NHIET_EP','value',78+(k%6),'ok',true)), 78+(k%6), 12+(k%3), 'DONG'),
     (F, d + time '05:30', U, 'IMPORT', 'h2-b-tmr-'||k, F||'-ME-'||to_char(d,'YYMMDD')||'-T1', 'D5_TMR', 'RC-TMR-VO', 1, F||'-D5', jsonb_build_array(jsonb_build_object('sku','NL-BAP-U','kg',9000),jsonb_build_object('sku','NL-BA-BIA','kg',5000),jsonb_build_object('sku','NL-ROM','kg',3000)), jsonb_build_array(jsonb_build_object('sku','TA-TMR-VO','kg',19600)), jsonb_build_object('dm_pct', 44+(k%4), 'mix_min', 8+(k%3)), '[]'::jsonb, null, 44+(k%4), 'DONG'),
     (F, d + time '09:00', U, 'IMPORT', 'h2-b-trun-'||k, F||'-ME-'||to_char(d,'YYMMDD')||'-TN', 'TRUN_NAP', null, null, F||'-KHU-D', jsonb_build_array(jsonb_build_object('sku','PHAN_UOT','kg',6000+(k%5)*400)), '[]'::jsonb, '{}'::jsonb, '[]'::jsonb, 26+(k%6), null, 'DONG'),
     (F, d + 4 + time '14:00', U, 'IMPORT', 'h2-b-trunthu-'||k, F||'-ME-'||to_char(d+4,'YYMMDD')||'-PT', 'TRUN_THU', null, null, F||'-KHU-D', jsonb_build_array(jsonb_build_object('sku','PHAN_UOT','kg',2400)), jsonb_build_array(jsonb_build_object('sku','SKU-PTR-25','kg',1100)), '{}'::jsonb, '[]'::jsonb, null, 33, 'DONG'),
     (F, d + 1 + time '10:00', U, 'IMPORT', 'h2-b-bsf-'||k, F||'-ME-'||to_char(d+1,'YYMMDD')||'-BS', 'BSF', null, null, F||'-KHU-D', jsonb_build_array(jsonb_build_object('sku','RAC_HUU_CO','kg',700+(k%4)*50)), jsonb_build_array(jsonb_build_object('sku','SKU-BSF','kg',120+(k%4)*10),jsonb_build_object('sku','SKU-COMPOST','kg',200)), '{}'::jsonb, '[]'::jsonb, 30, null, 'DONG'),
     (F, d + 2 + time '10:00', U, 'IMPORT', 'h2-b-bg-'||k, F||'-ME-'||to_char(d+2,'YYMMDD')||'-BG', 'BIOGAS', null, null, F||'-KHU-D', jsonb_build_array(jsonb_build_object('sku','PHAN_UOT','kg',3500)), jsonb_build_array(jsonb_build_object('sku','DIEN_KWH','kg',320+(k%7)*15)), '{}'::jsonb, '[]'::jsonb, null, null, 'DONG'),
     (F, d + 3 + time '15:00', U, 'IMPORT', 'h2-b-em-'||k, F||'-ME-'||to_char(d+3,'YYMMDD')||'-EM', 'IMO_EM', null, null, F||'-KHU-D', jsonb_build_array(jsonb_build_object('sku','NL-RI-MAT','kg',20)), jsonb_build_array(jsonb_build_object('sku','NL-MEN-VS','kg',200)), jsonb_build_object('ph', 3.4+(k%4)*0.1), '[]'::jsonb, null, null, 'DONG'),
     (F, d + 5 + time '08:00', U, 'IMPORT', 'h2-b-ano-'||k, F||'-ME-'||to_char(d+5,'YYMMDD')||'-AN', 'ANOLYTE', null, null, F||'-D5', '[]'::jsonb, jsonb_build_array(jsonb_build_object('sku','TH-ANOLYTE','kg',500)), jsonb_build_object('ppm', 480+(k%5)*10, 'ph', 6.5), jsonb_build_array(jsonb_build_object('ccp','PPM','value',480+(k%5)*10,'ok',true)), null, null, 'DONG'),
     (F, d + 5 + time '13:00', U, 'IMPORT', 'h2-b-dg-'||k, F||'-ME-'||to_char(d+5,'YYMMDD')||'-DG', 'DONG_GOI', null, null, F||'-D5', jsonb_build_array(jsonb_build_object('sku','TA-TMR-VO','kg',2750),jsonb_build_object('sku','BB-BAO-25','kg',110)), jsonb_build_array(jsonb_build_object('sku','SKU-TMR-25','kg',110,'lot_id',F||'-LOT-SKU-TMR-25-TMR'||to_char(d,'YYMM'))), jsonb_build_object('label_ok', true), jsonb_build_array(jsonb_build_object('ccp','KIM_LOAI','ok',true)), null, null, 'DONG')
    on conflict do nothing;
  end loop;
  -- ---------- C. CHECKLIST CA hằng ngày (120 ngày) + hằng tuần (trước), 4 SOP; ~8% chưa đạt ----------
  for i in 0..(current_date - d0) loop d := d0 + i; continue when i < (current_date - d0) - 120 and extract(dow from d) <> 2;
    for r in select * from (values ('SOP-BO-07.2',6),('SOP-GA-02.1',7),('SOP-SH-01.2',8),('SOP-HC-02.1',9),('SOP-AT-01.1',5),('SOP-CB-01.3',10)) t(sop,h) loop
      insert into checklist_runs(farm_id, ts, created_by, source, client_ref, sop_code, sop_version, shift, results, all_green, note, approved_by, approved_at) values (F, d + make_time(r.h,40,0), U, 'IMPORT', 'h2-ck-'||i||'-'||r.sop, r.sop, 1, 'SANG', jsonb_build_array(jsonb_build_object('n',1,'ok',true),jsonb_build_object('n',2,'ok',(i*13+length(r.sop))%12<>0),jsonb_build_object('n',3,'ok',true)), (i*13+length(r.sop))%12<>0, case when (i*13+length(r.sop))%12=0 then 'bước 2 chưa đạt — khắc phục trong ca' end, U, d + make_time(r.h+2,0,0)) on conflict do nothing;
    end loop;
  end loop;
  -- ---------- D. CỔNG (gate_logs) 3–6 xe/ngày 120 ngày + tuần trước đó; CẢM BIẾN DO/nhiệt kho lạnh/nhiệt chuồng 90 ngày mỗi 2 giờ ----------
  for i in 0..(current_date - d0) loop d := d0 + i; continue when i < (current_date - d0) - 120 and extract(dow from d) <> 3;
    for k in 1..(3 + i%4) loop insert into gate_logs(farm_id, ts, created_by, source, client_ref, plate, direction, weighed, anolyte_wash, purpose, driver) values (F, d + make_time(6+(k*3)%12, (i*7)%60, 0), U, 'IMPORT', 'h2-gate-'||i||'-'||k, '89C-'||(100+(i*k)%900)||'.'||(10+(i+k)%90), case when k%2=0 then 'VAO' else 'RA' end, (i+k)%10<>0, (i+k)%20<>0, (array['giao rơm','lấy phân trùn','thú y','khách tham quan','giao trứng','bã bia','xe lạnh giao hàng'])[1+(i+k)%7], 'Tài xế '||(1+(i+k)%5)) on conflict do nothing; end loop;
  end loop;
  for i in 0..89 loop d := current_date - i; for k in 0..11 loop
    insert into sensor_reads(ts, farm_id, device_id, metric, value) values (d + make_time(k*2,0,0), F, F||'-TB-020', 'DO', round((5.5 + sin(k/2.0)*0.8 + (i%5)*0.1 - case when i=18 and k=1 then 2.5 else 0 end)::numeric,2)) on conflict do nothing;
    insert into sensor_reads(ts, farm_id, device_id, metric, value) values (d + make_time(k*2,0,0), F, F||'-TB-021', 'TEMP_COLD', round((3 + sin(k/1.5)*0.7 + (i%3)*0.2 + case when i=22 and k=7 then 6 else 0 end)::numeric,1)) on conflict do nothing;
    insert into sensor_reads(ts, farm_id, device_id, metric, value) values (d + make_time(k*2,0,0), F, F||'-TB-022', 'TEMP_BARN', round((26 + sin((k-3)/2.0)*4 + (i%4)*0.3)::numeric,1)) on conflict do nothing;
  end loop; end loop;
  -- ---------- E. KIỂM KÊ tháng K2/K5 + tuần K5 (12 tuần gần); SỰ CỐ quý (thiết bị/an ninh/thú y/ATLĐ) có 5-why + CAPA ----------
  for k in 0..(M-1) loop d := (d0 + (k||' months')::interval)::date + 27; exit when d > current_date;
    insert into stocktakes(farm_id, ts, created_by, source, client_ref, warehouse_id, counted_by, lines, diff_pct, note) values
     (F, d + time '16:00', U, 'IMPORT', 'h2-st-k2-'||k, wh.k2, U, jsonb_build_array(jsonb_build_object('sku','NL-BA-BIA','book',24000+(k*97)%3000,'counted',24000+(k*97)%3000-(k%4)*30),jsonb_build_object('sku','NL-RI-MAT','book',4200,'counted',4180),jsonb_build_object('sku','NL-KHOANG','book',3300,'counted',3300)), 0.1+(k%4)*0.1, 'kiểm kê tháng — người ngoài bộ phận'),
     (F, d + time '16:30', U, 'IMPORT', 'h2-st-k5-'||k, wh.k5, U, jsonb_build_array(jsonb_build_object('sku','SKU-TRUNG-10','book',1200+(k*31)%300,'counted',1200+(k*31)%300-(k%3)*4),jsonb_build_object('sku','SKU-PTR-25','book',250,'counted',249)), 0.2, 'kiểm kê tháng K5') on conflict do nothing;
    if k%3=1 then insert into incidents(farm_id, ts, created_by, source, client_ref, code, kind, severity, description, location_id, classification, five_why, capa, sop_fixed, closed_at) values (F, d - 10 + time '11:00', U, 'IMPORT', 'h2-inc-'||k, F||'-INC-'||to_char(d,'YYYY')||'-'||lpad((k/3+1)::text,4,'0'), (array['THIET_BI','AN_NINH','THU_Y','ATLD','MOI_TRUONG','CHAT_LUONG'])[1+(k/3)%6], (array['NHE','TRUNG','NHE','NEAR_MISS','TRUNG','NHE'])[1+(k/3)%6], (array['Máy thu sinh khối kẹt băng tải 40 phút','Xe lạ dừng gần rào phía nam','Bê ỉa chảy 3 con dãy nái 1','Trượt ngã sàn ướt khu D — không thương tích','Nước rỉ hào ủ tràn ra rãnh','Mẻ viên ẩm 14% > chuẩn 12%'])[1+(k/3)%6], (array[F||'-KHU-D',F||'-CH-NAI-1',F||'-CH-NAI-1',F||'-KHU-D',F||'-D5',F||'-D5'])[1+(k/3)%6], 'ROOT_CAUSE', jsonb_build_array('Tại sao? băng tải kẹt','Tại sao? vật lạ','Tại sao? sàng lọc đầu vào yếu'), jsonb_build_object('action','Bổ sung sàng lọc + kiểm tra đầu ca','owner',U,'due',(d+7)::text,'done',true), 'SOP-TT-03.2', d - 3 + time '17:00') on conflict do nothing; end if;
  end loop;
  -- ---------- F. CHI PHÍ (expense_requests) 4–6 khoản/tháng, một số >20tr 2 chữ ký; TÀI SẢN CỐ ĐỊNH + khấu hao tháng; TRẢ NỢ VAY các kỳ đã đến hạn; BẢO HIỂM bồi thường 1 ca ----------
  for k in 0..(M-1) loop d := (d0 + (k||' months')::interval)::date + 8; exit when d > current_date;
    for r in select * from (values ('Điện lưới + ĐMT bù','CNTB',18000000+(k*131)%4000000,1),('Sửa chữa máy nông cụ','TT',3500000+(k*97)%2500000,2),('Thuốc thú y – vaccine đợt','KTCN',9000000+(k*71)%3000000,3),('Vật tư văn phòng – tem','HCNS',1200000,4),('Thuê máy gặt / thu hoạch','TT',case when k%6=2 then 26000000 else 0 end,5),('Marketing – gian hàng hội chợ','KDM',case when k%4=0 then 12000000 else 0 end,6)) t(purpose,cc,amt,j) loop
      continue when r.amt=0;
      insert into expense_requests(id, farm_id, ts, requested_by, amount, cost_center, purpose, status, approver1, approved1_at, approver2, approved2_at, owner_notified_at, paid_at, paid_ref)
      values (F||'-DNC-H'||lpad(k::text,2,'0')||r.j, F, d + make_time(9,0,0), U, r.amt, r.cc, r.purpose, 'DUYET', 'NS-002', d + make_time(11,0,0), case when r.amt>20000000 then 'NS-102' end, case when r.amt>20000000 then d + make_time(15,0,0) end, case when r.amt>50000000 then d + make_time(15,0,0) end, d + 3, 'UNC-'||to_char(d,'YYMM')||'-'||r.j) on conflict do nothing;
    end loop;
  end loop;
  insert into fixed_assets(id, farm_id, name, kind, cost, salvage, life_months, start_date, method, cost_center, gl_expense, status) select F||'-TS-'||v.n, F, v.name, v.kind, v.cost, v.cost*0.05, v.life, d0 + v.off, 'THANG', v.cc, '627', 'DANG_DUNG' from (values
   ('01','Chuồng bò 100 con (khung thép, mái tôn)','NHA_XUONG',1800000000,240,'BO',0),('02','Xưởng D5 + máy ép viên 1 t/h','NHA_XUONG',950000000,180,'D5',0),('03','Máy kéo Kubota 50HP + dàn','MAY_MOC',620000000,120,'TT',0),('04','Máy thu sinh khối tự nạp','MAY_MOC',480000000,120,'TT',30),('05','Hệ ĐMT áp mái 60 kWp','THIET_BI',720000000,240,'CNTB',60),
   ('06','Kho lạnh 40 m³','THIET_BI',380000000,120,'CB',90),('07','Xe tải lạnh 1.5 t','PHUONG_TIEN',650000000,96,'CCU',120),('08','Hệ RAS 2 bể + drum filter','THIET_BI',420000000,120,'SH',150),('09','Trạm anolyte + biogas','THIET_BI',260000000,120,'SH',180),('10','Nhà lưới rau 500 m²','NHA_XUONG',150000000,84,'TT',400)) v(n,name,kind,cost,life,cc,off)
  where not exists (select 1 from fixed_assets x where x.id=F||'-TS-'||v.n);
  begin for k in 0..(M-1) loop d := (d0 + (k||' months')::interval)::date; if to_regprocedure('run_depreciation(text,date)') is not null then perform run_depreciation(F, d); end if; end loop; exception when others then raise notice 'khấu hao: %', sqlerrm; end;
  begin for r in select s.id from loan_schedule s join loans l on l.id=s.loan_id where l.farm_id=F and s.status<>'DA_TRA' and s.due_date < current_date order by s.due_date loop perform pay_loan_installment(r.id, 'UNC-VAY'); end loop; exception when others then raise notice 'vay: %', sqlerrm; end;
  insert into insurance_claims(id, policy_id, farm_id, event_date, description, claimed_amount, approved_amount, paid_amount, paid_at, status) select F||'-BT-01', p.id, F, current_date-200, 'Bò cái N012 chết do tụ huyết trùng — có biên bản thú y', 28000000, 22400000, 22400000, current_date-150, 'DA_NHAN' from insurance_policies p where p.farm_id=F and p.kind='VAT_NUOI' and not exists (select 1 from insurance_claims c where c.id=F||'-BT-01') limit 1;
  -- ---------- G. ĐƠN HÀNG B2B tháng (CHOT→GIAO), BÁO GIÁ tháng, TRẢ HÀNG quý, HỢP ĐỒNG bao tiêu 2, NHẬN NUÔI 3, CRM lead tháng, CHỈ TIÊU KD tháng, NGÂN SÁCH năm ----------
  for k in 0..(M-1) loop d := (d0 + (k||' months')::interval)::date + 5; exit when d > current_date;
    insert into orders(id, farm_id, partner_id, channel, order_date, deliver_date, lines, total, status, created_by, note) values (F||'-DH-H'||lpad(k::text,2,'0'), F, case when k%2=0 then 'KH-0001' else 'KH-0002' end, 1, d, d+3, jsonb_build_array(jsonb_build_object('sku','SKU-TMR-25','qty',200+(k*17)%80,'price',101200),jsonb_build_object('sku','SKU-PTR-25','qty',80,'price',78000)), (200+(k*17)%80)*101200 + 80*78000, case when d+3 < current_date then 'GIAO' else 'CHOT' end, U, 'đơn tháng') on conflict do nothing;
    insert into quotes(id, farm_id, partner_id, quote_date, valid_until, lines, subtotal, total, payment_terms, status, order_id, sales_rep_id) values (F||'-BG-H'||lpad(k::text,2,'0'), F, 'KH-000'||(1+k%4), d-2, d+12, jsonb_build_array(jsonb_build_object('sku','SKU-TRUNG-10','name','Trứng vỉ 10','qty',300,'unit','vi','price',42000,'discount_pct',0,'amount',12600000)), 12600000, 12600000, 'NET15', case when k%3=0 then 'THANH_DON' when k%3=1 then 'GUI' else 'TU_CHOI' end, case when k%3=0 then F||'-DH-H'||lpad(k::text,2,'0') end, U) on conflict do nothing;
    if k%3=2 then insert into sales_returns(id, farm_id, partner_id, ts, sku, qty, unit_price, amount, reason, disposition, restocked, status, approved_by, created_by) values (F||'-TH-H'||lpad(k::text,2,'0'), F, 'KH-0003', d + 10 + time '10:00', 'SKU-TRUNG-10', 12, 42000, 504000, 'vỡ khi vận chuyển', 'HUY', false, 'DA_DUYET', 'NS-002', U) on conflict do nothing; end if;
    insert into crm_leads(id, farm_id, org_id, name, company, phone, source, segment, channel_code, interest, est_value, stage, owner_id, created_at, next_action, next_at) values (F||'-LEAD-H'||lpad(k::text,2,'0'), F, 'ITRAN', 'Anh/chị lead '||k, (array['Siêu thị Xanh','Bếp ăn KCN','Cửa hàng hữu cơ','Nhà hàng farm-to-table','Đại lý TACN','Trường học'])[1+k%6], '09'||lpad((k*7777)::text,8,'0'), (array['HOI_CHO','FACEBOOK','GIOI_THIEU','ZALO','WEB'])[1+k%5], (array['B2B','HORECA','BAN_LE','DAI_LY'])[1+k%4], (array['B2B','ONLINE','CUA_HANG'])[1+k%3], (array['trứng thảo dược','TMR bao','phân trùn','thịt bò','nhận nuôi'])[1+k%5], 20000000+(k*1234567)%80000000, (array['MOI','LIEN_HE','BAO_GIA','THUONG_LUONG','THANG','THUA'])[1+k%6], U, d, 'gọi lại', d+7) on conflict do nothing;
    insert into sales_targets(id, farm_id, staff_id, period, target_amount, commission_pct) values (F||'-ST-'||to_char(d,'YYMM'), F, U, to_char(d,'YYYY-MM'), 250000000+(k*5000000), 1.5) on conflict do nothing;
  end loop;
  insert into contracts(id, farm_id, partner_id, kind, sku, qty_committed, unit, price, start_date, end_date, status, created_by) values (F||'-HD-H01', F, 'KH-0001', 'BAO_TIEU', 'SKU-TMR-25', 6000, 'bao', 101200, d0 + 200, d0 + 565, 'HIEU_LUC', U), (F||'-HD-H02', F, 'KH-0003', 'BAO_TIEU', 'SKU-TRUNG-10', 60000, 'vi', 42000, d0 + 400, current_date + 300, 'HIEU_LUC', U) on conflict do nothing;
  begin perform gen_contract_deliveries(F||'-HD-H02', 14); exception when others then null; end;
  insert into custody_contracts(id, farm_id, partner_id, kind, animal_ids, package, fee, period_months, prepaid, start_date, end_date, status, created_by) select F||'-NN-H'||v.n, F, v.p, 'NHAN_NUOI', array[v.a], v.pk, v.fee, 12, v.fee*12, d0 + v.off, d0 + v.off + 365, case when d0+v.off+365 < current_date then 'KET_THUC' else 'HIEU_LUC' end, U from (values ('01','KH-0004',F||'-BO-H005','BO_CAI_1_NAM',1500000,120),('02','KH-0003',F||'-BO-H012','BO_CAI_1_NAM',1500000,300),('03','KH-0001',F||'-DE-C003','DE_1_NAM',600000,500)) v(n,p,a,pk,fee,off) where exists (select 1 from animals a where a.id=v.a) and not exists (select 1 from custody_contracts c where c.id=F||'-NN-H'||v.n);
  for k in 0..(M/12) loop
    insert into budgets(farm_id, year, month, cost_center, kind, category, amount, created_by) select F, extract(year from d0 + (k*12||' months')::interval)::int, m.m, v.cc, v.kind, v.cat, v.amt*(1+k*0.08), U from generate_series(1,12) m(m), (values ('*','DOANH_THU','Bán hàng',350000000),('BO','CHI','Thức ăn mua ngoài',60000000),('TT','CHI','Vật tư trồng trọt',25000000),('HCNS','CHI','Lương',420000000),('CNTB','CHI','Điện – nước',22000000),('D5','CHI','Bao bì – vận hành',15000000)) v(cc,kind,cat,amt)
    where not exists (select 1 from budgets b where b.farm_id=F and b.year=extract(year from d0 + (k*12||' months')::interval)::int and b.month=m.m and b.cost_center=v.cc and b.category=v.cat);
  end loop;
  -- ---------- H. DU LỊCH: booking tuần (2 phòng), folio ăn/tour, POS ca cuối tuần; ----------
  for k in 0..(M*30/7) loop d := d0 + k*7 + 4; exit when d > current_date + 20;
    for r in select * from (select id, code, room_type_id from hosp_rooms where farm_id=F order by code limit 2) x loop
      v_id := F||'-BK-H'||lpad(k::text,3,'0')||right(r.code,1);
      insert into hosp_bookings(id, farm_id, code, guest_name, guest_phone, pax_adult, pax_child, check_in, check_out, room_id, room_type_id, rate, nights, channel, status, deposit, total, paid, created_by) values (v_id, F, v_id, (array['Gia đình anh Minh','Đoàn công ty ABC','Chị Lan – Hà Nội','Khách Hàn Quốc','Nhóm sinh viên','Vợ chồng bác Tư'])[1+(k+length(r.code))%6], '09'||lpad((k*3131)::text,8,'0'), 2+(k%3), k%2, d, d+2, r.id, r.room_type_id, 900000+(k%3)*100000, 2, (array['TRUC_TIEP','BOOKING','AGODA','ZALO'])[1+k%4], case when d+2 < current_date then 'CHECKOUT' when d <= current_date then 'CHECKIN' else 'DAT' end, 500000, (900000+(k%3)*100000)*2, case when d+2 < current_date then (900000+(k%3)*100000)*2 else 500000 end, U) on conflict do nothing;
      if d <= current_date then
        insert into hosp_folio(farm_id, ts, created_by, source, client_ref, booking_id, kind, description, qty, unit_price, amount, payment) values (F, d + time '19:00', U, 'IMPORT', 'h2-folio-'||v_id||'-1', v_id, 'AN_UONG', 'Set farm-to-table tối', 2+(k%3), 250000, (2+(k%3))*250000, 'CK'), (F, d + 1 + time '09:00', U, 'IMPORT', 'h2-folio-'||v_id||'-2', v_id, 'TOUR', 'Tour vòng tuần hoàn 12 trạm', 2+(k%3), 120000, (2+(k%3))*120000, 'CK'), (F, d + 2 + time '11:00', U, 'IMPORT', 'h2-folio-'||v_id||'-3', v_id, 'PHONG', 'Tiền phòng 2 đêm', 2, 900000+(k%3)*100000, (900000+(k%3)*100000)*2, 'CK') on conflict do nothing;
      end if;
    end loop;
    if d <= current_date then
      insert into pos_shifts(id, farm_id, location_id, opened_at, opened_by, closed_at, closed_by, cash_open, cash_close, cash_expected, diff, status) values (F||'-CA-H'||lpad(k::text,3,'0'), F, F||'-D5', d + time '08:00', U, d + time '17:00', U, 500000, 500000 + 3200000 + (k%5)*150000 - (k%7)*10000, 500000 + 3200000 + (k%5)*150000, -(k%7)*10000, 'DONG') on conflict do nothing;
      for n in 1..(6+k%5) loop insert into pos_receipts(farm_id, ts, created_by, source, client_ref, shift_id, receipt_no, lines, subtotal, tax, total, payment, paid, channel_code) values (F, d + make_time(8+n,15,0), U, 'IMPORT', 'h2-pos-'||k||'-'||n, F||'-CA-H'||lpad(k::text,3,'0'), 'R'||to_char(d,'YYMMDD')||lpad(n::text,2,'0'), jsonb_build_array(jsonb_build_object('sku','SKU-TRUNG-10','name','Trứng vỉ 10','qty',1+n%3,'price',45000),jsonb_build_object('sku','SKU-RAU','name','Rau','qty',1,'price',25000)), (1+n%3)*45000+25000, 0, (1+n%3)*45000+25000, (array['TIEN_MAT','VIETQR','POS'])[1+n%3], (1+n%3)*45000+25000, 'CUA_HANG') on conflict do nothing; end loop;
    end if;
  end loop;
  -- ---------- I. THẺ TAI (animal_tags) cho mọi vật nuôi có visual_tag; LÔ NHẬP theo đợt; HIỆU CHUẨN thiết bị quý; NGHỈ PHÉP tháng; CHỨNG NHẬN + KIỂM TRA TUÂN THỦ quý; KẾ HOẠCH SX tuần 12 tuần; TÀI LIỆU; QUY TRÌNH đã chạy ----------
  insert into animal_tags(farm_id, animal_id, tag_type, value, from_ts, created_by) select F, a.id, 'VISUAL', a.visual_tag, coalesce(a.created_at, now()), U from animals a where a.farm_id=F and a.visual_tag is not null and not exists (select 1 from animal_tags t where t.animal_id=a.id and t.tag_type='VISUAL');
  insert into animal_tags(farm_id, animal_id, tag_type, value, from_ts, created_by) select F, a.id, 'RFID', '840'||lpad(abs(hashtext(a.id))::text, 12, '0'), coalesce(a.created_at, now()) + interval '1 day', U from animals a where a.farm_id=F and a.species='BO' and not exists (select 1 from animal_tags t where t.animal_id=a.id and t.tag_type='RFID');
  insert into intake_lots(id, farm_id, kind, date, source_partner_id, quarantine_until, vet_cert_no, price, head_count, note) select F||'-LN-H'||v.n, F, 'MUA', d0 + v.off, 'NCC-0001', d0 + v.off + 21, 'KD-'||to_char(d0+v.off,'YYMM')||'-'||v.n, v.price, v.head, v.note from (values ('01','BO',0,28000000,16,'Nái đợt 1'),('02','BO',90,28000000,16,'Nái đợt 2'),('03','BO',180,28000000,13,'Nái đợt 3'),('04','BO',0,22000000,30,'Tơ vỗ béo lứa 1'),('05','BO',180,22000000,30,'Tơ vỗ béo lứa 2'),('06','BO',360,22000000,30,'Tơ vỗ béo lứa 3'),('07','BO',540,22000000,30,'Tơ vỗ béo lứa 4'),('08','DE',90,6500000,44,'Dê giống'),('09','GA',0,18000,3000,'Gà hậu bị lứa 00'),('10','GA',456,18000,3000,'Gà hậu bị lứa 01')) v(n,kind,off,price,head,note) where not exists (select 1 from intake_lots x where x.id=F||'-LN-H'||v.n);
  update animals a set intake_lot_id = case when a.id like F||'-BO-H0%' and right(a.id,3)::int<=16 then F||'-LN-H01' when a.id like F||'-BO-H0%' and right(a.id,3)::int<=32 then F||'-LN-H02' when a.id like F||'-BO-H%' then F||'-LN-H03' when a.id like F||'-BO-V1%' then F||'-LN-H04' when a.id like F||'-BO-V2%' then F||'-LN-H05' when a.id like F||'-BO-V3%' then F||'-LN-H06' when a.id like F||'-BO-V4%' then F||'-LN-H07' when a.id like F||'-DE-C%' or a.id like F||'-DE-D%' then F||'-LN-H08' else a.intake_lot_id end where a.farm_id=F and a.intake_lot_id is null;
  for k in 0..(M/3) loop d := (d0 + (k*3||' months')::interval)::date + 15; exit when d > current_date;
    for r in select id from devices where farm_id=F and active loop
      insert into calibrations(farm_id, ts, created_by, source, client_ref, target_device_id, method, before_val, after_val, result, next_due) values (F, d + time '09:00', U, 'IMPORT', 'h2-cal-'||k||'-'||r.id, r.id, 'Chuẩn quả cân/ dung dịch chuẩn', 100 + (k%5)*0.3, 100, case when k%7=3 then 'HIEU_CHINH' else 'DAT' end, d + 90) on conflict do nothing;
    end loop;
    update devices set calib_due = (select max(next_due) from calibrations c where c.target_device_id=devices.id) where farm_id=F;
    insert into compliance_checks(farm_id, standard_code, requirement_id, checked_at, checked_by, result, evidence, nc_severity, corrective_action, due_date, closed_at)
    select F, sr.standard_code, sr.id, d + time '10:00', 'NS-108', case when (k+sr.id)%9=0 then 'KHONG_DAT' else 'DAT' end, 'Audit nội bộ quý '||(k%4+1)||' — bằng chứng từ dữ liệu vận hành', case when (k+sr.id)%9=0 then sr.level end, case when (k+sr.id)%9=0 then 'CAPA: cập nhật SOP + đào tạo lại' end, case when (k+sr.id)%9=0 then d+30 end, case when (k+sr.id)%9=0 and d+30<current_date then d+25+time '10:00' end
    from standard_requirements sr where sr.standard_code in ('VIETGAP-CN','VN-TT66','HACCP') and (sr.id + k) % 4 = 0 and not exists (select 1 from compliance_checks c where c.farm_id=F and c.requirement_id=sr.id and c.checked_at::date = d);
  end loop;
  insert into certifications(id, farm_id, org_id, standard_code, body, cert_number, scope, issued_on, valid_to, status, next_audit) values (F||'-CERT-VGCN', F, 'ITRAN', 'VIETGAP-CN', 'Trung tâm Chứng nhận VietCert', 'VG-CN-2025-0'||right(F,1)||'18', 'Bò thịt, gà đẻ – trại '||F, d0 + 400, d0 + 400 + 730, 'HIEU_LUC', current_date + 60), (F||'-CERT-VGTT', F, 'ITRAN', 'VIETGAP-TT', 'VietCert', 'VG-TT-2025-0'||right(F,1)||'22', 'Bắp sinh khối, rau ăn lá', d0 + 420, d0 + 420 + 730, 'HIEU_LUC', current_date + 75), (F||'-CERT-ATTP', F, 'ITRAN', 'HACCP', 'Chi cục ATTP', 'ATTP-'||F||'-2026', 'Xưởng D5, sơ chế', d0 + 700, d0 + 700 + 1095, 'HIEU_LUC', current_date + 200) on conflict do nothing;
  for k in 0..(M-1) loop d := (d0 + (k||' months')::interval)::date + 12; exit when d > current_date; if k%2=0 then
    insert into leave_requests(farm_id, staff_id, kind, from_date, to_date, days, reason, status, approved_by, approved_at, created_at) select F, s.id, (array['PHEP_NAM','OM','VIEC_RIENG'])[1+(k+length(s.id))%3], d, d+1+(k%2), 2+(k%2), 'lý do cá nhân', 'DUYET', 'NS-002', d - 3 + time '10:00', d - 5 + time '09:00' from staff s where s.farm_id=F and s.active and (length(s.id)+k)%6=0 and not exists (select 1 from leave_requests l where l.staff_id=s.id and l.from_date=d); end if; end loop;
  for k in -8..4 loop d := (date_trunc('week', current_date) + (k*7||' days')::interval)::date;
    insert into production_plans(id, farm_id, week_start, sku, qty_plan, unit, line, source, qty_done, status, created_by) values (F||'-PP-'||to_char(d,'YYMMDD')||'-T', F, d, 'SKU-TMR-25', 100, 'bao', 'DONG_GOI', 'HOP_DONG', case when d < current_date-7 then 100 else 0 end, case when d < current_date-7 then 'XONG' when d <= current_date then 'DANG_SX' else 'KE_HOACH' end, U), (F||'-PP-'||to_char(d,'YYMMDD')||'-V', F, d, 'TA-VIEN-GA', 2450, 'kg', 'D5_VIEN', 'DU_BAO', case when d < current_date-7 then 2450 else 0 end, case when d < current_date-7 then 'XONG' when d <= current_date then 'DANG_SX' else 'KE_HOACH' end, U) on conflict do nothing; end loop;
  insert into documents(farm_id, org_id, ref_table, ref_id, kind, title, file, mime, size_bytes, tags, expires_on, uploaded_by, status) select F, 'ITRAN', v.rt, v.rid, v.kind, v.title, '/uploads/seed/'||v.fname, 'application/pdf', 200000+(row_number() over ())*7000, v.tags::text[], v.exp, U, 'ACTIVE' from (values
   ('farms',F,'GIAY_PHEP','Giấy chứng nhận đủ điều kiện chăn nuôi','gcn-chan-nuoi.pdf','{PHAP_LY}',current_date+400),('farms',F,'GIAY_PHEP','Giấy phép môi trường','gpmt.pdf','{PHAP_LY,MOI_TRUONG}',current_date+700),('certifications',F||'-CERT-VGCN','CHUNG_NHAN','Chứng chỉ VietGAP chăn nuôi','vietgap-cn.pdf','{CHUNG_NHAN}',d0+400+730),
   ('purchase_orders',F||'-PO-H001','COA','COA bã bia tháng','coa-babia.pdf','{COA}',null),('animals',F||'-BO-H001','KIEM_DICH','Giấy kiểm dịch đợt nái 1','kiem-dich-1.pdf','{THU_Y}',null),('loans',F||'-VAY-01','HOP_DONG','Hợp đồng tín dụng Agribank','hdtd.pdf','{TAI_CHINH}',null),
   ('sops','SOP-BO-07.2','SOP','SOP trộn TMR (bản ký)','sop-bo-07-2.pdf','{SOP}',current_date+300),('insurance_policies',F||'-BH-01','HOP_DONG','Hợp đồng bảo hiểm vật nuôi','bh-vat-nuoi.pdf','{BAO_HIEM}',current_date+300)) v(rt,rid,kind,title,fname,tags,exp)
  where not exists (select 1 from documents dd where dd.farm_id=F and dd.title=v.title);
  -- quy trình đã chạy xong 6 lượt (3 tháng gần) + 2 đang chạy
  begin
    for k in 0..7 loop
      d := current_date - 90 + k*12;
      select start_process_run(F, (array['SOP-BO-01','SOP-TT-01','SOP-CB-06','SOP-GA-03','SOP-SH-01','SOP-HC-02','SOP-KD-01','SOP-AT-04'])[k+1], U, null, null, 'Lượt '||to_char(d,'DD/MM'), '{}'::jsonb) into s_id;
      if k < 6 then update process_run_steps set status='XONG', started_at=d, done_at=d + interval '1 day', done_by=U where run_id=s_id; update process_runs set status='XONG', finished_at=d + interval '3 days', started_at=d where id=s_id; update tasks set status='XONG', done_by=U, done_at=d + interval '1 day' where ref_table='process_runs' and ref_id=s_id::text; end if;
    end loop;
  exception when others then raise notice 'process runs: %', sqlerrm; end;
end $$;
select 'feed_logs' t, count(*) from feed_logs where farm_id=:'farm' union all select 'batch_logs', count(*) from batch_logs where farm_id=:'farm' union all select 'checklist_runs', count(*) from checklist_runs where farm_id=:'farm' union all select 'gate_logs', count(*) from gate_logs where farm_id=:'farm' union all select 'expense_requests', count(*) from expense_requests where farm_id=:'farm' union all select 'orders', count(*) from orders where farm_id=:'farm' union all select 'hosp_bookings', count(*) from hosp_bookings where farm_id=:'farm' union all select 'pos_receipts', count(*) from pos_receipts where farm_id=:'farm' union all select 'compliance_checks', count(*) from compliance_checks where farm_id=:'farm' union all select 'process_runs', count(*) from process_runs where farm_id=:'farm';
