/* Giả lập N ngày vận hành trại F01 (mặc định 30) — dữ liệu "như thật": cho ăn 2 cữ/đàn (sai số ~1–4%), cân bò 2 tuần/lần, sinh sản,
 * gà đẻ 76–80% + chết lẻ, RAS ăn/chết, thu cỏ/bắp theo lô + nhiên liệu + giờ máy, khu D nạp/thu, D5 mẻ, xuất kho cho ăn, bán trứng/phân trùn/TMR,
 * kiểm kê tuần, checklist ca, phiếu giấy (10% bản ghi từ giấy), vài sự cố; đồng thời "gài" lệch có chủ ý để RC bắt (thức ăn xuất > cho ăn 6% ở 1 ngày,
 * dầu vượt định mức, phiếu giấy quá 24h, seri nhảy quãng). Chạy: pnpm db:seed:sim [days] */
import { Client } from "pg";
import "dotenv/config";
const ADMIN = process.env.DATABASE_ADMIN_URL ?? "postgres://postgres:itranagri@localhost:54499/itranagri";
const DAYS = Number(process.argv[2] ?? 30); const FARM = "F01";
const rnd = (a: number, b: number) => a + Math.random() * (b - a); const ri = (a: number, b: number) => Math.floor(rnd(a, b + 1)); const pick = <T,>(a: T[]) => a[ri(0, a.length - 1)];
const at = (day: Date, h: number, m = ri(0, 59)) => { const d = new Date(day); d.setHours(h, m, ri(0, 59), 0); return d.toISOString(); };
let ref = 0; const cref = (p: string) => `sim-${p}-${Date.now().toString(36)}-${(ref++).toString(36)}`;

async function main() {
  const c = new Client({ connectionString: ADMIN }); await c.connect();
  await c.query("select set_config('app.org_id','ITRAN',false), set_config('app.farm_id',$1,false), set_config('app.role','it_engineer',false), set_config('app.staff_id','SIM',false)", [FARM]);
  const cows = (await c.query("select id, sex, status from animals where farm_id=$1 and species='BO' and status not in ('CHET','XUAT')", [FARM])).rows;
  const dams = cows.filter((a) => a.sex === "F" && !["THEO_ME", "SO_SINH"].includes(a.status));
  const groups = Object.fromEntries((await c.query("select id, kind, head_count from animal_groups where farm_id=$1", [FARM])).rows.map((g) => [g.kind + (g.id.endsWith("02") ? "2" : ""), g]));
  const wh = Object.fromEntries((await c.query("select code, id from warehouses where farm_id=$1", [FARM])).rows.map((w) => [w.code, w.id]));
  const lots = Object.fromEntries((await c.query("select sku, id from lots where farm_id=$1", [FARM])).rows.map((l) => [l.sku, l.id]));
  const staff = { a1: "NS-011", a2: "NS-012", a3: "NS-013", a4: "NS-014", a5: "NS-015", a6: "NS-016", a7: "NS-017", a8: "NS-018", a9: "NS-019", a11: "NS-020", tl: "NS-006", ktt: "NS-003" };
  const ins = async (t: string, o: Record<string, unknown>) => { const cols = Object.keys(o).filter((k) => o[k] !== undefined); const JSONB = new Set(["inputs","outputs","lines","results","ccp_readings","qc","detail","input_lots"]); const vals = cols.map((k) => { const v = o[k]; return JSONB.has(k) || (v && typeof v === "object" && !Array.isArray(v)) ? JSON.stringify(v) : v; }); await c.query(`insert into ${t}(${cols.join(",")}) values (${cols.map((_, i) => `$${i + 1}`).join(",")}) on conflict do nothing`, vals); };
  const day0 = new Date(); day0.setDate(day0.getDate() - DAYS);
  const paperSerial: Record<string, number> = {}; let counts = 0;
  const bump = () => { counts++; };
  for (let d = 0; d < DAYS; d++) {
    const day = new Date(day0); day.setDate(day0.getDate() + d); const dow = day.getDay(); const isPast = d < DAYS - 1;
    const paper = Math.random() < 0.1; const psrc = (t?: string) => { if (!(paper && t)) return {}; paperSerial[t] = (paperSerial[t] ?? 5000) + 1; return { source: "PAPER", paper_serial: `${FARM}-${t}-${String(paperSerial[t]).padStart(6, "0")}`, is_backfill: true }; };
    // ---- A1: TMR 2 cữ cho đàn nái + vỗ; xuất kho K3/K4 tương ứng (ngày 12 gài lệch 6%)
    for (const [gk, meal, hour] of [["BO_NHOM", "SANG", 6], ["BO_NHOM", "CHIEU", 15], ["BO_NHOM2", "SANG", 6], ["BO_NHOM2", "CHIEU", 15]] as const) {
      const g = groups[gk]; if (!g) continue; const head = Math.max(1, Number(g.head_count) || (gk === "BO_NHOM" ? 20 : 8));
      const planned = Math.round(head * rnd(15, 17)); const err = Math.random() < 0.85 ? rnd(-0.02, 0.02) : rnd(-0.06, 0.06); const actual = Math.round(planned * (1 + err));
      await ins("feed_logs", { farm_id: FARM, ts: at(day, hour), created_by: staff.a1, client_ref: cref("f"), batch_ref: `TMR-${day.toISOString().slice(5, 10)}-${meal}`, recipe_id: "RC-TMR-VO", recipe_version: 1, dest_group_id: g.id, dest_location_id: gk === "BO_NHOM" ? "F01-CH-NAI-1" : "F01-CH-VO-1", planned_kg: planned, qty_kg: actual, meal, leftover_pct: rnd(2, 6).toFixed(1), photo_urls: Math.random() < 0.9 ? ["/uploads/sim/mang.jpg"] : [], ...psrc("BM01") }); bump();
      const factor = d === 12 ? 1.06 : 1.0; // gài lệch RC1
      await ins("inventory_moves", { farm_id: FARM, ts: at(day, hour, 5), created_by: staff.a1, client_ref: cref("m"), warehouse_id: wh.K3, sku: "NL-BAP-U", lot_id: lots["NL-BAP-U"], direction: -1, qty: Math.round(actual * 0.45 * factor), unit: "kg", reason: "XUAT_CHO_AN", from_to: g.id, weigh_point: "CAN_CAU_D" });
      await ins("inventory_moves", { farm_id: FARM, ts: at(day, hour, 6), created_by: staff.a1, client_ref: cref("m"), warehouse_id: wh.K2, sku: "NL-BA-BIA", lot_id: lots["NL-BA-BIA"], direction: -1, qty: Math.round(actual * 0.25 * factor), unit: "kg", reason: "XUAT_CHO_AN", from_to: g.id, weigh_point: "CUA_KHO" });
      await ins("inventory_moves", { farm_id: FARM, ts: at(day, hour, 7), created_by: staff.a1, client_ref: cref("m"), warehouse_id: wh.K2, sku: "NL-ROM", lot_id: lots["NL-ROM"], direction: -1, qty: Math.round(actual * 0.15 * factor), unit: "kg", reason: "XUAT_CHO_AN", from_to: g.id, weigh_point: "CUA_KHO" });
      await ins("inventory_moves", { farm_id: FARM, ts: at(day, hour, 8), created_by: staff.a1, client_ref: cref("m"), warehouse_id: wh.K3, sku: "NL-CO-TUOI", lot_id: lots["NL-CO-TUOI"], direction: -1, qty: Math.round(actual * 0.08 * factor), unit: "kg", reason: "XUAT_CHO_AN", from_to: g.id, weigh_point: "CAN_CAU_D" });
      await ins("inventory_moves", { farm_id: FARM, ts: at(day, hour, 9), created_by: staff.a1, client_ref: cref("m"), warehouse_id: wh.K2, sku: "NL-KHOANG", lot_id: lots["NL-KHOANG"], direction: -1, qty: Math.round(actual * 0.03 * factor), unit: "kg", reason: "XUAT_CHO_AN", from_to: g.id, weigh_point: "CUA_KHO" });
      await ins("inventory_moves", { farm_id: FARM, ts: at(day, hour, 9), created_by: staff.a1, client_ref: cref("m"), warehouse_id: wh.K2, sku: "NL-RI-MAT", lot_id: lots["NL-RI-MAT"], direction: -1, qty: Math.round(actual * 0.04 * factor), unit: "kg", reason: "XUAT_CHO_AN", from_to: g.id, weigh_point: "CUA_KHO" });
    }
    // ---- A2: cân 2 tuần/lần, sinh sản
    if (d % 14 === 3) for (const a of cows) { const base = a.status === "THEO_ME" ? 40 + d * 0.9 : 300 + d * 0.8; await ins("animal_events", { farm_id: FARM, ts: at(day, 8), created_by: staff.a2, client_ref: cref("w"), animal_id: a.id, event_type: "CAN", value: Math.round(base + rnd(-8, 12)), unit: "kg", detail: { gain_kg: rnd(8, 14).toFixed(1) } }); bump(); }
    if (Math.random() < 0.35 && dams.length) { const a = pick(dams); await ins("animal_events", { farm_id: FARM, ts: at(day, 7), created_by: staff.a2, client_ref: cref("e"), animal_id: a.id, event_type: "DONG_DUC", detail: { source: "quan_sat" } }); await ins("animal_events", { farm_id: FARM, ts: at(day, 9), created_by: staff.a2, client_ref: cref("e"), animal_id: a.id, event_type: "PHOI", detail: { semen_lot: "TINH-BRAHMAN/LOT-24", new_status: "PHOI" }, ...psrc("BM02") }); bump(); }
    if (Math.random() < 0.25 && dams.length) { const a = pick(dams); const pos = Math.random() < 0.6; await ins("animal_events", { farm_id: FARM, ts: at(day, 10), created_by: staff.a2, client_ref: cref("e"), animal_id: a.id, event_type: "KHAM_THAI", detail: { result: pos ? "+" : "-", ...(pos ? { new_status: "MANG_THAI" } : {}) } }); bump(); }
    if (Math.random() < 0.08 && dams.length) { const a = pick(dams); await ins("animal_events", { farm_id: FARM, ts: at(day, 11), created_by: staff.a2, client_ref: cref("e"), animal_id: a.id, event_type: "BENH", detail: { note: "bỏ ăn, sốt nhẹ" } }); await ins("animal_events", { farm_id: FARM, ts: at(day, 14), created_by: staff.a2, client_ref: cref("e"), animal_id: a.id, event_type: "DIEU_TRI", value: 1, unit: "lieu", detail: { note: "Oxytetracycline 15ml IM", dose_units: 1, protocol: "TP-017" }, withdrawal_until: new Date(day.getTime() + 21 * 86400e3).toISOString().slice(0, 10) }); await ins("inventory_moves", { farm_id: FARM, ts: at(day, 14, 10), created_by: staff.a2, client_ref: cref("m"), warehouse_id: wh.K1, sku: "TH-OXY", lot_id: lots["TH-OXY"], direction: -1, qty: 1, unit: "lo", reason: "XUAT_SX", from_to: a.id, weigh_point: "CUA_KHO" }); bump(); }
    // ---- A3: gà đẻ
    const gaDe = groups.GA_DE; if (gaDe) { const hens = Number(gaDe.head_count) || 3000; const eggs = Math.round(hens * rnd(0.755, 0.80)); await ins("animal_events", { farm_id: FARM, ts: at(day, 16), created_by: staff.a3, client_ref: cref("g"), group_id: gaDe.id, event_type: "SO_LUONG", value: eggs, unit: "qua", detail: { metric: "eggs_counted" } });
      const trays = Math.round(eggs * (d === 20 ? 0.95 : 0.99) / 10); await ins("inventory_moves", { farm_id: FARM, ts: at(day, 17), created_by: staff.a3, client_ref: cref("m"), warehouse_id: wh.K5, sku: "SKU-TRUNG-10", lot_id: (await c.query("select ensure_lot($1,'SKU-TRUNG-10',$2) as id", [FARM, `${FARM}-ME-${day.toISOString().slice(2, 10).replace(/-/g, "")}-TRA`])).rows[0].id, direction: 1, qty: trays, unit: "vi", unit_cost: 22000, reason: "NHAP_SX", from_to: "GA-DE", weigh_point: "APP", ...psrc("BM05") });
      const dead = Math.random() < 0.7 ? ri(0, 2) : (d === 25 ? 6 : ri(0, 1)); if (dead) await ins("animal_events", { farm_id: FARM, ts: at(day, 7), created_by: staff.a3, client_ref: cref("g"), group_id: gaDe.id, event_type: "CHET", value: dead, unit: "con", detail: { note: "chết lẻ" } });
      await ins("feed_logs", { farm_id: FARM, ts: at(day, 6, 30), created_by: staff.a3, client_ref: cref("f"), recipe_id: "RC-GA-DE", recipe_version: 1, dest_group_id: gaDe.id, dest_location_id: "F01-GA-DE", planned_kg: Math.round(hens * 0.115), qty_kg: Math.round(hens * rnd(0.11, 0.12)), meal: "SANG" }); bump(); }
    // ---- A7: D5 ép viên gà 400 kg/ngày → K4, rồi xuất cho ăn gà + RAS
    { const vienLot = (await c.query("select ensure_lot($1,'TA-VIEN-GA',$2) as id", [FARM, `${FARM}-ME-${day.toISOString().slice(2, 10).replace(/-/g, "")}-V1`])).rows[0].id; const kg = ri(380, 420);
      await ins("batch_logs", { farm_id: FARM, ts: at(day, 5), created_by: staff.a7, client_ref: cref("b"), batch_code: `${FARM}-ME-${day.toISOString().slice(2, 10).replace(/-/g, "")}-V1`, line: "D5_VIEN", recipe_id: "RC-GA-DE", recipe_version: 1, location_id: "F01-D5", inputs: [{ sku: "NL-BAP-U", kg: Math.round(kg * 0.55), lot_id: lots["NL-BAP-U"] }, { sku: "NL-BA-BIA", kg: Math.round(kg * 0.25), lot_id: lots["NL-BA-BIA"] }, { sku: "NL-KHOANG", kg: Math.round(kg * 0.05), lot_id: lots["NL-KHOANG"] }, { sku: "NL-RI-MAT", kg: Math.round(kg * 0.05), lot_id: lots["NL-RI-MAT"] }, { sku: "NL-ROM", kg: Math.round(kg * 0.1), lot_id: lots["NL-ROM"] }], outputs: [{ sku: "TA-VIEN-GA", kg, lot_id: vienLot }], qc: { protein_pct: rnd(16.5, 17.5).toFixed(1), mix_err_pct: rnd(0.5, 2.5).toFixed(1) }, ccp_readings: [{ ccp: "KIM_LOAI", ok: true }] });
      for (const [sku, k] of [["NL-BAP-U", 0.55], ["NL-BA-BIA", 0.25], ["NL-KHOANG", 0.05], ["NL-RI-MAT", 0.05], ["NL-ROM", 0.1]] as const) await ins("inventory_moves", { farm_id: FARM, ts: at(day, 5, 10), created_by: staff.a7, client_ref: cref("m"), warehouse_id: sku === "NL-BAP-U" ? wh.K3 : wh.K2, sku, lot_id: lots[sku], direction: -1, qty: Math.round(kg * k), unit: "kg", reason: "XUAT_SX", from_to: "D5", weigh_point: "CUA_KHO" });
      await ins("inventory_moves", { farm_id: FARM, ts: at(day, 5, 50), created_by: staff.a7, client_ref: cref("m"), warehouse_id: wh.K4, sku: "TA-VIEN-GA", lot_id: vienLot, direction: 1, qty: kg, unit: "kg", unit_cost: 9500, reason: "NHAP_SX", from_to: "D5", weigh_point: "CUA_KHO" });
      const gaKg = Math.round((Number(groups.GA_DE?.head_count) || 3000) * 0.115); await ins("inventory_moves", { farm_id: FARM, ts: at(day, 6, 20), created_by: staff.a3, client_ref: cref("m"), warehouse_id: wh.K4, sku: "TA-VIEN-GA", lot_id: vienLot, direction: -1, qty: gaKg + 24, unit: "kg", reason: "XUAT_CHO_AN", from_to: "GA-DE+RAS", weigh_point: "SILO_SENSOR" }); }
    // ---- A4: RAS
    for (const gk of ["RAS", "RAS2"]) { const g = groups[gk]; if (!g) continue; await ins("feed_logs", { farm_id: FARM, ts: at(day, 7), created_by: staff.a4, client_ref: cref("f"), dest_group_id: g.id, dest_location_id: "F01-RAS", planned_kg: 12, qty_kg: rnd(11, 13).toFixed(1), meal: "SANG" }); if (Math.random() < 0.3) await ins("animal_events", { farm_id: FARM, ts: at(day, 8), created_by: staff.a4, client_ref: cref("r"), group_id: g.id, event_type: "CHET", value: ri(1, 3), unit: "con", detail: { note: "vớt" } }); await ins("sensor_reads", { ts: at(day, 3), farm_id: FARM, device_id: "F01-TB-020", metric: "DO", value: d === 18 ? 3.6 : rnd(5.2, 7.1).toFixed(2) }); await ins("sensor_reads", { ts: at(day, 15), farm_id: FARM, device_id: "F01-TB-020", metric: "DO", value: rnd(5.5, 7.5).toFixed(2) }); }
    for (let h = 0; h < 24; h += 2) await ins("sensor_reads", { ts: at(day, h, 0), farm_id: FARM, device_id: "F01-TB-021", metric: "TEMP_COLD", value: (d === 22 && h === 14 ? 9.4 : rnd(2, 5)).toFixed(1) });
    // ---- A5: trồng trọt — cắt cỏ 2 ngày/lần, thu bắp G1A tuần 2–3, làm đất G2A
    if (d % 2 === 0) { const kg = ri(2500, 4200); const hrs = rnd(2, 3.5); const machine = "F01-TB-002"; await ins("crop_logs", { farm_id: FARM, ts: at(day, 8), created_by: staff.a5, client_ref: cref("c"), plot_id: pick(["F01-LO-K01", "F01-LO-K02"]), activity: "CAT", variety: "Mombasa", qty_kg: kg, moisture_pct: rnd(70, 78).toFixed(0), machine_id: machine, machine_hours: hrs.toFixed(1), fuel_l: (hrs * 14 * rnd(0.95, 1.05)).toFixed(1), ...psrc("BM03") }); await ins("inventory_moves", { farm_id: FARM, ts: at(day, 10), created_by: staff.a5, client_ref: cref("m"), warehouse_id: wh.K3, sku: "NL-CO-TUOI", lot_id: lots["NL-CO-TUOI"], direction: 1, qty: Math.round(kg * rnd(0.97, 1.0)), unit: "kg", unit_cost: 600, reason: "NHAP_SX", from_to: "LO-K", weigh_point: "CAN_CAU_D" }); await ins("inventory_moves", { farm_id: FARM, ts: at(day, 7, 30), created_by: staff.a5, client_ref: cref("m"), warehouse_id: wh.K7, sku: "NL-DAU", direction: -1, qty: Math.round(hrs * 14 * (d === 16 ? 1.3 : 1.0)), unit: "l", reason: "XUAT_SX", from_to: machine, weigh_point: "TRAM_DAU" }); await c.query("update devices set machine_hours = machine_hours + $2 where id=$1", [machine, hrs]); bump(); }
    if (d >= 14 && d <= 20) { const kg = ri(18000, 26000); await ins("crop_logs", { farm_id: FARM, ts: at(day, 9), created_by: staff.a5, client_ref: cref("c"), plot_id: "F01-LO-G1A", activity: "THU", variety: "Bắp sinh khối NK7328", qty_kg: kg, moisture_pct: 68, machine_id: "F01-TB-002", machine_hours: 6, fuel_l: 84 }); await ins("inventory_moves", { farm_id: FARM, ts: at(day, 12), created_by: staff.a5, client_ref: cref("m"), warehouse_id: wh.K3, sku: "NL-BAP-U", lot_id: lots["NL-BAP-U"], direction: 1, qty: Math.round(kg * 0.985), unit: "kg", unit_cost: 850, reason: "NHAP_SX", from_to: "LO-G1A", weigh_point: "CAN_CAU_D" }); await ins("inventory_moves", { farm_id: FARM, ts: at(day, 7), created_by: staff.a5, client_ref: cref("m"), warehouse_id: wh.K7, sku: "NL-DAU", direction: -1, qty: 84, unit: "l", reason: "XUAT_SX", from_to: "F01-TB-002", weigh_point: "TRAM_DAU" }); await ins("batch_logs", { farm_id: FARM, ts: at(day, 16), created_by: staff.a7, client_ref: cref("b"), batch_code: `${FARM}-ME-${day.toISOString().slice(2, 10).replace(/-/g, "")}-U${ri(1, 9)}`, line: "U_CHUA", location_id: "F01-D5", inputs: [{ sku: "NL-BAP-U", kg, lot_id: lots["NL-BAP-U"] }], outputs: [{ sku: "NL-BAP-U", kg: Math.round(kg * 0.97), lot_id: lots["NL-BAP-U"] }], moisture_pct: 66 }); }
    // ---- A6: khu D — nạp trùn hằng ngày (~60% phân), thu phân trùn tuần
    const herd = cows.length; const manure = Math.round(herd * 15 * rnd(0.55, 0.65)); await ins("batch_logs", { farm_id: FARM, ts: at(day, 9), created_by: staff.a6, client_ref: cref("b"), batch_code: `${FARM}-ME-${day.toISOString().slice(2, 10).replace(/-/g, "")}-TN`, line: "TRUN_NAP", location_id: d % 2 ? "F01-TR-01" : "F01-TR-02", inputs: [{ sku: "PHAN_UOT", kg: manure }], outputs: [], temp_c: ri(24, 31), ...psrc("BM04") }); bump();
    await ins("batch_logs", { farm_id: FARM, ts: at(day, 10), created_by: staff.a6, client_ref: cref("b"), batch_code: `${FARM}-ME-${day.toISOString().slice(2, 10).replace(/-/g, "")}-BG`, line: "BIOGAS", location_id: "F01-KHU-D", inputs: [{ sku: "PHAN_UOT", kg: Math.round(herd * 15 * 0.38) }], outputs: [{ sku: "DIEN_KWH", kg: ri(40, 70) }] });
    if (dow === 5) { const kg = ri(900, 1400); const lot = (await c.query("select ensure_lot($1,'SKU-PTR-25',$2) as id", [FARM, `${FARM}-ME-${day.toISOString().slice(2, 10).replace(/-/g, "")}-PT`])).rows[0].id; await ins("batch_logs", { farm_id: FARM, ts: at(day, 14), created_by: staff.a6, client_ref: cref("b"), batch_code: `${FARM}-ME-${day.toISOString().slice(2, 10).replace(/-/g, "")}-PT`, line: "TRUN_THU", location_id: "F01-TR-01", inputs: [{ sku: "PHAN_UOT", kg: Math.round(kg * 2.2), lot_id: null }], outputs: [{ sku: "SKU-PTR-25", kg, lot_id: lot, labels: Math.round(kg / 25) }], moisture_pct: 33 }); await ins("inventory_moves", { farm_id: FARM, ts: at(day, 15), created_by: staff.a6, client_ref: cref("m"), warehouse_id: wh.K5, sku: "SKU-PTR-25", lot_id: lot, direction: 1, qty: Math.round(kg / 25), unit: "bao", unit_cost: 60000, reason: "NHAP_SX", from_to: "KHU-D", weigh_point: "CUA_KHO" }); await ins("inventory_moves", { farm_id: FARM, ts: at(day, 15, 10), created_by: staff.a6, client_ref: cref("m"), warehouse_id: wh.K9, sku: "BB-TEM", lot_id: lots["BB-TEM"], direction: -1, qty: Math.round(kg / 25), unit: "cai", reason: "XUAT_SX", from_to: "PT", weigh_point: "CUA_KHO" }); }
    // ---- A9: bán hàng — trứng hằng ngày, phân trùn 2 lần/tuần, TMR bao tuần
    const eggLot = (await c.query("select id from lots where farm_id=$1 and sku='SKU-TRUNG-10' order by created_at desc limit 1", [FARM])).rows[0]?.id;
    const eggQty = ri(150, 230); await ins("inventory_moves", { farm_id: FARM, ts: at(day, 17, 20), created_by: staff.a8, client_ref: cref("m"), warehouse_id: wh.K5, sku: "SKU-TRUNG-10", lot_id: eggLot, direction: -1, qty: eggQty, unit: "vi", reason: "XUAT_BAN", from_to: "KH", weigh_point: "CUA_KHO" });
    await ins("sales", { farm_id: FARM, ts: at(day, 17, 30), created_by: staff.a9, client_ref: cref("s"), partner_id: pick(["KH-0003", "KH-0004", "KH-0001"]), sku: "SKU-TRUNG-10", lot_id: eggLot, qty: eggQty, unit: "vi", price: pick([38000, 38000, 40000, 36000]), amount: 0, channel: pick([2, 3, 1]), payment: pick(["CK", "VIETQR", "POS", "CONG_NO"]), paid: undefined, ...psrc("BM06") });
    if (dow === 2 || dow === 6) { const ptLot = (await c.query("select id from lots where farm_id=$1 and sku='SKU-PTR-25' order by created_at desc limit 1", [FARM])).rows[0]?.id; const q = ri(20, 60); await ins("sales", { farm_id: FARM, ts: at(day, 10), created_by: staff.a9, client_ref: cref("s"), partner_id: "KH-0002", sku: "SKU-PTR-25", lot_id: ptLot, qty: q, unit: "bao", price: 78000, amount: q * 78000, channel: 1, payment: d < 10 ? "CONG_NO" : "CK", paid: d >= 10 }); await ins("inventory_moves", { farm_id: FARM, ts: at(day, 10, 20), created_by: staff.a8, client_ref: cref("m"), warehouse_id: wh.K5, sku: "SKU-PTR-25", lot_id: ptLot, direction: -1, qty: q, unit: "bao", reason: "XUAT_BAN", from_to: "KH-0002", weigh_point: "CUA_KHO" }); }
    await c.query("update sales set amount = qty*price where farm_id=$1 and amount=0", [FARM]); await c.query("update sales set paid = (payment<>'CONG_NO') where farm_id=$1 and paid is null", [FARM]);
    // ---- A11: cổng
    for (let k = 0; k < ri(2, 5); k++) await ins("gate_logs", { farm_id: FARM, ts: at(day, ri(6, 18)), created_by: staff.a11, client_ref: cref("gt"), plate: `89C-${ri(100, 999)}.${ri(10, 99)}`, direction: pick(["VAO", "RA"]), weighed: Math.random() < 0.9, anolyte_wash: Math.random() < 0.95, purpose: pick(["giao rơm", "lấy phân trùn", "thú y", "khách", "giao trứng"]), ...psrc("BM08") });
    // ---- checklist ca (A1, A3, A6, A8)
    for (const [sop, who] of [["SOP-BO-07.2", staff.a1], ["SOP-GA-02.1", staff.a3], ["SOP-TR-01.3", staff.a6], ["SOP-KHO-01.1", staff.a8]]) { const green = Math.random() < 0.9; await ins("checklist_runs", { farm_id: FARM, ts: at(day, 6, 40), created_by: who, client_ref: cref("k"), sop_code: sop, sop_version: 1, shift: "SANG", results: [{ n: 1, ok: true }, { n: 2, ok: green }], all_green: green, note: green ? null : "bước 2 chưa đạt — máng ướt", approved_by: isPast ? staff.tl : null, approved_at: isPast ? at(day, 9) : null }); }
    // ---- kiểm kê tuần K4/K5, tháng K2
    if (dow === 6) { const bal = (await c.query("select sku, sum(qty) as q from v_stock_balance where farm_id=$1 and warehouse_code='K5' group by sku", [FARM])).rows; await ins("stocktakes", { farm_id: FARM, ts: at(day, 16), created_by: staff.tl, client_ref: cref("st"), warehouse_id: wh.K5, counted_by: staff.tl, lines: bal.map((b) => ({ sku: b.sku, book: Number(b.q), counted: Math.round(Number(b.q) * rnd(0.985, 1.005)) })), note: "kiểm kê tuần — người ngoài bộ phận" }); await ins("stocktakes", { farm_id: FARM, ts: at(day, 16, 30), created_by: staff.tl, client_ref: cref("st"), warehouse_id: wh.K8, counted_by: staff.tl, lines: [{ sku: "BO", counted: herd }], camera_count: herd, note: "đếm đàn tuần" }); }
    // ---- sự cố thi thoảng
    if (d === 9) await ins("incidents", { farm_id: FARM, ts: at(day, 11), created_by: staff.a5, client_ref: cref("i"), code: `${FARM}-INC-2026-0001`, kind: "THIET_BI", severity: "TRUNG", description: "Máy thu sinh khối kẹt băng tải 40 phút", location_id: "F01-LO-K01" });
    if (d === 21) await ins("incidents", { farm_id: FARM, ts: at(day, 20), created_by: staff.a11, client_ref: cref("i"), code: `${FARM}-INC-2026-0002`, kind: "AN_NINH", severity: "NEAR_MISS", description: "Xe lạ dừng gần rào phía nam, đã rời đi", location_id: "F01-CONG" });
    // ---- phiếu giấy đã nộp (paper_scans) — 1 tờ/ngày; gài 1 tờ chưa số hóa >24h và nhảy quãng seri BM01
    const serial = `${FARM}-BM07-${String(1000 + d * (d === 26 ? 2 : 1)).padStart(6, "0")}`; await ins("paper_scans", { farm_id: FARM, ts: at(day, 18), created_by: staff.a1, client_ref: cref("p"), form_code: "BM07", serial, photo_url: "/uploads/sim/bm01.jpg", uploaded_by: staff.a1, digitized: d < DAYS - 3, digitized_by: d < DAYS - 3 ? staff.tl : null, digitized_ts: d < DAYS - 3 ? at(day, 19) : null });
  }
  await c.query("update animal_groups g set head_count = greatest(0, head_count) where farm_id=$1", [FARM]);
  console.log(`simulated ${DAYS} days, ~${counts} core records (+ moves/sensor/gate/checklist)`);
  await c.end();
}
main().catch((e) => { console.error(e); process.exit(1); });
