-- 0020 · TỔ CHỨC: phòng ban · chức năng nhiệm vụ · quy trình A–Z · đầu vào/đầu ra giữa phòng ban · chủ đề event bus (dữ liệu chạy thẳng, không phải đi hỏi)
create table if not exists departments(code text primary key, org_id text default 'ITRAN', name text not null, short text, parent_code text, level int default 1, block text, -- DIEU_HANH|SAN_XUAT|CHUOI_CUNG_UNG|KINH_DOANH|HO_TRO|CHIEN_LUOC
  mission text, functions text[] default '{}', head_role text, roles text[] default '{}', kpis text[] default '{}', records text[] default '{}', dashboards text[] default '{}', modules text[] default '{}', per_farm bool default true, position int default 0, active bool default true);
create table if not exists processes(code text primary key, dept_code text references departments, name text not null, kind text, -- CORE|SUPPORT|MANAGEMENT
  trigger_text text, inputs jsonb default '[]'::jsonb, -- [{from:dept, what, table/topic}]
  outputs jsonb default '[]'::jsonb, -- [{to:dept, what, table/topic}]
  sla text, owner_role text, kpi text, tables text[] default '{}', topics text[] default '{}', forms text[] default '{}', sop_code text, position int default 0, active bool default true);
create table if not exists process_steps(id serial primary key, process_code text references processes, step_no int not null, name text not null, actor_role text, dept_code text, action text, -- mô tả làm gì
  system_where text, -- màn hình/API/bảng
  raci jsonb default '{}'::jsonb, control text, output text, unique(process_code, step_no));
create table if not exists dept_links(id serial primary key, from_dept text references departments, to_dept text references departments, what text not null, via text, -- table/topic/view/export
  frequency text, realtime bool default true, unique(from_dept, to_dept, what));
create table if not exists event_topics(topic text primary key, producer_dept text, consumer_depts text[] default '{}', description text, payload jsonb default '{}'::jsonb, source_table text, wired bool default true);
do $$ declare t text; begin foreach t in array array['departments','processes','process_steps','dept_links','event_topics'] loop
  execute format('alter table %I enable row level security', t); execute format('drop policy if exists p_all on %I', t); execute format('create policy p_all on %I for all using (true) with check (app_role() in (''owner'',''director'',''it_engineer''))', t); execute format('grant select, insert, update on %I to app_user', t); end loop;
  grant usage, select on all sequences in schema public to app_user; end $$;
do $$ declare t text; begin foreach t in array array['departments','processes','process_steps','dept_links','event_topics'] loop
  execute format('drop trigger if exists audit_%1$s on %1$s; create trigger audit_%1$s after insert or update or delete on %1$s for each row execute function itran_audit()', t); end loop; end $$;

-- ===== PHÒNG BAN (16) =====
insert into departments(code,name,short,parent_code,level,block,mission,functions,head_role,roles,kpis,records,dashboards,modules,per_farm,position) values
('HDQT','Hội đồng quản trị / Chủ đầu tư','HĐQT',null,0,'DIEU_HANH','Định hướng chiến lược, phê duyệt đầu tư – mở trại – XNK, giám sát rủi ro','{Chiến lược & vốn,Phê duyệt đầu tư >50tr,Bổ nhiệm GĐ trại,Giám sát 3 lớp,Nhân rộng/nhượng quyền}','owner','{owner}','{ROI,EBITDA công ty,Số trại vận hành,Cảnh báo ĐỎ mở}','{HS-AUDIT,HS-PHAP-LY}','{/hq,/hq?tab=cty,/ke-toan}','{core}',false,1),
('BGD','Ban Giám đốc điều hành (công ty mẹ)','BGĐ','HDQT',1,'DIEU_HANH','Điều hành chuỗi trại, cân đối kế hoạch – nguồn lực – dòng tiền, ra quyết định vận hành liên trại','{Kế hoạch năm/quý,Điều phối liên trại,Duyệt chi 20–50tr,Phê duyệt kế hoạch mùa vụ,Quản trị rủi ro/sự cố}','director','{director}','{P&L phân hệ,Chi phí/kg sản phẩm,Đúng KH mùa vụ %,Tỷ lệ việc quá hạn}','{HS-KE-TOAN,HS-AUDIT}','{/gd,/ke-hoach,/so-lieu}','{core}',false,2),
('GDT','Giám đốc trại (từng trại)','GĐ trại','BGD',2,'DIEU_HANH','Chịu trách nhiệm toàn diện 1 trại: sản lượng – chi phí – an toàn – tuân thủ','{Vận hành hàng ngày,Duyệt chi <20tr,Giao ca,Phê duyệt điều chỉnh kho,Quan hệ địa phương}','director','{director,team_lead}','{Sản lượng vs KH,Chi phí/ngày,Cảnh báo chưa xử lý,KPI nhân sự}','{HS-NHAN-SU,HS-PHAP-LY}','{/gd,/ca,/canh-bao}','{core}',true,3),
('KTCN','Phòng Kỹ thuật – Công nghệ chăn nuôi & thú y','KT chăn nuôi','GDT',2,'SAN_XUAT','Sức khỏe – sinh sản – tăng trọng đàn; ngưng thuốc; định danh cá thể; SOP kỹ thuật','{Sổ đàn & định danh,Sinh sản (phối/khám/đẻ),Thú y – vaccine – điều trị,Khẩu phần & TMR (cùng D5),Cách ly & an toàn sinh học,SOP kỹ thuật}','tech_head','{tech_head,team_lead,worker}','{Đậu thai %,ADG,Chết %,Sai số TMR,Ngưng thuốc vi phạm=0}','{HS-SO-DAN,HS-THU-Y,HS-THUC-AN}','{/ktt,/thu-y,/dan,/suc-khoe}','{bo,ga,de,ras}',true,4),
('TT','Phòng Trồng trọt – Sinh khối – Vườn','Trồng trọt','GDT',2,'SAN_XUAT','Đủ sinh khối (cỏ/bắp/rơm) và cây trồng hữu cơ; hồ sơ canh tác đạt VietGAP/hữu cơ/GlobalG.A.P.','{Kế hoạch mùa vụ theo K,Nhật ký canh tác,Phân bón/BVTV & PHI,Tưới – đất – nước,Thu hoạch & cân,Chứng nhận}','tech_head','{tech_head,team_lead,worker}','{Ngày-tồn ủ chua,Năng suất kg/ha,PHI vi phạm=0,Chi phí/kg sinh khối}','{HS-CANH-TAC,HS-THU-HOACH,HS-DAT-NUOC}','{/canh-tac,/ke-hoach,/so-lieu}','{core}',true,5),
('SH','Phòng Sinh học tuần hoàn – Môi trường (khu D)','Sinh học','GDT',2,'SAN_XUAT','Biến chất thải thành tài nguyên: trùn – BSF – biogas – compost; tuân thủ môi trường','{Mẻ khu D,Biogas – điện – nhiệt,Compost/phân hữu cơ,Quan trắc nước thải,Giấy phép môi trường,Chỉ số tuần hoàn}','tech_head','{team_lead,worker}','{Tỷ lệ chất thải tái sử dụng %,kg phân hữu cơ,m3 biogas,Sự cố môi trường=0}','{HS-MOI-TRUONG}','{/so-lieu,/thiet-bi}','{trun}',true,6),
('D5','Xưởng thức ăn – Chế biến (D5 & sơ chế)','D5/Chế biến','GDT',2,'SAN_XUAT','Sản xuất TMR/thức ăn đúng công thức; sơ chế – chế biến sản phẩm đạt ATTP/HACCP','{Công thức & mẻ,QC nguyên liệu,HACCP/CCP,Kho lạnh & FEFO,Truy xuất lô,Đóng gói – tem GS1}','tech_head','{team_lead,worker}','{Sai số mẻ %,Giá thành/kg TA,CCP lệch=0,Tỷ lệ hao hụt}','{HS-THUC-AN,HS-ATTP,HS-TRUY-XUAT}','{/kho,/so-lieu,/truy-xuat}','{d5,cb}',true,7),
('CCU','Phòng Chuỗi cung ứng – Kho – Mua hàng','Kho & Mua','BGD',1,'CHUOI_CUNG_UNG','Đủ hàng đúng lúc, tồn kho tối ưu, nguồn ≤35%/NCC; nhập – xuất – kiểm kê minh bạch','{Kế hoạch nhu cầu (MRP),Mua hàng & PO,Đánh giá NCC,9 kho & FEFO,Kiểm kê – điều chỉnh,Vận tải – cổng – cân}','accountant','{accountant,worker,team_lead}','{Ngày-tồn,Hết hàng=0,Chênh kiểm kê %,Giá mua vs thị trường}','{HS-KHO}','{/kho,/ke-toan}','{core}',true,8),
('KDM','Phòng Kinh doanh – Marketing – CSKH','Kinh doanh','BGD',1,'KINH_DOANH','Bán hết sản lượng với giá tốt qua đa kênh; khách nhận nuôi; thương hiệu','{CRM & pipeline,Đơn hàng – HĐ – giá,POS cửa hàng,Online/Zalo,Khách nhận nuôi (portal),Khuyến mãi,Công nợ (cùng KT)}','director','{worker,team_lead,director}','{Doanh thu theo kênh,Biên lợi nhuận,Công nợ >30 ngày,Tỷ lệ chốt lead}','{HS-BAN-HANG,HS-NHAN-NUOI}','{/ban-hang,/so-lieu}','{kd,custody}',true,9),
('XNK','Phòng Xuất nhập khẩu – Thị trường quốc tế','XNK','KDM',2,'KINH_DOANH','Đưa sản phẩm ra thị trường quốc tế đúng chuẩn; nhập giống/vật tư/máy hợp pháp','{Hồ sơ thị trường & yêu cầu,HĐ ngoại – LC – incoterm,Chứng từ CO/Phyto/Health/Halal,Logistics – container,Hải quan – thuế,Thanh toán quốc tế & tỷ giá,Giấy phép nhập}','director','{director,accountant}','{Giá trị XK,Lô hàng đúng hạn %,Chứng từ lỗi=0,Landed cost}','{HS-XNK,HS-TRUY-XUAT}','{/quan-tri?t=trade_contracts}','{xnk}',false,10),
('DL','Phòng Du lịch – Lưu trú – Ẩm thực – Sự kiện','Du lịch','BGD',1,'KINH_DOANH','Trải nghiệm farm-to-table; lưu trú, tour, tiệc/MICE sinh lời và bán chéo sản phẩm trại','{Booking & phòng,Tour – trải nghiệm,Nhà hàng & menu,Tiệc/hội nghị,Folio – thanh toán,Khai báo lưu trú}','director','{worker,team_lead}','{Công suất phòng %,ADR/RevPAR,Doanh thu F&B,Đánh giá khách}','{HS-DU-LICH}','{/du-lich}','{resort}',true,11),
('TCKT','Phòng Tài chính – Kế toán','Kế toán','BGD',1,'HO_TRO','Số liệu tài chính tin được: P&L phân hệ, dòng tiền, thuế, kiểm toán; 2 chữ ký chi lớn','{Kế toán tổng hợp,Chi phí – giá vốn – CC,Công nợ – thu tiền,Ngân hàng & đối chiếu,Thuế – hóa đơn ĐT,Quỹ & ngân sách,Xuất báo cáo cơ quan}','accountant','{accountant}','{P&L đúng hạn,Đối chiếu ngân hàng 100%,Nợ quá hạn,Chi vượt ngân sách}','{HS-KE-TOAN,HS-KHO,HS-BAN-HANG}','{/ke-toan,/audit}','{core}',false,12),
('HCNS','Phòng Hành chính – Nhân sự – Đào tạo','Nhân sự','BGD',1,'HO_TRO','Đủ người đúng việc, KPI→lương công bằng, đào tạo SOP, an toàn lao động','{Tuyển – HĐLĐ,Chấm công – ca,KPI→lương lớp 2,Đào tạo & chứng chỉ SOP,Khám SK/ATTP,Kỷ luật – khen thưởng,Hành chính – pháp lý}','director','{director,accountant}','{KPI TB,Nghỉ việc %,Chứng chỉ SOP đủ %,Tai nạn=0}','{HS-NHAN-SU}','{/nhan-su}','{core}',false,13),
('CNTB','Phòng Công nghệ – Thiết bị – IoT – Dữ liệu','Công nghệ','BGD',1,'HO_TRO','Máy chạy, cảm biến đúng, dữ liệu sạch, hệ thống an toàn; hiệu chuẩn cân','{Bảo trì máy & giờ máy,Hiệu chuẩn cân/cảm biến,IoT/MQTT/camera,Hệ thống ITRAN AGRI,Tích hợp (Zalo/Bank/GIS),Sao lưu & bảo mật}','it_engineer','{it_engineer}','{Uptime thiết bị,Cảm biến off,Job đêm OK %,Hiệu chuẩn đúng hạn}','{HS-THIET-BI}','{/thiet-bi,/quan-tri,/canh-bao}','{core}',false,14),
('QA','Phòng Chất lượng – Tuân thủ – Chứng nhận (QA/QC)','QA','BGD',1,'HO_TRO','Đạt & giữ chứng nhận (VietGAP/hữu cơ/GlobalG.A.P./ISO 22000/HACCP/Halal); audit nội bộ; truy xuất','{Hệ thống tài liệu SOP,Audit nội bộ,Đối soát RC1–RC16,Chuẩn bị đánh giá ngoài,Xử lý không phù hợp,Truy xuất & thu hồi}','auditor','{auditor,tech_head}','{Điểm audit,NC mở,Đối soát lệch %,Chứng nhận còn hạn}','{HS-ATTP,HS-TRUY-XUAT,HS-AUDIT}','{/audit,/doi-soat,/sop}','{core}',false,15),
('RD','Phòng R&D – Đổi mới – Tri thức','R&D','BGD',1,'CHIEN_LUOC','Thử nghiệm giống/thức ăn/quy trình có đối chứng; tri thức hóa; chuẩn hóa để nhân rộng','{Đề tài & thử nghiệm,Nhánh đối chứng,Mẫu lab,Tri thức & SOP mới,Chuyển giao cho trại,Hợp tác viện/trường}','tech_head','{tech_head}','{Đề tài kết thúc,Cải thiện chỉ số %,SOP mới ban hành}','{HS-RD,HS-DAT-NUOC}','{/quan-tri?t=rd_trials}','{rnd}',false,16),
('MR','Ban Phát triển dự án – Nhân rộng – Nhượng quyền','Nhân rộng','HDQT',1,'CHIEN_LUOC','Khảo sát – thiết kế – chuyển giao trại mới/franchise; gói mẫu theo dải diện tích','{Khảo sát đất – nước – pháp lý,Thế số Lớp B,Thiết kế & dự toán,Khai báo trại (create_farm),Checklist chuyển giao,Theo dõi sau go-live}','owner','{owner,director}','{Trại mới/năm,Đúng tiến độ %,Chi phí/ha,Đạt KPI sau 6 tháng}','{HS-PHAP-LY}','{/hq?tab=cty}','{franchise}',false,17)
on conflict (code) do update set name=excluded.name, mission=excluded.mission, functions=excluded.functions, kpis=excluded.kpis, records=excluded.records, dashboards=excluded.dashboards, parent_code=excluded.parent_code, block=excluded.block, position=excluded.position;

-- ===== QUY TRÌNH A–Z (theo phòng ban) — inputs/outputs = mối liên hệ; tables/topics = dữ liệu chạy thẳng =====
insert into processes(code,dept_code,name,kind,trigger_text,inputs,outputs,sla,owner_role,kpi,tables,topics,forms,position) values
-- KTCN
('P-KT-01','KTCN','Nhập đàn & định danh cá thể (A–Z)','CORE','Có lô nhập / bê sinh','[{"from":"CCU","what":"PO giống, kiểm dịch","via":"purchase_orders"},{"from":"XNK","what":"Giấy phép nhập giống","via":"import_permits"}]','[{"to":"CCU","what":"Sổ đàn K8 tăng","via":"inventory_moves"},{"to":"TCKT","what":"Giá trị đàn","via":"v_herd_value"},{"to":"KDM","what":"Cá thể sẵn sàng nhận nuôi","via":"animals"}]','Trong ngày','tech_head','100% có mã trong 24h','{intake_lots,animals,animal_tags,animal_events}','{animal.intake}','{A5 nhập đàn}',1),
('P-KT-02','KTCN','Sinh sản: động dục → phối → khám thai → đẻ → cai sữa','CORE','Phát hiện động dục / lịch','[{"from":"KTCN","what":"Lịch khám","via":"tasks"}]','[{"to":"GDT","what":"KPI đậu thai","via":"v_kpi_conception"},{"to":"KTCN","what":"Bê mới (tag_pending)","via":"animals"}]','Phối ≤12h sau động dục; khám 30–45 ngày','tech_head','Đậu thai ≥55%','{animal_events,tasks,vaccine_schedules}','{task.created}','{A2 sinh sản}',2),
('P-KT-03','KTCN','Thú y: bệnh → điều trị → ngưng thuốc → xuất bán','CORE','Phát hiện bệnh','[{"from":"CCU","what":"Thuốc K1 theo lô","via":"inventory_moves"}]','[{"to":"KDM","what":"Chặn bán khi chưa hết ngưng thuốc","via":"withdrawal trigger"},{"to":"QA","what":"Sổ thuốc thú y","via":"medicine-book"}]','Ghi trong ca','tech_head','Vi phạm ngưng thuốc = 0','{animal_events,treatment_protocols}','{alert.raised}','{A2 điều trị}',3),
('P-KT-04','KTCN','Cân định kỳ & phân loại vỗ béo','CORE','Lịch cân 30 ngày','[{"from":"CNTB","what":"Cân hiệu chuẩn (BLE)","via":"calibrations"}]','[{"to":"KDM","what":"Bò đủ trọng lượng bán","via":"v_animals_attention"},{"to":"D5","what":"Điều chỉnh khẩu phần","via":"feed_plans"}]','Tháng','team_lead','ADG ≥0,8 kg','{animal_events,weigh_tickets}','{}','{A2 cân}',4),
-- TT
('P-TT-01','TT','Kế hoạch mùa vụ theo K (đàn → sinh khối → ô thửa)','MANAGEMENT','Đầu năm / thay đổi đàn','[{"from":"KTCN","what":"Đàn dự kiến","via":"herd_daily"},{"from":"BGD","what":"Ngân sách","via":"season_plans"}]','[{"to":"CCU","what":"Nhu cầu giống/phân","via":"purchase_orders"},{"to":"HCNS","what":"Nhu cầu nhân công","via":"tasks"}]','Trước vụ 30 ngày','tech_head','Ngày-tồn ủ chua ≥60','{season_plans,crop_seasons,plots}','{}','{}',1),
('P-TT-02','TT','Hồ sơ canh tác A–Z: gieo → chăm sóc → phân/BVTV (PHI) → thu hoạch → nhập kho','CORE','Mở mùa vụ','[{"from":"CCU","what":"Giống, phân, BVTV theo lô","via":"inventory_moves"},{"from":"CNTB","what":"Cảm biến đất/thời tiết","via":"sensor_reads"}]','[{"to":"CCU","what":"Nhập K2/K3 sinh khối","via":"inventory_moves"},{"to":"QA","what":"Nhật ký sản xuất VietGAP/hữu cơ","via":"crop-dossier"},{"to":"XNK","what":"Chứng cứ vùng trồng/PHI","via":"crop-dossier"}]','Ghi cùng ngày','team_lead','PHI vi phạm = 0; năng suất vs KH','{crop_seasons,crop_logs,crop_inputs,harvests}','{harvest.done}','{A6 ruộng}',2),
('P-TT-03','TT','Đất – nước – môi trường canh tác','SUPPORT','Định kỳ quý / trước chứng nhận','[{"from":"RD","what":"Kết quả mẫu lab","via":"lab_samples"}]','[{"to":"QA","what":"Hồ sơ đất nước","via":"lab_samples"}]','Quý','tech_head','Mẫu đạt 100%','{lab_samples,sensor_reads}','{}','{}',3),
-- SH
('P-SH-01','SH','Chất thải → mẻ khu D (trùn/BSF/biogas/compost) → sản phẩm','CORE','Hàng ngày','[{"from":"KTCN","what":"Phân, chất độn","via":"batch_logs.inputs"},{"from":"D5","what":"Phụ phẩm chế biến","via":"batch_logs.inputs"}]','[{"to":"TT","what":"Phân hữu cơ ra ruộng","via":"inventory_moves"},{"to":"D5","what":"Đạm côn trùng vào TA","via":"inventory_moves"},{"to":"CNTB","what":"Biogas → điện","via":"sensor_reads"}]','Ca','team_lead','Tái sử dụng ≥90%','{batch_logs,inventory_moves}','{}','{A4 khu D}',1),
('P-SH-02','SH','Quan trắc & báo cáo môi trường','MANAGEMENT','Tháng / quý','[{"from":"CNTB","what":"Cảm biến nước thải","via":"sensor_reads"}]','[{"to":"QA","what":"Báo cáo giấy phép MT","via":"table:sensor_reads"},{"to":"HDQT","what":"Chỉ số tuần hoàn","via":"agg_daily"}]','Quý','tech_head','Sự cố = 0','{sensor_reads,incidents,documents}','{incident.created}','{}',2),
-- D5
('P-D5-01','D5','Mẻ TMR: kế hoạch → cân nguyên liệu → trộn → phát → sai số','CORE','2 bữa/ngày','[{"from":"KTCN","what":"Khẩu phần theo nhóm","via":"feed_plans"},{"from":"CCU","what":"Nguyên liệu K2/K3","via":"inventory_moves"}]','[{"to":"KTCN","what":"Thực ăn vs KH","via":"v_feed_plan_vs_actual"},{"to":"CCU","what":"Xuất K3/K4","via":"inventory_moves"},{"to":"TCKT","what":"Giá thành TA","via":"v_pl_cc_month"}]','Bữa','worker','Sai số ≤3%','{recipes,feed_plans,feed_logs,inventory_moves}','{}','{A1 TMR}',1),
('P-D5-02','D5','Chế biến & HACCP: nguyên liệu → CCP → đóng gói → tem → kho lạnh','CORE','Đơn hàng / lịch','[{"from":"KTCN","what":"Trứng/sữa/thịt (hết ngưng thuốc)","via":"inventory_moves"},{"from":"TT","what":"Rau/quả (hết PHI)","via":"harvests"}]','[{"to":"KDM","what":"SKU thành phẩm + QR","via":"lots"},{"to":"QA","what":"Hồ sơ HACCP","via":"checklist_runs"}]','Mẻ','team_lead','CCP lệch = 0','{batch_logs,checklist_runs,lots,inventory_moves,calibrations}','{}','{A7 chế biến}',2),
-- CCU
('P-CCU-01','CCU','Mua hàng A–Z: nhu cầu → PO → duyệt → nhận hàng → QC → nhập kho → thanh toán','CORE','Ngày-tồn < ngưỡng / kế hoạch','[{"from":"KTCN","what":"Nhu cầu thuốc/vật tư","via":"alerts"},{"from":"TT","what":"Giống/phân","via":"season_plans"},{"from":"D5","what":"Nguyên liệu TA","via":"v_days_of_stock"}]','[{"to":"TCKT","what":"Công nợ phải trả","via":"purchase_orders"},{"to":"D5","what":"Nguyên liệu sẵn","via":"inventory_moves"},{"to":"QA","what":"COA NCC","via":"documents"}]','PO ≤2 ngày','accountant','Hết hàng = 0; ≤35%/NCC','{purchase_orders,inventory_moves,partners,documents}','{alert.raised,po.created}','{A8 kho}',1),
('P-CCU-02','CCU','Kho: nhập – xuất – FEFO – kiểm kê – điều chỉnh có duyệt','CORE','Hàng ngày; kiểm kê tuần/tháng','[{"from":"*","what":"Mọi phiếu nhập/xuất","via":"inventory_moves"}]','[{"to":"TCKT","what":"Nhập xuất tồn","via":"stock-ledger"},{"to":"GDT","what":"Chênh lệch kiểm kê","via":"adjustments"},{"to":"*","what":"Cảnh báo ngày-tồn","via":"AL-STOCK-DAYS"}]','Ghi trong ca','worker','Chênh ≤1%','{inventory_moves,stocktakes,adjustments,lots}','{alert.raised}','{A8 kho}',2),
('P-CCU-03','CCU','Cổng – cân – vận chuyển (đầu vào/đầu ra vật lý)','SUPPORT','Xe đến/đi','[{"from":"KDM","what":"Đơn giao","via":"orders"},{"from":"CCU","what":"PO nhận","via":"purchase_orders"}]','[{"to":"QA","what":"Đối soát RC cân–kho","via":"weigh_tickets"}]','Ngay','worker','100% xe có phiếu cân','{gate_logs,weigh_tickets}','{}','{A10 cổng}',3),
-- KDM
('P-KD-01','KDM','CRM: lead → liên hệ → báo giá → đàm phán → HĐ/đơn','CORE','Có lead','[{"from":"DL","what":"Khách tham quan","via":"hosp_bookings"},{"from":"XNK","what":"Nhà nhập khẩu","via":"trade_partners"}]','[{"to":"KDM","what":"Đối tác/khách","via":"partners"},{"to":"TCKT","what":"Hạn mức tín dụng","via":"partners"}]','Phản hồi ≤24h','worker','Chốt ≥20%','{crm_leads,crm_activities,partners,contracts}','{}','{}',1),
('P-KD-02','KDM','Đơn hàng → xuất kho → giao → hóa đơn → thu tiền → công nợ','CORE','Đơn/HĐ','[{"from":"CCU","what":"Tồn sẵn bán","via":"stock"},{"from":"KTCN","what":"Ngưng thuốc/PHI đã qua","via":"triggers"},{"from":"TCKT","what":"Bảng giá","via":"price_list"}]','[{"to":"CCU","what":"Xuất K5/K6","via":"inventory_moves"},{"to":"TCKT","what":"Doanh thu, công nợ","via":"sales"},{"to":"QA","what":"Truy xuất lô đến khách","via":"epcis"}]','Giao đúng hẹn','worker','Đúng hẹn ≥95%','{orders,sales,inventory_moves,price_list}','{}','{A9 bán hàng}',2),
('P-KD-03','KDM','POS cửa hàng: mở ca → bán → khuyến mãi → chốt ca','CORE','Ca bán','[{"from":"CCU","what":"Tồn K5","via":"stock"},{"from":"KDM","what":"Khuyến mãi","via":"promotions"}]','[{"to":"TCKT","what":"Tiền mặt/chuyển khoản","via":"pos_shifts"},{"to":"TCKT","what":"Doanh thu POS","via":"sales"}]','Chốt cuối ca','worker','Chênh két = 0','{pos_shifts,pos_receipts,promotions,sales}','{}','{}',3),
('P-KD-04','KDM','Chăm sóc hộ / nhận nuôi: HĐ → gán cá thể → cập nhật/live → tin nhắn → hết hạn','CORE','Khách đăng ký','[{"from":"KTCN","what":"Cá thể & sự kiện","via":"animals,animal_events"}]','[{"to":"TCKT","what":"Doanh thu nhận nuôi","via":"sales"},{"to":"KTCN","what":"Yêu cầu khách","via":"customer_messages"}]','Cập nhật ≥1 lần/tuần','worker','Gia hạn ≥60%','{custody_contracts,customer_messages}','{customer.message}','{}',4),
-- XNK
('P-XNK-01','XNK','Xuất khẩu A–Z: thị trường → đàm phán → HĐ/LC → sản xuất theo spec → chứng từ → hải quan → giao → thanh toán','CORE','Đơn hàng quốc tế','[{"from":"KDM","what":"Lead nước ngoài","via":"crm_leads"},{"from":"QA","what":"Chứng nhận, truy xuất","via":"documents,epcis"},{"from":"TT","what":"Hồ sơ vùng trồng","via":"crop-dossier"},{"from":"D5","what":"Lô thành phẩm","via":"lots"}]','[{"to":"TCKT","what":"Phải thu ngoại tệ, tỷ giá","via":"intl_payments"},{"to":"CCU","what":"Xuất kho container","via":"inventory_moves"},{"to":"HDQT","what":"Doanh thu XK","via":"trade_contracts"}]','Chứng từ trước ETD 3 ngày','director','Chứng từ lỗi = 0','{market_profiles,trade_contracts,shipments,trade_documents,customs_declarations,intl_payments,landed_costs}','{}','{}',1),
('P-XNK-02','XNK','Nhập khẩu giống/vật tư/máy: giấy phép → HĐ → vận chuyển → kiểm dịch → thông quan → nhập kho','CORE','Nhu cầu nhập','[{"from":"KTCN","what":"Giống cần nhập","via":"rd_trials"},{"from":"CNTB","what":"Máy/cảm biến","via":"devices"}]','[{"to":"CCU","what":"Nhập kho + landed cost","via":"inventory_moves"},{"to":"KTCN","what":"Lô giống + cách ly","via":"intake_lots"}]','Theo lô','director','Thông quan đúng hạn','{import_permits,trade_contracts,shipments,customs_declarations,landed_costs}','{}','{}',2),
-- DL
('P-DL-01','DL','Lưu trú A–Z: booking → xác nhận → nhận phòng → folio → trả phòng → dọn → khai báo','CORE','Khách đặt','[{"from":"KDM","what":"Khách/đối tác","via":"partners"}]','[{"to":"HCNS","what":"Việc dọn phòng","via":"tasks"},{"to":"TCKT","what":"Doanh thu phòng","via":"sales"},{"to":"KDM","what":"Lead bán sản phẩm","via":"crm_leads"}]','Check-in ≤10 phút','worker','Công suất ≥50%','{hosp_bookings,hosp_rooms,hosp_folio,tasks}','{}','{}',1),
('P-DL-02','DL','Tiệc / hội nghị / MICE: báo giá → cọc → chuẩn bị (menu ↔ kho) → diễn ra → quyết toán','CORE','Yêu cầu tiệc','[{"from":"CCU","what":"Nguyên liệu farm-to-table","via":"inventory_moves"},{"from":"D5","what":"Thực phẩm chế biến","via":"lots"}]','[{"to":"CCU","what":"Xuất kho theo menu×pax","via":"inventory_moves"},{"to":"TCKT","what":"Doanh thu tiệc","via":"sales"}]','Báo giá ≤24h','team_lead','Biên F&B ≥35%','{hosp_events,hosp_menus,hosp_folio}','{}','{}',2),
('P-DL-03','DL','Tour – trải nghiệm: lịch → bán vé → hướng dẫn → an toàn sinh học → phản hồi','CORE','Lịch tour','[{"from":"KTCN","what":"Khu được phép vào (ATSH)","via":"locations"}]','[{"to":"KDM","what":"Bán chéo sản phẩm","via":"pos_receipts"},{"to":"TCKT","what":"Doanh thu tour","via":"sales"}]','Ngày','worker','Đánh giá ≥4,5/5','{hosp_tours,hosp_tour_bookings,hosp_folio}','{}','{}',3),
-- TCKT
('P-TC-01','TCKT','Chi tiêu: đề nghị → duyệt (2 chữ ký >20tr, báo chủ >50tr) → chi → hạch toán','CORE','Đề nghị chi','[{"from":"*","what":"Đề nghị chi","via":"expense_requests"}]','[{"to":"HDQT","what":"Chi lớn","via":"expense.approved.big"},{"to":"TCKT","what":"Sổ chi","via":"expense_requests"}]','≤2 ngày','accountant','Chi vượt NS = 0','{expense_requests,funds}','{expense.approved.big}','{}',1),
('P-TC-02','TCKT','Đóng sổ tháng: đối chiếu ngân hàng → giá vốn → P&L phân hệ → khóa kỳ → báo cáo thuế','MANAGEMENT','Đầu tháng','[{"from":"CCU","what":"Nhập xuất tồn","via":"stock-ledger"},{"from":"KDM","what":"Doanh thu","via":"sales"},{"from":"HCNS","what":"Lương","via":"kpi_results"}]','[{"to":"BGD","what":"P&L phân hệ","via":"v_pl_cc_month"},{"to":"HDQT","what":"Báo cáo","via":"exports"},{"to":"Cơ quan thuế","what":"Bảng kê","via":"sales-tax"}]','Ngày 5','accountant','Đúng hạn 100%','{bank_statement_lines,cc_fixed_costs,period_locks,recon_results}','{}','{}',2),
-- HCNS
('P-HC-01','HCNS','Nhân sự A–Z: tuyển → HĐLĐ → đào tạo SOP → giao ca → KPI → lương → nghỉ việc','CORE','Nhu cầu','[{"from":"GDT","what":"Nhu cầu nhân lực","via":"tasks"},{"from":"*","what":"Bản ghi công việc","via":"events"}]','[{"to":"TCKT","what":"Bảng lương KPI","via":"v_staff_kpi_month"},{"to":"QA","what":"Chứng chỉ SOP/khám SK","via":"staff"}]','Tháng','director','KPI TB ≥80','{staff,kpi_results,shift_notes,checklist_runs}','{}','{}',1),
-- CNTB
('P-CN-01','CNTB','Thiết bị: lý lịch → giờ máy → bảo trì → hiệu chuẩn → sự cố','CORE','Giờ máy / lịch','[{"from":"TT","what":"Giờ máy ruộng","via":"crop_logs"},{"from":"D5","what":"Giờ máy trộn","via":"batch_logs"}]','[{"to":"CCU","what":"Phụ tùng cần mua","via":"purchase_orders"},{"to":"QA","what":"Hiệu chuẩn cân","via":"calibrations"}]','Theo chu kỳ','it_engineer','Đúng hạn 100%','{devices,calibrations,tasks}','{alert.raised}','{}',1),
('P-CN-02','CNTB','Dữ liệu & hệ thống: job đêm → đối soát → cảnh báo → sao lưu → tích hợp','SUPPORT','Hàng đêm','[{"from":"*","what":"Mọi sự kiện","via":"event_bus"}]','[{"to":"*","what":"Cảnh báo/thông báo","via":"notifications"},{"to":"QA","what":"Kết quả RC","via":"recon_results"}]','Đêm','it_engineer','Job OK ≥99%','{job_runs,event_bus,notifications,integrations,webhooks}','{*}','{}',2),
-- QA
('P-QA-01','QA','Chứng nhận A–Z: gap analysis → SOP → hồ sơ → audit nội bộ → đánh giá ngoài → duy trì','MANAGEMENT','Mục tiêu thị trường','[{"from":"TT","what":"Hồ sơ canh tác","via":"crop-dossier"},{"from":"KTCN","what":"Sổ đàn/thú y","via":"herd,medicine-book"},{"from":"D5","what":"HACCP","via":"checklist_runs"}]','[{"to":"KDM,XNK","what":"Chứng nhận để bán/xuất","via":"documents"}]','Theo lịch chứng nhận','auditor','Chứng nhận đạt','{documents,checklist_runs,audit_log}','{}','{}',1),
('P-QA-02','QA','Truy xuất & thu hồi: khiếu nại → truy lô → chặn xuất → thu hồi → nguyên nhân → khắc phục','CORE','Khiếu nại/sự cố','[{"from":"KDM","what":"Khiếu nại","via":"customer_messages"}]','[{"to":"CCU","what":"Khóa lô","via":"lots.status"},{"to":"BGD","what":"Báo cáo sự cố","via":"incidents"}]','Truy lô ≤4h','auditor','Truy lô 100%','{lots,epcis,incidents}','{incident.created}','{}',2),
-- RD
('P-RD-01','RD','Thử nghiệm A–Z: đề xuất → duyệt → nhánh đối chứng → quan sát → mẫu lab → kết luận → SOP/nhân rộng','CORE','Ý tưởng/vấn đề','[{"from":"KTCN,TT,SH,D5","what":"Vấn đề & dữ liệu vận hành","via":"agg_daily"}]','[{"to":"KTCN,TT","what":"SOP/định mức mới","via":"sops,norms"},{"to":"MR","what":"Chuẩn cho gói mẫu","via":"knowledge_articles"}]','Theo đề tài','tech_head','Cải thiện ≥10%','{rd_trials,rd_trial_arms,rd_observations,lab_samples,knowledge_articles}','{}','{}',1),
-- MR
('P-MR-01','MR','Mở trại mới A–Z: khảo sát → thế số Lớp B → pháp lý → thiết kế → khai báo trại → tuyển – đào tạo → go-live → theo dõi','MANAGEMENT','Quyết định HĐQT','[{"from":"RD","what":"Chuẩn/gói mẫu","via":"franchise_packages"},{"from":"TCKT","what":"Ngân sách","via":"funds"}]','[{"to":"*","what":"Trại mới với 9 kho/12 CC/khu","via":"create_farm"},{"to":"HCNS","what":"Nhân sự trại","via":"staff"}]','6–9 tháng','owner','Đúng tiến độ','{franchise_sites,transfer_checklists,farms,facilities}','{farm.created}','{}',1)
on conflict (code) do update set name=excluded.name, inputs=excluded.inputs, outputs=excluded.outputs, tables=excluded.tables, topics=excluded.topics, kpi=excluded.kpi, sla=excluded.sla;

-- Bước quy trình mẫu chi tiết cho các quy trình lõi (mỗi bước: ai, làm gì, ở đâu trong hệ thống, kiểm soát)
insert into process_steps(process_code,step_no,name,actor_role,dept_code,action,system_where,control,output) values
('P-TT-02',1,'Mở mùa vụ','tech_head','TT','Tạo crop_season: ô, giống, nguồn giống, ngày gieo, chứng nhận','/canh-tac › + Mùa vụ','Ô phải có area_ha; giống có nguồn','crop_seasons'),
('P-TT-02',2,'Làm đất – gieo','worker','TT','Ghi crop_logs GIEO/LAM_DAT (kg giống, giờ máy)','/ca A6 ruộng (3 chạm)','Xuất kho giống K2 khớp','crop_logs,inventory_moves'),
('P-TT-02',3,'Bón phân / phun BVTV','worker','TT','Ghi crop_inputs: SKU, liều/ha, PHI → safe_after tự tính','/canh-tac › Vật tư đầu vào','Chỉ SKU được phép (hữu cơ); PPE','crop_inputs'),
('P-TT-02',4,'Tưới – chăm sóc – theo dõi sâu bệnh','worker','TT','crop_logs TUOI/CHAM_SOC; ảnh','/ca A6','Cảm biến ẩm đất (nếu có)','crop_logs'),
('P-TT-02',5,'Thu hoạch','team_lead','TT','Ghi harvests: kg, ẩm độ, phẩm cấp, phiếu cân, kho đích; hệ thống CHẶN nếu chưa hết PHI','/canh-tac › Thu hoạch','Trigger PHI; phiếu cân','harvests,weigh_tickets'),
('P-TT-02',6,'Nhập kho / bán trực tiếp','worker','CCU','inventory_moves NHAP_SX vào K2/K3/K5 với harvest_lot','/kho › Nhập','Đối soát RC cân–kho','inventory_moves,lots'),
('P-TT-02',7,'Đóng mùa vụ & xuất hồ sơ','tech_head','TT','Cập nhật actual_yield, status=KET_THUC; xuất Nhật ký sản xuất','/canh-tac › Xuất hồ sơ','QA rà soát','crop-dossier export'),
('P-KD-02',1,'Tạo đơn/HĐ','worker','KDM','create_order với SKU, giá theo price_list, kênh','/ban-hang › Đơn','Hạn mức tín dụng','orders'),
('P-KD-02',2,'Chuẩn bị hàng','worker','CCU','Chọn lô FEFO; kiểm ngưng thuốc/PHI','/kho','Trigger withdrawal/PHI','lots'),
('P-KD-02',3,'Xuất kho – giao','worker','CCU','inventory_moves XUAT_BAN + gate_logs + phiếu cân','/kho, /ca A10','Phiếu cân','inventory_moves,gate_logs'),
('P-KD-02',4,'Ghi bán – hóa đơn','worker','KDM','sales (amount, payment, paid, invoice_no)','/ca A9 bán hàng','Idempotent client_ref','sales'),
('P-KD-02',5,'Thu tiền – công nợ','accountant','TCKT','Đối chiếu ngân hàng; cập nhật paid','/ke-toan › Ngân hàng','RC10','bank_statement_lines'),
('P-DL-01',1,'Nhận booking','worker','DL','Tạo hosp_bookings (khách, ngày, phòng, giá, kênh, cọc)','/du-lich › Booking','Kiểm trùng phòng','hosp_bookings'),
('P-DL-01',2,'Nhận phòng','worker','DL','status=DA_NHAN; folio PHONG; khai báo lưu trú','/du-lich','CCCD/hộ chiếu','hosp_folio'),
('P-DL-01',3,'Dịch vụ trong kỳ','worker','DL','folio AN_UONG/DICH_VU/TOUR; xuất kho theo menu','/du-lich › Folio','Xuất kho khớp','hosp_folio,inventory_moves'),
('P-DL-01',4,'Trả phòng – thanh toán','worker','DL','folio THANH_TOAN → sales kênh RESORT; status=DA_TRA → việc dọn phòng tự sinh','/du-lich','Trigger checkout','sales,tasks'),
('P-XNK-01',1,'Hồ sơ thị trường','director','XNK','market_profiles: yêu cầu chứng nhận, dư lượng, nhãn, thuế','/quan-tri?t=market_profiles','QA xác nhận đáp ứng','market_profiles'),
('P-XNK-01',2,'HĐ ngoại – LC','director','XNK','trade_contracts: incoterm, tiền tệ, tỷ giá, điều khoản, dòng hàng','/quan-tri?t=trade_contracts','2 chữ ký','trade_contracts'),
('P-XNK-01',3,'Sản xuất theo spec','tech_head','D5','Lô thành phẩm gắn contract; QC; tem GS1','/kho, /truy-xuat','COA','lots'),
('P-XNK-01',4,'Chứng từ','director','XNK','trade_documents: Invoice, PL, CO, Phyto/Health, Halal, BL, bảo hiểm','/quan-tri?t=trade_documents','Checklist đủ trước ETD-3','trade_documents'),
('P-XNK-01',5,'Đóng hàng – hải quan – vận chuyển','worker','CCU','shipments + inventory_moves XUAT_KHAU + customs_declarations','/quan-tri?t=shipments','Phiếu cân/container','shipments,customs_declarations'),
('P-XNK-01',6,'Thanh toán – landed cost','accountant','TCKT','intl_payments (TT/LC), fx_rates, landed_costs','/quan-tri?t=intl_payments','Đối chiếu ngân hàng','intl_payments,landed_costs')
on conflict (process_code, step_no) do update set name=excluded.name, action=excluded.action, system_where=excluded.system_where, control=excluded.control, output=excluded.output;

-- Ma trận liên hệ đầu vào/đầu ra (sinh từ processes.inputs/outputs) — view để vẽ
create or replace view v_dept_io as
select p.dept_code as to_dept, i->>'from' as from_dept, i->>'what' as what, i->>'via' as via, p.code as process_code, 'IN' as dir from processes p, jsonb_array_elements(p.inputs) i
union all
select o->>'to' as to_dept, p.dept_code as from_dept, o->>'what' as what, o->>'via' as via, p.code, 'OUT' from processes p, jsonb_array_elements(p.outputs) o;
grant select on v_dept_io to app_user;

-- Chủ đề event bus (đã nối / sẽ nối) — producer → consumers
insert into event_topics(topic,producer_dept,consumer_depts,description,source_table,wired) values
('alert.raised','CNTB','{KTCN,TT,CCU,GDT,BGD,HDQT}','Mọi cảnh báo (luật SQL + luật cấu hình) → hộp thư người/nhóm nhận theo luật; ĐỎ luôn báo GĐ & chủ','alerts',true),
('task.created','CNTB','{KTCN,TT,D5,CCU,DL}','Việc KHẨN/CAO mới → người được giao / vai gợi ý','tasks',true),
('incident.created','GDT','{BGD,QA,HDQT}','Sự cố mới → KTT/GĐ; CAO/NGHIÊM TRỌNG báo chủ','incidents',true),
('expense.approved.big','TCKT','{HDQT}','Chi >50tr đã duyệt → chủ','expense_requests',true),
('farm.created','MR','{HDQT,BGD,HCNS}','Trại mới khai báo','farms',true),
('customer.message','KDM','{KTCN,GDT}','Tin nhắn khách nhận nuôi','customer_messages',true),
('master.changed','*','{HDQT,CNTB}','Thêm/sửa/gỡ danh mục (audit) → admin','audit_log',true),
('import.done','*','{HDQT,CNTB,BGD}','Nhập CSV xong (ok/lỗi)','import_batches',true),
('animal.intake','KTCN','{CCU,TCKT,KDM}','Lô nhập đàn mới → sổ đàn K8, giá trị đàn, cá thể sẵn sàng nhận nuôi','intake_lots',false),
('harvest.done','TT','{CCU,D5,KDM,QA}','Thu hoạch xong → nhập kho, kế hoạch chế biến/bán, hồ sơ','harvests',false),
('po.created','CCU','{TCKT,GDT}','PO mới → duyệt/công nợ','purchase_orders',false),
('order.created','KDM','{CCU,D5,TCKT}','Đơn bán mới → chuẩn bị hàng, sản xuất, công nợ','orders',false),
('booking.created','DL','{CCU,D5,HCNS}','Booking/tiệc mới → chuẩn bị F&B, nhân sự','hosp_bookings',false),
('shipment.status','XNK','{CCU,TCKT,KDM}','Lô hàng XNK đổi trạng thái','shipments',false),
('lot.blocked','QA','{KDM,CCU,D5}','Lô bị khóa (thu hồi/không phù hợp) → chặn bán/xuất','lots',false),
('period.locked','TCKT','{*}','Khóa kỳ kế toán → chặn ghi lùi','period_locks',false)
on conflict (topic) do update set consumer_depts=excluded.consumer_depts, description=excluded.description, wired=excluded.wired;
-- Nối thêm trigger publish cho các topic đã liệt kê (dữ liệu chạy thẳng giữa phòng ban)
create or replace function itran_generic_publish() returns trigger language plpgsql as $$
declare tp text := TG_ARGV[0]; pk text; begin
  pk := coalesce(to_jsonb(new)->>'id', to_jsonb(new)->>'code');
  perform publish_event(to_jsonb(new)->>'farm_id', tp, jsonb_build_object('table', TG_TABLE_NAME, 'id', pk, 'status', to_jsonb(new)->>'status', 'by', nullif(current_setting('app.staff_id', true),'')));
  return new; end $$;
do $$ begin
  if to_regclass('intake_lots') is not null then execute 'drop trigger if exists pub_intake on intake_lots; create trigger pub_intake after insert on intake_lots for each row execute function itran_generic_publish(''animal.intake'')'; end if;
  execute 'drop trigger if exists pub_harvest on harvests; create trigger pub_harvest after insert on harvests for each row execute function itran_generic_publish(''harvest.done'')';
  execute 'drop trigger if exists pub_po on purchase_orders; create trigger pub_po after insert on purchase_orders for each row execute function itran_generic_publish(''po.created'')';
  execute 'drop trigger if exists pub_order on orders; create trigger pub_order after insert on orders for each row execute function itran_generic_publish(''order.created'')';
  execute 'drop trigger if exists pub_booking on hosp_bookings; create trigger pub_booking after insert on hosp_bookings for each row execute function itran_generic_publish(''booking.created'')';
  execute 'drop trigger if exists pub_event on hosp_events; create trigger pub_event after insert on hosp_events for each row execute function itran_generic_publish(''booking.created'')';
  execute 'drop trigger if exists pub_ship on shipments; create trigger pub_ship after insert or update of status on shipments for each row execute function itran_generic_publish(''shipment.status'')';
  execute 'drop trigger if exists pub_lock on period_locks; create trigger pub_lock after insert on period_locks for each row execute function itran_generic_publish(''period.locked'')';
end $$;
update event_topics set wired=true where topic in ('animal.intake','harvest.done','po.created','order.created','booking.created','shipment.status','period.locked');
-- staff.dept chuẩn hóa về mã phòng ban
update staff set dept = case when role='owner' then 'HDQT' when role='director' and farm_id is null then 'BGD' when role='director' then 'GDT' when role='accountant' then 'TCKT' when role='it_engineer' then 'CNTB' when role='auditor' then 'QA'
  when position ilike 'A1%' or position ilike 'A7%' then 'D5' when position ilike 'A2%' or position ilike 'A3%' or position ilike 'A5%' then 'KTCN' when position ilike 'A4%' then 'SH' when position ilike 'A6%' then 'TT' when position ilike 'A8%' or position ilike 'A10%' then 'CCU' when position ilike 'A9%' then 'KDM' when position ilike 'A11%' then 'CNTB' else coalesce(dept,'KTCN') end
where dept is null or dept not in (select code from departments);
update staff set dept=case dept when 'SHTT' then 'SH' when 'SXCN' then 'D5' else 'KTCN' end where dept not in (select code from departments);
