-- 0022 · KIỂM KÊ QUY TRÌNH NGHIỆP VỤ theo ĐỐI TƯỢNG × VÒNG ĐỜI (rà soát toàn dự án) — coverage: DA_CO (bảng+UI+form) · MOT_PHAN (bảng có, UI qua Quản trị DL) · CHUA
alter table processes add column if not exists object_type text, add column if not exists coverage text default 'DA_CO', add column if not exists ui_path text, add column if not exists lifecycle_stage text;
update processes set object_type = case dept_code when 'KTCN' then 'VAT_NUOI' when 'TT' then 'CAY_TRONG' when 'SH' then 'SAN_XUAT' when 'D5' then 'SAN_XUAT' when 'CCU' then 'VAT_TU_KHO' when 'KDM' then 'KHACH_HANG' when 'XNK' then 'KHACH_HANG' when 'DL' then 'KHACH_HANG' when 'TCKT' then 'TAI_CHINH' when 'HCNS' then 'CON_NGUOI' when 'CNTB' then 'THIET_BI_DU_LIEU' when 'QA' then 'CHAT_LUONG' when 'RD' then 'TRI_THUC' when 'MR' then 'TRAI' else 'QUAN_TRI' end where object_type is null;
update processes set ui_path = case code when 'P-KT-01' then '/dan' when 'P-KT-02' then '/thu-y' when 'P-KT-03' then '/thu-y' when 'P-KT-04' then '/dan' when 'P-TT-01' then '/ke-hoach' when 'P-TT-02' then '/canh-tac' when 'P-TT-03' then '/quan-tri?t=lab_samples' when 'P-SH-01' then '/ca' when 'P-SH-02' then '/so-lieu' when 'P-D5-01' then '/ke-hoach' when 'P-D5-02' then '/kho' when 'P-CCU-01' then '/ke-toan' when 'P-CCU-02' then '/kho' when 'P-CCU-03' then '/ca' when 'P-KD-01' then '/ban-hang?tab=crm' when 'P-KD-02' then '/ban-hang' when 'P-KD-03' then '/ban-hang?tab=pos' when 'P-KD-04' then '/ban-hang?tab=nhan-nuoi' when 'P-XNK-01' then '/quan-tri?t=trade_contracts' when 'P-XNK-02' then '/quan-tri?t=import_permits' when 'P-DL-01' then '/du-lich' when 'P-DL-02' then '/du-lich?tab=tiec' when 'P-DL-03' then '/du-lich?tab=tour' when 'P-TC-01' then '/ke-toan' when 'P-TC-02' then '/ke-toan' when 'P-HC-01' then '/nhan-su' when 'P-CN-01' then '/thiet-bi' when 'P-CN-02' then '/canh-bao' when 'P-QA-01' then '/audit' when 'P-QA-02' then '/truy-xuat' when 'P-RD-01' then '/quan-tri?t=rd_trials' when 'P-MR-01' then '/hq?tab=cty' end where ui_path is null;
update processes set coverage='MOT_PHAN' where code in ('P-TT-03','P-XNK-01','P-XNK-02','P-RD-01','P-SH-02','P-QA-01');
insert into processes(code,dept_code,name,kind,object_type,lifecycle_stage,trigger_text,inputs,outputs,sla,owner_role,kpi,tables,ui_path,coverage,position) values
-- VẬT NUÔI theo vòng đời (bò/dê cá thể · gà đàn · thủy sản · côn trùng)
('P-VN-01','KTCN','Chọn giống – lập kế hoạch đàn (cơ cấu lớp: bê/tơ/cái SS/vỗ béo/đực)','MANAGEMENT','VAT_NUOI','KE_HOACH','Đầu năm / mở trại','[{"from":"BGD","what":"Mục tiêu đàn","via":"season_plans"}]','[{"to":"CCU","what":"Nhu cầu mua giống","via":"purchase_orders"}]','Năm','tech_head','Đúng cơ cấu đàn','{animal_classes,season_plans,herd_daily}','/ke-hoach','DA_CO',10),
('P-VN-02','KTCN','Cách ly nhập đàn 21 ngày → nhập chính thức','CORE','VAT_NUOI','NHAP','Lô nhập về','[{"from":"CCU","what":"Lô nhập + kiểm dịch","via":"intake_lots"}]','[{"to":"KTCN","what":"Đàn chính thức","via":"animal_events CACH_LY_RA"}]','21 ngày','team_lead','0 dịch xâm nhập','{intake_lots,animal_events,tasks}','/dan','DA_CO',11),
('P-VN-03','KTCN','Dinh dưỡng theo lớp: định mức → khẩu phần → phát ăn → theo dõi ăn thừa','CORE','VAT_NUOI','NUOI','Hàng ngày','[{"from":"D5","what":"TMR/thức ăn","via":"feed_logs"}]','[{"to":"D5","what":"Điều chỉnh công thức","via":"feed_plans"}]','Bữa','worker','Sai lệch ≤5% KH','{norms,feed_plans,feed_logs}','/ke-hoach','DA_CO',12),
('P-VN-04','KTCN','Di chuyển – phân đàn – nhập/xuất chuồng (all-in/all-out cho gà)','CORE','VAT_NUOI','NUOI','Theo giai đoạn','[]','[{"to":"CCU","what":"Sổ đàn K8 theo vị trí","via":"animal_events CHUYEN"}]','Ngày','team_lead','Vị trí đúng 100%','{animal_events,animal_groups,locations}','/dan','DA_CO',13),
('P-VN-05','KTCN','An toàn sinh học: cổng – sát trùng – khách – xe – trang phục','CORE','VAT_NUOI','NUOI','Hàng ngày','[{"from":"CCU","what":"Xe qua cổng","via":"gate_logs"},{"from":"DL","what":"Khách tham quan","via":"hosp_tours"}]','[{"to":"QA","what":"Checklist ATSH","via":"checklist_runs"}]','Ca','worker','Vi phạm = 0','{gate_logs,checklist_runs}','/ca','DA_CO',14),
('P-VN-06','KTCN','Vaccine theo lịch (kế hoạch → nhắc → tiêm → ghi lô vaccine)','CORE','VAT_NUOI','NUOI','Lịch vaccine','[{"from":"CCU","what":"Vaccine K1 (lạnh)","via":"inventory_moves"}]','[{"to":"QA","what":"Sổ vaccine","via":"medicine-book"}]','Đúng ngày','worker','Đúng lịch ≥98%','{vaccine_schedules,tasks,animal_events}','/thu-y','DA_CO',15),
('P-VN-07','KTCN','Chết/loại thải/xuất bán cá thể (nguyên nhân → xử lý xác → giảm sổ đàn)','CORE','VAT_NUOI','XUAT','Sự kiện','[]','[{"to":"CCU","what":"Sổ đàn K8 giảm","via":"trigger"},{"to":"TCKT","what":"Giảm giá trị đàn","via":"v_herd_value"},{"to":"SH","what":"Xác → xử lý (compost/biogas)","via":"batch_logs"}]','Trong ngày','team_lead','Chết ≤3%/năm','{animal_events,herd_daily}','/dan','DA_CO',16),
('P-VN-08','KTCN','Gia cầm: úm → hậu bị → đẻ (thu trứng, đếm băng chuyền) → loại đàn','CORE','VAT_NUOI','NUOI','Theo lứa','[{"from":"CCU","what":"Con giống, cám","via":"inventory_moves"}]','[{"to":"CCU","what":"Trứng nhập K5","via":"inventory_moves"},{"to":"KDM","what":"Trứng bán","via":"sales"}]','Ngày','worker','Tỷ lệ đẻ ≥85%','{animal_groups,animal_events,inventory_moves}','/dan','DA_CO',17),
('P-VN-09','KTCN','Thủy sản RAS/ao: thả giống → chất lượng nước (DO/pH/NH3) → cho ăn → thu tỉa → thu toàn bộ','CORE','VAT_NUOI','NUOI','Theo vụ','[{"from":"CNTB","what":"Cảm biến nước","via":"sensor_reads"}]','[{"to":"KDM","what":"Cá thương phẩm","via":"sales"}]','Ngày','worker','FCR, sống ≥85%','{animal_groups,animal_events,sensor_reads,feed_logs}','/dan','DA_CO',18),
('P-VN-10','KTCN','Sữa (bò/dê): vắt → lọc → lạnh → bán/chế biến (nếu mở)','CORE','VAT_NUOI','XUAT','Ngày','[]','[{"to":"D5","what":"Sữa tươi → chế biến","via":"inventory_moves"}]','2 lần/ngày','worker','SCC, kg/con','{animal_events,inventory_moves}','/ca','MOT_PHAN',19),
-- CÂY TRỒNG theo nhóm/vòng đời
('P-CT-01','TT','Quy hoạch đất – luân canh – phân ô (tầng cao trình T1–T3, ngập)','MANAGEMENT','CAY_TRONG','KE_HOACH','Đầu năm','[{"from":"MR","what":"Bản đồ trại","via":"plots.geom"}]','[{"to":"TT","what":"Kế hoạch ô–vụ","via":"crop_seasons"}]','Năm','tech_head','Đất sử dụng ≥90%','{plots,crop_seasons,crops}','/canh-tac','DA_CO',10),
('P-CT-02','TT','Giống & vườn ươm: mua/nhập giống → kiểm tra → ươm → trồng','CORE','CAY_TRONG','GIONG','Trước vụ','[{"from":"CCU","what":"Hạt/cây giống","via":"inventory_moves"},{"from":"XNK","what":"Giống nhập khẩu","via":"import_permits"}]','[{"to":"TT","what":"Cây con","via":"crop_logs GIEO"}]','Theo giống','worker','Nảy mầm ≥85%','{crop_seasons,crop_logs,inventory_moves}','/canh-tac','DA_CO',11),
('P-CT-03','TT','Tưới – dinh dưỡng đất – phân hữu cơ (từ khu D) – vôi','CORE','CAY_TRONG','CHAM_SOC','Theo lịch/cảm biến','[{"from":"SH","what":"Phân hữu cơ/compost","via":"inventory_moves"},{"from":"CNTB","what":"Ẩm đất/thời tiết","via":"sensor_reads"}]','[{"to":"QA","what":"Nhật ký phân bón","via":"crop_inputs"}]','Ngày','worker','Nước m3/kg','{crop_inputs,crop_logs,sensor_reads}','/canh-tac','DA_CO',12),
('P-CT-04','TT','Bảo vệ thực vật – IPM – sinh học – PHI (danh mục được phép hữu cơ)','CORE','CAY_TRONG','CHAM_SOC','Phát hiện sâu bệnh','[{"from":"CCU","what":"Thuốc BVTV/sinh học K1","via":"inventory_moves"}]','[{"to":"TT","what":"Khóa thu hoạch đến safe_after","via":"trigger PHI"},{"to":"QA","what":"Hồ sơ BVTV","via":"crop_inputs"}]','Ngay','team_lead','PHI vi phạm = 0','{crop_inputs}','/canh-tac','DA_CO',13),
('P-CT-05','TT','Cây lâu năm: kiến thiết cơ bản → tỉa cành – tạo tán → ra hoa – đậu quả → thu theo vụ → tái canh','CORE','CAY_TRONG','CHAM_SOC','Theo năm tuổi','[]','[{"to":"KDM","what":"Quả theo mùa","via":"harvests"}]','Mùa','team_lead','kg/cây','{crop_seasons,crop_logs,harvests}','/canh-tac','DA_CO',14),
('P-CT-06','TT','Sơ chế – bảo quản sau thu hoạch (rửa, phân loại, đóng gói, lạnh, ủ chua)','CORE','CAY_TRONG','SAU_THU','Sau thu hoạch','[{"from":"TT","what":"Lô thu hoạch","via":"harvests"}]','[{"to":"CCU","what":"K2/K3/K5/K6","via":"inventory_moves"},{"to":"D5","what":"Nguyên liệu chế biến","via":"lots"}]','≤24h','worker','Hao hụt ≤5%','{harvests,batch_logs,inventory_moves,lots}','/kho','DA_CO',15),
('P-CT-07','TT','Nấm – rau nhà màng – thủy canh (nếu mở)','CORE','CAY_TRONG','CHAM_SOC','Theo mẻ','[]','[]','Mẻ','worker','kg/m²','{crop_seasons,crop_logs,harvests}','/canh-tac','MOT_PHAN',16),
-- SẢN XUẤT – CHẾ BIẾN
('P-SX-01','D5','Ủ chua sinh khối: cắt → băm → nén → bọc → theo dõi pH → xuất K3','CORE','SAN_XUAT','CHE_BIEN','Vụ thu','[{"from":"TT","what":"Bắp/cỏ tươi","via":"harvests"}]','[{"to":"CCU","what":"K3 ủ chua","via":"inventory_moves"},{"to":"KTCN","what":"Ngày-tồn ủ chua","via":"v_days_silage"}]','Vụ','team_lead','Hao hụt ≤10%','{batch_logs,inventory_moves}','/kho','DA_CO',10),
('P-SX-02','D5','Chế biến sâu (sữa chua/phô mai/xúc xích/khô/bột) & QC lô','CORE','SAN_XUAT','CHE_BIEN','Đơn hàng','[{"from":"KTCN","what":"Sữa/thịt/trứng","via":"inventory_moves"}]','[{"to":"KDM","what":"SKU chế biến","via":"lots"}]','Mẻ','team_lead','QC đạt','{batch_logs,lots,checklist_runs}','/kho','MOT_PHAN',11),
('P-SX-03','D5','Đóng gói – nhãn – GS1/QR – tem truy xuất – kho lạnh','CORE','SAN_XUAT','DONG_GOI','Sau mẻ','[{"from":"CCU","what":"Bao bì K9","via":"inventory_moves"}]','[{"to":"KDM","what":"SKU sẵn bán + QR","via":"lots.qr"}]','Mẻ','worker','Sai nhãn = 0','{lots,inventory_moves,products}','/truy-xuat','DA_CO',12),
('P-SX-04','SH','Biogas → điện/nhiệt; compost → phân bón; trùn/BSF → đạm & phân','CORE','SAN_XUAT','TUAN_HOAN','Ngày','[{"from":"KTCN","what":"Phân chuồng","via":"batch_logs"}]','[{"to":"TT","what":"Phân hữu cơ","via":"inventory_moves"},{"to":"D5","what":"Đạm côn trùng","via":"inventory_moves"}]','Ngày','worker','Tuần hoàn ≥90%','{batch_logs,inventory_moves,sensor_reads}','/ca','DA_CO',13),
-- CON NGƯỜI
('P-NS-01','HCNS','Ca làm việc – chấm công – giao ca (shift_notes) – checklist đầu/cuối ca','CORE','CON_NGUOI','VAN_HANH','Ca','[]','[{"to":"HCNS","what":"Công/KPI","via":"v_staff_activity"}]','Ca','team_lead','Giao ca 100%','{shift_notes,checklist_runs,tasks}','/ca','DA_CO',10),
('P-NS-02','HCNS','Đào tạo SOP – chứng chỉ – khám SK/ATTP – an toàn lao động','CORE','CON_NGUOI','PHAT_TRIEN','Định kỳ','[{"from":"QA","what":"SOP mới","via":"sops"}]','[{"to":"QA","what":"Chứng chỉ đủ","via":"staff.sop_certs"}]','Quý','director','Đủ 100%','{staff,sops,tasks}','/nhan-su','DA_CO',11),
('P-NS-03','HCNS','KPI → lương lớp 2 → thưởng/phạt → bảng lương','CORE','CON_NGUOI','LUONG','Tháng','[{"from":"*","what":"Bản ghi & KPI","via":"kpi_results"}]','[{"to":"TCKT","what":"Bảng lương","via":"v_staff_kpi_month"}]','Ngày 3','accountant','Đúng hạn','{kpi_results,kpi_defs}','/nhan-su','DA_CO',12),
('P-NS-04','HCNS','Tuyển – HĐLĐ – hồ sơ – phân trại – tài khoản/PIN – nghỉ việc/thu hồi quyền','CORE','CON_NGUOI','VONG_DOI','Nhu cầu','[]','[{"to":"CNTB","what":"Tài khoản","via":"staff"}]','Tuần','director','Nghỉ việc ≤10%','{staff,audit_log}','/quan-tri?t=staff','DA_CO',13),
-- VẬT TƯ / KHO / THIẾT BỊ / TÀI CHÍNH bổ sung
('P-KHO-01','CCU','Đánh giá & phê duyệt NCC (COA, ≤35%/nguồn, review định kỳ)','MANAGEMENT','VAT_TU_KHO','MUA','Quý','[]','[{"to":"CCU","what":"NCC được duyệt","via":"partners.approved"}]','Quý','accountant','NCC đạt','{partners,documents}','/quan-tri?t=partners','DA_CO',10),
('P-KHO-02','CCU','Kiểm kê định kỳ (tuần K4–K6, tháng K1–K3) → chênh lệch → điều chỉnh có duyệt','CORE','VAT_TU_KHO','KIEM_KE','Lịch','[]','[{"to":"TCKT","what":"Biên bản kiểm kê","via":"stocktakes"}]','Theo kho','worker','Chênh ≤1%','{stocktakes,adjustments}','/kho','DA_CO',11),
('P-KHO-03','CCU','Hàng lạnh – nhiệt độ – FEFO – hủy hàng hết hạn','CORE','VAT_TU_KHO','BAO_QUAN','Ngày','[{"from":"CNTB","what":"Cảm biến nhiệt","via":"sensor_reads"}]','[{"to":"QA","what":"Log nhiệt độ","via":"sensor_reads"}]','Ngày','worker','FEFO đỏ = 0','{inventory_moves,lots,sensor_reads}','/kho','DA_CO',12),
('P-TB-01','CNTB','Cảm biến/IoT: lắp → MQTT → ngưỡng → cảnh báo → bảo trì','CORE','THIET_BI_DU_LIEU','VAN_HANH','Liên tục','[]','[{"to":"*","what":"Cảnh báo sensor-off/ngưỡng","via":"alerts"}]','Realtime','it_engineer','Off ≤1%','{devices,sensor_reads,alert_rules}','/thiet-bi','DA_CO',10),
('P-TC-03','TCKT','Ngân sách – quỹ (thiên tai/bảo dưỡng/đào tạo/marketing) – theo dõi vượt','MANAGEMENT','TAI_CHINH','NGAN_SACH','Năm/tháng','[]','[{"to":"BGD","what":"Vượt ngân sách","via":"alerts"}]','Tháng','accountant','Vượt = 0','{funds,cc_fixed_costs}','/ke-toan','DA_CO',10),
('P-TC-04','TCKT','Giá thành sản phẩm (CC → SKU) & giá chuyển nội bộ 70%','MANAGEMENT','TAI_CHINH','GIA_THANH','Tháng','[{"from":"CCU","what":"Nhập xuất theo CC","via":"cc_of_move"}]','[{"to":"KDM","what":"Giá sàn","via":"price_list"}]','Tháng','accountant','Biên ≥ mục tiêu','{v_pl_cc_month,price_list}','/ke-toan','DA_CO',11),
('P-QT-01','HDQT','Quản trị rủi ro – sự cố – kế hoạch ứng phó (dịch, lũ, cháy, mất điện)','MANAGEMENT','QUAN_TRI','RUI_RO','Sự cố/quý','[{"from":"*","what":"Sự cố","via":"incidents"}]','[{"to":"*","what":"Kịch bản/checklist","via":"sops"}]','Quý','director','Đóng sự cố ≤7 ngày','{incidents,sops,funds}','/gd','DA_CO',10),
('P-QT-02','HDQT','Báo cáo định kỳ: tuần chủ – tháng BGĐ – quý cơ quan (TT66, thuế, môi trường)','MANAGEMENT','QUAN_TRI','BAO_CAO','Lịch','[{"from":"*","what":"Mọi số liệu","via":"views"}]','[{"to":"Cơ quan","what":"File chuẩn","via":"exports"}]','Đúng hạn','accountant','Đúng hạn 100%','{agg_daily,exports}','/audit','DA_CO',11)
on conflict (code) do update set name=excluded.name, object_type=excluded.object_type, coverage=excluded.coverage, ui_path=excluded.ui_path, inputs=excluded.inputs, outputs=excluded.outputs, tables=excluded.tables;
create or replace view v_process_coverage as select object_type, coverage, count(*) as n from processes where active group by 1,2 order by 1,2;
grant select on v_process_coverage to app_user;
