-- 0025 · Tài liệu / biểu mẫu / file / công cụ đi kèm mỗi quy trình và mỗi bước (không bỏ sót): documents jsonb [{kind: BIEU_MAU|SOP|HO_SO|FILE|CONG_CU|PHAN_MEM, name, ref, required}]
alter table processes add column if not exists documents jsonb default '[]'::jsonb, add column if not exists tools text[] default '{}', add column if not exists visible_depts text[] default '{}';
alter table process_steps add column if not exists documents jsonb default '[]'::jsonb;
update processes set documents = (case code
  when 'P-TT-02' then '[{"kind":"BIEU_MAU","name":"BM06 Nhật ký ruộng","ref":"crop_logs","required":true},{"kind":"BIEU_MAU","name":"Phiếu vật tư/BVTV (PHI)","ref":"crop_inputs","required":true},{"kind":"BIEU_MAU","name":"Phiếu thu hoạch + phiếu cân","ref":"harvests,weigh_tickets","required":true},{"kind":"SOP","name":"SOP canh tác hữu cơ / VietGAP","ref":"/sop","required":true},{"kind":"HO_SO","name":"Nhật ký sản xuất (xuất ZIP)","ref":"crop-dossier","required":true},{"kind":"FILE","name":"Danh mục thuốc BVTV được phép (hữu cơ)","ref":"products.kind=THUOC organic_allowed","required":true},{"kind":"CONG_CU","name":"Máy cày · máy gieo · bình phun · máy cắt/băm · cân 40T","ref":"devices","required":false},{"kind":"PHAN_MEM","name":"Form 3 chạm A6 · /canh-tac · /kho","ref":"/ca","required":true}]'
  when 'P-KD-02' then '[{"kind":"BIEU_MAU","name":"Đơn hàng / HĐ bao tiêu","ref":"orders,contracts","required":true},{"kind":"BIEU_MAU","name":"Phiếu xuất kho + phiếu cân + phiếu cổng","ref":"inventory_moves,weigh_tickets,gate_logs","required":true},{"kind":"BIEU_MAU","name":"BM09 Bán hàng / hóa đơn","ref":"sales","required":true},{"kind":"FILE","name":"Bảng giá sàn","ref":"price_list","required":true},{"kind":"HO_SO","name":"Bảng kê bán hàng thuế (sales-tax)","ref":"sales-tax","required":true},{"kind":"CONG_CU","name":"Cân · máy in tem/QR · POS","ref":"devices","required":false},{"kind":"PHAN_MEM","name":"/ban-hang · /kho · A9","ref":"/ban-hang","required":true}]'
  when 'P-DL-01' then '[{"kind":"BIEU_MAU","name":"Phiếu booking / đăng ký lưu trú","ref":"hosp_bookings","required":true},{"kind":"BIEU_MAU","name":"Folio thanh toán","ref":"hosp_folio","required":true},{"kind":"HO_SO","name":"Khai báo lưu trú (CA), danh sách khách","ref":"table:hosp_bookings","required":true},{"kind":"FILE","name":"Bảng giá phòng/dịch vụ","ref":"hosp_room_types,hosp_services","required":true},{"kind":"CONG_CU","name":"Máy POS · máy in · khóa phòng","ref":"devices","required":false},{"kind":"PHAN_MEM","name":"/du-lich","ref":"/du-lich","required":true}]'
  when 'P-XNK-01' then '[{"kind":"HO_SO","name":"Hồ sơ thị trường (yêu cầu chứng nhận, dư lượng, nhãn)","ref":"market_profiles","required":true},{"kind":"BIEU_MAU","name":"Hợp đồng ngoại thương / LC","ref":"trade_contracts","required":true},{"kind":"FILE","name":"Invoice · Packing list · CO · Phyto/Health cert · Halal · B/L · Bảo hiểm","ref":"trade_documents","required":true},{"kind":"BIEU_MAU","name":"Tờ khai hải quan","ref":"customs_declarations","required":true},{"kind":"HO_SO","name":"Truy xuất lô EPCIS + COA","ref":"epcis,documents","required":true},{"kind":"BIEU_MAU","name":"Thanh toán quốc tế · tỷ giá · landed cost","ref":"intl_payments,fx_rates,landed_costs","required":true},{"kind":"PHAN_MEM","name":"/quan-tri?t=trade_contracts","ref":"/quan-tri","required":true}]'
  when 'P-KT-01' then '[{"kind":"BIEU_MAU","name":"BM05 Nhập đàn / lô nhập","ref":"intake_lots,animal_events","required":true},{"kind":"FILE","name":"Giấy kiểm dịch, hồ sơ nguồn gốc giống","ref":"documents","required":true},{"kind":"CONG_CU","name":"Thẻ tai/RFID · máy đọc · cân","ref":"animal_tags,devices","required":true},{"kind":"SOP","name":"SOP nhập đàn – cách ly 21 ngày","ref":"/sop","required":true},{"kind":"PHAN_MEM","name":"/dan · A5","ref":"/dan","required":true}]'
  when 'P-KT-03' then '[{"kind":"BIEU_MAU","name":"BM02 Điều trị / thú y","ref":"animal_events","required":true},{"kind":"FILE","name":"Phác đồ điều trị · lịch vaccine","ref":"treatment_protocols,vaccine_schedules","required":true},{"kind":"HO_SO","name":"Sổ thuốc thú y (medicine-book)","ref":"medicine-book","required":true},{"kind":"CONG_CU","name":"Tủ thuốc K1 · dụng cụ tiêm · nhiệt kế","ref":"warehouses","required":true},{"kind":"PHAN_MEM","name":"/thu-y · A2","ref":"/thu-y","required":true}]'
  when 'P-D5-01' then '[{"kind":"BIEU_MAU","name":"BM01 Mẻ TMR (KH/thực)","ref":"feed_logs","required":true},{"kind":"FILE","name":"Công thức TMR · kế hoạch khẩu phần","ref":"recipes,feed_plans","required":true},{"kind":"CONG_CU","name":"Máy trộn · cân bàn · xe phát","ref":"devices","required":true},{"kind":"PHAN_MEM","name":"A1 · /ke-hoach","ref":"/ca","required":true}]'
  when 'P-CCU-01' then '[{"kind":"BIEU_MAU","name":"Đơn mua (PO)","ref":"purchase_orders","required":true},{"kind":"FILE","name":"COA/CoQ NCC · báo giá","ref":"documents","required":true},{"kind":"BIEU_MAU","name":"BM08 Nhập kho","ref":"inventory_moves","required":true},{"kind":"HO_SO","name":"Đánh giá NCC","ref":"partners","required":true},{"kind":"PHAN_MEM","name":"/ke-toan (PO) · /kho","ref":"/kho","required":true}]'
  when 'P-TC-01' then '[{"kind":"BIEU_MAU","name":"Đề nghị chi (2 chữ ký >20tr)","ref":"expense_requests","required":true},{"kind":"FILE","name":"Hóa đơn/chứng từ đính kèm","ref":"documents","required":true},{"kind":"PHAN_MEM","name":"/ke-toan","ref":"/ke-toan","required":true}]'
  when 'P-HC-01' then '[{"kind":"BIEU_MAU","name":"Hợp đồng lao động · hồ sơ nhân sự","ref":"staff","required":true},{"kind":"FILE","name":"Chứng chỉ SOP · khám sức khỏe · tập huấn ATTP","ref":"staff.sop_certs","required":true},{"kind":"HO_SO","name":"Bảng KPI→lương","ref":"v_staff_kpi_month","required":true},{"kind":"PHAN_MEM","name":"/nhan-su · /quan-tri?t=staff","ref":"/nhan-su","required":true}]'
  else '[{"kind":"PHAN_MEM","name":"Màn hình quy trình","ref":"'||coalesce(ui_path,'/to-chuc')||'","required":true}]' end)::jsonb
where documents = '[]'::jsonb or documents is null;
update processes set documents = documents || jsonb_build_array(jsonb_build_object('kind','HO_SO','name','Bảng dữ liệu: '||array_to_string(tables,', '),'ref',array_to_string(tables,','),'required',true)) where array_length(tables,1) > 0 and not exists (select 1 from jsonb_array_elements(documents) d where d->>'kind'='HO_SO' and (d->>'name') like 'Bảng dữ liệu%');
update processes set visible_depts = array_remove(array[dept_code] || (select array_agg(distinct x) from (select jsonb_array_elements(inputs)->>'from' as x union select jsonb_array_elements(outputs)->>'to') t where x is not null and x<>'*'), null) where cardinality(visible_depts)=0;
