-- 0027 · ITRAN STANDARD — tiêu chuẩn sản xuất tuần hoàn của riêng ITRAN FARM (áp cho trại ITRAN & hộ liên kết/franchise), minh bạch – có bằng chứng dữ liệu – công khai
-- Nguyên tắc sinh chuẩn: (1) kế thừa điều khoản mạnh nhất của VietGAP/GlobalG.A.P./EU Organic/ISO 22000/Halal/ASC (map sang cột 'basis'), (2) THÊM những gì họ không có: tuần hoàn (chất thải→tài nguyên), định danh cá thể suốt đời, dữ liệu realtime + append-only + đối soát RC, minh bạch công khai (QR/EPCIS/portal), phúc lợi & việc làm địa phương;
-- (3) mọi yêu cầu PHẢI đo được bằng bảng dữ liệu (evidence_tables) → mức tuân thủ tự tính, không tự khai; (4) phiên bản hóa, công khai lịch sử sửa đổi (audit_log).
alter table standard_requirements add column if not exists basis text[] default '{}', add column if not exists metric_sql text, add column if not exists threshold text, add column if not exists public bool default true, add column if not exists points int default 1;
alter table standards add column if not exists owner_org text, add column if not exists public bool default false, add column if not exists pillars text[] default '{}', add column if not exists levels jsonb default '[]'::jsonb;
insert into standards(code,name,issuer,scope,region,version,description,required_for,position,owner_org,public,pillars,levels,url) values
('ITRAN-STD','ITRAN Circular Farm Standard (ICFS) v1.0','ITRAN FARM','QUAN_LY','VN+GLOBAL','1.0',
 'Tiêu chuẩn trang trại tuần hoàn ITRAN: 7 trụ cột — 1 An toàn & truy xuất · 2 Tuần hoàn tài nguyên · 3 Định danh & phúc lợi vật nuôi · 4 Đất–nước–đa dạng sinh học · 5 Con người & cộng đồng · 6 Dữ liệu minh bạch (append-only, đối soát, công khai) · 7 Quản trị & cải tiến. Mọi điều khoản đo bằng dữ liệu, không tự khai.',
 '{HO_LIEN_KET,FRANCHISE,XUAT_KHAU,NHAN_NUOI}',0,'ITRAN',true,'{AN_TOAN,TUAN_HOAN,VAT_NUOI,DAT_NUOC,CON_NGUOI,DU_LIEU,QUAN_TRI}',
 '[{"level":"ĐỒNG","min_pct":60,"desc":"Đủ hồ sơ & truy xuất; đang chuyển đổi"},{"level":"BẠC","min_pct":80,"desc":"Tuân thủ đủ, tuần hoàn ≥70%"},{"level":"VÀNG","min_pct":92,"desc":"Xuất khẩu được: 0 vi phạm CRITICAL 12 tháng, công khai dữ liệu"}]','https://github.com/ztrandinh/itranagri (docs/plan/13, /chuan)')
on conflict (code) do update set name=excluded.name, description=excluded.description, pillars=excluded.pillars, levels=excluded.levels, public=true, owner_org='ITRAN';
insert into standard_requirements(standard_code,clause,title,requirement,level,evidence_tables,evidence_records,process_codes,frequency,owner_dept,basis,metric_sql,threshold,points) values
-- 1 An toàn & truy xuất
('ITRAN-STD','1.1','Mỗi lô sản phẩm truy xuất được về ô/đàn/mẻ và người ghi trong ≤4 giờ','QR lô → EPCIS: đầu vào → mẻ → SKU → khách','CRITICAL','{lots,inventory_moves,batch_logs,harvests}','{HS-TRUY-XUAT}','{P-QA-02,P-SX-03}','Mỗi lô','QA','{VIETGAP-TT:10,ISO22000:8.3,GLOBALGAP:AF}','select round(100.0*count(*) filter (where exists (select 1 from inventory_moves m where m.lot_id=l.id))/nullif(count(*),0),0) from lots l where l.farm_id=$1','≥95%',3),
('ITRAN-STD','1.2','Không thu hoạch trong thời gian cách ly BVTV (PHI) và không xuất bán khi chưa hết ngưng thuốc thú y','Hệ thống chặn bằng trigger; vi phạm = 0','CRITICAL','{crop_inputs,harvests,animal_events,sales}','{HS-CANH-TAC,HS-THU-Y}','{P-CT-04,P-KT-03}','Liên tục','TT','{VIETGAP-TT:6,VIETGAP-CN:4,GLOBALGAP:CB,EU-ORGANIC:3}','select count(*) from alerts where farm_id=$1 and rule_code in (''AL-WITHDRAWAL'',''AL-PHI'') and ts>now()-interval ''365 days''','=0',3),
('ITRAN-STD','1.3','Đầu vào (phân, BVTV, thuốc, TACN) chỉ từ danh mục được phép, có nguồn gốc & lô','products.organic_allowed / lô NCC','MAJOR','{crop_inputs,inventory_moves,partners,documents}','{HS-KHO}','{P-CCU-01}','Mỗi lần','CCU','{EU-ORGANIC:2,USDA-NOP:2,VIETGAP-TT:4}','select round(100.0*count(*) filter (where organic_allowed is not false)/nullif(count(*),0),0) from crop_inputs where farm_id=$1 and status=''ACTIVE'' and ts>now()-interval ''365 days''','=100%',2),
('ITRAN-STD','1.4','HACCP/PRP cho mọi công đoạn chế biến; kho lạnh có log nhiệt độ; hiệu chuẩn cân đúng hạn','checklist CCP + sensor + calibrations','MAJOR','{checklist_runs,sensor_reads,calibrations}','{HS-ATTP,HS-THIET-BI}','{P-D5-02,P-CN-01}','Ngày','D5','{ISO22000:8.2,HACCP:1-7}','select count(*) from devices where farm_id=$1 and calib_due < current_date','=0',2),
-- 2 Tuần hoàn
('ITRAN-STD','2.1','≥90% chất thải hữu cơ (phân, phụ phẩm) quay lại chuỗi (trùn/BSF/biogas/compost)','kg vào khu D / kg chất thải ước tính theo định mức','MAJOR','{batch_logs,herd_daily,norms}','{HS-MOI-TRUONG}','{P-SH-01,P-SX-04}','Tháng','SH','{}','select round(100.0*coalesce(sum((i->>''kg'')::numeric),0)/nullif((select coalesce(sum(head),0)*20*30 from herd_daily h where h.farm_id=$1 and h.day=(select max(day) from herd_daily where farm_id=$1)),0),0) from batch_logs b, jsonb_array_elements(b.inputs) i where b.farm_id=$1 and b.status=''ACTIVE'' and b.ts>now()-interval ''30 days''','≥90%',3),
('ITRAN-STD','2.2','≥60% thức ăn thô xanh tự sản xuất trong trại/vùng liên kết (sinh khối theo K)','kg cỏ/bắp tự trồng / tổng kg TA thô','MAJOR','{feed_logs,harvests,inventory_moves}','{HS-THUC-AN,HS-THU-HOACH}','{P-TT-01,P-D5-01}','Tháng','TT','{}','select round(100.0*(select coalesce(sum(qty),0) from inventory_moves where farm_id=$1 and status=''ACTIVE'' and direction=1 and reason<>''NHAP_MUA'' and sku in (''NL-CO-TUOI'',''NL-BAP-U'') and ts>now()-interval ''90 days'')/nullif((select sum(qty) from inventory_moves where farm_id=$1 and status=''ACTIVE'' and direction=1 and sku in (''NL-CO-TUOI'',''NL-BAP-U'',''NL-ROM'') and ts>now()-interval ''90 days''),0),0)','≥60%',2),
('ITRAN-STD','2.3','Năng lượng tái tạo (biogas/solar) và nước tuần hoàn được đo & công bố','sensor/biogas m3, solar kWh, nước m3','MINOR','{sensor_reads,facilities}','{HS-MOI-TRUONG}','{P-SX-04}','Tháng','CNTB','{ISO14001}','select count(*) from sensor_reads where farm_id=$1 and metric in (''biogas_m3'',''solar_kwh'',''water_m3'') and ts>now()-interval ''30 days''','>0',1),
('ITRAN-STD','2.4','Không đốt phụ phẩm; nước thải đạt QCVN trước khi ra môi trường','quan trắc + sự cố MT = 0','MAJOR','{sensor_reads,incidents}','{HS-MOI-TRUONG}','{P-SH-02}','Quý','SH','{ISO14001,ASC:2}','select count(*) from incidents where farm_id=$1 and kind=''MOI_TRUONG'' and ts>now()-interval ''365 days''','=0',2),
-- 3 Vật nuôi
('ITRAN-STD','3.1','100% bò/dê có mã cá thể suốt đời trong 24h nhập/sinh; gia cầm/thủy sản theo đàn có lô','animals/animal_tags','CRITICAL','{animals,animal_tags,intake_lots}','{HS-SO-DAN}','{P-KT-01}','Liên tục','KTCN','{GLOBALGAP:LB,VIETGAP-CN:7}','select round(100.0*count(*) filter (where not coalesce(tag_pending,false))/nullif(count(*),0),0) from animals where farm_id=$1 and status not in (''CHET'',''XUAT'',''LOAI'')','≥98%',3),
('ITRAN-STD','3.2','Phúc lợi 5 tự do: mật độ, nước, bóng mát, không đói khát; tỷ lệ chết ≤3%/năm (bò)','herd_daily + CHET','MAJOR','{animal_events,herd_daily,locations}','{HS-SO-DAN}','{P-VN-07}','Tháng','KTCN','{GLOBALGAP:LB,EU-ORGANIC:3}','select round(100.0*(select coalesce(sum(coalesce(value,1)),0) from animal_events where farm_id=$1 and status=''ACTIVE'' and event_type=''CHET'' and animal_id is not null and ts>now()-interval ''365 days'')/nullif((select count(*) from animals where farm_id=$1 and species=''BO''),0),1)','≤3%',2),
('ITRAN-STD','3.3','Kháng sinh chỉ khi có bệnh, theo phác đồ, ghi ngưng thuốc; không kháng sinh kích thích tăng trưởng','animal_events DIEU_TRI có protocol','MAJOR','{animal_events,treatment_protocols}','{HS-THU-Y}','{P-KT-03}','Mỗi lần','KTCN','{VIETGAP-CN:4,ASC:3,EU-ORGANIC:3}','select round(100.0*count(*) filter (where withdrawal_until is not null)/nullif(count(*),0),0) from animal_events where farm_id=$1 and status=''ACTIVE'' and event_type=''DIEU_TRI'' and ts>now()-interval ''365 days''','=100%',2),
-- 4 Đất nước
('ITRAN-STD','4.1','Phân tích đất & nước ≥1 lần/năm mỗi vùng; kết quả công khai','lab_samples DAT/NUOC','MAJOR','{lab_samples}','{HS-DAT-NUOC}','{P-TT-03}','Năm','TT','{VIETGAP-TT:1,GLOBALGAP:CB}','select count(*) from lab_samples where farm_id=$1 and kind in (''DAT'',''NUOC'') and taken_at>now()-interval ''365 days''','≥2',1),
('ITRAN-STD','4.2','≥5% diện tích là viền sinh thái (cây chắn gió, hoa, ao lắng); không GMO','plots kind VIEN','MINOR','{plots,crops}','{HS-CANH-TAC}','{P-CT-01}','Năm','TT','{RAINFOREST,EU-ORGANIC:1}','select round(100.0*coalesce(sum(area_ha) filter (where crop_code in (''KEO'',''TRE'',''HOA'') or kind=''VIEN''),0)/nullif(sum(area_ha),0),1) from plots where farm_id=$1 and coalesce(active,true)','≥5%',1),
-- 5 Con người
('ITRAN-STD','5.1','100% nhân sự có HĐLĐ, chứng chỉ SOP vị trí, khám SK/tập huấn ATTP còn hạn','staff','MAJOR','{staff}','{HS-NHAN-SU}','{P-NS-02,P-NS-04}','Năm','HCNS','{GLOBALGAP:AF,VIETGAP-TT:9,ASC:4}','select round(100.0*count(*) filter (where health_check_due>=current_date and food_safety_training_due>=current_date)/nullif(count(*),0),0) from staff where active and (farm_id=$1 or $1=any(farm_ids))','≥95%',2),
('ITRAN-STD','5.2','KPI→lương minh bạch, công khai công thức; không lao động trẻ em; ưu tiên lao động địa phương','kpi_results','MINOR','{kpi_results,kpi_defs}','{HS-NHAN-SU}','{P-NS-03}','Tháng','HCNS','{RAINFOREST}','select count(*) from kpi_results where farm_id=$1 and period_start>=date_trunc(''month'',now())-interval ''1 month''','>0',1),
-- 6 Dữ liệu minh bạch (khác biệt của ITRAN)
('ITRAN-STD','6.1','Mọi bản ghi sản xuất là append-only, có người ghi & thời điểm; sửa = bản mới; ≥95% ghi trong ngày','events source/is_backfill','CRITICAL','{animal_events,feed_logs,crop_logs,inventory_moves}','{HS-AUDIT}','{P-CN-02}','Liên tục','CNTB','{}','select round(100.0*count(*) filter (where not is_backfill)/nullif(count(*),0),0) from (select is_backfill from feed_logs where farm_id=$1 and ts>now()-interval ''30 days'' union all select is_backfill from crop_logs where farm_id=$1 and ts>now()-interval ''30 days'' union all select is_backfill from animal_events where farm_id=$1 and ts>now()-interval ''30 days'') u','≥95%',3),
('ITRAN-STD','6.2','Đối soát tự động cân–kho–sổ–giấy (RC1–RC16) chạy hằng đêm; lệch >5% phải có giải trình','recon_results','CRITICAL','{recon_results,job_runs}','{HS-AUDIT}','{P-CN-02,P-TC-02}','Ngày','QA','{}','select round(100.0*count(*) filter (where status=''OK'')/nullif(count(*),0),0) from recon_results where farm_id=$1 and period>current_date-30','≥90%',3),
('ITRAN-STD','6.3','Công khai dữ liệu: QR truy xuất công khai cho khách; portal nhận nuôi; báo cáo tuần hoàn công bố theo quý','trace + portal + export','MAJOR','{lots,custody_contracts,documents}','{HS-TRUY-XUAT,HS-NHAN-NUOI}','{P-KD-04,P-QT-02}','Quý','KDM','{}','select count(*) from lots where farm_id=$1 and qr_token is not null','>0',2),
('ITRAN-STD','6.4','Gói audit (sha256) xuất được bất kỳ lúc nào; lưu hồ sơ ≥5 năm','audit-pack','MAJOR','{audit_log,recon_results}','{HS-AUDIT}','{P-QT-02}','Quý','QA','{USDA-NOP:3}','select count(*) from job_runs where farm_id=$1 and job like ''%backup%'' and started_at>now()-interval ''30 days''','≥4',1),
-- 7 Quản trị
('ITRAN-STD','7.1','Tự đánh giá nội bộ theo ICFS mỗi quý; NC đóng ≤30 ngày','compliance_checks','MAJOR','{compliance_checks}','{HS-TUAN-THU}','{P-QA-01}','Quý','QA','{ISO9001,VIETGAP-TT:11}','select count(*) from compliance_checks where farm_id=$1 and standard_code=''ITRAN-STD'' and checked_at>now()-interval ''100 days''','≥1',1),
('ITRAN-STD','7.2','Sự cố (dịch, môi trường, ATTP) báo trong 24h, có nguyên nhân & khắc phục','incidents','MAJOR','{incidents}','{HS-AUDIT}','{P-QT-01}','Mỗi lần','GDT','{ISO22000:8.9}','select count(*) from incidents where farm_id=$1 and status<>''DONG'' and ts<now()-interval ''7 days''','=0',1),
('ITRAN-STD','7.3','Hộ liên kết/franchise dùng cùng hệ thống dữ liệu ITRAN AGRI (cùng biểu mẫu, cùng đối soát) và được audit chéo','farms/franchise_sites','MINOR','{farms,franchise_sites}','{HS-PHAP-LY}','{P-MR-01}','Năm','MR','{}','select 1','—',1)
on conflict (standard_code, clause) do update set title=excluded.title, requirement=excluded.requirement, evidence_tables=excluded.evidence_tables, basis=excluded.basis, metric_sql=excluded.metric_sql, threshold=excluded.threshold, points=excluded.points, level=excluded.level;
-- Điểm ICFS theo trại: tính metric_sql từng điều khoản (an toàn: chỉ chạy các SQL đã khai báo trong bảng, do QA/IT quản lý)
create or replace function icfs_score(p_farm text) returns table(clause text, title text, level text, points int, threshold text, value text, pass bool) language plpgsql security definer as $$
declare r record; v text; ok bool; num numeric; th text; begin
  for r in select * from standard_requirements where standard_code='ITRAN-STD' order by clause loop
    v := null; ok := null;
    if r.metric_sql is not null then begin execute r.metric_sql into v using p_farm; exception when others then v := 'ERR'; end; end if;
    th := coalesce(r.threshold,''); num := nullif(regexp_replace(coalesce(v,''),'[^0-9.\-]','','g'),'')::numeric;
    if v is null or v='ERR' then ok := null;
    elsif th like '≥%' then ok := num >= nullif(regexp_replace(th,'[^0-9.]','','g'),'')::numeric;
    elsif th like '≤%' then ok := num <= nullif(regexp_replace(th,'[^0-9.]','','g'),'')::numeric;
    elsif th like '=%' then ok := num = nullif(regexp_replace(th,'[^0-9.]','','g'),'')::numeric;
    elsif th like '>%' then ok := num > nullif(regexp_replace(th,'[^0-9.]','','g'),'')::numeric;
    else ok := true; end if;
    clause := r.clause; title := r.title; level := r.level; points := r.points; threshold := r.threshold; value := v; pass := ok; return next;
  end loop; end $$;
grant execute on function icfs_score(text) to app_user;
create or replace view v_icfs_summary as
select f.id as farm_id, f.name, s.total_points, s.got_points, round(100.0*s.got_points/nullif(s.total_points,0),0) as pct, s.critical_fail,
  case when s.critical_fail>0 then 'CHƯA ĐẠT' when 100.0*s.got_points/nullif(s.total_points,0)>=92 then 'VÀNG' when 100.0*s.got_points/nullif(s.total_points,0)>=80 then 'BẠC' when 100.0*s.got_points/nullif(s.total_points,0)>=60 then 'ĐỒNG' else 'CHƯA ĐẠT' end as level
from farms f cross join lateral (select coalesce(sum(points),0) as total_points, coalesce(sum(points) filter (where pass),0) as got_points, count(*) filter (where level='CRITICAL' and pass=false) as critical_fail from icfs_score(f.id)) s;
grant select on v_icfs_summary to app_user;
