-- 0041 · Bước chi tiết A→Z cho 47 quy trình còn lại (mỗi bước: bộ phận · vai · làm gì · ở đâu · kiểm soát · biểu mẫu/bảng · SLA); QA sửa tiếp trong app
insert into process_steps(process_code,step_no,name,actor_role,dept_code,action,system_where,control,form_table,sla_hours,tools) values
-- CCU-03 cổng – cân
('P-CCU-03',1,'Xe đến: ghi biển số, mục đích, sát trùng','worker','CCU','gate_logs VAO + anolyte_wash','/ca A10','ATSH: mọi xe qua hố sát trùng','gate_logs',1,'{Sổ cổng,Máy phun sát trùng}'),
('P-CCU-03',2,'Cân tổng/bì, phiếu cân','worker','CCU','weigh_tickets gross/tare/net, ảnh','/ca A10','Cân hiệu chuẩn còn hạn','weigh_tickets',1,'{Cân 40T}'),
('P-CCU-03',3,'Xe ra: khớp phiếu với nhập/xuất kho','worker','CCU','gate_logs RA; đối soát RC cân–kho','/ca A10','Chênh ≤2%','gate_logs',1,'{}'),
-- CN-02 dữ liệu & hệ thống
('P-CN-02',1,'Job đêm: recon RC1–RC16, cảnh báo, việc, snapshot, backup','it_engineer','CNTB','instrumentation 01:15 / POST /api/jobs/all','/canh-bao, /api/health','job_runs ok','job_runs',1,'{}'),
('P-CN-02',2,'Dispatch thông báo & kênh (app/push/Zalo/SMS/email/webhook)','it_engineer','CNTB','mỗi phút: event_bus → notifications → deliveries','/quan-tri?t=notification_deliveries','event_bus tồn <500','notification_deliveries',1,'{}'),
('P-CN-02',3,'Theo dõi health, phục hồi thử hằng quý','it_engineer','CNTB','/api/health; scripts/restore-drill.sh; ghi ICFS 6.4','/tuan-thu','Restore đúng đếm','compliance_checks',720,'{}'),
-- CT-01..07 cây trồng
('P-CT-01',1,'Đánh giá ô: cao trình, ngập, đất, tưới','tech_head','TT','plots: elevation_tier, area, geom','/ban-do, /quan-tri?t=plots','Ô có tọa độ & diện tích','plots',168,'{GPS/máy đo}'),
('P-CT-01',2,'Lập luân canh & phân ô theo vụ (K → sinh khối)','tech_head','TT','crop_seasons KE_HOACH cho từng ô','/canh-tac','Đủ sinh khối theo K','crop_seasons',72,'{}'),
('P-CT-01',3,'Duyệt kế hoạch mùa vụ','director','GDT','season_plans duyệt','/phe-duyet','Ngân sách vật tư','season_plans',48,'{}'),
('P-CT-02',1,'Đặt mua/nhập giống theo kế hoạch','accountant','CCU','PO giống, COA/chứng nhận giống','/ke-toan › PO','Giống có nguồn gốc','purchase_orders',72,'{}'),
('P-CT-02',2,'Nhận giống, kiểm tra nảy mầm/độ sạch, nhập kho K1/K2','worker','CCU','inventory_moves NHAP_MUA lô giống','/kho','Tỷ lệ nảy mầm ≥85%','inventory_moves',24,'{}'),
('P-CT-02',3,'Ươm / gieo, ghi nhật ký','worker','TT','crop_logs GIEO, xuất kho giống','/ca A6','Đúng mật độ','crop_logs',24,'{Máy gieo,Khay ươm}'),
('P-CT-03',1,'Lịch tưới theo ẩm đất/thời tiết','tech_head','TT','feed từ sensor_reads soil_moist; tasks tưới','/canh-tac','Ẩm đất trong ngưỡng','tasks',24,'{Cảm biến ẩm,Bơm}'),
('P-CT-03',2,'Bón phân hữu cơ (compost khu D) / vôi theo phân tích đất','worker','TT','crop_inputs kind PHAN_HUU_CO/VOI, xuất kho','/canh-tac › Vật tư','Chỉ đầu vào được phép','crop_inputs',24,'{Máy rải phân}'),
('P-CT-03',3,'Ghi nước tưới m³ & điện bơm','worker','TT','crop_logs TUOI water_m3; sensor kwh','/ca A6','m³/kg mục tiêu','crop_logs',24,'{Đồng hồ nước}'),
('P-CT-04',1,'Giám sát sâu bệnh (bẫy, quan sát) & ngưỡng IPM','worker','TT','crop_logs GIAM_SAT, ảnh','/ca A6','Ngưỡng hành động IPM','crop_logs',24,'{Bẫy dính,Lúp}'),
('P-CT-04',2,'Ưu tiên biện pháp sinh học/thiên địch','tech_head','TT','crop_inputs kind SINH_HOC','/canh-tac','Hữu cơ: không hóa chất tổng hợp','crop_inputs',24,'{}'),
('P-CT-04',3,'Phun BVTV (nếu buộc phải): thuốc trong danh mục, PHI, PPE, thời tiết','worker','TT','crop_inputs THUOC_BVTV phi_days → safe_after; khóa thu hoạch','/canh-tac › Vật tư','PHI tự chặn thu hoạch','crop_inputs',4,'{Bình phun,PPE}'),
('P-CT-04',4,'Xử lý bao bì thuốc & ghi sổ BVTV','worker','TT','batch_logs/inventory_moves bao bì; hồ sơ','/kho','Bể chứa bao bì riêng','inventory_moves',24,'{}'),
('P-CT-05',1,'Kiến thiết cơ bản: trồng, tưới, tạo tán (năm 1–3)','worker','TT','crop_seasons LAU_NAM; crop_logs KTCB','/canh-tac','Tỷ lệ sống ≥95%','crop_logs',720,'{Kéo tỉa}'),
('P-CT-05',2,'Kinh doanh: ra hoa, đậu quả, bao trái, thu theo vụ','worker','TT','crop_logs; harvests','/canh-tac › Thu hoạch','PHI, kích cỡ','harvests',24,'{}'),
('P-CT-05',3,'Đánh giá năng suất/cây, quyết định tái canh','tech_head','TT','v_crop_dossier; season KET_THUC','/canh-tac','kg/cây vs chuẩn','crop_seasons',720,'{}'),
('P-CT-06',1,'Tiếp nhận lô thu hoạch, cân, phân loại','worker','D5','harvests grade; weigh','/kho','Nhiệt độ/độ ẩm sản phẩm','harvests',2,'{Cân,Bàn phân loại}'),
('P-CT-06',2,'Rửa/sơ chế/đóng gói hoặc ủ chua (K3)','worker','D5','batch_logs; inventory_moves K2/K3/K5/K6','/ca A7','Nước rửa đạt; hao hụt ≤5%','batch_logs',8,'{Bồn rửa,Máy băm}'),
('P-CT-06',3,'Nhập kho lạnh/khô theo lô, tem QR','worker','CCU','inventory_moves với lot_id; nhãn','/kho, /in-an nhãn lô','FEFO','inventory_moves',2,'{Máy in nhãn}'),
('P-CT-07',1,'Chuẩn bị giá thể/phôi nấm/dung dịch','worker','TT','crop_seasons NAM/RAU_NHA_MANG; crop_inputs','/canh-tac','pH/EC dung dịch','crop_inputs',24,'{Bút đo EC/pH}'),
('P-CT-07',2,'Theo dõi vi khí hậu nhà màng, thu theo lứa','worker','TT','sensor_reads T/RH; harvests','/canh-tac','Nhiệt/ẩm trong ngưỡng','harvests',24,'{Cảm biến T/RH}'),
-- D5-02 chế biến HACCP
('P-D5-02',1,'Nhận nguyên liệu: kiểm ngưng thuốc/PHI, nhiệt độ, COA','worker','D5','checklist_runs tiếp nhận; lots','/ca A7','Từ chối nếu chưa hết ngưng thuốc','checklist_runs',2,'{Nhiệt kế}'),
('P-D5-02',2,'Chế biến theo công thức, giám sát CCP (nhiệt/thời gian/pH)','worker','D5','batch_logs ccp_readings, temp_c','/ca A7','CCP trong giới hạn; lệch → dừng','batch_logs',4,'{Nhiệt kế đầu dò,Đồng hồ}'),
('P-D5-02',3,'Đóng gói, tem GS1/QR, kho lạnh, log nhiệt','worker','D5','lots + inventory_moves K6; sensor temp','/kho','Nhiệt kho lạnh ≤4°C','inventory_moves',2,'{Máy in nhãn,Cảm biến kho lạnh}'),
('P-D5-02',4,'Vệ sinh sau ca & hiệu chuẩn cân định kỳ','worker','D5','checklist_runs vệ sinh; calibrations','/ca A7, /thiet-bi','Đúng lịch','calibrations',24,'{Bộ quả cân}'),
-- DL-03 tour
('P-DL-03',1,'Mở lịch tour/trải nghiệm, phân HDV','team_lead','DL','hosp_tours','/du-lich › Tour','Khu được phép vào (ATSH)','hosp_tours',24,'{}'),
('P-DL-03',2,'Bán vé, thu tiền','worker','DL','hosp_tour_bookings + folio THANH_TOAN','/du-lich','Đúng sức chứa','hosp_folio',1,'{POS}'),
('P-DL-03',3,'Dẫn tour theo ATSH, bán chéo sản phẩm, lấy phản hồi','worker','DL','pos_receipts; customer_messages','/ban-hang?tab=pos','Sát trùng giày/tay','pos_receipts',4,'{Ủng,Nước sát trùng}'),
-- KD-01 CRM
('P-KD-01',1,'Nhận lead (hội chợ/web/Zalo/tham quan)','worker','KDM','crm_leads MOI','/ban-hang?tab=crm','Phản hồi ≤24h','crm_leads',24,'{}'),
('P-KD-01',2,'Liên hệ, khảo sát nhu cầu, gửi mẫu/báo giá','worker','KDM','crm_activities; giai đoạn BAO_GIA','/ban-hang?tab=crm','Giá ≥ sàn','crm_activities',72,'{}'),
('P-KD-01',3,'Đàm phán → thắng: tạo đối tác, hạn mức tín dụng, HĐ','director','KDM','partners + contracts','/ban-hang?tab=hd','Duyệt hạn mức','contracts',72,'{}'),
-- KD-03 POS
('P-KD-03',1,'Mở ca, kiểm két, kiểm tồn quầy','worker','KDM','pos_shifts MO','/ban-hang?tab=pos','Két đầu ca ghi','pos_shifts',1,'{POS,Két}'),
('P-KD-03',2,'Bán: quét/chọn hàng, khuyến mãi, thanh toán (TM/QR)','worker','KDM','pos_receipts → sales tự sinh','/ban-hang?tab=pos','Đúng giá bảng','pos_receipts',1,'{Máy quét QR,VietQR}'),
('P-KD-03',3,'Chốt ca: đếm két, chênh lệch, nộp tiền','worker','KDM','pos_shifts DONG diff','/ban-hang?tab=pos','Chênh = 0','pos_shifts',1,'{}'),
-- KD-04 nhận nuôi
('P-KD-04',1,'Tư vấn gói, ký HĐ, chọn cá thể, thu tiền','worker','KDM','create_custody; sales','/ban-hang?tab=nhan-nuoi','Cá thể đủ điều kiện','custody_contracts',48,'{}'),
('P-KD-04',2,'Cập nhật ảnh/sự kiện hằng tuần, giờ live','worker','KTCN','animal_events + photos; portal /khach','/dan','≥1 cập nhật/tuần','animal_events',168,'{Điện thoại,Camera}'),
('P-KD-04',3,'Trả lời tin nhắn khách, gia hạn/kết thúc','worker','KDM','customer_messages reply; HĐ end_option','/ban-hang?tab=nhan-nuoi','Trả lời ≤24h','customer_messages',24,'{}'),
-- KHO-01..03
('P-KHO-01',1,'Đánh giá NCC mới: pháp lý, COA, tham quan','accountant','CCU','partners approved=false → hồ sơ documents','/quan-tri?t=partners','Đủ hồ sơ','documents',168,'{}'),
('P-KHO-01',2,'Duyệt NCC, hạn mức, kỳ review','director','CCU','partners approved, review_due','/phe-duyet','≤35%/nguồn','partners',72,'{}'),
('P-KHO-01',3,'Đánh giá định kỳ (chất lượng, đúng hạn, giá)','accountant','CCU','review_due; NC nếu vi phạm','/quan-tri?t=partners','Điểm ≥ ngưỡng','partners',2160,'{}'),
('P-KHO-02',1,'Lập lịch kiểm kê (K4–K6 tuần, K1–K3 tháng), in biên bản BM09','worker','CCU','tasks KIEM_KE; /in-an BM','/kho › Kiểm kê','2 người đếm','tasks',24,'{}'),
('P-KHO-02',2,'Đếm/cân thực tế theo lô, chụp ảnh','worker','CCU','stocktakes','/kho › Kiểm kê','Đếm mù (không xem sổ)','stocktakes',4,'{Cân}'),
('P-KHO-02',3,'Chênh lệch → phiếu điều chỉnh có duyệt → GL','tech_head','KTCN','adjustments; approve','/phe-duyet','Chênh ≤1%','adjustments',24,'{}'),
('P-KHO-03',1,'Nhập kho lạnh: nhiệt độ lô, vị trí, FEFO','worker','CCU','inventory_moves K6; sensor temp','/kho','≤4°C','inventory_moves',1,'{Nhiệt kế}'),
('P-KHO-03',2,'Theo dõi nhiệt liên tục, cảnh báo lệch','it_engineer','CNTB','sensor_reads → alert sensor-off/ngưỡng','/thiet-bi','Log 24/7','sensor_reads',1,'{Cảm biến kho lạnh}'),
('P-KHO-03',3,'FEFO đỏ: hạ giá/chế biến/hủy có biên bản','team_lead','CCU','lots status; inventory_moves HUY','/kho','FEFO đỏ = 0','inventory_moves',24,'{}'),
-- KT-04 cân
('P-KT-04',1,'Lịch cân 30 ngày (vòng theo dõi) → việc','worker','KTCN','tasks THEO_DOI CAN30','/dan › Vòng theo dõi','Đúng lịch','tasks',24,'{}'),
('P-KT-04',2,'Cân từng con (BLE/tay), ghi CAN','worker','KTCN','animal_events CAN value','/ca A2','ADG tính tự động','animal_events',2,'{Cân bò,BLE}'),
('P-KT-04',3,'Phân loại lại lớp (vỗ béo/xuất) theo ADG','tech_head','KTCN','animals.class_code; PHAN_LOAI','/dan','ADG ≥0,8','animal_events',24,'{}'),
-- NS-01..04
('P-NS-01',1,'Vào ca: chấm công (vị trí), nhận việc','worker','HCNS','attendance check-in; tasks','/nhan-su, /ca','Đúng giờ','attendance',1,'{Điện thoại}'),
('P-NS-01',2,'Checklist đầu/cuối ca theo SOP vị trí','worker','HCNS','checklist_runs','/ca','Xanh hết mới giao ca','checklist_runs',1,'{}'),
('P-NS-01',3,'Giao ca: ghi chú, việc dở dang, ra ca','team_lead','HCNS','shift_notes; attendance check-out','/ca','Người nhận xác nhận','shift_notes',1,'{}'),
('P-NS-02',1,'Xác định SOP theo vị trí, lịch đào tạo','tech_head','QA','positions_catalog.sops; tasks DAO_TAO','/nhan-su','Đủ trước khi vào ca','tasks',168,'{}'),
('P-NS-02',2,'Đào tạo, kiểm tra, cấp chứng chỉ (sop_certs)','tech_head','QA','staff.sop_certs; documents','/quan-tri?t=staff','Đạt ≥80%','staff',24,'{}'),
('P-NS-02',3,'Khám SK, tập huấn ATTP định kỳ, nhắc hạn','director','HCNS','staff.health_check_due; alert','/nhan-su','Còn hạn 100%','staff',8760,'{}'),
('P-NS-03',1,'Chốt KPI tháng từ bản ghi (tự tính)','accountant','TCKT','compute_staff_kpi → v_staff_kpi_month','/nhan-su › KPI→lương','Ngày 1','kpi_results',24,'{}'),
('P-NS-03',2,'Tính bảng lương (công × cơ bản + KPI + phụ cấp − BH − thuế − tạm ứng)','accountant','TCKT','compute_payroll','/nhan-su › Bảng lương','Đủ chấm công','payslips',24,'{}'),
('P-NS-03',3,'Duyệt & hạch toán, chuyển khoản, phát phiếu lương','director','TCKT','approve_payroll → GL; /in phieu-luong','/nhan-su, /phe-duyet','Không tự duyệt','payroll_runs',48,'{}'),
('P-NS-04',1,'Tuyển: đăng, phỏng vấn, thử việc','director','HCNS','documents CV; staff active=false','/quan-tri?t=staff','Đúng định biên','staff',336,'{}'),
('P-NS-04',2,'HĐLĐ, hồ sơ, tài khoản/PIN, phân trại, dept','director','HCNS','create_staff; assign_staff_farm','/hq?tab=cty','must_change_pin','staff',24,'{}'),
('P-NS-04',3,'Nghỉ việc: bàn giao, thu hồi quyền, quyết toán','director','HCNS','active=false; revoke_sessions; payroll cuối','/quan-tri?t=staff','Bàn giao xong','staff',72,'{}'),
-- QT-01/02
('P-QT-01',1,'Sổ rủi ro & kịch bản (dịch, lũ, cháy, mất điện, mất mạng)','director','GDT','sops kịch bản; funds THIEN_TAI','/sop','Diễn tập quý','sops',2160,'{}'),
('P-QT-01',2,'Sự cố xảy ra: báo ≤24h, cách ly/ứng phó, ghi incident','worker','GDT','incidents + event incident.created','/ca, /gd','Mức CAO báo chủ','incidents',1,'{}'),
('P-QT-01',3,'5-why, CAPA, đóng, cập nhật SOP','tech_head','QA','incidents five_why, capa, closed_at','/gd','Đóng ≤7 ngày','incidents',168,'{}'),
('P-QT-02',1,'Tuần: báo cáo chủ tự gửi (thứ 2 07:00)','it_engineer','CNTB','report_schedules weekly → notifications/email','/ke-toan','Đúng hạn','notifications',168,'{}'),
('P-QT-02',2,'Tháng: đóng sổ, P&L, ngân sách–thực tế, gửi BGĐ','accountant','TCKT','period_locks; v_pl_cc_month; report pl-thang','/ke-toan','Ngày 5','journal_entries',720,'{}'),
('P-QT-02',3,'Quý: TT66, thuế, môi trường, ICFS, gói audit','accountant','TCKT','/api/exports tt66, sales-tax, audit-pack; compliance','/audit, /tuan-thu','sha256 lưu','audit_log',2160,'{}'),
-- SH-01/02, SX-01..04
('P-SH-01',1,'Thu gom phân/phụ phẩm, cân, ghi mẻ vào','worker','SH','batch_logs inputs (kg)','/ca A4','Kg vào khớp định mức đàn','batch_logs',2,'{Xe gom,Cân}'),
('P-SH-01',2,'Vận hành trùn/BSF/biogas/compost theo SOP (nhiệt, ẩm, đảo)','worker','SH','batch_logs temp/moisture; sensor','/ca A4','Nhiệt compost 55–65°C','batch_logs',24,'{Nhiệt kế đo đống ủ}'),
('P-SH-01',3,'Thu sản phẩm (phân trùn/ấu trùng/khí/compost) → kho/ruộng/D5','worker','SH','batch_logs outputs; inventory_moves','/kho','Tỷ lệ tuần hoàn','inventory_moves',24,'{}'),
('P-SH-02',1,'Quan trắc nước thải/khí theo giấy phép (tần suất)','it_engineer','CNTB','sensor_reads / lab_samples NUOC','/so-lieu','QCVN','lab_samples',720,'{Cảm biến,Lab}'),
('P-SH-02',2,'Báo cáo môi trường định kỳ, lưu hồ sơ','tech_head','SH','documents; export table:sensor_reads','/audit','Đúng hạn','documents',2160,'{}'),
('P-SX-01',1,'Cắt/thu sinh khối đúng độ chín (bắp sáp)','worker','TT','harvests','/canh-tac','Ẩm 65–70%','harvests',24,'{Máy cắt}'),
('P-SX-01',2,'Băm 1–2 cm, nén hố/bao, bọc kín, ghi mẻ','worker','D5','batch_logs U_CHUA; inventory_moves K3','/ca A1','Nén đủ, kín khí','batch_logs',8,'{Máy băm,Máy nén}'),
('P-SX-01',3,'Theo dõi pH sau 21 ngày, mở dùng, ghi hao hụt','tech_head','D5','batch_logs qc pH; xuất K3','/kho','pH ≤4,2','batch_logs',504,'{Bút pH}'),
('P-SX-02',1,'Lệnh SX từ đơn hoặc kế hoạch','team_lead','D5','production_orders','/ke-hoach','Nguyên liệu hết ngưng thuốc/PHI','production_orders',24,'{}'),
('P-SX-02',2,'Chế biến theo công thức + CCP, QC lô','worker','D5','batch_logs; checklist_runs; lots','/ca A7','QC đạt','batch_logs',8,'{}'),
('P-SX-02',3,'Giá thành mẻ, nhập kho thành phẩm','accountant','TCKT','v_batch_cost; inventory_moves K5/K6','/ke-hoach','đ/kg vs sàn','inventory_moves',24,'{}'),
('P-SX-03',1,'Tạo lô, in nhãn QR/GS1, đóng gói','worker','D5','lots; /in-an nhãn lô','/truy-xuat','Nhãn đúng lô','lots',2,'{Máy in nhãn}'),
('P-SX-03',2,'Nhập kho lạnh theo lô, log nhiệt','worker','CCU','inventory_moves K6','/kho','FEFO','inventory_moves',1,'{}'),
('P-SX-04',1,'Nạp biogas, theo dõi áp/khí, phát điện','worker','SH','batch_logs BIOGAS; sensor biogas_m3, kwh','/ca A4','An toàn khí','sensor_reads',24,'{Đồng hồ khí}'),
('P-SX-04',2,'Ủ compost, kiểm nhiệt/độ chín, xuất ra ruộng','worker','SH','batch_logs COMPOST; inventory_moves','/kho','Chín ≥45 ngày','inventory_moves',1080,'{}'),
-- TB-01 IoT
('P-TB-01',1,'Lắp cảm biến, khai báo devices, khóa API gateway','it_engineer','CNTB','devices; api_keys scope ingest','/thiet-bi, /quan-tri?t=api_keys','Đủ metadata','devices',24,'{Gateway}'),
('P-TB-01',2,'Ingest dữ liệu (HTTP/MQTT bridge), ngưỡng cảnh báo','it_engineer','CNTB','POST /api/ingest/sensor; alert_rules','/canh-bao','Off ≤1%','sensor_reads',1,'{}'),
('P-TB-01',3,'Bảo trì/hiệu chuẩn cảm biến định kỳ','worker','CNTB','calibrations; tasks','/thiet-bi','Đúng lịch','calibrations',720,'{}'),
-- TC-02..04
('P-TC-02',1,'Nhập sao kê ngân hàng, đối chiếu RC10','accountant','TCKT','/api/import/bank; recon_results','/ke-toan','Khớp 100%','bank_statement_lines',48,'{}'),
('P-TC-02',2,'Chi phí cố định theo CC, khấu hao, giá vốn','accountant','TCKT','cc_fixed_costs; run_depreciation; v_pl_cc_month','/ke-toan','Đủ CC','cc_fixed_costs',72,'{}'),
('P-TC-02',3,'Khóa kỳ, xuất báo cáo (P&L, cân đối, thuế)','director','TCKT','lock_period; exports','/ke-toan, /audit','Ngày 5','period_locks',24,'{}'),
('P-TC-03',1,'Lập ngân sách năm/tháng theo CC','accountant','TCKT','budgets','/ke-toan › Ngân sách','Duyệt HĐQT','budgets',168,'{}'),
('P-TC-03',2,'Trích quỹ (thiên tai/bảo dưỡng/đào tạo/marketing) theo tỷ lệ','accountant','TCKT','funds; journal_entries','/ke-toan','Đúng %','funds',720,'{}'),
('P-TC-03',3,'Theo dõi vượt ngân sách → cảnh báo, giải trình','director','BGD','v_budget_vs_actual; alerts','/ke-toan','Vượt = 0','budgets',720,'{}'),
('P-TC-04',1,'Tính giá thành theo CC/SKU/mẻ','accountant','TCKT','v_pl_cc_month; v_batch_cost','/ke-toan, /ke-hoach','Đủ chi phí','journal_entries',720,'{}'),
('P-TC-04',2,'Cập nhật giá sàn/niêm yết, giá chuyển nội bộ 70%','director','TCKT','price_list SAN/NIEM_YET','/quan-tri?t=price_list','Biên ≥ mục tiêu','price_list',720,'{}'),
-- TT-01/03
('P-TT-01',1,'Đọc đàn dự kiến & K → nhu cầu sinh khối/năm','tech_head','TT','herd_daily; season_plans','/ke-hoach','Ngày-tồn ≥60','season_plans',168,'{}'),
('P-TT-01',2,'Phân ô/giống/lịch gieo, nhu cầu vật tư & nhân công','tech_head','TT','crop_seasons KE_HOACH; PO','/canh-tac','Trước vụ 30 ngày','crop_seasons',72,'{}'),
('P-TT-03',1,'Lấy mẫu đất/nước theo vùng, gửi lab','worker','TT','lab_samples DAT/NUOC','/quan-tri?t=lab_samples','Mỗi vùng ≥1/năm','lab_samples',24,'{Bộ lấy mẫu}'),
('P-TT-03',2,'Nhập kết quả, so QCVN, quyết định cải tạo','tech_head','TT','lab_samples results/verdict','/quan-tri?t=lab_samples','Đạt/không đạt','lab_samples',336,'{}'),
-- VN-01..10
('P-VN-01',1,'Xem cơ cấu lớp hiện tại vs mục tiêu (bê/tơ/SS/vỗ béo/đực)','tech_head','KTCN','v_obj_animals; animal_classes','/doi-tuong','Đúng tỷ lệ','season_plans',168,'{}'),
('P-VN-01',2,'Kế hoạch mua giống/loại thải/xuất bán năm','director','BGD','season_plans; PO giống','/ke-hoach','Ngân sách','season_plans',168,'{}'),
('P-VN-02',1,'Đưa lô vào khu cách ly, treo bảng, việc theo dõi ngày','worker','KTCN','CACH_LY_VAO; tasks','/dan','Khu riêng','animal_events',2,'{}'),
('P-VN-02',2,'Theo dõi 21 ngày: nhiệt, ăn, phân, bệnh','worker','KTCN','animal_events BENH/GHI_CHU','/ca A5','Không dấu hiệu','animal_events',24,'{Nhiệt kế}'),
('P-VN-02',3,'Kết thúc cách ly, nhập đàn chính thức, gán chuồng','tech_head','KTCN','CACH_LY_RA; CHUYEN','/dan','KTT xác nhận','animal_events',24,'{}'),
('P-VN-03',1,'Định mức theo lớp (norms) → kế hoạch khẩu phần ngày','tech_head','KTCN','norms TA_KG_*; gen_feed_plans','/ke-hoach','KH có duyệt','feed_plans',24,'{}'),
('P-VN-03',2,'Phát ăn theo KH, ghi thực tế & ăn thừa','worker','D5','feed_logs; AN_THUA','/ca A1','Sai lệch ≤5%','feed_logs',1,'{}'),
('P-VN-03',3,'Xem KH vs thực, điều chỉnh công thức/định mức','tech_head','KTCN','v_feed_plan_vs_actual','/ke-hoach','Tuần','feed_plans',168,'{}'),
('P-VN-04',1,'Quyết định chuyển (giai đoạn/bệnh/xuất), kiểm sức chứa','team_lead','KTCN','locations.capacity; v_location_summary','/dan','Không quá sức chứa','animal_events',24,'{}'),
('P-VN-04',2,'Ghi CHUYEN cho từng con/đàn (quét thẻ), cập nhật vị trí','worker','KTCN','animal_events CHUYEN; bulk_move_animals','/dan','100% cập nhật','animal_events',2,'{Máy đọc RFID}'),
('P-VN-05',1,'Cổng: sát trùng xe/người, sổ khách','worker','CCU','gate_logs anolyte_wash','/ca A10','Mọi xe','gate_logs',1,'{Hố sát trùng}'),
('P-VN-05',2,'Checklist ATSH hằng ngày theo khu (giày, quần áo, dụng cụ)','worker','KTCN','checklist_runs ATSH','/ca','Xanh hết','checklist_runs',24,'{}'),
('P-VN-05',3,'Khách tham quan theo lối riêng, khu cho phép','worker','DL','hosp_tours; locations','/du-lich','Không vào khu cách ly','hosp_tours',24,'{}'),
('P-VN-06',1,'Lịch vaccine theo tuổi/mùa (vaccine_schedules) → việc','tech_head','KTCN','tasks VACCINE (monitoring)','/thu-y','Đúng lịch','tasks',24,'{}'),
('P-VN-06',2,'Xuất vaccine K1 (lạnh, lô, hạn), tiêm, ghi lô','worker','KTCN','inventory_moves; animal_events VACCINE detail.lot','/ca A2','Chuỗi lạnh','animal_events',2,'{Tủ lạnh vaccine,Kim tiêm}'),
('P-VN-06',3,'Sổ vaccine, xuất cho thú y/QA','tech_head','KTCN','medicine-book','/thu-y','Đầy đủ','animal_events',24,'{}'),
('P-VN-07',1,'Chết: ghi nguyên nhân, ảnh, báo KTT','worker','KTCN','animal_events CHET detail.cause','/ca A2','Báo ≤2h','animal_events',2,'{}'),
('P-VN-07',2,'Xử lý xác theo quy định (chôn/đốt/compost) có biên bản','worker','SH','batch_logs/incidents','/ca A4','Đúng luật thú y','incidents',24,'{}'),
('P-VN-07',3,'Loại thải/xuất bán: cân, giá, HĐ, giảm sổ đàn','team_lead','KTCN','animal_events LOAI/XUAT; sales; K8 tự giảm','/dan, /ban-hang','Hết ngưng thuốc','sales',24,'{Cân}'),
('P-VN-08',1,'Úm gà con: nhiệt, ánh sáng, nước, vaccine','worker','KTCN','animal_groups; animal_events; sensor T','/ca A3','Nhiệt úm đúng','animal_events',24,'{Đèn úm,Nhiệt kế}'),
('P-VN-08',2,'Hậu bị → đẻ: thu trứng/đếm băng chuyền, ghi hao hụt','worker','KTCN','SO_LUONG eggs_counted; CHET','/ca A3','Tỷ lệ đẻ','animal_events',24,'{Băng chuyền trứng}'),
('P-VN-08',3,'Trứng nhập K5, phân loại, loại đàn cuối chu kỳ (all-out)','worker','CCU','inventory_moves SKU-TRUNG; animal_groups status','/kho','All-in/all-out','inventory_moves',24,'{}'),
('P-VN-09',1,'Chuẩn bị bể/ao, thả giống, mật độ','worker','KTCN','animal_groups; THA_GIONG','/dan','Mật độ chuẩn','animal_events',24,'{}'),
('P-VN-09',2,'Đo DO/pH/NH3 (cảm biến/tay), cho ăn, xử lý nước','worker','KTCN','sensor_reads; feed_logs','/ca','DO ≥5 mg/l','sensor_reads',4,'{Máy đo DO/pH}'),
('P-VN-09',3,'Thu tỉa/thu toàn bộ, cân, bán','worker','KTCN','THU_TIA; sales','/dan, /ban-hang','Size đạt','sales',24,'{Cân,Vợt}'),
('P-VN-10',1,'Vắt sữa 2 lần/ngày, vệ sinh bầu vú, ghi kg','worker','KTCN','animal_events VAT_SUA','/ca A2','SCC','animal_events',12,'{Máy vắt}'),
('P-VN-10',2,'Lọc, làm lạnh, nhập kho lạnh/chế biến','worker','D5','inventory_moves K6; batch_logs','/kho','≤4°C trong 2h','inventory_moves',2,'{Bồn lạnh}'),
-- XNK-02 nhập khẩu
('P-XNK-02',1,'Xin/kiểm giấy phép nhập (giống/TACN/thuốc/máy)','director','XNK','import_permits','/xnk › Giấy phép nhập','Còn hạn','import_permits',720,'{}'),
('P-XNK-02',2,'HĐ ngoại, vận chuyển, bảo hiểm','director','XNK','trade_contracts NHAP; shipments','/xnk','Incoterm rõ','trade_contracts',168,'{}'),
('P-XNK-02',3,'Kiểm dịch/thông quan, landed cost, nhập kho hoặc lô nhập đàn (cách ly)','accountant','CCU','customs_declarations; apply_landed_cost; inventory_moves/intake_herd','/xnk, /dan','Thông quan đúng hạn','customs_declarations',168,'{}')
on conflict (process_code, step_no) do update set name=excluded.name, actor_role=excluded.actor_role, dept_code=excluded.dept_code, action=excluded.action, system_where=excluded.system_where, control=excluded.control, form_table=excluded.form_table, sla_hours=excluded.sla_hours, tools=excluded.tools;
update processes p set visible_depts = (select array_agg(distinct x) from (select unnest(coalesce(p.visible_depts,'{}')) as x union select ps.dept_code from process_steps ps where ps.process_code=p.code and ps.dept_code is not null and ps.dept_code<>'*') u), coverage='DA_CO' where exists (select 1 from process_steps ps where ps.process_code=p.code);
