-- 0042 · THƯ VIỆN QUY TRÌNH CHUẨN THEO BỘ GỐC (Quyển 3 §15): 8 chuỗi L1 · 66 quy trình L2 · ~420 SOP L3 (mỗi L3 = 1 bước quy trình + 1 mục thư viện SOP) · 12 điểm giao nhận SLA
-- Mã L2: SOP-[BỘ PHẬN]-[NN]; SOP L3: SOP-[BỘ PHẬN]-[NN].[k]. Bộ phận: BO GA DE RAS TOM TT SH NAM CB KD RS HC CN AT
alter table sops add column if not exists version int default 1, add column if not exists std_clauses text[] default '{}', add column if not exists owner_role text, add column if not exists l2_code text, add column if not exists l3_no int, add column if not exists tools text, add column if not exists frequency text, add column if not exists pass_criteria text, add column if not exists evidence text, add column if not exists safety text, add column if not exists video_url text, add column if not exists published_at timestamptz, add column if not exists published_by text, add column if not exists review_due date, add column if not exists ccp bool default false, add column if not exists ccp_limit text, add column if not exists ccp_action text;
alter table processes add column if not exists l1_chain text, add column if not exists organ text, add column if not exists sop_count int;
create temp table _l2(code text, organ text, dept text, l1 text, name text, n int, obj text, ui text, tools text, recv text, give text, evidence text, sops text[]);
insert into _l2 values
-- ===== BÒ (67) =====
('SOP-BO-01','BO','KTCN','CHUOI_BO','Nhập đàn – cách ly 21 ngày',6,'VAT_NUOI','/dan','Máy đọc RFID, cân lối đi, hố sát trùng','Kho: thuốc/vaccine; KD: lệnh mua; Cổng: giấy kiểm dịch','FMS: cá thể mới; Chuồng: bò nhập chính thức','EVENT_ANIMAL từng con; giấy thú y ký', array['Tiếp nhận xe & giấy kiểm dịch, sát trùng','Xuống bò, cân, gắn thẻ tai/RFID, tạo mã cá thể','Đưa vào chuồng cách ly, treo bảng lô','Theo dõi hằng ngày: nhiệt độ, ăn, phân, triệu chứng','Tẩy ký sinh trùng & vaccine đầu vào theo phác đồ','Kết thúc cách ly: kiểm tra, ký nhập đàn, phân chuồng']),
('SOP-BO-02','BO','KTCN','CHUOI_BO','Phối tinh nhân tạo (TTNT)',8,'VAT_NUOI','/thu-y','Vòng cổ cảm biến, súng TTNT, bình nitơ','Chuồng: bò động dục; Kho lạnh: tinh','FMS: sự kiện PHOI; Khám thai sau 35 ngày','KPI đậu thai; sổ phối', array['Phát hiện động dục (quan sát 3 lần/ngày + cảm biến)','Ghi nhận & quyết định phối (giờ, độ chín)','Chuẩn bị tinh: rã đông đúng nhiệt/thời gian, ghi lô tinh','Cố định bò, vệ sinh, dẫn tinh đúng vị trí','Ghi PHOI + lô tinh + kỹ thuật viên vào FMS','Theo dõi động dục lại 21 ngày','Phối lần 2/3, quyết định loại nếu phối hụt ≥3','Bảo quản bình nitơ: kiểm mức nitơ, sổ tinh']),
('SOP-BO-03','BO','KTCN','CHUOI_BO','Khám thai – mang thai',5,'VAT_NUOI','/thu-y','Máy siêu âm, găng khám','Sinh sản: bò đã phối','FMS: kết quả (+/−), nhóm mang thai; D5: khẩu phần cạn sữa','Sổ khám thai; % đậu thai', array['Lập danh sách khám thai 30–45 ngày sau phối','Khám (siêu âm/trực tràng), ghi kết quả + ảnh','Âm tính → quay lại theo dõi động dục','Dương tính → chuyển nhóm mang thai, khẩu phần theo giai đoạn','Cạn sữa 60 ngày trước đẻ, chuyển chuồng chờ đẻ']),
('SOP-BO-04','BO','KTCN','CHUOI_BO','Đỡ đẻ – úm bê',9,'VAT_NUOI','/dan','Bộ đỡ đẻ, canxi truyền, cân bê, đèn úm','Mang thai: bò sắp đẻ; Kho: thuốc cấp cứu','FMS: bê mới (mẹ, cân sơ sinh); Trùn: nhau/đệm','EVENT DE; tỷ lệ bê sống', array['Nhận diện dấu hiệu đẻ, chuyển ô đẻ sạch','Theo dõi đẻ, can thiệp đẻ khó theo SOP thú y','Vệ sinh bê, sát trùng rốn, cân sơ sinh','Cho bú sữa đầu ≤2h, ghi lượng','Tạo mã bê (tag_pending), gắn mẹ, ảnh','Chăm mẹ sau đẻ: nước, khẩu phần, kiểm sót nhau','Úm bê: nhiệt độ, sữa/thay thế theo lịch','Tập ăn tinh + cỏ non từ ngày 7','Xử lý nhau/đệm bẩn về khu D']),
('SOP-BO-05','BO','KTCN','CHUOI_BO','Cai sữa – phân loại 3 hướng',5,'VAT_NUOI','/dan','Cân, thẻ màu','Úm bê: bê 3–6 tháng','Nhóm: hậu bị / vỗ béo / bán giống','EVENT CAI_SUA, PHAN_LOAI', array['Đánh giá bê: cân, thể trạng, sức khỏe','Cai sữa theo lịch, giảm sữa dần 7 ngày','Phân loại 3 hướng: cái hậu bị · đực vỗ béo · bán giống','Cập nhật lớp (class_code) & chuyển chuồng','Ghi PHAN_LOAI + lý do']),
('SOP-BO-06','BO','KTCN','CHUOI_BO','Vỗ béo 3 pha',7,'VAT_NUOI','/dan','Cân lối đi, máng TMR','Cai sữa: bê đực/bò loại; D5: TMR theo pha','KD: bò đủ trọng lượng; Chế biến','ADG, FCR', array['Nhận bò vào vỗ béo, cân đầu vào, phân ô','Pha 1 thích nghi (14 ngày) khẩu phần tăng dần','Pha 2 tăng trọng: TMR vỗ béo, cân 30 ngày','Pha 3 hoàn thiện: điều chỉnh tinh, kiểm ADG','Theo dõi bệnh chân/tiêu hóa, xử lý sớm','Quyết định xuất bán khi đạt trọng lượng mục tiêu','Đánh giá lứa: ADG, FCR, giá thành/kg']),
('SOP-BO-07','BO','D5','CHUOI_BO','Cho ăn TMR ngày',6,'VAT_NUOI','/ca','Xe trộn 2m³, cân, công thức FMS','D5: nguyên liệu; KTT: công thức','Chuồng: TMR đúng mã loài trước 06h/15h','FEED_LOG + ảnh máng', array['Nhận công thức mẻ theo nhóm trên app','Trộn & rải TMR (SOP-BO-07.2: thô → tinh → rỉ mật/khoáng sau cùng, 8–10 phút)','Rải đều 2 lượt, đẩy thức ăn thừa, ước % thừa','Kiểm nước uống, máng sạch','Ghi FEED_LOG kế hoạch/thực + ảnh','Báo KTT khi thừa >8% hoặc 0%']),
('SOP-BO-08','BO','KTCN','CHUOI_BO','Sức khỏe – điều trị',10,'VAT_NUOI','/thu-y','Nhiệt kế, tủ thuốc K1, phác đồ ký','Chuồng: con bệnh; Kho: thuốc theo lô','FMS: DIEU_TRI + ngưng thuốc; QA: sổ thuốc','Sổ thuốc TT66; vi phạm ngưng thuốc = 0', array['Quan sát ca: phát hiện con bất thường (ăn, đi, phân, sốt)','Cách ly con bệnh, đo nhiệt, ghi BENH + ảnh','Chẩn đoán theo phác đồ ký sẵn / gọi thú y','Xuất thuốc K1 theo lô, đúng liều theo cân nặng','Điều trị & ghi DIEU_TRI (thuốc, liều, đường, ngưng thuốc tự tính)','Theo dõi liệu trình, đánh giá đáp ứng','Kết thúc: khỏi/chuyển/loại, ghi kết quả','Chặn xuất bán đến hết ngưng thuốc (trigger)','Sát trùng ô cách ly sau điều trị','Tổng hợp sổ thuốc tháng, gửi QA/thú y']),
('SOP-BO-09','BO','KTCN','CHUOI_BO','Xuất bán – cân – kiểm dịch',6,'VAT_NUOI','/ban-hang','Cân 40T, giấy thú y','KD: lệnh xuất; Sức khỏe: hết ngưng thuốc','KD/Chế biến: bò + hồ sơ; K8 giảm','SALE, phiếu cân, giấy kiểm dịch', array['Nhận lệnh xuất từ KD, chọn con đủ điều kiện (hết ngưng thuốc)','Nhịn ăn 12h, dồn bò an toàn','Cân từng con, phiếu cân, ảnh','Giấy kiểm dịch/thú y ký, hồ sơ cá thể in','Ghi XUAT + SALE, giảm sổ đàn K8','Vệ sinh chuồng/xe sau xuất']),
('SOP-BO-10','BO','KTCN','CHUOI_BO','Vệ sinh – đệm chuồng',5,'VAT_NUOI','/ca','Máy cào, anolyte, đệm lót','Kho: đệm lót/anolyte','Trùn/Biogas: phân ≤24h','Checklist vệ sinh; NH₃', array['Cào phân ngày 2 lần, gom về điểm chuyển khu D','Bổ sung/đảo đệm lót sinh học','Phun anolyte máng/nền theo lịch','Kiểm nước sạch, ruồi, chuột','Ghi checklist vệ sinh + ảnh']),
-- ===== GÀ 2 KHỐI (30) =====
('SOP-GA-01','GA','KTCN','CHUOI_BO','Gà đẻ: nhập hậu bị',4,'VAT_NUOI','/dan','Xe chuyên dụng, cân mẫu','KD: hợp đồng giống; Cổng','Chuồng đẻ: đàn hậu bị','Lô nhập; cân mẫu', array['Chuẩn bị chuồng: khô, sát trùng, trống ≥14 ngày','Nhận gà, đếm, cân mẫu 5%, tạo đàn (lô)','Vaccine/thuốc đầu vào theo lịch','Theo dõi 7 ngày đầu, ghi hao hụt']),
('SOP-GA-02','GA','KTCN','CHUOI_BO','Gà đẻ: chăm ngày',6,'VAT_NUOI','/ca','Vít tải silo, nipple, NH₃ sensor','D5: viên; Kho: thuốc','Thu trứng; BSF: phân','FEED_LOG; % đẻ', array['Kiểm nước/nipple, thức ăn silo, ghi FEED_LOG','Quan sát đàn: bệnh, chết, nhặt gà chết ghi CHET','Kiểm nhiệt/ẩm/NH₃, thông gió','Ánh sáng theo chương trình đẻ','Vệ sinh máng, xử lý phân theo lịch','Checklist ca + ảnh']),
('SOP-GA-03','GA','KTCN','CHUOI_BO','Thu – phân loại trứng',5,'VAT_NUOI','/kho','Băng trứng, máy soi, vỉ','Chuồng đẻ','Chế biến/K5: trứng phân loại','SO_LUONG eggs; nhập K5', array['Thu trứng đúng giờ (2 lần/ngày), đếm băng chuyền','Soi loại vỡ/bẩn/dị dạng','Phân loại cỡ, xếp vỉ, ghi lô','Nhập K5, ghi tỷ lệ đẻ','Vệ sinh khu thu trứng']),
('SOP-GA-04','GA','KTCN','CHUOI_BO','Đệm lót – anolyte nước',4,'VAT_NUOI','/ca','Đệm lót, trạm anolyte','Sinh học: anolyte','BSF/Compost: đệm cũ','Ảnh đệm tuần; ppm anolyte', array['Kiểm đệm lót ẩm/vón, đảo/bổ sung','Anolyte nước uống theo ppm quy định (đo mỗi mẻ)','Thay đệm cuối lứa → BSF/compost','Ghi lịch anolyte + ảnh đệm tuần']),
('SOP-GA-05','GA','KTCN','CHUOI_BO','Loại đàn gà đẻ',3,'VAT_NUOI','/dan','Lồng, cân','KD: lệnh','KD/Chế biến: gà loại; chuồng trống','Đàn đóng; hao hụt lứa', array['Quyết định loại đàn (tỷ lệ đẻ giảm), lệnh KD','Bắt, cân, xuất, ghi giảm đàn','Trống chuồng, vệ sinh, sát trùng 14 ngày']),
('SOP-GA-06','GA','KTCN','CHUOI_BO','Gà thịt: vào lứa all-in',3,'VAT_NUOI','/dan','Đèn úm, máng úm','KD: giống','Chuồng thịt: lứa mới','Lô nhập', array['Chuẩn bị úm: nhiệt, nước, thức ăn, đệm','Nhận gà con, đếm, tạo đàn all-in','Úm 14 ngày: nhiệt, vaccine, ghi hao hụt']),
('SOP-GA-07','GA','KTCN','CHUOI_BO','Gà thịt: chăm ngày',3,'VAT_NUOI','/ca','Máng, nipple','D5: viên + BSF','Xuất lứa','FEED_LOG; cân mẫu tuần', array['Cho ăn/uống, ghi FEED_LOG','Cân mẫu tuần, ghi tăng trọng','Quan sát bệnh/chết, vệ sinh']),
('SOP-GA-08','GA','KTCN','CHUOI_BO','Gà thịt: xuất & trống chuồng 14 ngày',2,'VAT_NUOI','/ban-hang','Cân, lồng','KD: đơn','KD/Chế biến; chuồng trống','SALE; sát trùng', array['Bắt, cân, xuất all-out, ghi SALE + hồ sơ','Vệ sinh, sát trùng, trống 14 ngày, checklist']),
-- ===== DÊ (12) =====
('SOP-DE-01','DE','KTCN','CHUOI_BO','Dê: chăm – ăn phụ phẩm',5,'VAT_NUOI','/ca','Sàn cao, máng treo','TT: lá viền, thân chuối','Trùn: phân','Kiểm đếm tuần', array['Cho ăn lá viền/thân chuối/phụ phẩm, ghi FEED_LOG','Nước sạch, khoáng liếm','Kiểm sàn/phân, vệ sinh','Quan sát bệnh, tẩy KST 4 tháng','Kiểm đếm tuần, ghi']),
('SOP-DE-02','DE','KTCN','CHUOI_BO','Dê: sinh sản',4,'VAT_NUOI','/thu-y','Đực giống/tinh','Chuồng dê cái','Dê con','Sổ phối, đẻ', array['Phát hiện động dục, ghép đực/phối','Khám thai 30 ngày, ghi','Đỡ đẻ, cân dê con, tạo mã','Cai sữa, phân loại']),
('SOP-DE-03','DE','KTCN','CHUOI_BO','Dê: xuất – trình diễn resort',3,'VAT_NUOI','/du-lich','Rào 2 lớp','KD/Resort: lịch','Khách: trải nghiệm; KD: dê xuất','Nhật ký cổng', array['Chọn dê trình diễn, lịch cố định, khách không vào lõi','Xuất bán: cân, giấy thú y, SALE','Vệ sinh khu trình diễn sau khách']),
-- ===== RAS (30) =====
('SOP-RAS-01','RAS','KTCN','CHUOI_BO','RAS: cấp – xử lý nước',6,'VAT_NUOI','/thiet-bi','Drum filter, bơm, UV','Nước giếng/hồ','Bể nuôi: nước đạt','SENSOR_READ', array['Cấp nước, kiểm nguồn (pH, độ mặn, kim loại)','Vận hành lọc cơ (drum), lọc sinh học','Kiểm DO/pH/NH3/NO2 định kỳ, ghi','Xả bùn, vệ sinh lọc theo lịch','Xử lý sự cố lọc/bơm, dự phòng ắc quy sục','Nước thải → wetland/azolla đúng van']),
('SOP-RAS-02','RAS','KTCN','CHUOI_BO','RAS: thả giống',4,'VAT_NUOI','/dan','Cân, thùng vận chuyển','KD: giống; Cổng','Bể: đàn mới','Lô thả', array['Chuẩn bị bể: nước ổn định 7 ngày','Nhận giống, thuần nhiệt/độ mặn 30 phút','Đếm/cân mẫu, thả, tạo đàn','Theo dõi 3 ngày đầu, ghi hao hụt']),
('SOP-RAS-03','RAS','KTCN','CHUOI_BO','RAS: cho ăn theo cảm biến',5,'VAT_NUOI','/ca','Feeder tự động, DO meter','D5: viên; Sinh học: trùn/BSF','FEED_LOG','FCR bể', array['Tính khẩu phần theo sinh khối ước & nhiệt độ','Cho ăn nhiều bữa nhỏ, quan sát ăn','Ngừng/giảm khi DO thấp, thời tiết xấu','Ghi FEED_LOG, thức ăn thừa','Cân mẫu 2 tuần, cập nhật sinh khối']),
('SOP-RAS-04','RAS','KTCN','CHUOI_BO','RAS: quan trắc – xử lý sự cố DO/pH',7,'VAT_NUOI','/canh-bao','DO/pH sensor, ắc quy sục, oxy viên','Cảm biến','Cảnh báo; INCIDENT','Nhật ký sự cố', array['Đọc cảnh báo DO/pH/NH3 từ FMS','Xác minh tại bể bằng máy đo tay','DO thấp: bật sục dự phòng/oxy viên, ngừng ăn','pH lệch: điều chỉnh vôi/nước theo SOP','NH3 cao: thay nước một phần, giảm ăn','Ghi INCIDENT, 5-why nếu lặp','Kiểm ắc quy/máy sục dự phòng tuần']),
('SOP-RAS-05','RAS','KTCN','CHUOI_BO','RAS: thu – phân cỡ',4,'VAT_NUOI','/ban-hang','Lưới, sàng cỡ, cân','KD: đơn','Chế biến/KD: cá theo cỡ','SALE, phiếu cân', array['Nhịn ăn 24h trước thu','Thu tỉa/thu toàn bộ, sàng cỡ','Cân, ghi THU_TIA/XUAT + SALE','Cập nhật sinh khối bể']),
('SOP-RAS-06','RAS','KTCN','CHUOI_BO','RAS: vệ sinh bể anolyte',4,'VAT_NUOI','/ca','Anolyte, bàn chải','Sinh học: anolyte','Bể sạch','Checklist', array['Xả cạn bể sau vụ, cọ rửa','Phun anolyte, phơi khô','Vệ sinh ống/feeder/lọc','Ghi checklist + ảnh']),
-- ===== TÔM + BÈ SÔNG (18) =====
('SOP-TOM-01','TOM','KTCN','CHUOI_BO','Ủ rơm vi sinh đáy ao',5,'VAT_NUOI','/ca','Men vi sinh, máy quạt','Kho: rơm; Sinh học: men','Ao: đáy sẵn sàng','Nhật ký ao', array['Cải tạo đáy, phơi, vôi','Trải rơm, ủ men vi sinh theo liều','Cấp nước, gây màu','Kiểm pH/kiềm/khí độc','Ghi nhật ký ao']),
('SOP-TOM-02','TOM','KTCN','CHUOI_BO','Vụ tôm',5,'VAT_NUOI','/dan','Quạt nước, sàng ăn','KD: giống','Chế biến/KD','Nhật ký ao; FCR', array['Thả giống, thuần, mật độ','Cho ăn theo sàng, ghi','Quan trắc nước ngày, xử lý','Kiểm bệnh (đốm trắng, gan tụy), xử lý','Thu hoạch, cân, SALE']),
('SOP-TOM-03','TOM','KTCN','CHUOI_BO','Bè sông: thả – chăm',4,'VAT_NUOI','/dan','Bè, neo kép','KD: giống','Chế biến/KD','Nhật ký lồng', array['Kiểm bè/neo/lưới trước thả','Thả giống, ghi đàn','Cho ăn, vệ sinh lưới, quan sát','Thu hoạch, cân, SALE']),
('SOP-TOM-04','TOM','GDT','CHUOI_AN_TOAN','Kéo bè trú lũ',4,'VAT_NUOI','/gd','Neo kép, tàu kéo','Ban chỉ huy: lệnh R1','Bè an toàn','Lệnh R1; biên bản', array['Nhận lệnh lũ cấp R1 từ Ban chỉ huy','Gia cố/di dời bè về vị trí trú','Kiểm đàn/lưới sau di dời','Ghi biên bản, báo cáo']),
-- ===== TRỒNG TRỌT (45) =====
('SOP-TT-01','TT','TT','CHUOI_CAY','Làm đất – gieo',8,'CAY_TRONG','/canh-tac','Máy kéo + dàn, máy gieo, GPS','Sinh học: phân trùn/compost; Kho: giống','Ruộng: lô đã gieo','CROP_LOG theo lô; giờ máy', array['Mở mùa vụ trên FMS (ô, giống, nguồn giống, chứng nhận)','Kiểm mẫu đất, quyết định vôi/phân nền','Cày/bừa/lên luống theo hàng chuẩn 75 cm','Bón phân nền hữu cơ theo phân tích đất, ghi crop_inputs','Gieo/trồng đúng mật độ, ghi giống–lô','Tưới ẩm sau gieo','Ghi CROP_LOG GIEO + giờ máy + nhiên liệu','Kiểm nảy mầm 7 ngày, dặm']),
('SOP-TT-02','TT','TT','CHUOI_CAY','Chăm – tưới – drone',7,'CAY_TRONG','/canh-tac','Van tưới, ẩm kế đất, drone','Cảm biến ẩm/thời tiết; Sinh học: giấm gỗ/IMO','Ruộng: cây khỏe','CROP_LOG; NDVI 2 tuần', array['Lịch tưới theo ẩm đất/thời tiết, mở van đúng lô','Bón thúc hữu cơ/vi sinh theo giai đoạn (crop_inputs)','Giám sát sâu bệnh, ngưỡng IPM','Phun sinh học/giấm gỗ; BVTV cục bộ chỉ khi có lệnh GĐ (PHI)','Làm cỏ cơ giới/che phủ','Bay drone/NDVI 2 tuần, ghi ảnh','Ghi CROP_LOG chăm sóc + nước m³']),
('SOP-TT-03','TT','TT','CHUOI_CAY','Thu – vận chuyển',6,'CAY_TRONG','/canh-tac','Máy thu tự nạp, xe kéo, cân 40T','Ruộng: lô chín; KTT: lệnh thu','D5/hào ủ: sinh khối trong ngày','harvests + phiếu cân + mẫu ẩm', array['Xác định độ chín/ẩm (bắp sáp 65–70%)','Kiểm PHI đã qua (FMS chặn nếu chưa)','Thu hoạch bằng máy, ghi giờ máy','Vận chuyển về D5/hào ủ trong ngày, cân','Ghi harvests (kg, ẩm, lô)','Vệ sinh máy, kiểm bảo dưỡng sau vụ']),
('SOP-TT-04','TT','D5','CHUOI_CAY','Ủ chua đóng hào',6,'SAN_XUAT','/kho','Máy băm, máy nén, bạt','Ruộng: sinh khối; Kho: rỉ mật/men','K3: ủ chua đạt','BATCH_LOG; pH 21 ngày; tồn hào 60 ngày', array['Băm 1–2 cm, kiểm ẩm','Nén lớp 20–30 cm bằng máy, liên tục','Bổ sung rỉ mật/men nếu cần','Đậy bạt kín, chèn, đánh dấu hào/ngày','Theo dõi pH sau 21 ngày, ghi BATCH_LOG','Mở hào lấy dùng đúng mặt cắt, ghi xuất K3']),
('SOP-TT-05','TT','CNTB','CHUOI_CAY','Máy & bảo dưỡng',8,'THIET_BI_DU_LIEU','/thiet-bi','Đội máy, sổ giờ máy','Mọi ca: giờ máy','Máy sẵn sàng','Nhật ký bảo dưỡng; uptime', array['Kiểm tra trước ca (dầu, nước, lốp, an toàn)','Ghi giờ máy & nhiên liệu mỗi ca','Bảo dưỡng theo giờ máy (thay dầu/lọc) → việc tự sinh','Sửa chữa: work order, phụ tùng từ kho','Rửa máy, bảo quản cuối vụ','Hiệu chuẩn cân/thiết bị đo định kỳ','Nhật ký sự cố máy, 5-why','Đào tạo & chứng chỉ vận hành máy']),
('SOP-TT-06','TT','TT','CHUOI_CAY','Đồng cỏ luân phiên ô',5,'CAY_TRONG','/canh-tac','Hàng rào điện, ô cỏ','Chăn nuôi: lịch chăn thả','Chăn nuôi: ô cỏ đủ','Nhật ký ô; ngày nghỉ ô', array['Chia ô, lịch luân phiên (chăn 2–3 ngày, nghỉ 25–35)','Kiểm chiều cao cỏ trước vào','Bón phân/tưới sau khi ra','Cắt dọn cỏ già, dặm','Ghi CROP_LOG ô cỏ']),
('SOP-TT-07','TT','TT','CHUOI_CAY','Viền cau – dừa – đai chắn',5,'CAY_TRONG','/canh-tac','Kéo tỉa, thang','—','Chế biến: mo cau; Dê: lá viền','Nhật ký viền', array['Trồng/dặm viền theo bản đồ','Tưới/bón, tỉa cành, chắn gió','Thu mo cau/dừa/lá viền, ghi harvests','Kiểm sâu bệnh cây lâu năm','Ghi CROP_LOG viền']),
-- ===== SINH HỌC (36) =====
('SOP-SH-01','SH','SH','CHUOI_SINH_HOC','Trùn: nạp – ủ sơ – thu',6,'SAN_XUAT','/ca','Xe điện ben, nhiệt kế luống, máy sàng','Chuồng: phân; Nấm: bã','TT: phân trùn; D5/RAS: trùn tươi','BATCH_LOG ô', array['Ủ sơ phân ≥7 ngày, đo nhiệt <35°C','Nạp liệu luống (SOP-TR-01.3: nửa mặt luống, 5–7 cm)','Tưới ẩm 70–80%, che nắng','Kiểm mật độ trùn 3 điểm/ô tuần','Thu trùn/phân trùn bằng sàng, cân','Ghi BATCH_LOG vào/ra + ảnh']),
('SOP-SH-02','SH','SH','CHUOI_SINH_HOC','BSF chu trình',6,'SAN_XUAT','/ca','Lồng ruồi, khay ấu trùng, máy phân ly','Chế biến/Bếp: rác hữu cơ; Gà: phân+đệm','D5: đạm BSF; TT: phân','BATCH_LOG', array['Nhận rác hữu cơ đã phân loại, cân','Ấp trứng, ương ấu trùng nhỏ','Nuôi ấu trùng trên cơ chất, kiểm ẩm/nhiệt','Thu hoạch ấu trùng, phân ly','Giữ ruồi bố mẹ, thu trứng','Ghi BATCH_LOG, sản lượng đạm']),
('SOP-SH-03','SH','SH','CHUOI_SINH_HOC','Biogas + đuốc dư khí',5,'SAN_XUAT','/ca','Hầm HDPE, đồng hồ khí, đuốc','Chuồng: phân/nước rửa','CN: khí → điện/nhiệt; TT: nước sau biogas','sensor biogas_m3', array['Nạp phân/nước theo tỷ lệ, tránh sát trùng mạnh','Kiểm áp suất/khí, an toàn rò rỉ','Vận hành máy phát/bếp, ghi kWh','Đốt khí dư bằng đuốc, không xả','Xả bùn, kiểm bạt định kỳ, ghi BATCH_LOG']),
('SOP-SH-04','SH','SH','CHUOI_SINH_HOC','Compost – biochar – giấm gỗ',5,'SAN_XUAT','/ca','Máy đảo, lò than, nhiệt kế đống','Chuồng/ruộng: chất thải, phụ phẩm gỗ','TT: compost/biochar/giấm; KD','BATCH_LOG', array['Phối trộn C/N, tạo đống, ghi mẻ','Đảo đống, kiểm nhiệt 55–65°C ≥3 ngày','Ủ chín ≥45 ngày, sàng','Đốt than lò kín, thu giấm gỗ','Ghi BATCH_LOG ra, nhập kho']),
('SOP-SH-05','SH','D5','CHUOI_SINH_HOC','D5: phối trộn – ép viên',8,'SAN_XUAT','/kho','Cân định lượng, máy trộn, ép viên','TT: sinh khối; SH: đạm BSF/trùn; Kho: NVL','Mọi chuồng: khẩu phần; K4','BATCH_LOG mỗi mẻ; sai số', array['Nhận công thức theo loài/pha từ KTT','Cân định lượng từng NVL, ghi lô','Trộn theo thứ tự, thời gian chuẩn','Ép viên/nghiền theo cỡ loài','Sấy/làm nguội, kiểm ẩm','Đóng bao, tem mẻ, nhập K4','QC mẻ (ẩm, độ bền viên), lưu mẫu','Ghi BATCH_LOG + sai số']),
('SOP-SH-06','SH','SH','CHUOI_SINH_HOC','Nhân men IMO/EM + trạm anolyte',6,'SAN_XUAT','/ca','Thùng nhân men, máy điện phân, bút ppm','Kho: rỉ mật, muối','Mọi khu: men/anolyte','ppm đo mỗi mẻ', array['Nhân men IMO/EM theo công thức, ghi mẻ','Kiểm chất lượng men (mùi, pH)','Vận hành trạm anolyte, đo ppm mỗi mẻ','Cấp phát theo lịch cho các khu','Bảo trì máy điện phân/điện cực','Ghi BATCH_LOG anolyte/men']),
-- ===== NẤM (10) =====
('SOP-NAM-01','NAM','TT','CHUOI_CAY','Rơm vào – cấy meo',4,'CAY_TRONG','/canh-tac','Kệ tầng, nồi hấp','TT/kho rơm: rơm sạch','Phòng ươm','Phiếu lô', array['Nhận rơm/lõi bắp sạch, kiểm mốc','Xử lý (ủ/hấp), đóng bịch','Cấy meo, ghi lô','Ươm: nhiệt/ẩm, kiểm nhiễm']),
('SOP-NAM-02','NAM','TT','CHUOI_CAY','Chăm – hái 2 lần/ngày',3,'CAY_TRONG','/canh-tac','Phun sương','Phòng ươm','KD/Bếp: nấm','Sản lượng/kệ', array['Phun sương, thông gió, ánh sáng','Hái 2 lần/ngày, cân, ghi harvests','Sơ chế, đóng gói, giao KD/bếp']),
('SOP-NAM-03','NAM','TT','CHUOI_CAY','Bã ra trùn + vệ sinh',3,'CAY_TRONG','/ca','—','Cuối lứa','Trùn: bã ≤48h','BATCH_LOG', array['Kết lứa, gom bã, cân','Chuyển bã cho trùn ≤48h','Vệ sinh phòng, sát trùng, nghỉ chu kỳ']),
-- ===== CHẾ BIẾN (30) =====
('SOP-CB-01','CB','D5','CHUOI_CHE_BIEN','Sơ chế thịt – pha lóc',7,'SAN_XUAT','/kho','Bàn inox, dao, hút chân không','Chuồng: vật nuôi + hồ sơ kiểm dịch/ngưng thuốc','Đóng gói; BSF: phụ phẩm','Mã mẻ; CCP nhiệt', array['Tiếp nhận: kiểm hồ sơ kiểm dịch + hết ngưng thuốc (từ chối nếu thiếu)','Vệ sinh cá nhân, khu vực, dụng cụ (checklist)','Pha lóc theo quy cách, kiểm nhiệt phòng ≤12°C','Cân, ghi mẻ, tách phụ phẩm → BSF','Đóng gói hút chân không, tem mẻ','Chuyển kho lạnh ≤2h','Vệ sinh sau ca, lưu mẫu 15 ngày']),
('SOP-CB-02','CB','D5','CHUOI_CHE_BIEN','Trứng – rửa anolyte – vỉ',4,'SAN_XUAT','/kho','Bồn rửa anolyte, vỉ','Gà: trứng','K5/KD: vỉ trứng','Mã lô', array['Nhận trứng, loại vỡ/bẩn','Rửa anolyte đúng ppm, làm khô','Xếp vỉ, tem lô/hạn','Nhập K5, ghi']),
('SOP-CB-03','CB','D5','CHUOI_CHE_BIEN','Sấy (solar + lạnh)',5,'SAN_XUAT','/kho','Solar dryer, máy sấy lạnh','Ruộng/chuồng: nguyên liệu','Đóng gói','BATCH_LOG; ẩm cuối', array['Sơ chế, cắt lát đều','Xếp khay, sấy solar/lạnh theo chương trình','Kiểm ẩm cuối, aw','Làm nguội, đóng gói kín','Ghi BATCH_LOG, lưu mẫu']),
('SOP-CB-04','CB','D5','CHUOI_CHE_BIEN','Ép mo cau – than gáo',4,'SAN_XUAT','/kho','Máy ép mo, lò than','TT: mo cau, gáo dừa','KD: SKU','BATCH_LOG', array['Ngâm/làm mềm mo cau','Ép khuôn, sấy','Than gáo: đốt lò kín, phân loại','Đóng gói, tem, nhập kho']),
('SOP-CB-05','CB','D5','CHUOI_CHE_BIEN','Đóng gói – tem truy xuất',5,'SAN_XUAT','/truy-xuat','Máy in tem QR/GS1, cân','Sơ chế/sấy: bán thành phẩm','KD/Resort: SKU đủ tem + hạn','Mã mẻ trên bao bì', array['Kiểm QC bán thành phẩm','Cân định lượng, đóng gói đúng quy cách','In tem lô/QR/GS1, hạn dùng','Nhập kho thành phẩm theo lô','Ghi BATCH_LOG outputs, lưu mẫu']),
('SOP-CB-06','CB','CCU','CHUOI_CHE_BIEN','Kho lạnh – xuất dock',5,'VAT_TU_KHO','/kho','Kho lạnh, sensor nhiệt, xe lạnh','Đóng gói: SKU','KD: hàng giao','sensor nhiệt; FEFO', array['Nhập kho lạnh theo lô, vị trí','Theo dõi nhiệt liên tục, xử lý lệch','Soạn hàng FEFO theo phiếu soạn','Xuất dock: kiểm nhiệt xe, ghi','Vệ sinh kho, xả tuyết định kỳ']),
-- ===== KINH DOANH (25) =====
('SOP-KD-01','KD','KDM','CHUOI_BAN','B2B hợp đồng – bao tiêu',6,'KHACH_HANG','/ban-hang','CRM, mẫu HĐ','Chế biến: SKU + giá thành','Chế biến: đơn; TK: tiền','SALE; ≥70% có HĐ trước', array['Tìm & đánh giá khách B2B, lead','Báo giá theo giá sàn/giá thành','Ký HĐ bao tiêu (sản lượng, giá, kỳ giao)','Lập lịch giao theo HĐ, đơn tuần','Theo dõi công nợ ≤15 ngày','Đánh giá HĐ cuối kỳ']),
('SOP-KD-02','KD','KDM','CHUOI_BAN','Quầy + online',6,'KHACH_HANG','/ban-hang','POS, sàn TMĐT, Zalo','K5: SKU','Khách; TK','pos_receipts; đơn sàn', array['Mở ca POS, kiểm hàng quầy','Bán quầy: quét, KM, thanh toán VietQR','Đơn online về webhook → xác nhận, soạn, giao','Chăm sóc/đánh giá sau bán','Chốt ca, đối soát sàn/COD','Cập nhật giá/khuyến mãi']),
('SOP-KD-03','KD','KDM','CHUOI_BAN','Nhận nuôi (chăm sóc hộ)',4,'KHACH_HANG','/ban-hang','Portal /khach','Chăn nuôi: cá thể','Khách: HĐ + portal','custody_contracts', array['Tư vấn gói, chọn cá thể, ký HĐ, thu tiền','Cập nhật ảnh/sự kiện, giờ live hằng tuần','Trả lời tin nhắn ≤24h','Gia hạn/kết thúc, chia lợi ích']),
('SOP-KD-04','KD','CCU','CHUOI_BAN','Giao hàng tuyến',4,'KHACH_HANG','/kho','Xe lạnh, app tuyến','Kho: hàng soạn','Khách: hàng đúng hẹn','Xác nhận giao', array['Lập tuyến giao theo đơn/ngày','Xuất kho theo phiếu soạn, kiểm nhiệt xe','Giao, khách ký/ảnh xác nhận','Xử lý trả hàng tại chỗ']),
('SOP-KD-05','KD','KDM','CHUOI_BAN','CSKH + khủng hoảng truyền thông',5,'KHACH_HANG','/ban-hang','Hotline, Zalo','Khách: phản hồi','QA: khiếu nại; BGĐ','customer_messages', array['Tiếp nhận phản hồi/khiếu nại, ghi','Phân loại, chuyển QA (nếu chất lượng), hạn xử lý','Trả lời khách, bồi thường theo chính sách','Kịch bản khủng hoảng: 1 đầu mối phát ngôn, 24h','Tổng hợp NPS/khiếu nại tháng']),
-- ===== RESORT (34) =====
('SOP-RS-01','RS','DL','CHUOI_KHACH','Đặt – checkin tự động',5,'KHACH_HANG','/du-lich','Khóa mã, app đặt','Khách/OTA','Buồng phòng','BOOKING', array['Nhận booking (trực tiếp/OTA), xác nhận, cọc','Gửi hướng dẫn checkin, mã khóa','Nhận phòng: khai báo lưu trú, folio PHONG','Hỗ trợ trong kỳ, folio dịch vụ','Trả phòng, thanh toán, đánh giá']),
('SOP-RS-02','RS','DL','CHUOI_KHACH','Buồng phòng',4,'KHACH_HANG','/du-lich','Checklist ảnh buồng','Lễ tân: lịch','Phòng sẵn sàng','Ảnh checklist', array['Dọn phòng theo checklist ảnh sau trả','Kiểm minibar/đồ vải, báo hỏng','Sát trùng, đặt lại tiêu chuẩn','Cập nhật trạng thái phòng SAN_SANG']),
('SOP-RS-03','RS','DL','CHUOI_KHACH','F&B đặt trước',8,'KHACH_HANG','/du-lich','App đặt bàn, bếp','Chế biến/ruộng: thực phẩm','Khách: bữa; BSF: rác bếp','Lưu mẫu 24h', array['Nhận đặt bàn/menu trước, số khách','Lên kế hoạch nguyên liệu, xuất kho theo menu×pax','Sơ chế, kiểm nhiệt bảo quản','Nấu theo công thức, CCP nhiệt','Lưu mẫu 24h mỗi món','Phục vụ, ghi folio','Thu gom rác hữu cơ → BSF ngày 1 lần','Vệ sinh bếp cuối ca, checklist']),
('SOP-RS-04','RS','DL','CHUOI_KHACH','Tour vòng tuần hoàn',6,'KHACH_HANG','/du-lich','QR 12 trạm, xe điện','Chăn nuôi: khu được vào','Khách; KD: bán chéo','Vé; đánh giá', array['Mở lịch tour, phân HDV','Bán vé, thu tiền','Sát trùng giày/tay, phổ biến ATSH','Dẫn tour 12 trạm QR, không vào lõi','Bán chéo sản phẩm tại quầy','Thu phản hồi NPS']),
('SOP-RS-05','RS','DL','CHUOI_KHACH','MICE – đào tạo',6,'KHACH_HANG','/du-lich','Hội trường, checklist sự kiện','KD: HĐ tiệc/đào tạo','Học viên; nhượng quyền','hosp_events', array['Nhận yêu cầu, báo giá menu×pax/gói đào tạo','Ký/cọc, brief, checklist chuẩn bị','Chuẩn bị hội trường, F&B, tài liệu','Điều hành sự kiện/lớp học','Quyết toán, thu tiền','Đánh giá & lưu học viên (chuỗi nhượng quyền)']),
('SOP-RS-06','RS','GDT','CHUOI_AN_TOAN','An toàn khách + trẻ em',5,'KHACH_HANG','/du-lich','Biển báo, áo phao, tủ sơ cứu','—','Khách an toàn','Sự cố = 0', array['Phổ biến an toàn khi checkin (nước, động vật, máy)','Khu vực cấm, rào, biển báo, giám sát trẻ em','Tủ sơ cứu, số khẩn cấp, người trực','Xử lý sự cố khách: sơ cứu, ghi INCIDENT','Diễn tập sơ tán/PCCC với khách theo lịch']),
-- ===== HC–TC–NS (29) =====
('SOP-HC-01','HC','TCKT','CHUOI_HO_TRO','Kế toán P&L phân hệ',6,'TAI_CHINH','/ke-toan','GL, ngân hàng','Mọi nơi: chứng từ','BGĐ: P&L ngày 5','journal_entries', array['Nhận chứng từ, hạch toán (GL tự sinh + tay)','Đối chiếu ngân hàng, RC10','Chi phí cố định/CC, khấu hao','Đóng sổ, khóa kỳ ngày 5','P&L phân hệ, ngân sách–thực tế, dòng tiền','Xuất báo cáo thuế/BCTC']),
('SOP-HC-02','HC','CCU','CHUOI_HO_TRO','Mua hàng – kho vật tư',7,'VAT_TU_KHO','/kho','PO, kho mã vạch','Nhu cầu mọi phòng','Kho: hàng đúng lúc','PO; kiểm kê chéo tháng', array['Tổng hợp nhu cầu (ngày-tồn, kế hoạch)','Lập PO, chọn NCC được duyệt (≤35%)','Duyệt PO (không tự duyệt)','Nhận hàng: cân/đếm, COA, nhập kho theo lô','Xuất kho theo phiếu, FEFO','Kiểm kê chéo tháng, điều chỉnh có duyệt','Đánh giá NCC định kỳ']),
('SOP-HC-03','HC','HCNS','CHUOI_HO_TRO','Tuyển – đào tạo – chứng chỉ SOP',6,'CON_NGUOI','/nhan-su','Hồ sơ chứng chỉ','Nhu cầu nhân lực','Nhân sự đủ chứng chỉ trước khi làm','sop_certs', array['Tuyển: đăng, phỏng vấn, thử việc','HĐLĐ, hồ sơ, tài khoản/PIN, phân trại','Đào tạo SOP theo vị trí, kiểm tra','Cấp chứng chỉ nội bộ, ghi sop_certs','Khám SK/ATTP định kỳ','Đào tạo lại khi SOP đổi phiên bản']),
('SOP-HC-04','HC','HCNS','CHUOI_HO_TRO','Pháp lý – giấy phép – bảo hiểm',5,'QUAN_TRI','/hq','Sổ giấy phép','—','BGĐ: cảnh báo pháp lý','Hạn giấy phép', array['Lập sổ giấy phép/chứng nhận/bảo hiểm (hạn)','Nhắc hạn 90 ngày, gia hạn','Đính kèm hồ sơ pháp lý đất/xây dựng/MT','Bảo hiểm tài sản/vật nuôi/mùa vụ, hồ sơ bồi thường','Cập nhật văn bản pháp luật mới']),
('SOP-HC-05','HC','TCKT','CHUOI_HO_TRO','Lương – KPI – khoán',5,'CON_NGUOI','/nhan-su','KPI FMS, bảng lương','Bản ghi mọi bảng','Lương ngày 10','payslips', array['Chốt KPI tháng từ bản ghi','Tính bảng lương (công, KPI, phụ cấp, BH, thuế)','Duyệt (2 chữ ký), hạch toán','Chuyển khoản, phát phiếu lương','Xử lý khiếu nại lương']),
-- ===== CÔNG NGHỆ (28) =====
('SOP-CN-01','CN','CNTB','CHUOI_HO_TRO','FMS vận hành – phân quyền',5,'THIET_BI_DU_LIEU','/quan-tri','ITRAN OS','Yêu cầu mọi phòng','Tài khoản, dữ liệu sạch','job_runs; audit_log', array['Tạo tài khoản/vai/PIN, phân trại, khóa/mở','Theo dõi job đêm, health, backup, restore quý','Quản trị danh mục, nhập CSV, lịch sử','Xử lý sự cố phần mềm, cập nhật phiên bản','Đào tạo người dùng, hướng dẫn']),
('SOP-CN-02','CN','CNTB','CHUOI_HO_TRO','Cảm biến – hiệu chuẩn',5,'THIET_BI_DU_LIEU','/thiet-bi','Tool hiệu chuẩn, gateway','—','Dữ liệu tin cậy','calibrations', array['Lắp/khai báo cảm biến, API key gateway','Ingest, ngưỡng cảnh báo, sensor-off','Hiệu chuẩn định kỳ (cân, DO/pH, nhiệt)','Cờ dữ liệu từ thiết bị quá hạn hiệu chuẩn','Bảo trì/thay thế']),
('SOP-CN-03','CN','CNTB','CHUOI_HO_TRO','Camera – an ninh',4,'THIET_BI_DU_LIEU','/thiet-bi','Camera AI, NVR','—','Đếm đàn/an ninh','Log', array['Lắp/đặt góc camera, lưu trữ','Đếm đàn/nhận diện, đối soát sổ','Xử lý cảnh báo an ninh','Bảo trì, kiểm ổ lưu']),
('SOP-CN-04','CN','CNTB','CHUOI_HO_TRO','Drone',4,'THIET_BI_DU_LIEU','/canh-tac','Drone, pin','TT: lịch bay','TT: NDVI/phun','Log bay', array['Kế hoạch bay, giấy phép, an toàn','Bay chụp NDVI/phun theo lô','Xử lý ảnh, ghi vào lô','Bảo dưỡng pin/cánh']),
('SOP-CN-05','CN','CNTB','CHUOI_HO_TRO','Điện ĐMT – biogas – máy phát',6,'THIET_BI_DU_LIEU','/thiet-bi','Inverter, máy phát, UPS','SH: khí biogas','Toàn trại: điện ổn định','kWh; uptime ≥98%', array['Vận hành ĐMT, ghi kWh','Máy phát biogas/diesel: kiểm, chạy thử tuần','Chuyển nguồn khi mất điện, UPS','Bảo trì định kỳ inverter/ắc quy','Kiểm an toàn điện, chống sét','Ghi nhật ký điện']),
('SOP-CN-06','CN','CNTB','CHUOI_HO_TRO','Nước – anolyte – tháp',4,'THIET_BI_DU_LIEU','/thiet-bi','Bơm, tháp, bể','—','Nước sạch mọi khu','m³; test nước 2 lần/năm', array['Vận hành giếng/bơm/tháp, ghi m³','Test nước định kỳ 2 lần/năm, lưu kết quả','Bảo trì bể/đường ống, xả cặn','Phối hợp trạm anolyte']),
-- ===== AN TOÀN CHUNG (28) =====
('SOP-AT-01','AT','CCU','CHUOI_AN_TOAN','Cổng sinh học – cân – rửa xe',5,'QUAN_TRI','/ca','Trạm cân, hố khử trùng','Mọi xe/người','Cắt ngang mọi cơ quan','Nhật ký cổng 100%', array['Đăng ký xe/khách, mục đích, sổ cổng','Rửa/khử trùng xe qua hố, người qua buồng','Cân vào/ra, phiếu cân','Kiểm hàng/giấy tờ, cấm xe lạ vào lõi','Đóng cổng, báo cáo ca']),
('SOP-AT-02','AT','HCNS','CHUOI_AN_TOAN','An toàn lao động',6,'CON_NGUOI','/nhan-su','PPE, biển báo','—','Mọi vị trí','Tai nạn = 0', array['Đánh giá rủi ro vị trí, biển báo','Cấp phát/kiểm PPE, ký nhận','Huấn luyện ATLĐ định kỳ','Kiểm tra an toàn máy/điện/hóa chất','Xử lý tai nạn: sơ cứu, ghi INCIDENT, báo cáo','Điều tra 5-why, CAPA']),
('SOP-AT-03','AT','GDT','CHUOI_AN_TOAN','PCCC',4,'QUAN_TRI','/gd','Bình chữa cháy, còi, sơ đồ','—','Toàn trại','Diễn tập năm', array['Kiểm bình/họng/còi định kỳ','Sơ đồ thoát hiểm, tập kết','Diễn tập PCCC năm có biên bản','Xử lý cháy: báo động, dập, sơ tán, INCIDENT']),
('SOP-AT-04','AT','GDT','CHUOI_AN_TOAN','Lũ 3 cấp',5,'QUAN_TRI','/gd','Bản đồ ngập, bao cát, bơm','Dự báo/lệnh','Mọi cơ quan','Lệnh R1/R2/R3', array['Theo dõi dự báo, mực nước, cảnh báo cấp','R1: gia cố, di dời bè, kiểm máy phát','R2: di chuyển đàn/vật tư lên tầng cao','R3: sơ tán người, đóng trại','Sau lũ: kiểm đếm, dịch bệnh, biên bản']),
('SOP-AT-05','AT','KTCN','CHUOI_AN_TOAN','"Trại đóng" khi dịch',5,'VAT_NUOI','/gd','Lệnh đóng, sát trùng','Dịch tễ vùng/địa phương','Mọi cơ quan','Biên bản lệnh', array['Kích hoạt lệnh đóng trại (dịch vùng ĐỎ)','Cấm ra/vào, cấm khách, cấm mượn người','Sát trùng tăng cường, khu đệm','Giám sát đàn hằng ngày, báo thú y','Dỡ lệnh: điều kiện, biên bản']),
('SOP-AT-06','AT','SH','CHUOI_AN_TOAN','Xử lý xác – chất thải nguy hại',3,'VAT_NUOI','/ca','Hố/lò, thùng CTNH','Chuồng: xác; kho: CTNH','Đơn vị thu gom','Biên bản; chứng từ CTNH', array['Xử lý xác theo quy định (chôn/đốt/compost) có biên bản, ảnh','Phân loại, lưu CTNH (bao bì thuốc, kim tiêm) đúng nơi','Bàn giao đơn vị thu gom, chứng từ']);
-- 1) Quy trình L2 → processes
insert into processes(code,dept_code,name,kind,object_type,trigger_text,inputs,outputs,sla,owner_role,kpi,tables,ui_path,coverage,status,l1_chain,organ,sop_count,description,position)
select code, dept, name, 'CORE', obj, 'Theo lịch/ca hoặc sự kiện', jsonb_build_array(jsonb_build_object('from','*','what',recv,'via','xem bảng')), jsonb_build_array(jsonb_build_object('to','*','what',give,'via','xem bảng')), 'Theo SOP', 'team_lead', evidence, '{}', ui, 'DA_CO', 'BAN_HANH', l1, organ, n, 'Quy trình chuẩn bộ gốc (Quyển 3 §15) · '||n||' SOP L3', 200 + row_number() over () from _l2
on conflict (code) do update set name=excluded.name, dept_code=excluded.dept_code, l1_chain=excluded.l1_chain, organ=excluded.organ, sop_count=excluded.sop_count, inputs=excluded.inputs, outputs=excluded.outputs, kpi=excluded.kpi, ui_path=excluded.ui_path, description=excluded.description;
-- 2) SOP L3 → process_steps + thư viện sops
insert into process_steps(process_code,step_no,name,actor_role,dept_code,action,system_where,control,form_table,sla_hours,tools,output)
select l.code, s.k, s.name, case when l.dept in ('KTCN','TT','SH','D5','CCU','DL') then 'worker' else 'team_lead' end, l.dept, s.name, l.ui, 'Chuẩn ĐẠT theo SOP '||l.code||'.'||s.k, null, 24, string_to_array(l.tools, ', '), 'Bằng chứng: '||l.evidence
from _l2 l, unnest(l.sops) with ordinality as s(name, k)
on conflict (process_code, step_no) do update set name=excluded.name, dept_code=excluded.dept_code, action=excluded.action, tools=excluded.tools, output=excluded.output;
insert into sops(code,org_id,title,dept,l1_chain,l2_group,status,version,owner_role,l2_code,l3_no,tools,frequency,evidence,review_due)
select l.code||'.'||s.k, 'ITRAN', s.name, l.dept, l.l1, l.name, 'NHAP', 1, 'team_lead', l.code, s.k, l.tools, 'Theo ca/lịch', l.evidence, current_date + 365
from _l2 l, unnest(l.sops) with ordinality as s(name, k)
on conflict (code) do update set title=excluded.title, dept=excluded.dept, l1_chain=excluded.l1_chain, l2_group=excluded.l2_group, l2_code=excluded.l2_code, l3_no=excluded.l3_no, tools=excluded.tools, evidence=excluded.evidence;
alter table process_steps add column if not exists sop_code text; update process_steps ps set sop_code = ps.process_code||'.'||ps.step_no where ps.process_code like 'SOP-%' and sop_code is null;
-- CCP mẫu (HACCP): đánh dấu SOP có điểm kiểm soát tới hạn
update sops set ccp=true, ccp_limit='Nhiệt phòng ≤12°C; sản phẩm ≤4°C trong 2h', ccp_action='Dừng, kiểm sản phẩm, làm lạnh lại/loại, INCIDENT' where code in ('SOP-CB-01.3','SOP-CB-01.6');
update sops set ccp=true, ccp_limit='Ẩm cuối ≤12% (sấy khô), aw <0,6', ccp_action='Sấy tiếp/loại lô' where code='SOP-CB-03.3';
update sops set ccp=true, ccp_limit='Nhiệt tâm ≥75°C', ccp_action='Nấu tiếp; loại nếu không đạt' where code='SOP-RS-03.4';
update sops set ccp=true, ccp_limit='Kho lạnh ≤4°C liên tục', ccp_action='Chuyển kho dự phòng, đánh giá lô' where code='SOP-CB-06.2';
-- 3) 12 điểm giao nhận SLA → dept_links (from/to theo phòng ban) + event_topics đã có
insert into departments(code,name,short,block,mission,per_farm,position,active) values ('*','Mọi phòng ban','*','DIEU_HANH','Đích chung cho luồng cắt ngang',false,99,true) on conflict do nothing;
insert into dept_links(from_dept,to_dept,what,via,frequency,realtime) values
('D5','KTCN','GN1 · Khẩu phần đúng mã loài trước 06h00 & 15h00 — Phiếu cân + FEED_LOG','feed_logs','ngày',true),
('KTCN','SH','GN2 · Phân chuyển ≤24h, đã tách rác — Phiếu khối lượng cân khu D','batch_logs.inputs','ngày',true),
('TT','D5','GN3 · Sinh khối cắt trong ngày, ẩm đạt chuẩn ủ — CROP_LOG + mẫu ẩm','harvests','vụ',true),
('TT','TT','GN4 · Rơm sạch nấm mốc lạ cho Nấm — Phiếu lô','inventory_moves','lứa',true),
('TT','SH','GN5 · Bã nấm → trùn trong 48h — BATCH_LOG','batch_logs','lứa',true),
('KTCN','SH','GN6 · Nước RAS → wetland/azolla đúng van, không tắt lọc — SENSOR_READ','sensor_reads','liên tục',true),
('KTCN','D5','GN7 · Vật nuôi kèm hồ sơ kiểm dịch + ngưng thuốc — Giấy thú y ký','animal_events,documents','mỗi lô',true),
('D5','KDM','GN8 · SKU đủ tem truy xuất + hạn dùng — Mã mẻ','lots','mỗi lô',true),
('DL','SH','GN9 · Rác hữu cơ phân loại, ngày 1 lần — Phiếu cân','batch_logs.inputs','ngày',true),
('KDM','D5','GN10 · Đơn hàng chốt trước 15h cho giao hôm sau — Lệnh sản xuất','orders,production_orders','ngày',true),
('DL','KTCN','GN11 · Chỉ đàn trình diễn, lịch cố định, khách không vào lõi — Nhật ký cổng','hosp_tours,gate_logs','ngày',true),
('QA','*','GN12 · Lệnh dừng/đóng có hiệu lực tức thời — Biên bản lệnh','incidents','sự kiện',true)
on conflict (from_dept,to_dept,what) do nothing;
insert into dept_links(from_dept,to_dept,what,via,frequency,realtime) values ('QA','*','GN12 · Lệnh dừng/đóng có hiệu lực tức thời — Biên bản lệnh','incidents','sự kiện',true) on conflict do nothing;
update processes p set visible_depts = (select array_agg(distinct x) from (select unnest(coalesce(p.visible_depts,'{}')) as x union select ps.dept_code from process_steps ps where ps.process_code=p.code and ps.dept_code is not null and ps.dept_code<>'*') u) where p.code like 'SOP-%';
drop table _l2;
