-- 0043 · TẦNG TUÂN THỦ theo SPEC-05: chuẩn = metadata gắn lên hệ sẵn có · CONTROL = vật thật trong app (trigger/alert/checklist/report/field/process/test) có evidence_query · điều khoản không trỏ được control = GAP đỏ · gói audit theo chuẩn = bộ lọc export
-- ===== chuẩn bổ sung theo SPEC-05 (giữ mã hiện có, thêm alias spec) =====
alter table standards add column if not exists spec_code text, add column if not exists priority int;
update standards set spec_code = case code when 'VIETGAP-TT' then 'VN-VIETGAP-TT' when 'VIETGAP-CN' then 'VN-VIETGAP-CN' when 'ORGANIC-VN' then 'VN-ORG' when 'HACCP' then 'CODEX-HACCP' when 'ISO22000' then 'ISO-22000' when 'ISO9001' then 'ISO-9001' when 'GLOBALGAP' then 'GGAP-IFA' when 'EU-ORGANIC' then 'EU-ORG' when 'USDA-NOP' then 'US-NOP' when 'HALAL' then 'HALAL' when 'JAS-ORGANIC' then 'JP-GAP' when 'KR-MFDS' then 'KR-CERT' else code end;
insert into standards(code,name,issuer,scope,region,description,required_for,position,url,spec_code,priority) values
('VN-TT66','Thông tư 66/2025/TT-BNNMT — hồ sơ, sổ sách chăn nuôi (kê khai, sổ đàn, sổ thuốc, báo cáo định kỳ)','Bộ NN&MT','CHAN_NUOI','VN','Bắt buộc pháp lý với cơ sở chăn nuôi: kê khai, sổ theo dõi đàn/thuốc/thức ăn/dịch bệnh, báo cáo cơ quan','{PHAP_LY}',0,'Văn bản TT 66/2025 (đối chiếu bản gốc)','VN-TT66',1),
('VN-ND13','Nghị định 13/2023/NĐ-CP — bảo vệ dữ liệu cá nhân','Chính phủ','QUAN_LY','VN','Consent, quyền chủ thể dữ liệu (xem/sửa/xóa), thông báo vi phạm 72h, hồ sơ xử lý dữ liệu','{PHAP_LY}',0,'https://vanban.chinhphu.vn (NĐ 13/2023)','VN-ND13',1),
('VN-PHANBON','Luật Trồng trọt + NĐ 84/2019 + QCVN 01-189:2019 — phân bón','Bộ NN&PTNT','TRONG_TROT','VN','Phân bón lưu hành phải được công nhận, kiểm nghiệm từng lô đạt QCVN trước xuất bán (làn 2 phân trùn/compost)','{PHAP_LY,BAN_PHAN}',0,'QCVN 01-189:2019/BNNPTNT','VN-PHANBON',1),
('JGAP','JGAP / ASIAGAP (Nhật, tương thích GFSI)','Japan GAP Foundation','TRONG_TROT','JP','GAP Nhật cho xuất khẩu; ASIAGAP được GFSI công nhận','{XUAT_KHAU_NHAT}',20,'https://jgap.jp','JP-GAP',3)
on conflict (code) do update set spec_code=excluded.spec_code, priority=excluded.priority, description=excluded.description;
update standards set priority = case when code in ('VIETGAP-TT','VIETGAP-CN','ITRAN-STD') then 1 when code in ('HACCP','ISO22000') then 2 when code in ('ORGANIC-VN','EU-ORGANIC') then 3 else coalesce(priority,4) end where priority is null;
-- ===== CONTROLS: vật thật trong app =====
create table if not exists controls(id text primary key, kind text not null, -- TRIGGER|ALERT|CHECKLIST|REPORT|FIELD|PROCESS|TEST|VIEW|JOB
  ref text not null, description text, evidence_query text, owner_dept text, active bool default true);
create table if not exists clause_controls(requirement_id int references standard_requirements on delete cascade, control_id text references controls on delete cascade, primary key(requirement_id, control_id));
create table if not exists compliance_gaps(id uuid primary key default gen_random_uuid(), requirement_id int references standard_requirements, farm_id text, status text default 'MO', -- MO|DANG_LAM|DONG
  plan text, due date, owner text, created_at timestamptz default now(), closed_at timestamptz);
do $$ declare t text; begin foreach t in array array['controls','clause_controls','compliance_gaps'] loop execute format('alter table %I enable row level security', t); execute format('drop policy if exists p_all on %I', t); execute format('create policy p_all on %I for all using (true) with check (app_role() in (''owner'',''director'',''it_engineer'',''tech_head'',''auditor''))', t); execute format('grant select, insert, update, delete on %I to app_user', t); end loop; end $$;
insert into controls(id,kind,ref,description,evidence_query,owner_dept) values
('C-TRACE','VIEW','v_trace_links + /trace/{lot} + EPCIS export','Truy xuất 1 bước lùi – 1 bước tiến: mẻ inputs/outputs, tem mã mẻ, trang công khai','select count(*) as lots_traced from lots l where farm_id=$1 and exists (select 1 from inventory_moves m where m.lot_id=l.id)','QA'),
('C-CCP','FIELD','batch_logs.ccp_readings + sops.ccp + AL-CCP + INCIDENT','Giám sát CCP, giới hạn tới hạn, hành động khắc phục; ĐỎ dừng chuyền','select count(*) as batches_with_ccp from batch_logs where farm_id=$1 and status=''ACTIVE'' and ccp_readings is not null and ts>now()-interval ''90 days''','D5'),
('C-RECALL','PROCESS','P-QA-02 truy xuất & thu hồi + mock recall 2 lần/năm (tasks)','Thu hồi + diễn tập ≤4h có biên bản','select count(*) as recall_drills from tasks where farm_id=$1 and kind=''DIEN_TAP_THU_HOI'' and status=''XONG'' and done_at>now()-interval ''365 days''','QA'),
('C-WITHDRAWAL','TRIGGER','trigger chặn sales khi animals.withdrawal_until > now (ERR_WITHDRAWAL_ACTIVE)','Ngưng thuốc trước xuất — chặn cứng tầng DB','select count(*) as violations from sales s join animals a on a.id=s.detail->>''animal_id'' where s.farm_id=$1 and a.withdrawal_until>s.ts::date','KTCN'),
('C-MEDBOOK','REPORT','/api/exports/medicine-book + animal_events(DIEU_TRI/VACCINE) + treatment_protocols','Sổ thuốc – đơn thú y – vaccine (TT66, GGAP)','select count(*) as treatments_90d from animal_events where farm_id=$1 and status=''ACTIVE'' and event_type in (''DIEU_TRI'',''VACCINE'') and ts>now()-interval ''90 days''','KTCN'),
('C-TT66','REPORT','/api/exports/tt66 (sổ đàn, sổ thuốc, sổ thức ăn, dịch bệnh theo biểu mẫu)','Hồ sơ chăn nuôi định kỳ nộp cơ quan','select count(*) as animals_active from animals where farm_id=$1 and status not in (''CHET'',''XUAT'',''LOAI'')','KTCN'),
('C-COA','FIELD','partners.approved + lots.coa_url + documents(kind=COA); luật K1 chặn nhập thiếu COA','Vật tư đầu vào có COA / NCC phê duyệt','select count(*) filter (where p.approved) as approved, count(*) as total from partners p where (p.farm_id=$1 or p.farm_id is null) and p.kind in (''NCC'',''KH_NCC'')','CCU'),
('C-CROPLOG','FIELD','crop_logs (giống-lô, PHI safe_after, water_source) + crop_inputs + trigger PHI chặn thu hoạch + khóa backdate','Nhật ký đồng ruộng đầy đủ, PHI, nguồn nước','select count(*) as inputs_90d, count(*) filter (where organic_allowed is false) as not_allowed from crop_inputs where farm_id=$1 and status=''ACTIVE'' and ts>now()-interval ''90 days''','TT'),
('C-WATERTEST','TEST','lab_samples kind NUOC/DAT 2 lần/năm + task lịch','Test nước/đất định kỳ có kết quả','select count(*) as tests_365d from lab_samples where farm_id=$1 and kind in (''NUOC'',''DAT'') and taken_at>now()-interval ''365 days''','TT'),
('C-SANITATION','CHECKLIST','checklist_runs vệ sinh/khử trùng + BATCH anolyte (ppm mỗi mẻ)','Vệ sinh – khử trùng có log','select count(*) as checklists_30d from checklist_runs where farm_id=$1 and status=''ACTIVE'' and ts>now()-interval ''30 days''','KTCN'),
('C-TRAINING','FIELD','staff.sop_certs + positions_catalog.sops + chặn phân ca việc chưa chứng chỉ','Đào tạo – chứng chỉ trước khi làm','select count(*) filter (where sop_certs is not null and sop_certs::text<>''[]'') as certified, count(*) as total from staff where active and (farm_id=$1 or $1=any(farm_ids))','HCNS'),
('C-CALIB','ALERT','calibrations + devices.calib_due + AL đến hạn + cờ dữ liệu quá hạn hiệu chuẩn','Hiệu chuẩn thiết bị đo','select count(*) filter (where calib_due<current_date) as overdue, count(*) as total from devices where farm_id=$1 and calib_due is not null','CNTB'),
('C-SAMPLE','CHECKLIST','checklist lưu mẫu 24h (bếp) / 15 ngày (chế biến) + log tủ mẫu','Lưu mẫu thực phẩm','select count(*) as sample_logs_30d from checklist_runs where farm_id=$1 and sop_code ilike ''%LUU-MAU%'' and ts>now()-interval ''30 days''','D5'),
('C-DOCCTRL','FIELD','sops.version + published_at/by + xác nhận đọc-hiểu (staff.sop_certs) + audit_log','Kiểm soát tài liệu – phiên bản – đọc hiểu (ISO 9001:7.5)','select count(*) filter (where published_at is not null) as published, count(*) as total from sops','QA'),
('C-AUDIT','PROCESS','P-QA-01 + compliance_checks (tự đánh giá 2 lần/năm) + xem xét lãnh đạo (report pl-thang)','Đánh giá nội bộ + xem xét lãnh đạo (ISO 9001:9)','select count(*) as checks_365d from compliance_checks where farm_id=$1 and checked_at>now()-interval ''365 days''','QA'),
('C-CAPA','FIELD','incidents.five_why + capa + closed_at ≤7 ngày; sops v+1','Hành động khắc phục – CAPA (ISO 9001:10)','select count(*) filter (where closed_at is not null) as closed, count(*) as total from incidents where farm_id=$1 and status=''ACTIVE'' and ts>now()-interval ''365 days''','QA'),
('C-QUARANTINE','FIELD','intake_lots.quarantine_until + CACH_LY_VAO/RA + SOP-BO-01 + gate_logs anolyte_wash','Cách ly nhập đàn – an toàn sinh học','select count(*) filter (where anolyte_wash) as washed, count(*) as total from gate_logs where farm_id=$1 and status=''ACTIVE'' and ts>now()-interval ''30 days''','KTCN'),
('C-WELFARE','FIELD','locations.capacity + settings mật độ + checklist ca + SOP phúc lợi','Phúc lợi: mật độ, nước tự do, không cắt mỏ','select count(*) as over_capacity from v_location_summary where farm_id=$1 and capacity is not null and coalesce(head_count,head,0) > capacity','KTCN'),
('C-ENV','VIEW','RC13 nước + sensor_reads nước thải + batch_logs biogas/compost + SOP wetland','Môi trường: zero xả, nước rỉ ủ phân gom xử lý','select count(*) as env_readings_30d from sensor_reads where farm_id=$1 and metric in (''water_m3'',''biogas_m3'',''cod'',''ph_out'') and ts>now()-interval ''30 days''','SH'),
('C-ORGANIC','VIEW','lots.organic/crop_inputs.organic_allowed + plots.organic_since/crop_seasons.conversion_stage + view % khẩu phần hữu cơ + cảnh báo trộn làn','Hữu cơ: % thức ăn hữu cơ, cấm GMO, đồng hồ chuyển đổi, tách khu','select count(*) filter (where conversion_stage is not null) as organic_seasons, count(*) as total from crop_seasons where farm_id=$1','TT'),
('C-HALAL','FIELD','recipes.halal_ok + recipes.no_bsf + hợp đồng lò mổ (documents) + cờ dòng SKU (products.halal_ok)','Halal: recipe không-BSF, lò mổ chứng nhận, tách dòng','select count(*) filter (where halal_ok) as halal_recipes, count(*) as total from recipes where farm_id=$1 and active','D5'),
('C-PDPA','FIELD','partners.consent + custody consent_at + job ẩn danh 5 năm + runbook sự cố 72h','Dữ liệu cá nhân NĐ13: consent, quyền xóa, thông báo 72h','select count(*) filter (where consent is not null) as consented, count(*) as total from partners where (farm_id=$1 or farm_id is null) and kind like ''KH%''','KDM'),
('C-FERT','TRIGGER','lots phân (SKU-PTR/compost) + lab_samples đạt QCVN + chặn xuất K5-phân khi thiếu phiếu lab','Phân bón: kiểm nghiệm từng lô đạt QCVN trước xuất','select count(*) as fert_lots from lots where farm_id=$1 and sku like ''SKU-PTR%''','SH'),
('C-GATE','FIELD','gate_logs 100% xe + weigh_tickets + anolyte','Cổng sinh học – cân – rửa xe','select count(*) as gate_30d from gate_logs where farm_id=$1 and status=''ACTIVE'' and ts>now()-interval ''30 days''','CCU'),
('C-APPENDONLY','TRIGGER','itran_no_update_delete + supersede + audit_log + gói audit sha256','Bằng chứng = dữ liệu vận hành append-only','select count(*) as events_30d from audit_log where ts>now()-interval ''30 days''','CNTB'),
('C-ICFS','JOB','icfs_score() + /chuan công khai','Chuẩn ITRAN tự chấm từ dữ liệu','select pct, level from v_icfs_summary where farm_id=$1','QA')
on conflict (id) do update set kind=excluded.kind, ref=excluded.ref, description=excluded.description, evidence_query=excluded.evidence_query, owner_dept=excluded.owner_dept;
-- ===== Điều khoản TT66 / NĐ13 / Phân bón (tóm tắt để lập ma trận) =====
insert into standard_requirements(standard_code,clause,title,requirement,level,evidence_tables,evidence_records,process_codes,frequency,owner_dept) values
('VN-TT66','1','Kê khai hoạt động chăn nuôi với UBND xã (loại, quy mô, địa điểm)','Kê khai & cập nhật khi thay đổi quy mô','CRITICAL','{farms,animal_groups,herd_daily}','{HS-SO-DAN}','{P-VN-01}','Khi thay đổi','GDT'),
('VN-TT66','2','Sổ theo dõi đàn: nhập, xuất, sinh, chết, chuyển','Ghi hằng ngày theo cá thể/đàn','CRITICAL','{animals,animal_events,intake_lots}','{HS-SO-DAN}','{SOP-BO-01,SOP-BO-09,P-VN-07}','Ngày','KTCN'),
('VN-TT66','3','Sổ theo dõi thức ăn, nguyên liệu, nguồn gốc','FEED_LOG + lô nguyên liệu','MAJOR','{feed_logs,inventory_moves,recipes}','{HS-THUC-AN}','{SOP-BO-07,SOP-SH-05}','Ngày','D5'),
('VN-TT66','4','Sổ theo dõi thuốc thú y, vaccine, ngưng thuốc','Đơn thú y, lô thuốc, liều, ngưng thuốc','CRITICAL','{animal_events,treatment_protocols}','{HS-THU-Y}','{SOP-BO-08}','Mỗi lần','KTCN'),
('VN-TT66','5','Sổ theo dõi dịch bệnh & xử lý xác/chất thải','Bệnh, chết, xử lý theo quy định','MAJOR','{animal_events,incidents,batch_logs}','{HS-THU-Y,HS-MOI-TRUONG}','{SOP-AT-06,P-VN-07}','Mỗi lần','KTCN'),
('VN-TT66','6','Báo cáo định kỳ/đột xuất cho cơ quan quản lý','Xuất biểu mẫu TT66 1 nút','MAJOR','{agg_daily}','{HS-SO-DAN}','{P-QT-02}','Quý','GDT'),
('VN-ND13','1','Thu thập dữ liệu cá nhân có sự đồng ý (consent) rõ mục đích','partners.consent, custody consent_at, khách lưu trú','CRITICAL','{partners,custody_contracts,hosp_bookings}','{HS-NHAN-NUOI,HS-DU-LICH}','{SOP-KD-03,SOP-RS-01}','Mỗi lần','KDM'),
('VN-ND13','2','Quyền chủ thể: xem, sửa, xóa/ẩn danh theo yêu cầu','Job ẩn danh, quy trình xử lý yêu cầu','MAJOR','{partners,audit_log}','{HS-AUDIT}','{P-CN-02}','Mỗi yêu cầu','CNTB'),
('VN-ND13','3','Bảo mật & thông báo vi phạm trong 72h','Runbook sự cố dữ liệu, incident','MAJOR','{incidents}','{HS-AUDIT}','{P-QT-01}','Sự kiện','CNTB'),
('VN-ND13','4','Hồ sơ đánh giá tác động xử lý dữ liệu, lưu ≥5 năm','Tài liệu đánh giá, lưu documents','MINOR','{documents}','{HS-PHAP-LY}','{SOP-HC-04}','Năm','HCNS'),
('VN-PHANBON','1','Phân bón lưu hành phải được công nhận (Quyết định công nhận)','Hồ sơ công nhận sản phẩm phân trùn/compost','CRITICAL','{products,documents}','{HS-PHAP-LY}','{SOP-HC-04}','Khi lưu hành','SH'),
('VN-PHANBON','2','Kiểm nghiệm từng lô đạt QCVN 01-189 trước xuất bán','lab_samples theo lô; chặn xuất K5-phân thiếu phiếu','CRITICAL','{lots,lab_samples,inventory_moves}','{HS-TRUY-XUAT}','{SOP-SH-01,SOP-SH-04}','Mỗi lô','SH'),
('VN-PHANBON','3','Nhãn, bao bì, công bố hợp quy','Nhãn đúng quy định','MAJOR','{products,lots}','{HS-TRUY-XUAT}','{SOP-CB-05}','Mỗi lô','D5'),
('JGAP','1','Quản lý trại & hồ sơ, an toàn lao động, môi trường (khung ASIAGAP/GFSI)','Tương đương GlobalG.A.P. AF/CB','MAJOR','{documents,staff,crop_seasons}','{HS-CANH-TAC}','{P-QA-01}','Năm','QA'),
('JGAP','2','ATTP: dư lượng, nước, vệ sinh thu hoạch','MRL Nhật, phân tích trước xuất','CRITICAL','{crop_inputs,lab_samples,harvests}','{HS-CANH-TAC}','{SOP-TT-02,SOP-TT-03}','Vụ','TT')
on conflict (standard_code, clause) do update set title=excluded.title, evidence_tables=excluded.evidence_tables, process_codes=excluded.process_codes;
-- ===== Map điều khoản → control (theo nhóm §3 SPEC-05) =====
insert into clause_controls(requirement_id, control_id)
select r.id, m.control from standard_requirements r join (values
 ('%truy xuất%','C-TRACE'),('%thu hồi%','C-RECALL'),('%CCP%','C-CCP'),('%HACCP%','C-CCP'),('%ngưng thuốc%','C-WITHDRAWAL'),('%thuốc%','C-MEDBOOK'),('%vaccine%','C-MEDBOOK'),('%Sổ theo dõi đàn%','C-TT66'),('%báo cáo%','C-TT66'),
 ('%COA%','C-COA'),('%NCC%','C-COA'),('%nhà cung cấp%','C-COA'),('%Phân bón%','C-CROPLOG'),('%BVTV%','C-CROPLOG'),('%Nhật ký%','C-CROPLOG'),('%nước%','C-WATERTEST'),('%đất%','C-WATERTEST'),
 ('%vệ sinh%','C-SANITATION'),('%Vệ sinh%','C-SANITATION'),('%đào tạo%','C-TRAINING'),('%Người lao động%','C-TRAINING'),('%Nhân sự%','C-TRAINING'),('%hiệu chuẩn%','C-CALIB'),('%thiết bị%','C-CALIB'),
 ('%lưu mẫu%','C-SAMPLE'),('%tài liệu%','C-DOCCTRL'),('%văn bản%','C-DOCCTRL'),('%audit%','C-AUDIT'),('%Đánh giá%','C-AUDIT'),('%kiểm tra nội bộ%','C-AUDIT'),('%khắc phục%','C-CAPA'),('%không phù hợp%','C-CAPA'),
 ('%cách ly%','C-QUARANTINE'),('%ATSH%','C-QUARANTINE'),('%sinh học%','C-QUARANTINE'),('%phúc lợi%','C-WELFARE'),('%mật độ%','C-WELFARE'),('%môi trường%','C-ENV'),('%chất thải%','C-ENV'),('%nước thải%','C-ENV'),
 ('%hữu cơ%','C-ORGANIC'),('%Chuyển đổi%','C-ORGANIC'),('%Annex%','C-ORGANIC'),('%National List%','C-ORGANIC'),('%Halal%','C-HALAL'),('%haram%','C-HALAL'),('%dữ liệu cá nhân%','C-PDPA'),('%consent%','C-PDPA'),
 ('%QCVN 01-189%','C-FERT'),('%lưu hành%','C-FERT'),('%Cổng%','C-GATE'),('%kiểm dịch%','C-GATE'),('%append%','C-APPENDONLY'),('%ghi chép%','C-APPENDONLY'),('%Ghi chép%','C-APPENDONLY'),('%hồ sơ%','C-APPENDONLY'),('%Hồ sơ%','C-APPENDONLY'),('%Sổ sách%','C-APPENDONLY'),('%truy được%','C-TRACE'),('%dư lượng%','C-CROPLOG'),('%MRL%','C-CROPLOG'),('%PHI%','C-CROPLOG'),('%giống%','C-QUARANTINE'),('%Con giống%','C-QUARANTINE'),('%thức ăn%','C-ORGANIC'),('%Thức ăn%','C-MEDBOOK'),('%kháng sinh%','C-MEDBOOK'),('%Sức khỏe%','C-MEDBOOK'),('%Điều hành%','C-AUDIT'),('%Bối cảnh%','C-DOCCTRL'),('%Hỗ trợ%','C-TRAINING'),('%PRP%','C-SANITATION'),('%Kiểm soát sản phẩm%','C-CCP'),('%Nhân sự%','C-TRAINING'),('%Xã hội%','C-TRAINING'),('%lao động%','C-TRAINING'),('%pháp luật%','C-DOCCTRL'),('%vùng trồng%','C-CROPLOG'),('%GACC%','C-TRACE'),('%Grader%','C-DOCCTRL'),('%grader%','C-DOCCTRL'),('%OSP%','C-DOCCTRL'),('%lưu hồ sơ%','C-APPENDONLY'),('%Lưu hồ sơ%','C-APPENDONLY'),('%Cam kết%','C-AUDIT'),('%Truy xuất%','C-TRACE'),('%rủi ro%','C-CAPA'),('%Kế hoạch%','C-DOCCTRL')
) m(pat, control) on r.title ilike m.pat or coalesce(r.requirement,'') ilike m.pat
where r.standard_code<>'ITRAN-STD' on conflict do nothing;
-- ITRAN-STD: mọi điều đều có control = chính metric_sql (C-ICFS) + control theo nhóm
insert into clause_controls(requirement_id, control_id) select id, 'C-ICFS' from standard_requirements where standard_code='ITRAN-STD' on conflict do nothing;
-- ===== Độ phủ + GAP tự sinh =====
create or replace view v_compliance_coverage as
select s.code as standard_code, s.name, s.priority, s.spec_code, count(r.id) as clauses,
  count(r.id) filter (where exists (select 1 from clause_controls cc where cc.requirement_id=r.id)) as with_control,
  count(r.id) filter (where r.level in ('CRITICAL','MAJOR')) as major, count(r.id) filter (where r.level in ('CRITICAL','MAJOR') and exists (select 1 from clause_controls cc where cc.requirement_id=r.id)) as major_with_control,
  round(100.0*count(r.id) filter (where exists (select 1 from clause_controls cc where cc.requirement_id=r.id))/nullif(count(r.id),0),0) as pct
from standards s left join standard_requirements r on r.standard_code=s.code where s.active group by s.code, s.name, s.priority, s.spec_code order by s.priority, s.code;
grant select on v_compliance_coverage to app_user;
create or replace function refresh_compliance_gaps() returns int language plpgsql as $$
declare n int; begin
  insert into compliance_gaps(requirement_id, farm_id, status, plan) select r.id, null, 'MO', 'Chưa có control trong app — cần thêm bảng/trigger/checklist/report hoặc map control có sẵn' from standard_requirements r where not exists (select 1 from clause_controls cc where cc.requirement_id=r.id) and not exists (select 1 from compliance_gaps g where g.requirement_id=r.id and g.status<>'DONG');
  update compliance_gaps g set status='DONG', closed_at=now() where status<>'DONG' and exists (select 1 from clause_controls cc where cc.requirement_id=g.requirement_id);
  get diagnostics n = row_count; return n; end $$;
select refresh_compliance_gaps();
grant execute on function refresh_compliance_gaps() to app_user;
-- ===== Audit nội bộ 2 lần/năm & diễn tập thu hồi 2 lần/năm: việc tự sinh (job tasks) =====
create or replace function gen_compliance_tasks(p_farm text) returns int language plpgsql as $$
declare n int := 0; half text := to_char(now(),'YYYY')||'-H'||case when extract(month from now())<=6 then 1 else 2 end; begin
  if not exists (select 1 from tasks where farm_id=p_farm and kind='AUDIT_NOI_BO' and detail->>'period'=half) then insert into tasks(farm_id,kind,title,detail,role_hint,priority,due_at,source) values (p_farm,'AUDIT_NOI_BO','Audit nội bộ '||half||' — tự đánh giá điều khoản (chuẩn ưu tiên 1–2) tại /tuan-thu', jsonb_build_object('period',half,'link','/tuan-thu'),'auditor','CAO', date_trunc('quarter', now()) + interval '2 months', 'COMPLIANCE'); n:=n+1; end if;
  if not exists (select 1 from tasks where farm_id=p_farm and kind='DIEN_TAP_THU_HOI' and detail->>'period'=half) then insert into tasks(farm_id,kind,title,detail,role_hint,priority,due_at,source) values (p_farm,'DIEN_TAP_THU_HOI','Diễn tập thu hồi lô ≤4h '||half||' — chọn 1 lô, truy 1 lùi 1 tiến, biên bản', jsonb_build_object('period',half,'link','/truy-xuat'),'tech_head','CAO', date_trunc('quarter', now()) + interval '2 months', 'COMPLIANCE'); n:=n+1; end if;
  return n; end $$;
grant execute on function gen_compliance_tasks(text) to app_user;
select gen_compliance_tasks(id) from farms where status='ACTIVE';
