-- 0065 · seed tồn công cụ F01 (nhập ban đầu, nguồn IMPORT) + chính sách min cho công cụ hay hỏng
insert into inventory_moves(farm_id, ts, created_by, source, warehouse_id, sku, direction, qty, unit, reason, from_to, client_ref)
select 'F01', now()-interval '30 days', 'NS-001', 'IMPORT', 'F01-'||v.wh, v.sku, 1, v.q, p.unit, 'NHAP_MUA', 'Kiểm kê ban đầu', 'seed-tool-'||v.wh||'-'||v.sku
from (values ('KCC-A','CC-CUOC',6),('KCC-A','CC-XENG-XUC',8),('KCC-A','CC-CAO',6),('KCC-A','CC-CHIA',4),('KCC-A','CC-XE-RUA',5),('KCC-A','CC-XO',20),('KCC-A','CC-CHOI-CO',10),('KCC-A','CC-DAY-DAT',12),('KCC-A','CC-BOC-TAI',2),('KCC-A','CC-BOM-TIEM',3),('KCC-A','CC-UNG',15),('KCC-A','CC-GANG',60),('KCC-A','CC-CAN-TREO',2),('KCC-A','CC-DEN-PIN',6),
 ('KCC-D','CC-XENG-XUC',6),('KCC-D','CC-CHIA',6),('KCC-D','CC-XE-RUA',4),('KCC-D','CC-NHIET-KE',4),('KCC-D','CC-CAN-DIEN-TU',1),('KCC-D','CC-MAY-BOM-XACH',1),('KCC-D','CC-BINH-PHUN',3),('KCC-D','CC-MAY-PHUN',1),('KCC-D','CC-UNG',10),('KCC-D','CC-KHAU-TRANG',100),
 ('KCC-R','CC-CUOC',10),('KCC-R','CC-CUOC-CHIM',4),('KCC-R','CC-XENG',8),('KCC-R','CC-DAO-PHAT',8),('KCC-R','CC-CUA-TAY',3),('KCC-R','CC-KEO-CANH',4),('KCC-R','CC-MAY-CAT-CO',2),('KCC-R','CC-ONG-TUOI',6),('KCC-R','CC-THUOC-DAY',2),('KCC-R','CC-BINH-PHUN',4),
 ('KCC-CB','CC-BUA',3),('KCC-CB','CC-KIM',4),('KCC-CB','CC-CO-LE',2),('KCC-CB','CC-MAY-KHOAN',2),('KCC-CB','CC-MU-BH',10),('KCC-CB','CC-KINH-BH',10),('KCC-CB','CC-BINH-CC',6),('KCC-CB','CC-XE-DAY',2)) v(wh,sku,q)
join products p on p.sku=v.sku where not exists (select 1 from inventory_moves m where m.client_ref='seed-tool-'||v.wh||'-'||v.sku);
insert into stock_policies(id, farm_id, sku, method, min_qty, max_qty, lead_time_days, abc_class) select 'F01-SP-'||v.sku, 'F01', v.sku, 'MIN_MAX', v.mn, v.mx, 7, 'C' from (values ('CC-GANG',30,120),('CC-KHAU-TRANG',50,300),('CC-UNG',10,40),('CC-XO',10,40),('CC-CUOC',8,24),('CC-XENG-XUC',8,24)) v(sku,mn,mx) where not exists (select 1 from stock_policies s where s.id='F01-SP-'||v.sku);
