-- 0078 · run_supervision_auto: ép tên cột (staff_id,value,target) bằng subquery; tiêu chí đếm left join dùng count(t.id) (không có dữ liệu = null → không chấm)
create or replace function run_supervision_auto(p_farm text, p_week date default date_trunc('week', current_date)::date) returns int language plpgsql as $$
declare c record; r record; n int := 0; ach numeric; w_end date := p_week + 7; tgt numeric; begin
  for c in select * from supervision_criteria where active and method='AUTO' and sql is not null order by position loop
    begin
      for r in execute format('select x.* from (%s) x(staff_id, value, target)', c.sql) using p_farm, p_week, w_end loop
        if c.position_code is not null and not exists (select 1 from staff s where s.id=r.staff_id and s.position_code=c.position_code) then continue; end if;
        if c.dept_code is not null and not exists (select 1 from staff s where s.id=r.staff_id and s.dept=c.dept_code) then continue; end if;
        if r.value is null then continue; end if;
        tgt := coalesce(r.target, c.target);
        if tgt is null or tgt = 0 then ach := case c.direction when '<=' then (case when r.value=0 then 1 else greatest(0, 1 - r.value*0.25) end) else (case when r.value>0 then 1 else 0 end) end;
        else ach := case c.direction when '>=' then least(1, r.value/tgt) when '<=' then case when r.value <= tgt then 1 else greatest(0, 1 - (r.value - tgt)/tgt) end else case when r.value = tgt then 1 else 0 end end; end if;
        insert into supervision_scores(farm_id, week_start, staff_id, criteria_id, method, value, target, achieved, weight, points, source)
        values (p_farm, p_week, r.staff_id, c.id, 'AUTO', r.value, tgt, coalesce(ach,0), c.weight, round(c.weight*coalesce(ach,0),2), 'AUTO')
        on conflict (farm_id, week_start, staff_id, criteria_id) do update set value=excluded.value, target=excluded.target, achieved=excluded.achieved, points=excluded.points, checked_at=now();
        n := n+1;
      end loop;
    exception when others then raise notice 'criteria % lỗi: %', c.id, sqlerrm; end;
  end loop;
  insert into supervision_scores(farm_id, week_start, staff_id, criteria_id, method, value, target, achieved, weight, points, source, checked_by, note)
  select sc.farm_id, p_week, sc.target_staff_id, sc.criteria_id, 'MANUAL', case when sc.result='DAT' then 1 else 0 end, 1, case when sc.result='DAT' then 1 else 0 end, cr.weight, case when sc.result='DAT' then cr.weight else 0 end, 'GIAM_SAT', sc.supervisor_id, sc.note
  from supervision_checks sc join supervision_criteria cr on cr.id=sc.criteria_id where sc.farm_id=p_farm and sc.status='ACTIVE' and sc.target_staff_id is not null and sc.criteria_id is not null and sc.ts>=p_week and sc.ts<w_end
  on conflict (farm_id, week_start, staff_id, criteria_id) do update set value=excluded.value, achieved=excluded.achieved, points=excluded.points, checked_by=excluded.checked_by, note=excluded.note, checked_at=now();
  return n; end $$;
-- Sửa các tiêu chí: mẫu = "không có bản ghi → null (không chấm)", có bản ghi → tỷ lệ
update supervision_criteria set sql = $q$select s.id as staff_id, case when count(t.id)=0 then null else round(100.0*count(*) filter (where t.status='XONG' and t.done_at<=t.due_at)/count(t.id),0) end as value, 90 as target from staff s left join tasks t on t.farm_id=s.farm_id and (t.assignee_id=s.id or (t.assignee_id is null and t.role_hint=s.role and t.detail->>'dept'=s.dept)) and t.due_at>=$2 and t.due_at<$3 where s.farm_id=$1 and s.active group by s.id$q$ where id='SC-ALL-01';
update supervision_criteria set sql = $q$select s.id, case when count(c.id)=0 then null else round(100.0*count(*) filter (where c.all_green)/count(c.id),0) end, 90 from staff s left join checklist_runs c on c.farm_id=s.farm_id and c.created_by=s.id and c.ts>=$2 and c.ts<$3 and c.status='ACTIVE' where s.farm_id=$1 and s.active group by s.id$q$ where id='SC-ALL-04';
update supervision_criteria set sql = $q$with e as (select created_by, ts, created_at from feed_logs where farm_id=$1 and ts>=$2 and ts<$3 union all select created_by, ts, created_at from animal_events where farm_id=$1 and ts>=$2 and ts<$3 union all select created_by, ts, created_at from crop_logs where farm_id=$1 and ts>=$2 and ts<$3 union all select created_by, ts, created_at from inventory_moves where farm_id=$1 and ts>=$2 and ts<$3)
   select s.id, case when count(e.ts)=0 then null else round(100.0*count(*) filter (where e.created_at - e.ts <= interval '2 hours')/count(e.ts),0) end, 85 from staff s left join e on e.created_by=s.id where s.farm_id=$1 and s.active and s.role='worker' group by s.id$q$ where id='SC-ALL-05';
update supervision_criteria set sql = $q$select s.id, count(t.id) filter (where t.status='XONG') as value, count(t.id) as target from staff s left join training_sessions t on t.farm_id=s.farm_id and (t.trainee_id=s.id or t.trainer_id=s.id) and t.week_start>=$2 and t.week_start<$3 where s.farm_id=$1 and s.active group by s.id having count(t.id)>0$q$ where id='SC-ALL-06';
update supervision_criteria set sql = $q$select s.id, count(t.id) filter (where t.status='XONG'), count(t.id) from staff s left join training_sessions t on t.farm_id=s.farm_id and t.trainer_id=s.id and t.week_start>=$2 and t.week_start<$3 where s.farm_id=$1 and s.role in ('team_lead','tech_head','director') group by s.id having count(t.id)>0$q$ where id='SC-TL-02';
update supervision_criteria set sql = $q$select s.id, case when count(c.id)=0 then null else round(100.0*count(*) filter (where c.approved_at - c.ts <= interval '24 hours')/count(c.id),0) end, 90 from staff s left join checklist_runs c on c.farm_id=s.farm_id and c.approved_by=s.id and c.ts>=$2 and c.ts<$3 where s.farm_id=$1 and s.role in ('team_lead','tech_head') group by s.id$q$ where id='SC-TL-01';
update supervision_criteria set sql = $q$select s.id, case when count(a.id)=0 then null else round(100.0*count(*) filter (where a.acked_at - a.ts <= interval '4 hours')/count(a.id),0) end, 90 from staff s left join alerts a on a.farm_id=s.farm_id and a.level='DO' and a.ts>=$2 and a.ts<$3 and a.acked_by=s.id where s.farm_id=$1 and s.role in ('team_lead','tech_head') group by s.id$q$ where id='SC-TL-03';
update supervision_criteria set sql = $q$select s.id, case when count(f.id)=0 then null else round(100.0*count(*) filter (where cardinality(f.photo_urls)>0)/count(f.id),0) end, 80 from staff s left join feed_logs f on f.farm_id=s.farm_id and f.created_by=s.id and f.ts>=$2 and f.ts<$3 where s.farm_id=$1 and s.position_code='A1' group by s.id$q$ where id='SC-A1-04';
update supervision_criteria set sql = $q$select s.id, case when count(f.id)=0 then null else round(avg(abs(f.qty_kg-f.planned_kg)/nullif(f.planned_kg,0))*100,1) end, 3 from staff s left join feed_logs f on f.farm_id=s.farm_id and f.created_by=s.id and f.ts>=$2 and f.ts<$3 and f.planned_kg>0 where s.farm_id=$1 and s.position_code='A1' group by s.id$q$ where id='SC-A1-02';
update supervision_criteria set sql = $q$select s.id, case when count(e.id)=0 then null else round(100.0*count(*) filter (where a.created_at - e.ts <= interval '24 hours')/count(e.id),0) end, 100 from staff s left join animal_events e on e.farm_id=s.farm_id and e.created_by=s.id and e.event_type='DE' and e.ts>=$2 and e.ts<$3 left join animals a on a.dam_id=e.animal_id and a.birth_date=e.ts::date where s.farm_id=$1 and s.position_code='A2' group by s.id$q$ where id='SC-A2-02';
update supervision_criteria set sql = $q$select s.id, case when count(b.id)=0 then null else round(100.0*count(*) filter (where jsonb_array_length(coalesce(b.ccp_readings,'[]'))>0 and b.qc<>'{}'::jsonb)/count(b.id),0) end, 100 from staff s left join batch_logs b on b.farm_id=s.farm_id and b.created_by=s.id and b.line in ('D5_VIEN','D5_TMR','DONG_GOI') and b.ts>=$2 and b.ts<$3 where s.farm_id=$1 and s.position_code='A7' group by s.id$q$ where id='SC-A7-01';
update supervision_criteria set sql = $q$select s.id, case when count(m.id)=0 then null else round(100.0*count(*) filter (where m.created_at - m.ts <= interval '2 hours')/count(m.id),0) end, 90 from staff s left join inventory_moves m on m.farm_id=s.farm_id and m.created_by=s.id and m.ts>=$2 and m.ts<$3 where s.farm_id=$1 and s.position_code='A8' group by s.id$q$ where id='SC-A8-01';
update supervision_criteria set sql = $q$select s.id, case when count(o.id)=0 then null else round(100.0*count(*) filter (where o.status='GIAO')/count(o.id),0) end, 95 from staff s left join orders o on o.farm_id=s.farm_id and o.created_by=s.id and o.deliver_date>=$2 and o.deliver_date<$3 where s.farm_id=$1 and s.position_code='A9' group by s.id$q$ where id='SC-A9-01';
update supervision_criteria set sql = $q$select s.id, case when count(g.id)=0 then null else round(100.0*count(*) filter (where g.weighed and g.anolyte_wash)/count(g.id),0) end, 95 from staff s left join gate_logs g on g.farm_id=s.farm_id and g.created_by=s.id and g.ts>=$2 and g.ts<$3 where s.farm_id=$1 and s.position_code='A11' group by s.id$q$ where id='SC-A11-01';
