-- 0175 · ĐẦU VÀO (materials) + ĐẦU RA (output) ĐỊNH LƯỢNG cho bước quy trình — lô Thủy sản RAS/ao/bè (cá·lươn·tôm — RAS/TOM).
-- Khung ĐÃ CÓ (process_steps.materials jsonb [{sku,qty,unit,ghi_chu}] + output; UI ProcessDesigner render+sửa).
-- Chỉ THIẾU DỮ LIỆU. SKU tham chiếu bảng products (đã kiểm: mọi SKU có thật). Số theo norms/recipes khi có;
-- không có → MINH HOẠ (ghi_chu ghi rõ "MINH HOẠ, chủ/thú y sửa"). Guard materials='[]' để KHÔNG đè bước đã điền.
-- Bước thuần ghi sổ/kiểm tra/phê duyệt/quan sát → materials=[] (chỉ điền output). Nối tiếp mẫu 0159.

update process_steps set materials = '[{"sku":"PB-VOI","qty":0.02,"unit":"kg/m3","ghi_chu":"nâng kiềm/ổn định pH nước cấp — MINH HOẠ, chủ/thú y sửa"}]'::jsonb, output = 'nước cấp đạt pH 7–8, độ mặn/kim loại trong ngưỡng; số liệu nguồn ghi sổ' where process_code='SOP-RAS-01' and step_no=1 and coalesce(materials,'[]'::jsonb)='[]'::jsonb;
update process_steps set materials = '[{"sku":"NL-MEN-VS","qty":0.5,"unit":"lít/m3","ghi_chu":"gây/duy trì màng vi sinh lọc — MINH HOẠ, chủ/thú y sửa"}]'::jsonb, output = 'lọc cơ (drum) + lọc sinh học chạy ổn định, nước trong; NH3/NO2 đầu ra đạt' where process_code='SOP-RAS-01' and step_no=2 and coalesce(materials,'[]'::jsonb)='[]'::jsonb;
update process_steps set materials = '[]'::jsonb, output = 'số liệu DO/pH/NH3/NO2 theo ca (DO ≥5 mg/l, NH3 <0.1 mg/l) ghi sổ' where process_code='SOP-RAS-01' and step_no=3 and coalesce(materials,'[]'::jsonb)='[]'::jsonb;
update process_steps set materials = '[{"sku":"TH-ANOLYTE","qty":2,"unit":"lít/bể","ghi_chu":"vệ sinh lọc/drum — MINH HOẠ, chủ/thú y sửa"}]'::jsonb, output = 'bùn đã xả, lọc/drum sạch theo lịch; nhật ký vệ sinh' where process_code='SOP-RAS-01' and step_no=4 and coalesce(materials,'[]'::jsonb)='[]'::jsonb;
update process_steps set materials = '[]'::jsonb, output = 'sự cố lọc/bơm xử lý ≤30 phút, sục dự phòng hoạt động; nhật ký sự cố' where process_code='SOP-RAS-01' and step_no=5 and coalesce(materials,'[]'::jsonb)='[]'::jsonb;
update process_steps set materials = '[]'::jsonb, output = 'nước thải dẫn đúng van về wetland/azolla, không xả thẳng ra môi trường' where process_code='SOP-RAS-01' and step_no=6 and coalesce(materials,'[]'::jsonb)='[]'::jsonb;
update process_steps set materials = '[{"sku":"NL-MEN-VS","qty":0.5,"unit":"lít/m3","ghi_chu":"ổn định vi sinh nước trước thả — MINH HOẠ, chủ/thú y sửa"}]'::jsonb, output = 'bể nước ổn định ≥7 ngày, pH/DO/NH3 đạt ngưỡng thả giống' where process_code='SOP-RAS-02' and step_no=1 and coalesce(materials,'[]'::jsonb)='[]'::jsonb;
update process_steps set materials = '[]'::jsonb, output = 'giống thuần nhiệt/độ mặn 30 phút, cân bằng môi trường, giảm sốc' where process_code='SOP-RAS-02' and step_no=2 and coalesce(materials,'[]'::jsonb)='[]'::jsonb;
update process_steps set materials = '[{"sku":"GI-LUON","qty":100,"unit":"con/m3","ghi_chu":"lươn/cá giống thả — MINH HOẠ, chủ/thú y sửa"}]'::jsonb, output = 'đàn mới tạo, mật độ ~100 con/m3, số lượng thả đếm/cân ghi sổ' where process_code='SOP-RAS-02' and step_no=3 and coalesce(materials,'[]'::jsonb)='[]'::jsonb;
update process_steps set materials = '[]'::jsonb, output = 'hao hụt 3 ngày đầu ≤5%/đàn theo dõi & ghi sổ' where process_code='SOP-RAS-02' and step_no=4 and coalesce(materials,'[]'::jsonb)='[]'::jsonb;
update process_steps set materials = '[]'::jsonb, output = 'khẩu phần ngày tính theo sinh khối ước & nhiệt độ, ~0.012 kg/con/ngày' where process_code='SOP-RAS-03' and step_no=1 and coalesce(materials,'[]'::jsonb)='[]'::jsonb;
update process_steps set materials = '[{"sku":"TA-VIEN-CA","qty":0.012,"unit":"kg/con/ngày","ghi_chu":"viên cá/lươn, chia nhiều bữa nhỏ"}]'::jsonb, output = 'đàn ăn hết theo bữa, không dư thừa; lượng ăn ghi FEED_LOG' where process_code='SOP-RAS-03' and step_no=2 and coalesce(materials,'[]'::jsonb)='[]'::jsonb;
update process_steps set materials = '[]'::jsonb, output = 'khẩu phần giảm/ngừng khi DO <4 mg/l hoặc thời tiết xấu; ghi lý do' where process_code='SOP-RAS-03' and step_no=3 and coalesce(materials,'[]'::jsonb)='[]'::jsonb;
update process_steps set materials = '[]'::jsonb, output = 'FEED_LOG ngày + lượng thức ăn thừa ghi nhận, tính FCR bể' where process_code='SOP-RAS-03' and step_no=4 and coalesce(materials,'[]'::jsonb)='[]'::jsonb;
update process_steps set materials = '[]'::jsonb, output = 'sinh khối bể cập nhật 2 tuần/lần, ADG & FCR bể theo dõi' where process_code='SOP-RAS-03' and step_no=5 and coalesce(materials,'[]'::jsonb)='[]'::jsonb;
update process_steps set materials = '[]'::jsonb, output = 'cảnh báo DO/pH/NH3 từ FMS tiếp nhận, phân loại mức ưu tiên' where process_code='SOP-RAS-04' and step_no=1 and coalesce(materials,'[]'::jsonb)='[]'::jsonb;
update process_steps set materials = '[]'::jsonb, output = 'chỉ số DO/pH/NH3 xác minh tại bể bằng máy đo tay, đối chiếu FMS' where process_code='SOP-RAS-04' and step_no=2 and coalesce(materials,'[]'::jsonb)='[]'::jsonb;
update process_steps set materials = '[]'::jsonb, output = 'sục dự phòng bật, ngừng cho ăn; DO phục hồi ≥5 mg/l' where process_code='SOP-RAS-04' and step_no=3 and coalesce(materials,'[]'::jsonb)='[]'::jsonb;
update process_steps set materials = '[{"sku":"PB-VOI","qty":0.03,"unit":"kg/m3","ghi_chu":"điều chỉnh pH/kiềm nước — MINH HOẠ, chủ/thú y sửa"}]'::jsonb, output = 'pH đưa về 7–8 bằng vôi/thay nước theo SOP; ghi liều dùng' where process_code='SOP-RAS-04' and step_no=4 and coalesce(materials,'[]'::jsonb)='[]'::jsonb;
update process_steps set materials = '[]'::jsonb, output = 'thay ~30% nước, giảm cho ăn; NH3 về <0.1 mg/l' where process_code='SOP-RAS-04' and step_no=5 and coalesce(materials,'[]'::jsonb)='[]'::jsonb;
update process_steps set materials = '[]'::jsonb, output = 'INCIDENT ghi nhận, phân tích 5-why nếu lặp; hành động khắc phục' where process_code='SOP-RAS-04' and step_no=6 and coalesce(materials,'[]'::jsonb)='[]'::jsonb;
update process_steps set materials = '[]'::jsonb, output = 'ắc quy/máy sục dự phòng kiểm hàng tuần, sẵn sàng ≥95%' where process_code='SOP-RAS-04' and step_no=7 and coalesce(materials,'[]'::jsonb)='[]'::jsonb;
update process_steps set materials = '[]'::jsonb, output = 'đàn nhịn ăn 24h trước thu, ruột sạch, giảm hao khi vận chuyển' where process_code='SOP-RAS-05' and step_no=1 and coalesce(materials,'[]'::jsonb)='[]'::jsonb;
update process_steps set materials = '[]'::jsonb, output = 'cá/lươn thu tỉa/thu toàn bộ, phân cỡ theo sàng' where process_code='SOP-RAS-05' and step_no=2 and coalesce(materials,'[]'::jsonb)='[]'::jsonb;
update process_steps set materials = '[{"sku":"CC-CAN-DIEN-TU","qty":1,"unit":"cái/lần","ghi_chu":"cân sản phẩm thu hoạch"}]'::jsonb, output = 'sản lượng thu (SKU-CA-THIT/SKU-LUON-THIT) cân & ghi THU_TIA/XUAT + SALE' where process_code='SOP-RAS-05' and step_no=3 and coalesce(materials,'[]'::jsonb)='[]'::jsonb;
update process_steps set materials = '[]'::jsonb, output = 'sinh khối bể còn lại cập nhật sau thu hoạch' where process_code='SOP-RAS-05' and step_no=4 and coalesce(materials,'[]'::jsonb)='[]'::jsonb;
update process_steps set materials = '[]'::jsonb, output = 'bể xả cạn sau vụ, cọ rửa cơ học sạch cặn bám' where process_code='SOP-RAS-06' and step_no=1 and coalesce(materials,'[]'::jsonb)='[]'::jsonb;
update process_steps set materials = '[{"sku":"TH-ANOLYTE","qty":5,"unit":"lít/bể","ghi_chu":"sát trùng bể sau vụ — MINH HOẠ, chủ/thú y sửa"}]'::jsonb, output = 'bể phun anolyte sát trùng, phơi khô đạt trống bể' where process_code='SOP-RAS-06' and step_no=2 and coalesce(materials,'[]'::jsonb)='[]'::jsonb;
update process_steps set materials = '[{"sku":"TH-ANOLYTE","qty":2,"unit":"lít/bể","ghi_chu":"vệ sinh ống/feeder/lọc — MINH HOẠ, chủ/thú y sửa"}]'::jsonb, output = 'ống/feeder/lọc vệ sinh, thông thoáng, không nghẹt' where process_code='SOP-RAS-06' and step_no=3 and coalesce(materials,'[]'::jsonb)='[]'::jsonb;
update process_steps set materials = '[]'::jsonb, output = 'checklist vệ sinh + ảnh hoàn tất, bể sẵn sàng vụ mới' where process_code='SOP-RAS-06' and step_no=4 and coalesce(materials,'[]'::jsonb)='[]'::jsonb;
update process_steps set materials = '[{"sku":"PB-VOI","qty":80,"unit":"kg/1000m2","ghi_chu":"vôi cải tạo/khử phèn đáy ao — MINH HOẠ, chủ/thú y sửa"}]'::jsonb, output = 'đáy ao cải tạo, phơi nứt chân chim, rải vôi khử phèn' where process_code='SOP-TOM-01' and step_no=1 and coalesce(materials,'[]'::jsonb)='[]'::jsonb;
update process_steps set materials = '[{"sku":"NL-ROM","qty":200,"unit":"kg/1000m2","ghi_chu":"rơm ủ đáy tạo nền vi sinh — MINH HOẠ, chủ sửa"},{"sku":"NL-MEN-VS","qty":5,"unit":"lít/1000m2","ghi_chu":"ủ men vi sinh phân huỷ rơm — MINH HOẠ, chủ/thú y sửa"}]'::jsonb, output = 'rơm trải + ủ men vi sinh đáy ao, tạo nền thức ăn tự nhiên' where process_code='SOP-TOM-01' and step_no=2 and coalesce(materials,'[]'::jsonb)='[]'::jsonb;
update process_steps set materials = '[{"sku":"NL-RI-MAT","qty":3,"unit":"kg/1000m2","ghi_chu":"gây màu nước/tảo — MINH HOẠ, chủ sửa"},{"sku":"NL-MEN-VS","qty":2,"unit":"lít/1000m2","ghi_chu":"gây màu vi sinh — MINH HOẠ, chủ sửa"}]'::jsonb, output = 'nước cấp đủ mức, gây màu đạt độ trong 30–40 cm' where process_code='SOP-TOM-01' and step_no=3 and coalesce(materials,'[]'::jsonb)='[]'::jsonb;
update process_steps set materials = '[]'::jsonb, output = 'pH/kiềm/khí độc (NH3, H2S) kiểm tra & đạt ngưỡng thả' where process_code='SOP-TOM-01' and step_no=4 and coalesce(materials,'[]'::jsonb)='[]'::jsonb;
update process_steps set materials = '[]'::jsonb, output = 'nhật ký ao cập nhật (cải tạo, vôi, ủ rơm men, gây màu)' where process_code='SOP-TOM-01' and step_no=5 and coalesce(materials,'[]'::jsonb)='[]'::jsonb;
update process_steps set materials = '[{"sku":"GI-LUON","qty":30,"unit":"con/m2","ghi_chu":"tôm giống — MINH HOẠ (thiếu SKU tôm giống), chủ sửa"}]'::jsonb, output = 'tôm giống thả, thuần môi trường, mật độ ~30 con/m2; đàn tạo' where process_code='SOP-TOM-02' and step_no=1 and coalesce(materials,'[]'::jsonb)='[]'::jsonb;
update process_steps set materials = '[{"sku":"TA-VIEN-CA","qty":5,"unit":"% khối lượng/ngày","ghi_chu":"thức ăn tôm ~5% sinh khối, canh sàng — MINH HOẠ, chủ/thú y sửa"}]'::jsonb, output = 'tôm ăn theo sàng, điều chỉnh lượng; ghi FEED_LOG, FCR theo dõi' where process_code='SOP-TOM-02' and step_no=2 and coalesce(materials,'[]'::jsonb)='[]'::jsonb;
update process_steps set materials = '[]'::jsonb, output = 'chỉ số nước (pH, kiềm, DO, khí độc) quan trắc hàng ngày; xử lý khi lệch' where process_code='SOP-TOM-02' and step_no=3 and coalesce(materials,'[]'::jsonb)='[]'::jsonb;
update process_steps set materials = '[]'::jsonb, output = 'kiểm bệnh đốm trắng/gan tụy định kỳ; cách ly & xử lý ổ bệnh nếu có' where process_code='SOP-TOM-02' and step_no=4 and coalesce(materials,'[]'::jsonb)='[]'::jsonb;
update process_steps set materials = '[{"sku":"CC-CAN-DIEN-TU","qty":1,"unit":"cái/lần","ghi_chu":"cân tôm thu hoạch"}]'::jsonb, output = 'sản lượng tôm (SKU-TOM-THIT) thu hoạch, cân & ghi SALE' where process_code='SOP-TOM-02' and step_no=5 and coalesce(materials,'[]'::jsonb)='[]'::jsonb;
update process_steps set materials = '[]'::jsonb, output = 'bè/neo/lưới kiểm tra chắc chắn trước thả, không rách/lỏng neo' where process_code='SOP-TOM-03' and step_no=1 and coalesce(materials,'[]'::jsonb)='[]'::jsonb;
update process_steps set materials = '[{"sku":"GI-LUON","qty":50,"unit":"con/m3","ghi_chu":"cá/tôm giống bè — MINH HOẠ, chủ sửa"}]'::jsonb, output = 'giống thả vào bè, đàn ghi nhận; mật độ ~50 con/m3' where process_code='SOP-TOM-03' and step_no=2 and coalesce(materials,'[]'::jsonb)='[]'::jsonb;
update process_steps set materials = '[{"sku":"TA-VIEN-CA","qty":0.012,"unit":"kg/con/ngày","ghi_chu":"thức ăn viên cá bè"}]'::jsonb, output = 'cá ăn đủ khẩu phần, lưới vệ sinh thông nước; quan sát sức khoẻ đàn' where process_code='SOP-TOM-03' and step_no=3 and coalesce(materials,'[]'::jsonb)='[]'::jsonb;
update process_steps set materials = '[{"sku":"CC-CAN-DIEN-TU","qty":1,"unit":"cái/lần","ghi_chu":"cân cá bè thu hoạch"}]'::jsonb, output = 'sản lượng cá bè (SKU-CA-THIT) thu hoạch, cân & ghi SALE' where process_code='SOP-TOM-03' and step_no=4 and coalesce(materials,'[]'::jsonb)='[]'::jsonb;
update process_steps set materials = '[]'::jsonb, output = 'lệnh lũ R1 tiếp nhận từ Ban chỉ huy, kích hoạt phương án trú lũ' where process_code='SOP-TOM-04' and step_no=1 and coalesce(materials,'[]'::jsonb)='[]'::jsonb;
update process_steps set materials = '[{"sku":"VT-DAY-LUOI","qty":2,"unit":"cuộn/bè","ghi_chu":"dây/lưới gia cố, neo bè trú lũ — MINH HOẠ, chủ sửa"}]'::jsonb, output = 'bè gia cố/di dời về vị trí trú an toàn trước lũ' where process_code='SOP-TOM-04' and step_no=2 and coalesce(materials,'[]'::jsonb)='[]'::jsonb;
update process_steps set materials = '[]'::jsonb, output = 'đàn/lưới kiểm tra sau di dời, hao hụt do di dời ≤2%' where process_code='SOP-TOM-04' and step_no=3 and coalesce(materials,'[]'::jsonb)='[]'::jsonb;
update process_steps set materials = '[]'::jsonb, output = 'biên bản trú lũ + báo cáo Ban chỉ huy hoàn tất' where process_code='SOP-TOM-04' and step_no=4 and coalesce(materials,'[]'::jsonb)='[]'::jsonb;
