-- 0179 · ĐẦU VÀO (materials) + ĐẦU RA (output) ĐỊNH LƯỢNG cho bước quy trình — lô Văn phòng (HR·KD·MK·QA·TC·XNK·resort — nghiệp vụ giấy tờ, output-only).
-- Khung ĐÃ CÓ (process_steps.materials jsonb [{sku,qty,unit,ghi_chu}] + output; UI ProcessDesigner render+sửa).
-- Chỉ THIẾU DỮ LIỆU. SKU tham chiếu bảng products (đã kiểm: mọi SKU có thật). Số theo norms/recipes khi có;
-- không có → MINH HOẠ (ghi_chu ghi rõ "MINH HOẠ, chủ/thú y sửa"). Guard materials='[]' để KHÔNG đè bước đã điền.
-- Bước thuần ghi sổ/kiểm tra/phê duyệt/quan sát → materials=[] (chỉ điền output). Nối tiếp mẫu 0159.

update process_steps set materials = '[]'::jsonb, output = 'phiếu booking đã xác nhận + cọc thu' where process_code='P-DL-01' and step_no=1 and coalesce(materials,'[]'::jsonb)='[]'::jsonb;
update process_steps set materials = '[]'::jsonb, output = 'khách nhận phòng, folio mở + khai báo lưu trú' where process_code='P-DL-01' and step_no=2 and coalesce(materials,'[]'::jsonb)='[]'::jsonb;
update process_steps set materials = '[]'::jsonb, output = 'dịch vụ trong kỳ ghi vào folio + xuất kho ghi nhận' where process_code='P-DL-01' and step_no=3 and coalesce(materials,'[]'::jsonb)='[]'::jsonb;
update process_steps set materials = '[]'::jsonb, output = 'hóa đơn tất toán + phòng chuyển chờ dọn' where process_code='P-DL-01' and step_no=4 and coalesce(materials,'[]'::jsonb)='[]'::jsonb;
update process_steps set materials = '[]'::jsonb, output = 'báo giá tiệc (menu×pax) gửi khách' where process_code='P-DL-02' and step_no=1 and coalesce(materials,'[]'::jsonb)='[]'::jsonb;
update process_steps set materials = '[]'::jsonb, output = 'hợp đồng tiệc ký + cọc thu' where process_code='P-DL-02' and step_no=2 and coalesce(materials,'[]'::jsonb)='[]'::jsonb;
update process_steps set materials = '[]'::jsonb, output = 'địa điểm sẵn sàng + NL xuất kho + phân công xong' where process_code='P-DL-02' and step_no=3 and coalesce(materials,'[]'::jsonb)='[]'::jsonb;
update process_steps set materials = '[]'::jsonb, output = 'tiệc diễn ra, chi phí phát sinh ghi folio' where process_code='P-DL-02' and step_no=4 and coalesce(materials,'[]'::jsonb)='[]'::jsonb;
update process_steps set materials = '[]'::jsonb, output = 'quyết toán thu đủ + phản hồi khách ≥4/5' where process_code='P-DL-02' and step_no=5 and coalesce(materials,'[]'::jsonb)='[]'::jsonb;
update process_steps set materials = '[]'::jsonb, output = 'lịch tour mở + HDV phân công' where process_code='P-DL-03' and step_no=1 and coalesce(materials,'[]'::jsonb)='[]'::jsonb;
update process_steps set materials = '[]'::jsonb, output = 'vé bán + tiền thu đủ' where process_code='P-DL-03' and step_no=2 and coalesce(materials,'[]'::jsonb)='[]'::jsonb;
update process_steps set materials = '[]'::jsonb, output = 'tour hoàn tất N khách, phản hồi ≥4/5, có bán chéo' where process_code='P-DL-03' and step_no=3 and coalesce(materials,'[]'::jsonb)='[]'::jsonb;
update process_steps set materials = '[]'::jsonb, output = 'nhân sự mới: HĐLĐ ký + hồ sơ + tài khoản/PIN' where process_code='P-HC-01' and step_no=1 and coalesce(materials,'[]'::jsonb)='[]'::jsonb;
update process_steps set materials = '[]'::jsonb, output = 'nhân sự đạt SOP vị trí + chứng chỉ + khám SK/ATTP' where process_code='P-HC-01' and step_no=2 and coalesce(materials,'[]'::jsonb)='[]'::jsonb;
update process_steps set materials = '[]'::jsonb, output = 'bảng chấm công ngày + ghi chú giao ca' where process_code='P-HC-01' and step_no=3 and coalesce(materials,'[]'::jsonb)='[]'::jsonb;
update process_steps set materials = '[]'::jsonb, output = 'KPI tháng chốt → bảng lương + thưởng phạt' where process_code='P-HC-01' and step_no=4 and coalesce(materials,'[]'::jsonb)='[]'::jsonb;
update process_steps set materials = '[]'::jsonb, output = 'nghỉ việc: thu hồi quyền + bàn giao + quyết toán' where process_code='P-HC-01' and step_no=5 and coalesce(materials,'[]'::jsonb)='[]'::jsonb;
update process_steps set materials = '[]'::jsonb, output = 'lead ghi nhận vào CRM' where process_code='P-KD-01' and step_no=1 and coalesce(materials,'[]'::jsonb)='[]'::jsonb;
update process_steps set materials = '[]'::jsonb, output = 'mẫu/báo giá gửi khách theo nhu cầu' where process_code='P-KD-01' and step_no=2 and coalesce(materials,'[]'::jsonb)='[]'::jsonb;
update process_steps set materials = '[]'::jsonb, output = 'đối tác mới + hạn mức tín dụng + HĐ ký' where process_code='P-KD-01' and step_no=3 and coalesce(materials,'[]'::jsonb)='[]'::jsonb;
update process_steps set materials = '[]'::jsonb, output = 'đơn hàng/HĐ N dòng tạo' where process_code='P-KD-02' and step_no=1 and coalesce(materials,'[]'::jsonb)='[]'::jsonb;
update process_steps set materials = '[]'::jsonb, output = 'lô hàng soạn đủ theo đơn' where process_code='P-KD-02' and step_no=2 and coalesce(materials,'[]'::jsonb)='[]'::jsonb;
update process_steps set materials = '[]'::jsonb, output = 'hàng xuất kho + phiếu cổng ghi nhận' where process_code='P-KD-02' and step_no=3 and coalesce(materials,'[]'::jsonb)='[]'::jsonb;
update process_steps set materials = '[]'::jsonb, output = 'hóa đơn bán phát hành' where process_code='P-KD-02' and step_no=4 and coalesce(materials,'[]'::jsonb)='[]'::jsonb;
update process_steps set materials = '[]'::jsonb, output = 'tiền thu/ghi công nợ đối chiếu' where process_code='P-KD-02' and step_no=5 and coalesce(materials,'[]'::jsonb)='[]'::jsonb;
update process_steps set materials = '[]'::jsonb, output = 'ca POS mở, két + tồn quầy khớp' where process_code='P-KD-03' and step_no=1 and coalesce(materials,'[]'::jsonb)='[]'::jsonb;
update process_steps set materials = '[]'::jsonb, output = 'giao dịch bán quầy (TM/QR) ghi nhận' where process_code='P-KD-03' and step_no=2 and coalesce(materials,'[]'::jsonb)='[]'::jsonb;
update process_steps set materials = '[]'::jsonb, output = 'chốt ca: chênh lệch két=0, tiền nộp đủ' where process_code='P-KD-03' and step_no=3 and coalesce(materials,'[]'::jsonb)='[]'::jsonb;
update process_steps set materials = '[]'::jsonb, output = 'HĐ nhận nuôi ký + cá thể gán + tiền thu' where process_code='P-KD-04' and step_no=1 and coalesce(materials,'[]'::jsonb)='[]'::jsonb;
update process_steps set materials = '[]'::jsonb, output = 'ảnh/sự kiện tuần + buổi live cập nhật' where process_code='P-KD-04' and step_no=2 and coalesce(materials,'[]'::jsonb)='[]'::jsonb;
update process_steps set materials = '[]'::jsonb, output = 'tin nhắn trả ≤24h + gia hạn/kết thúc HĐ' where process_code='P-KD-04' and step_no=3 and coalesce(materials,'[]'::jsonb)='[]'::jsonb;
update process_steps set materials = '[]'::jsonb, output = 'lịch nội dung tuần/tháng ban hành' where process_code='P-MK-01' and step_no=1 and coalesce(materials,'[]'::jsonb)='[]'::jsonb;
update process_steps set materials = '[]'::jsonb, output = 'bản nháp nội dung theo brief' where process_code='P-MK-01' and step_no=2 and coalesce(materials,'[]'::jsonb)='[]'::jsonb;
update process_steps set materials = '[]'::jsonb, output = 'bài được duyệt (người duyệt ≠ người viết)' where process_code='P-MK-01' and step_no=3 and coalesce(materials,'[]'::jsonb)='[]'::jsonb;
update process_steps set materials = '[]'::jsonb, output = 'bài đăng đúng giờ + link lưu' where process_code='P-MK-01' and step_no=4 and coalesce(materials,'[]'::jsonb)='[]'::jsonb;
update process_steps set materials = '[]'::jsonb, output = 'số đo hiệu quả sau 48h/7 ngày cập nhật' where process_code='P-MK-01' and step_no=5 and coalesce(materials,'[]'::jsonb)='[]'::jsonb;
update process_steps set materials = '[]'::jsonb, output = 'phản hồi/bình luận/bài báo ghi nhận' where process_code='P-MK-02' and step_no=1 and coalesce(materials,'[]'::jsonb)='[]'::jsonb;
update process_steps set materials = '[]'::jsonb, output = 'phân loại mức độ; CAO/khủng hoảng → báo GĐ ngay' where process_code='P-MK-02' and step_no=2 and coalesce(materials,'[]'::jsonb)='[]'::jsonb;
update process_steps set materials = '[]'::jsonb, output = 'kết luận xác minh sự thật với bộ phận' where process_code='P-MK-02' and step_no=3 and coalesce(materials,'[]'::jsonb)='[]'::jsonb;
update process_steps set materials = '[]'::jsonb, output = 'phản hồi công khai đăng + theo dõi' where process_code='P-MK-02' and step_no=4 and coalesce(materials,'[]'::jsonb)='[]'::jsonb;
update process_steps set materials = '[]'::jsonb, output = 'bài học rút + SOP/FAQ cập nhật' where process_code='P-MK-02' and step_no=5 and coalesce(materials,'[]'::jsonb)='[]'::jsonb;
update process_steps set materials = '[]'::jsonb, output = 'chiến dịch lập: mục tiêu/ngân sách/kênh/mã UTM' where process_code='P-MK-03' and step_no=1 and coalesce(materials,'[]'::jsonb)='[]'::jsonb;
update process_steps set materials = '[]'::jsonb, output = 'lead/đơn/booking gắn campaign_id' where process_code='P-MK-03' and step_no=2 and coalesce(materials,'[]'::jsonb)='[]'::jsonb;
update process_steps set materials = '[]'::jsonb, output = 'báo cáo ROI + đề xuất tiếp' where process_code='P-MK-03' and step_no=3 and coalesce(materials,'[]'::jsonb)='[]'::jsonb;
update process_steps set materials = '[]'::jsonb, output = 'hồ sơ khảo sát đất-nước-pháp lý + mẫu lab' where process_code='P-MR-01' and step_no=1 and coalesce(materials,'[]'::jsonb)='[]'::jsonb;
update process_steps set materials = '[]'::jsonb, output = 'thiết kế + dự toán được duyệt cấp vốn' where process_code='P-MR-01' and step_no=2 and coalesce(materials,'[]'::jsonb)='[]'::jsonb;
update process_steps set materials = '[]'::jsonb, output = 'trại khai báo (create_farm) + khu/kho/CC tự sinh + nhân sự' where process_code='P-MR-01' and step_no=3 and coalesce(materials,'[]'::jsonb)='[]'::jsonb;
update process_steps set materials = '[]'::jsonb, output = 'trại go-live + checklist chuyển giao đủ (theo dõi 6 tháng)' where process_code='P-MR-01' and step_no=4 and coalesce(materials,'[]'::jsonb)='[]'::jsonb;
update process_steps set materials = '[]'::jsonb, output = 'vào ca chấm công (vị trí) + nhận việc' where process_code='P-NS-01' and step_no=1 and coalesce(materials,'[]'::jsonb)='[]'::jsonb;
update process_steps set materials = '[]'::jsonb, output = 'checklist đầu/cuối ca theo SOP hoàn thành' where process_code='P-NS-01' and step_no=2 and coalesce(materials,'[]'::jsonb)='[]'::jsonb;
update process_steps set materials = '[]'::jsonb, output = 'biên bản giao ca + việc dở dang bàn giao' where process_code='P-NS-01' and step_no=3 and coalesce(materials,'[]'::jsonb)='[]'::jsonb;
update process_steps set materials = '[]'::jsonb, output = 'danh mục SOP vị trí + lịch đào tạo' where process_code='P-NS-02' and step_no=1 and coalesce(materials,'[]'::jsonb)='[]'::jsonb;
update process_steps set materials = '[]'::jsonb, output = 'chứng chỉ SOP cấp (sop_certs)' where process_code='P-NS-02' and step_no=2 and coalesce(materials,'[]'::jsonb)='[]'::jsonb;
update process_steps set materials = '[]'::jsonb, output = 'khám SK/ATTP định kỳ đạt + nhắc hạn' where process_code='P-NS-02' and step_no=3 and coalesce(materials,'[]'::jsonb)='[]'::jsonb;
update process_steps set materials = '[]'::jsonb, output = 'KPI tháng chốt từ bản ghi' where process_code='P-NS-03' and step_no=1 and coalesce(materials,'[]'::jsonb)='[]'::jsonb;
update process_steps set materials = '[]'::jsonb, output = 'bảng lương tính (công + cơ bản + KPI + phụ cấp − BH − thuế)' where process_code='P-NS-03' and step_no=2 and coalesce(materials,'[]'::jsonb)='[]'::jsonb;
update process_steps set materials = '[]'::jsonb, output = 'lương duyệt + hạch toán + chuyển khoản + phiếu lương phát' where process_code='P-NS-03' and step_no=3 and coalesce(materials,'[]'::jsonb)='[]'::jsonb;
update process_steps set materials = '[]'::jsonb, output = 'ứng viên qua phỏng vấn + thử việc' where process_code='P-NS-04' and step_no=1 and coalesce(materials,'[]'::jsonb)='[]'::jsonb;
update process_steps set materials = '[]'::jsonb, output = 'HĐLĐ ký + hồ sơ + tài khoản/PIN + phân trại/dept' where process_code='P-NS-04' and step_no=2 and coalesce(materials,'[]'::jsonb)='[]'::jsonb;
update process_steps set materials = '[]'::jsonb, output = 'nghỉ việc: bàn giao + thu hồi quyền + quyết toán' where process_code='P-NS-04' and step_no=3 and coalesce(materials,'[]'::jsonb)='[]'::jsonb;
update process_steps set materials = '[]'::jsonb, output = 'gap analysis theo chuẩn thị trường đích' where process_code='P-QA-01' and step_no=1 and coalesce(materials,'[]'::jsonb)='[]'::jsonb;
update process_steps set materials = '[]'::jsonb, output = 'SOP/hồ sơ/thiết bị thiếu bổ sung + đào tạo' where process_code='P-QA-01' and step_no=2 and coalesce(materials,'[]'::jsonb)='[]'::jsonb;
update process_steps set materials = '[]'::jsonb, output = 'audit nội bộ + khắc phục điểm không phù hợp' where process_code='P-QA-01' and step_no=3 and coalesce(materials,'[]'::jsonb)='[]'::jsonb;
update process_steps set materials = '[]'::jsonb, output = 'chứng nhận cấp + lưu sổ + nhắc tái đánh giá' where process_code='P-QA-01' and step_no=4 and coalesce(materials,'[]'::jsonb)='[]'::jsonb;
update process_steps set materials = '[]'::jsonb, output = 'khiếu nại/sự cố ghi + lô liên quan xác định' where process_code='P-QA-02' and step_no=1 and coalesce(materials,'[]'::jsonb)='[]'::jsonb;
update process_steps set materials = '[]'::jsonb, output = 'lô khóa + chặn xuất + thông báo khách/kênh' where process_code='P-QA-02' and step_no=2 and coalesce(materials,'[]'::jsonb)='[]'::jsonb;
update process_steps set materials = '[]'::jsonb, output = 'lô thu hồi/thu gom + 5-why + CAPA lập' where process_code='P-QA-02' and step_no=3 and coalesce(materials,'[]'::jsonb)='[]'::jsonb;
update process_steps set materials = '[]'::jsonb, output = 'sự cố đóng + SOP cập nhật + báo cáo' where process_code='P-QA-02' and step_no=4 and coalesce(materials,'[]'::jsonb)='[]'::jsonb;
update process_steps set materials = '[]'::jsonb, output = 'sổ rủi ro + kịch bản (dịch/lũ/cháy/mất điện/mạng)' where process_code='P-QT-01' and step_no=1 and coalesce(materials,'[]'::jsonb)='[]'::jsonb;
update process_steps set materials = '[]'::jsonb, output = 'sự cố báo ≤24h + cách ly/ứng phó + incident ghi' where process_code='P-QT-01' and step_no=2 and coalesce(materials,'[]'::jsonb)='[]'::jsonb;
update process_steps set materials = '[]'::jsonb, output = '5-why + CAPA + đóng + SOP cập nhật' where process_code='P-QT-01' and step_no=3 and coalesce(materials,'[]'::jsonb)='[]'::jsonb;
update process_steps set materials = '[]'::jsonb, output = 'báo cáo tuần gửi chủ (thứ 2 07:00)' where process_code='P-QT-02' and step_no=1 and coalesce(materials,'[]'::jsonb)='[]'::jsonb;
update process_steps set materials = '[]'::jsonb, output = 'đóng sổ tháng + P&L + ngân sách-thực tế gửi BGĐ' where process_code='P-QT-02' and step_no=2 and coalesce(materials,'[]'::jsonb)='[]'::jsonb;
update process_steps set materials = '[]'::jsonb, output = 'báo cáo quý: TT66/thuế/môi trường/ICFS + gói audit' where process_code='P-QT-02' and step_no=3 and coalesce(materials,'[]'::jsonb)='[]'::jsonb;
update process_steps set materials = '[]'::jsonb, output = 'đề tài + giả thuyết + KPI đo đăng ký (rd_trials)' where process_code='P-RD-01' and step_no=1 and coalesce(materials,'[]'::jsonb)='[]'::jsonb;
update process_steps set materials = '[]'::jsonb, output = 'ngân sách duyệt + thiết kế nhánh đối chứng' where process_code='P-RD-01' and step_no=2 and coalesce(materials,'[]'::jsonb)='[]'::jsonb;
update process_steps set materials = '[]'::jsonb, output = 'quan sát ghi + mẫu lab thu' where process_code='P-RD-01' and step_no=3 and coalesce(materials,'[]'::jsonb)='[]'::jsonb;
update process_steps set materials = '[]'::jsonb, output = 'kết luận + tri thức hóa → SOP/định mức mới' where process_code='P-RD-01' and step_no=4 and coalesce(materials,'[]'::jsonb)='[]'::jsonb;
update process_steps set materials = '[]'::jsonb, output = 'đề nghị chi (mục đích/CC/chứng từ đính kèm)' where process_code='P-TC-01' and step_no=1 and coalesce(materials,'[]'::jsonb)='[]'::jsonb;
update process_steps set materials = '[]'::jsonb, output = 'duyệt cấp 1 theo hạn mức vai' where process_code='P-TC-01' and step_no=2 and coalesce(materials,'[]'::jsonb)='[]'::jsonb;
update process_steps set materials = '[]'::jsonb, output = 'duyệt cấp 2 nếu >20tr; >50tr báo chủ' where process_code='P-TC-01' and step_no=3 and coalesce(materials,'[]'::jsonb)='[]'::jsonb;
update process_steps set materials = '[]'::jsonb, output = 'chi tiền + bút toán GL tự hạch toán' where process_code='P-TC-01' and step_no=4 and coalesce(materials,'[]'::jsonb)='[]'::jsonb;
update process_steps set materials = '[]'::jsonb, output = 'sao kê nhập + đối chiếu RC10 khớp' where process_code='P-TC-02' and step_no=1 and coalesce(materials,'[]'::jsonb)='[]'::jsonb;
update process_steps set materials = '[]'::jsonb, output = 'chi phí cố định/CC + khấu hao + giá vốn ghi' where process_code='P-TC-02' and step_no=2 and coalesce(materials,'[]'::jsonb)='[]'::jsonb;
update process_steps set materials = '[]'::jsonb, output = 'kỳ khóa + báo cáo (P&L/cân đối/thuế) xuất' where process_code='P-TC-02' and step_no=3 and coalesce(materials,'[]'::jsonb)='[]'::jsonb;
update process_steps set materials = '[]'::jsonb, output = 'ngân sách năm/tháng theo CC lập' where process_code='P-TC-03' and step_no=1 and coalesce(materials,'[]'::jsonb)='[]'::jsonb;
update process_steps set materials = '[]'::jsonb, output = 'quỹ trích theo tỷ lệ (thiên tai/bảo dưỡng/đào tạo/marketing)' where process_code='P-TC-03' and step_no=2 and coalesce(materials,'[]'::jsonb)='[]'::jsonb;
update process_steps set materials = '[]'::jsonb, output = 'cảnh báo vượt ngân sách + giải trình' where process_code='P-TC-03' and step_no=3 and coalesce(materials,'[]'::jsonb)='[]'::jsonb;
update process_steps set materials = '[]'::jsonb, output = 'giá thành theo CC/SKU/mẻ tính' where process_code='P-TC-04' and step_no=1 and coalesce(materials,'[]'::jsonb)='[]'::jsonb;
update process_steps set materials = '[]'::jsonb, output = 'giá sàn/niêm yết cập nhật + giá chuyển nội bộ 70%' where process_code='P-TC-04' and step_no=2 and coalesce(materials,'[]'::jsonb)='[]'::jsonb;
update process_steps set materials = '[]'::jsonb, output = 'hồ sơ thị trường đích lập (market_profiles)' where process_code='P-XNK-01' and step_no=1 and coalesce(materials,'[]'::jsonb)='[]'::jsonb;
update process_steps set materials = '[]'::jsonb, output = 'HĐ ngoại thương + LC mở' where process_code='P-XNK-01' and step_no=2 and coalesce(materials,'[]'::jsonb)='[]'::jsonb;
update process_steps set materials = '[]'::jsonb, output = 'lô sản xuất đạt spec khách' where process_code='P-XNK-01' and step_no=3 and coalesce(materials,'[]'::jsonb)='[]'::jsonb;
update process_steps set materials = '[]'::jsonb, output = 'bộ chứng từ XK đủ (CO/CQ/phyto...)' where process_code='P-XNK-01' and step_no=4 and coalesce(materials,'[]'::jsonb)='[]'::jsonb;
update process_steps set materials = '[]'::jsonb, output = 'hàng đóng + tờ khai hải quan thông quan + vận chuyển' where process_code='P-XNK-01' and step_no=5 and coalesce(materials,'[]'::jsonb)='[]'::jsonb;
update process_steps set materials = '[]'::jsonb, output = 'thanh toán quốc tế + landed cost chốt' where process_code='P-XNK-01' and step_no=6 and coalesce(materials,'[]'::jsonb)='[]'::jsonb;
update process_steps set materials = '[]'::jsonb, output = 'giấy phép nhập (giống/TACN/thuốc/máy) đủ' where process_code='P-XNK-02' and step_no=1 and coalesce(materials,'[]'::jsonb)='[]'::jsonb;
update process_steps set materials = '[]'::jsonb, output = 'HĐ ngoại + vận chuyển + bảo hiểm ký' where process_code='P-XNK-02' and step_no=2 and coalesce(materials,'[]'::jsonb)='[]'::jsonb;
update process_steps set materials = '[]'::jsonb, output = 'thông quan + landed cost + nhập kho/lô nhập đàn cách ly' where process_code='P-XNK-02' and step_no=3 and coalesce(materials,'[]'::jsonb)='[]'::jsonb;
update process_steps set materials = '[]'::jsonb, output = 'chứng từ hạch toán → journal_entries (GL tự sinh + tay)' where process_code='SOP-HC-01' and step_no=1 and coalesce(materials,'[]'::jsonb)='[]'::jsonb;
update process_steps set materials = '[]'::jsonb, output = 'đối chiếu ngân hàng RC10 khớp' where process_code='SOP-HC-01' and step_no=2 and coalesce(materials,'[]'::jsonb)='[]'::jsonb;
update process_steps set materials = '[]'::jsonb, output = 'chi phí cố định/CC + khấu hao ghi sổ' where process_code='SOP-HC-01' and step_no=3 and coalesce(materials,'[]'::jsonb)='[]'::jsonb;
update process_steps set materials = '[]'::jsonb, output = 'sổ đóng, khóa kỳ ngày 5' where process_code='SOP-HC-01' and step_no=4 and coalesce(materials,'[]'::jsonb)='[]'::jsonb;
update process_steps set materials = '[]'::jsonb, output = 'P&L phân hệ + ngân sách-thực tế + dòng tiền' where process_code='SOP-HC-01' and step_no=5 and coalesce(materials,'[]'::jsonb)='[]'::jsonb;
update process_steps set materials = '[]'::jsonb, output = 'báo cáo thuế/BCTC xuất' where process_code='SOP-HC-01' and step_no=6 and coalesce(materials,'[]'::jsonb)='[]'::jsonb;
update process_steps set materials = '[]'::jsonb, output = 'tổng hợp nhu cầu mua (ngày-tồn + kế hoạch)' where process_code='SOP-HC-02' and step_no=1 and coalesce(materials,'[]'::jsonb)='[]'::jsonb;
update process_steps set materials = '[]'::jsonb, output = 'PO lập, NCC được duyệt (≤35% 1 NCC)' where process_code='SOP-HC-02' and step_no=2 and coalesce(materials,'[]'::jsonb)='[]'::jsonb;
update process_steps set materials = '[]'::jsonb, output = 'PO duyệt (không tự duyệt)' where process_code='SOP-HC-02' and step_no=3 and coalesce(materials,'[]'::jsonb)='[]'::jsonb;
update process_steps set materials = '[]'::jsonb, output = 'hàng nhận: cân/đếm + COA + nhập kho theo lô' where process_code='SOP-HC-02' and step_no=4 and coalesce(materials,'[]'::jsonb)='[]'::jsonb;
update process_steps set materials = '[]'::jsonb, output = 'xuất kho theo phiếu FEFO' where process_code='SOP-HC-02' and step_no=5 and coalesce(materials,'[]'::jsonb)='[]'::jsonb;
update process_steps set materials = '[]'::jsonb, output = 'kiểm kê chéo tháng + điều chỉnh có duyệt' where process_code='SOP-HC-02' and step_no=6 and coalesce(materials,'[]'::jsonb)='[]'::jsonb;
update process_steps set materials = '[]'::jsonb, output = 'đánh giá NCC định kỳ (scorecard)' where process_code='SOP-HC-02' and step_no=7 and coalesce(materials,'[]'::jsonb)='[]'::jsonb;
update process_steps set materials = '[]'::jsonb, output = 'ứng viên phỏng vấn + thử việc' where process_code='SOP-HC-03' and step_no=1 and coalesce(materials,'[]'::jsonb)='[]'::jsonb;
update process_steps set materials = '[]'::jsonb, output = 'HĐLĐ + hồ sơ + tài khoản/PIN + phân trại' where process_code='SOP-HC-03' and step_no=2 and coalesce(materials,'[]'::jsonb)='[]'::jsonb;
update process_steps set materials = '[]'::jsonb, output = 'đào tạo SOP vị trí + kiểm tra đạt' where process_code='SOP-HC-03' and step_no=3 and coalesce(materials,'[]'::jsonb)='[]'::jsonb;
update process_steps set materials = '[]'::jsonb, output = 'chứng chỉ nội bộ cấp (sop_certs)' where process_code='SOP-HC-03' and step_no=4 and coalesce(materials,'[]'::jsonb)='[]'::jsonb;
update process_steps set materials = '[]'::jsonb, output = 'khám SK/ATTP định kỳ đạt' where process_code='SOP-HC-03' and step_no=5 and coalesce(materials,'[]'::jsonb)='[]'::jsonb;
update process_steps set materials = '[]'::jsonb, output = 'đào tạo lại khi SOP đổi phiên bản' where process_code='SOP-HC-03' and step_no=6 and coalesce(materials,'[]'::jsonb)='[]'::jsonb;
update process_steps set materials = '[]'::jsonb, output = 'sổ giấy phép/chứng nhận/bảo hiểm (có hạn)' where process_code='SOP-HC-04' and step_no=1 and coalesce(materials,'[]'::jsonb)='[]'::jsonb;
update process_steps set materials = '[]'::jsonb, output = 'nhắc hạn 90 ngày + gia hạn' where process_code='SOP-HC-04' and step_no=2 and coalesce(materials,'[]'::jsonb)='[]'::jsonb;
update process_steps set materials = '[]'::jsonb, output = 'hồ sơ pháp lý đất/xây dựng/MT đính kèm' where process_code='SOP-HC-04' and step_no=3 and coalesce(materials,'[]'::jsonb)='[]'::jsonb;
update process_steps set materials = '[]'::jsonb, output = 'bảo hiểm tài sản/vật nuôi/mùa vụ + hồ sơ bồi thường' where process_code='SOP-HC-04' and step_no=4 and coalesce(materials,'[]'::jsonb)='[]'::jsonb;
update process_steps set materials = '[]'::jsonb, output = 'văn bản pháp luật mới cập nhật' where process_code='SOP-HC-04' and step_no=5 and coalesce(materials,'[]'::jsonb)='[]'::jsonb;
update process_steps set materials = '[]'::jsonb, output = 'KPI tháng chốt từ bản ghi' where process_code='SOP-HC-05' and step_no=1 and coalesce(materials,'[]'::jsonb)='[]'::jsonb;
update process_steps set materials = '[]'::jsonb, output = 'bảng lương tính (công/KPI/phụ cấp/BH/thuế)' where process_code='SOP-HC-05' and step_no=2 and coalesce(materials,'[]'::jsonb)='[]'::jsonb;
update process_steps set materials = '[]'::jsonb, output = 'lương duyệt 2 chữ ký + hạch toán' where process_code='SOP-HC-05' and step_no=3 and coalesce(materials,'[]'::jsonb)='[]'::jsonb;
update process_steps set materials = '[]'::jsonb, output = 'chuyển khoản + phát phiếu lương (payslips)' where process_code='SOP-HC-05' and step_no=4 and coalesce(materials,'[]'::jsonb)='[]'::jsonb;
update process_steps set materials = '[]'::jsonb, output = 'khiếu nại lương xử lý' where process_code='SOP-HC-05' and step_no=5 and coalesce(materials,'[]'::jsonb)='[]'::jsonb;
update process_steps set materials = '[]'::jsonb, output = 'khách B2B/lead tìm + đánh giá' where process_code='SOP-KD-01' and step_no=1 and coalesce(materials,'[]'::jsonb)='[]'::jsonb;
update process_steps set materials = '[]'::jsonb, output = 'báo giá theo giá sàn/giá thành' where process_code='SOP-KD-01' and step_no=2 and coalesce(materials,'[]'::jsonb)='[]'::jsonb;
update process_steps set materials = '[]'::jsonb, output = 'HĐ bao tiêu ký (sản lượng/giá/kỳ giao)' where process_code='SOP-KD-01' and step_no=3 and coalesce(materials,'[]'::jsonb)='[]'::jsonb;
update process_steps set materials = '[]'::jsonb, output = 'lịch giao theo HĐ + đơn tuần' where process_code='SOP-KD-01' and step_no=4 and coalesce(materials,'[]'::jsonb)='[]'::jsonb;
update process_steps set materials = '[]'::jsonb, output = 'công nợ theo dõi ≤15 ngày' where process_code='SOP-KD-01' and step_no=5 and coalesce(materials,'[]'::jsonb)='[]'::jsonb;
update process_steps set materials = '[]'::jsonb, output = 'đánh giá HĐ cuối kỳ' where process_code='SOP-KD-01' and step_no=6 and coalesce(materials,'[]'::jsonb)='[]'::jsonb;
update process_steps set materials = '[]'::jsonb, output = 'ca POS mở + hàng quầy kiểm' where process_code='SOP-KD-02' and step_no=1 and coalesce(materials,'[]'::jsonb)='[]'::jsonb;
update process_steps set materials = '[]'::jsonb, output = 'bán quầy: quét + KM + VietQR (pos_receipts)' where process_code='SOP-KD-02' and step_no=2 and coalesce(materials,'[]'::jsonb)='[]'::jsonb;
update process_steps set materials = '[]'::jsonb, output = 'đơn online về webhook → xác nhận + soạn + giao' where process_code='SOP-KD-02' and step_no=3 and coalesce(materials,'[]'::jsonb)='[]'::jsonb;
update process_steps set materials = '[]'::jsonb, output = 'chăm sóc/đánh giá sau bán' where process_code='SOP-KD-02' and step_no=4 and coalesce(materials,'[]'::jsonb)='[]'::jsonb;
update process_steps set materials = '[]'::jsonb, output = 'chốt ca + đối soát sàn/COD' where process_code='SOP-KD-02' and step_no=5 and coalesce(materials,'[]'::jsonb)='[]'::jsonb;
update process_steps set materials = '[]'::jsonb, output = 'giá/khuyến mãi cập nhật' where process_code='SOP-KD-02' and step_no=6 and coalesce(materials,'[]'::jsonb)='[]'::jsonb;
update process_steps set materials = '[]'::jsonb, output = 'HĐ nhận nuôi ký + cá thể chọn + thu tiền (custody_contracts)' where process_code='SOP-KD-03' and step_no=1 and coalesce(materials,'[]'::jsonb)='[]'::jsonb;
update process_steps set materials = '[]'::jsonb, output = 'ảnh/sự kiện + giờ live hằng tuần cập nhật' where process_code='SOP-KD-03' and step_no=2 and coalesce(materials,'[]'::jsonb)='[]'::jsonb;
update process_steps set materials = '[]'::jsonb, output = 'tin nhắn khách trả ≤24h' where process_code='SOP-KD-03' and step_no=3 and coalesce(materials,'[]'::jsonb)='[]'::jsonb;
update process_steps set materials = '[]'::jsonb, output = 'gia hạn/kết thúc + chia lợi ích' where process_code='SOP-KD-03' and step_no=4 and coalesce(materials,'[]'::jsonb)='[]'::jsonb;
update process_steps set materials = '[]'::jsonb, output = 'tuyến giao lập theo đơn/ngày' where process_code='SOP-KD-04' and step_no=1 and coalesce(materials,'[]'::jsonb)='[]'::jsonb;
update process_steps set materials = '[]'::jsonb, output = 'xuất kho theo phiếu soạn + kiểm nhiệt xe' where process_code='SOP-KD-04' and step_no=2 and coalesce(materials,'[]'::jsonb)='[]'::jsonb;
update process_steps set materials = '[]'::jsonb, output = 'giao + khách ký/ảnh xác nhận' where process_code='SOP-KD-04' and step_no=3 and coalesce(materials,'[]'::jsonb)='[]'::jsonb;
update process_steps set materials = '[]'::jsonb, output = 'trả hàng xử lý tại chỗ' where process_code='SOP-KD-04' and step_no=4 and coalesce(materials,'[]'::jsonb)='[]'::jsonb;
update process_steps set materials = '[]'::jsonb, output = 'phản hồi/khiếu nại tiếp nhận + ghi' where process_code='SOP-KD-05' and step_no=1 and coalesce(materials,'[]'::jsonb)='[]'::jsonb;
update process_steps set materials = '[]'::jsonb, output = 'phân loại + chuyển QA (nếu chất lượng) + hạn xử lý' where process_code='SOP-KD-05' and step_no=2 and coalesce(materials,'[]'::jsonb)='[]'::jsonb;
update process_steps set materials = '[]'::jsonb, output = 'trả lời khách + bồi thường theo chính sách' where process_code='SOP-KD-05' and step_no=3 and coalesce(materials,'[]'::jsonb)='[]'::jsonb;
update process_steps set materials = '[]'::jsonb, output = 'kịch bản khủng hoảng: 1 đầu mối phát ngôn, 24h' where process_code='SOP-KD-05' and step_no=4 and coalesce(materials,'[]'::jsonb)='[]'::jsonb;
update process_steps set materials = '[]'::jsonb, output = 'NPS/khiếu nại tháng tổng hợp' where process_code='SOP-KD-05' and step_no=5 and coalesce(materials,'[]'::jsonb)='[]'::jsonb;
update process_steps set materials = '[]'::jsonb, output = 'booking nhận (trực tiếp/OTA) + xác nhận + cọc' where process_code='SOP-RS-01' and step_no=1 and coalesce(materials,'[]'::jsonb)='[]'::jsonb;
update process_steps set materials = '[]'::jsonb, output = 'hướng dẫn checkin + mã khóa gửi' where process_code='SOP-RS-01' and step_no=2 and coalesce(materials,'[]'::jsonb)='[]'::jsonb;
update process_steps set materials = '[]'::jsonb, output = 'nhận phòng: khai báo lưu trú + folio PHONG' where process_code='SOP-RS-01' and step_no=3 and coalesce(materials,'[]'::jsonb)='[]'::jsonb;
update process_steps set materials = '[]'::jsonb, output = 'hỗ trợ trong kỳ + folio dịch vụ' where process_code='SOP-RS-01' and step_no=4 and coalesce(materials,'[]'::jsonb)='[]'::jsonb;
update process_steps set materials = '[]'::jsonb, output = 'trả phòng + thanh toán + đánh giá' where process_code='SOP-RS-01' and step_no=5 and coalesce(materials,'[]'::jsonb)='[]'::jsonb;
update process_steps set materials = '[]'::jsonb, output = 'phòng dọn theo checklist ảnh sau trả' where process_code='SOP-RS-02' and step_no=1 and coalesce(materials,'[]'::jsonb)='[]'::jsonb;
update process_steps set materials = '[]'::jsonb, output = 'minibar/đồ vải kiểm + báo hỏng' where process_code='SOP-RS-02' and step_no=2 and coalesce(materials,'[]'::jsonb)='[]'::jsonb;
update process_steps set materials = '[]'::jsonb, output = 'sát trùng + đặt lại tiêu chuẩn' where process_code='SOP-RS-02' and step_no=3 and coalesce(materials,'[]'::jsonb)='[]'::jsonb;
update process_steps set materials = '[]'::jsonb, output = 'phòng sạch sẵn sàng (trạng thái SAN_SANG)' where process_code='SOP-RS-02' and step_no=4 and coalesce(materials,'[]'::jsonb)='[]'::jsonb;
update process_steps set materials = '[]'::jsonb, output = 'đặt bàn/menu + số khách chốt' where process_code='SOP-RS-03' and step_no=1 and coalesce(materials,'[]'::jsonb)='[]'::jsonb;
update process_steps set materials = '[]'::jsonb, output = 'NL xuất kho theo menu×pax' where process_code='SOP-RS-03' and step_no=2 and coalesce(materials,'[]'::jsonb)='[]'::jsonb;
update process_steps set materials = '[]'::jsonb, output = 'sơ chế + kiểm nhiệt bảo quản' where process_code='SOP-RS-03' and step_no=3 and coalesce(materials,'[]'::jsonb)='[]'::jsonb;
update process_steps set materials = '[]'::jsonb, output = 'nấu theo công thức + CCP nhiệt đạt' where process_code='SOP-RS-03' and step_no=4 and coalesce(materials,'[]'::jsonb)='[]'::jsonb;
update process_steps set materials = '[]'::jsonb, output = 'lưu mẫu 24h mỗi món' where process_code='SOP-RS-03' and step_no=5 and coalesce(materials,'[]'::jsonb)='[]'::jsonb;
update process_steps set materials = '[]'::jsonb, output = 'phục vụ + ghi folio' where process_code='SOP-RS-03' and step_no=6 and coalesce(materials,'[]'::jsonb)='[]'::jsonb;
update process_steps set materials = '[]'::jsonb, output = 'rác hữu cơ thu gom → BSF (1 lần/ngày)' where process_code='SOP-RS-03' and step_no=7 and coalesce(materials,'[]'::jsonb)='[]'::jsonb;
update process_steps set materials = '[]'::jsonb, output = 'bếp vệ sinh cuối ca + checklist' where process_code='SOP-RS-03' and step_no=8 and coalesce(materials,'[]'::jsonb)='[]'::jsonb;
update process_steps set materials = '[]'::jsonb, output = 'lịch tour mở + HDV phân' where process_code='SOP-RS-04' and step_no=1 and coalesce(materials,'[]'::jsonb)='[]'::jsonb;
update process_steps set materials = '[]'::jsonb, output = 'vé bán + thu tiền' where process_code='SOP-RS-04' and step_no=2 and coalesce(materials,'[]'::jsonb)='[]'::jsonb;
update process_steps set materials = '[]'::jsonb, output = 'sát trùng giày/tay + phổ biến ATSH' where process_code='SOP-RS-04' and step_no=3 and coalesce(materials,'[]'::jsonb)='[]'::jsonb;
update process_steps set materials = '[]'::jsonb, output = 'dẫn tour 12 trạm QR, không vào lõi' where process_code='SOP-RS-04' and step_no=4 and coalesce(materials,'[]'::jsonb)='[]'::jsonb;
update process_steps set materials = '[]'::jsonb, output = 'bán chéo sản phẩm tại quầy' where process_code='SOP-RS-04' and step_no=5 and coalesce(materials,'[]'::jsonb)='[]'::jsonb;
update process_steps set materials = '[]'::jsonb, output = 'NPS thu (đánh giá ≥4/5)' where process_code='SOP-RS-04' and step_no=6 and coalesce(materials,'[]'::jsonb)='[]'::jsonb;
update process_steps set materials = '[]'::jsonb, output = 'báo giá menu×pax/gói đào tạo gửi khách' where process_code='SOP-RS-05' and step_no=1 and coalesce(materials,'[]'::jsonb)='[]'::jsonb;
update process_steps set materials = '[]'::jsonb, output = 'ký/cọc + brief + checklist chuẩn bị' where process_code='SOP-RS-05' and step_no=2 and coalesce(materials,'[]'::jsonb)='[]'::jsonb;
update process_steps set materials = '[]'::jsonb, output = 'hội trường + F&B + tài liệu sẵn sàng' where process_code='SOP-RS-05' and step_no=3 and coalesce(materials,'[]'::jsonb)='[]'::jsonb;
update process_steps set materials = '[]'::jsonb, output = 'sự kiện/lớp học điều hành' where process_code='SOP-RS-05' and step_no=4 and coalesce(materials,'[]'::jsonb)='[]'::jsonb;
update process_steps set materials = '[]'::jsonb, output = 'quyết toán + thu tiền' where process_code='SOP-RS-05' and step_no=5 and coalesce(materials,'[]'::jsonb)='[]'::jsonb;
update process_steps set materials = '[]'::jsonb, output = 'đánh giá + lưu học viên (chuỗi nhượng quyền)' where process_code='SOP-RS-05' and step_no=6 and coalesce(materials,'[]'::jsonb)='[]'::jsonb;
update process_steps set materials = '[]'::jsonb, output = 'phổ biến an toàn khi checkin (nước/động vật/máy)' where process_code='SOP-RS-06' and step_no=1 and coalesce(materials,'[]'::jsonb)='[]'::jsonb;
update process_steps set materials = '[]'::jsonb, output = 'khu vực cấm rào + biển báo + giám sát trẻ em' where process_code='SOP-RS-06' and step_no=2 and coalesce(materials,'[]'::jsonb)='[]'::jsonb;
update process_steps set materials = '[]'::jsonb, output = 'tủ sơ cứu + số khẩn cấp + người trực' where process_code='SOP-RS-06' and step_no=3 and coalesce(materials,'[]'::jsonb)='[]'::jsonb;
update process_steps set materials = '[]'::jsonb, output = 'sự cố khách: sơ cứu + ghi INCIDENT' where process_code='SOP-RS-06' and step_no=4 and coalesce(materials,'[]'::jsonb)='[]'::jsonb;
update process_steps set materials = '[]'::jsonb, output = 'diễn tập sơ tán/PCCC với khách theo lịch, sự cố = 0' where process_code='SOP-RS-06' and step_no=5 and coalesce(materials,'[]'::jsonb)='[]'::jsonb;
