"use client";
import { use, useEffect, useState } from "react";
type R = Record<string, unknown>;
const d = (v: unknown) => (v ? new Date(String(v)).toLocaleString("vi-VN", { day: "2-digit", month: "2-digit", year: "numeric", hour: "2-digit", minute: "2-digit" }) : "");
/** PORTAL KHÁCH (mobile-first, không cần tài khoản): con của tôi · sự kiện · sức khỏe · giờ xem live · nhắn tin trại */
export default function P({ params }: { params: Promise<{ token: string }> }) {
  const { token } = use(params); const [j, setJ] = useState<R | null>(null); const [msg, setMsg] = useState(""); const [err, setErr] = useState("");
  const load = () => fetch(`/api/public/custody/${token}`).then((r) => r.json()).then((x) => (x.error ? setErr("Liên kết không hợp lệ hoặc hợp đồng đã kết thúc") : setJ(x)));
  useEffect(() => { load(); }, [token]); // eslint-disable-line react-hooks/exhaustive-deps
  if (err) return <main className="min-h-screen flex items-center justify-center text-muted">{err}</main>;
  if (!j) return <main className="min-h-screen flex items-center justify-center text-muted">Đang tải…</main>;
  const c = j.contract as R; const A = (j.animals as R[]) ?? []; const E = (j.events as R[]) ?? []; const H = (j.health as R[]) ?? []; const M = (j.messages as R[]) ?? [];
  return (<main className="min-h-screen bg-brand-soft text-ink"><div className="max-w-xl mx-auto p-4 space-y-4">
    <div className="rounded-2xl bg-white p-4 shadow"><div className="text-xs uppercase tracking-widest text-brand font-bold">ITRAN FARM · chăm sóc hộ</div><h1 className="text-xl font-black">Xin chào {String(c.customer ?? "quý khách")}</h1><div className="text-sm text-muted">HĐ {String(c.id)} · gói {String(c.package ?? c.kind)} · {String(c.start_date)} → {String(c.end_date ?? "…")} · trại {String(c.farm)}</div><div className="mt-2 text-sm">🎥 Giờ xem live: <b>{(j.live_hours as string[]).join(" · ")}</b> — nhắn "xem live" bên dưới, nhân viên sẽ gọi video.</div></div>
    {A.map((a) => { const h = H.find((x) => x.animal_id === a.id); return <div key={String(a.id)} className="rounded-2xl bg-white p-4 shadow"><div className="flex items-center gap-2"><span className="text-3xl">🐄</span><div><div className="font-black text-lg">{String(a.visual_tag ?? a.id)}</div><div className="text-xs text-muted">{String(a.species)} · {String(a.breed ?? "")} · {a.sex === "F" ? "cái" : "đực"} · sinh {String(a.birth_date ?? "?")} · {String(a.status)}</div></div><div className="ml-auto text-right"><div className="text-2xl font-black">{a.last_weight_kg ? `${a.last_weight_kg} kg` : "—"}</div><div className="text-[10px] text-muted">cân {d(a.last_weight_at)}</div></div></div>
      <div className="text-xs mt-2 flex gap-3"><span>💉 vaccine gần nhất: {h?.last_vaccine ? d(h.last_vaccine) : "—"}</span><span>🩺 điều trị (tổng): {String(h?.treatments ?? 0)}</span></div>
      {Array.isArray(a.photos) && (a.photos as string[]).length > 0 && <div className="flex gap-2 mt-2 overflow-x-auto">{(a.photos as string[]).slice(-6).map((u) => <img key={u} src={u} alt="" loading="lazy" className="h-24 w-24 object-cover rounded-xl" />)}</div>}
      <div className="mt-2 max-h-56 overflow-auto text-sm">{E.filter((e) => e.animal_id === a.id).map((e, i) => <div key={i} className="border-t py-1 flex gap-2"><span className="text-xs text-muted w-28 shrink-0">{d(e.ts)}</span><span className="font-semibold">{String(e.event_type)}</span><span>{e.value ? `${e.value} ${e.unit ?? ""}` : ""}</span>{Array.isArray(e.photo_urls) && (e.photo_urls as string[]).length > 0 && <a className="underline text-xs" href={(e.photo_urls as string[])[0]} target="_blank">ảnh</a>}</div>)}{!E.some((e) => e.animal_id === a.id) && <div className="text-muted">Chưa có sự kiện 90 ngày.</div>}</div></div>; })}
    <div className="rounded-2xl bg-white p-4 shadow"><div className="font-bold">Nhắn cho trại</div><div className="flex gap-2 mt-2"><input className="flex-1 rounded-xl border px-3 py-3 text-base" placeholder="Ví dụ: cho tôi xem live lúc 15h nhé" aria-label="Ví dụ: cho tôi xem live lúc 15h nhé" value={msg} onChange={(e) => setMsg(e.target.value)} /><button className="rounded-xl bg-brand-tok text-white px-4 font-bold" onClick={async () => { if (!msg.trim()) return; await fetch(`/api/public/custody/${token}`, { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ body: msg }) }); setMsg(""); load(); }}>Gửi</button></div>
      <div className="mt-2 space-y-1 text-sm max-h-64 overflow-auto">{M.map((m) => <div key={String(m.id)} className={`rounded-xl px-3 py-2 ${m.from_customer ? "bg-brand-soft ml-8" : "bg-surface-2 mr-8"}`}><div className="text-[10px] text-muted">{m.from_customer ? "Bạn" : "Trại"} · {d(m.ts)}</div>{String(m.body)}</div>)}</div></div>
    <div className="text-center text-xs text-muted">Dữ liệu lấy trực tiếp từ sổ đàn ITRAN AGRI · truy xuất công khai · <a className="underline" href="/chuan">tiêu chuẩn ICFS</a></div>
  </div></main>);
}
